import { DayContent } from './types';

const day07: DayContent = {
  dayNumber: 7,
  title: 'Volatility Spreads & Multi-Leg Strategies',
  subtitle: 'Natenberg Chapters 7, 8, 10',
  week: 1,
  chapters: ['Chapter 7', 'Chapter 8', 'Chapter 10'],
  estimatedMinutes: 130,
  prerequisites: [1, 2, 3, 4, 5, 6],
  objectives: [
    'Construct and analyze vertical spreads, straddles, strangles, and butterflies',
    'Calculate net Greeks for multi-leg option positions',
    'Understand the risk/reward profiles of common spread strategies',
    'Identify strategies from their Greek profiles',
    'Price calendar spreads and understand their vega characteristics',
    'Perform full-chain analysis: forward pricing through BS to spread construction',
  ],
  theory: {
    sections: [
      {
        title: 'Vertical Spreads',
        blocks: [
          {
            type: 'text',
            body: 'A **vertical spread** (or "money spread") involves buying and selling options of the same type (both calls or both puts) with the same expiration but different strikes. Verticals are directional bets with capped risk and capped reward.',
          },
          {
            type: 'concept',
            title: 'Bull Call Spread',
            body: 'Buy a lower-strike call, sell a higher-strike call. Max profit $= (K_2 - K_1) - \\text{net premium}$. Max loss $= \\text{net premium}$. Delta is positive (bullish). This is equivalent to a bull put spread by put-call parity.',
          },
          {
            type: 'concept',
            title: 'Bear Put Spread',
            body: 'Buy a higher-strike put, sell a lower-strike put. Max profit $= (K_2 - K_1) - \\text{net premium}$. Max loss $= \\text{net premium}$. Delta is negative (bearish).',
          },
          {
            type: 'example',
            title: 'Bull Call Spread Pricing',
            problem: 'Buy the 100 call at $5.00, sell the 110 call at $2.00. What is the max profit, max loss, and breakeven?',
            solution: [
              'Net premium paid $= 5.00 - 2.00 = \\$3.00$.',
              'Max profit $= (110 - 100) - 3.00 = \\$7.00$ (if $S_T \\geq 110$).',
              'Max loss $= \\$3.00$ (if $S_T \\leq 100$).',
              'Breakeven $= 100 + 3.00 = \\$103.00$.',
            ],
          },
          {
            type: 'callout',
            variant: 'tip',
            body: 'Vertical spreads reduce vega exposure compared to naked options. The long and short legs partially offset each other\'s vega. This makes verticals useful when you have a directional view but do not want large vol exposure.',
          },
        ],
      },
      {
        title: 'Straddles & Strangles',
        blocks: [
          {
            type: 'text',
            body: '**Straddles** and **strangles** are volatility bets. A straddle (long call + long put, same strike) profits from large moves in either direction. A strangle (long OTM call + long OTM put) is similar but cheaper, requiring a larger move to profit.',
          },
          {
            type: 'formula',
            latex: '\\text{Straddle price} = C(K) + P(K) \\approx 0.8 \\cdot S \\cdot \\sigma \\cdot \\sqrt{T}',
            label: 'ATM Straddle Approximation',
            explanation: 'For ATM straddles with $r \\approx 0$: the straddle price is approximately proportional to $S$, $\\sigma$, and $\\sqrt{T}$.',
          },
          {
            type: 'concept',
            title: 'Straddle Greeks',
            body: 'An ATM straddle has: delta $\\approx 0$ (the call and put deltas roughly cancel), gamma $= 2\\Gamma_{\\text{single}}$ (double the gamma of one option), theta $= 2\\Theta_{\\text{single}}$ (double the theta), vega $= 2\\mathcal{V}_{\\text{single}}$ (double the vega). A straddle is a pure volatility bet.',
          },
          {
            type: 'callout',
            variant: 'key-insight',
            body: 'The break-even move for a straddle is approximately the straddle price itself. If a 1-month ATM straddle costs $5 on a $100 stock, the stock needs to move about $\\pm 5\\%$ (about $\\$5$) for the buyer to break even. The implied daily move is straddle price $/ \\sqrt{T_{\\text{days}}}$.',
          },
        ],
      },
      {
        title: 'Butterflies & Condors',
        blocks: [
          {
            type: 'text',
            body: 'A **butterfly** is a three-strike spread: buy 1 low-strike, sell 2 middle-strike, buy 1 high-strike (all calls or all puts, equally spaced). It profits from the stock staying near the middle strike. A **condor** is a four-strike version, providing a wider profit zone.',
          },
          {
            type: 'formula',
            latex: '\\text{Long butterfly} = C(K_1) - 2C(K_2) + C(K_3)',
            label: 'Butterfly Payoff',
            explanation: 'Where $K_1 < K_2 < K_3$ and $K_2 = (K_1 + K_3)/2$. Max payoff $= K_2 - K_1$ at $S_T = K_2$. Max loss $= \\text{premium paid}$.',
          },
          {
            type: 'concept',
            title: 'Butterfly Greeks',
            body: 'A long butterfly has: near-zero delta (if centered ATM), negative gamma (short vol), positive theta (collect time decay), negative vega (benefits from vol decrease). A butterfly is effectively a short-vol bet with limited risk.',
          },
          {
            type: 'example',
            title: 'Iron Butterfly Pricing',
            problem: 'ATM strike $K = 100$. Buy the 95 put at $1.50$, sell the 100 put at $3.50$, sell the 100 call at $4.00$, buy the 105 call at $2.00$. What is the net credit and max profit?',
            solution: [
              'Net credit $= (3.50 + 4.00) - (1.50 + 2.00) = 7.50 - 3.50 = \\$4.00$.',
              'Max profit $= \\$4.00$ (if $S_T = 100$ at expiry, all options expire worthless except the short ATM, which are at-the-money).',
              'Max loss $= (K_2 - K_1) - \\text{credit} = 5 - 4 = \\$1.00$ (if $S_T \\leq 95$ or $S_T \\geq 105$).',
              'Breakevens: $100 \\pm 4 = \\$96$ and $\\$104$.',
            ],
          },
        ],
      },
      {
        title: 'Calendar Spreads (Time Spreads)',
        blocks: [
          {
            type: 'text',
            body: 'A **calendar spread** involves buying and selling the same strike but different expirations. Typically: sell the near-dated option and buy the far-dated option. Calendar spreads are primarily vega trades: they profit when implied vol increases.',
          },
          {
            type: 'concept',
            title: 'Calendar Spread Greeks',
            body: 'A long calendar spread (short near-term, long far-term) has: near-zero delta (if ATM), negative gamma (short the high-gamma near-term option), positive theta (the near-term decays faster), positive vega (the far-term has more vega than the near-term). The key driver is vega: the far-dated leg has more vega, so a vol increase benefits the position.',
          },
          {
            type: 'callout',
            variant: 'warning',
            body: 'Calendar spreads have a hidden risk: if the vol term structure shifts (e.g., near-term vol spikes while far-term stays flat), the spread can lose money even if overall vol increases. This is term structure risk, not captured by a single vega number.',
          },
        ],
      },
      {
        title: 'Ratio Spreads & Risk Reversals',
        blocks: [
          {
            type: 'text',
            body: 'A **ratio spread** involves buying and selling different quantities of options at different strikes (e.g., buy 1 ATM call, sell 2 OTM calls). A **risk reversal** (or "combo") is a long OTM call + short OTM put (or vice versa), creating a synthetic directional position with skew exposure.',
          },
          {
            type: 'concept',
            title: 'Ratio Spread: 1x2 Call Spread',
            body: 'Buy 1 lower-strike call, sell 2 higher-strike calls. Net position is long 1 vertical + short 1 naked call. Below $K_1$: zero. Between $K_1$ and $K_2$: gains. Above $K_2$: gains decrease and eventually become losses (unlimited on the upside). The position can often be put on for zero or small net premium.',
          },
          {
            type: 'concept',
            title: 'Risk Reversal',
            body: 'Long OTM call + Short OTM put (bullish risk reversal). Delta-wise this is similar to a long stock position. The key feature is that the cost depends heavily on the volatility skew. In equity markets, puts usually have higher implied vol than calls (downside skew), so a bullish risk reversal often generates a net credit.',
          },
        ],
      },
    ],
  },
  exercises: [
    // --- EASY (5) ---
    {
      id: 'd7-spread-01',
      exerciseType: 'numeric',
      difficulty: 'easy',
      topic: 'vertical-spreads',
      tags: ['spreads', 'vertical', 'call-spread'],
      timeEstimateSeconds: 60,
      question: 'You buy the 50 call at $3.00 and sell the 55 call at $1.50. What is the maximum profit of this bull call spread?',
      correctAnswer: 3.50,
      tolerance: 0.01,
      unit: '$',
      explanation: 'Max profit $= (55 - 50) - (3.00 - 1.50) = 5.00 - 1.50 = \\$3.50$ (at $S_T \\geq 55$).',
      solutionSteps: [
        'Net premium paid $= 3.00 - 1.50 = \\$1.50$.',
        'Width of spread $= 55 - 50 = \\$5.00$.',
        'Max profit $= \\$5.00 - \\$1.50 = \\$3.50$.',
      ],
    },
    {
      id: 'd7-spread-02',
      exerciseType: 'numeric',
      difficulty: 'easy',
      topic: 'straddle',
      tags: ['spreads', 'straddle'],
      timeEstimateSeconds: 45,
      question: 'An ATM straddle (100-strike) costs $8.00. What are the two breakeven stock prices at expiry?',
      correctAnswer: 108,
      tolerance: 0.01,
      unit: '$ (upper breakeven)',
      hint: 'Breakevens are $K \\pm \\text{straddle price}$.',
      explanation: 'Upper breakeven $= 100 + 8 = 108$. Lower breakeven $= 100 - 8 = 92$.',
      solutionSteps: [
        'A straddle profits if the stock moves more than the straddle price from the strike.',
        'Upper breakeven $= K + \\text{straddle price} = 100 + 8 = \\$108$.',
        'Lower breakeven $= K - \\text{straddle price} = 100 - 8 = \\$92$.',
      ],
    },
    {
      id: 'd7-spread-03',
      exerciseType: 'multiple-choice',
      difficulty: 'easy',
      topic: 'butterfly',
      tags: ['spreads', 'butterfly'],
      timeEstimateSeconds: 30,
      question: 'A long butterfly spread profits most when:',
      options: [
        'The stock makes a large move in either direction',
        'The stock stays near the middle strike at expiry',
        'Implied volatility increases',
        'Interest rates increase',
      ],
      correctIndex: 1,
      explanation: 'A long butterfly has maximum profit when $S_T$ equals the middle strike. It is a short-vol position (profits from the stock staying put).',
      solutionSteps: [
        'Long butterfly: buy wings, sell body.',
        'Max payoff at $S_T = K_{\\text{middle}}$.',
        'Short gamma, positive theta: profits from no movement.',
        'Negative vega: benefits from vol decrease.',
      ],
    },
    {
      id: 'd7-spread-04',
      exerciseType: 'true-false',
      difficulty: 'easy',
      topic: 'straddle',
      tags: ['spreads', 'straddle', 'greeks'],
      timeEstimateSeconds: 20,
      statement: 'An ATM straddle has approximately zero delta.',
      correct: true,
      explanation: 'ATM call delta $\\approx +0.50$, ATM put delta $\\approx -0.50$. Combined: $0.50 + (-0.50) = 0$. The straddle is delta-neutral, making it a pure vol bet.',
      solutionSteps: [
        'Straddle $= $ call $+$ put at the same strike.',
        '$\\Delta_{\\text{straddle}} = \\Delta_C + \\Delta_P = N(d_1) + (N(d_1) - 1)$',
        'For ATM: $\\approx 0.50 + (-0.50) = 0$.',
      ],
    },
    {
      id: 'd7-spread-05',
      exerciseType: 'numeric',
      difficulty: 'easy',
      topic: 'vertical-spreads',
      tags: ['spreads', 'vertical', 'put-spread'],
      timeEstimateSeconds: 45,
      question: 'You buy the 60 put at $4.00 and sell the 55 put at $1.50. What is the maximum loss?',
      correctAnswer: 2.50,
      tolerance: 0.01,
      unit: '$',
      explanation: 'Net premium paid $= 4.00 - 1.50 = \\$2.50$. Max loss is the premium paid (if $S_T \\geq 60$).',
      solutionSteps: [
        'This is a bear put spread (bearish).',
        'Net premium $= 4.00 - 1.50 = \\$2.50$.',
        'Max loss $= \\$2.50$ (if both puts expire worthless, $S_T \\geq 60$).',
        'Max profit $= (60 - 55) - 2.50 = \\$2.50$ (if $S_T \\leq 55$).',
      ],
    },
    // --- MEDIUM (6) ---
    {
      id: 'd7-spread-06',
      exerciseType: 'multi-step',
      difficulty: 'medium',
      topic: 'spread-greeks',
      tags: ['spreads', 'greeks', 'straddle'],
      timeEstimateSeconds: 120,
      question: 'An ATM straddle at strike 100: call has $\\Delta = 0.55$, $\\Gamma = 0.03$, $\\Theta = -0.05$/day, $\\mathcal{V} = 0.20$. Put has $\\Delta = -0.45$, same $\\Gamma$, $\\Theta = -0.04$/day, same $\\mathcal{V}$. Compute the straddle Greeks.',
      steps: [
        {
          prompt: 'What is the straddle delta?',
          correctAnswer: 0.10,
          tolerance: 0.01,
          stepExplanation: '$\\Delta_{\\text{straddle}} = 0.55 + (-0.45) = 0.10$',
        },
        {
          prompt: 'What is the straddle gamma?',
          correctAnswer: 0.06,
          tolerance: 0.001,
          stepExplanation: '$\\Gamma_{\\text{straddle}} = 0.03 + 0.03 = 0.06$',
        },
        {
          prompt: 'What is the straddle daily theta?',
          correctAnswer: -0.09,
          tolerance: 0.005,
          unit: '$/day',
          stepExplanation: '$\\Theta_{\\text{straddle}} = -0.05 + (-0.04) = -0.09$/day',
        },
        {
          prompt: 'What is the straddle vega?',
          correctAnswer: 0.40,
          tolerance: 0.01,
          stepExplanation: '$\\mathcal{V}_{\\text{straddle}} = 0.20 + 0.20 = 0.40$',
        },
      ],
      explanation: 'Spread Greeks are simply the sum of individual leg Greeks (with appropriate signs for long/short).',
      solutionSteps: [
        '$\\Delta = 0.55 + (-0.45) = 0.10$ (slightly long because call delta slightly exceeds 0.50)',
        '$\\Gamma = 0.03 + 0.03 = 0.06$ (double the single-option gamma)',
        '$\\Theta = -0.05 + (-0.04) = -0.09$/day (double the theta)',
        '$\\mathcal{V} = 0.20 + 0.20 = 0.40$ (double the vega)',
      ],
    },
    {
      id: 'd7-spread-07',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'butterfly',
      tags: ['spreads', 'butterfly', 'pricing'],
      timeEstimateSeconds: 90,
      question: 'Price a call butterfly: buy 95 call at $8.50, sell 2x 100 calls at $5.00 each, buy 105 call at $2.50. What is the net cost and maximum payoff?',
      correctAnswer: 1.00,
      tolerance: 0.01,
      unit: '$ (net cost)',
      explanation: 'Net cost $= 8.50 - 2(5.00) + 2.50 = 8.50 - 10.00 + 2.50 = \\$1.00$. Max payoff $= 5.00 - 1.00 = \\$4.00$ at $S_T = 100$.',
      solutionSteps: [
        'Net premium $= 8.50 - 2(5.00) + 2.50 = 1.00$.',
        'Max payoff at $S_T = 100$: long 95C pays $5, short 100Cs and long 105C all at $0.',
        'Net payoff $= 5 - 0 + 0 = 5$. Profit $= 5 - 1 = \\$4$.',
        'Max loss $= \\$1.00$ (premium paid, when $S_T \\leq 95$ or $S_T \\geq 105$).',
      ],
    },
    {
      id: 'd7-spread-08',
      exerciseType: 'free-response',
      difficulty: 'medium',
      topic: 'calendar-spread',
      tags: ['spreads', 'calendar', 'vega'],
      timeEstimateSeconds: 120,
      question: 'Explain why a long calendar spread (sell near-term, buy far-term, same strike) is a long vega position. Under what market conditions does it perform best?',
      modelAnswer: 'A long calendar spread is long vega because the far-dated option has more vega than the near-dated option (vega scales with $\\sqrt{T}$). When vol rises, the far-dated leg gains more than the near-dated leg loses, generating a net profit. It performs best when: (1) implied vol increases (the vega effect), and (2) the stock stays near the strike (both options are ATM, where vega is highest). It also benefits from the near-term option decaying faster than the far-term (theta benefit). The worst scenario is a large stock move away from the strike (both options go OTM/ITM, reducing time value) combined with a vol decrease.',
      explanation: 'Calendar spreads are long vega because far-dated options have more vega than near-dated options.',
      solutionSteps: [
        'Far-dated option vega $> $ near-dated option vega (since $\\mathcal{V} \\propto \\sqrt{T}$).',
        'Net vega $= \\mathcal{V}_{\\text{far}} - \\mathcal{V}_{\\text{near}} > 0$ (long vega).',
        'Profits from: vol increase, stock staying near strike, near-term theta decay.',
        'Worst case: large move away from strike + vol decrease.',
      ],
    },
    {
      id: 'd7-spread-09',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'spread-greeks',
      tags: ['spreads', 'vertical', 'greeks'],
      timeEstimateSeconds: 90,
      question: 'A bull call spread: long 100C ($\\Delta = 0.60$, $\\Gamma = 0.03$, $\\mathcal{V} = 0.18$), short 110C ($\\Delta = 0.35$, $\\Gamma = 0.025$, $\\mathcal{V} = 0.15$). What is the spread vega?',
      correctAnswer: 0.03,
      tolerance: 0.005,
      explanation: 'Spread vega $= 0.18 - 0.15 = 0.03$. The spread has a small long vega exposure.',
      solutionSteps: [
        'Long 100C vega: $+0.18$.',
        'Short 110C vega: $-0.15$.',
        'Net vega $= 0.18 - 0.15 = 0.03$.',
        'The spread has residual vega exposure but much less than a single leg.',
      ],
    },
    {
      id: 'd7-spread-10',
      exerciseType: 'multiple-choice',
      difficulty: 'medium',
      topic: 'risk-reversal',
      tags: ['spreads', 'risk-reversal', 'skew'],
      timeEstimateSeconds: 45,
      question: 'In equity markets with typical downside skew, a bullish risk reversal (long OTM call, short OTM put) usually:',
      options: [
        'Costs money (net debit) because the call is more expensive',
        'Generates a credit because the put (higher implied vol) is more expensive than the call',
        'Costs nothing because the payoffs are symmetric',
        'Depends only on the risk-free rate, not on skew',
      ],
      correctIndex: 1,
      explanation: 'In equity markets, OTM puts trade at higher implied vol than equidistant OTM calls (downside skew). So the put premium exceeds the call premium, and selling the put while buying the call generates a net credit.',
      solutionSteps: [
        'Equity skew: OTM put IV > OTM call IV (downside protection is expensive).',
        'Selling the OTM put generates more premium than buying the OTM call costs.',
        'Net result: credit for a bullish risk reversal.',
        'The skew compensates the put seller for taking crash risk.',
      ],
    },
    {
      id: 'd7-spread-11',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'straddle',
      tags: ['spreads', 'straddle', 'pricing'],
      timeEstimateSeconds: 60,
      question: 'Using the ATM straddle approximation $\\approx 0.8 S \\sigma \\sqrt{T}$: estimate the price of a 30-day ATM straddle on a $75 stock with 35% implied vol. ($\\sqrt{30/365} \\approx 0.287$.)',
      correctAnswer: 6.03,
      tolerance: 0.2,
      unit: '$',
      explanation: '$\\text{Straddle} \\approx 0.8 \\times 75 \\times 0.35 \\times 0.287 = 0.8 \\times 75 \\times 0.1005 = 6.03$.',
      solutionSteps: [
        '$\\text{Straddle} \\approx 0.8 S \\sigma \\sqrt{T}$',
        '$= 0.8 \\times 75 \\times 0.35 \\times \\sqrt{30/365}$',
        '$= 0.8 \\times 75 \\times 0.35 \\times 0.287 = 6.03$',
        'The implied daily move is about $6.03/\\sqrt{30} \\approx \\$1.10$.',
      ],
    },
    // --- HARD (5) ---
    {
      id: 'd7-spread-12',
      exerciseType: 'multi-step',
      difficulty: 'hard',
      topic: 'spread-pnl',
      tags: ['spreads', 'butterfly', 'pnl'],
      timeEstimateSeconds: 180,
      question: 'A call butterfly: long 1x 95C, short 2x 100C, long 1x 105C. Cost: $1.50. Compute the P&L at expiry for: (a) $S_T = 100$, (b) $S_T = 97$, (c) $S_T = 110$.',
      steps: [
        {
          prompt: 'P&L at $S_T = 100$?',
          correctAnswer: 3.50,
          tolerance: 0.01,
          unit: '$',
          stepExplanation: 'Payoff: 95C pays $5, 100Cs pay $0, 105C pays $0. Net payoff $= 5$. P&L $= 5 - 1.50 = \\$3.50$.',
        },
        {
          prompt: 'P&L at $S_T = 97$?',
          correctAnswer: 0.50,
          tolerance: 0.01,
          unit: '$',
          stepExplanation: 'Payoff: 95C pays $2, 100Cs pay $0, 105C pays $0. Net payoff $= 2$. P&L $= 2 - 1.50 = \\$0.50$.',
        },
        {
          prompt: 'P&L at $S_T = 110$?',
          correctAnswer: -1.50,
          tolerance: 0.01,
          unit: '$',
          stepExplanation: 'Payoff: 95C pays $15, 100Cs pay $-20$ (short 2x $10 each), 105C pays $5. Net $= 15 - 20 + 5 = 0$. P&L $= 0 - 1.50 = -\\$1.50$.',
        },
      ],
      explanation: 'The butterfly has max profit at the body strike, small profit in the wings, and max loss outside the wings.',
      solutionSteps: [
        '$S_T = 100$: payoff $= (100-95) - 2(0) + 0 = 5$. P&L $= 5 - 1.50 = 3.50$.',
        '$S_T = 97$: payoff $= (97-95) - 2(0) + 0 = 2$. P&L $= 2 - 1.50 = 0.50$.',
        '$S_T = 110$: payoff $= (110-95) - 2(110-100) + (110-105) = 15-20+5 = 0$. P&L $= -1.50$.',
      ],
    },
    {
      id: 'd7-spread-13',
      exerciseType: 'scenario',
      difficulty: 'hard',
      topic: 'spread-greeks',
      tags: ['spreads', 'straddle', 'greeks', 'pnl'],
      timeEstimateSeconds: 180,
      question: 'You are long 10 ATM straddles. Per straddle: $\\Gamma = 0.06$, daily $\\Theta = -\\$0.10$, $\\mathcal{V} = 0.40$. Compute the portfolio P&L under each scenario (1-day changes).',
      scenarios: [
        {
          description: 'Stock moves +$3, vol unchanged',
          shocks: [{ variable: 'stock', change: 3 }],
          expectedAnswer: 1.70,
          tolerance: 0.2,
          unit: '$',
        },
        {
          description: 'Stock flat, vol drops 2 points',
          shocks: [{ variable: 'implied_vol', change: -2 }],
          expectedAnswer: -9.0,
          tolerance: 0.5,
          unit: '$',
        },
        {
          description: 'Stock moves +$5, vol increases 1 point',
          shocks: [{ variable: 'stock', change: 5 }],
          expectedAnswer: 11.50,
          tolerance: 1.0,
          unit: '$',
        },
      ],
      explanation: 'P&L = gamma P&L + vega P&L + theta. Each Greek contribution is additive.',
      solutionSteps: [
        'Position: $10 \\times$ straddle. $\\Gamma_{\\text{pos}} = 10 \\times 0.06 = 0.60$, $\\Theta_{\\text{pos}} = 10 \\times (-0.10) = -1.00$/day, $\\mathcal{V}_{\\text{pos}} = 10 \\times 0.40 = 4.0$.',
        '+$3, vol flat: $\\frac{1}{2}(0.60)(9) + 0 + (-1.00) = 2.70 - 1.00 = 1.70$.',
        'Flat, vol $-2$: $0 + 4.0 \\times (-2) + (-1.00) = -8.00 - 1.00 = -9.00$.',
        '+$5, vol $+1$: $\\frac{1}{2}(0.60)(25) + 4.0(1) + (-1.00) = 7.50 + 4.00 - 1.00 = 10.50$.',
      ],
    },
    {
      id: 'd7-spread-14',
      exerciseType: 'free-response',
      difficulty: 'hard',
      topic: 'strategy-identification',
      tags: ['spreads', 'greeks', 'identification'],
      timeEstimateSeconds: 150,
      question: 'A portfolio has: delta $\\approx 0$, gamma $< 0$, theta $> 0$, vega $< 0$. What strategy is this most likely? Describe its risk profile and when it performs well.',
      modelAnswer: 'This is a short volatility position, most likely a short straddle, short strangle, or long butterfly (iron condor). Delta neutral means no directional bet. Negative gamma means large moves hurt. Positive theta means it profits from time decay. Negative vega means it profits from vol decrease. Risk profile: limited profit (theta collected), unlimited loss potential (for short straddle/strangle; limited for butterfly). Performs best when the stock stays in a narrow range and implied vol decreases. Worst case: large stock move or vol spike. This is the classic "collect pennies in front of a steamroller" profile that market makers often run (but with sophisticated risk management).',
      explanation: 'Delta-neutral, short gamma, long theta, short vega = short volatility position (short straddle/strangle or long butterfly).',
      solutionSteps: [
        '$\\Delta \\approx 0$: no directional bias.',
        '$\\Gamma < 0$: loses on large moves (short convexity).',
        '$\\Theta > 0$: profits from time passing (collecting decay).',
        '$\\mathcal{V} < 0$: profits from vol decrease.',
        'Strategy: short straddle, short strangle, or long butterfly/condor.',
        'Best scenario: quiet market, declining vol. Worst: gap move or vol spike.',
      ],
    },
    {
      id: 'd7-spread-15',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'ratio-spread',
      tags: ['spreads', 'ratio', 'pricing'],
      timeEstimateSeconds: 120,
      question: 'A 1x2 call ratio spread: buy 1x 100C at $5.00, sell 2x 110C at $2.00 each. What is the net premium, the P&L at $S_T = 110$, and at $S_T = 125$?',
      correctAnswer: 1.0,
      tolerance: 0.01,
      unit: '$ (net credit)',
      explanation: 'Net credit $= 2(2.00) - 5.00 = -1.00$. Actually: $-5.00 + 2(2.00) = -1.00$. Net debit of $1.00.',
      solutionSteps: [
        'Net premium: buy 100C ($-5.00$), sell 2x 110C ($+4.00$). Net $= -1.00$ (debit of $\\$1.00$).',
        '$S_T = 110$: 100C pays $10, 110Cs pay $0. Payoff $= 10$. P&L $= 10 - 1 = +\\$9.00$.',
        '$S_T = 125$: 100C pays $25, 110Cs pay $-2 \\times 15 = -30$. Net payoff $= 25 - 30 = -5$. P&L $= -5 - 1 = -\\$6.00$.',
        'Breakevens: lower $= 101$ ($100 + 1$ debit). Upper $= 119$ ($110 + 9$ max payoff above $K_2$: solve $S - 100 - 2(S - 110) + 1 = 0 \\Rightarrow -S + 121 = 0 \\Rightarrow S = 121$).',
      ],
    },
    {
      id: 'd7-spread-16',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'straddle',
      tags: ['spreads', 'straddle', 'implied-move'],
      timeEstimateSeconds: 90,
      question: 'A 7-day ATM straddle on a $200 stock costs $12. What is the implied daily move? What is the annualized implied volatility?',
      correctAnswer: 4.54,
      tolerance: 0.2,
      unit: '$ (implied daily move)',
      explanation: 'Implied move over $T$ days $= \\text{straddle price}$. Daily implied move $= 12/\\sqrt{7} = 12/2.646 = \\$4.54$. Annualized implied vol: daily vol $= 4.54/200 = 2.27\\%$. Annual $= 2.27\\% \\times \\sqrt{252} = 36.0\\%$.',
      solutionSteps: [
        'Straddle $\\approx $ expected move over $T$ days.',
        'Daily implied move $= \\text{straddle}/\\sqrt{T_{\\text{days}}} = 12/\\sqrt{7} = 12/2.646 = \\$4.54$.',
        'Daily implied vol $= 4.54/200 = 2.27\\%$.',
        'Annualized: $2.27\\% \\times \\sqrt{252} = 36.0\\%$.',
      ],
    },
    // --- INTERVIEW (3) ---
    {
      id: 'd7-spread-17',
      exerciseType: 'speed-drill',
      difficulty: 'interview',
      topic: 'spread-mental-math',
      tags: ['spreads', 'mental-math'],
      timeEstimateSeconds: 90,
      timeLimitSeconds: 90,
      problems: [
        { prompt: 'Bull call spread: buy 100C at $6, sell 105C at $3. Max profit?', correctAnswer: 2.0, tolerance: 0.1 },
        { prompt: 'ATM straddle costs $10 on $100 stock. Breakevens?', correctAnswer: 110.0, tolerance: 0.1 },
        { prompt: 'Butterfly 95/100/105: costs $1.50. Max profit?', correctAnswer: 3.50, tolerance: 0.1 },
        { prompt: 'Straddle approx: S=$100, sigma=24%, T=1mo (sqrt(1/12)=0.289)?', correctAnswer: 5.55, tolerance: 0.3 },
        { prompt: 'Put delta = -0.30, call delta = 0.70. Straddle delta?', correctAnswer: 0.40, tolerance: 0.01 },
      ],
      explanation: 'Quick spread pricing and Greek computations for interviews.',
      solutionSteps: [
        'Bull call: max profit $= 5 - 3 = 2$',
        'Straddle breakevens: $100 \\pm 10 = 90, 110$ (upper $= 110$)',
        'Butterfly max profit $= 5 - 1.50 = 3.50$',
        'Straddle $\\approx 0.8 \\times 100 \\times 0.24 \\times 0.289 = 5.55$',
        'Straddle delta $= 0.70 + (-0.30) = 0.40$ (this is not ATM since delta is skewed)',
      ],
    },
    {
      id: 'd7-spread-18',
      exerciseType: 'free-response',
      difficulty: 'interview',
      topic: 'strategy-selection',
      tags: ['spreads', 'interview', 'strategy'],
      timeEstimateSeconds: 120,
      question: 'Interview: "You think a stock will stay between $95 and $105 over the next month. Current price is $100. How would you express this view with options, and what are the risks?"',
      modelAnswer: 'Sell an ATM straddle or sell a strangle (e.g., sell the 95P and 105C). Alternatively, buy a butterfly or iron condor centered at 100. The straddle sale has the highest premium but unlimited risk. The butterfly/condor has limited risk but lower max profit. Best choice: iron condor (sell 95P/105C, buy 90P/110C) for defined risk. Greeks: short gamma (lose on moves beyond range), long theta (profit from time decay), short vega (profit if vol drops). Key risks: (1) Large gap move beyond the expected range, (2) Vol spike increasing the value of options you sold, (3) Pin risk near expiry if stock is at a short strike. Risk management: define max loss with wings (buy further OTM options), monitor position size, set stop-loss levels.',
      explanation: 'Range-bound view = short vol. Express via short straddle/strangle, butterfly, or iron condor.',
      solutionSteps: [
        'Range-bound view $\\Rightarrow$ short volatility strategy.',
        'Options: (a) Short straddle (aggressive), (b) Short strangle (moderate), (c) Iron condor (defined risk).',
        'Iron condor: sell 95P/105C, buy 90P/110C. Max profit $=$ net credit. Max loss $=$ width $-$ credit.',
        'Greeks: short $\\Gamma$, long $\\Theta$, short $\\mathcal{V}$.',
        'Risks: gap moves, vol spikes, pin risk.',
      ],
    },
    {
      id: 'd7-spread-19',
      exerciseType: 'free-response',
      difficulty: 'interview',
      topic: 'full-chain',
      tags: ['spreads', 'bs', 'greeks', 'forward', 'interview'],
      timeEstimateSeconds: 180,
      question: 'Interview: Walk through the full chain of options analysis for a stock at $100, 3 months to expiry, 25% vol, 5% rate. Start from the forward price, compute approximate BS prices for the ATM straddle, describe the key Greeks, and explain how you would delta-hedge the position.',
      modelAnswer: 'Step 1 (Forward): $F = 100 e^{0.05 \\times 0.25} = 100 \\times 1.0126 = \\$101.26$. Step 2 (BS Pricing): ATM call $\\approx 0.4 \\times 100 \\times 0.25 \\times 0.50 = \\$5.00$. Put via parity: $P = C - S + Ke^{-rT} = 5.00 - 100 + 98.76 = \\$3.76$. Straddle $\\approx 5.00 + 3.76 = \\$8.76$. Step 3 (Greeks): Call delta $\\approx 0.55$, straddle delta $\\approx 0.10$ (slightly positive due to rates). Straddle gamma $\\approx 2 \\times 0.032 = 0.064$. Straddle vega $\\approx 2 \\times 0.20 = 0.40$. Daily theta $\\approx -\\$0.10$. Step 4 (Hedging): Sell 10 shares to offset the 0.10 delta. Rebalance as delta changes. P&L depends on realized vol vs. 25% implied. If realized > 25%, profit (gamma P&L > theta). If realized < 25%, lose.',
      explanation: 'This exercise combines every concept from Days 1-7: forward pricing, BS, Greeks, delta hedging, and vol trading.',
      solutionSteps: [
        'Forward: $F = 100 e^{0.0125} = 101.26$',
        'ATM call $\\approx 0.4 \\times 100 \\times 0.25 \\times 0.50 = \\$5.00$',
        'Put $= C - S + Ke^{-rT} = 5.00 - 100 + 98.76 = \\$3.76$',
        'Straddle $\\approx \\$8.76$. Delta $\\approx 0.10$. Gamma $\\approx 0.064$. Vega $\\approx 0.40$.',
        'Hedge: sell 10 shares. Rebalance daily. P&L driven by realized vs. implied vol.',
      ],
    },
  ],
  cumulativeExercises: [
    {
      id: 'd7-cum-01',
      exerciseType: 'multi-step',
      difficulty: 'hard',
      topic: 'full-chain',
      tags: ['forward', 'bs', 'put-call-parity', 'greeks', 'spreads'],
      timeEstimateSeconds: 300,
      fromDay: 1,
      question: 'Complete chain: $S = 100$, $K_1 = 95$, $K_2 = 105$, $T = 0.5$, $r = 4\\%$, $\\sigma = 25\\%$. (a) Forward price. (b) Approximate 95C price using BS. (c) 105C price. (d) Net delta of the bull call spread (long 95C, short 105C).',
      steps: [
        {
          prompt: 'What is the 6-month forward price?',
          correctAnswer: 102.02,
          tolerance: 0.1,
          unit: '$',
          stepExplanation: '$F = 100 e^{0.04 \\times 0.5} = 100 e^{0.02} = 102.02$.',
        },
        {
          prompt: 'Approximate the 95-strike call price. (Hint: this is 5% ITM. Use intrinsic + time value estimate.)',
          correctAnswer: 9.5,
          tolerance: 1.5,
          unit: '$',
          stepExplanation: 'Intrinsic $\\approx S - Ke^{-rT} = 100 - 93.12 = 6.88$. Time value for near-ATM $\\approx 0.4 \\times 100 \\times 0.25 \\times 0.707 \\times 0.8 \\approx 5.66 \\times 0.8 = 4.53$. Rough total $\\approx 11.4$. (Exact BS gives about $10.5$.)',
        },
        {
          prompt: 'Approximate the 105-strike call price. (OTM, lower delta.)',
          correctAnswer: 4.5,
          tolerance: 1.5,
          unit: '$',
          stepExplanation: 'This is 5% OTM. Time value for near-ATM $\\approx 5.66 \\times 0.7 \\approx 3.96$. (Exact BS gives about $4.0$.)',
        },
        {
          prompt: 'Estimate the net delta of the bull call spread (long 95C, short 105C). ITM delta $\\approx 0.70$, OTM delta $\\approx 0.35$.',
          correctAnswer: 0.35,
          tolerance: 0.1,
          stepExplanation: 'Net delta $= 0.70 - 0.35 = 0.35$. The spread is directionally bullish.',
        },
      ],
      explanation: 'This exercise chains forward pricing, BS pricing, and spread construction across all prior days.',
      solutionSteps: [
        '$F = 100 e^{0.02} = 102.02$',
        '95C: ITM, delta $\\approx 0.70$. Price includes intrinsic + time value $\\approx \\$10.5$.',
        '105C: OTM, delta $\\approx 0.35$. Price is pure time value $\\approx \\$4.0$.',
        'Spread delta $= 0.70 - 0.35 = 0.35$.',
      ],
    },
    {
      id: 'd7-cum-02',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'pde-and-spreads',
      tags: ['greeks', 'pde', 'straddle', 'gamma', 'theta'],
      timeEstimateSeconds: 120,
      fromDay: 6,
      question: 'A long ATM straddle on a $100 stock has position gamma $= 0.08$ and $\\sigma = 30\\%$. Using the gamma-theta relationship ($\\Theta \\approx -\\frac{1}{2}\\sigma^2 S^2 \\Gamma$), compute the annual and daily theta for the straddle.',
      correctAnswer: -0.0986,
      tolerance: 0.005,
      unit: '$ per day',
      explanation: '$|\\Theta_{\\text{annual}}| = \\frac{1}{2}(0.09)(10000)(0.08) = 36.0$. Daily $= 36.0/365 = 0.0986$. Theta $= -\\$0.099$ per day.',
      solutionSteps: [
        '$\\Theta_{\\text{annual}} = -\\frac{1}{2}\\sigma^2 S^2 \\Gamma = -\\frac{1}{2}(0.09)(10000)(0.08) = -36.0$',
        '$\\Theta_{\\text{daily}} = -36.0/365 = -0.0986$',
        'The straddle decays about $\\$0.10$ per day.',
        'Break-even daily move: $\\sqrt{2 \\times 0.099/0.08} = \\sqrt{2.47} = \\$1.57$.',
      ],
    },
    {
      id: 'd7-cum-03',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'ev-and-straddle',
      tags: ['ev', 'straddle', 'implied-move'],
      timeEstimateSeconds: 90,
      fromDay: 3,
      question: 'A 1-month ATM straddle costs $6 on a $100 stock. Assuming the stock\'s move over the month follows a symmetric distribution, what is the market-implied expected absolute move $E[|S_T - S_0|]$?',
      correctAnswer: 6.0,
      tolerance: 0.1,
      unit: '$',
      explanation: 'The straddle payoff $= |S_T - K|$ (for ATM where $K = S_0$). The straddle price is the discounted expected payoff: $\\text{Straddle} \\approx E[|S_T - S_0|]$ (with $r \\approx 0$). So the market-implied expected absolute move is approximately $\\$6$.',
      solutionSteps: [
        'Straddle payoff $= \\max(S_T - K, 0) + \\max(K - S_T, 0) = |S_T - K|$.',
        'For ATM: $= |S_T - S_0|$.',
        'Straddle price $= e^{-rT} E^{\\mathbb{Q}}[|S_T - S_0|] \\approx E[|S_T - S_0|]$ (for small $r$).',
        'So the implied expected absolute move $\\approx \\$6.00$.',
        'This is approximately $6\\%$ of the stock price over 1 month.',
      ],
    },
  ],
  flashcards: [
    { id: 'd7-f01', front: 'Bull call spread construction', back: 'Buy lower-strike call, sell higher-strike call. Max profit $= (K_2 - K_1) - \\text{net premium}$.', tags: ['spreads', 'vertical'] },
    { id: 'd7-f02', front: 'ATM straddle approximation', back: '$\\text{Straddle} \\approx 0.8 S \\sigma \\sqrt{T}$', tags: ['spreads', 'straddle'] },
    { id: 'd7-f03', front: 'Straddle breakevens', back: '$K \\pm \\text{straddle price}$', tags: ['spreads', 'straddle'] },
    { id: 'd7-f04', front: 'Straddle Greeks', back: '$\\Delta \\approx 0$ (ATM), $\\Gamma = 2\\Gamma_{\\text{single}}$, $\\Theta = 2\\Theta_{\\text{single}}$, $\\mathcal{V} = 2\\mathcal{V}_{\\text{single}}$.', tags: ['spreads', 'straddle', 'greeks'] },
    { id: 'd7-f05', front: 'Butterfly construction', back: 'Buy $K_1$, sell $2 \\times K_2$, buy $K_3$ (equally spaced). Max profit at $K_2$. Short vol bet.', tags: ['spreads', 'butterfly'] },
    { id: 'd7-f06', front: 'Long butterfly Greeks', back: '$\\Delta \\approx 0$, $\\Gamma < 0$, $\\Theta > 0$, $\\mathcal{V} < 0$. Short vol with limited risk.', tags: ['spreads', 'butterfly', 'greeks'] },
    { id: 'd7-f07', front: 'Calendar spread: why long vega?', back: 'Far-dated option has more vega ($\\propto \\sqrt{T}$) than near-dated. Net vega is positive.', tags: ['spreads', 'calendar', 'vega'] },
    { id: 'd7-f08', front: 'Risk reversal (equity)', back: 'Long OTM call + Short OTM put. Usually generates credit due to put skew. Bullish directional view.', tags: ['spreads', 'risk-reversal'] },
    { id: 'd7-f09', front: 'Implied move from straddle', back: 'Expected move $\\approx$ straddle price. Daily implied move $\\approx$ straddle$/\\sqrt{T_{\\text{days}}}$.', tags: ['spreads', 'straddle', 'implied-move'] },
    { id: 'd7-f10', front: 'Vertical spread vega', back: 'Much less vega than single legs (partial offset). Good for directional trades with limited vol risk.', tags: ['spreads', 'vertical', 'vega'] },
    { id: 'd7-f11', front: 'Short straddle Greek profile', back: '$\\Delta \\approx 0$, $\\Gamma < 0$, $\\Theta > 0$, $\\mathcal{V} < 0$. Collect theta, pay on moves.', tags: ['spreads', 'straddle', 'greeks'] },
    { id: 'd7-f12', front: '1x2 ratio spread risk', back: 'Unlimited loss on one side (exposed short call/put). Often entered for zero or small net premium.', tags: ['spreads', 'ratio'] },
  ],
  interactiveTools: ['payoff-diagram', 'greek-visualizer', 'bs-calculator'],
  cheatSheet: [
    { topic: 'Bull Call Spread', formula: 'Long K₁C + Short K₂C (K₁<K₂)', description: 'Bullish, capped risk/reward. Delta > 0.' },
    { topic: 'ATM Straddle', formula: 'Long C(K) + Long P(K) ≈ 0.8Sσ√T', description: 'Vol bet. Delta ≈ 0, 2x gamma/theta/vega.' },
    { topic: 'Straddle Breakevens', formula: 'K ± straddle_price', description: 'Stock must move beyond this range to profit.' },
    { topic: 'Butterfly', formula: 'Long K₁ + Short 2K₂ + Long K₃', description: 'Max profit at K₂. Short vol, limited risk.' },
    { topic: 'Calendar Spread', formula: 'Short near-term + Long far-term', description: 'Long vega (far>near). Positive theta.' },
    { topic: 'Iron Condor', formula: 'Sell OTM put spread + Sell OTM call spread', description: 'Short vol, defined risk. Collect premium.' },
    { topic: 'Implied Move', formula: 'Straddle price / √(T_days)', description: 'Market-implied daily expected move.' },
    { topic: 'Risk Reversal', formula: 'Long OTM call + Short OTM put', description: 'Directional with skew exposure. Often net credit in equities.' },
  ],
  summary: [
    'Vertical spreads: directional bets with capped risk. Reduced vega vs. single legs.',
    'Straddle $\\approx 0.8 S \\sigma \\sqrt{T}$: pure vol bet with $\\Delta \\approx 0$ and $2\\times$ gamma/theta/vega.',
    'Butterfly: short vol with limited risk. Max profit at middle strike. $\\Gamma < 0$, $\\Theta > 0$, $\\mathcal{V} < 0$.',
    'Calendar spreads are long vega (far-dated vega $>$ near-dated) and positive theta.',
    'Implied daily move $\\approx$ straddle price $/ \\sqrt{T_{\\text{days}}}$.',
    'Full chain: forward $\\to$ BS pricing $\\to$ Greeks $\\to$ spread construction and Greek analysis.',
  ],
};

export default day07;
