import { DayContent } from './types';

const day06: DayContent = {
  dayNumber: 6,
  title: 'Greeks & Cross-Greek Relationships',
  subtitle: 'Natenberg Chapters 6, 9',
  week: 1,
  chapters: ['Chapter 6', 'Chapter 9'],
  estimatedMinutes: 120,
  prerequisites: [1, 2, 3, 4, 5],
  objectives: [
    'Compute Delta, Gamma, Theta, Vega, and Rho from the BS formulas',
    'Understand the gamma-theta tradeoff and BS PDE relationship',
    'Analyze Greek profiles across moneyness and time',
    'Perform delta-hedging P&L analysis using Greeks',
    'Apply the BS PDE: $\\Theta + \\frac{1}{2}\\sigma^2 S^2 \\Gamma = rV - rS\\Delta$',
  ],
  theory: {
    sections: [
      {
        title: 'Delta',
        blocks: [
          {
            type: 'text',
            body: 'Delta ($\\Delta$) measures the rate of change of the option price with respect to the underlying price. It is the most fundamental Greek and the primary hedge ratio. For a call, $\\Delta = N(d_1) \\in (0, 1)$. For a put, $\\Delta = N(d_1) - 1 \\in (-1, 0)$.',
          },
          {
            type: 'formula',
            latex: '\\Delta_{\\text{call}} = N(d_1), \\quad \\Delta_{\\text{put}} = N(d_1) - 1',
            label: 'Delta Formulas',
            explanation: 'Call delta is always positive (option gains when stock rises). Put delta is always negative. Note: $\\Delta_{\\text{put}} = \\Delta_{\\text{call}} - 1$, consistent with put-call parity.',
          },
          {
            type: 'callout',
            variant: 'tip',
            body: 'ATM options have delta $\\approx \\pm 0.50$. Deep ITM calls have $\\Delta \\approx 1$ (behave like stock). Deep OTM calls have $\\Delta \\approx 0$ (barely respond to stock moves). Puts mirror this: deep ITM puts have $\\Delta \\approx -1$.',
          },
        ],
      },
      {
        title: 'Gamma',
        blocks: [
          {
            type: 'text',
            body: 'Gamma ($\\Gamma$) is the rate of change of delta with respect to the stock price. It measures the curvature of the option\'s price function. Gamma is highest for ATM options near expiration and is always positive for long options.',
          },
          {
            type: 'formula',
            latex: '\\Gamma = \\frac{n(d_1)}{S \\sigma \\sqrt{T}}',
            label: 'Gamma Formula',
            explanation: '$n(d_1) = \\frac{1}{\\sqrt{2\\pi}} e^{-d_1^2/2}$ is the standard normal PDF. Gamma is the same for calls and puts (same strike, same expiry).',
          },
          {
            type: 'concept',
            title: 'Gamma as a Risk Measure',
            body: 'Long gamma positions profit from large moves (in either direction) because delta adjusts favorably. Short gamma positions lose on large moves. Gamma is the source of the convexity benefit of owning options. It is paid for via theta.',
          },
        ],
      },
      {
        title: 'Theta',
        blocks: [
          {
            type: 'text',
            body: 'Theta ($\\Theta$) measures time decay: the rate at which an option loses value as time passes, all else equal. For long options, theta is negative (the option decays). For ATM options, theta is largest near expiration.',
          },
          {
            type: 'formula',
            latex: '\\Theta_{\\text{call}} = -\\frac{S \\sigma n(d_1)}{2\\sqrt{T}} - rKe^{-rT}N(d_2)',
            label: 'Theta Formula (Call)',
            explanation: 'The first term is always negative (volatility component of decay). The second term is the interest cost of the strike. For puts, the sign of the interest term flips.',
          },
          {
            type: 'callout',
            variant: 'key-insight',
            body: 'Theta for an ATM option accelerates as expiry approaches (the "hockey stick" decay curve). Roughly: theta is proportional to $1/\\sqrt{T}$. An option with 1 week to expiry decays about twice as fast as one with 4 weeks.',
          },
        ],
      },
      {
        title: 'Vega',
        blocks: [
          {
            type: 'text',
            body: 'Vega measures the sensitivity of the option price to changes in implied volatility. It is the most important Greek for volatility traders. Vega is highest for ATM options with long time to expiry.',
          },
          {
            type: 'formula',
            latex: '\\mathcal{V} = S \\sqrt{T} \\cdot n(d_1)',
            label: 'Vega Formula',
            explanation: 'Vega is the same for calls and puts (same strike, expiry). It is always positive for long options. Convention: vega gives the price change for a 1-point (1 percentage point) change in implied vol.',
          },
          {
            type: 'callout',
            variant: 'tip',
            body: 'Vega scales with $\\sqrt{T}$: a 1-year option has about $\\sqrt{4} = 2$ times the vega of a 3-month option. This is crucial for calendar spread analysis.',
          },
        ],
      },
      {
        title: 'The Gamma-Theta Tradeoff & BS PDE',
        blocks: [
          {
            type: 'text',
            body: 'The most important relationship among the Greeks is the **gamma-theta tradeoff**. Long gamma positions (which profit from moves) pay for this through theta (time decay). The exact relationship is given by the BS PDE.',
          },
          {
            type: 'formula',
            latex: '\\Theta + \\frac{1}{2}\\sigma^2 S^2 \\Gamma = rV - rS\\Delta',
            label: 'BS PDE in Greek Form',
            explanation: 'For ATM options with low rates: $\\Theta \\approx -\\frac{1}{2}\\sigma^2 S^2 \\Gamma$. Theta and gamma are locked in opposition: more gamma means more negative theta.',
          },
          {
            type: 'example',
            title: 'Gamma-Theta Tradeoff',
            problem: 'An ATM call has $\\Gamma = 0.02$, $S = 100$, $\\sigma = 20\\%$, $r \\approx 0$. What is the approximate daily theta?',
            solution: [
              'From the PDE (with $r \\approx 0$): $\\Theta \\approx -\\frac{1}{2}\\sigma^2 S^2 \\Gamma$',
              '$= -\\frac{1}{2}(0.04)(10000)(0.02) = -4.00$ per year.',
              'Daily theta $= -4.00 / 365 = -\\$0.011$ per day.',
              'Alternatively: the option decays by about $1.1$ cents per day, offset by gamma profits from daily moves.',
            ],
          },
          {
            type: 'callout',
            variant: 'key-insight',
            body: 'The gamma-theta tradeoff is the fundamental tension in options trading. You cannot have gamma (convexity) for free. If you want to profit from moves, you must pay theta. If you collect theta, you are exposed to large moves (short gamma). Understanding this tradeoff is the single most important insight for a volatility trader.',
          },
        ],
      },
      {
        title: 'Rho & Minor Greeks',
        blocks: [
          {
            type: 'text',
            body: 'Rho ($\\rho$) measures sensitivity to the risk-free rate. It is typically the least important Greek for short-dated equity options, but matters for long-dated options and interest rate derivatives.',
          },
          {
            type: 'formula',
            latex: '\\rho_{\\text{call}} = KTe^{-rT}N(d_2), \\quad \\rho_{\\text{put}} = -KTe^{-rT}N(-d_2)',
            label: 'Rho Formulas',
            explanation: 'Rho is positive for calls (higher rates increase forward, benefiting calls) and negative for puts. Rho scales with $T$: long-dated options are more rate-sensitive.',
          },
        ],
      },
    ],
  },
  exercises: [
    // --- EASY (5) ---
    {
      id: 'd6-greek-01',
      exerciseType: 'numeric',
      difficulty: 'easy',
      topic: 'delta',
      tags: ['greeks', 'delta'],
      timeEstimateSeconds: 30,
      question: 'A call option has $d_1 = 0.25$. What is its delta? Use $N(0.25) = 0.5987$.',
      correctAnswer: 0.5987,
      tolerance: 0.001,
      explanation: '$\\Delta_{\\text{call}} = N(d_1) = N(0.25) = 0.5987$.',
      solutionSteps: [
        '$\\Delta_{\\text{call}} = N(d_1) = N(0.25) = 0.5987$.',
        'This means for every $1 the stock moves, the call moves about $0.60.',
      ],
    },
    {
      id: 'd6-greek-02',
      exerciseType: 'numeric',
      difficulty: 'easy',
      topic: 'delta',
      tags: ['greeks', 'delta'],
      timeEstimateSeconds: 20,
      question: 'If a call has delta $= 0.60$, what is the delta of the corresponding put (same strike and expiry)?',
      correctAnswer: -0.40,
      tolerance: 0.01,
      explanation: '$\\Delta_{\\text{put}} = \\Delta_{\\text{call}} - 1 = 0.60 - 1 = -0.40$.',
      solutionSteps: [
        '$\\Delta_{\\text{put}} = N(d_1) - 1 = \\Delta_{\\text{call}} - 1$',
        '$= 0.60 - 1 = -0.40$',
        'This follows directly from put-call parity: differentiating $C - P = S - Ke^{-rT}$ with respect to $S$ gives $\\Delta_C - \\Delta_P = 1$.',
      ],
    },
    {
      id: 'd6-greek-03',
      exerciseType: 'true-false',
      difficulty: 'easy',
      topic: 'gamma',
      tags: ['greeks', 'gamma'],
      timeEstimateSeconds: 20,
      statement: 'Gamma is different for a call and put at the same strike and expiry.',
      correct: false,
      explanation: 'Gamma is identical for a call and put at the same strike and expiry. This follows from put-call parity: $C - P = S - Ke^{-rT}$. The second derivative of the RHS with respect to $S$ is 0, so $\\Gamma_C = \\Gamma_P$.',
      solutionSteps: [
        'From put-call parity: $C - P = S - Ke^{-rT}$.',
        'Differentiate twice w.r.t. $S$: $\\Gamma_C - \\Gamma_P = 0$.',
        'So $\\Gamma_C = \\Gamma_P$.',
      ],
    },
    {
      id: 'd6-greek-04',
      exerciseType: 'multiple-choice',
      difficulty: 'easy',
      topic: 'greeks',
      tags: ['greeks', 'gamma', 'theta'],
      timeEstimateSeconds: 30,
      question: 'Which Greek is always the same for a call and put at the same strike and expiry?',
      options: [
        'Delta',
        'Theta',
        'Gamma',
        'Rho',
      ],
      correctIndex: 2,
      explanation: 'Gamma and Vega are the same for calls and puts (same strike/expiry). Delta differs by 1. Theta differs by $rKe^{-rT}$. Rho differs by sign.',
      solutionSteps: [
        'From parity $C - P = S - Ke^{-rT}$:',
        '$\\Delta_C - \\Delta_P = 1$ (different).',
        '$\\Gamma_C - \\Gamma_P = 0$ (same).',
        '$\\Theta_C - \\Theta_P = rKe^{-rT}$ (different).',
        '$\\mathcal{V}_C = \\mathcal{V}_P$ (same, since $\\partial(S - Ke^{-rT})/\\partial\\sigma = 0$).',
      ],
    },
    {
      id: 'd6-greek-05',
      exerciseType: 'numeric',
      difficulty: 'easy',
      topic: 'vega',
      tags: ['greeks', 'vega'],
      timeEstimateSeconds: 45,
      question: 'An ATM call has vega $= 0.20$ (price change per 1% vol change). If implied vol increases from 25% to 27%, what is the approximate price change?',
      correctAnswer: 0.40,
      tolerance: 0.01,
      unit: '$',
      explanation: 'Vol change $= 2$ percentage points. Price change $\\approx 0.20 \\times 2 = \\$0.40$.',
      solutionSteps: [
        'Vega $= 0.20$ per 1 percentage point of vol.',
        'Vol increase $= 27\\% - 25\\% = 2$ points.',
        'Price change $\\approx 0.20 \\times 2 = \\$0.40$.',
      ],
    },
    // --- MEDIUM (6) ---
    {
      id: 'd6-greek-06',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'gamma',
      tags: ['greeks', 'gamma'],
      timeEstimateSeconds: 90,
      question: 'Compute gamma for an ATM option: $S = 100$, $K = 100$, $T = 0.25$, $r = 0$, $\\sigma = 20\\%$. Use $n(0.05) \\approx 0.3984$.',
      correctAnswer: 0.0399,
      tolerance: 0.001,
      explanation: 'With $r = 0$, $S = K$: $d_1 = \\sigma\\sqrt{T}/2 = 0.10/2 = 0.05$. $\\Gamma = \\frac{n(0.05)}{S\\sigma\\sqrt{T}} = \\frac{0.3984}{100 \\times 0.20 \\times 0.50} = \\frac{0.3984}{10} = 0.03984$.',
      solutionSteps: [
        '$d_1 = \\sigma\\sqrt{T}/2 = 0.20 \\times 0.50/2 = 0.05$ (ATM with $r = 0$).',
        '$n(d_1) = n(0.05) = \\frac{1}{\\sqrt{2\\pi}}e^{-0.05^2/2} \\approx 0.3984$.',
        '$\\Gamma = \\frac{n(d_1)}{S\\sigma\\sqrt{T}} = \\frac{0.3984}{100 \\times 0.10} = 0.03984$.',
        'This means for a $1 move in the stock, delta changes by about 0.04.',
      ],
    },
    {
      id: 'd6-greek-07',
      exerciseType: 'multi-step',
      difficulty: 'medium',
      topic: 'gamma-theta-tradeoff',
      tags: ['greeks', 'gamma', 'theta', 'pde'],
      timeEstimateSeconds: 120,
      question: 'An ATM call has $\\Gamma = 0.04$, $S = 100$, $\\sigma = 20\\%$, $r = 0$. (a) Compute the annual theta from the BS PDE. (b) Convert to daily theta.',
      steps: [
        {
          prompt: 'What is the annual theta (using $\\Theta \\approx -\\frac{1}{2}\\sigma^2 S^2 \\Gamma$ when $r \\approx 0$)?',
          correctAnswer: -8.0,
          tolerance: 0.1,
          unit: '$ per year',
          stepExplanation: '$\\Theta \\approx -\\frac{1}{2}(0.04)(10000)(0.04) = -8.00$ per year.',
        },
        {
          prompt: 'What is the daily theta?',
          correctAnswer: -0.0219,
          tolerance: 0.002,
          unit: '$ per day',
          stepExplanation: 'Daily theta $= -8.00/365 = -0.0219$ per day.',
        },
      ],
      explanation: 'The gamma-theta tradeoff: this option earns gamma P&L from moves but pays about 2.2 cents per day in theta.',
      solutionSteps: [
        'BS PDE with $r = 0$: $\\Theta = -\\frac{1}{2}\\sigma^2 S^2 \\Gamma$',
        '$= -\\frac{1}{2}(0.04)(10000)(0.04) = -8.00$ per year',
        'Daily: $-8.00/365 = -\\$0.022$ per day.',
        'Break-even daily move: $|\\Delta S|$ where $\\frac{1}{2}\\Gamma(\\Delta S)^2 = 0.022$.',
        '$\\Delta S = \\sqrt{2 \\times 0.022/0.04} = \\sqrt{1.10} = \\$1.05$.',
      ],
    },
    {
      id: 'd6-greek-08',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'vega',
      tags: ['greeks', 'vega'],
      timeEstimateSeconds: 90,
      question: 'Compute vega for: $S = 100$, $d_1 = 0.10$, $T = 1$. Use $n(0.10) \\approx 0.3970$.',
      correctAnswer: 39.70,
      tolerance: 0.2,
      explanation: '$\\mathcal{V} = S\\sqrt{T} \\cdot n(d_1) = 100 \\times 1 \\times 0.3970 = 39.70$. This means a 1 percentage point increase in vol increases the option price by about $0.397.',
      solutionSteps: [
        '$\\mathcal{V} = S\\sqrt{T} \\cdot n(d_1) = 100 \\times 1.0 \\times 0.3970 = 39.70$',
        'Convention: vega is often quoted per 1% vol change. So $39.70/100 = 0.397$ per 1% vol.',
        'Or equivalently, a 1 vol point (1%) increase raises the price by $\\$0.397$.',
      ],
    },
    {
      id: 'd6-greek-09',
      exerciseType: 'free-response',
      difficulty: 'medium',
      topic: 'greek-profiles',
      tags: ['greeks', 'delta', 'gamma'],
      timeEstimateSeconds: 120,
      question: 'Describe the delta and gamma profiles of a call option as a function of the stock price, for fixed $K$, $T$, $\\sigma$. How do these profiles change as $T \\to 0$?',
      modelAnswer: 'Delta profile: S-shaped curve from 0 (far OTM) to 1 (far ITM), passing through 0.5 at ATM. Gamma profile: bell-shaped, peaked at ATM, approaching zero for deep ITM and OTM. As $T \\to 0$: delta approaches a step function (0 for $S < K$, 1 for $S > K$), and gamma approaches a Dirac delta at $S = K$ (infinite at ATM, zero elsewhere). Near expiry, ATM gamma explodes, creating extreme hedging risk (the "pin risk" problem). This is why market makers are very cautious with ATM options near expiry.',
      explanation: 'Delta is sigmoid-shaped; gamma is bell-shaped centered at ATM. Both sharpen as expiry approaches.',
      solutionSteps: [
        'Delta: sigmoid from 0 to 1, centered at $K$. Slope $= \\Gamma$.',
        'Gamma: peaked at ATM ($S = K$). Width $\\propto \\sigma\\sqrt{T}$.',
        'As $T \\to 0$: delta $\\to$ step function, gamma $\\to$ Dirac delta at $K$.',
        'Near expiry: ATM gamma is huge (delta flips rapidly between 0 and 1).',
        'This creates "pin risk" for short option holders at ATM near expiry.',
      ],
    },
    {
      id: 'd6-greek-10',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'delta-hedging',
      tags: ['greeks', 'delta', 'hedging'],
      timeEstimateSeconds: 90,
      question: 'You are short 200 calls with delta 0.45 and long 300 puts with delta $-0.30$. What is your portfolio delta? How many shares do you need to buy/sell to be delta-neutral?',
      correctAnswer: 0,
      tolerance: 1,
      unit: 'shares (net delta before hedging)',
      hint: 'Portfolio delta = sum of position deltas.',
      explanation: 'Short 200 calls: delta $= -200 \\times 0.45 = -90$. Long 300 puts: delta $= 300 \\times (-0.30) = -90$. Total delta $= -180$. Buy 180 shares to be delta-neutral.',
      solutionSteps: [
        'Short 200 calls: $-200 \\times 0.45 = -90$',
        'Long 300 puts: $+300 \\times (-0.30) = -90$',
        'Total delta $= -90 + (-90) = -180$',
        'Buy 180 shares (each share has delta $= +1$) to neutralize.',
      ],
    },
    {
      id: 'd6-greek-11',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'theta',
      tags: ['greeks', 'theta'],
      timeEstimateSeconds: 60,
      question: 'An option portfolio has daily theta of $-\\$500$. Over a weekend (Friday close to Monday open, effectively 3 calendar days), how much theta does the portfolio lose?',
      correctAnswer: 1500,
      tolerance: 50,
      unit: '$',
      explanation: 'Theta accrues on a calendar-day basis. Over 3 calendar days: $3 \\times 500 = \\$1500$. (Note: in practice, weekend theta may be weighted differently, but the standard convention is calendar-day accrual.)',
      solutionSteps: [
        'Daily theta $= -\\$500$ (the portfolio loses $500/day).',
        'Weekend $= 3$ calendar days (Friday, Saturday, Sunday).',
        'Theta loss $= 3 \\times 500 = \\$1500$.',
        'Note: some firms assign weekend theta differently (e.g., 1.5 days), but standard is 3.',
      ],
    },
    // --- HARD (5) ---
    {
      id: 'd6-greek-12',
      exerciseType: 'multi-step',
      difficulty: 'hard',
      topic: 'bs-pde-verification',
      tags: ['greeks', 'pde', 'gamma', 'theta'],
      timeEstimateSeconds: 240,
      question: 'Verify the BS PDE for an ATM call: $S = K = 100$, $T = 0.25$, $r = 5\\%$, $\\sigma = 20\\%$, $C = 4.62$, $\\Delta = 0.57$, $\\Gamma = 0.040$, $\\Theta_{\\text{annual}} = -8.89$. Check that $\\Theta + \\frac{1}{2}\\sigma^2 S^2 \\Gamma + rS\\Delta \\approx rC$.',
      steps: [
        {
          prompt: 'What is $\\frac{1}{2}\\sigma^2 S^2 \\Gamma$?',
          correctAnswer: 8.0,
          tolerance: 0.1,
          stepExplanation: '$\\frac{1}{2}(0.04)(10000)(0.040) = 8.00$',
        },
        {
          prompt: 'What is $rS\\Delta$?',
          correctAnswer: 2.85,
          tolerance: 0.1,
          stepExplanation: '$0.05 \\times 100 \\times 0.57 = 2.85$',
        },
        {
          prompt: 'What is $rC$?',
          correctAnswer: 0.231,
          tolerance: 0.01,
          stepExplanation: '$0.05 \\times 4.62 = 0.231$',
        },
        {
          prompt: 'Verify LHS $\\approx$ RHS: $\\Theta + \\frac{1}{2}\\sigma^2 S^2 \\Gamma + rS\\Delta$',
          correctAnswer: 1.96,
          tolerance: 0.5,
          stepExplanation: 'LHS $= -8.89 + 8.00 + 2.85 = 1.96$. RHS $= rC = 0.231$. These should be closer; the discrepancy comes from rounding in the Greeks. With exact values, LHS $=$ RHS.',
        },
      ],
      explanation: 'The BS PDE $\\Theta + \\frac{1}{2}\\sigma^2 S^2 \\Gamma + rS\\Delta = rV$ must hold exactly for consistent Greek values.',
      solutionSteps: [
        '$\\frac{1}{2}\\sigma^2 S^2 \\Gamma = \\frac{1}{2}(0.04)(10000)(0.040) = 8.00$',
        '$rS\\Delta = 0.05 \\times 100 \\times 0.57 = 2.85$',
        '$rC = 0.05 \\times 4.62 = 0.231$',
        'LHS $= \\Theta + 8.00 + 2.85 = -8.89 + 8.00 + 2.85 = 1.96$',
        'With exact Greeks, LHS $=$ RHS $= rC$. Small discrepancy is from rounding.',
      ],
    },
    {
      id: 'd6-greek-13',
      exerciseType: 'scenario',
      difficulty: 'hard',
      topic: 'delta-hedging-pnl',
      tags: ['greeks', 'delta', 'gamma', 'theta', 'pnl'],
      timeEstimateSeconds: 180,
      question: 'You are long 100 ATM calls. $\\Delta = 0.50$, $\\Gamma = 0.03$, daily $\\Theta = -\\$15$ (for the whole position). You delta-hedge. Compute the net P&L for each daily stock move scenario.',
      scenarios: [
        {
          description: 'Stock moves +$2',
          shocks: [{ variable: 'stock', change: 2 }],
          expectedAnswer: -9.0,
          tolerance: 1.0,
          unit: '$',
        },
        {
          description: 'Stock moves +$5',
          shocks: [{ variable: 'stock', change: 5 }],
          expectedAnswer: 22.5,
          tolerance: 2.0,
          unit: '$',
        },
        {
          description: 'Stock does not move',
          shocks: [{ variable: 'stock', change: 0 }],
          expectedAnswer: -15.0,
          tolerance: 0.5,
          unit: '$',
        },
      ],
      explanation: 'Net P&L = gamma P&L + theta. Gamma P&L $= \\frac{1}{2} \\times 100 \\times \\Gamma (\\Delta S)^2$. Theta is paid regardless.',
      solutionSteps: [
        'Position gamma $= 100 \\times 0.03 = 3.0$.',
        'Gamma P&L $= \\frac{1}{2} \\times 3.0 \\times (\\Delta S)^2$.',
        '+$2 move: gamma P&L $= 0.5 \\times 3.0 \\times 4 = 6.0$. Net $= 6.0 - 15.0 = -9.0$.',
        '+$5 move: gamma P&L $= 0.5 \\times 3.0 \\times 25 = 37.5$. Net $= 37.5 - 15.0 = 22.5$.',
        'No move: gamma P&L $= 0$. Net $= 0 - 15.0 = -15.0$.',
      ],
    },
    {
      id: 'd6-greek-14',
      exerciseType: 'free-response',
      difficulty: 'hard',
      topic: 'greeks',
      tags: ['greeks', 'gamma', 'theta', 'vega'],
      timeEstimateSeconds: 150,
      question: 'Explain why ATM gamma is highest near expiry but ATM vega is highest far from expiry. How do these opposing behaviors affect a market maker managing a book of options across expirations?',
      modelAnswer: 'Gamma $\\propto n(d_1)/(S\\sigma\\sqrt{T})$, which has $1/\\sqrt{T}$ in the denominator. Near expiry, $\\sqrt{T} \\to 0$, so gamma explodes. Vega $\\propto S\\sqrt{T} \\cdot n(d_1)$, which has $\\sqrt{T}$ in the numerator. Far from expiry, $\\sqrt{T}$ is large, so vega is large. For a market maker: (1) Near-expiry options have high gamma risk (large delta swings from small moves) but low vega risk. (2) Far-dated options have high vega risk (sensitive to vol changes) but low gamma risk. The book must be managed across both dimensions. Often, near-term gamma risk is hedged by frequent delta rebalancing, while long-term vega risk is hedged by offsetting long and short vol positions across the term structure.',
      explanation: 'Gamma scales as $1/\\sqrt{T}$ (peaks near expiry); vega scales as $\\sqrt{T}$ (peaks far from expiry).',
      solutionSteps: [
        '$\\Gamma = n(d_1)/(S\\sigma\\sqrt{T})$. As $T \\to 0$, $\\Gamma \\to \\infty$ (for ATM).',
        '$\\mathcal{V} = S\\sqrt{T} n(d_1)$. As $T \\to \\infty$, $\\mathcal{V}$ grows.',
        'Near-expiry: gamma dominates (hedging risk from delta swings).',
        'Far-expiry: vega dominates (risk from vol level changes).',
        'Market makers manage gamma risk via rebalancing and vega risk via the term structure.',
      ],
    },
    {
      id: 'd6-greek-15',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'gamma-breakeven',
      tags: ['greeks', 'gamma', 'theta', 'breakeven'],
      timeEstimateSeconds: 120,
      question: 'You are long an ATM straddle with total position gamma $= 0.08$ and daily theta $= -\\$40$. What is the break-even daily stock move (in dollars) for the straddle to pay for its theta?',
      correctAnswer: 31.62,
      tolerance: 1.0,
      unit: '$',
      hint: 'Set gamma P&L = theta: $\\frac{1}{2}\\Gamma(\\Delta S)^2 = |\\Theta_{\\text{daily}}|$.',
      explanation: '$\\frac{1}{2}(0.08)(\\Delta S)^2 = 40$. $\\Delta S^2 = 1000$. $\\Delta S = \\sqrt{1000} = 31.62$. The stock must move about $31.62 per day for gamma gains to offset theta.',
      solutionSteps: [
        'Set gamma P&L $= |\\text{theta}|$: $\\frac{1}{2}\\Gamma(\\Delta S)^2 = 40$',
        '$0.04 (\\Delta S)^2 = 40$',
        '$(\\Delta S)^2 = 1000$',
        '$\\Delta S = \\sqrt{1000} = \\$31.62$',
        'If the stock moves more than $31.62/day, the straddle profits. Less than that, it loses.',
      ],
    },
    {
      id: 'd6-greek-16',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'rho',
      tags: ['greeks', 'rho'],
      timeEstimateSeconds: 90,
      question: 'Compute rho for a call: $K = 100$, $T = 1$, $r = 5\\%$, $d_2 = 0.10$, $N(0.10) = 0.5398$. Express rho per 1% rate change.',
      correctAnswer: 51.33,
      tolerance: 0.5,
      unit: '$ per 100% rate change',
      explanation: '$\\rho_{\\text{call}} = KTe^{-rT}N(d_2) = 100 \\times 1 \\times e^{-0.05} \\times 0.5398 = 95.12 \\times 0.5398 = 51.35$. Per 1% change: $51.35/100 = 0.5135$.',
      solutionSteps: [
        '$\\rho = KTe^{-rT}N(d_2) = 100 \\times 1 \\times 0.9512 \\times 0.5398$',
        '$= 51.35$ (in units of price per 100% rate change)',
        'Per 1% change (1 bp $\\times$ 100): $\\rho_{1\\%} = 51.35/100 = 0.5135$',
        'So a 1% increase in $r$ increases the call by about $\\$0.51$.',
      ],
    },
    // --- INTERVIEW (3) ---
    {
      id: 'd6-greek-17',
      exerciseType: 'speed-drill',
      difficulty: 'interview',
      topic: 'greek-mental-math',
      tags: ['greeks', 'mental-math'],
      timeEstimateSeconds: 90,
      timeLimitSeconds: 90,
      problems: [
        { prompt: 'ATM call delta (approximate)', correctAnswer: 0.50, tolerance: 0.05 },
        { prompt: 'Put delta if call delta = 0.70', correctAnswer: -0.30, tolerance: 0.01 },
        { prompt: 'Long 100 calls, delta 0.60. Shares to hedge?', correctAnswer: -60, tolerance: 1 },
        { prompt: 'Gamma = 0.05, stock moves +$4. Gamma P&L?', correctAnswer: 0.40, tolerance: 0.02 },
        { prompt: 'Daily theta = -$20, stock moves $0. Net P&L?', correctAnswer: -20.0, tolerance: 0.5 },
        { prompt: 'Vega = 0.15, vol drops 3 points. Price change?', correctAnswer: -0.45, tolerance: 0.02 },
      ],
      explanation: 'These are the mental math computations a trader does dozens of times per day.',
      solutionSteps: [
        'ATM call delta $\\approx 0.50$',
        'Put delta $= 0.70 - 1 = -0.30$',
        'Hedge: sell $100 \\times 0.60 = 60$ shares (or buy $-60$)',
        'Gamma P&L $= \\frac{1}{2}(0.05)(16) = 0.40$',
        'No move: P&L $=$ theta $= -\\$20$',
        'Vega P&L $= 0.15 \\times (-3) = -\\$0.45$',
      ],
    },
    {
      id: 'd6-greek-18',
      exerciseType: 'free-response',
      difficulty: 'interview',
      topic: 'gamma-theta',
      tags: ['greeks', 'gamma', 'theta', 'interview'],
      timeEstimateSeconds: 120,
      question: 'Interview question: "You are long gamma. Explain what this means in terms of your P&L profile and how you make money. What is the cost?"',
      modelAnswer: 'Long gamma means I own convexity. My delta adjusts favorably when the stock moves: if the stock rises, my delta becomes more positive (I get longer); if the stock falls, my delta becomes more negative (I get shorter). By delta-hedging after each move, I systematically "buy low, sell high." My gamma P&L per move is $\\frac{1}{2}\\Gamma(\\Delta S)^2$, which is always positive. The cost is theta: my options decay over time. The gamma-theta tradeoff says $\\Theta \\approx -\\frac{1}{2}\\sigma^2 S^2 \\Gamma$ (when $r \\approx 0$). I make money if the stock moves more than implied vol predicts (realized vol > implied vol). I lose if the stock is quiet (realized < implied). The break-even daily move is $\\sqrt{2|\\Theta|/\\Gamma}$.',
      explanation: 'Long gamma = long convexity. Profit from moves, pay theta. Net P&L depends on realized vs. implied vol.',
      solutionSteps: [
        'Long gamma: favorable delta adjustment on stock moves.',
        'Gamma P&L $= \\frac{1}{2}\\Gamma(\\Delta S)^2 > 0$ for any move.',
        'Cost: theta. $\\Theta \\approx -\\frac{1}{2}\\sigma^2 S^2 \\Gamma$.',
        'Profit if realized vol > implied vol.',
        'Break-even move $= \\sqrt{2|\\Theta|/\\Gamma}$.',
      ],
    },
    {
      id: 'd6-greek-19',
      exerciseType: 'numeric',
      difficulty: 'interview',
      topic: 'greeks',
      tags: ['greeks', 'mental-math', 'gamma', 'theta'],
      timeEstimateSeconds: 60,
      question: 'Quick estimate: You are long gamma 0.05 on a $100 stock with 20% implied vol. What is your approximate daily theta? (Use $\\Theta_{\\text{daily}} \\approx \\frac{1}{2}\\sigma^2 S^2 \\Gamma / 365$.)',
      correctAnswer: -0.027,
      tolerance: 0.003,
      unit: '$ per day',
      explanation: '$\\Theta_{\\text{annual}} \\approx -\\frac{1}{2}(0.04)(10000)(0.05) = -10.0$. Daily $= -10.0/365 = -0.027$.',
      solutionSteps: [
        '$|\\Theta_{\\text{annual}}| \\approx \\frac{1}{2}\\sigma^2 S^2 \\Gamma = \\frac{1}{2}(0.04)(10000)(0.05) = 10.0$',
        '$|\\Theta_{\\text{daily}}| = 10.0/365 = 0.0274$',
        'Daily theta $\\approx -\\$0.027$ per option.',
        'This is very small; the gamma-theta tradeoff is balanced.',
      ],
    },
  ],
  cumulativeExercises: [
    {
      id: 'd6-cum-01',
      exerciseType: 'multi-step',
      difficulty: 'hard',
      topic: 'full-greeks',
      tags: ['bs', 'greeks', 'pricing'],
      timeEstimateSeconds: 300,
      fromDay: 4,
      question: 'Full BS pricing + Greeks: $S = 100$, $K = 100$, $T = 0.25$, $r = 5\\%$, $\\sigma = 20\\%$. Compute the call price, delta, gamma, and verify the PDE. Use $d_1 = 0.175$, $N(0.175) = 0.5695$, $N(0.075) = 0.5299$, $n(0.175) = 0.3932$.',
      steps: [
        {
          prompt: 'What is the call price?',
          correctAnswer: 4.62,
          tolerance: 0.1,
          unit: '$',
          stepExplanation: '$C = 100(0.5695) - 98.76(0.5299) = 56.95 - 52.33 = 4.62$',
        },
        {
          prompt: 'What is delta?',
          correctAnswer: 0.5695,
          tolerance: 0.005,
          stepExplanation: '$\\Delta = N(d_1) = 0.5695$',
        },
        {
          prompt: 'What is gamma?',
          correctAnswer: 0.0393,
          tolerance: 0.001,
          stepExplanation: '$\\Gamma = \\frac{n(d_1)}{S\\sigma\\sqrt{T}} = \\frac{0.3932}{100 \\times 0.20 \\times 0.50} = \\frac{0.3932}{10} = 0.03932$',
        },
      ],
      explanation: 'Computing the full set of Greeks from BS building blocks.',
      solutionSteps: [
        '$d_1 = 0.175$, $d_2 = 0.075$',
        '$C = 100 N(0.175) - 98.76 N(0.075) = 56.95 - 52.33 = 4.62$',
        '$\\Delta = N(0.175) = 0.5695$',
        '$\\Gamma = n(0.175)/(100 \\times 0.10) = 0.3932/10 = 0.03932$',
      ],
    },
    {
      id: 'd6-cum-02',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'parity-greeks',
      tags: ['greeks', 'put-call-parity', 'delta'],
      timeEstimateSeconds: 60,
      fromDay: 1,
      question: 'From put-call parity, if the call delta is $0.65$ and the put delta is $-0.35$, verify that $\\Delta_C - \\Delta_P = 1$. What is the delta of the forward (long stock + long put + short call at the same strike)?',
      correctAnswer: 0,
      tolerance: 0.01,
      explanation: '$\\Delta_C - \\Delta_P = 0.65 - (-0.35) = 1.00$. Confirmed. Forward delta: $+1 + (-0.35) + (-0.65) = 0$. Wait: long stock ($\\Delta = 1$) + long put ($\\Delta = -0.35$) + short call ($\\Delta = -0.65$) $= 1 - 0.35 - 0.65 = 0$. The forward has zero delta because it is a fixed obligation.',
      solutionSteps: [
        '$\\Delta_C - \\Delta_P = 0.65 - (-0.35) = 1.00$. Consistent with parity.',
        'Forward = long stock + long put + short call (conversion).',
        'Delta $= +1 + (-0.35) + (-0.65) = 0$.',
        'A forward has zero delta because it is a fixed future exchange with no optionality.',
      ],
    },
    {
      id: 'd6-cum-03',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'ev-and-gamma',
      tags: ['ev', 'greeks', 'gamma'],
      timeEstimateSeconds: 120,
      fromDay: 3,
      question: 'You are long gamma 0.04 on a delta-hedged position. The stock can move +$3 or -$3 with equal probability each day. What is the expected daily gamma P&L?',
      correctAnswer: 0.18,
      tolerance: 0.01,
      unit: '$',
      explanation: 'Gamma P&L per move $= \\frac{1}{2}\\Gamma(\\Delta S)^2 = \\frac{1}{2}(0.04)(9) = 0.18$. Since the move is $\\pm 3$ with equal probability, and gamma P&L does not depend on direction, $E[\\text{gamma P&L}] = 0.18$.',
      solutionSteps: [
        'Gamma P&L $= \\frac{1}{2}\\Gamma(\\Delta S)^2$, regardless of direction.',
        'For $|\\Delta S| = 3$: $\\frac{1}{2}(0.04)(9) = 0.18$.',
        'Both up and down moves give the same gamma P&L.',
        '$E[\\text{gamma P&L}] = 0.5 \\times 0.18 + 0.5 \\times 0.18 = 0.18$.',
      ],
    },
  ],
  flashcards: [
    { id: 'd6-f01', front: 'Delta of a call', back: '$\\Delta_C = N(d_1)$, ranges from 0 (deep OTM) to 1 (deep ITM). ATM $\\approx 0.50$.', tags: ['greeks', 'delta'] },
    { id: 'd6-f02', front: 'Delta of a put', back: '$\\Delta_P = N(d_1) - 1$, ranges from $-1$ (deep ITM) to 0 (deep OTM). ATM $\\approx -0.50$.', tags: ['greeks', 'delta'] },
    { id: 'd6-f03', front: 'Gamma formula', back: '$\\Gamma = \\frac{n(d_1)}{S\\sigma\\sqrt{T}}$. Same for calls and puts. Highest for ATM, near expiry.', tags: ['greeks', 'gamma'] },
    { id: 'd6-f04', front: 'Vega formula', back: '$\\mathcal{V} = S\\sqrt{T} \\cdot n(d_1)$. Same for calls and puts. Highest for ATM, far from expiry.', tags: ['greeks', 'vega'] },
    { id: 'd6-f05', front: 'Gamma-theta tradeoff (BS PDE, $r \\approx 0$)', back: '$\\Theta \\approx -\\frac{1}{2}\\sigma^2 S^2 \\Gamma$. Long gamma = pay theta. Short gamma = collect theta.', tags: ['greeks', 'gamma', 'theta'] },
    { id: 'd6-f06', front: 'Break-even daily move for a gamma position', back: '$|\\Delta S|_{\\text{BE}} = \\sqrt{2|\\Theta_{\\text{daily}}|/\\Gamma}$', tags: ['greeks', 'gamma', 'theta'] },
    { id: 'd6-f07', front: 'Gamma P&L from a stock move', back: '$\\frac{1}{2}\\Gamma(\\Delta S)^2$. Always positive for long gamma. Direction does not matter.', tags: ['greeks', 'gamma', 'pnl'] },
    { id: 'd6-f08', front: 'Why is gamma highest near expiry?', back: '$\\Gamma \\propto 1/\\sqrt{T}$. Near expiry, the option is very sensitive to whether it is ITM or OTM.', tags: ['greeks', 'gamma'] },
    { id: 'd6-f09', front: 'Why is vega highest far from expiry?', back: '$\\mathcal{V} \\propto \\sqrt{T}$. Longer-dated options are more sensitive to vol because vol has more time to act.', tags: ['greeks', 'vega'] },
    { id: 'd6-f10', front: 'Full BS PDE in Greek form', back: '$\\Theta + \\frac{1}{2}\\sigma^2 S^2 \\Gamma + rS\\Delta = rV$', tags: ['greeks', 'pde'] },
    { id: 'd6-f11', front: 'Rho of a call', back: '$\\rho_C = KTe^{-rT}N(d_2) > 0$. Calls benefit from higher rates (higher forward).', tags: ['greeks', 'rho'] },
    { id: 'd6-f12', front: 'Put-call parity and Greek relationships', back: '$\\Delta_C - \\Delta_P = 1$. $\\Gamma_C = \\Gamma_P$. $\\mathcal{V}_C = \\mathcal{V}_P$. $\\Theta_C - \\Theta_P = rKe^{-rT}$.', tags: ['greeks', 'put-call-parity'] },
  ],
  interactiveTools: ['greek-visualizer', 'delta-hedging', 'bs-calculator'],
  cheatSheet: [
    { topic: 'Delta (Call/Put)', formula: 'N(d₁) / N(d₁)-1', description: 'Hedge ratio; ATM ≈ ±0.50' },
    { topic: 'Gamma', formula: 'n(d₁)/(Sσ√T)', description: 'Same for calls/puts; peaks ATM near expiry' },
    { topic: 'Theta (approx)', formula: 'Θ ≈ -½σ²S²Γ (when r≈0)', description: 'Time decay; locked to gamma' },
    { topic: 'Vega', formula: 'S√T·n(d₁)', description: 'Same for calls/puts; peaks ATM far from expiry' },
    { topic: 'Rho (Call)', formula: 'KTe⁻ʳᵀN(d₂)', description: 'Rate sensitivity; usually small for equities' },
    { topic: 'BS PDE', formula: 'Θ + ½σ²S²Γ + rSΔ = rV', description: 'Links all Greeks; must hold at every point' },
    { topic: 'Gamma P&L', formula: '½Γ(ΔS)²', description: 'P&L from stock move; direction-independent' },
    { topic: 'Break-even Move', formula: '√(2|Θ_daily|/Γ)', description: 'Stock move needed for gamma to offset theta' },
  ],
  summary: [
    '$\\Delta_C = N(d_1)$, $\\Delta_P = N(d_1) - 1$. ATM delta $\\approx \\pm 0.50$.',
    '$\\Gamma = n(d_1)/(S\\sigma\\sqrt{T})$: highest ATM, near expiry. Same for calls and puts.',
    '$\\Theta \\approx -\\frac{1}{2}\\sigma^2 S^2 \\Gamma$: gamma and theta are locked in opposition.',
    'Vega $= S\\sqrt{T} n(d_1)$: highest ATM, far from expiry. Same for calls and puts.',
    'BS PDE: $\\Theta + \\frac{1}{2}\\sigma^2 S^2 \\Gamma + rS\\Delta = rV$ links all Greeks.',
    'Break-even daily move $= \\sqrt{2|\\Theta_{\\text{daily}}|/\\Gamma}$.',
  ],
};

export default day06;
