import { DayContent } from './types';

const day09: DayContent = {
  dayNumber: 9,
  title: 'Early Exercise for American Options',
  subtitle: 'Natenberg Chapter 12',
  week: 2,
  chapters: ['Chapter 12'],
  estimatedMinutes: 110,
  prerequisites: [1, 2, 3, 4, 5, 6, 7, 8],
  objectives: [
    'Prove why an American call on a non-dividend-paying stock should never be exercised early',
    'Identify the conditions under which early exercise of an American call is optimal (dividends)',
    'Determine the early exercise boundary for American puts',
    'Calculate the early exercise premium for American vs. European options',
    'Apply the dividend threshold rule: exercise when dividend exceeds remaining time value',
  ],
  theory: {
    sections: [
      {
        title: 'Why Never Early Exercise a Call on a Non-Dividend Stock?',
        blocks: [
          {
            type: 'text',
            body: 'This is one of the most important results in options theory and a classic interview question. An American call on a **non-dividend-paying** stock is **never** optimally exercised early. The intuition: exercising early forfeits the time value of the option and requires paying the strike price today rather than later (losing the interest on $K$).',
          },
          {
            type: 'concept',
            title: 'Three Reasons Not to Early Exercise a Call',
            body: '(1) **Insurance value**: A call provides downside protection that is lost upon exercise. Holding the call limits your loss to the premium; exercising exposes you to unlimited downside. (2) **Time value of money**: By exercising, you pay $K$ now instead of later, losing interest on $K$. (3) **Optionality**: The option to wait and decide later is always worth something. These three reasons combine to make early exercise strictly suboptimal.',
          },
          {
            type: 'formula',
            latex: 'C_{\\text{Am}} \\geq \\max(S - K, 0) \\geq S - K',
            label: 'American Call Lower Bound',
            explanation: 'The American call is always worth at least its intrinsic value. But more importantly, $C \\geq S - Ke^{-rT} > S - K$ (the European lower bound exceeds intrinsic). So selling the call always dominates exercising.',
          },
          {
            type: 'callout',
            variant: 'key-insight',
            body: 'The proof is simple: $C \\geq S - Ke^{-rT} > S - K$ (since $e^{-rT} < 1$). Exercising gives you $S - K$. Selling the call gives you at least $S - Ke^{-rT}$. Selling always dominates. QED.',
          },
          {
            type: 'example',
            title: 'Why Not Exercise Early?',
            problem: 'A deep ITM American call with $S = 150$, $K = 100$, $T = 0.5$, $r = 5\\%$. The call trades at $52$. Should you exercise?',
            solution: [
              'Intrinsic value (from exercise) = $150 - 100 = 50$.',
              'Call market value = $52 > 50$.',
              'European lower bound = $S - Ke^{-rT} = 150 - 100 \\cdot e^{-0.025} = 150 - 97.53 = 52.47$.',
              'Even the absolute minimum value ($52.47$) exceeds the exercise value ($50$).',
              'You would lose $52 - 50 = \\$2$ by exercising instead of selling.',
              'Never exercise early. Sell the call if you want to exit the position.',
            ],
          },
        ],
      },
      {
        title: 'Early Exercise for Calls on Dividend-Paying Stocks',
        blocks: [
          {
            type: 'text',
            body: 'The only time it may be optimal to early exercise an American call is **just before an ex-dividend date**. When a stock goes ex-dividend, the stock price drops by approximately the dividend amount. The call holder does not receive the dividend. If the dividend is large enough relative to the remaining time value, exercising to capture the dividend is optimal.',
          },
          {
            type: 'formula',
            latex: '\\text{Exercise if: } D > K(1 - e^{-r(T - t_D)}) + \\text{Time Value of Put}',
            label: 'Early Exercise Condition for Calls',
            explanation: 'Exercise the call just before the ex-date if the dividend $D$ exceeds the interest savings from delaying payment of $K$ plus the time value of the corresponding put. The put time value represents the insurance you give up by exercising.',
          },
          {
            type: 'concept',
            title: 'Simplified Rule of Thumb',
            body: 'For deep ITM calls where the put is far OTM (and its time value is negligible): exercise when $D > K \\cdot r \\cdot (T - t_D)$. In words: exercise when the dividend exceeds the interest earned by delaying payment of the strike. For near-ATM calls, the put time value matters and the decision is more nuanced.',
          },
          {
            type: 'example',
            title: 'Dividend-Triggered Early Exercise',
            problem: 'Stock at $110, $K = 100$ call, 3 months to expiry, ex-dividend in 1 week with $D = \\$3$. $r = 4\\%$. Remaining time after ex-date: 11 weeks. Should you exercise?',
            solution: [
              'Interest savings from not exercising = $K \\cdot (1 - e^{-r(T-t_D)}) = 100 \\cdot (1 - e^{-0.04 \\times 11/52})$',
              '$= 100 \\cdot (1 - e^{-0.00846}) = 100 \\times 0.00842 = 0.84$',
              'Put time value: With $S = 110$, the 100-strike put is deep OTM. Time value $\\approx 0.10$ (very small).',
              'Threshold: $0.84 + 0.10 = 0.94$',
              '$D = 3.00 > 0.94$. Yes, exercise just before the ex-date.',
              'By exercising, you capture the $3 dividend, losing only $0.94 in time value + interest.',
            ],
          },
          {
            type: 'callout',
            variant: 'tip',
            body: 'At Optiver, early exercise decisions are automated. The system checks every position nightly against the ex-date calendar. Understanding the logic behind the decision is essential for debugging and overriding the system when needed.',
          },
        ],
      },
      {
        title: 'Early Exercise for American Puts',
        blocks: [
          {
            type: 'text',
            body: 'Unlike calls, American puts **can** be optimally exercised early even without dividends. The intuition: when a put is deep ITM, the stock is near zero. The put is worth nearly $K$. By exercising, you receive $K$ immediately and can invest it at $r$. Waiting means foregoing interest on $K$. When this interest exceeds the remaining time value (optionality), early exercise is optimal.',
          },
          {
            type: 'formula',
            latex: 'P_{\\text{Am}} \\geq K - S \\quad \\text{(always)}',
            label: 'American Put Lower Bound',
            explanation: 'An American put is always worth at least its intrinsic value. Unlike the European put, which can trade below intrinsic when deep ITM (since $P_{\\text{Eu}} \\geq Ke^{-rT} - S$, which can be less than $K - S$).',
          },
          {
            type: 'concept',
            title: 'The Critical Stock Price $S^*$',
            body: 'There exists a critical stock price $S^*$ below which it is optimal to exercise the American put immediately. At $S^*$, the value of holding the put (time value) exactly equals the interest earned by exercising and investing $K - S^*$ at rate $r$. Above $S^*$, the put is "alive" (hold it). Below $S^*$, the put is "dead" (exercise it).',
          },
          {
            type: 'formula',
            latex: 'P_{\\text{Am}} - P_{\\text{Eu}} = \\text{Early Exercise Premium} \\geq 0',
            label: 'Early Exercise Premium',
            explanation: 'The American put is always worth at least as much as the European put. The difference is the early exercise premium, which increases as the put goes deeper ITM and as interest rates rise.',
          },
          {
            type: 'callout',
            variant: 'warning',
            body: 'Dividends make early exercise of puts LESS likely (not more). The stock is expected to drop on the ex-date, which increases the put value. Waiting to capture the drop is usually better than exercising before the dividend.',
          },
        ],
      },
      {
        title: 'European vs. American Option Pricing',
        blocks: [
          {
            type: 'text',
            body: 'For calls on non-dividend stocks: $C_{\\text{Am}} = C_{\\text{Eu}}$. The early exercise right has zero value. For puts: $P_{\\text{Am}} \\geq P_{\\text{Eu}}$, with the difference being the early exercise premium. For calls on dividend-paying stocks: $C_{\\text{Am}} \\geq C_{\\text{Eu}}$, with the premium depending on dividend size and timing.',
          },
          {
            type: 'table',
            headers: ['Option Type', 'Non-Dividend Stock', 'Dividend Stock'],
            rows: [
              ['American Call', 'Never exercise early; $C_{Am} = C_{Eu}$', 'May exercise before ex-date if $D$ large enough'],
              ['American Put', 'May exercise early when deep ITM', 'Less likely to exercise early (wait for div drop)'],
              ['Early Exercise Premium (Call)', 'Zero', 'Positive; increases with dividend size'],
              ['Early Exercise Premium (Put)', 'Positive; increases with rates', 'Smaller than no-div case'],
            ],
          },
        ],
      },
    ],
  },
  exercises: [
    {
      id: 'd9-early-01',
      exerciseType: 'true-false',
      difficulty: 'easy',
      topic: 'early-exercise',
      tags: ['early-exercise', 'american-call'],
      timeEstimateSeconds: 15,
      statement: 'It is never optimal to exercise an American call option early on a non-dividend-paying stock.',
      correct: true,
      explanation: 'This is a foundational result. The call is always worth more alive (with time value) than dead (exercised for intrinsic). Selling the call always dominates exercising because $C \\geq S - Ke^{-rT} > S - K$.',
      solutionSteps: [
        'European lower bound: $C \\geq S - Ke^{-rT}$',
        'Since $e^{-rT} < 1$: $S - Ke^{-rT} > S - K$ = intrinsic value.',
        'The option is worth more than its exercise value, so never exercise.',
      ],
    },
    {
      id: 'd9-early-02',
      exerciseType: 'true-false',
      difficulty: 'easy',
      topic: 'early-exercise',
      tags: ['early-exercise', 'american-put'],
      timeEstimateSeconds: 15,
      statement: 'It is never optimal to exercise an American put option early on a non-dividend-paying stock.',
      correct: false,
      explanation: 'Unlike calls, American puts CAN be optimally exercised early. When the put is deep ITM, the interest earned on $K - S$ from immediate exercise can exceed the remaining time value.',
      solutionSteps: [
        'For European puts: $P_{Eu} \\geq Ke^{-rT} - S$, which can be LESS than $K - S$.',
        'This means the European put can trade below intrinsic value when deep ITM.',
        'The American put is worth at least $K - S$, so it may be optimal to exercise and invest the proceeds.',
      ],
    },
    {
      id: 'd9-early-03',
      exerciseType: 'multiple-choice',
      difficulty: 'easy',
      topic: 'early-exercise',
      tags: ['early-exercise', 'american-call'],
      timeEstimateSeconds: 30,
      question: 'Which of the following gives a reason NOT to exercise an American call early?',
      options: [
        'You lose the insurance (downside protection) the call provides',
        'You pay the strike price now instead of later, losing interest',
        'You forfeit the remaining time value (optionality)',
        'All of the above',
      ],
      correctIndex: 3,
      explanation: 'All three are valid reasons. (1) The call provides a floor on losses. (2) Exercising requires paying $K$ now vs. later. (3) The option to wait is always valuable.',
      solutionSteps: [
        'Insurance: exercising exposes you to downside; holding the call does not.',
        'Interest: paying $K$ now costs $K - Ke^{-rT}$ in interest.',
        'Optionality: the right to wait and see is valuable.',
        'All three reasons apply. Answer: D.',
      ],
    },
    {
      id: 'd9-early-04',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'early-exercise',
      tags: ['early-exercise', 'american-call', 'dividend'],
      timeEstimateSeconds: 90,
      question: 'Stock at $105, 100-strike American call, 6 months to expiry. A $2 dividend in 1 month. $r = 5\\%$. Remaining time after ex-date: 5 months. Assume the put time value is negligible. Should you exercise? What is the exercise threshold?',
      correctAnswer: 2.08,
      tolerance: 0.05,
      unit: '$',
      hint: 'Calculate the interest savings from not exercising, which is the threshold the dividend must exceed.',
      explanation: 'Threshold = $K(1 - e^{-r(T - t_D)}) = 100(1 - e^{-0.05 \\times 5/12}) = 100(1 - e^{-0.02083}) = 100 \\times 0.02062 = 2.06$. Since $D = 2.00 < 2.06$, do NOT exercise. The threshold is $\\$2.06$.',
      solutionSteps: [
        'Interest savings from delaying exercise: $K(1 - e^{-r(T-t_D)})$',
        '$= 100(1 - e^{-0.05 \\times 5/12}) = 100(1 - e^{-0.02083})$',
        '$= 100 \\times 0.02062 = \\$2.06$',
        'Adding negligible put time value, threshold $\\approx \\$2.08$.',
        'Since $D = 2.00 < 2.08$, do NOT exercise.',
      ],
    },
    {
      id: 'd9-early-05',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'early-exercise',
      tags: ['early-exercise', 'american-call', 'dividend'],
      timeEstimateSeconds: 90,
      question: 'Stock at $120, 100-strike American call, 3 months to expiry. Ex-dividend in 2 weeks with $D = \\$4$. $r = 6\\%$. Remaining time after ex-date: 10 weeks. What is the minimum dividend that would trigger early exercise? (Ignore put time value.)',
      correctAnswer: 1.15,
      tolerance: 0.05,
      unit: '$',
      explanation: 'Threshold = $K(1 - e^{-r(T - t_D)}) = 100(1 - e^{-0.06 \\times 10/52}) = 100(1 - e^{-0.01154}) = 100 \\times 0.01147 = 1.15$. Since $D = 4.00 > 1.15$, exercise. But the question asks for the minimum trigger, which is $\\$1.15$.',
      solutionSteps: [
        'Threshold = $K(1 - e^{-r(T - t_D)})$',
        'Remaining time after ex-date: $10/52$ years $= 0.1923$ years',
        '$= 100(1 - e^{-0.06 \\times 0.1923}) = 100(1 - e^{-0.01154})$',
        '$= 100 \\times 0.01147 = \\$1.15$',
        'Any dividend above $\\$1.15$ triggers exercise (ignoring put time value).',
      ],
    },
    {
      id: 'd9-early-06',
      exerciseType: 'free-response',
      difficulty: 'medium',
      topic: 'early-exercise',
      tags: ['early-exercise', 'american-put'],
      timeEstimateSeconds: 120,
      question: 'Explain intuitively why it can be optimal to exercise an American put early, but not an American call (on a non-dividend stock). What is fundamentally different about the two cases?',
      modelAnswer: 'The key asymmetry is in the **time value of money** effect on the strike. For a call, exercising means paying $K$ now. Delaying saves interest on $K$. For a put, exercising means receiving $K$ now. Delaying loses interest on $K$. So for calls, time works in your favor (delay is free money). For puts, time works against you (delay costs interest). Additionally, a stock can only fall to zero (bounded downside for puts), but can rise infinitely (unbounded upside for calls). When a put is deep ITM (stock near zero), the maximum remaining upside from waiting is small relative to the interest lost. The option is essentially "maxed out" and should be exercised.',
      explanation: 'The fundamental difference is whether delaying exercise earns interest (calls) or loses interest (puts) on the strike price.',
      solutionSteps: [
        'Call exercise: pay $K$ now. Delay = save interest on $K$. Always better to delay.',
        'Put exercise: receive $K$ now. Delay = lose interest on $K$. Sometimes better to exercise.',
        'Bounded vs. unbounded payoff: put payoff maxes at $K$ (stock at 0); call payoff is unlimited.',
        'When put is deep ITM, remaining optionality is small vs. interest lost. Exercise.',
      ],
    },
    {
      id: 'd9-early-07',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'early-exercise-premium',
      tags: ['early-exercise', 'american-put', 'premium'],
      timeEstimateSeconds: 120,
      question: 'A European put is worth $8.50 and an American put (same terms) is worth $9.20. Both have $K = 100$, $S = 90$, $T = 1$, $r = 5\\%$. What is the early exercise premium? Also verify: is the European put below intrinsic?',
      correctAnswer: 0.70,
      tolerance: 0.01,
      unit: '$',
      explanation: 'Early exercise premium = $P_{Am} - P_{Eu} = 9.20 - 8.50 = 0.70$. Intrinsic = $K - S = 10$. European put = $8.50 < 10$. Yes, the European put is below intrinsic. This is possible because $P_{Eu} \\geq Ke^{-rT} - S = 95.12 - 90 = 5.12$, which is above zero but below $K - S = 10$.',
      solutionSteps: [
        'Early exercise premium = $P_{Am} - P_{Eu} = 9.20 - 8.50 = \\$0.70$',
        'Intrinsic value = $K - S = 100 - 90 = 10$',
        'European put = $8.50 < 10$: yes, it is below intrinsic.',
        'European lower bound: $Ke^{-rT} - S = 100 \\cdot e^{-0.05} - 90 = 95.12 - 90 = 5.12$.',
        'The European put ($8.50$) is above this bound but below intrinsic ($10$). This is normal for deep ITM European puts.',
      ],
    },
    {
      id: 'd9-early-08',
      exerciseType: 'multiple-choice',
      difficulty: 'medium',
      topic: 'early-exercise',
      tags: ['early-exercise', 'american-put', 'dividends'],
      timeEstimateSeconds: 45,
      question: 'How do dividends affect the early exercise decision for American puts?',
      options: [
        'Dividends make early exercise MORE likely for puts',
        'Dividends make early exercise LESS likely for puts',
        'Dividends have no effect on put early exercise',
        'The effect depends on the moneyness of the put',
      ],
      correctIndex: 1,
      explanation: 'Dividends make early exercise of puts LESS likely. An upcoming dividend will cause the stock price to drop, which increases the put value. It is better to wait for the dividend-driven drop than to exercise before it. This is the opposite of the call case.',
      solutionSteps: [
        'A dividend causes the stock to drop by approximately $D$ on the ex-date.',
        'For a put holder, this drop increases the put value.',
        'Exercising before the drop means missing out on this gain.',
        'Therefore, dividends make early exercise of puts less likely.',
      ],
    },
    {
      id: 'd9-early-09',
      exerciseType: 'multi-step',
      difficulty: 'hard',
      topic: 'early-exercise',
      tags: ['early-exercise', 'american-call', 'dividend'],
      timeEstimateSeconds: 180,
      question: 'Stock at $95, 90-strike American call, 6 months to expiry. Two dividends: $D_1 = \\$1.50$ in 2 months, $D_2 = \\$1.50$ in 5 months. $r = 5\\%$. (a) Should you exercise before $D_1$? (b) Should you exercise before $D_2$? (Ignore put time value.)',
      steps: [
        {
          prompt: 'What is the exercise threshold before $D_1$ (interest saving from delaying to expiry minus the period after D1)?',
          correctAnswer: 1.48,
          tolerance: 0.1,
          unit: '$',
          stepExplanation: 'If you exercise before $D_1$, you give up interest on $K$ from month 2 to month 6 (4 months). Threshold = $K(1 - e^{-r \\times 4/12}) = 90(1 - e^{-0.05 \\times 1/3}) = 90(1 - e^{-0.01667}) = 90 \\times 0.01653 = 1.49$. Also need to consider that if you don\'t exercise, you can still exercise before $D_2$. So the threshold is roughly $K(1 - e^{-r(t_2 - t_1)}) = 90(1 - e^{-0.05 \\times 3/12}) = 90(1 - e^{-0.0125}) = 90 \\times 0.01242 = 1.12$. Since you have the option to exercise before $D_2$ too, the relevant interest saving is just from $t_1$ to $t_2$: $1.12$. Then $D_1 = 1.50 > 1.12$, so you would exercise before $D_1$. But actually, the standard approach checks against the last dividend first. Let me use the threshold for the full remaining time: $K(1 - e^{-r(T - t_1)}) = 90(1 - e^{-0.05 \\times 4/12}) = 1.49$. $D_1 = 1.50 > 1.49$. Exercise.',
        },
        {
          prompt: 'What is the exercise threshold before $D_2$?',
          correctAnswer: 0.37,
          tolerance: 0.05,
          unit: '$',
          stepExplanation: 'Threshold = $K(1 - e^{-r(T - t_2)}) = 90(1 - e^{-0.05 \\times 1/12}) = 90(1 - e^{-0.00417}) = 90 \\times 0.00416 = 0.37$. $D_2 = 1.50 > 0.37$. Exercise before $D_2$ as well.',
        },
      ],
      explanation: 'With multiple dividends, check each ex-date. Usually only the last ex-date before expiry matters most, but large early dividends can trigger earlier exercise.',
      solutionSteps: [
        'Before $D_1$: Threshold = $K(1 - e^{-r(T - t_1)}) = 90(1 - e^{-0.01667}) = 1.49$. $D_1 = 1.50 > 1.49$: exercise.',
        'Before $D_2$: Threshold = $K(1 - e^{-r(T - t_2)}) = 90(1 - e^{-0.00417}) = 0.37$. $D_2 = 1.50 > 0.37$: exercise.',
        'Both dividends trigger exercise. In practice, you would exercise before $D_1$ (the first opportunity).',
      ],
    },
    {
      id: 'd9-early-10',
      exerciseType: 'true-false',
      difficulty: 'medium',
      topic: 'early-exercise',
      tags: ['early-exercise', 'pricing'],
      timeEstimateSeconds: 20,
      statement: 'For a non-dividend stock, American and European calls have the same value.',
      correct: true,
      explanation: 'Since early exercise of an American call on a non-dividend stock is never optimal, the early exercise premium is zero. Therefore $C_{Am} = C_{Eu}$.',
      solutionSteps: [
        'Early exercise is never optimal for calls on non-dividend stocks.',
        'The early exercise right has zero value.',
        'Therefore $C_{Am} = C_{Eu}$.',
      ],
    },
    {
      id: 'd9-early-11',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'early-exercise',
      tags: ['early-exercise', 'american-put', 'boundary'],
      timeEstimateSeconds: 120,
      question: 'For an American put with $K = 50$, $r = 8\\%$, $\\sigma = 30\\%$, $T = 1$, the critical stock price (early exercise boundary) is approximately $S^* = 36$. If the stock drops to $34$, what is the minimum value of the American put?',
      correctAnswer: 16.00,
      tolerance: 0.01,
      unit: '$',
      explanation: 'Below the critical stock price, the American put should be exercised immediately. Its value equals the intrinsic value: $P_{Am} = K - S = 50 - 34 = 16$. The put is "dead" (should be exercised).',
      solutionSteps: [
        'The critical stock price $S^* = 36$ is the boundary below which exercise is optimal.',
        'At $S = 34 < S^* = 36$, the put should be exercised immediately.',
        'Exercise value = $K - S = 50 - 34 = \\$16.00$.',
        'The American put is worth exactly its intrinsic value in this region.',
      ],
    },
    {
      id: 'd9-early-12',
      exerciseType: 'multiple-choice',
      difficulty: 'hard',
      topic: 'early-exercise',
      tags: ['early-exercise', 'interest-rates'],
      timeEstimateSeconds: 45,
      question: 'If interest rates increase, what happens to the early exercise premium of an American put?',
      options: [
        'It decreases because higher rates reduce put values',
        'It increases because the cost of delaying exercise (lost interest on $K$) is higher',
        'It stays the same because rates do not affect early exercise',
        'It increases for ITM puts but decreases for OTM puts',
      ],
      correctIndex: 1,
      explanation: 'Higher rates mean the opportunity cost of NOT exercising the put (and NOT investing $K$ at the higher rate) is larger. This makes early exercise more attractive and increases the early exercise premium.',
      solutionSteps: [
        'Exercising a put gives you $K$ cash to invest at rate $r$.',
        'Higher $r$ means more interest earned from early exercise.',
        'The cost of waiting (lost interest) increases with $r$.',
        'Therefore the early exercise premium increases with rates.',
      ],
    },
    {
      id: 'd9-early-13',
      exerciseType: 'free-response',
      difficulty: 'interview',
      topic: 'early-exercise',
      tags: ['early-exercise', 'interview'],
      timeEstimateSeconds: 120,
      question: 'An interviewer asks: "Why should you never early exercise an American call on a non-dividend stock?" Give a concise, rigorous answer.',
      modelAnswer: 'Because selling the call always dominates exercising. Proof: By the European call lower bound, $C \\geq S - Ke^{-rT}$. Exercising gives $S - K$. Since $Ke^{-rT} < K$ (for $r > 0$, $T > 0$), we have $S - Ke^{-rT} > S - K$, so $C > S - K$. The call is always worth more than its exercise value. Alternatively: by exercising, you (1) forfeit insurance against the stock dropping below $K$, (2) pay $K$ now instead of later (losing interest), and (3) give up all remaining optionality. All three effects are value-destroying.',
      explanation: 'This is the most commonly asked early exercise question in trading interviews.',
      solutionSteps: [
        'State the European lower bound: $C \\geq S - Ke^{-rT}$.',
        'Since $r > 0$: $Ke^{-rT} < K$, so $S - Ke^{-rT} > S - K$.',
        'Therefore $C > S - K$ = exercise value.',
        'Selling always beats exercising. Three reasons: insurance, interest, optionality.',
      ],
    },
    {
      id: 'd9-early-14',
      exerciseType: 'numeric',
      difficulty: 'interview',
      topic: 'early-exercise',
      tags: ['early-exercise', 'mental-math', 'interview'],
      timeEstimateSeconds: 30,
      question: 'Mental math: Stock at $100, 100-strike American put, $r = 10\\%$, $T = 1$. The European put is worth $7$. What is the minimum value of the American put?',
      correctAnswer: 7.00,
      tolerance: 0.01,
      unit: '$',
      explanation: '$P_{Am} \\geq P_{Eu} = 7$ and $P_{Am} \\geq K - S = 0$. So minimum is $\\max(7, 0) = 7$. Note: even though the European put might be below intrinsic for ITM puts, here the put is ATM with intrinsic = 0.',
      solutionSteps: [
        '$P_{Am} \\geq P_{Eu} = 7$',
        '$P_{Am} \\geq K - S = 100 - 100 = 0$',
        'Minimum American put value = $\\max(7, 0) = \\$7.00$.',
      ],
    },
    {
      id: 'd9-speed-01',
      exerciseType: 'speed-drill',
      difficulty: 'medium',
      topic: 'early-exercise',
      tags: ['early-exercise', 'speed-drill'],
      timeEstimateSeconds: 120,
      timeLimitSeconds: 120,
      problems: [
        { prompt: 'American call, no dividends. Early exercise optimal? (1=yes, 0=no)', correctAnswer: 0, tolerance: 0 },
        { prompt: 'American put, deep ITM, high rates. Early exercise possible? (1=yes, 0=no)', correctAnswer: 1, tolerance: 0 },
        { prompt: 'Stock at $50, K=$100 American put, r=5%, T=1. Put intrinsic?', correctAnswer: 50, tolerance: 0.01 },
        { prompt: 'European put lower bound: K*e^(-0.05)-S, K=100, S=90, T=1. Value?', correctAnswer: 5.12, tolerance: 0.1 },
        { prompt: 'Is the European put below intrinsic? (K-S=10, Eu put bound=5.12). 1=yes possible, 0=no', correctAnswer: 1, tolerance: 0 },
        { prompt: 'Am call = Eu call for non-div stock? (1=yes, 0=no)', correctAnswer: 1, tolerance: 0 },
      ],
      explanation: 'Speed drill covering the key early exercise facts.',
      solutionSteps: [
        'No early exercise for calls on non-div stocks.',
        'Yes, puts can be exercised early, especially deep ITM with high rates.',
        'Intrinsic = $K - S = 100 - 50 = 50$.',
        'European put lower bound = $100e^{-0.05} - 90 = 95.12 - 90 = 5.12$.',
        'Yes, European put can be below intrinsic ($5.12 < 10$).',
        'Yes, American call = European call for non-div stocks.',
      ],
    },
  ],
  cumulativeExercises: [
    {
      id: 'd9-cum-01',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'parity-early-exercise',
      tags: ['put-call-parity', 'early-exercise', 'american'],
      timeEstimateSeconds: 90,
      fromDay: 1,
      question: 'For a non-dividend stock at $100, $r = 5\\%$, $T = 0.5$: the European call at $K = 100$ is $5.00$. What is the European put? What is the American put worth at minimum?',
      correctAnswer: 2.53,
      tolerance: 0.05,
      unit: '$',
      explanation: '$P_{Eu} = C - S + Ke^{-rT} = 5.00 - 100 + 100e^{-0.025} = 5.00 - 100 + 97.53 = 2.53$. American put $\\geq \\max(P_{Eu}, K - S) = \\max(2.53, 0) = 2.53$.',
      solutionSteps: [
        'From parity: $P_{Eu} = C - S + Ke^{-rT} = 5.00 - 100 + 97.53 = 2.53$.',
        '$P_{Am} \\geq P_{Eu} = 2.53$ and $P_{Am} \\geq K - S = 0$.',
        'Minimum American put = $\\$2.53$.',
      ],
    },
    {
      id: 'd9-cum-02',
      exerciseType: 'multiple-choice',
      difficulty: 'medium',
      topic: 'synthetics-early-exercise',
      tags: ['synthetics', 'early-exercise', 'conversion'],
      timeEstimateSeconds: 60,
      fromDay: 8,
      question: 'A trader holds a conversion (long stock, long put, short call) on an American option. What additional risk does the conversion have compared to a European conversion?',
      options: [
        'The long put might be exercised early by the trader, reducing profits',
        'The short call might be assigned early if a dividend is coming',
        'The stock might gap through the strike',
        'There is no additional risk since conversions are always risk-free',
      ],
      correctIndex: 1,
      explanation: 'In an American conversion, the short call can be assigned early (especially before a dividend). This forces the trader to deliver the stock and changes the cash flow timing, potentially reducing the arbitrage profit.',
      solutionSteps: [
        'European conversion: no early exercise risk. Cash flows are locked.',
        'American conversion: the counterparty holding the call may exercise early.',
        'Early assignment on the short call means: deliver stock, receive $K$.',
        'If this happens before planned, the trader loses the remaining time value.',
        'This is particularly risky around dividend ex-dates.',
      ],
    },
    {
      id: 'd9-cum-03',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'delta-early-exercise',
      tags: ['delta', 'early-exercise', 'american-put'],
      timeEstimateSeconds: 120,
      fromDay: 5,
      question: 'An American put at the early exercise boundary ($S = S^* = 40$, $K = 50$) has a delta of exactly $-1$. Why? What is the gamma at this point?',
      correctAnswer: 0,
      tolerance: 0.01,
      unit: 'gamma',
      explanation: 'At the early exercise boundary, the American put value equals its intrinsic value $K - S$, whose slope is $-1$. The delta is exactly $-1$. Below $S^*$, the put is exercised (value = $K - S$, delta = $-1$, gamma = $0$). At $S^*$, the put transitions from "alive" to "dead." Gamma is $0$ at and below the boundary.',
      solutionSteps: [
        'At $S \\leq S^*$: put value = $K - S$ (intrinsic). Slope = $-1$. Delta = $-1$.',
        'The second derivative of $K - S$ is $0$.',
        'Therefore gamma = $0$ at and below the boundary.',
        'At $S > S^*$ (just above), gamma is positive (the put is alive with curvature).',
      ],
    },
    {
      id: 'd9-cum-04',
      exerciseType: 'free-response',
      difficulty: 'hard',
      topic: 'volatility-early-exercise',
      tags: ['volatility', 'early-exercise'],
      timeEstimateSeconds: 120,
      fromDay: 7,
      question: 'How does implied volatility affect the early exercise decision for American puts? Does higher vol make early exercise more or less likely?',
      modelAnswer: 'Higher implied volatility makes early exercise LESS likely. Here is why: higher vol increases the time value (optionality) of the put. At high vol, there is a greater chance the stock could move significantly in the remaining time, making the option to wait more valuable. The critical stock price $S^*$ moves lower when vol is higher, meaning the stock has to fall further before early exercise becomes optimal. Conversely, low vol (near zero) makes early exercise more likely because there is little chance of the stock moving significantly.',
      explanation: 'Higher vol increases optionality, which competes against the interest earned from early exercise.',
      solutionSteps: [
        'Higher vol increases put time value (more chance of profitable moves).',
        'Early exercise forfeits this time value.',
        'With high vol, the forgone time value exceeds the interest benefit.',
        'Therefore the critical price $S^*$ decreases: stock must fall further to trigger exercise.',
        'In the limit: $\\sigma \\to 0$ means exercise whenever $S < K$ (interest always wins); $\\sigma \\to \\infty$ means never exercise (time value always wins).',
      ],
    },
    {
      id: 'd9-cum-05',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'forward-early-exercise',
      tags: ['forward', 'early-exercise'],
      timeEstimateSeconds: 90,
      fromDay: 1,
      question: 'Stock at $100, $r = 6\\%$, $T = 0.25$. A deep ITM European put ($K = 130$) has a lower bound of $Ke^{-rT} - S$. Calculate this and compare to intrinsic.',
      correctAnswer: 27.07,
      tolerance: 0.1,
      unit: '$',
      explanation: 'European put lower bound = $Ke^{-rT} - S = 130 \\cdot e^{-0.015} - 100 = 128.07 - 100 = 28.07$. Intrinsic = $130 - 100 = 30$. The European lower bound ($28.07$) is below intrinsic ($30$), confirming that a European put can trade below intrinsic.',
      solutionSteps: [
        '$Ke^{-rT} = 130 \\cdot e^{-0.06 \\times 0.25} = 130 \\cdot e^{-0.015} = 130 \\times 0.98511 = 128.06$',
        'European lower bound = $128.06 - 100 = 28.06$.',
        'Intrinsic = $130 - 100 = 30$.',
        'Gap = $30 - 28.06 = 1.94$. The European put can be up to $\\$1.94$ below intrinsic.',
        'This is why the American put (which cannot trade below intrinsic) has a positive early exercise premium.',
      ],
    },
    {
      id: 'd9-cum-06',
      exerciseType: 'scenario',
      difficulty: 'hard',
      topic: 'early-exercise-greeks',
      tags: ['early-exercise', 'theta', 'rho'],
      timeEstimateSeconds: 150,
      fromDay: 5,
      question: 'Consider an American put near the early exercise boundary. How do theta and rho behave?',
      scenarios: [
        {
          description: 'Stock just above S* (put is alive): What is the sign of theta?',
          shocks: [{ variable: 'stock_price', change: 1 }],
          expectedAnswer: -1,
          tolerance: 0,
          unit: 'sign (-1 or +1)',
        },
        {
          description: 'Stock just below S* (put is dead/exercised): What is theta?',
          shocks: [{ variable: 'stock_price', change: -1 }],
          expectedAnswer: 0,
          tolerance: 0,
          unit: 'sign (0 if zero)',
        },
      ],
      explanation: 'Just above $S^*$: the American put is alive and has negative theta (time decay). Just below $S^*$: the put should be exercised immediately. Once exercised, there is no more theta (it becomes a stock/cash position). This is a discontinuity in the Greeks at the boundary.',
      solutionSteps: [
        'Above $S^*$: Put is alive. Time decay exists. Theta < 0 (sign = -1).',
        'Below $S^*$: Put should be exercised. Value = $K - S$ (no time component). Theta = 0.',
        'At the boundary: theta jumps from negative to zero (discontinuity).',
      ],
    },
  ],
  flashcards: [
    { id: 'd9-f01', front: 'Should you ever early exercise an American call on a non-dividend stock?', back: 'Never. The call is always worth more alive than dead: $C \\geq S - Ke^{-rT} > S - K$.', tags: ['early-exercise'] },
    { id: 'd9-f02', front: 'When should you early exercise an American call on a dividend stock?', back: 'Just before the ex-dividend date, if $D > K(1 - e^{-r(T-t_D)}) + \\text{put time value}$. I.e., when the dividend exceeds the interest savings plus insurance value.', tags: ['early-exercise', 'dividend'] },
    { id: 'd9-f03', front: 'Can American puts be optimally exercised early?', back: 'Yes, even without dividends. When deep ITM, the interest on $K$ from exercise exceeds remaining time value.', tags: ['early-exercise'] },
    { id: 'd9-f04', front: 'What is the critical stock price $S^*$ for an American put?', back: 'The price below which immediate exercise is optimal. At $S^*$: time value = interest on $K - S^*$.', tags: ['early-exercise', 'boundary'] },
    { id: 'd9-f05', front: 'How do dividends affect American put early exercise?', back: 'Dividends make early exercise LESS likely. The stock drops on ex-date, increasing put value. Better to wait.', tags: ['early-exercise', 'dividend'] },
    { id: 'd9-f06', front: 'American call vs European call value (no dividends)', back: '$C_{Am} = C_{Eu}$. The early exercise right has zero value.', tags: ['early-exercise', 'pricing'] },
    { id: 'd9-f07', front: 'American put vs European put value', back: '$P_{Am} \\geq P_{Eu}$. The difference is the early exercise premium, which increases with rates and ITM-ness.', tags: ['early-exercise', 'pricing'] },
    { id: 'd9-f08', front: 'Can a European put trade below intrinsic?', back: 'Yes. $P_{Eu} \\geq Ke^{-rT} - S$, which is less than $K - S$ when $r > 0$. Deep ITM European puts can be below intrinsic.', tags: ['early-exercise', 'european'] },
    { id: 'd9-f09', front: 'Three reasons not to early exercise a call', back: '(1) Lose insurance (downside protection). (2) Pay $K$ now vs. later (lose interest). (3) Forfeit optionality (right to wait).', tags: ['early-exercise'] },
    { id: 'd9-f10', front: 'How does volatility affect put early exercise?', back: 'Higher vol makes early exercise LESS likely (more optionality value). $S^*$ decreases.', tags: ['early-exercise', 'volatility'] },
    { id: 'd9-f11', front: 'How do interest rates affect put early exercise?', back: 'Higher rates make early exercise MORE likely (higher opportunity cost of not investing $K$). $S^*$ increases.', tags: ['early-exercise', 'interest-rates'] },
    { id: 'd9-f12', front: 'Delta of an American put at the early exercise boundary', back: '$\\Delta = -1$ at $S = S^*$ and below. The put tracks intrinsic value dollar-for-dollar.', tags: ['early-exercise', 'greeks'] },
  ],
  interactiveTools: ['bs-calculator', 'payoff-diagram', 'put-call-parity'],
  cheatSheet: [
    { topic: 'Call Early Exercise (no div)', formula: 'Never exercise', description: 'C ≥ S - Ke^{-rT} > S - K' },
    { topic: 'Call Early Exercise (div)', formula: 'Exercise if D > K(1-e^{-r(T-tD)})', description: 'When dividend exceeds interest savings' },
    { topic: 'Put Early Exercise', formula: 'Exercise when S < S*', description: 'Below critical price, interest on K exceeds time value' },
    { topic: 'Am Call = Eu Call', formula: 'C_Am = C_Eu (no div)', description: 'Early exercise right worthless for calls' },
    { topic: 'Am Put ≥ Eu Put', formula: 'P_Am - P_Eu = early exercise premium', description: 'Premium increases with rates and ITM-ness' },
    { topic: 'Eu Put Lower Bound', formula: 'P_Eu ≥ Ke^{-rT} - S', description: 'Can be below intrinsic K-S' },
  ],
  summary: [
    'Never early exercise an American call on a non-dividend stock: $C \\geq S - Ke^{-rT} > S - K$',
    'Exercise calls before ex-dividend when $D > K(1 - e^{-r(T-t_D)}) + \\text{put time value}$',
    'American puts may be exercised early when deep ITM: interest on $K$ exceeds time value',
    'Higher rates increase put early exercise premium; higher vol decreases it',
    'European puts can trade below intrinsic; American puts cannot',
  ],
  trackB: {
    title: 'Extensive-Form Games & Kuhn Poker',
    subtitle: 'Game Trees, Information Sets & Nash Equilibrium',
    objectives: [
      'Distinguish between normal-form and extensive-form game representations',
      'Construct game trees with information sets and chance nodes',
      'Define and compute Nash equilibrium for simple games',
      'Solve Kuhn Poker analytically and identify the equilibrium bluffing frequency',
      'Connect poker strategy concepts to market making and adverse selection',
    ],
    theory: {
      sections: [
        {
          title: 'Normal-Form vs Extensive-Form Games',
          blocks: [
            {
              type: 'text',
              body: 'A **normal-form** (or strategic-form) game is represented by a payoff matrix. Players choose their strategies simultaneously, without observing each other. An **extensive-form** game is represented by a game tree. Players move sequentially, potentially with imperfect information about previous moves. Extensive form is richer and can model timing, information revelation, and bluffing.',
            },
            {
              type: 'table',
              headers: ['Feature', 'Normal-Form', 'Extensive-Form'],
              rows: [
                ['Representation', 'Payoff matrix', 'Game tree'],
                ['Timing', 'Simultaneous moves', 'Sequential moves'],
                ['Information', 'Complete (see matrix)', 'Can be imperfect (info sets)'],
                ['Bluffing', 'Not naturally modeled', 'Naturally modeled via hidden info'],
                ['Example', 'Prisoner\'s Dilemma', 'Poker, chess (imperfect/perfect info)'],
              ],
            },
            {
              type: 'concept',
              title: 'Why Extensive Form for Trading?',
              body: 'Market interactions are inherently sequential and involve private information. A market maker posts quotes (move 1), a trader decides to hit/lift (move 2), then the market maker hedges (move 3). Each player has private information: the market maker knows their inventory, the trader may know upcoming news. Extensive-form games model this naturally.',
            },
          ],
        },
        {
          title: 'Game Trees & Information Sets',
          blocks: [
            {
              type: 'text',
              body: 'A **game tree** has nodes (decision points), edges (actions), and terminal nodes (outcomes with payoffs). **Chance nodes** represent random events (like card deals or market moves). **Information sets** group nodes where a player cannot distinguish between them -- they have the same available actions and the same information.',
            },
            {
              type: 'concept',
              title: 'Perfect vs Imperfect Information',
              body: '**Perfect information**: every information set contains exactly one node (the player knows exactly where they are in the tree). Example: chess. **Imperfect information**: some information sets contain multiple nodes (the player is uncertain about previous moves). Example: poker -- you do not know your opponent\'s card.',
            },
            {
              type: 'example',
              title: 'Simple Game Tree',
              problem: 'A coin is flipped (chance node). Player 1 sees the result, Player 2 does not. Player 1 can say "Heads" or "Tails." Player 2 then guesses the coin. If Player 2 guesses correctly, they win $1 from Player 1. Draw the information structure.',
              solution: [
                'Chance node: Heads (0.5) or Tails (0.5).',
                'Player 1 has 2 information sets (one for each coin outcome): {H} and {T}.',
                'Player 2 has 4 possible states but only 2 information sets: {P1 said "Heads"} and {P1 said "Tails"} -- they cannot distinguish the actual coin.',
                'Player 1 can bluff: say "Heads" when the coin is Tails.',
                'This structure mirrors market making: informed trader (P1) knows the "coin," market maker (P2) only sees the action.',
              ],
            },
            {
              type: 'callout',
              variant: 'key-insight',
              body: 'Information sets are the key concept connecting game theory to trading. A market maker\'s information set groups all possible states of the world consistent with the observable order flow. Adverse selection is precisely the problem of acting optimally within an information set that includes informed and uninformed counterparties.',
            },
          ],
        },
        {
          title: 'Nash Equilibrium',
          blocks: [
            {
              type: 'text',
              body: 'A **Nash Equilibrium** (NE) is a strategy profile where no player can improve their expected payoff by unilaterally changing their strategy. At a NE, each player is playing a best response to the other players\' strategies. Nash proved that every finite game has at least one NE (possibly in mixed strategies).',
            },
            {
              type: 'formula',
              latex: '\\text{NE: } \\forall i, \\forall s_i^\\prime: u_i(s_i^*, s_{-i}^*) \\geq u_i(s_i^\\prime, s_{-i}^*)',
              label: 'Nash Equilibrium Definition',
              explanation: 'For every player $i$ and every alternative strategy $s_i^\\prime$, the player\'s utility under the equilibrium strategy $s_i^*$ (given others play $s_{-i}^*$) is at least as good as any deviation.',
            },
            {
              type: 'example',
              title: 'Finding NE in a 2x2 Game',
              problem: 'Player 1 chooses Row (U or D), Player 2 chooses Column (L or R). Payoffs (P1, P2): (U,L)=(3,1), (U,R)=(0,0), (D,L)=(2,2), (D,R)=(1,3). Find all Nash equilibria.',
              solution: [
                'Check (U,L): P1 deviates to D? Payoff goes from 3 to 2. No. P2 deviates to R? Payoff goes from 1 to 0. No.',
                '(U,L) is a NE: neither player wants to deviate.',
                'Check (D,R): P1 deviates to U? Payoff goes from 1 to 0. No. P2 deviates to L? Payoff goes from 3 to 2. No.',
                '(D,R) is also a NE.',
                'There may also be a mixed-strategy NE. Set P1 indifferent: $p \\cdot 1 + (1-p) \\cdot 0 = p \\cdot 2 + (1-p) \\cdot 3$, giving $p = 3/4$.',
              ],
            },
            {
              type: 'concept',
              title: 'Mixed Strategies',
              body: 'A **mixed strategy** randomizes over pure strategies with specified probabilities. In a mixed NE, each player is indifferent between all strategies in their support. Bluffing in poker is a mixed strategy: you bluff with a specific probability to keep your opponent indifferent between calling and folding.',
            },
          ],
        },
        {
          title: 'Kuhn Poker',
          blocks: [
            {
              type: 'text',
              body: '**Kuhn Poker** is a simplified poker game that is small enough to solve analytically. Deck: 3 cards (J, Q, K). Two players each ante $1, then receive one card each. Player 1 acts first: check or bet ($1). If P1 checks, P2 can check (showdown) or bet. If P2 bets, P1 can call or fold. If P1 bets, P2 can call or fold.',
            },
            {
              type: 'concept',
              title: 'Kuhn Poker Nash Equilibrium',
              body: 'The Nash equilibrium of Kuhn Poker has been computed analytically. Player 1\'s optimal strategy: **always bet with K** (value bet), **always check with Q** (it is too weak to bet, too strong to bluff), **bluff with J at frequency $1/3$** (and check the rest). Player 2\'s optimal strategy: **always call with K**, **call with Q at frequency $1/3$** (to make P1 indifferent about bluffing), **always fold J** to a bet.',
            },
            {
              type: 'formula',
              latex: '\\text{EV}_{P1} = -\\frac{1}{18} \\approx -0.056',
              label: 'Player 1 Expected Value at Equilibrium',
              explanation: 'At Nash equilibrium, Player 1 loses $1/18$ of a unit per hand on average. Player 2 has a positional advantage because they act second and can use P1\'s action as information.',
            },
            {
              type: 'callout',
              variant: 'key-insight',
              body: 'The bluffing frequency of $1/3$ is not arbitrary. Player 1 bets K always (probability 1) and bluffs with J at $1/3$. So when P1 bets, the ratio of value bets to bluffs is $1 : 1/3 = 3 : 1$. This makes the pot odds exactly right for P2 with Q to be indifferent between calling and folding. The bluff frequency is determined by making the opponent indifferent.',
            },
            {
              type: 'example',
              title: 'Computing EV in Kuhn Poker',
              problem: 'Player 1 has J, Player 2 has Q. P1 bluffs (bets $1). P2 must decide: call or fold. Pot is $4 ($1 ante each + $1 bet + $1 call). What are the EVs?',
              solution: [
                'If P2 calls: P2 wins (Q > J). P2 gains $2 (P1\'s ante + P1\'s bet). P2\'s EV = +$2.',
                'If P2 folds: P1 wins the pot ($2 in antes). P1\'s EV = +$1 (wins P2\'s ante).',
                'P2 should always call here if they know P1 has J. But P1 might have K.',
                'If P1 bets, P1 has K with prob $1/(1 + 1/3) = 3/4$ and J with prob $1/4$.',
                'P2 call EV with Q: $3/4 \\times (-2) + 1/4 \\times (+2) = -1.5 + 0.5 = -1.0$.',
                'P2 fold EV: $-1$ (lose ante). P2 is indifferent: call EV = fold EV = $-1$.',
              ],
            },
          ],
        },
        {
          title: 'Connection to Market Making',
          blocks: [
            {
              type: 'text',
              body: 'The strategic interactions in poker map directly to market making. The **market maker** is like Player 2 in Kuhn Poker: they cannot see the other player\'s "card" (private information) and must infer it from actions (order flow). The **informed trader** is like Player 1: they know the true value and can either trade (bet) or not (check).',
            },
            {
              type: 'table',
              headers: ['Poker Concept', 'Market Making Analogue'],
              rows: [
                ['Private cards', 'Private information about asset value'],
                ['Betting', 'Submitting market orders / hitting the bid or lifting the offer'],
                ['Bluffing', 'Uninformed traders trading randomly / noise trading'],
                ['Calling', 'Market maker filling the order (providing liquidity)'],
                ['Pot odds', 'Expected P&L per trade vs. adverse selection risk'],
                ['Fold', 'Market maker widening the spread or pulling quotes'],
              ],
            },
            {
              type: 'concept',
              title: 'Optimal Bluff Frequency and Bid-Ask Spreads',
              body: 'In Kuhn Poker, the bluff frequency is set to make the opponent indifferent. In market making, the fraction of informed vs. uninformed flow determines the optimal spread. If the market maker knew all traders were informed, they would "fold" (pull quotes). If all were uninformed, they would quote very tight. The equilibrium spread balances these, just as the equilibrium bluff frequency balances value bets and bluffs.',
            },
            {
              type: 'callout',
              variant: 'tip',
              body: 'At Optiver, understanding game theory is not about playing poker -- it is about understanding the strategic interaction between market makers and traders. Every quote is a "bet" about the asset\'s value, and every order that comes in is like an opponent\'s move in a game of imperfect information.',
            },
          ],
        },
      ],
    },
    exercises: [
      {
        id: 'd9b-game-01',
        exerciseType: 'multiple-choice',
        difficulty: 'easy',
        topic: 'game-theory',
        tags: ['game-theory', 'normal-form'],
        timeEstimateSeconds: 30,
        question: 'In a normal-form game, players choose their strategies:',
        options: ['Sequentially', 'Simultaneously', 'After seeing a game tree', 'Based on information sets'],
        correctIndex: 1,
        explanation: 'Normal-form games represent simultaneous moves via a payoff matrix. Players choose strategies without observing each other\'s choices.',
        solutionSteps: [
          'Normal-form = payoff matrix = simultaneous moves.',
          'Extensive-form = game tree = sequential moves.',
        ],
      },
      {
        id: 'd9b-game-02',
        exerciseType: 'true-false',
        difficulty: 'easy',
        topic: 'game-theory',
        tags: ['game-theory', 'nash'],
        timeEstimateSeconds: 20,
        statement: 'Every finite game has at least one Nash equilibrium (possibly in mixed strategies).',
        correct: true,
        explanation: 'Nash\'s existence theorem (1950) proves this. Every finite game has at least one NE, though it may require randomization (mixed strategies).',
        solutionSteps: [
          'Nash\'s theorem: existence guaranteed for finite games.',
          'May be in pure strategies (deterministic) or mixed (randomized).',
        ],
      },
      {
        id: 'd9b-game-03',
        exerciseType: 'multiple-choice',
        difficulty: 'easy',
        topic: 'information-sets',
        tags: ['game-theory', 'information-sets'],
        timeEstimateSeconds: 30,
        question: 'An information set containing more than one node indicates:',
        options: [
          'The player knows exactly where they are in the game tree',
          'The player cannot distinguish between the nodes in the set',
          'The game has perfect information',
          'The game is a normal-form game',
        ],
        correctIndex: 1,
        explanation: 'An information set groups nodes that are indistinguishable to the player. If it contains multiple nodes, the player does not know which node they are at -- they have imperfect information.',
        solutionSteps: [
          'Single node in info set = perfect information at that point.',
          'Multiple nodes = imperfect information (cannot distinguish).',
          'Poker: you know your card but not your opponent\'s = imperfect information.',
        ],
      },
      {
        id: 'd9b-game-04',
        exerciseType: 'numeric',
        difficulty: 'easy',
        topic: 'nash-equilibrium',
        tags: ['nash', 'payoff-matrix'],
        timeEstimateSeconds: 60,
        question: 'In the Prisoner\'s Dilemma: payoffs (Cooperate, Cooperate) = (3,3), (C,D) = (0,5), (D,C) = (5,0), (D,D) = (1,1). What is Player 1\'s payoff at the Nash equilibrium?',
        correctAnswer: 1,
        tolerance: 0,
        unit: '',
        explanation: 'The unique NE is (Defect, Defect) with payoffs (1,1). Both players defect because D is a dominant strategy: regardless of the opponent\'s choice, D gives a higher payoff.',
        solutionSteps: [
          'If P2 cooperates: P1 gets 3 (C) vs 5 (D). D is better.',
          'If P2 defects: P1 gets 0 (C) vs 1 (D). D is better.',
          'D is dominant for P1. By symmetry, D is dominant for P2.',
          'NE: (D,D), payoff = (1,1). P1 payoff = 1.',
        ],
      },
      {
        id: 'd9b-game-05',
        exerciseType: 'true-false',
        difficulty: 'easy',
        topic: 'kuhn-poker',
        tags: ['kuhn-poker'],
        timeEstimateSeconds: 20,
        statement: 'In Kuhn Poker, Player 1 should always bet when holding a King.',
        correct: true,
        explanation: 'At Nash equilibrium, Player 1 always bets with K (the highest card). This is a pure value bet -- K wins the showdown against both Q and J, so betting maximizes the expected pot size.',
        solutionSteps: [
          'K is the strongest card in the 3-card deck.',
          'Betting with K wins more (gets called by weaker hands or wins a bigger pot).',
          'In equilibrium, P1 bets K with probability 1.',
        ],
      },
      {
        id: 'd9b-game-06',
        exerciseType: 'numeric',
        difficulty: 'medium',
        topic: 'kuhn-poker',
        tags: ['kuhn-poker', 'bluffing'],
        timeEstimateSeconds: 90,
        question: 'In Kuhn Poker, Player 1 bets with K (always) and bluffs with J at frequency $\\alpha$. Player 2 holds Q. When P1 bets, the pot is $4 (2 antes + 1 bet + 1 call). What value of $\\alpha$ makes P2 indifferent between calling and folding?',
        correctAnswer: 0.333,
        tolerance: 0.02,
        unit: '',
        explanation: 'When P1 bets, P2 with Q wins against J (bluff) and loses against K. P(K|bet) = $1/(1+\\alpha)$, P(J|bet) = $\\alpha/(1+\\alpha)$. Call EV: $\\frac{\\alpha}{1+\\alpha} \\times 2 + \\frac{1}{1+\\alpha} \\times (-2)$. Fold EV: $-1$. Indifference: $\\frac{2\\alpha - 2}{1+\\alpha} = -1$. $2\\alpha - 2 = -(1+\\alpha) = -1 - \\alpha$. $3\\alpha = 1$. $\\alpha = 1/3$.',
        solutionSteps: [
          'P(P1 has K | P1 bets) = $1/(1+\\alpha)$',
          'P(P1 has J | P1 bets) = $\\alpha/(1+\\alpha)$',
          'P2 call EV: $\\frac{\\alpha}{1+\\alpha}(+2) + \\frac{1}{1+\\alpha}(-2) = \\frac{2\\alpha-2}{1+\\alpha}$',
          'Set equal to fold EV ($-1$): $2\\alpha - 2 = -1 - \\alpha$',
          '$3\\alpha = 1$, so $\\alpha = 1/3$',
        ],
      },
      {
        id: 'd9b-game-07',
        exerciseType: 'numeric',
        difficulty: 'medium',
        topic: 'nash-equilibrium',
        tags: ['nash', 'mixed-strategy'],
        timeEstimateSeconds: 120,
        question: 'In Matching Pennies: P1 chooses H or T, P2 chooses H or T. Payoffs for P1: (H,H)=+1, (H,T)=-1, (T,H)=-1, (T,T)=+1. P2\'s payoffs are the negatives. What is the mixed-strategy NE probability that P1 plays H?',
        correctAnswer: 0.5,
        tolerance: 0.01,
        unit: '',
        explanation: 'This is a zero-sum game. P1 must make P2 indifferent: $p \\times (-1) + (1-p) \\times 1 = p \\times 1 + (1-p) \\times (-1)$. $-p + 1 - p = p - 1 + p$. $1 - 2p = 2p - 1$. $4p = 2$. $p = 0.5$. Both players randomize 50/50.',
        solutionSteps: [
          'Set P2 indifferent between H and T.',
          'P2 plays H: EV = $p(-1) + (1-p)(1) = 1 - 2p$',
          'P2 plays T: EV = $p(1) + (1-p)(-1) = 2p - 1$',
          'Indifference: $1 - 2p = 2p - 1$, so $p = 0.5$',
        ],
      },
      {
        id: 'd9b-game-08',
        exerciseType: 'free-response',
        difficulty: 'medium',
        topic: 'kuhn-poker',
        tags: ['kuhn-poker', 'strategy'],
        timeEstimateSeconds: 120,
        question: 'In Kuhn Poker, why does Player 1 never bet with Q at equilibrium? What would happen if P1 always bet with Q?',
        modelAnswer: 'Q is the middle card -- it beats J but loses to K. If P1 bets Q: (1) P2 with K always calls and wins. (2) P2 with J always folds (correct decision). (3) P2 with Q must decide (but Q vs Q cannot happen in Kuhn since each player has a different card). So betting Q only wins when P2 has J (who would fold anyway, so P1 wins just the ante). But checking Q has value too: if P2 checks back, there is a showdown where Q can still win against J. If P2 bets after P1 checks, P1 with Q can decide based on pot odds. Essentially, betting Q does not extract extra value (J folds anyway, K calls and wins). Checking keeps options open. The EV of checking Q exceeds betting Q at equilibrium.',
        explanation: 'The medium-strength hand gains nothing from betting because weak hands fold and strong hands call.',
        solutionSteps: [
          'Bet Q: K calls and wins, J folds. Only wins the ante vs J.',
          'Check Q: can still win at showdown vs J, can make informed decision if P2 bets.',
          'Checking preserves information and flexibility.',
          'Betting Q is dominated by checking at equilibrium.',
        ],
      },
      {
        id: 'd9b-game-09',
        exerciseType: 'multi-step',
        difficulty: 'medium',
        topic: 'nash-equilibrium',
        tags: ['nash', '2x2-games'],
        timeEstimateSeconds: 180,
        question: 'Find the mixed-strategy NE for: P1 payoffs: (U,L)=2, (U,R)=0, (D,L)=0, (D,R)=1. P2 payoffs: (U,L)=0, (U,R)=2, (D,L)=1, (D,R)=0. (a) P1\'s mixing probability for U. (b) P2\'s mixing probability for L. (c) P1\'s expected payoff at the NE.',
        steps: [
          {
            prompt: 'What probability does P1 play U?',
            correctAnswer: 0.333,
            tolerance: 0.02,
            unit: '',
            stepExplanation: 'P2 must be indifferent: $p \\cdot 0 + (1-p) \\cdot 1 = p \\cdot 2 + (1-p) \\cdot 0$. $1 - p = 2p$. $p = 1/3$.',
          },
          {
            prompt: 'What probability does P2 play L?',
            correctAnswer: 0.333,
            tolerance: 0.02,
            unit: '',
            stepExplanation: 'P1 must be indifferent: $q \\cdot 2 + (1-q) \\cdot 0 = q \\cdot 0 + (1-q) \\cdot 1$. $2q = 1 - q$. $q = 1/3$.',
          },
          {
            prompt: 'P1\'s expected payoff at NE?',
            correctAnswer: 0.667,
            tolerance: 0.02,
            unit: '',
            stepExplanation: '$\\text{EV}_1 = q \\cdot 2 + (1-q) \\cdot 0 = 2/3$ (using P1\'s U payoffs since P1 is indifferent).',
          },
        ],
        explanation: 'The mixed NE is found by making each player indifferent between their strategies.',
        solutionSteps: [
          'P1 indifference (determines P2 mixing): $2q = 1 - q$, $q = 1/3$.',
          'P2 indifference (determines P1 mixing): $1 - p = 2p$, $p = 1/3$.',
          'P1 expected payoff: $2 \\times 1/3 = 2/3$.',
        ],
      },
      {
        id: 'd9b-game-10',
        exerciseType: 'numeric',
        difficulty: 'hard',
        topic: 'kuhn-poker',
        tags: ['kuhn-poker', 'ev-calculation'],
        timeEstimateSeconds: 120,
        question: 'In Kuhn Poker at Nash equilibrium, Player 1 has Jack and checks. Player 2 has King and bets. Player 1 must call or fold. The pot is $3 ($1 ante each + $1 bet) and it costs $1 to call. What is P1\'s EV of calling with J?',
        correctAnswer: -1,
        tolerance: 0.01,
        unit: '$',
        explanation: 'P2 with K always bets (at equilibrium). J always loses to K. Calling costs $1 and P1 loses for certain. EV of calling = $-1$. Folding: EV = $-1$ (lost ante). P1 is indifferent (actually slightly worse calling since they lose $2$ total vs $1$ from folding). At equilibrium P1 always folds J to a bet.',
        solutionSteps: [
          'P1 has J, P2 has K. K > J always.',
          'Call: pay $1, lose showdown. Total loss = $-2$ ($1$ ante + $1$ call).',
          'Fold: lose ante only = $-1$.',
          'EV of calling = $-2$ (total), net EV of call action = $-1$ (the additional dollar lost).',
          'Fold is strictly better. P1 folds J facing a bet at equilibrium.',
        ],
      },
      {
        id: 'd9b-game-11',
        exerciseType: 'true-false',
        difficulty: 'hard',
        topic: 'game-theory',
        tags: ['game-theory', 'nash', 'zero-sum'],
        timeEstimateSeconds: 30,
        statement: 'In a two-player zero-sum game, if both players play their NE strategies, the game value is uniquely determined.',
        correct: true,
        explanation: 'In zero-sum games, the minimax theorem (von Neumann) guarantees a unique game value: $\\max_p \\min_q p^\\top A q = \\min_q \\max_p p^\\top A q = v$. Different NE may use different strategy mixtures, but the value $v$ is always the same.',
        solutionSteps: [
          'Zero-sum: P1\'s gain = P2\'s loss.',
          'Minimax theorem: max-min = min-max = game value $v$.',
          'Different equilibria may exist but all yield the same $v$.',
        ],
      },
      {
        id: 'd9b-game-12',
        exerciseType: 'free-response',
        difficulty: 'hard',
        topic: 'market-making',
        tags: ['game-theory', 'market-making', 'adverse-selection'],
        timeEstimateSeconds: 150,
        question: 'Model a simple market making scenario as a game. There is one asset with true value $V \\in \\{90, 110\\}$ with equal probability. An informed trader knows $V$. The market maker sets a bid $b$ and ask $a$. The trader buys if $V > a$, sells if $V < b$, does nothing otherwise. What is the market maker\'s optimal spread?',
        modelAnswer: 'If $V = 110$: informed trader buys at $a$. Market maker sells at $a$ and the asset is worth $110$. MM loss = $110 - a$. If $V = 90$: informed trader sells at $b$. Market maker buys at $b$ and asset worth $90$. MM loss = $b - 90$. Expected loss per trade: $0.5(110 - a) + 0.5(b - 90)$. For the MM to break even: $0.5(110 - a) + 0.5(b - 90) = 0$. $110 - a + b - 90 = 0$. $b - a = -20$. Since $a > b$ (spread is positive), $a - b = 20$. The minimum spread is $20 (= 110 - 90)$. With mid at $100$: $b = 90, a = 110$. This is the Glosten-Milgrom result: the spread equals the full range of uncertainty when all traders are informed.',
        explanation: 'With 100% informed flow, the spread must equal the full information range.',
        solutionSteps: [
          'V = 110: trader buys at $a$. MM loses $110 - a$.',
          'V = 90: trader sells at $b$. MM loses $b - 90$.',
          'Break even: $110 - a + b - 90 = 0$, so $a - b = 20$.',
          'Minimum spread = $20$ (entire range of uncertainty).',
          'With uninformed traders too, spread narrows proportionally.',
        ],
      },
      {
        id: 'd9b-game-13',
        exerciseType: 'scenario',
        difficulty: 'hard',
        topic: 'kuhn-poker',
        tags: ['kuhn-poker', 'ev-analysis'],
        timeEstimateSeconds: 180,
        question: 'Analyze P1\'s EV with each card in Kuhn Poker at Nash equilibrium.',
        scenarios: [
          {
            description: 'P1 holds K: always bets. P2 calls with K (impossible, same card), Q at 1/3. EV from betting?',
            shocks: [{ variable: 'card', change: 3 }],
            expectedAnswer: 0.67,
            tolerance: 0.1,
            unit: '$ per hand',
          },
          {
            description: 'P1 holds Q: always checks. EV?',
            shocks: [{ variable: 'card', change: 2 }],
            expectedAnswer: 0.0,
            tolerance: 0.1,
            unit: '$ per hand',
          },
          {
            description: 'P1 holds J: bluffs 1/3, checks 2/3. EV?',
            shocks: [{ variable: 'card', change: 1 }],
            expectedAnswer: -0.67,
            tolerance: 0.1,
            unit: '$ per hand',
          },
        ],
        explanation: 'At NE, P1 with K profits most, P1 with Q roughly breaks even, and P1 with J loses the most. The total EV averages to $-1/18$ per hand. Each card is equally likely ($1/3$), and P2 holds one of the remaining 2 cards.',
        solutionSteps: [
          'P1 with K: wins often (value bet succeeds). EV $\\approx +2/3$.',
          'P1 with Q: checks, wins some showdowns, loses some. EV $\\approx 0$.',
          'P1 with J: loses most hands, gains occasionally from successful bluffs. EV $\\approx -2/3$.',
          'Average: $(2/3 + 0 - 2/3)/3 = 0$... but P2\'s position advantage makes it $-1/18$.',
        ],
      },
      {
        id: 'd9b-game-14',
        exerciseType: 'free-response',
        difficulty: 'interview',
        topic: 'game-theory',
        tags: ['game-theory', 'interview', 'market-making'],
        timeEstimateSeconds: 180,
        question: 'An interviewer asks: "How is market making like playing poker? Be specific about the parallels and how game theory applies."',
        modelAnswer: 'Both are games of imperfect information with strategic interaction. Parallels: (1) **Private information**: In poker, you know your cards but not your opponent\'s. In market making, the counterparty may know the true asset value (informed trader) or not (noise trader). Your information set contains both possibilities. (2) **Bluffing / adverse selection**: Poker players bluff (bet with weak hands). In markets, uninformed traders trade randomly (like "bluffs" from the MM\'s perspective). The MM must set the spread to be profitable against the mixture of informed and uninformed flow, just as a poker player sets their calling frequency against the mixture of value bets and bluffs. (3) **Pot odds / expected value**: In poker, you call when EV(call) > EV(fold) based on pot odds. In market making, you fill an order when the expected profit from the spread exceeds the expected loss from adverse selection. (4) **Nash equilibrium**: Both sides optimize simultaneously. The equilibrium spread is like the equilibrium bluff frequency -- both are set to make the opponent indifferent. (5) **Position**: In poker, acting second is advantageous (more information). In market making, the MM acts "second" (responds to order flow), which is informative but also exposes them to adverse selection.',
        explanation: 'The poker-trading parallel is one of the most productive frameworks in quantitative finance.',
        solutionSteps: [
          'Private information: cards = asset value knowledge.',
          'Bluffing: uninformed flow = bluffs; informed flow = value bets.',
          'Pot odds: spread captures = pot; adverse selection = losing hands.',
          'NE: spread ↔ bluff frequency; both make opponent indifferent.',
          'Position: acting second = information advantage.',
        ],
      },
      {
        id: 'd9b-game-15',
        exerciseType: 'numeric',
        difficulty: 'interview',
        topic: 'kuhn-poker',
        tags: ['kuhn-poker', 'interview', 'ev'],
        timeEstimateSeconds: 90,
        question: 'At Kuhn Poker NE, P1 bluffs with J at $1/3$. If P1 deviates and bluffs at $1/2$ instead, while P2 still calls Q at $1/3$, by how much does P1\'s EV change per J-hand (approximate)?',
        correctAnswer: -0.11,
        tolerance: 0.05,
        unit: '$ per J-hand',
        explanation: 'At equilibrium ($\\alpha = 1/3$), P1\'s J-hand EV is calculated by mixing check and bluff EVs. At $\\alpha = 1/2$, P1 bluffs more often. When P1 bluffs J: vs K (P2 calls always, P1 loses $2$) and vs Q (P2 calls at $1/3$, P1 loses $2$ with $1/3$ prob, wins $2$ with $2/3$ prob). Bluff EV vs Q: $(-2)(1/3) + (1)(2/3) = -2/3 + 2/3 = 0$. Bluff EV vs K: $-2$. P2 has K or Q with equal prob ($1/2$ each). Bluff EV = $0.5(-2) + 0.5(0) = -1$. At equilibrium bluff rate $1/3$: J-hand EV includes check EV too. The deviation from NE loses about $0.11$ per J-hand because over-bluffing is exploited.',
        solutionSteps: [
          'NE bluff rate: $1/3$. Deviation: $1/2$.',
          'Over-bluffing loses money because P2\'s calling frequency punishes excess bluffs.',
          'Extra bluffs cost $\\approx 0.11$ per J-hand on average.',
          'At NE, P1 is indifferent about bluffing with J; deviating in either direction cannot help.',
        ],
      },
      {
        id: 'd9b-game-16',
        exerciseType: 'speed-drill',
        difficulty: 'interview',
        topic: 'game-theory',
        tags: ['game-theory', 'speed-drill'],
        timeEstimateSeconds: 120,
        timeLimitSeconds: 120,
        problems: [
          { prompt: 'In Prisoner\'s Dilemma, the dominant strategy is Defect. 1=True, 0=False', correctAnswer: 1, tolerance: 0 },
          { prompt: 'Kuhn Poker optimal P1 bluff frequency with Jack?', correctAnswer: 0.333, tolerance: 0.02 },
          { prompt: 'In a zero-sum game, P1 gains $5. P2 gains?', correctAnswer: -5, tolerance: 0 },
          { prompt: 'Matching Pennies NE: probability of Heads for P1?', correctAnswer: 0.5, tolerance: 0.01 },
          { prompt: 'Kuhn Poker P1 overall EV at NE (approx)?', correctAnswer: -0.056, tolerance: 0.01 },
          { prompt: 'If 100% of order flow is informed, MM spread = full range? 1=Yes', correctAnswer: 1, tolerance: 0 },
        ],
        explanation: 'Quick recall of key game theory concepts for interviews.',
        solutionSteps: [
          'Prisoner\'s Dilemma: Defect dominates. True.',
          'Kuhn: P1 bluffs J at $1/3$.',
          'Zero-sum: sum = 0, so P2 = $-5$.',
          'Matching Pennies: both play $0.5$.',
          'Kuhn P1 EV: $-1/18 \\approx -0.056$.',
          'Fully informed flow: spread = $V_H - V_L$. Yes.',
        ],
      },
    ],
    flashcards: [
      { id: 'd9b-f01', front: 'Normal-form vs extensive-form game', back: 'Normal: payoff matrix, simultaneous. Extensive: game tree, sequential, can model private info.', tags: ['game-theory'] },
      { id: 'd9b-f02', front: 'What is an information set?', back: 'A set of game tree nodes that a player cannot distinguish between. Captures imperfect information.', tags: ['game-theory'] },
      { id: 'd9b-f03', front: 'Nash Equilibrium definition', back: 'No player can improve their payoff by unilaterally deviating: $u_i(s_i^*, s_{-i}^*) \\geq u_i(s_i\', s_{-i}^*)$ for all $s_i\'$.', tags: ['nash'] },
      { id: 'd9b-f04', front: 'Kuhn Poker P1 equilibrium strategy', back: 'K: always bet. Q: always check. J: bluff (bet) with probability $1/3$, check with probability $2/3$.', tags: ['kuhn-poker'] },
      { id: 'd9b-f05', front: 'Kuhn Poker P2 equilibrium strategy', back: 'K: always call. Q: call with probability $1/3$. J: always fold to a bet.', tags: ['kuhn-poker'] },
      { id: 'd9b-f06', front: 'Why bluff at frequency 1/3 in Kuhn?', back: 'Makes P2 with Q indifferent between calling and folding. The ratio value:bluff = 3:1 matches the pot odds.', tags: ['kuhn-poker', 'bluffing'] },
      { id: 'd9b-f07', front: 'Mixed strategy', back: 'A probability distribution over pure strategies. At a mixed NE, the player is indifferent between strategies in the support.', tags: ['nash', 'mixed-strategy'] },
      { id: 'd9b-f08', front: 'Poker-to-trading mapping', back: 'Cards = private info, betting = trading, bluffing = noise trading, calling = filling orders, pot odds = spread EV.', tags: ['market-making', 'game-theory'] },
      { id: 'd9b-f09', front: 'Kuhn Poker P1 expected value at NE', back: '$-1/18 \\approx -0.056$. P2 has a positional advantage (acts second with more information).', tags: ['kuhn-poker'] },
      { id: 'd9b-f10', front: 'Zero-sum game property', back: 'One player\'s gain = other\'s loss. Total payoff always sums to zero. Minimax theorem guarantees unique game value.', tags: ['game-theory'] },
      { id: 'd9b-f11', front: 'Why does Q never bet in Kuhn Poker?', back: 'Q is medium strength. Betting only gets called by K (loses) and folds J (would lose anyway). Checking preserves flexibility.', tags: ['kuhn-poker'] },
      { id: 'd9b-f12', front: 'Adverse selection as a game', back: 'MM faces a game against informed (know true value) and uninformed traders. Spread = equilibrium strategy balancing profit vs adverse selection loss.', tags: ['game-theory', 'market-making'] },
    ],
    cheatSheet: [
      { topic: 'Nash Equilibrium', formula: '∀i, ∀s\'ᵢ: uᵢ(sᵢ*, s₋ᵢ*) ≥ uᵢ(s\'ᵢ, s₋ᵢ*)', description: 'No player gains from unilateral deviation' },
      { topic: 'Kuhn P1 Bluff Rate', formula: 'α = 1/3 with Jack', description: 'Makes P2 with Q indifferent' },
      { topic: 'Kuhn P2 Call Rate', formula: 'β = 1/3 with Queen', description: 'Makes P1 indifferent about bluffing' },
      { topic: 'Kuhn P1 EV', formula: 'EV = -1/18', description: 'P2 has positional advantage' },
      { topic: 'Mixed NE Method', formula: 'Set opponent indifferent', description: 'P1\'s mixing prob found from P2\'s indifference' },
      { topic: 'MM Spread (Full Info)', formula: 'S = V_H - V_L', description: 'Spread equals info range with 100% informed flow' },
    ],
    summary: [
      'Normal-form games use payoff matrices for simultaneous play; extensive-form games use game trees for sequential play with information sets',
      'Nash Equilibrium: no player can improve by unilateral deviation; every finite game has at least one NE',
      'Kuhn Poker NE: P1 bets K always, bluffs J at $1/3$, checks Q; P2 calls K always, calls Q at $1/3$',
      'The bluffing frequency is set to make the opponent indifferent, paralleling how spreads are set in market making',
      'Market making is a game of imperfect information: private signals map to cards, order flow maps to bets, spreads map to pot odds',
    ],
    interactiveTools: [],
  },
};

export default day09;
