import { DayContent } from './types';

const day07: DayContent = {
  dayNumber: 7,
  title: 'Volatility Spreads & Multi-Leg Strategies',
  subtitle: 'Natenberg Chapters 7, 8, 10',
  week: 1,
  chapters: ['Chapter 7', 'Chapter 8', 'Chapter 10'],
  estimatedMinutes: 130,
  prerequisites: [1, 2, 3, 4, 5, 6],
  objectives: [
    'Construct and analyze vertical spreads, straddles, strangles, and butterflies',
    'Calculate net Greeks for multi-leg option positions',
    'Understand the risk/reward profiles of common spread strategies',
    'Identify strategies from their Greek profiles',
    'Price calendar spreads and understand their vega characteristics',
    'Perform full-chain analysis: forward pricing through BS to spread construction',
  ],
  theory: {
    sections: [
      {
        title: 'Vertical Spreads',
        blocks: [
          {
            type: 'text',
            body: 'A **vertical spread** (or "money spread") involves buying and selling options of the same type (both calls or both puts) with the same expiration but different strikes. Verticals are directional bets with capped risk and capped reward.',
          },
          {
            type: 'concept',
            title: 'Bull Call Spread',
            body: 'Buy a lower-strike call, sell a higher-strike call. Max profit $= (K_2 - K_1) - \\text{net premium}$. Max loss $= \\text{net premium}$. Delta is positive (bullish). This is equivalent to a bull put spread by put-call parity.',
          },
          {
            type: 'concept',
            title: 'Bear Put Spread',
            body: 'Buy a higher-strike put, sell a lower-strike put. Max profit $= (K_2 - K_1) - \\text{net premium}$. Max loss $= \\text{net premium}$. Delta is negative (bearish).',
          },
          {
            type: 'example',
            title: 'Bull Call Spread Pricing',
            problem: 'Buy the 100 call at $5.00, sell the 110 call at $2.00. What is the max profit, max loss, and breakeven?',
            solution: [
              'Net premium paid $= 5.00 - 2.00 = \\$3.00$.',
              'Max profit $= (110 - 100) - 3.00 = \\$7.00$ (if $S_T \\geq 110$).',
              'Max loss $= \\$3.00$ (if $S_T \\leq 100$).',
              'Breakeven $= 100 + 3.00 = \\$103.00$.',
            ],
          },
          {
            type: 'callout',
            variant: 'tip',
            body: 'Vertical spreads reduce vega exposure compared to naked options. The long and short legs partially offset each other\'s vega. This makes verticals useful when you have a directional view but do not want large vol exposure.',
          },
        ],
      },
      {
        title: 'Straddles & Strangles',
        blocks: [
          {
            type: 'text',
            body: '**Straddles** and **strangles** are volatility bets. A straddle (long call + long put, same strike) profits from large moves in either direction. A strangle (long OTM call + long OTM put) is similar but cheaper, requiring a larger move to profit.',
          },
          {
            type: 'formula',
            latex: '\\text{Straddle price} = C(K) + P(K) \\approx 0.8 \\cdot S \\cdot \\sigma \\cdot \\sqrt{T}',
            label: 'ATM Straddle Approximation',
            explanation: 'For ATM straddles with $r \\approx 0$: the straddle price is approximately proportional to $S$, $\\sigma$, and $\\sqrt{T}$.',
          },
          {
            type: 'concept',
            title: 'Straddle Greeks',
            body: 'An ATM straddle has: delta $\\approx 0$ (the call and put deltas roughly cancel), gamma $= 2\\Gamma_{\\text{single}}$ (double the gamma of one option), theta $= 2\\Theta_{\\text{single}}$ (double the theta), vega $= 2\\mathcal{V}_{\\text{single}}$ (double the vega). A straddle is a pure volatility bet.',
          },
          {
            type: 'callout',
            variant: 'key-insight',
            body: 'The break-even move for a straddle is approximately the straddle price itself. If a 1-month ATM straddle costs $5 on a $100 stock, the stock needs to move about $\\pm 5\\%$ (about $\\$5$) for the buyer to break even. The implied daily move is straddle price $/ \\sqrt{T_{\\text{days}}}$.',
          },
        ],
      },
      {
        title: 'Butterflies & Condors',
        blocks: [
          {
            type: 'text',
            body: 'A **butterfly** is a three-strike spread: buy 1 low-strike, sell 2 middle-strike, buy 1 high-strike (all calls or all puts, equally spaced). It profits from the stock staying near the middle strike. A **condor** is a four-strike version, providing a wider profit zone.',
          },
          {
            type: 'formula',
            latex: '\\text{Long butterfly} = C(K_1) - 2C(K_2) + C(K_3)',
            label: 'Butterfly Payoff',
            explanation: 'Where $K_1 < K_2 < K_3$ and $K_2 = (K_1 + K_3)/2$. Max payoff $= K_2 - K_1$ at $S_T = K_2$. Max loss $= \\text{premium paid}$.',
          },
          {
            type: 'concept',
            title: 'Butterfly Greeks',
            body: 'A long butterfly has: near-zero delta (if centered ATM), negative gamma (short vol), positive theta (collect time decay), negative vega (benefits from vol decrease). A butterfly is effectively a short-vol bet with limited risk.',
          },
          {
            type: 'example',
            title: 'Iron Butterfly Pricing',
            problem: 'ATM strike $K = 100$. Buy the 95 put at $1.50$, sell the 100 put at $3.50$, sell the 100 call at $4.00$, buy the 105 call at $2.00$. What is the net credit and max profit?',
            solution: [
              'Net credit $= (3.50 + 4.00) - (1.50 + 2.00) = 7.50 - 3.50 = \\$4.00$.',
              'Max profit $= \\$4.00$ (if $S_T = 100$ at expiry, all options expire worthless except the short ATM, which are at-the-money).',
              'Max loss $= (K_2 - K_1) - \\text{credit} = 5 - 4 = \\$1.00$ (if $S_T \\leq 95$ or $S_T \\geq 105$).',
              'Breakevens: $100 \\pm 4 = \\$96$ and $\\$104$.',
            ],
          },
        ],
      },
      {
        title: 'Calendar Spreads (Time Spreads)',
        blocks: [
          {
            type: 'text',
            body: 'A **calendar spread** involves buying and selling the same strike but different expirations. Typically: sell the near-dated option and buy the far-dated option. Calendar spreads are primarily vega trades: they profit when implied vol increases.',
          },
          {
            type: 'concept',
            title: 'Calendar Spread Greeks',
            body: 'A long calendar spread (short near-term, long far-term) has: near-zero delta (if ATM), negative gamma (short the high-gamma near-term option), positive theta (the near-term decays faster), positive vega (the far-term has more vega than the near-term). The key driver is vega: the far-dated leg has more vega, so a vol increase benefits the position.',
          },
          {
            type: 'callout',
            variant: 'warning',
            body: 'Calendar spreads have a hidden risk: if the vol term structure shifts (e.g., near-term vol spikes while far-term stays flat), the spread can lose money even if overall vol increases. This is term structure risk, not captured by a single vega number.',
          },
        ],
      },
      {
        title: 'Ratio Spreads & Risk Reversals',
        blocks: [
          {
            type: 'text',
            body: 'A **ratio spread** involves buying and selling different quantities of options at different strikes (e.g., buy 1 ATM call, sell 2 OTM calls). A **risk reversal** (or "combo") is a long OTM call + short OTM put (or vice versa), creating a synthetic directional position with skew exposure.',
          },
          {
            type: 'concept',
            title: 'Ratio Spread: 1x2 Call Spread',
            body: 'Buy 1 lower-strike call, sell 2 higher-strike calls. Net position is long 1 vertical + short 1 naked call. Below $K_1$: zero. Between $K_1$ and $K_2$: gains. Above $K_2$: gains decrease and eventually become losses (unlimited on the upside). The position can often be put on for zero or small net premium.',
          },
          {
            type: 'concept',
            title: 'Risk Reversal',
            body: 'Long OTM call + Short OTM put (bullish risk reversal). Delta-wise this is similar to a long stock position. The key feature is that the cost depends heavily on the volatility skew. In equity markets, puts usually have higher implied vol than calls (downside skew), so a bullish risk reversal often generates a net credit.',
          },
        ],
      },
    ],
  },
  exercises: [
    // --- EASY (5) ---
    {
      id: 'd7-spread-01',
      exerciseType: 'numeric',
      difficulty: 'easy',
      topic: 'vertical-spreads',
      tags: ['spreads', 'vertical', 'call-spread'],
      timeEstimateSeconds: 60,
      question: 'You buy the 50 call at $3.00 and sell the 55 call at $1.50. What is the maximum profit of this bull call spread?',
      correctAnswer: 3.50,
      tolerance: 0.01,
      unit: '$',
      explanation: 'Max profit $= (55 - 50) - (3.00 - 1.50) = 5.00 - 1.50 = \\$3.50$ (at $S_T \\geq 55$).',
      solutionSteps: [
        'Net premium paid $= 3.00 - 1.50 = \\$1.50$.',
        'Width of spread $= 55 - 50 = \\$5.00$.',
        'Max profit $= \\$5.00 - \\$1.50 = \\$3.50$.',
      ],
    },
    {
      id: 'd7-spread-02',
      exerciseType: 'numeric',
      difficulty: 'easy',
      topic: 'straddle',
      tags: ['spreads', 'straddle'],
      timeEstimateSeconds: 45,
      question: 'An ATM straddle (100-strike) costs $8.00. What are the two breakeven stock prices at expiry?',
      correctAnswer: 108,
      tolerance: 0.01,
      unit: '$ (upper breakeven)',
      hint: 'Breakevens are $K \\pm \\text{straddle price}$.',
      explanation: 'Upper breakeven $= 100 + 8 = 108$. Lower breakeven $= 100 - 8 = 92$.',
      solutionSteps: [
        'A straddle profits if the stock moves more than the straddle price from the strike.',
        'Upper breakeven $= K + \\text{straddle price} = 100 + 8 = \\$108$.',
        'Lower breakeven $= K - \\text{straddle price} = 100 - 8 = \\$92$.',
      ],
    },
    {
      id: 'd7-spread-03',
      exerciseType: 'multiple-choice',
      difficulty: 'easy',
      topic: 'butterfly',
      tags: ['spreads', 'butterfly'],
      timeEstimateSeconds: 30,
      question: 'A long butterfly spread profits most when:',
      options: [
        'The stock makes a large move in either direction',
        'The stock stays near the middle strike at expiry',
        'Implied volatility increases',
        'Interest rates increase',
      ],
      correctIndex: 1,
      explanation: 'A long butterfly has maximum profit when $S_T$ equals the middle strike. It is a short-vol position (profits from the stock staying put).',
      solutionSteps: [
        'Long butterfly: buy wings, sell body.',
        'Max payoff at $S_T = K_{\\text{middle}}$.',
        'Short gamma, positive theta: profits from no movement.',
        'Negative vega: benefits from vol decrease.',
      ],
    },
    {
      id: 'd7-spread-04',
      exerciseType: 'true-false',
      difficulty: 'easy',
      topic: 'straddle',
      tags: ['spreads', 'straddle', 'greeks'],
      timeEstimateSeconds: 20,
      statement: 'An ATM straddle has approximately zero delta.',
      correct: true,
      explanation: 'ATM call delta $\\approx +0.50$, ATM put delta $\\approx -0.50$. Combined: $0.50 + (-0.50) = 0$. The straddle is delta-neutral, making it a pure vol bet.',
      solutionSteps: [
        'Straddle $= $ call $+$ put at the same strike.',
        '$\\Delta_{\\text{straddle}} = \\Delta_C + \\Delta_P = N(d_1) + (N(d_1) - 1)$',
        'For ATM: $\\approx 0.50 + (-0.50) = 0$.',
      ],
    },
    {
      id: 'd7-spread-05',
      exerciseType: 'numeric',
      difficulty: 'easy',
      topic: 'vertical-spreads',
      tags: ['spreads', 'vertical', 'put-spread'],
      timeEstimateSeconds: 45,
      question: 'You buy the 60 put at $4.00 and sell the 55 put at $1.50. What is the maximum loss?',
      correctAnswer: 2.50,
      tolerance: 0.01,
      unit: '$',
      explanation: 'Net premium paid $= 4.00 - 1.50 = \\$2.50$. Max loss is the premium paid (if $S_T \\geq 60$).',
      solutionSteps: [
        'This is a bear put spread (bearish).',
        'Net premium $= 4.00 - 1.50 = \\$2.50$.',
        'Max loss $= \\$2.50$ (if both puts expire worthless, $S_T \\geq 60$).',
        'Max profit $= (60 - 55) - 2.50 = \\$2.50$ (if $S_T \\leq 55$).',
      ],
    },
    // --- MEDIUM (6) ---
    {
      id: 'd7-spread-06',
      exerciseType: 'multi-step',
      difficulty: 'medium',
      topic: 'spread-greeks',
      tags: ['spreads', 'greeks', 'straddle'],
      timeEstimateSeconds: 120,
      question: 'An ATM straddle at strike 100: call has $\\Delta = 0.55$, $\\Gamma = 0.03$, $\\Theta = -0.05$/day, $\\mathcal{V} = 0.20$. Put has $\\Delta = -0.45$, same $\\Gamma$, $\\Theta = -0.04$/day, same $\\mathcal{V}$. Compute the straddle Greeks.',
      steps: [
        {
          prompt: 'What is the straddle delta?',
          correctAnswer: 0.10,
          tolerance: 0.01,
          stepExplanation: '$\\Delta_{\\text{straddle}} = 0.55 + (-0.45) = 0.10$',
        },
        {
          prompt: 'What is the straddle gamma?',
          correctAnswer: 0.06,
          tolerance: 0.001,
          stepExplanation: '$\\Gamma_{\\text{straddle}} = 0.03 + 0.03 = 0.06$',
        },
        {
          prompt: 'What is the straddle daily theta?',
          correctAnswer: -0.09,
          tolerance: 0.005,
          unit: '$/day',
          stepExplanation: '$\\Theta_{\\text{straddle}} = -0.05 + (-0.04) = -0.09$/day',
        },
        {
          prompt: 'What is the straddle vega?',
          correctAnswer: 0.40,
          tolerance: 0.01,
          stepExplanation: '$\\mathcal{V}_{\\text{straddle}} = 0.20 + 0.20 = 0.40$',
        },
      ],
      explanation: 'Spread Greeks are simply the sum of individual leg Greeks (with appropriate signs for long/short).',
      solutionSteps: [
        '$\\Delta = 0.55 + (-0.45) = 0.10$ (slightly long because call delta slightly exceeds 0.50)',
        '$\\Gamma = 0.03 + 0.03 = 0.06$ (double the single-option gamma)',
        '$\\Theta = -0.05 + (-0.04) = -0.09$/day (double the theta)',
        '$\\mathcal{V} = 0.20 + 0.20 = 0.40$ (double the vega)',
      ],
    },
    {
      id: 'd7-spread-07',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'butterfly',
      tags: ['spreads', 'butterfly', 'pricing'],
      timeEstimateSeconds: 90,
      question: 'Price a call butterfly: buy 95 call at $8.50, sell 2x 100 calls at $5.00 each, buy 105 call at $2.50. What is the net cost and maximum payoff?',
      correctAnswer: 1.00,
      tolerance: 0.01,
      unit: '$ (net cost)',
      explanation: 'Net cost $= 8.50 - 2(5.00) + 2.50 = 8.50 - 10.00 + 2.50 = \\$1.00$. Max payoff $= 5.00 - 1.00 = \\$4.00$ at $S_T = 100$.',
      solutionSteps: [
        'Net premium $= 8.50 - 2(5.00) + 2.50 = 1.00$.',
        'Max payoff at $S_T = 100$: long 95C pays $5, short 100Cs and long 105C all at $0.',
        'Net payoff $= 5 - 0 + 0 = 5$. Profit $= 5 - 1 = \\$4$.',
        'Max loss $= \\$1.00$ (premium paid, when $S_T \\leq 95$ or $S_T \\geq 105$).',
      ],
    },
    {
      id: 'd7-spread-08',
      exerciseType: 'free-response',
      difficulty: 'medium',
      topic: 'calendar-spread',
      tags: ['spreads', 'calendar', 'vega'],
      timeEstimateSeconds: 120,
      question: 'Explain why a long calendar spread (sell near-term, buy far-term, same strike) is a long vega position. Under what market conditions does it perform best?',
      modelAnswer: 'A long calendar spread is long vega because the far-dated option has more vega than the near-dated option (vega scales with $\\sqrt{T}$). When vol rises, the far-dated leg gains more than the near-dated leg loses, generating a net profit. It performs best when: (1) implied vol increases (the vega effect), and (2) the stock stays near the strike (both options are ATM, where vega is highest). It also benefits from the near-term option decaying faster than the far-term (theta benefit). The worst scenario is a large stock move away from the strike (both options go OTM/ITM, reducing time value) combined with a vol decrease.',
      explanation: 'Calendar spreads are long vega because far-dated options have more vega than near-dated options.',
      solutionSteps: [
        'Far-dated option vega $> $ near-dated option vega (since $\\mathcal{V} \\propto \\sqrt{T}$).',
        'Net vega $= \\mathcal{V}_{\\text{far}} - \\mathcal{V}_{\\text{near}} > 0$ (long vega).',
        'Profits from: vol increase, stock staying near strike, near-term theta decay.',
        'Worst case: large move away from strike + vol decrease.',
      ],
    },
    {
      id: 'd7-spread-09',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'spread-greeks',
      tags: ['spreads', 'vertical', 'greeks'],
      timeEstimateSeconds: 90,
      question: 'A bull call spread: long 100C ($\\Delta = 0.60$, $\\Gamma = 0.03$, $\\mathcal{V} = 0.18$), short 110C ($\\Delta = 0.35$, $\\Gamma = 0.025$, $\\mathcal{V} = 0.15$). What is the spread vega?',
      correctAnswer: 0.03,
      tolerance: 0.005,
      explanation: 'Spread vega $= 0.18 - 0.15 = 0.03$. The spread has a small long vega exposure.',
      solutionSteps: [
        'Long 100C vega: $+0.18$.',
        'Short 110C vega: $-0.15$.',
        'Net vega $= 0.18 - 0.15 = 0.03$.',
        'The spread has residual vega exposure but much less than a single leg.',
      ],
    },
    {
      id: 'd7-spread-10',
      exerciseType: 'multiple-choice',
      difficulty: 'medium',
      topic: 'risk-reversal',
      tags: ['spreads', 'risk-reversal', 'skew'],
      timeEstimateSeconds: 45,
      question: 'In equity markets with typical downside skew, a bullish risk reversal (long OTM call, short OTM put) usually:',
      options: [
        'Costs money (net debit) because the call is more expensive',
        'Generates a credit because the put (higher implied vol) is more expensive than the call',
        'Costs nothing because the payoffs are symmetric',
        'Depends only on the risk-free rate, not on skew',
      ],
      correctIndex: 1,
      explanation: 'In equity markets, OTM puts trade at higher implied vol than equidistant OTM calls (downside skew). So the put premium exceeds the call premium, and selling the put while buying the call generates a net credit.',
      solutionSteps: [
        'Equity skew: OTM put IV > OTM call IV (downside protection is expensive).',
        'Selling the OTM put generates more premium than buying the OTM call costs.',
        'Net result: credit for a bullish risk reversal.',
        'The skew compensates the put seller for taking crash risk.',
      ],
    },
    {
      id: 'd7-spread-11',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'straddle',
      tags: ['spreads', 'straddle', 'pricing'],
      timeEstimateSeconds: 60,
      question: 'Using the ATM straddle approximation $\\approx 0.8 S \\sigma \\sqrt{T}$: estimate the price of a 30-day ATM straddle on a $75 stock with 35% implied vol. ($\\sqrt{30/365} \\approx 0.287$.)',
      correctAnswer: 6.03,
      tolerance: 0.2,
      unit: '$',
      explanation: '$\\text{Straddle} \\approx 0.8 \\times 75 \\times 0.35 \\times 0.287 = 0.8 \\times 75 \\times 0.1005 = 6.03$.',
      solutionSteps: [
        '$\\text{Straddle} \\approx 0.8 S \\sigma \\sqrt{T}$',
        '$= 0.8 \\times 75 \\times 0.35 \\times \\sqrt{30/365}$',
        '$= 0.8 \\times 75 \\times 0.35 \\times 0.287 = 6.03$',
        'The implied daily move is about $6.03/\\sqrt{30} \\approx \\$1.10$.',
      ],
    },
    // --- HARD (5) ---
    {
      id: 'd7-spread-12',
      exerciseType: 'multi-step',
      difficulty: 'hard',
      topic: 'spread-pnl',
      tags: ['spreads', 'butterfly', 'pnl'],
      timeEstimateSeconds: 180,
      question: 'A call butterfly: long 1x 95C, short 2x 100C, long 1x 105C. Cost: $1.50. Compute the P&L at expiry for: (a) $S_T = 100$, (b) $S_T = 97$, (c) $S_T = 110$.',
      steps: [
        {
          prompt: 'P&L at $S_T = 100$?',
          correctAnswer: 3.50,
          tolerance: 0.01,
          unit: '$',
          stepExplanation: 'Payoff: 95C pays $5, 100Cs pay $0, 105C pays $0. Net payoff $= 5$. P&L $= 5 - 1.50 = \\$3.50$.',
        },
        {
          prompt: 'P&L at $S_T = 97$?',
          correctAnswer: 0.50,
          tolerance: 0.01,
          unit: '$',
          stepExplanation: 'Payoff: 95C pays $2, 100Cs pay $0, 105C pays $0. Net payoff $= 2$. P&L $= 2 - 1.50 = \\$0.50$.',
        },
        {
          prompt: 'P&L at $S_T = 110$?',
          correctAnswer: -1.50,
          tolerance: 0.01,
          unit: '$',
          stepExplanation: 'Payoff: 95C pays $15, 100Cs pay $-20$ (short 2x $10 each), 105C pays $5. Net $= 15 - 20 + 5 = 0$. P&L $= 0 - 1.50 = -\\$1.50$.',
        },
      ],
      explanation: 'The butterfly has max profit at the body strike, small profit in the wings, and max loss outside the wings.',
      solutionSteps: [
        '$S_T = 100$: payoff $= (100-95) - 2(0) + 0 = 5$. P&L $= 5 - 1.50 = 3.50$.',
        '$S_T = 97$: payoff $= (97-95) - 2(0) + 0 = 2$. P&L $= 2 - 1.50 = 0.50$.',
        '$S_T = 110$: payoff $= (110-95) - 2(110-100) + (110-105) = 15-20+5 = 0$. P&L $= -1.50$.',
      ],
    },
    {
      id: 'd7-spread-13',
      exerciseType: 'scenario',
      difficulty: 'hard',
      topic: 'spread-greeks',
      tags: ['spreads', 'straddle', 'greeks', 'pnl'],
      timeEstimateSeconds: 180,
      question: 'You are long 10 ATM straddles. Per straddle: $\\Gamma = 0.06$, daily $\\Theta = -\\$0.10$, $\\mathcal{V} = 0.40$. Compute the portfolio P&L under each scenario (1-day changes).',
      scenarios: [
        {
          description: 'Stock moves +$3, vol unchanged',
          shocks: [{ variable: 'stock', change: 3 }],
          expectedAnswer: 1.70,
          tolerance: 0.2,
          unit: '$',
        },
        {
          description: 'Stock flat, vol drops 2 points',
          shocks: [{ variable: 'implied_vol', change: -2 }],
          expectedAnswer: -9.0,
          tolerance: 0.5,
          unit: '$',
        },
        {
          description: 'Stock moves +$5, vol increases 1 point',
          shocks: [{ variable: 'stock', change: 5 }],
          expectedAnswer: 11.50,
          tolerance: 1.0,
          unit: '$',
        },
      ],
      explanation: 'P&L = gamma P&L + vega P&L + theta. Each Greek contribution is additive.',
      solutionSteps: [
        'Position: $10 \\times$ straddle. $\\Gamma_{\\text{pos}} = 10 \\times 0.06 = 0.60$, $\\Theta_{\\text{pos}} = 10 \\times (-0.10) = -1.00$/day, $\\mathcal{V}_{\\text{pos}} = 10 \\times 0.40 = 4.0$.',
        '+$3, vol flat: $\\frac{1}{2}(0.60)(9) + 0 + (-1.00) = 2.70 - 1.00 = 1.70$.',
        'Flat, vol $-2$: $0 + 4.0 \\times (-2) + (-1.00) = -8.00 - 1.00 = -9.00$.',
        '+$5, vol $+1$: $\\frac{1}{2}(0.60)(25) + 4.0(1) + (-1.00) = 7.50 + 4.00 - 1.00 = 10.50$.',
      ],
    },
    {
      id: 'd7-spread-14',
      exerciseType: 'free-response',
      difficulty: 'hard',
      topic: 'strategy-identification',
      tags: ['spreads', 'greeks', 'identification'],
      timeEstimateSeconds: 150,
      question: 'A portfolio has: delta $\\approx 0$, gamma $< 0$, theta $> 0$, vega $< 0$. What strategy is this most likely? Describe its risk profile and when it performs well.',
      modelAnswer: 'This is a short volatility position, most likely a short straddle, short strangle, or long butterfly (iron condor). Delta neutral means no directional bet. Negative gamma means large moves hurt. Positive theta means it profits from time decay. Negative vega means it profits from vol decrease. Risk profile: limited profit (theta collected), unlimited loss potential (for short straddle/strangle; limited for butterfly). Performs best when the stock stays in a narrow range and implied vol decreases. Worst case: large stock move or vol spike. This is the classic "collect pennies in front of a steamroller" profile that market makers often run (but with sophisticated risk management).',
      explanation: 'Delta-neutral, short gamma, long theta, short vega = short volatility position (short straddle/strangle or long butterfly).',
      solutionSteps: [
        '$\\Delta \\approx 0$: no directional bias.',
        '$\\Gamma < 0$: loses on large moves (short convexity).',
        '$\\Theta > 0$: profits from time passing (collecting decay).',
        '$\\mathcal{V} < 0$: profits from vol decrease.',
        'Strategy: short straddle, short strangle, or long butterfly/condor.',
        'Best scenario: quiet market, declining vol. Worst: gap move or vol spike.',
      ],
    },
    {
      id: 'd7-spread-15',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'ratio-spread',
      tags: ['spreads', 'ratio', 'pricing'],
      timeEstimateSeconds: 120,
      question: 'A 1x2 call ratio spread: buy 1x 100C at $5.00, sell 2x 110C at $2.00 each. What is the net premium, the P&L at $S_T = 110$, and at $S_T = 125$?',
      correctAnswer: 1.0,
      tolerance: 0.01,
      unit: '$ (net credit)',
      explanation: 'Net credit $= 2(2.00) - 5.00 = -1.00$. Actually: $-5.00 + 2(2.00) = -1.00$. Net debit of $1.00.',
      solutionSteps: [
        'Net premium: buy 100C ($-5.00$), sell 2x 110C ($+4.00$). Net $= -1.00$ (debit of $\\$1.00$).',
        '$S_T = 110$: 100C pays $10, 110Cs pay $0. Payoff $= 10$. P&L $= 10 - 1 = +\\$9.00$.',
        '$S_T = 125$: 100C pays $25, 110Cs pay $-2 \\times 15 = -30$. Net payoff $= 25 - 30 = -5$. P&L $= -5 - 1 = -\\$6.00$.',
        'Breakevens: lower $= 101$ ($100 + 1$ debit). Upper $= 119$ ($110 + 9$ max payoff above $K_2$: solve $S - 100 - 2(S - 110) + 1 = 0 \\Rightarrow -S + 121 = 0 \\Rightarrow S = 121$).',
      ],
    },
    {
      id: 'd7-spread-16',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'straddle',
      tags: ['spreads', 'straddle', 'implied-move'],
      timeEstimateSeconds: 90,
      question: 'A 7-day ATM straddle on a $200 stock costs $12. What is the implied daily move? What is the annualized implied volatility?',
      correctAnswer: 4.54,
      tolerance: 0.2,
      unit: '$ (implied daily move)',
      explanation: 'Implied move over $T$ days $= \\text{straddle price}$. Daily implied move $= 12/\\sqrt{7} = 12/2.646 = \\$4.54$. Annualized implied vol: daily vol $= 4.54/200 = 2.27\\%$. Annual $= 2.27\\% \\times \\sqrt{252} = 36.0\\%$.',
      solutionSteps: [
        'Straddle $\\approx $ expected move over $T$ days.',
        'Daily implied move $= \\text{straddle}/\\sqrt{T_{\\text{days}}} = 12/\\sqrt{7} = 12/2.646 = \\$4.54$.',
        'Daily implied vol $= 4.54/200 = 2.27\\%$.',
        'Annualized: $2.27\\% \\times \\sqrt{252} = 36.0\\%$.',
      ],
    },
    // --- INTERVIEW (3) ---
    {
      id: 'd7-spread-17',
      exerciseType: 'speed-drill',
      difficulty: 'interview',
      topic: 'spread-mental-math',
      tags: ['spreads', 'mental-math'],
      timeEstimateSeconds: 90,
      timeLimitSeconds: 90,
      problems: [
        { prompt: 'Bull call spread: buy 100C at $6, sell 105C at $3. Max profit?', correctAnswer: 2.0, tolerance: 0.1 },
        { prompt: 'ATM straddle costs $10 on $100 stock. Breakevens?', correctAnswer: 110.0, tolerance: 0.1 },
        { prompt: 'Butterfly 95/100/105: costs $1.50. Max profit?', correctAnswer: 3.50, tolerance: 0.1 },
        { prompt: 'Straddle approx: S=$100, sigma=24%, T=1mo (sqrt(1/12)=0.289)?', correctAnswer: 5.55, tolerance: 0.3 },
        { prompt: 'Put delta = -0.30, call delta = 0.70. Straddle delta?', correctAnswer: 0.40, tolerance: 0.01 },
      ],
      explanation: 'Quick spread pricing and Greek computations for interviews.',
      solutionSteps: [
        'Bull call: max profit $= 5 - 3 = 2$',
        'Straddle breakevens: $100 \\pm 10 = 90, 110$ (upper $= 110$)',
        'Butterfly max profit $= 5 - 1.50 = 3.50$',
        'Straddle $\\approx 0.8 \\times 100 \\times 0.24 \\times 0.289 = 5.55$',
        'Straddle delta $= 0.70 + (-0.30) = 0.40$ (this is not ATM since delta is skewed)',
      ],
    },
    {
      id: 'd7-spread-18',
      exerciseType: 'free-response',
      difficulty: 'interview',
      topic: 'strategy-selection',
      tags: ['spreads', 'interview', 'strategy'],
      timeEstimateSeconds: 120,
      question: 'Interview: "You think a stock will stay between $95 and $105 over the next month. Current price is $100. How would you express this view with options, and what are the risks?"',
      modelAnswer: 'Sell an ATM straddle or sell a strangle (e.g., sell the 95P and 105C). Alternatively, buy a butterfly or iron condor centered at 100. The straddle sale has the highest premium but unlimited risk. The butterfly/condor has limited risk but lower max profit. Best choice: iron condor (sell 95P/105C, buy 90P/110C) for defined risk. Greeks: short gamma (lose on moves beyond range), long theta (profit from time decay), short vega (profit if vol drops). Key risks: (1) Large gap move beyond the expected range, (2) Vol spike increasing the value of options you sold, (3) Pin risk near expiry if stock is at a short strike. Risk management: define max loss with wings (buy further OTM options), monitor position size, set stop-loss levels.',
      explanation: 'Range-bound view = short vol. Express via short straddle/strangle, butterfly, or iron condor.',
      solutionSteps: [
        'Range-bound view $\\Rightarrow$ short volatility strategy.',
        'Options: (a) Short straddle (aggressive), (b) Short strangle (moderate), (c) Iron condor (defined risk).',
        'Iron condor: sell 95P/105C, buy 90P/110C. Max profit $=$ net credit. Max loss $=$ width $-$ credit.',
        'Greeks: short $\\Gamma$, long $\\Theta$, short $\\mathcal{V}$.',
        'Risks: gap moves, vol spikes, pin risk.',
      ],
    },
    {
      id: 'd7-spread-19',
      exerciseType: 'free-response',
      difficulty: 'interview',
      topic: 'full-chain',
      tags: ['spreads', 'bs', 'greeks', 'forward', 'interview'],
      timeEstimateSeconds: 180,
      question: 'Interview: Walk through the full chain of options analysis for a stock at $100, 3 months to expiry, 25% vol, 5% rate. Start from the forward price, compute approximate BS prices for the ATM straddle, describe the key Greeks, and explain how you would delta-hedge the position.',
      modelAnswer: 'Step 1 (Forward): $F = 100 e^{0.05 \\times 0.25} = 100 \\times 1.0126 = \\$101.26$. Step 2 (BS Pricing): ATM call $\\approx 0.4 \\times 100 \\times 0.25 \\times 0.50 = \\$5.00$. Put via parity: $P = C - S + Ke^{-rT} = 5.00 - 100 + 98.76 = \\$3.76$. Straddle $\\approx 5.00 + 3.76 = \\$8.76$. Step 3 (Greeks): Call delta $\\approx 0.55$, straddle delta $\\approx 0.10$ (slightly positive due to rates). Straddle gamma $\\approx 2 \\times 0.032 = 0.064$. Straddle vega $\\approx 2 \\times 0.20 = 0.40$. Daily theta $\\approx -\\$0.10$. Step 4 (Hedging): Sell 10 shares to offset the 0.10 delta. Rebalance as delta changes. P&L depends on realized vol vs. 25% implied. If realized > 25%, profit (gamma P&L > theta). If realized < 25%, lose.',
      explanation: 'This exercise combines every concept from Days 1-7: forward pricing, BS, Greeks, delta hedging, and vol trading.',
      solutionSteps: [
        'Forward: $F = 100 e^{0.0125} = 101.26$',
        'ATM call $\\approx 0.4 \\times 100 \\times 0.25 \\times 0.50 = \\$5.00$',
        'Put $= C - S + Ke^{-rT} = 5.00 - 100 + 98.76 = \\$3.76$',
        'Straddle $\\approx \\$8.76$. Delta $\\approx 0.10$. Gamma $\\approx 0.064$. Vega $\\approx 0.40$.',
        'Hedge: sell 10 shares. Rebalance daily. P&L driven by realized vs. implied vol.',
      ],
    },
  ],
  cumulativeExercises: [
    {
      id: 'd7-cum-01',
      exerciseType: 'multi-step',
      difficulty: 'hard',
      topic: 'full-chain',
      tags: ['forward', 'bs', 'put-call-parity', 'greeks', 'spreads'],
      timeEstimateSeconds: 300,
      fromDay: 1,
      question: 'Complete chain: $S = 100$, $K_1 = 95$, $K_2 = 105$, $T = 0.5$, $r = 4\\%$, $\\sigma = 25\\%$. (a) Forward price. (b) Approximate 95C price using BS. (c) 105C price. (d) Net delta of the bull call spread (long 95C, short 105C).',
      steps: [
        {
          prompt: 'What is the 6-month forward price?',
          correctAnswer: 102.02,
          tolerance: 0.1,
          unit: '$',
          stepExplanation: '$F = 100 e^{0.04 \\times 0.5} = 100 e^{0.02} = 102.02$.',
        },
        {
          prompt: 'Approximate the 95-strike call price. (Hint: this is 5% ITM. Use intrinsic + time value estimate.)',
          correctAnswer: 9.5,
          tolerance: 1.5,
          unit: '$',
          stepExplanation: 'Intrinsic $\\approx S - Ke^{-rT} = 100 - 93.12 = 6.88$. Time value for near-ATM $\\approx 0.4 \\times 100 \\times 0.25 \\times 0.707 \\times 0.8 \\approx 5.66 \\times 0.8 = 4.53$. Rough total $\\approx 11.4$. (Exact BS gives about $10.5$.)',
        },
        {
          prompt: 'Approximate the 105-strike call price. (OTM, lower delta.)',
          correctAnswer: 4.5,
          tolerance: 1.5,
          unit: '$',
          stepExplanation: 'This is 5% OTM. Time value for near-ATM $\\approx 5.66 \\times 0.7 \\approx 3.96$. (Exact BS gives about $4.0$.)',
        },
        {
          prompt: 'Estimate the net delta of the bull call spread (long 95C, short 105C). ITM delta $\\approx 0.70$, OTM delta $\\approx 0.35$.',
          correctAnswer: 0.35,
          tolerance: 0.1,
          stepExplanation: 'Net delta $= 0.70 - 0.35 = 0.35$. The spread is directionally bullish.',
        },
      ],
      explanation: 'This exercise chains forward pricing, BS pricing, and spread construction across all prior days.',
      solutionSteps: [
        '$F = 100 e^{0.02} = 102.02$',
        '95C: ITM, delta $\\approx 0.70$. Price includes intrinsic + time value $\\approx \\$10.5$.',
        '105C: OTM, delta $\\approx 0.35$. Price is pure time value $\\approx \\$4.0$.',
        'Spread delta $= 0.70 - 0.35 = 0.35$.',
      ],
    },
    {
      id: 'd7-cum-02',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'pde-and-spreads',
      tags: ['greeks', 'pde', 'straddle', 'gamma', 'theta'],
      timeEstimateSeconds: 120,
      fromDay: 6,
      question: 'A long ATM straddle on a $100 stock has position gamma $= 0.08$ and $\\sigma = 30\\%$. Using the gamma-theta relationship ($\\Theta \\approx -\\frac{1}{2}\\sigma^2 S^2 \\Gamma$), compute the annual and daily theta for the straddle.',
      correctAnswer: -0.0986,
      tolerance: 0.005,
      unit: '$ per day',
      explanation: '$|\\Theta_{\\text{annual}}| = \\frac{1}{2}(0.09)(10000)(0.08) = 36.0$. Daily $= 36.0/365 = 0.0986$. Theta $= -\\$0.099$ per day.',
      solutionSteps: [
        '$\\Theta_{\\text{annual}} = -\\frac{1}{2}\\sigma^2 S^2 \\Gamma = -\\frac{1}{2}(0.09)(10000)(0.08) = -36.0$',
        '$\\Theta_{\\text{daily}} = -36.0/365 = -0.0986$',
        'The straddle decays about $\\$0.10$ per day.',
        'Break-even daily move: $\\sqrt{2 \\times 0.099/0.08} = \\sqrt{2.47} = \\$1.57$.',
      ],
    },
    {
      id: 'd7-cum-03',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'ev-and-straddle',
      tags: ['ev', 'straddle', 'implied-move'],
      timeEstimateSeconds: 90,
      fromDay: 3,
      question: 'A 1-month ATM straddle costs $6 on a $100 stock. Assuming the stock\'s move over the month follows a symmetric distribution, what is the market-implied expected absolute move $E[|S_T - S_0|]$?',
      correctAnswer: 6.0,
      tolerance: 0.1,
      unit: '$',
      explanation: 'The straddle payoff $= |S_T - K|$ (for ATM where $K = S_0$). The straddle price is the discounted expected payoff: $\\text{Straddle} \\approx E[|S_T - S_0|]$ (with $r \\approx 0$). So the market-implied expected absolute move is approximately $\\$6$.',
      solutionSteps: [
        'Straddle payoff $= \\max(S_T - K, 0) + \\max(K - S_T, 0) = |S_T - K|$.',
        'For ATM: $= |S_T - S_0|$.',
        'Straddle price $= e^{-rT} E^{\\mathbb{Q}}[|S_T - S_0|] \\approx E[|S_T - S_0|]$ (for small $r$).',
        'So the implied expected absolute move $\\approx \\$6.00$.',
        'This is approximately $6\\%$ of the stock price over 1 month.',
      ],
    },
  ],
  flashcards: [
    { id: 'd7-f01', front: 'Bull call spread construction', back: 'Buy lower-strike call, sell higher-strike call. Max profit $= (K_2 - K_1) - \\text{net premium}$.', tags: ['spreads', 'vertical'] },
    { id: 'd7-f02', front: 'ATM straddle approximation', back: '$\\text{Straddle} \\approx 0.8 S \\sigma \\sqrt{T}$', tags: ['spreads', 'straddle'] },
    { id: 'd7-f03', front: 'Straddle breakevens', back: '$K \\pm \\text{straddle price}$', tags: ['spreads', 'straddle'] },
    { id: 'd7-f04', front: 'Straddle Greeks', back: '$\\Delta \\approx 0$ (ATM), $\\Gamma = 2\\Gamma_{\\text{single}}$, $\\Theta = 2\\Theta_{\\text{single}}$, $\\mathcal{V} = 2\\mathcal{V}_{\\text{single}}$.', tags: ['spreads', 'straddle', 'greeks'] },
    { id: 'd7-f05', front: 'Butterfly construction', back: 'Buy $K_1$, sell $2 \\times K_2$, buy $K_3$ (equally spaced). Max profit at $K_2$. Short vol bet.', tags: ['spreads', 'butterfly'] },
    { id: 'd7-f06', front: 'Long butterfly Greeks', back: '$\\Delta \\approx 0$, $\\Gamma < 0$, $\\Theta > 0$, $\\mathcal{V} < 0$. Short vol with limited risk.', tags: ['spreads', 'butterfly', 'greeks'] },
    { id: 'd7-f07', front: 'Calendar spread: why long vega?', back: 'Far-dated option has more vega ($\\propto \\sqrt{T}$) than near-dated. Net vega is positive.', tags: ['spreads', 'calendar', 'vega'] },
    { id: 'd7-f08', front: 'Risk reversal (equity)', back: 'Long OTM call + Short OTM put. Usually generates credit due to put skew. Bullish directional view.', tags: ['spreads', 'risk-reversal'] },
    { id: 'd7-f09', front: 'Implied move from straddle', back: 'Expected move $\\approx$ straddle price. Daily implied move $\\approx$ straddle$/\\sqrt{T_{\\text{days}}}$.', tags: ['spreads', 'straddle', 'implied-move'] },
    { id: 'd7-f10', front: 'Vertical spread vega', back: 'Much less vega than single legs (partial offset). Good for directional trades with limited vol risk.', tags: ['spreads', 'vertical', 'vega'] },
    { id: 'd7-f11', front: 'Short straddle Greek profile', back: '$\\Delta \\approx 0$, $\\Gamma < 0$, $\\Theta > 0$, $\\mathcal{V} < 0$. Collect theta, pay on moves.', tags: ['spreads', 'straddle', 'greeks'] },
    { id: 'd7-f12', front: '1x2 ratio spread risk', back: 'Unlimited loss on one side (exposed short call/put). Often entered for zero or small net premium.', tags: ['spreads', 'ratio'] },
  ],
  interactiveTools: ['payoff-diagram', 'greek-visualizer', 'bs-calculator'],
  cheatSheet: [
    { topic: 'Bull Call Spread', formula: 'Long K₁C + Short K₂C (K₁<K₂)', description: 'Bullish, capped risk/reward. Delta > 0.' },
    { topic: 'ATM Straddle', formula: 'Long C(K) + Long P(K) ≈ 0.8Sσ√T', description: 'Vol bet. Delta ≈ 0, 2x gamma/theta/vega.' },
    { topic: 'Straddle Breakevens', formula: 'K ± straddle_price', description: 'Stock must move beyond this range to profit.' },
    { topic: 'Butterfly', formula: 'Long K₁ + Short 2K₂ + Long K₃', description: 'Max profit at K₂. Short vol, limited risk.' },
    { topic: 'Calendar Spread', formula: 'Short near-term + Long far-term', description: 'Long vega (far>near). Positive theta.' },
    { topic: 'Iron Condor', formula: 'Sell OTM put spread + Sell OTM call spread', description: 'Short vol, defined risk. Collect premium.' },
    { topic: 'Implied Move', formula: 'Straddle price / √(T_days)', description: 'Market-implied daily expected move.' },
    { topic: 'Risk Reversal', formula: 'Long OTM call + Short OTM put', description: 'Directional with skew exposure. Often net credit in equities.' },
  ],
  summary: [
    'Vertical spreads: directional bets with capped risk. Reduced vega vs. single legs.',
    'Straddle $\\approx 0.8 S \\sigma \\sqrt{T}$: pure vol bet with $\\Delta \\approx 0$ and $2\\times$ gamma/theta/vega.',
    'Butterfly: short vol with limited risk. Max profit at middle strike. $\\Gamma < 0$, $\\Theta > 0$, $\\mathcal{V} < 0$.',
    'Calendar spreads are long vega (far-dated vega $>$ near-dated) and positive theta.',
    'Implied daily move $\\approx$ straddle price $/ \\sqrt{T_{\\text{days}}}$.',
    'Full chain: forward $\\to$ BS pricing $\\to$ Greeks $\\to$ spread construction and Greek analysis.',
  ],
  trackB: {
    title: 'Tree-Based Models & Ensemble Methods',
    subtitle: 'From decision trees to gradient boosting for financial prediction',
    objectives: [
      'Understand decision tree construction via the CART algorithm using Gini impurity and entropy',
      'Explain bagging and the variance-reduction mechanism behind Random Forests',
      'Describe the gradient boosting framework including AdaBoost and XGBoost concepts',
      'Compute and interpret feature importance using MDI and permutation methods',
      'Detect overfitting in tree-based models and apply regularization techniques',
      'Apply tree-based models to volatility regime detection and options pricing features',
    ],
    theory: {
      sections: [
        {
          title: 'Decision Trees: CART Algorithm',
          blocks: [
            {
              type: 'text',
              body: 'A **decision tree** recursively partitions the feature space into rectangular regions, assigning a prediction (class label or value) to each region. The **CART** (Classification and Regression Trees) algorithm builds trees by choosing, at each node, the feature and threshold that best separates the data according to an impurity criterion.',
            },
            {
              type: 'formula',
              latex: 'G(t) = 1 - \\\\sum_{k=1}^{K} p_k^2',
              label: 'Gini Impurity',
              explanation: 'Measures the probability that a randomly chosen sample at node $t$ would be misclassified if labeled according to the class distribution at that node. $p_k$ is the proportion of class $k$ at node $t$. Gini $= 0$ for a pure node.',
            },
            {
              type: 'formula',
              latex: 'H(t) = -\\\\sum_{k=1}^{K} p_k \\\\log_2(p_k)',
              label: 'Entropy',
              explanation: 'An alternative impurity measure from information theory. Entropy is 0 for a pure node and maximized when all classes are equally likely. Measured in bits when using $\\\\log_2$.',
            },
            {
              type: 'formula',
              latex: 'IG = H(\\\\text{parent}) - \\\\sum_{j} \\\\frac{n_j}{n} H(\\\\text{child}_j)',
              label: 'Information Gain',
              explanation: 'The reduction in impurity achieved by splitting on a given feature and threshold. CART selects the split that maximizes information gain (or equivalently, maximally reduces Gini impurity).',
            },
            {
              type: 'example',
              title: 'Computing Gini Impurity for a Vol Regime Split',
              problem: 'A node contains 100 observations: 60 labeled "low vol", 30 labeled "medium vol", 10 labeled "high vol". Compute the Gini impurity. Then consider a split that produces a left child (50 low, 5 medium, 0 high) and a right child (10 low, 25 medium, 10 high). Compute the weighted Gini after the split.',
              solution: [
                'Parent Gini: $G = 1 - (0.60^2 + 0.30^2 + 0.10^2) = 1 - (0.36 + 0.09 + 0.01) = 1 - 0.46 = 0.54$.',
                'Left child ($n_L = 55$): $G_L = 1 - ((50/55)^2 + (5/55)^2 + 0^2) = 1 - (0.826 + 0.008) = 0.166$.',
                'Right child ($n_R = 45$): $G_R = 1 - ((10/45)^2 + (25/45)^2 + (10/45)^2) = 1 - (0.049 + 0.309 + 0.049) = 0.593$.',
                'Weighted Gini: $G_{\\\\text{split}} = (55/100)(0.166) + (45/100)(0.593) = 0.091 + 0.267 = 0.358$.',
                'Gini reduction: $0.54 - 0.358 = 0.182$. This split reduces impurity substantially.',
              ],
            },
            {
              type: 'concept',
              title: 'Pruning',
              body: 'Unpruned trees overfit badly. **Pre-pruning** stops tree growth early using constraints (max depth, min samples per leaf, min impurity decrease). **Post-pruning** (cost-complexity pruning) grows a full tree and then removes branches that provide minimal reduction in a complexity-penalized error: $R_\\\\alpha(T) = R(T) + \\\\alpha |T|$, where $|T|$ is the number of leaves and $\\\\alpha$ is chosen by cross-validation.',
            },
            {
              type: 'callout',
              variant: 'key-insight',
              body: 'A single decision tree is a high-variance, low-bias estimator. Given enough depth, it can memorize any training set (zero training error) but will generalize poorly. This is exactly the problem that ensemble methods (bagging, boosting) are designed to solve.',
            },
          ],
        },
        {
          title: 'Ensemble Methods: Bagging',
          blocks: [
            {
              type: 'text',
              body: '**Bagging** (Bootstrap AGGregatING) reduces variance by training $B$ independent models on bootstrap samples of the training data and averaging their predictions. For classification, majority voting is used. The key insight is that averaging $B$ correlated estimators with pairwise correlation $\\\\rho$ and individual variance $\\\\sigma^2$ yields a variance of $\\\\rho \\\\sigma^2 + (1 - \\\\rho) \\\\sigma^2 / B$.',
            },
            {
              type: 'formula',
              latex: '\\\\text{Var}(\\\\bar{f}) = \\\\rho \\\\sigma^2 + \\\\frac{(1 - \\\\rho) \\\\sigma^2}{B}',
              label: 'Bagging Variance Reduction',
              explanation: 'When $B \\\\to \\\\infty$, the second term vanishes but the first term $\\\\rho \\\\sigma^2$ remains. This is why reducing correlation $\\\\rho$ between base learners (as Random Forests do) is crucial for further variance reduction.',
            },
            {
              type: 'concept',
              title: 'Out-of-Bag (OOB) Error',
              body: 'Each bootstrap sample excludes about $1 - 1/e \\\\approx 36.8\\\\%$ of the original data. These "out-of-bag" observations provide a free validation set. The OOB error is computed by predicting each observation using only the trees for which it was NOT in the bootstrap sample. OOB error is an unbiased estimate of the test error, eliminating the need for a separate validation set.',
            },
            {
              type: 'callout',
              variant: 'tip',
              body: 'In financial applications, standard bootstrap sampling (with replacement from i.i.d. data) can be problematic because financial time series have autocorrelation. Use **block bootstrap** or **purged/embargo cross-validation** to respect temporal structure.',
            },
          ],
        },
        {
          title: 'Random Forests',
          blocks: [
            {
              type: 'text',
              body: '**Random Forests** extend bagging by adding **feature subsampling**: at each split, only a random subset of $m$ features (out of $p$ total) are considered. This decorrelates the individual trees, reducing $\\\\rho$ in the variance formula and yielding better ensemble performance. The typical choice is $m = \\\\sqrt{p}$ for classification and $m = p/3$ for regression.',
            },
            {
              type: 'table',
              headers: ['Hyperparameter', 'Typical Default', 'Effect on Bias/Variance'],
              rows: [
                ['Number of trees $B$', '100-500', 'More trees reduce variance (no increase in bias). Diminishing returns past ~300.'],
                ['Max features $m$', '$\\\\sqrt{p}$ (classification)', 'Smaller $m$ reduces correlation $\\\\rho$, lower variance; may increase bias slightly.'],
                ['Max depth', 'Unlimited', 'Deeper trees have lower bias but higher individual variance. Bagging controls overall variance.'],
                ['Min samples per leaf', '1 (classification)', 'Larger values act as regularization (increase bias, reduce variance).'],
              ],
            },
            {
              type: 'example',
              title: 'Random Forest for Vol Regime Classification',
              problem: 'You build a Random Forest with $B = 200$ trees using 10 features (realized vol, VIX level, put/call ratio, term structure slope, skew, etc.) to classify vol regimes as low/medium/high. Each tree has individual accuracy of 70% and pairwise correlation $\\\\rho = 0.3$. Estimate the ensemble variance reduction compared to a single tree.',
              solution: [
                'Single tree variance: $\\\\sigma^2$ (assume normalized to 1).',
                'Ensemble variance: $\\\\rho \\\\sigma^2 + (1-\\\\rho)\\\\sigma^2/B = 0.3(1) + 0.7(1)/200 = 0.3 + 0.0035 = 0.3035$.',
                'Variance reduction: from $1.0$ to $0.3035$, a $70\\\\%$ reduction.',
                'The irreducible component $\\\\rho \\\\sigma^2 = 0.3$ dominates — further trees barely help.',
                'To improve further: reduce $\\\\rho$ by decreasing $m$ (feature subsample), or use a more diverse feature set.',
              ],
            },
            {
              type: 'callout',
              variant: 'warning',
              body: 'Random Forests can give misleadingly high accuracy on financial data if temporal leakage is not prevented. Always use time-series split (train on past, test on future) rather than random k-fold CV, and apply purging/embargo to remove overlapping labels near the train/test boundary.',
            },
          ],
        },
        {
          title: 'Gradient Boosting',
          blocks: [
            {
              type: 'text',
              body: '**Boosting** builds an ensemble sequentially: each new model focuses on the errors of the previous ensemble. Unlike bagging (which reduces variance), boosting primarily reduces **bias** by iteratively fitting residuals. The two key algorithms are **AdaBoost** (re-weights misclassified samples) and **Gradient Boosting** (fits new trees to the negative gradient of the loss function).',
            },
            {
              type: 'formula',
              latex: 'w_i \\\\leftarrow w_i \\\\cdot \\\\exp\\\\left(\\\\alpha_t \\\\cdot \\\\mathbf{1}[y_i \\\\neq h_t(x_i)]\\\\right)',
              label: 'AdaBoost Weight Update',
              explanation: 'After each round, misclassified samples have their weights increased by factor $e^{\\\\alpha_t}$, where $\\\\alpha_t = \\\\frac{1}{2}\\\\ln\\\\frac{1 - \\\\epsilon_t}{\\\\epsilon_t}$ and $\\\\epsilon_t$ is the weighted error rate. This forces subsequent learners to focus on hard examples.',
            },
            {
              type: 'concept',
              title: 'Gradient Boosting Framework',
              body: 'At round $t$, compute the pseudo-residuals $r_i = -\\\\frac{\\\\partial L(y_i, F(x_i))}{\\\\partial F(x_i)}$ where $F$ is the current ensemble prediction. Fit a new tree $h_t$ to the pseudo-residuals. Update: $F_{t+1}(x) = F_t(x) + \\\\eta \\\\cdot h_t(x)$, where $\\\\eta$ is the learning rate. For squared loss, pseudo-residuals are simply $y_i - F_t(x_i)$.',
            },
            {
              type: 'table',
              headers: ['Parameter', 'Typical Range', 'Effect'],
              rows: [
                ['Learning rate $\\\\eta$', '0.01 - 0.3', 'Smaller $\\\\eta$ requires more trees but generalizes better (shrinkage regularization).'],
                ['Number of rounds $T$', '100 - 10000', 'More rounds reduce bias; too many lead to overfitting (unlike Random Forests).'],
                ['Max depth per tree', '3 - 8', 'Shallow trees (stumps or depth 3-6) are standard; deep trees risk overfitting.'],
                ['Subsample ratio', '0.5 - 0.9', 'Stochastic gradient boosting: each tree sees a random fraction of training data.'],
              ],
            },
            {
              type: 'callout',
              variant: 'key-insight',
              body: 'The key difference: **bagging/RF reduces variance** (averaging many independent, high-variance trees), while **boosting reduces bias** (sequentially correcting errors). In practice, gradient boosting (XGBoost, LightGBM) often achieves the best predictive performance on tabular financial data, but requires careful tuning to prevent overfitting.',
            },
          ],
        },
        {
          title: 'Feature Importance & Model Interpretation',
          blocks: [
            {
              type: 'text',
              body: 'Understanding which features drive predictions is critical in trading, both for model validation and for gaining economic intuition. Tree-based models offer two main importance measures.',
            },
            {
              type: 'concept',
              title: 'Mean Decrease in Impurity (MDI)',
              body: 'MDI (or "Gini importance") sums the total reduction in impurity from all splits on a given feature across all trees. It is fast to compute but has known biases: (1) it favors features with many possible split points (continuous > categorical), (2) it is computed on training data, so it can overstate importance of noisy features. In scikit-learn, `feature_importances_` reports normalized MDI.',
            },
            {
              type: 'concept',
              title: 'Permutation Importance',
              body: 'Permutation importance measures the increase in prediction error when a feature\'s values are randomly shuffled. Unlike MDI, it is computed on a held-out set and is model-agnostic. It correctly identifies features that contribute to generalization. However, it can understate importance of correlated features (shuffling one leaves the correlated feature intact to compensate).',
            },
            {
              type: 'table',
              headers: ['Method', 'Pros', 'Cons'],
              rows: [
                ['MDI (Gini importance)', 'Fast, built-in, no extra data needed', 'Biased toward high-cardinality features; uses training data'],
                ['Permutation importance', 'Unbiased, model-agnostic, uses test data', 'Slow (requires re-evaluation), misleading with correlated features'],
                ['SHAP values', 'Theoretically grounded, per-prediction explanations', 'Computationally expensive for large ensembles'],
              ],
            },
            {
              type: 'callout',
              variant: 'tip',
              body: 'For trading models, always use permutation importance on out-of-sample data to validate feature relevance. Features that appear important by MDI but unimportant by permutation importance are likely capturing noise — a critical overfitting red flag.',
            },
          ],
        },
        {
          title: 'Applications: Vol Regime Detection',
          blocks: [
            {
              type: 'text',
              body: 'Tree-based models excel at detecting **volatility regimes** — discrete market states (low/normal/high/crisis vol) that determine optimal trading strategies. Unlike linear models, trees can capture non-linear interactions between features (e.g., "VIX above 25 AND term structure inverted" signals a different regime than either condition alone).',
            },
            {
              type: 'example',
              title: 'Building a Vol Regime Classifier',
              problem: 'You want to classify daily vol regimes (low: RV < 12%, medium: 12-25%, high: > 25%) using features: 5-day realized vol, VIX level, VIX term structure slope, put/call ratio, SPX 1-month skew, and credit spread level. Describe the workflow and key pitfalls.',
              solution: [
                'Step 1: Label historical data by regime using realized vol thresholds. Use 10+ years of data.',
                'Step 2: Create temporal train/test split (e.g., train on 2010-2020, test on 2021-2023). Never use random CV.',
                'Step 3: Fit a Random Forest (for stability) or Gradient Boosting (for accuracy). Start with RF, $B=300$, $m=\\\\sqrt{6}=2-3$.',
                'Step 4: Evaluate using time-series accuracy, confusion matrix, and regime transition detection lag.',
                'Key pitfalls: (a) Regime labels depend on future realized vol — use only past-looking features. (b) Class imbalance: high-vol regimes are rare. Use SMOTE or class weights. (c) Feature stationarity: credit spreads may have structural breaks across decades.',
              ],
            },
            {
              type: 'concept',
              title: 'Tree Models for Options Pricing Features',
              body: 'Tree-based models are increasingly used in options pricing to capture non-linear feature interactions. Applications include: (1) predicting implied vol changes from order flow and Greeks, (2) identifying mispriced options by comparing model-implied fair values to market quotes, (3) detecting changes in the vol surface shape (skew steepening, term structure inversion) that signal regime shifts. The advantage over linear models is that trees automatically capture threshold effects (e.g., delta hedging costs spike non-linearly above VIX 30).',
            },
            {
              type: 'interactive',
              tool: 'bias-variance-explorer',
              defaultParams: { polynomialDegree: 5, sampleSize: 50, noiseLevel: 1.5 },
            },
            {
              type: 'callout',
              variant: 'key-insight',
              body: 'In practice, the most successful quant firms use gradient boosting (XGBoost/LightGBM) on tabular features for short-horizon alpha signals, but Random Forests for risk regime classification where stability and interpretability matter more than marginal accuracy gains.',
            },
          ],
        },
      ],
    },
    exercises: [
      // --- EASY (5) ---
      {
        id: 'd7b-tree-01',
        exerciseType: 'numeric',
        difficulty: 'easy',
        topic: 'Gini Impurity',
        tags: ['decision-tree', 'gini'],
        timeEstimateSeconds: 60,
        question: 'A node contains 80 samples: 60 from class A and 20 from class B. Compute the Gini impurity.',
        correctAnswer: 0.375,
        tolerance: 0.005,
        explanation: '$G = 1 - (0.75^2 + 0.25^2) = 1 - (0.5625 + 0.0625) = 1 - 0.625 = 0.375$.',
        solutionSteps: [
          'Class proportions: $p_A = 60/80 = 0.75$, $p_B = 20/80 = 0.25$.',
          '$G = 1 - \\\\sum p_k^2 = 1 - (0.75^2 + 0.25^2)$.',
          '$= 1 - (0.5625 + 0.0625) = 1 - 0.625 = 0.375$.',
        ],
      },
      {
        id: 'd7b-tree-02',
        exerciseType: 'numeric',
        difficulty: 'easy',
        topic: 'Entropy',
        tags: ['decision-tree', 'entropy'],
        timeEstimateSeconds: 60,
        question: 'A node has 50% class A and 50% class B. Compute the entropy $H$ in bits.',
        correctAnswer: 1.0,
        tolerance: 0.01,
        explanation: '$H = -(0.5 \\\\log_2 0.5 + 0.5 \\\\log_2 0.5) = -(0.5 \\\\cdot (-1) + 0.5 \\\\cdot (-1)) = 1.0$ bit.',
        solutionSteps: [
          '$H = -\\\\sum p_k \\\\log_2 p_k = -(0.5 \\\\log_2 0.5 + 0.5 \\\\log_2 0.5)$.',
          '$\\\\log_2(0.5) = -1$.',
          '$H = -(0.5 \\\\cdot (-1) + 0.5 \\\\cdot (-1)) = -(-0.5 - 0.5) = 1.0$ bit.',
          'Maximum entropy for a binary classification — no information about which class a random sample belongs to.',
        ],
      },
      {
        id: 'd7b-tree-03',
        exerciseType: 'true-false',
        difficulty: 'easy',
        topic: 'Decision Trees',
        tags: ['decision-tree', 'overfitting'],
        timeEstimateSeconds: 30,
        statement: 'A fully-grown (unpruned) decision tree typically has low bias and high variance.',
        correct: true,
        explanation: 'An unpruned tree can perfectly classify the training data (zero training error = low bias), but the learned decision boundaries are highly sensitive to the specific training data (high variance). Small changes in the data produce very different trees.',
        solutionSteps: [
          'Unpruned tree memorizes training data: training error $\\\\approx 0$ (low bias).',
          'The tree structure changes drastically with different training samples (high variance).',
          'This is why ensemble methods (bagging) are used to reduce variance.',
        ],
      },
      {
        id: 'd7b-tree-04',
        exerciseType: 'multiple-choice',
        difficulty: 'easy',
        topic: 'Gini vs Entropy',
        tags: ['decision-tree', 'gini', 'entropy'],
        timeEstimateSeconds: 45,
        question: 'Which statement about Gini impurity and entropy is TRUE?',
        options: [
          'Gini impurity can be negative for highly pure nodes',
          'Entropy uses base-10 logarithms by convention',
          'Both equal zero for a pure node (all samples from one class)',
          'Entropy is always smaller than Gini impurity',
        ],
        correctIndex: 2,
        explanation: 'Both Gini and entropy measure impurity and both equal zero when all samples belong to a single class ($p_k = 1$ for one class). Gini is bounded in $[0, 1 - 1/K]$ and is never negative. Entropy typically uses $\\\\log_2$ (bits) or $\\\\ln$ (nats).',
        solutionSteps: [
          'Pure node: $p_1 = 1$, all other $p_k = 0$.',
          'Gini: $1 - 1^2 = 0$.',
          'Entropy: $-1 \\\\cdot \\\\log_2(1) = 0$.',
          'Both are zero for pure nodes, confirming option C.',
        ],
      },
      {
        id: 'd7b-rf-01',
        exerciseType: 'multiple-choice',
        difficulty: 'easy',
        topic: 'Random Forests',
        tags: ['random-forest', 'bagging'],
        timeEstimateSeconds: 45,
        question: 'What is the primary mechanism by which Random Forests improve upon bagging?',
        options: [
          'Using deeper trees to reduce bias',
          'Subsampling features at each split to decorrelate trees',
          'Training on the full dataset instead of bootstrap samples',
          'Using entropy instead of Gini impurity',
        ],
        correctIndex: 1,
        explanation: 'Random Forests add feature subsampling (considering only $m$ out of $p$ features at each split). This decorrelates the individual trees, reducing $\\\\rho$ in $\\\\text{Var}(\\\\bar{f}) = \\\\rho\\\\sigma^2 + (1-\\\\rho)\\\\sigma^2/B$, which lowers the ensemble variance beyond what standard bagging achieves.',
        solutionSteps: [
          'Bagging: bootstrap samples, full feature set at each split.',
          'Random Forest: bootstrap samples + random feature subsets at each split.',
          'Feature subsampling reduces inter-tree correlation $\\\\rho$.',
          'Lower $\\\\rho$ $\\\\Rightarrow$ lower ensemble variance $\\\\rho\\\\sigma^2 + (1-\\\\rho)\\\\sigma^2/B$.',
        ],
      },
      // --- MEDIUM (5) ---
      {
        id: 'd7b-tree-05',
        exerciseType: 'numeric',
        difficulty: 'medium',
        topic: 'Information Gain',
        tags: ['decision-tree', 'entropy', 'information-gain'],
        timeEstimateSeconds: 120,
        question: 'A parent node has 100 samples: 70 class A, 30 class B. A split produces Left (50A, 5B) and Right (20A, 25B). Compute the information gain using entropy. Use $\\\\log_2(7/10) \\\\approx -0.515$, $\\\\log_2(3/10) \\\\approx -1.737$, $\\\\log_2(10/11) \\\\approx -0.138$, $\\\\log_2(1/11) \\\\approx -3.459$, $\\\\log_2(4/9) \\\\approx -1.170$, $\\\\log_2(5/9) \\\\approx -0.848$.',
        correctAnswer: 0.312,
        tolerance: 0.02,
        explanation: 'Parent entropy: $H_p = -(0.7\\\\log_2 0.7 + 0.3\\\\log_2 0.3) = -(0.7 \\\\times (-0.515) + 0.3 \\\\times (-1.737)) = 0.361 + 0.521 = 0.882$. Left: $H_L = -(10/11 \\\\cdot (-0.138) + 1/11 \\\\cdot (-3.459)) = 0.126 + 0.314 = 0.440$. Right: $H_R = -(4/9 \\\\cdot (-1.170) + 5/9 \\\\cdot (-0.848)) = 0.520 + 0.471 = 0.991$. $IG = 0.882 - (55/100)(0.440) - (45/100)(0.991) = 0.882 - 0.242 - 0.446 = 0.194$.',
        solutionSteps: [
          'Parent: $p_A = 0.7$, $p_B = 0.3$. $H_p = -(0.7\\\\log_2 0.7 + 0.3\\\\log_2 0.3) = 0.361 + 0.521 = 0.882$.',
          'Left ($n_L=55$): $p_A = 50/55 = 10/11$, $p_B = 5/55 = 1/11$. $H_L \\\\approx 0.440$.',
          'Right ($n_R=45$): $p_A = 20/45 = 4/9$, $p_B = 25/45 = 5/9$. $H_R \\\\approx 0.991$.',
          '$IG = H_p - (n_L/n)H_L - (n_R/n)H_R = 0.882 - 0.242 - 0.446 = 0.194$.',
        ],
      },
      {
        id: 'd7b-rf-02',
        exerciseType: 'numeric',
        difficulty: 'medium',
        topic: 'Bagging Variance',
        tags: ['random-forest', 'bagging', 'variance'],
        timeEstimateSeconds: 90,
        question: 'You build a bagged ensemble of $B = 100$ trees. Each tree has variance $\\\\sigma^2 = 4.0$ and the average pairwise correlation between trees is $\\\\rho = 0.40$. What is the ensemble variance? By what factor is variance reduced compared to a single tree?',
        correctAnswer: 1.624,
        tolerance: 0.01,
        explanation: '$\\\\text{Var}(\\\\bar{f}) = \\\\rho\\\\sigma^2 + (1-\\\\rho)\\\\sigma^2/B = 0.40(4) + 0.60(4)/100 = 1.60 + 0.024 = 1.624$. Reduction factor: $4.0/1.624 = 2.46\\\\times$.',
        solutionSteps: [
          '$\\\\text{Var}(\\\\bar{f}) = \\\\rho\\\\sigma^2 + (1-\\\\rho)\\\\sigma^2/B$.',
          '$= 0.40 \\\\times 4.0 + (1 - 0.40) \\\\times 4.0/100$.',
          '$= 1.60 + 0.024 = 1.624$.',
          'Reduction: $4.0 / 1.624 \\\\approx 2.46\\\\times$.',
          'The correlation term $\\\\rho\\\\sigma^2 = 1.60$ dominates — reducing $\\\\rho$ (via feature subsampling) would help more than adding trees.',
        ],
      },
      {
        id: 'd7b-boost-01',
        exerciseType: 'multiple-choice',
        difficulty: 'medium',
        topic: 'Bagging vs Boosting',
        tags: ['random-forest', 'gradient-boosting', 'bias-variance'],
        timeEstimateSeconds: 60,
        question: 'Which statement correctly distinguishes bagging from boosting?',
        options: [
          'Bagging reduces bias; boosting reduces variance',
          'Bagging reduces variance; boosting primarily reduces bias',
          'Both primarily reduce bias',
          'Both primarily reduce variance',
        ],
        correctIndex: 1,
        explanation: 'Bagging averages many independent, high-variance estimators, reducing variance while leaving bias unchanged. Boosting sequentially corrects the errors of the ensemble, reducing bias (systematic error) at the cost of potentially increasing variance. This is why boosting can overfit if run too long, while bagging generally does not.',
        solutionSteps: [
          'Bagging: parallel, independent trees averaged $\\\\Rightarrow$ variance reduction.',
          'Boosting: sequential, each tree corrects previous errors $\\\\Rightarrow$ bias reduction.',
          'Bagging: more trees never hurts (variance keeps decreasing).',
          'Boosting: too many rounds can overfit (variance starts increasing).',
        ],
      },
      {
        id: 'd7b-boost-02',
        exerciseType: 'free-response',
        difficulty: 'medium',
        topic: 'Gradient Boosting',
        tags: ['gradient-boosting', 'learning-rate', 'regularization'],
        timeEstimateSeconds: 120,
        question: 'Explain the role of the learning rate $\\\\eta$ in gradient boosting. Why does a smaller learning rate typically improve generalization, and what is the tradeoff?',
        modelAnswer: 'The learning rate $\\\\eta$ (also called shrinkage) scales the contribution of each new tree: $F_{t+1}(x) = F_t(x) + \\\\eta \\\\cdot h_t(x)$. A smaller $\\\\eta$ means each tree makes a smaller correction, requiring more trees to achieve the same training loss. This acts as regularization: by taking many small steps in function space, the model is less likely to jump past the optimal solution and overfit. The tradeoff is computational: with $\\\\eta = 0.01$ instead of $\\\\eta = 0.1$, you need roughly 10x more trees, increasing training time proportionally. The standard practice is to set $\\\\eta$ as small as computationally feasible (0.01-0.1) and then choose the number of rounds by early stopping on a validation set.',
        explanation: 'Smaller learning rate = more regularization but more computation. The $\\\\eta$-number of rounds tradeoff is central to gradient boosting tuning.',
        solutionSteps: [
          'Update rule: $F_{t+1} = F_t + \\\\eta h_t$. $\\\\eta$ scales each tree\'s contribution.',
          'Small $\\\\eta$: each step is conservative, harder to overfit, but needs more rounds.',
          'Large $\\\\eta$: aggressive steps, faster training, but risk of overfitting.',
          'Regularization effect: many small steps smooth the function approximation.',
          'Best practice: small $\\\\eta$ (0.01-0.1) with early stopping on validation error.',
        ],
      },
      {
        id: 'd7b-feat-01',
        exerciseType: 'true-false',
        difficulty: 'medium',
        topic: 'Feature Importance',
        tags: ['feature-importance', 'mdi', 'permutation'],
        timeEstimateSeconds: 45,
        statement: 'Mean Decrease in Impurity (MDI / Gini importance) is always a reliable measure of a feature\'s true predictive value on unseen data.',
        correct: false,
        explanation: 'MDI is computed on the training data and is biased toward features with more possible split points (e.g., continuous features vs. binary ones). A random noise feature with high cardinality can appear important by MDI simply because the tree finds many opportunities to split on it. Permutation importance on held-out data is a more reliable measure.',
        solutionSteps: [
          'MDI sums impurity reduction over all splits on a feature — computed on training data.',
          'Bias 1: high-cardinality features get more split opportunities, inflating their MDI.',
          'Bias 2: training-data importance can overstate importance of overfit features.',
          'Permutation importance on test data avoids both biases.',
        ],
      },
      // --- HARD (4) ---
      {
        id: 'd7b-tree-06',
        exerciseType: 'multi-step',
        difficulty: 'hard',
        topic: 'Decision Tree Construction',
        tags: ['decision-tree', 'gini', 'splits'],
        timeEstimateSeconds: 180,
        question: 'You are building a decision tree to classify options trades as profitable (P) or unprofitable (U). At the root, you have 200 samples (120 P, 80 U). Two candidate splits: Split A produces Left(90P, 10U) and Right(30P, 70U). Split B produces Left(60P, 20U) and Right(60P, 60U). Which split is better according to Gini impurity reduction?',
        steps: [
          {
            prompt: 'Compute the parent Gini impurity.',
            correctAnswer: 0.48,
            tolerance: 0.005,
            stepExplanation: '$G_p = 1 - (0.6^2 + 0.4^2) = 1 - (0.36 + 0.16) = 0.48$.',
          },
          {
            prompt: 'Compute the weighted Gini after Split A.',
            correctAnswer: 0.30,
            tolerance: 0.01,
            stepExplanation: 'Left ($n=100$): $G_L = 1 - (0.9^2 + 0.1^2) = 1 - 0.82 = 0.18$. Right ($n=100$): $G_R = 1 - (0.3^2 + 0.7^2) = 1 - 0.58 = 0.42$. Weighted: $(100/200)(0.18) + (100/200)(0.42) = 0.09 + 0.21 = 0.30$.',
          },
          {
            prompt: 'Compute the weighted Gini after Split B.',
            correctAnswer: 0.45,
            tolerance: 0.01,
            stepExplanation: 'Left ($n=80$): $G_L = 1 - (0.75^2 + 0.25^2) = 1 - 0.625 = 0.375$. Right ($n=120$): $G_R = 1 - (0.5^2 + 0.5^2) = 1 - 0.50 = 0.50$. Weighted: $(80/200)(0.375) + (120/200)(0.50) = 0.15 + 0.30 = 0.45$.',
          },
        ],
        explanation: 'Split A achieves Gini reduction of $0.48 - 0.30 = 0.18$, while Split B achieves only $0.48 - 0.45 = 0.03$. Split A is much better — it produces one highly pure node (90% profitable).',
        solutionSteps: [
          'Parent Gini: $1 - (0.6^2 + 0.4^2) = 0.48$.',
          'Split A weighted Gini: $0.5(0.18) + 0.5(0.42) = 0.30$. Reduction = $0.18$.',
          'Split B weighted Gini: $0.4(0.375) + 0.6(0.50) = 0.45$. Reduction = $0.03$.',
          'Split A is superior: it creates a much purer partition.',
        ],
      },
      {
        id: 'd7b-boost-03',
        exerciseType: 'multi-step',
        difficulty: 'hard',
        topic: 'AdaBoost',
        tags: ['adaboost', 'boosting', 'weights'],
        timeEstimateSeconds: 180,
        question: 'In AdaBoost, after round 1 the weak learner achieves weighted error rate $\\\\epsilon_1 = 0.30$ on 10 equally-weighted samples (initial weight $w_i = 0.10$). Samples 3 and 7 are misclassified. (a) Compute the learner weight $\\\\alpha_1$. (b) Compute the updated weight for a correctly classified sample. (c) Compute the updated weight for a misclassified sample. Assume weights are renormalized to sum to 1.',
        steps: [
          {
            prompt: 'Compute $\\\\alpha_1 = \\\\frac{1}{2}\\\\ln\\\\frac{1-\\\\epsilon_1}{\\\\epsilon_1}$.',
            correctAnswer: 0.4236,
            tolerance: 0.01,
            stepExplanation: '$\\\\alpha_1 = \\\\frac{1}{2}\\\\ln\\\\frac{0.70}{0.30} = \\\\frac{1}{2}\\\\ln(2.333) = \\\\frac{1}{2}(0.8473) = 0.4236$.',
          },
          {
            prompt: 'What is the unnormalized weight for a correctly classified sample? (Correct samples: $w_i \\\\cdot e^{-\\\\alpha_1}$)',
            correctAnswer: 0.0655,
            tolerance: 0.002,
            stepExplanation: '$w_i e^{-\\\\alpha_1} = 0.10 \\\\times e^{-0.4236} = 0.10 \\\\times 0.6547 = 0.0655$.',
          },
          {
            prompt: 'What is the unnormalized weight for a misclassified sample? ($w_i \\\\cdot e^{\\\\alpha_1}$)',
            correctAnswer: 0.1528,
            tolerance: 0.005,
            stepExplanation: '$w_i e^{\\\\alpha_1} = 0.10 \\\\times e^{0.4236} = 0.10 \\\\times 1.5275 = 0.1528$.',
          },
        ],
        explanation: 'After normalization, misclassified samples have weight $\\\\approx 0.1528/Z$ and correct samples have weight $\\\\approx 0.0655/Z$, where $Z$ is the normalizing constant. Misclassified samples get $\\\\approx 2.3\\\\times$ the weight of correct ones, forcing the next learner to focus on them.',
        solutionSteps: [
          '$\\\\alpha_1 = 0.5 \\\\ln(0.7/0.3) = 0.4236$.',
          'Correct: $w = 0.10 e^{-0.4236} = 0.0655$. (8 samples)',
          'Wrong: $w = 0.10 e^{0.4236} = 0.1528$. (2 samples)',
          'Sum: $8(0.0655) + 2(0.1528) = 0.524 + 0.306 = 0.830$.',
          'Normalized wrong: $0.1528/0.830 = 0.184$; correct: $0.0655/0.830 = 0.079$.',
        ],
      },
      {
        id: 'd7b-rf-03',
        exerciseType: 'scenario',
        difficulty: 'hard',
        topic: 'Random Forest Overfitting',
        tags: ['random-forest', 'overfitting', 'financial-data'],
        timeEstimateSeconds: 180,
        question: 'A Random Forest classifier predicts vol regimes (low/medium/high) using 10 features. Evaluate the model under different configurations to detect overfitting.',
        scenarios: [
          {
            description: 'Training accuracy = 99%, test accuracy = 62%. Number of trees = 500, max depth = unlimited, min_samples_leaf = 1.',
            shocks: [{ variable: 'train_accuracy', change: 99 }, { variable: 'test_accuracy', change: 62 }],
            expectedAnswer: 37,
            tolerance: 2,
            unit: '% generalization gap',
          },
          {
            description: 'After regularization: max_depth=5, min_samples_leaf=20. Training accuracy = 78%, test accuracy = 71%.',
            shocks: [{ variable: 'train_accuracy', change: 78 }, { variable: 'test_accuracy', change: 71 }],
            expectedAnswer: 7,
            tolerance: 2,
            unit: '% generalization gap',
          },
        ],
        explanation: 'The unrestricted model has a 37% generalization gap (severe overfitting). After regularization, the gap shrinks to 7% and test accuracy improves from 62% to 71%. The unrestricted trees memorize noise in training data, especially problematic with autocorrelated financial features.',
        solutionSteps: [
          'Gap = Train accuracy - Test accuracy.',
          'Unrestricted: $99\\\\% - 62\\\\% = 37\\\\%$ gap. Severe overfitting.',
          'Regularized: $78\\\\% - 71\\\\% = 7\\\\%$ gap. Acceptable.',
          'Test accuracy improved from 62% to 71% despite lower training accuracy.',
          'Regularization (max_depth, min_samples) constrains tree complexity, reducing variance.',
        ],
      },
      {
        id: 'd7b-feat-02',
        exerciseType: 'free-response',
        difficulty: 'hard',
        topic: 'Feature Importance Analysis',
        tags: ['feature-importance', 'permutation', 'trading'],
        timeEstimateSeconds: 150,
        question: 'You build a gradient boosting model to predict next-day implied vol changes using 8 features. MDI importance ranks "yesterday\'s vol change" as #1 (35% importance), but permutation importance on test data ranks it #5 (2% accuracy decrease). Meanwhile, "put/call ratio" is #6 by MDI but #1 by permutation importance. Diagnose the discrepancy and recommend which ranking to trust.',
        modelAnswer: 'The discrepancy indicates "yesterday\'s vol change" is likely overfit — it captures in-sample patterns (perhaps mean-reversion noise) that do not generalize. MDI overstates its importance because: (1) as a continuous feature, it offers many split points, inflating MDI, and (2) the model may be exploiting noise correlations that vanish out-of-sample. "Put/call ratio" has genuine predictive power on unseen data (high permutation importance on test set), but its lower MDI may be due to fewer effective split points or because its signal is subtle (captured in few but critical splits). Trust permutation importance on test data — it measures actual predictive contribution to generalization. Recommended action: (1) drop or regularize "yesterday\'s vol change," (2) investigate "put/call ratio" threshold effects, (3) use SHAP values for deeper feature interaction analysis.',
        explanation: 'MDI vs. permutation importance discrepancies are a key diagnostic for overfitting. Always prefer test-data-based importance measures for model validation in financial applications.',
        solutionSteps: [
          'MDI is computed on training data and biased toward high-cardinality features.',
          'Permutation importance on test data measures true predictive contribution.',
          '"Yesterday\'s vol change": high MDI but low permutation = overfit feature.',
          '"Put/call ratio": low MDI but high permutation = genuinely predictive.',
          'Trust permutation importance. Drop/regularize overfit features.',
        ],
      },
      // --- INTERVIEW (3) ---
      {
        id: 'd7b-interview-01',
        exerciseType: 'free-response',
        difficulty: 'interview',
        topic: 'Vol Regime Detection',
        tags: ['random-forest', 'vol-regime', 'interview', 'options'],
        timeEstimateSeconds: 240,
        question: 'Interview: "You are building a model to detect whether the market is in a low, normal, or high volatility regime, to adjust your options market-making strategy. Would you use a Random Forest or Gradient Boosting? What features would you include? How would you validate the model, given that financial data is time-series?"',
        modelAnswer: 'I would use a Random Forest for regime detection because: (1) stability of predictions matters more than marginal accuracy for a market-making application — regime classification drives position sizing and hedging parameters, so an unstable model is dangerous, (2) Random Forests are less prone to overfitting without careful tuning, which is important given limited regime-change samples. Features: (a) Realized vol (5-day, 20-day, 60-day) at multiple horizons, (b) VIX level and VIX term structure (contango vs. backwardation), (c) Implied vol skew (25-delta risk reversal), (d) Put/call ratio, (e) Credit spreads (OAS), (f) Recent max drawdown. Validation: Time-series split with purging — train on 2010-2019, validate on 2020, test on 2021-2023. Use 5-fold blocked time-series CV for hyperparameter tuning. Apply embargo periods of 5 days around each fold boundary to prevent label leakage. Key metric: not just accuracy but regime transition detection lag — how quickly does the model detect a shift from low to high vol?',
        explanation: 'This tests understanding of the bias-variance tradeoff in practice (RF vs. GBM), financial feature engineering, and proper time-series validation methodology.',
        solutionSteps: [
          'Choose Random Forest for stability in a risk-critical application.',
          'Features: realized vol (multiple horizons), VIX, term structure, skew, put/call ratio, credit spreads.',
          'Validation: time-series split with purging and embargo, NOT random CV.',
          'Metrics: accuracy + regime transition detection lag.',
          'Post-deployment: monitor for concept drift as market regimes evolve.',
        ],
      },
      {
        id: 'd7b-interview-02',
        exerciseType: 'free-response',
        difficulty: 'interview',
        topic: 'Tree Models for Options',
        tags: ['gradient-boosting', 'options', 'interview'],
        timeEstimateSeconds: 240,
        question: 'Interview: "An options desk wants to predict which options are mispriced relative to Black-Scholes. How would you use gradient boosting to identify mispriced options? What features would you use, and how would you define the target variable?"',
        modelAnswer: 'Target variable: next-day IV change (or equivalently, the difference between realized PnL from delta-hedging and the implied-vol-predicted PnL). A positive residual means the option was cheap (realized vol > implied vol). Features for GBM: (1) Current implied vol minus recent realized vol (vol risk premium), (2) Moneyness (delta or log(K/F)), (3) Days to expiry, (4) Skew slope and curvature, (5) Term structure slope, (6) Historical vol of vol, (7) Bid-ask spread (liquidity proxy), (8) Net gamma exposure of dealers (positioning), (9) Recent order flow imbalance. The GBM captures non-linear interactions: e.g., "cheap implied vol relative to realized" + "high dealer short gamma" + "approaching earnings" = high probability the option is underpriced. Validation: walk-forward optimization with 1-month refit windows. Out-of-sample Sharpe and max drawdown of a strategy that buys options predicted to be cheap and sells those predicted to be expensive. Guard against transaction costs: the model must predict mispricings exceeding the bid-ask spread.',
        explanation: 'This tests the ability to formulate a trading problem as a supervised learning task, select meaningful financial features, and think about practical deployment including transaction costs.',
        solutionSteps: [
          'Target: IV change or delta-hedged PnL residual.',
          'Features: vol risk premium, moneyness, DTE, skew, term structure, positioning.',
          'Model: GBM with shallow trees (depth 4-6), learning rate 0.05, early stopping.',
          'Validation: walk-forward with 1-month windows, no future leakage.',
          'Practical: signals must exceed bid-ask spread to be tradeable.',
        ],
      },
      {
        id: 'd7b-interview-03',
        exerciseType: 'scenario',
        difficulty: 'interview',
        topic: 'Model Comparison',
        tags: ['random-forest', 'gradient-boosting', 'interview', 'overfitting'],
        timeEstimateSeconds: 180,
        question: 'You are comparing a Random Forest and a Gradient Boosting model for predicting whether implied vol will increase or decrease over the next week. Analyze the performance metrics to determine which model to deploy.',
        scenarios: [
          {
            description: 'Random Forest: train accuracy = 82%, test accuracy = 68%, prediction stability (std of daily accuracy) = 3%. OOB error = 31%.',
            shocks: [{ variable: 'train_acc', change: 82 }, { variable: 'test_acc', change: 68 }],
            expectedAnswer: 14,
            tolerance: 2,
            unit: '% generalization gap for RF',
          },
          {
            description: 'Gradient Boosting: train accuracy = 95%, test accuracy = 71%, prediction stability (std of daily accuracy) = 8%. No OOB estimate available.',
            shocks: [{ variable: 'train_acc', change: 95 }, { variable: 'test_acc', change: 71 }],
            expectedAnswer: 24,
            tolerance: 2,
            unit: '% generalization gap for GBM',
          },
        ],
        explanation: 'GBM achieves 3% higher test accuracy (71% vs 68%) but has a much larger generalization gap (24% vs 14%) and much higher instability (8% vs 3% std). For a trading application where consistency matters, the Random Forest is likely the better choice despite lower peak accuracy. The GBM\'s 95% train accuracy signals serious overfitting. Recommended: (1) deploy the RF, (2) regularize the GBM aggressively (lower learning rate, shallower trees, more subsample) and retest, (3) consider an ensemble of both.',
        solutionSteps: [
          'RF gap: $82\\\\% - 68\\\\% = 14\\\\%$. GBM gap: $95\\\\% - 71\\\\% = 24\\\\%$.',
          'GBM overfits more severely (24% gap vs 14%).',
          'RF stability: $\\\\pm 3\\\\%$ daily. GBM: $\\\\pm 8\\\\%$ — highly unstable.',
          'For trading: consistency (low variance) often matters more than peak accuracy.',
          'Recommend RF for deployment; regularize GBM before reconsidering.',
        ],
      },
      // Speed drill
      {
        id: 'd7b-speed-01',
        exerciseType: 'speed-drill',
        difficulty: 'easy',
        topic: 'Quick Recall',
        tags: ['decision-tree', 'random-forest', 'boosting', 'speed'],
        timeEstimateSeconds: 120,
        timeLimitSeconds: 120,
        problems: [
          { prompt: 'Gini impurity for a node with 50% class A, 50% class B', correctAnswer: 0.50, tolerance: 0.01 },
          { prompt: 'Entropy (bits) for a pure node (100% one class)', correctAnswer: 0, tolerance: 0 },
          { prompt: 'VC dimension of a decision stump (single threshold on 1 feature)', correctAnswer: 2, tolerance: 0 },
          { prompt: 'Default feature subsample for RF classification with p=16 features: sqrt(16)=?', correctAnswer: 4, tolerance: 0 },
          { prompt: 'Bagging variance with rho=0, sigma^2=1, B=100: (1-0)*1/100 = ?', correctAnswer: 0.01, tolerance: 0.001 },
        ],
        explanation: 'Quick recall: Gini for 50/50 = 0.5, pure entropy = 0, stump VC = 2, sqrt(16) = 4, independent bagging variance = sigma^2/B.',
        solutionSteps: [
          'Gini: $1 - (0.5^2 + 0.5^2) = 0.50$.',
          'Entropy of pure node: $-1 \\\\cdot \\\\log_2(1) = 0$.',
          'Decision stump: like interval in $\\\\mathbb{R}$, VC dim $= 2$.',
          'RF subsample: $m = \\\\sqrt{p} = \\\\sqrt{16} = 4$.',
          'Independent trees ($\\\\rho=0$): Var $= \\\\sigma^2/B = 1/100 = 0.01$.',
        ],
      },
    ],
    flashcards: [
      { id: 'd7b-f01', front: 'What is Gini impurity?', back: '$G(t) = 1 - \\\\sum_k p_k^2$. Probability of misclassifying a random sample at node $t$. Equals 0 for a pure node.', tags: ['decision-tree', 'gini'] },
      { id: 'd7b-f02', front: 'What is entropy (for decision trees)?', back: '$H(t) = -\\\\sum_k p_k \\\\log_2(p_k)$. Measures information content/uncertainty at a node. Equals 0 for a pure node, max at equal class proportions.', tags: ['decision-tree', 'entropy'] },
      { id: 'd7b-f03', front: 'What is information gain?', back: '$IG = H(\\\\text{parent}) - \\\\sum_j (n_j/n) H(\\\\text{child}_j)$. The reduction in impurity from a split. CART selects the split maximizing IG.', tags: ['decision-tree', 'information-gain'] },
      { id: 'd7b-f04', front: 'How does bagging reduce variance?', back: '$\\\\text{Var}(\\\\bar{f}) = \\\\rho\\\\sigma^2 + (1-\\\\rho)\\\\sigma^2/B$. Averaging $B$ models reduces the second term. The correlation term $\\\\rho\\\\sigma^2$ is the irreducible floor.', tags: ['bagging', 'variance'] },
      { id: 'd7b-f05', front: 'How do Random Forests improve on bagging?', back: 'Feature subsampling at each split ($m = \\\\sqrt{p}$ for classification) decorrelates trees, reducing $\\\\rho$ and therefore the irreducible variance floor $\\\\rho\\\\sigma^2$.', tags: ['random-forest'] },
      { id: 'd7b-f06', front: 'What is OOB error?', back: 'Out-of-bag error: each bootstrap sample excludes ~37% of data. Predict each sample using only trees that did NOT include it in training. Free unbiased test error estimate.', tags: ['random-forest', 'oob'] },
      { id: 'd7b-f07', front: 'AdaBoost weight update rule', back: '$w_i \\\\leftarrow w_i \\\\exp(\\\\alpha_t \\\\mathbf{1}[y_i \\\\neq h_t(x_i)])$, where $\\\\alpha_t = \\\\frac{1}{2}\\\\ln\\\\frac{1-\\\\epsilon_t}{\\\\epsilon_t}$. Misclassified samples get higher weight.', tags: ['adaboost', 'boosting'] },
      { id: 'd7b-f08', front: 'Key difference: bagging vs. boosting', back: 'Bagging: parallel trees, reduces variance. Boosting: sequential trees, reduces bias. Bagging is safe from overfitting; boosting can overfit if run too long.', tags: ['bagging', 'boosting'] },
      { id: 'd7b-f09', front: 'MDI vs. permutation importance', back: 'MDI: training-data-based, biased toward high-cardinality features. Permutation: test-data-based, model-agnostic, measures true predictive contribution. Always prefer permutation for validation.', tags: ['feature-importance'] },
      { id: 'd7b-f10', front: 'What learning rate does in gradient boosting', back: '$F_{t+1} = F_t + \\\\eta h_t$. Smaller $\\\\eta$ = more regularization, needs more trees. Best practice: $\\\\eta \\\\in [0.01, 0.1]$ with early stopping.', tags: ['gradient-boosting', 'learning-rate'] },
      { id: 'd7b-f11', front: 'Why is time-series CV essential for financial tree models?', back: 'Standard random CV leaks future information into training folds. Use walk-forward / blocked time-series CV with purging and embargo to prevent look-ahead bias.', tags: ['cross-validation', 'financial'] },
      { id: 'd7b-f12', front: 'RF vs. GBM for trading applications', back: 'RF: more stable predictions, harder to overfit, better for risk-critical applications (regime detection). GBM: higher peak accuracy, better for alpha signals on tabular data, but requires careful tuning.', tags: ['random-forest', 'gradient-boosting', 'trading'] },
    ],
    cheatSheet: [
      { topic: 'Gini Impurity', formula: 'G(t) = 1 - Σ p_k²', description: 'Impurity measure for classification splits. 0 = pure node.' },
      { topic: 'Entropy', formula: 'H(t) = -Σ p_k log₂(p_k)', description: 'Information-theoretic impurity. 0 = pure, max at equal proportions.' },
      { topic: 'Information Gain', formula: 'IG = H(parent) - Σ(n_j/n)H(child_j)', description: 'Impurity reduction from a split. CART maximizes this.' },
      { topic: 'Bagging Variance', formula: 'Var(f̄) = ρσ² + (1-ρ)σ²/B', description: 'Averaging B models with correlation ρ. RF reduces ρ via feature subsampling.' },
      { topic: 'AdaBoost α', formula: 'α_t = ½ ln((1-ε_t)/ε_t)', description: 'Learner weight in AdaBoost. Higher α for more accurate learners.' },
      { topic: 'AdaBoost Weight Update', formula: 'w_i ← w_i · exp(α_t · 1[y_i ≠ h_t(x_i)])', description: 'Misclassified samples get upweighted by exp(α_t).' },
      { topic: 'GBM Update', formula: 'F_{t+1}(x) = F_t(x) + η·h_t(x)', description: 'Sequential fitting of residuals with learning rate η (shrinkage).' },
      { topic: 'RF Feature Subsample', formula: 'm = √p (classification), p/3 (regression)', description: 'Number of features considered at each split. Controls tree correlation.' },
    ],
    summary: [
      'Decision trees split data by maximizing impurity reduction (Gini or entropy). Unpruned trees overfit (low bias, high variance).',
      'Bagging reduces variance by averaging $B$ bootstrap-trained trees: $\\\\text{Var} = \\\\rho\\\\sigma^2 + (1-\\\\rho)\\\\sigma^2/B$.',
      'Random Forests decorrelate trees via feature subsampling ($m = \\\\sqrt{p}$), reducing $\\\\rho$ and further cutting variance.',
      'Gradient Boosting reduces bias by sequentially fitting residuals: $F_{t+1} = F_t + \\\\eta h_t$. Requires careful regularization.',
      'Feature importance: use permutation importance on test data, not MDI, to identify truly predictive features.',
      'For trading: RF for stability-critical applications (regime detection); GBM for peak accuracy on tabular alpha signals. Always use time-series CV.',
    ],
    interactiveTools: ['bias-variance-explorer'],
  },
};

export default day07;
