import { DayContent } from './types';

const day05: DayContent = {
  dayNumber: 5,
  title: 'Black-Scholes Framework II',
  subtitle: 'Natenberg Chapter 18 (continued)',
  week: 1,
  chapters: ['Chapter 18'],
  estimatedMinutes: 110,
  prerequisites: [1, 2, 3, 4],
  objectives: [
    'Construct a replicating portfolio for a European call option',
    'Understand the hedging argument that derives the BS equation',
    'Analyze how BS prices change when assumptions are violated',
    'Extend BS pricing to assets with continuous and discrete dividends',
    'Perform comparative statics on BS inputs',
  ],
  theory: {
    sections: [
      {
        title: 'The Replicating Portfolio',
        blocks: [
          {
            type: 'text',
            body: 'The Black-Scholes formula is not just a pricing formula. It is a **hedging recipe**. At any point in time, a call option can be replicated by holding $\\Delta = N(d_1)$ shares of stock and borrowing $B = Ke^{-r(T-t)} N(d_2)$ dollars at the risk-free rate. The cost of this portfolio equals the BS call price.',
          },
          {
            type: 'formula',
            latex: 'C = \\underbrace{N(d_1)}_{\\Delta} \\cdot S - \\underbrace{K e^{-rT} N(d_2)}_{B}',
            label: 'Call as Replicating Portfolio',
            explanation: 'Long $\\Delta$ shares, short $B$ in bonds. This portfolio has the same value as the call at all times if rebalanced continuously.',
          },
          {
            type: 'example',
            title: 'Replicating Portfolio for an ATM Call',
            problem: '$S = K = 100$, $T = 0.25$, $r = 5\\%$, $\\sigma = 20\\%$. Construct the replicating portfolio.',
            solution: [
              'From Day 4: $d_1 = 0.175$, $d_2 = 0.075$.',
              '$\\Delta = N(0.175) = 0.5695$. Buy 0.5695 shares at $100 = $56.95$.',
              '$B = 100 \\cdot e^{-0.0125} \\cdot N(0.075) = 98.76 \\cdot 0.5299 = 52.33$. Borrow $52.33.',
              'Net cost = $56.95 - $52.33 = $4.62. This equals the BS call price.',
              'To hedge a short call: hold $+0.5695$ shares (delta hedge).',
            ],
          },
          {
            type: 'callout',
            variant: 'key-insight',
            body: 'The replicating portfolio must be **continuously rebalanced** as $S$, $t$, and therefore $d_1$, $d_2$ change. In practice, market makers rebalance discretely (e.g., every few seconds), introducing **hedging error** proportional to $\\Gamma \\cdot (\\Delta S)^2$. This discrete hedging error is the primary source of P&L noise for delta-hedged option positions.',
          },
        ],
      },
      {
        title: 'The Hedging Argument',
        blocks: [
          {
            type: 'text',
            body: 'The BS equation can be derived without any probability theory, using only the hedging argument: (1) Form a portfolio of one option and $-\\Delta$ shares, making it locally riskless. (2) A riskless portfolio must earn the risk-free rate (no-arbitrage). (3) This condition yields the BS partial differential equation. The beauty is that the drift $\\mu$ cancels out. The option price depends only on $\\sigma$, not on the expected return of the stock.',
          },
          {
            type: 'formula',
            latex: '\\frac{\\partial V}{\\partial t} + \\frac{1}{2}\\sigma^2 S^2 \\frac{\\partial^2 V}{\\partial S^2} + rS\\frac{\\partial V}{\\partial S} = rV',
            label: 'Black-Scholes PDE',
            explanation: 'Any European derivative $V(S,t)$ on a non-dividend stock must satisfy this PDE. With appropriate boundary conditions, it gives the BS formula for calls and puts.',
          },
          {
            type: 'concept',
            title: 'Why the Drift Drops Out',
            body: 'The drift $\\mu$ disappears because the option can be perfectly hedged. Since the hedge removes all directional risk, the option position is riskless and must earn $r$. This is why we can price options without knowing the expected return of the stock. Traders only need to estimate $\\sigma$ (volatility), not $\\mu$ (direction).',
          },
          {
            type: 'callout',
            variant: 'key-insight',
            body: 'This is why volatility traders say they "do not need to predict direction." If you can estimate $\\sigma$ accurately and delta-hedge continuously, your P&L depends only on realized vol vs. implied vol, not on whether the stock goes up or down.',
          },
        ],
      },
      {
        title: 'When BS Assumptions Break',
        blocks: [
          {
            type: 'text',
            body: 'Every BS assumption fails in practice. Understanding how each failure affects pricing is critical for a trading career. The model is a starting point, and the deviations from it are where the real trading opportunities live.',
          },
          {
            type: 'table',
            headers: ['Assumption', 'Reality', 'Consequence'],
            rows: [
              ['Constant $\\sigma$', 'Vol varies by strike and time', 'Volatility smile/skew; need local or stochastic vol models'],
              ['Continuous trading', 'Discrete rebalancing', 'Hedging error; gamma risk between rebalances'],
              ['No transaction costs', 'Bid-ask spreads, commissions', 'Wider markets; less frequent rebalancing optimal'],
              ['Constant $r$', 'Yield curve changes', 'Minor for short-dated equity options; big for rates derivatives'],
              ['Lognormal returns', 'Fat tails, jumps', 'OTM options underpriced by BS; skew exists for this reason'],
              ['No dividends', 'Stocks pay dividends', 'Must adjust: replace $S$ with $Se^{-qT}$ or subtract PV of discrete dividends'],
            ],
          },
          {
            type: 'callout',
            variant: 'warning',
            body: 'The most dangerous assumption failure is **jumps** (discontinuous price moves). BS assumes continuous paths, but earnings announcements, geopolitical events, and flash crashes create gap moves that cannot be hedged. This is why options market makers charge a premium over BS theoretical value (the "edge").',
          },
        ],
      },
      {
        title: 'BS with Dividends',
        blocks: [
          {
            type: 'text',
            body: 'There are two standard approaches to handling dividends in Black-Scholes. For indices with many small dividends, we use a continuous yield $q$. For individual stocks with known ex-dividend dates, we subtract the present value of discrete dividends.',
          },
          {
            type: 'formula',
            latex: 'C = S e^{-qT} N(d_1) - K e^{-rT} N(d_2)',
            label: 'BS with Continuous Dividend Yield',
            explanation: '$d_1 = \\frac{\\ln(S/K) + (r - q + \\sigma^2/2)T}{\\sigma\\sqrt{T}}$. Replace the cost of carry $r$ with $r - q$.',
          },
          {
            type: 'formula',
            latex: 'C = S^* N(d_1) - K e^{-rT} N(d_2), \\quad S^* = S - PV(D)',
            label: 'BS with Discrete Dividends',
            explanation: 'Subtract the present value of known dividends from $S$, then apply the standard BS formula with $S^*$ in place of $S$.',
          },
          {
            type: 'example',
            title: 'BS Call with Continuous Dividends',
            problem: '$S = 100$, $K = 100$, $T = 1$, $r = 5\\%$, $q = 2\\%$, $\\sigma = 25\\%$. Compute the call price. Use $N(0.245) \\approx 0.597$ and $N(-0.005) \\approx 0.498$.',
            solution: [
              '$d_1 = \\frac{\\ln(1) + (0.05 - 0.02 + 0.03125)}{0.25} = \\frac{0.06125}{0.25} = 0.245$',
              '$d_2 = 0.245 - 0.25 = -0.005$',
              '$C = 100 e^{-0.02} \\cdot N(0.245) - 100 e^{-0.05} \\cdot N(-0.005)$',
              '$= 98.02 \\times 0.597 - 95.12 \\times 0.498 = 58.52 - 47.37 = 11.15$',
            ],
          },
        ],
      },
      {
        title: 'Comparative Statics: How Inputs Affect BS Price',
        blocks: [
          {
            type: 'text',
            body: 'Before studying the Greeks formally (Day 6), it is important to build intuition for how each BS input affects the option price. These are the "comparative statics" of the model.',
          },
          {
            type: 'table',
            headers: ['Input', 'Call Price', 'Put Price', 'Intuition'],
            rows: [
              ['$S \\uparrow$', 'Increases', 'Decreases', 'Higher S makes calls more ITM, puts more OTM'],
              ['$K \\uparrow$', 'Decreases', 'Increases', 'Higher K makes calls more OTM, puts more ITM'],
              ['$T \\uparrow$', 'Increases', 'Usually increases', 'More time = more optionality (but dividends can reverse for puts)'],
              ['$r \\uparrow$', 'Increases', 'Decreases', 'Higher rates raise forward price, benefiting calls'],
              ['$\\sigma \\uparrow$', 'Increases', 'Increases', 'More vol = more optionality for both calls and puts'],
              ['$q \\uparrow$', 'Decreases', 'Increases', 'Higher dividends lower the forward, hurting calls'],
            ],
          },
          {
            type: 'callout',
            variant: 'tip',
            body: 'The one that surprises most people: increasing $\\sigma$ always increases both call AND put prices. This is because options have convex payoffs. More uncertainty benefits the holder since the upside is unlimited but the downside is floored at zero.',
          },
        ],
      },
    ],
  },
  exercises: [
    // --- EASY (5) ---
    {
      id: 'd5-bs2-01',
      exerciseType: 'numeric',
      difficulty: 'easy',
      topic: 'replicating-portfolio',
      tags: ['bs', 'replication', 'delta'],
      timeEstimateSeconds: 60,
      question: 'A BS call has $N(d_1) = 0.60$ and $N(d_2) = 0.55$. $S = 100$, $Ke^{-rT} = 98$. What is the call price?',
      correctAnswer: 6.10,
      tolerance: 0.01,
      unit: '$',
      explanation: '$C = S \\cdot N(d_1) - Ke^{-rT} \\cdot N(d_2) = 100(0.60) - 98(0.55) = 60 - 53.90 = 6.10$.',
      solutionSteps: [
        '$C = S \\cdot N(d_1) - Ke^{-rT} \\cdot N(d_2)$',
        '$= 100(0.60) - 98(0.55)$',
        '$= 60.00 - 53.90 = 6.10$',
      ],
    },
    {
      id: 'd5-bs2-02',
      exerciseType: 'numeric',
      difficulty: 'easy',
      topic: 'replicating-portfolio',
      tags: ['bs', 'replication'],
      timeEstimateSeconds: 45,
      question: 'In the replicating portfolio for the call in the previous exercise, how many shares do you hold and how much do you borrow?',
      correctAnswer: 0.60,
      tolerance: 0.01,
      unit: 'shares',
      explanation: 'Shares $= N(d_1) = 0.60$. Borrowing $= Ke^{-rT} N(d_2) = 98 \\times 0.55 = 53.90$.',
      solutionSteps: [
        'Shares held $= \\Delta = N(d_1) = 0.60$',
        'Amount borrowed $= Ke^{-rT} N(d_2) = 98 \\times 0.55 = \\$53.90$',
        'Net portfolio value $= 0.60 \\times 100 - 53.90 = 6.10 = C$. Confirmed.',
      ],
    },
    {
      id: 'd5-bs2-03',
      exerciseType: 'true-false',
      difficulty: 'easy',
      topic: 'bs-hedging',
      tags: ['bs', 'hedging'],
      timeEstimateSeconds: 20,
      statement: 'The Black-Scholes option price depends on the expected return (drift) of the underlying stock.',
      correct: false,
      explanation: 'The drift $\\mu$ cancels out in the hedging argument. The BS price depends only on $S$, $K$, $T$, $r$, and $\\sigma$. This is because the option can be replicated, eliminating directional risk.',
      solutionSteps: [
        'In the derivation of BS, forming a delta-hedged portfolio eliminates directional risk.',
        'A riskless portfolio must earn $r$, regardless of $\\mu$.',
        'The drift drops out; only $\\sigma$ matters (plus $S$, $K$, $T$, $r$).',
      ],
    },
    {
      id: 'd5-bs2-04',
      exerciseType: 'multiple-choice',
      difficulty: 'easy',
      topic: 'bs-assumptions',
      tags: ['bs', 'assumptions'],
      timeEstimateSeconds: 30,
      question: 'Which of the following is NOT an assumption of the standard Black-Scholes model?',
      options: [
        'Volatility is constant',
        'Markets are continuously tradeable',
        'The risk-free rate is constant',
        'Stock returns follow a normal distribution',
      ],
      correctIndex: 3,
      explanation: 'BS assumes log-returns (not returns themselves) are normally distributed, meaning prices are lognormally distributed. This ensures prices stay positive. "Stock returns follow a normal distribution" is incorrect because it would allow negative prices.',
      solutionSteps: [
        'BS assumes GBM: $dS/S = \\mu dt + \\sigma dW$.',
        'This means $\\ln(S_T/S_0)$ is normal (log-returns are normal).',
        'The price $S_T$ itself is lognormal, not normal.',
        'Saying "stock returns are normal" confuses returns with log-returns.',
      ],
    },
    {
      id: 'd5-bs2-05',
      exerciseType: 'true-false',
      difficulty: 'easy',
      topic: 'comparative-statics',
      tags: ['bs', 'comparative-statics'],
      timeEstimateSeconds: 20,
      statement: 'Increasing volatility always increases the price of a European put option.',
      correct: true,
      explanation: 'Higher volatility increases both call and put prices. Options have convex payoffs, so more uncertainty benefits the holder. The downside is bounded by zero, but the upside is not.',
      solutionSteps: [
        'Put payoff $= \\max(K - S_T, 0)$ is convex in $S_T$.',
        'More volatility spreads the distribution of $S_T$.',
        'By Jensen\'s inequality, $E[\\max(K - S_T, 0)]$ increases when $S_T$ has more variance.',
        'So both call and put prices increase with volatility.',
      ],
    },
    // --- MEDIUM (6) ---
    {
      id: 'd5-bs2-06',
      exerciseType: 'multi-step',
      difficulty: 'medium',
      topic: 'replicating-portfolio',
      tags: ['bs', 'replication', 'delta-hedge'],
      timeEstimateSeconds: 180,
      question: 'You sold 100 ATM calls ($K = 50$) on a stock at $50. $d_1 = 0.15$, $N(0.15) = 0.5596$. (a) How many shares do you buy to delta-hedge? (b) If the stock moves to $52, approximately how much do you gain/lose on the shares before rebalancing?',
      steps: [
        {
          prompt: 'How many shares do you buy to delta-hedge 100 short calls?',
          correctAnswer: 55.96,
          tolerance: 0.5,
          unit: 'shares',
          stepExplanation: 'Short 100 calls means delta exposure $= -100 \\times 0.5596 = -55.96$. Buy 55.96 shares to offset.',
        },
        {
          prompt: 'If the stock moves from $50 to $52, what is your approximate P&L on the share position?',
          correctAnswer: 111.92,
          tolerance: 2.0,
          unit: '$',
          stepExplanation: 'Share P&L $= 55.96 \\times (52 - 50) = 55.96 \\times 2 = \\$111.92$. The short calls lost approximately the same amount (for small moves, delta hedge is perfect).',
        },
      ],
      explanation: 'Delta hedging offsets small stock moves. The residual P&L comes from gamma (second-order effects) and theta.',
      solutionSteps: [
        'Each call has delta $= N(d_1) = 0.5596$.',
        'Short 100 calls $\\Rightarrow$ delta $= -55.96$.',
        'Buy 55.96 shares to neutralize delta.',
        'Share P&L for $\\Delta S = +2$: $55.96 \\times 2 = \\$111.92$.',
        'This approximately offsets the loss on the short calls.',
      ],
    },
    {
      id: 'd5-bs2-07',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'bs-dividends',
      tags: ['bs', 'dividends', 'discrete'],
      timeEstimateSeconds: 120,
      question: 'A stock is at $100 and will pay a $2 dividend in 30 days. $K = 100$, $T = 90$ days, $r = 4\\%$, $\\sigma = 25\\%$. What is the adjusted stock price $S^*$ to use in BS?',
      correctAnswer: 98.01,
      tolerance: 0.05,
      unit: '$',
      explanation: '$PV(D) = 2 \\cdot e^{-0.04 \\times 30/365} = 2 \\cdot 0.99671 = 1.993$. $S^* = 100 - 1.993 = 98.007$.',
      solutionSteps: [
        '$PV(D) = D \\cdot e^{-r \\cdot t_D} = 2 \\cdot e^{-0.04 \\times 30/365}$',
        '$= 2 \\cdot e^{-0.003288} = 2 \\times 0.99671 = 1.993$',
        '$S^* = S - PV(D) = 100 - 1.993 = 98.007$',
        'Use $S^* = 98.01$ in the standard BS formula in place of $S$.',
      ],
    },
    {
      id: 'd5-bs2-08',
      exerciseType: 'free-response',
      difficulty: 'medium',
      topic: 'bs-assumptions',
      tags: ['bs', 'assumptions', 'hedging-error'],
      timeEstimateSeconds: 120,
      question: 'Explain why discrete (rather than continuous) rebalancing creates hedging error in delta-hedged option positions. How does gamma relate to this error?',
      modelAnswer: 'Between rebalances, the delta changes as S moves, but the hedge is stale (based on the old delta). The P&L error from a stock move of size $\\Delta S$ is approximately $\\frac{1}{2} \\Gamma (\\Delta S)^2$. This is because the option P&L has a second-order (quadratic) term that the linear delta hedge does not capture. High-gamma positions have larger hedging errors. In practice, market makers rebalance more frequently for high-gamma positions. The cost of this gamma P&L is offset by theta (time decay), leading to the fundamental gamma-theta tradeoff.',
      explanation: 'Discrete rebalancing means the hedge is always slightly wrong. The error is proportional to gamma and the square of the stock move.',
      solutionSteps: [
        'Delta hedge is linear: it matches the first derivative of the option price.',
        'The option price is curved (convex), so a linear hedge undershoots on large moves.',
        'Error $\\approx \\frac{1}{2} \\Gamma (\\Delta S)^2$ per rebalance period.',
        'High gamma $\\Rightarrow$ more curvature $\\Rightarrow$ larger hedging errors.',
        'More frequent rebalancing reduces error but increases transaction costs.',
      ],
    },
    {
      id: 'd5-bs2-09',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'bs-dividends',
      tags: ['bs', 'dividends', 'continuous'],
      timeEstimateSeconds: 120,
      question: 'Using BS with continuous dividends: $S = 100$, $K = 100$, $T = 0.5$, $r = 5\\%$, $q = 3\\%$, $\\sigma = 20\\%$. Compute $d_1$.',
      correctAnswer: 0.141,
      tolerance: 0.01,
      explanation: '$d_1 = \\frac{\\ln(1) + (0.05 - 0.03 + 0.02)(0.5)}{0.20 \\times 0.7071} = \\frac{0.02}{0.1414} = 0.141$.',
      solutionSteps: [
        '$d_1 = \\frac{\\ln(S/K) + (r - q + \\sigma^2/2)T}{\\sigma\\sqrt{T}}$',
        '$= \\frac{\\ln(1) + (0.05 - 0.03 + 0.02) \\times 0.5}{0.20 \\times 0.7071}$',
        '$= \\frac{0 + 0.02}{0.1414} = 0.141$',
      ],
    },
    {
      id: 'd5-bs2-10',
      exerciseType: 'multiple-choice',
      difficulty: 'medium',
      topic: 'comparative-statics',
      tags: ['bs', 'comparative-statics'],
      timeEstimateSeconds: 45,
      question: 'An increase in the risk-free rate $r$ will:',
      options: [
        'Increase both call and put prices',
        'Decrease both call and put prices',
        'Increase call price, decrease put price',
        'Decrease call price, increase put price',
      ],
      correctIndex: 2,
      explanation: 'Higher $r$ increases the forward price $F = Se^{rT}$. Since the forward goes up, calls benefit and puts suffer. Alternatively, from parity: $C - P = S - Ke^{-rT}$. Increasing $r$ increases $Ke^{-rT}$\'s discount, increasing $C - P$.',
      solutionSteps: [
        'Higher $r$ increases the forward: $F = Se^{rT}$.',
        'A higher forward makes it more likely the call is ITM and the put OTM.',
        'From the rho Greek: $\\rho_{\\text{call}} > 0$, $\\rho_{\\text{put}} < 0$.',
        'Also from parity: $C - P = S - Ke^{-rT}$. If $r \\uparrow$, $Ke^{-rT} \\downarrow$, so $C - P \\uparrow$.',
      ],
    },
    {
      id: 'd5-bs2-11',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'bs-hedging',
      tags: ['bs', 'hedging', 'pnl'],
      timeEstimateSeconds: 90,
      question: 'You are long 1 call with delta 0.50 and gamma 0.03. The stock moves from $100 to $103. Estimate your option P&L using the Taylor expansion: $\\Delta P \\approx \\Delta \\cdot \\Delta S + \\frac{1}{2} \\Gamma \\cdot (\\Delta S)^2$.',
      correctAnswer: 1.635,
      tolerance: 0.02,
      unit: '$',
      explanation: '$\\Delta P \\approx 0.50 \\times 3 + 0.5 \\times 0.03 \\times 9 = 1.50 + 0.135 = 1.635$.',
      solutionSteps: [
        'First-order (delta) P&L: $\\Delta \\cdot \\Delta S = 0.50 \\times 3 = 1.50$',
        'Second-order (gamma) P&L: $\\frac{1}{2} \\Gamma (\\Delta S)^2 = 0.5 \\times 0.03 \\times 9 = 0.135$',
        'Total: $1.50 + 0.135 = 1.635$',
        'The gamma term adds to the P&L for a long gamma position (convexity benefit).',
      ],
    },
    // --- HARD (5) ---
    {
      id: 'd5-bs2-12',
      exerciseType: 'multi-step',
      difficulty: 'hard',
      topic: 'replicating-portfolio',
      tags: ['bs', 'replication', 'delta-hedge', 'pnl'],
      timeEstimateSeconds: 240,
      question: 'You sold 1 call at the BS price of $4.62 ($S = K = 100$, $\\Delta = 0.57$, $\\Gamma = 0.027$). You delta-hedge by buying 0.57 shares. The stock drops to $97. (a) What is your share P&L? (b) What is your option P&L? (c) What is your net hedged P&L?',
      steps: [
        {
          prompt: 'What is your P&L on the 0.57 shares?',
          correctAnswer: -1.71,
          tolerance: 0.05,
          unit: '$',
          stepExplanation: 'Share P&L $= 0.57 \\times (97 - 100) = 0.57 \\times (-3) = -1.71$',
        },
        {
          prompt: 'What is the approximate change in the call value (your short option P&L)?',
          correctAnswer: 1.59,
          tolerance: 0.1,
          unit: '$',
          stepExplanation: 'Call change $\\approx \\Delta \\cdot (-3) + \\frac{1}{2}\\Gamma \\cdot 9 = -1.71 + 0.1215 = -1.5885$. Since you are short the call, your P&L $= +1.5885 \\approx +1.59$.',
        },
        {
          prompt: 'What is the net hedged P&L?',
          correctAnswer: -0.12,
          tolerance: 0.05,
          unit: '$',
          stepExplanation: 'Net $= -1.71 + 1.59 = -0.12$. The residual loss is the gamma effect: you are short gamma, so moves hurt you. Loss $\\approx \\frac{1}{2} \\Gamma (\\Delta S)^2 = \\frac{1}{2}(0.027)(9) = 0.12$.',
        },
      ],
      explanation: 'This illustrates why being short gamma (short options) loses money on large moves, even after delta hedging.',
      solutionSteps: [
        'Share P&L: $0.57 \\times (-3) = -1.71$',
        'Option P&L (short call): $-(0.57 \\times (-3) + 0.5 \\times 0.027 \\times 9) = -(-1.71 + 0.12) = +1.59$',
        'Net: $-1.71 + 1.59 = -0.12$',
        'This equals $-\\frac{1}{2}\\Gamma(\\Delta S)^2 = -0.5 \\times 0.027 \\times 9 = -0.12$. Short gamma always loses on moves.',
      ],
    },
    {
      id: 'd5-bs2-13',
      exerciseType: 'free-response',
      difficulty: 'hard',
      topic: 'bs-assumptions',
      tags: ['bs', 'assumptions', 'jumps'],
      timeEstimateSeconds: 150,
      question: 'A stock drops 15% overnight on an earnings miss. The BS model did not price this possibility into the call. Explain how jump risk affects BS pricing and how market makers deal with it.',
      modelAnswer: 'BS assumes continuous price paths (GBM), so it cannot capture gap moves. Consequences: (1) OTM puts are underpriced by BS because large down-moves are more likely than lognormal suggests. This is why the implied volatility skew exists: OTM puts trade at higher implied vols. (2) Hedging is impossible during the gap because you cannot rebalance. The delta hedge right before the gap is stale. Market makers deal with this by: (a) Charging a premium (edge) above BS fair value, (b) Reducing position sizes around known events (earnings, FOMC), (c) Using the volatility skew to implicitly price tail risk, (d) Running stress tests on their portfolio for gap scenarios, (e) Using event-vol models that separate "event vol" from "regular vol."',
      explanation: 'Jump risk is unhedgeable in the BS framework and is the primary reason options trade at a premium to BS theoretical values.',
      solutionSteps: [
        'BS assumes $dS = \\mu S\\,dt + \\sigma S\\,dW$ (continuous paths, no jumps).',
        'A 15% overnight gap is a jump event, not modeled by GBM.',
        'During the gap, the delta hedge cannot be rebalanced.',
        'Result: BS underprices tail risk, especially for OTM puts.',
        'Market makers compensate by: trading with edge, reducing event exposure, using the vol skew.',
      ],
    },
    {
      id: 'd5-bs2-14',
      exerciseType: 'scenario',
      difficulty: 'hard',
      topic: 'comparative-statics',
      tags: ['bs', 'comparative-statics', 'sensitivity'],
      timeEstimateSeconds: 150,
      question: 'Base case: ATM call with $C = 8.00$, $S = K = 100$, $T = 1$, $r = 0$, $\\sigma = 20\\%$. Using the ATM approximation $C \\approx 0.4 S \\sigma \\sqrt{T}$, estimate the call price under each scenario.',
      scenarios: [
        {
          description: 'Vol increases from 20% to 25% (vega effect)',
          shocks: [{ variable: 'sigma', change: 5 }],
          expectedAnswer: 10.0,
          tolerance: 0.3,
          unit: '$',
        },
        {
          description: 'Time passes: T drops from 1.0 to 0.5 (theta effect)',
          shocks: [{ variable: 'T', change: -0.5 }],
          expectedAnswer: 5.66,
          tolerance: 0.2,
          unit: '$',
        },
        {
          description: 'Stock drops to $90 (delta effect)',
          shocks: [{ variable: 'S', change: -10 }],
          expectedAnswer: 3.0,
          tolerance: 1.0,
          unit: '$',
        },
      ],
      explanation: 'These scenarios preview the Greeks: vega (vol sensitivity), theta (time decay), and delta (stock sensitivity).',
      solutionSteps: [
        'Base: $0.4 \\times 100 \\times 0.20 \\times 1 = 8.00$',
        'Vol to 25%: $0.4 \\times 100 \\times 0.25 \\times 1 = 10.00$ (linear in vol)',
        'T to 0.5: $0.4 \\times 100 \\times 0.20 \\times \\sqrt{0.5} = 0.4 \\times 100 \\times 0.20 \\times 0.707 = 5.66$',
        'S to 90: now OTM, the ATM approx no longer applies directly. Rough estimate: call loses about $\\Delta \\times 10 \\approx 0.50 \\times 10 = 5$, so $C \\approx 3$.',
      ],
    },
    {
      id: 'd5-bs2-15',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'bs-dividends',
      tags: ['bs', 'dividends', 'put-call-parity'],
      timeEstimateSeconds: 150,
      question: 'For a stock paying continuous dividend $q$, put-call parity becomes $C - P = Se^{-qT} - Ke^{-rT}$. With $S = 100$, $K = 100$, $T = 1$, $r = 5\\%$, $q = 3\\%$, compute $C - P$.',
      correctAnswer: 1.92,
      tolerance: 0.05,
      unit: '$',
      explanation: '$C - P = 100 e^{-0.03} - 100 e^{-0.05} = 97.04 - 95.12 = 1.92$. Dividends reduce $C - P$ relative to the no-dividend case.',
      solutionSteps: [
        '$C - P = Se^{-qT} - Ke^{-rT}$',
        '$= 100 e^{-0.03} - 100 e^{-0.05}$',
        '$= 97.04 - 95.12 = 1.92$',
        'Compare to no-dividend case: $C - P = 100 - 95.12 = 4.88$. Dividends reduce $C - P$.',
      ],
    },
    {
      id: 'd5-bs2-16',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'bs-hedging',
      tags: ['bs', 'hedging', 'transaction-costs'],
      timeEstimateSeconds: 120,
      question: 'A market maker rebalances a delta hedge every time the stock moves $1. Their gamma is 0.02 per dollar of stock. After 5 rebalancing events (stock moves: +1, -1, +1, +1, -1), what is the total gamma P&L? (They are long gamma.)',
      correctAnswer: 0.05,
      tolerance: 0.01,
      unit: '$',
      explanation: 'Each move of $\\pm 1$ produces gamma P&L of $\\frac{1}{2} \\Gamma (\\Delta S)^2 = \\frac{1}{2}(0.02)(1) = 0.01$ per move. Long gamma profits on moves. Total $= 5 \\times 0.01 = 0.05$.',
      solutionSteps: [
        'Gamma P&L per move $= \\frac{1}{2} \\Gamma (\\Delta S)^2 = \\frac{1}{2}(0.02)(1^2) = 0.01$',
        'Long gamma: you profit $0.01$ on each $\\$1$ move (regardless of direction).',
        'After 5 moves: total gamma P&L $= 5 \\times 0.01 = \\$0.05$.',
        'This is offset by theta: the option decays by approximately $\\$0.05$ over the same period (gamma-theta tradeoff).',
      ],
    },
    // --- INTERVIEW (3) ---
    {
      id: 'd5-bs2-17',
      exerciseType: 'speed-drill',
      difficulty: 'interview',
      topic: 'bs-mental-math',
      tags: ['bs', 'mental-math', 'replication'],
      timeEstimateSeconds: 90,
      timeLimitSeconds: 90,
      problems: [
        { prompt: 'ATM call, delta = 0.50. You sell 100 calls. How many shares to hedge?', correctAnswer: 50, tolerance: 1 },
        { prompt: 'Call delta = 0.70, gamma = 0.02. Stock moves +$5. New approximate delta?', correctAnswer: 0.80, tolerance: 0.02 },
        { prompt: 'You are short gamma 0.04. Stock moves $2. Your gamma P&L?', correctAnswer: -0.08, tolerance: 0.01 },
        { prompt: 'ATM straddle approximation: S=$100, sigma=30%, T=0.25yr?', correctAnswer: 12.0, tolerance: 0.5 },
        { prompt: 'If r increases by 1%, call (delta=0.5, T=1yr) changes by approx? (rho ~ delta*T*Ke^-rT/100)', correctAnswer: 0.50, tolerance: 0.1 },
      ],
      explanation: 'Quick mental math for hedging and BS sensitivities.',
      solutionSteps: [
        'Shares to hedge: $100 \\times 0.50 = 50$',
        'New delta: $0.70 + 0.02 \\times 5 = 0.80$',
        'Short gamma P&L: $-\\frac{1}{2}(0.04)(4) = -0.08$',
        'Straddle: $0.8 \\times 100 \\times 0.30 \\times 0.50 = 12.0$',
        'Rho effect: $\\approx 0.50 \\times 1 \\times 100/100 = 0.50$ per 1% rate change',
      ],
    },
    {
      id: 'd5-bs2-18',
      exerciseType: 'free-response',
      difficulty: 'interview',
      topic: 'bs-assumptions',
      tags: ['bs', 'assumptions', 'interview'],
      timeEstimateSeconds: 120,
      question: 'Interview question: "The Black-Scholes model is wrong. Why do we still use it?" Give a concise answer.',
      modelAnswer: 'BS is wrong because its assumptions (constant vol, continuous trading, lognormal returns, no jumps) all fail. But we use it because: (1) It provides a common language. When a trader says "implied vol is 25," everyone knows what that means through BS. (2) It gives the right hedging intuition. Delta, gamma, and the other Greeks from BS are excellent first-order hedge ratios even when the model is imperfect. (3) The errors are well-understood and can be systematically corrected (vol skew, discrete hedging adjustments, jump risk premiums). (4) It is fast to compute, allowing real-time pricing. (5) The market prices options in terms of implied vol (a BS concept), so understanding BS is necessary to participate. As Box said: "All models are wrong, but some are useful."',
      explanation: 'BS is the universal language of options and provides excellent first-order hedging, even though its assumptions fail.',
      solutionSteps: [
        'BS is wrong: constant vol, continuous trading, no jumps all fail in practice.',
        'Still used because: common language (implied vol), good hedge ratios (delta, gamma).',
        'Errors are systematic and can be adjusted for.',
        'Fast computation enables real-time trading.',
        '"All models are wrong, but some are useful" (George Box).',
      ],
    },
    {
      id: 'd5-bs2-19',
      exerciseType: 'free-response',
      difficulty: 'interview',
      topic: 'bs-hedging',
      tags: ['bs', 'hedging', 'interview', 'pnl'],
      timeEstimateSeconds: 120,
      question: 'You buy an ATM straddle at 25% implied vol and delta-hedge. Over the life of the option, the stock realizes 30% vol. Explain qualitatively whether you make or lose money, and why.',
      modelAnswer: 'You make money. You bought options at 25% implied vol and the stock realized 30% vol. Since realized > implied, the gamma profits from large daily moves exceed the theta you pay. Specifically, your daily P&L from delta hedging is approximately $\\frac{1}{2}\\Gamma S^2(\\sigma_{\\text{realized}}^2 - \\sigma_{\\text{implied}}^2) dt$. Since $30^2 > 25^2$, this is positive on average. Over the life of the option, the cumulative gamma P&L exceeds the total theta paid, resulting in a net profit. The intuition: you paid for "25% worth of moves" but got "30% worth of moves," pocketing the difference.',
      explanation: 'Delta-hedged option P&L is driven by realized vol minus implied vol. Buying vol at 25% when 30% is realized is profitable.',
      solutionSteps: [
        'Bought options at 25% implied vol.',
        'Realized vol was 30% > 25%. The stock moved more than the option priced in.',
        'Daily gamma P&L $\\propto \\Gamma S^2 (\\sigma_{\\text{real}}^2 - \\sigma_{\\text{impl}}^2)$.',
        'Since $0.30^2 - 0.25^2 = 0.09 - 0.0625 = 0.0275 > 0$, you profit daily.',
        'Net P&L is positive: gamma gains > theta costs.',
      ],
    },
  ],
  cumulativeExercises: [
    {
      id: 'd5-cum-01',
      exerciseType: 'multi-step',
      difficulty: 'hard',
      topic: 'full-chain',
      tags: ['forward', 'put-call-parity', 'bs'],
      timeEstimateSeconds: 240,
      fromDay: 1,
      question: 'Full pricing chain: $S = 100$, $K = 100$, $T = 0.5$, $r = 4\\%$, $q = 1\\%$ (continuous dividend), $\\sigma = 25\\%$. (a) Compute the forward price. (b) Compute $d_1$ using the dividend-adjusted formula. (c) Verify $C - P = Se^{-qT} - Ke^{-rT}$.',
      steps: [
        {
          prompt: 'What is the 6-month forward price?',
          correctAnswer: 101.51,
          tolerance: 0.1,
          unit: '$',
          stepExplanation: '$F = S e^{(r-q)T} = 100 e^{(0.04-0.01) \\times 0.5} = 100 e^{0.015} = 101.51$',
        },
        {
          prompt: 'What is $d_1$?',
          correctAnswer: 0.161,
          tolerance: 0.01,
          stepExplanation: '$d_1 = \\frac{\\ln(100/100) + (0.04 - 0.01 + 0.03125) \\times 0.5}{0.25 \\times 0.7071} = \\frac{0.030625}{0.1768} = 0.173$',
        },
        {
          prompt: 'What is $Se^{-qT} - Ke^{-rT}$ (the put-call parity spread)?',
          correctAnswer: 1.49,
          tolerance: 0.1,
          unit: '$',
          stepExplanation: '$Se^{-qT} = 100 e^{-0.005} = 99.50$. $Ke^{-rT} = 100 e^{-0.02} = 98.02$. Spread $= 99.50 - 98.02 = 1.48$.',
        },
      ],
      explanation: 'This exercise connects forward pricing (Day 1), put-call parity (Day 1), and BS pricing (Day 4) in a single chain.',
      solutionSteps: [
        '$F = 100 e^{0.015} = 101.51$',
        '$d_1 = \\frac{0 + (0.03 + 0.03125)(0.5)}{0.1768} = \\frac{0.0306}{0.1768} = 0.173$',
        '$Se^{-qT} - Ke^{-rT} = 99.50 - 98.02 = 1.48 = C - P$',
      ],
    },
    {
      id: 'd5-cum-02',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'ev-and-bs',
      tags: ['ev', 'bs', 'risk-neutral'],
      timeEstimateSeconds: 90,
      fromDay: 3,
      question: 'The BS call price can be written as $C = e^{-rT} E^{\\mathbb{Q}}[\\max(S_T - K, 0)]$. For an ATM call ($S = K = 100$, $r = 0$, $\\sigma = 20\\%$, $T = 1$), the BS price is $7.97. What is the risk-neutral expected payoff of this call?',
      correctAnswer: 7.97,
      tolerance: 0.01,
      unit: '$',
      explanation: 'Since $r = 0$: $E^{\\mathbb{Q}}[\\max(S_T - K, 0)] = C \\cdot e^{rT} = 7.97 \\cdot e^{0} = 7.97$. With zero rates, the expected payoff equals the price.',
      solutionSteps: [
        '$C = e^{-rT} E^{\\mathbb{Q}}[\\text{Payoff}]$',
        '$E^{\\mathbb{Q}}[\\text{Payoff}] = C \\cdot e^{rT} = 7.97 \\cdot e^{0} = 7.97$',
        'With $r = 0$, no discounting is needed. Price = expected payoff.',
      ],
    },
  ],
  flashcards: [
    { id: 'd5-f01', front: 'Replicating portfolio for a call', back: 'Long $N(d_1)$ shares + Short $Ke^{-rT}N(d_2)$ bonds. Cost = BS call price.', tags: ['bs', 'replication'] },
    { id: 'd5-f02', front: 'Why does drift $\\mu$ not appear in the BS formula?', back: 'The delta hedge eliminates directional risk. A riskless portfolio earns $r$ regardless of $\\mu$.', tags: ['bs', 'hedging'] },
    { id: 'd5-f03', front: 'Black-Scholes PDE', back: '$\\Theta + \\frac{1}{2}\\sigma^2 S^2 \\Gamma + rS\\Delta = rV$', tags: ['bs', 'pde'] },
    { id: 'd5-f04', front: 'Hedging error from discrete rebalancing', back: '$\\approx \\frac{1}{2}\\Gamma(\\Delta S)^2$ per rebalance. Higher gamma = more error.', tags: ['bs', 'hedging'] },
    { id: 'd5-f05', front: 'BS with continuous dividends: $d_1$ formula', back: '$d_1 = \\frac{\\ln(S/K) + (r - q + \\sigma^2/2)T}{\\sigma\\sqrt{T}}$', tags: ['bs', 'dividends'] },
    { id: 'd5-f06', front: 'BS with discrete dividends', back: 'Use $S^* = S - PV(D)$ in place of $S$ in the standard formula.', tags: ['bs', 'dividends'] },
    { id: 'd5-f07', front: 'Put-call parity with continuous dividends', back: '$C - P = Se^{-qT} - Ke^{-rT}$', tags: ['bs', 'put-call-parity', 'dividends'] },
    { id: 'd5-f08', front: 'Effect of higher vol on option prices', back: 'Both calls and puts increase. Options have convex payoffs, so more uncertainty benefits holders.', tags: ['bs', 'comparative-statics'] },
    { id: 'd5-f09', front: 'Most important BS assumption failure', back: 'Constant volatility. Real implied vol varies by strike (skew) and expiration (term structure).', tags: ['bs', 'assumptions'] },
    { id: 'd5-f10', front: 'Delta-hedged P&L formula', back: 'Daily P&L $\\approx \\frac{1}{2}\\Gamma S^2(\\sigma_{\\text{real}}^2 - \\sigma_{\\text{impl}}^2)\\,dt$. Profit if realized > implied (long gamma).', tags: ['bs', 'hedging', 'pnl'] },
    { id: 'd5-f11', front: 'Why do we use BS if it is wrong?', back: 'Common language (implied vol), good hedge ratios, fast computation, systematic and well-understood errors.', tags: ['bs', 'assumptions'] },
    { id: 'd5-f12', front: 'Effect of higher risk-free rate on options', back: 'Calls increase (higher forward), puts decrease. $\\rho_{\\text{call}} > 0$, $\\rho_{\\text{put}} < 0$.', tags: ['bs', 'comparative-statics'] },
  ],
  interactiveTools: ['bs-calculator', 'delta-hedging', 'payoff-diagram'],
  cheatSheet: [
    { topic: 'Replicating Portfolio', formula: 'Long N(d₁) shares, short Ke⁻ʳᵀN(d₂) bonds', description: 'Call = leveraged stock position' },
    { topic: 'BS PDE', formula: 'Θ + ½σ²S²Γ + rSΔ = rV', description: 'All European derivatives satisfy this' },
    { topic: 'Hedging Error', formula: '½Γ(ΔS)²', description: 'P&L from discrete rebalancing' },
    { topic: 'Dividend Parity', formula: 'C - P = Se⁻ᵠᵀ - Ke⁻ʳᵀ', description: 'Parity with continuous dividend yield q' },
    { topic: 'Discrete Dividend', formula: 'S* = S - PV(D)', description: 'Adjust spot by subtracting PV of dividends' },
    { topic: 'Delta-Hedged P&L', formula: '½ΓS²(σ_real² - σ_impl²)dt', description: 'Daily P&L from vol mismatch' },
  ],
  summary: [
    'A call is replicated by holding $N(d_1)$ shares and borrowing $Ke^{-rT}N(d_2)$',
    'The drift $\\mu$ drops out of BS because delta hedging eliminates directional risk',
    'Discrete hedging error $\\approx \\frac{1}{2}\\Gamma(\\Delta S)^2$; higher gamma = more error',
    'BS with dividends: replace $S$ with $Se^{-qT}$ (continuous) or $S - PV(D)$ (discrete)',
    'Delta-hedged P&L depends on $\\sigma_{\\text{realized}}^2 - \\sigma_{\\text{implied}}^2$: the core of vol trading',
  ],
  trackB: {
    title: 'Limit Order Book Microstructure',
    subtitle: 'OFI, Micro-Price & Predictive Signals',
    objectives: [
      'Understand limit order book mechanics: price-time priority, depth, and aggressor vs passive flow',
      'Compute the micro-price as a size-weighted fair value estimator',
      'Calculate Order Flow Imbalance (OFI) and interpret its predictive content',
      'Apply Kyle\'s lambda model for trade impact estimation',
      'Build predictive features from multi-level LOB data',
    ],
    theory: {
      sections: [
        {
          title: 'Limit Order Book Mechanics',
          blocks: [
            {
              type: 'text',
              body: 'The **limit order book (LOB)** is the central data structure of modern electronic markets. It records all outstanding buy and sell orders at each price level. **Market orders** cross the spread and execute immediately against resting liquidity. **Limit orders** rest in the book at a specified price and provide liquidity. Orders are matched by **price-time priority**: the best price gets filled first, and among orders at the same price, the earliest arrival is filled first.',
            },
            {
              type: 'concept',
              title: 'Aggressor vs Passive',
              body: 'The **aggressor** (or taker) sends a market order and crosses the spread, paying the bid-ask spread as a cost. The **passive** (or maker) provides liquidity via limit orders and earns the spread when filled. At Optiver, market-making profits come from repeatedly capturing the spread as a passive participant while managing inventory risk.',
            },
            {
              type: 'table',
              headers: ['Order Type', 'Execution', 'Cost', 'Role'],
              rows: [
                ['Market order', 'Immediate', 'Pays spread', 'Aggressor / taker'],
                ['Limit order', 'Rests until matched', 'Earns spread if filled', 'Passive / maker'],
                ['Cancel', 'Removes resting order', 'None', 'Adjusts exposure'],
              ],
            },
            {
              type: 'callout',
              variant: 'key-insight',
              body: 'The LOB is the actual mechanism of **price discovery**. Prices do not move because of news directly; they move because participants submit, modify, and cancel orders. Understanding LOB dynamics is essential for market-making at Optiver.',
            },
          ],
        },
        {
          title: 'Mid-Price vs Micro-Price',
          blocks: [
            {
              type: 'text',
              body: 'The **mid-price** is the simple average of the best bid and ask: $P_{\\\\text{mid}} = (P_{\\\\text{ask}} + P_{\\\\text{bid}}) / 2$. However, the mid-price ignores the relative sizes on each side. If there are 1000 shares on the bid and only 100 on the ask, the "true" fair value is likely closer to the ask (since it is easier to push the price up).',
            },
            {
              type: 'formula',
              latex: 'P_{\\text{micro}} = P_{\\text{ask}} \\cdot \\frac{V_{\\text{bid}}}{V_{\\text{bid}} + V_{\\text{ask}}} + P_{\\text{bid}} \\cdot \\frac{V_{\\text{ask}}}{V_{\\text{bid}} + V_{\\text{ask}}}',
              label: 'Stoikov Micro-Price',
              explanation: 'The micro-price weights each side by the **opposite** side\'s volume. More volume on the bid pulls the fair value toward the ask (and vice versa). When $V_{\\text{bid}} = V_{\\text{ask}}$, the micro-price equals the mid-price.',
            },
            {
              type: 'example',
              title: 'Micro-Price Calculation',
              problem: 'Best bid: $99.95 with 500 shares. Best ask: $100.05 with 200 shares. Compute the mid-price and micro-price.',
              solution: [
                '$P_{\\text{mid}} = (100.05 + 99.95)/2 = 100.00$',
                '$P_{\\text{micro}} = 100.05 \\times \\frac{500}{500 + 200} + 99.95 \\times \\frac{200}{500 + 200}$',
                '$= 100.05 \\times 0.7143 + 99.95 \\times 0.2857$',
                '$= 71.46 + 28.56 = 100.02$',
                'The micro-price is $100.02, pulled toward the ask because there is more volume on the bid (buying pressure).',
              ],
            },
            {
              type: 'callout',
              variant: 'tip',
              body: 'The micro-price is a better short-term predictor of the next trade price than the mid-price. Empirically, the micro-price reduces prediction error by 20-40% on liquid instruments.',
            },
          ],
        },
        {
          title: 'Order Flow Imbalance (OFI)',
          blocks: [
            {
              type: 'text',
              body: '**Order Flow Imbalance (OFI)** quantifies the relative buying vs selling pressure at the top of the book. The simplest version looks at the size imbalance at the best bid and ask.',
            },
            {
              type: 'formula',
              latex: 'I = \\frac{V_{\\text{bid}}}{V_{\\text{bid}} + V_{\\text{ask}}}',
              label: 'Order Flow Imbalance',
              explanation: 'OFI ranges from 0 to 1. $I > 0.5$ means more volume resting on the bid (buying pressure). $I < 0.5$ means more on the ask (selling pressure). OFI changes are strongly predictive of short-term price movements.',
            },
            {
              type: 'concept',
              title: 'OFI as a Predictive Signal',
              body: 'When OFI increases (more bid volume relative to ask), the price tends to move up in the next few seconds. The intuition: a thick bid means many buyers are willing to step in, making it hard for the price to fall. A thin ask means it takes fewer aggressive buy orders to push the price up. Multi-level OFI (aggregating the top 3-5 levels) is more robust than single-level.',
            },
            {
              type: 'callout',
              variant: 'warning',
              body: 'OFI can be manipulated via **spoofing**: placing large orders with no intent to trade, then canceling them before execution. Regulators have cracked down on this (Dodd-Frank, MiFID II), but it remains a concern. Always validate signals with actual trade data, not just resting orders.',
            },
          ],
        },
        {
          title: 'Trade Impact Models',
          blocks: [
            {
              type: 'text',
              body: 'When a large order hits the market, it moves the price. **Trade impact models** quantify how much. The simplest and most famous is Kyle\'s (1985) model, which shows that price impact is proportional to the square root of order size.',
            },
            {
              type: 'formula',
              latex: '\\Delta P = \\lambda \\cdot \\text{sign}(Q) \\cdot \\sqrt{|Q|}',
              label: 'Kyle\'s Lambda (Square-Root Impact)',
              explanation: '$\\lambda$ is the price impact coefficient (calibrated from data), $Q$ is the signed order size. The square-root relationship means that doubling your order size only increases impact by $\\sqrt{2} \\approx 1.41\\times$, not $2\\times$. This has profound implications for optimal execution.',
            },
            {
              type: 'formula',
              latex: 'S = P_{\\text{ask}} - P_{\\text{bid}}',
              label: 'Bid-Ask Spread',
              explanation: 'The spread is the fundamental cost of trading. Market makers earn the spread on round-trip trades. The spread reflects the market maker\'s costs: adverse selection (trading against informed flow), inventory risk, and operational costs.',
            },
            {
              type: 'example',
              title: 'Computing Price Impact',
              problem: 'A stock has $\\lambda = 0.05$ $/\\sqrt{\\text{shares}}$. You buy 400 shares as a market order. What is the expected price impact?',
              solution: [
                '$\\Delta P = \\lambda \\cdot \\text{sign}(Q) \\cdot \\sqrt{|Q|}$',
                '$= 0.05 \\times (+1) \\times \\sqrt{400}$',
                '$= 0.05 \\times 20 = \\$1.00$',
                'The 400-share buy order is expected to move the price up by $1.00.',
              ],
            },
            {
              type: 'concept',
              title: 'Almgren-Chriss Framework',
              body: 'The Almgren-Chriss model (2000) decomposes impact into **permanent** (information content of the trade, which does not revert) and **temporary** (liquidity displacement, which reverts). Total cost = permanent impact + temporary impact + volatility risk. This is the standard framework for optimal execution algorithms (VWAP, TWAP, etc.).',
            },
          ],
        },
        {
          title: 'Building Predictive Features',
          blocks: [
            {
              type: 'text',
              body: 'At Optiver, quantitative researchers build predictive models using LOB features. The goal is to predict the next few ticks of price movement (1-100ms horizon) to improve quote placement and hedging timing.',
            },
            {
              type: 'table',
              headers: ['Feature', 'Formula / Description', 'Predictive Content'],
              rows: [
                ['Top-level OFI', '$V_{\\text{bid}} / (V_{\\text{bid}} + V_{\\text{ask}})$', 'Short-term direction (1-10 ticks)'],
                ['Multi-level imbalance', 'Weighted OFI across top 5 levels', 'More robust directional signal'],
                ['Trade arrival intensity', 'Trades per second (exponential MA)', 'Activity regime detection'],
                ['Cancellation rate', 'Cancels / (Cancels + Fills) over window', 'Toxicity of flow'],
                ['Queue position value', 'Expected fill probability given position in queue', 'Optimal order placement'],
                ['Micro-price deviation', '$P_{\\text{micro}} - P_{\\text{mid}}$', 'Short-term fair value shift'],
              ],
            },
            {
              type: 'callout',
              variant: 'key-insight',
              body: 'The best LOB features are **lead-lag** signals: they detect when one piece of information (e.g., a large cancel on the ask) predicts a future event (e.g., the ask price moving up). At Optiver, these signals are used in real-time to adjust quotes by fractions of a tick, capturing edge on millions of trades per day.',
            },
            {
              type: 'interactive',
              tool: 'lob-order-flow',
              defaultParams: { levels: 5, tickSize: 1, updateFreqMs: 200 },
            },
          ],
        },
      ],
    },
    exercises: [
      // --- EASY (5) ---
      {
        id: 'd5b-lob-01',
        exerciseType: 'numeric',
        difficulty: 'easy',
        topic: 'micro-price',
        tags: ['lob', 'micro-price'],
        timeEstimateSeconds: 60,
        question: 'Best bid: $50.00 with 300 shares. Best ask: $50.10 with 100 shares. Compute the micro-price.',
        correctAnswer: 50.075,
        tolerance: 0.001,
        unit: '$',
        explanation: '$P_{\\text{micro}} = 50.10 \\times \\frac{300}{400} + 50.00 \\times \\frac{100}{400} = 50.10 \\times 0.75 + 50.00 \\times 0.25 = 37.575 + 12.50 = 50.075$.',
        solutionSteps: [
          '$P_{\\text{micro}} = P_{\\text{ask}} \\cdot \\frac{V_{\\text{bid}}}{V_{\\text{bid}} + V_{\\text{ask}}} + P_{\\text{bid}} \\cdot \\frac{V_{\\text{ask}}}{V_{\\text{bid}} + V_{\\text{ask}}}$',
          '$= 50.10 \\times \\frac{300}{300 + 100} + 50.00 \\times \\frac{100}{300 + 100}$',
          '$= 50.10 \\times 0.75 + 50.00 \\times 0.25$',
          '$= 37.575 + 12.50 = 50.075$',
        ],
      },
      {
        id: 'd5b-lob-02',
        exerciseType: 'numeric',
        difficulty: 'easy',
        topic: 'ofi',
        tags: ['lob', 'ofi'],
        timeEstimateSeconds: 45,
        question: 'An order book has 800 shares on the bid and 200 shares on the ask at the top level. Compute the OFI.',
        correctAnswer: 0.80,
        tolerance: 0.01,
        explanation: '$I = V_{\\text{bid}} / (V_{\\text{bid}} + V_{\\text{ask}}) = 800 / (800 + 200) = 800/1000 = 0.80$.',
        solutionSteps: [
          '$I = V_{\\text{bid}} / (V_{\\text{bid}} + V_{\\text{ask}})$',
          '$= 800 / (800 + 200) = 800/1000 = 0.80$',
          'OFI $= 0.80 > 0.5$: strong buying pressure (thick bid relative to ask).',
        ],
      },
      {
        id: 'd5b-lob-03',
        exerciseType: 'numeric',
        difficulty: 'easy',
        topic: 'spread',
        tags: ['lob', 'spread'],
        timeEstimateSeconds: 30,
        question: 'Best bid = $74.85, best ask = $74.95. What is the bid-ask spread? What is the mid-price?',
        correctAnswer: 0.10,
        tolerance: 0.001,
        unit: '$ (spread)',
        explanation: 'Spread $= P_{\\text{ask}} - P_{\\text{bid}} = 74.95 - 74.85 = \\$0.10$. Mid $= (74.95 + 74.85)/2 = \\$74.90$.',
        solutionSteps: [
          '$S = P_{\\text{ask}} - P_{\\text{bid}} = 74.95 - 74.85 = \\$0.10$',
          '$P_{\\text{mid}} = (74.95 + 74.85)/2 = \\$74.90$',
          'Spread is 10 cents, or about 0.13% of the mid-price.',
        ],
      },
      {
        id: 'd5b-lob-04',
        exerciseType: 'true-false',
        difficulty: 'easy',
        topic: 'micro-price',
        tags: ['lob', 'micro-price', 'mid-price'],
        timeEstimateSeconds: 20,
        statement: 'The micro-price equals the mid-price when the bid and ask sizes are equal.',
        correct: true,
        explanation: 'When $V_{\\text{bid}} = V_{\\text{ask}}$, the weights in the micro-price formula become $0.5$ and $0.5$: $P_{\\text{micro}} = P_{\\text{ask}} \\times 0.5 + P_{\\text{bid}} \\times 0.5 = (P_{\\text{ask}} + P_{\\text{bid}})/2 = P_{\\text{mid}}$.',
        solutionSteps: [
          'Set $V_{\\text{bid}} = V_{\\text{ask}} = V$ in the micro-price formula.',
          '$P_{\\text{micro}} = P_{\\text{ask}} \\cdot \\frac{V}{2V} + P_{\\text{bid}} \\cdot \\frac{V}{2V}$',
          '$= (P_{\\text{ask}} + P_{\\text{bid}})/2 = P_{\\text{mid}}$.',
          'Equal sizes mean neither side has more information, so micro-price = mid.',
        ],
      },
      {
        id: 'd5b-lob-05',
        exerciseType: 'numeric',
        difficulty: 'easy',
        topic: 'impact',
        tags: ['lob', 'kyle-lambda', 'impact'],
        timeEstimateSeconds: 45,
        question: 'A stock has $\\lambda = 0.02$ $/\\sqrt{\\text{shares}}$. You sell 100 shares. What is the expected price impact?',
        correctAnswer: -0.20,
        tolerance: 0.01,
        unit: '$',
        explanation: '$\\Delta P = \\lambda \\cdot \\text{sign}(Q) \\cdot \\sqrt{|Q|} = 0.02 \\times (-1) \\times \\sqrt{100} = 0.02 \\times (-1) \\times 10 = -\\$0.20$.',
        solutionSteps: [
          '$\\Delta P = \\lambda \\cdot \\text{sign}(Q) \\cdot \\sqrt{|Q|}$',
          'Selling: $\\text{sign}(Q) = -1$, $|Q| = 100$',
          '$= 0.02 \\times (-1) \\times \\sqrt{100} = -\\$0.20$',
          'The price is expected to drop $0.20 from the sell pressure.',
        ],
      },
      // --- MEDIUM (5) ---
      {
        id: 'd5b-lob-06',
        exerciseType: 'numeric',
        difficulty: 'medium',
        topic: 'impact',
        tags: ['lob', 'kyle-lambda', 'impact'],
        timeEstimateSeconds: 90,
        question: 'With $\\lambda = 0.03$ $/\\sqrt{\\text{shares}}$, compare the impact of buying 100 shares vs 900 shares. What is the ratio of the larger impact to the smaller?',
        correctAnswer: 3.0,
        tolerance: 0.01,
        explanation: 'Impact of 100 shares: $0.03 \\times \\sqrt{100} = 0.30$. Impact of 900 shares: $0.03 \\times \\sqrt{900} = 0.90$. Ratio $= 0.90/0.30 = 3.0$. Note: order size increased $9\\times$ but impact only $3\\times$ (square-root law).',
        solutionSteps: [
          'Impact(100) $= \\lambda \\sqrt{100} = 0.03 \\times 10 = \\$0.30$',
          'Impact(900) $= \\lambda \\sqrt{900} = 0.03 \\times 30 = \\$0.90$',
          'Ratio $= 0.90 / 0.30 = 3.0$',
          'Order size $\\times 9$ but impact only $\\times 3$ (since $\\sqrt{9} = 3$). This is the square-root law.',
        ],
      },
      {
        id: 'd5b-lob-07',
        exerciseType: 'multi-step',
        difficulty: 'medium',
        topic: 'vwap',
        tags: ['lob', 'vwap', 'execution'],
        timeEstimateSeconds: 180,
        question: 'You need to buy 5000 shares. The order book ask side shows: Level 1: $100.05 (1000 shares), Level 2: $100.10 (2000 shares), Level 3: $100.15 (3000 shares). (a) What is the VWAP for your 5000-share buy? (b) What is the total cost?',
        steps: [
          {
            prompt: 'Compute the VWAP (volume-weighted average price) to fill 5000 shares.',
            correctAnswer: 100.11,
            tolerance: 0.01,
            unit: '$',
            stepExplanation: 'Fill: 1000 @ $100.05, 2000 @ $100.10, 2000 @ $100.15. VWAP $= (1000 \\times 100.05 + 2000 \\times 100.10 + 2000 \\times 100.15) / 5000 = (100050 + 200200 + 200300) / 5000 = 500550/5000 = 100.11$.',
          },
          {
            prompt: 'What is the total cost to buy 5000 shares?',
            correctAnswer: 500550,
            tolerance: 5,
            unit: '$',
            stepExplanation: 'Total cost $= 1000 \\times 100.05 + 2000 \\times 100.10 + 2000 \\times 100.15 = 100050 + 200200 + 200300 = \\$500,550$.',
          },
        ],
        explanation: 'Walking the order book: you consume liquidity level by level until your order is filled. The VWAP reflects the average price paid.',
        solutionSteps: [
          'Level 1: fill 1000 shares @ $100.05. Running total: 1000 shares.',
          'Level 2: fill 2000 shares @ $100.10. Running total: 3000 shares.',
          'Level 3: need 2000 more, fill 2000 shares @ $100.15. Total: 5000 shares.',
          'VWAP $= (1000 \\times 100.05 + 2000 \\times 100.10 + 2000 \\times 100.15) / 5000$',
          '$= 500550 / 5000 = \\$100.11$',
        ],
      },
      {
        id: 'd5b-lob-08',
        exerciseType: 'numeric',
        difficulty: 'medium',
        topic: 'micro-price',
        tags: ['lob', 'micro-price', 'multi-level'],
        timeEstimateSeconds: 90,
        question: 'An order book shows: Bid $99.90 (400 shares), Ask $100.10 (600 shares). Compute the micro-price and the difference from mid-price.',
        correctAnswer: 99.98,
        tolerance: 0.005,
        unit: '$ (micro-price)',
        explanation: '$P_{\\text{mid}} = (100.10 + 99.90)/2 = 100.00$. $P_{\\text{micro}} = 100.10 \\times 400/1000 + 99.90 \\times 600/1000 = 40.04 + 59.94 = 99.98$. Deviation from mid $= -0.02$ (pulled toward bid because ask is thicker).',
        solutionSteps: [
          '$P_{\\text{mid}} = (100.10 + 99.90)/2 = 100.00$',
          '$P_{\\text{micro}} = 100.10 \\times \\frac{400}{1000} + 99.90 \\times \\frac{600}{1000}$',
          '$= 40.04 + 59.94 = 99.98$',
          'The micro-price is below mid because the ask has more volume (selling pressure).',
          'Deviation $= 99.98 - 100.00 = -0.02$.',
        ],
      },
      {
        id: 'd5b-lob-09',
        exerciseType: 'multiple-choice',
        difficulty: 'medium',
        topic: 'ofi',
        tags: ['lob', 'ofi', 'prediction'],
        timeEstimateSeconds: 45,
        question: 'The OFI at the top of book shifts from 0.50 to 0.75 over 100ms. What is the most likely short-term price movement?',
        options: [
          'Price moves down (more selling pressure)',
          'Price moves up (more buying pressure)',
          'Price stays unchanged (OFI is not predictive)',
          'Cannot determine without knowing trade arrival rate',
        ],
        correctIndex: 1,
        explanation: 'OFI increasing from 0.50 to 0.75 means the bid side has grown relative to the ask. More bid volume means buying pressure has intensified, which predicts a short-term price increase.',
        solutionSteps: [
          'OFI $= V_{\\text{bid}} / (V_{\\text{bid}} + V_{\\text{ask}})$ increased to 0.75.',
          'This means the bid is now 3x the ask size.',
          'Thick bid + thin ask = easy for price to move up, hard to move down.',
          'Empirically, OFI increases strongly predict short-term upward price moves.',
        ],
      },
      {
        id: 'd5b-lob-10',
        exerciseType: 'numeric',
        difficulty: 'medium',
        topic: 'impact',
        tags: ['lob', 'kyle-lambda', 'execution'],
        timeEstimateSeconds: 90,
        question: 'You want to buy 1600 shares with $\\lambda = 0.025$. If you split the order into 4 child orders of 400 shares each (assuming independent impact), what is the total impact cost? Compare to executing all 1600 at once.',
        correctAnswer: 2.0,
        tolerance: 0.05,
        unit: '$ (split execution total impact)',
        explanation: 'Single execution: $0.025 \\times \\sqrt{1600} = 0.025 \\times 40 = \\$1.00$. Split into 4x400: each impact $= 0.025 \\times \\sqrt{400} = 0.025 \\times 20 = \\$0.50$. Total $= 4 \\times 0.50 = \\$2.00$. The split execution has higher total impact! (This is because $4\\sqrt{400} = 80 > \\sqrt{1600} = 40$). However, in practice the permanent component may be the same; the advantage of splitting is reduced temporary impact.',
        solutionSteps: [
          'Single order: $\\Delta P = 0.025 \\times \\sqrt{1600} = 0.025 \\times 40 = \\$1.00$',
          'Split 4x400: each $\\Delta P = 0.025 \\times \\sqrt{400} = 0.025 \\times 20 = \\$0.50$',
          'Total split impact (naive sum) $= 4 \\times 0.50 = \\$2.00$',
          'Note: $4\\sqrt{n/4} = 4 \\times \\sqrt{n}/2 = 2\\sqrt{n} > \\sqrt{n}$',
          'Splitting is beneficial only when temporary impact reverts between child orders.',
        ],
      },
      // --- HARD (4) ---
      {
        id: 'd5b-lob-11',
        exerciseType: 'multi-step',
        difficulty: 'hard',
        topic: 'ofi-prediction',
        tags: ['lob', 'ofi', 'prediction', 'time-series'],
        timeEstimateSeconds: 240,
        question: 'You observe 5 consecutive LOB snapshots (100ms apart). Bid/Ask sizes: (500,500), (600,400), (700,300), (650,350), (800,200). (a) Compute the OFI series. (b) Compute the OFI change from snapshot 1 to 5. (c) If the empirical model is $\\Delta P_{\\text{next}} = 0.02 \\times (I_t - 0.5)$ per tick, predict the next price change from the final snapshot.',
        steps: [
          {
            prompt: 'Compute OFI for the 5th snapshot.',
            correctAnswer: 0.80,
            tolerance: 0.01,
            stepExplanation: '$I_5 = 800 / (800 + 200) = 0.80$.',
          },
          {
            prompt: 'What is the OFI change from snapshot 1 to 5?',
            correctAnswer: 0.30,
            tolerance: 0.01,
            stepExplanation: '$I_1 = 500/1000 = 0.50$. $I_5 = 0.80$. Change $= 0.80 - 0.50 = 0.30$.',
          },
          {
            prompt: 'Using $\\Delta P = 0.02 \\times (I_t - 0.5)$, predict the next price change (in ticks) from the final OFI.',
            correctAnswer: 0.006,
            tolerance: 0.001,
            unit: '$ per tick',
            stepExplanation: '$\\Delta P = 0.02 \\times (0.80 - 0.5) = 0.02 \\times 0.30 = 0.006$ (positive: price expected to rise).',
          },
        ],
        explanation: 'This exercise demonstrates building a simple linear OFI-to-price model. In practice, models use multiple levels and non-linear transformations.',
        solutionSteps: [
          'OFI series: $I_1 = 0.50$, $I_2 = 0.60$, $I_3 = 0.70$, $I_4 = 0.65$, $I_5 = 0.80$',
          'OFI is trending upward: buying pressure increasing.',
          '$\\Delta I = 0.80 - 0.50 = 0.30$ over 400ms.',
          'Predicted price change $= 0.02 \\times (0.80 - 0.50) = 0.006$ per tick.',
          'Positive prediction: the model expects price to move up.',
        ],
      },
      {
        id: 'd5b-lob-12',
        exerciseType: 'scenario',
        difficulty: 'hard',
        topic: 'execution',
        tags: ['lob', 'execution', 'impact', 'vwap'],
        timeEstimateSeconds: 200,
        question: 'You need to execute a 10,000-share buy on a stock with $\\lambda = 0.01$, spread = $0.05, and average daily volume = 1,000,000 shares. Analyze the execution under different strategies.',
        scenarios: [
          {
            description: 'Execute all at once (single market order)',
            shocks: [{ variable: 'order_size', change: 10000 }],
            expectedAnswer: 1.0,
            tolerance: 0.1,
            unit: '$ impact',
          },
          {
            description: 'Split into 10 child orders of 1000 (assuming full reversion between)',
            shocks: [{ variable: 'order_size', change: 1000 }],
            expectedAnswer: 0.316,
            tolerance: 0.05,
            unit: '$ impact per child',
          },
          {
            description: 'Participation rate: what % of daily volume is the total order?',
            shocks: [{ variable: 'participation', change: 1 }],
            expectedAnswer: 1.0,
            tolerance: 0.1,
            unit: '%',
          },
        ],
        explanation: 'Execution analysis combines impact modeling with practical constraints (spread, daily volume, urgency).',
        solutionSteps: [
          'Single execution: $\\Delta P = 0.01 \\times \\sqrt{10000} = 0.01 \\times 100 = \\$1.00$',
          'Split 10x1000: each impact $= 0.01 \\times \\sqrt{1000} = 0.01 \\times 31.6 = \\$0.316$',
          'If impact fully reverts between children, total cost is just per-child cost.',
          'Participation $= 10000 / 1000000 = 1.0\\%$ of daily volume.',
          'At 1% participation, this is a modest order that can be spread over the day.',
        ],
      },
      {
        id: 'd5b-lob-13',
        exerciseType: 'free-response',
        difficulty: 'hard',
        topic: 'features',
        tags: ['lob', 'features', 'prediction', 'ml'],
        timeEstimateSeconds: 180,
        question: 'You observe that the cancellation rate on the ask side has spiked to 90% (9 out of 10 placed ask orders are cancelled within 50ms). The OFI is 0.45. What might be happening, and what does this signal about future price movement?',
        modelAnswer: 'High cancellation rate on the ask side suggests the ask liquidity is "flickering" or being pulled. This is often a sign that ask-side participants have received information that the price may drop, or that they are spoofing. Despite the OFI of 0.45 suggesting mild selling pressure, the high cancel rate contradicts this: the resting ask orders are not genuine. The true available liquidity on the ask is lower than it appears. Prediction: the price is more likely to move DOWN. The ask-side participants may be informed sellers who briefly show liquidity then pull it. Alternatively, a large seller may be about to sweep the bid. This demonstrates why cancellation features add information beyond simple OFI. At Optiver, the ratio of cancels to fills (the "toxicity" metric) is a key input to quote adjustment models.',
        explanation: 'High cancellation rates indicate that resting liquidity is not genuine, often signaling informed trading or manipulation.',
        solutionSteps: [
          'Cancellation rate 90% on ask = ask liquidity is being pulled rapidly.',
          'OFI = 0.45 suggests mild selling pressure, but ask cancel rate contradicts.',
          'True ask depth is much thinner than displayed.',
          'This pattern often precedes a price drop (informed selling or bid sweep).',
          'Cancellation rate is a "toxicity" feature that adds predictive power beyond OFI.',
        ],
      },
      {
        id: 'd5b-lob-14',
        exerciseType: 'multi-step',
        difficulty: 'hard',
        topic: 'micro-price',
        tags: ['lob', 'micro-price', 'multi-level'],
        timeEstimateSeconds: 180,
        question: 'A 3-level order book: Bid: $99.90 (200), $99.80 (500), $99.70 (800). Ask: $100.10 (100), $100.20 (300), $100.30 (600). (a) Compute top-level micro-price. (b) Compute a volume-weighted micro-price using all 3 levels (weight by inverse distance from mid). Mid = $100.00.',
        steps: [
          {
            prompt: 'Top-level micro-price (using only level 1 bid/ask)?',
            correctAnswer: 100.033,
            tolerance: 0.005,
            unit: '$',
            stepExplanation: '$P_{\\text{micro}} = 100.10 \\times 200/300 + 99.90 \\times 100/300 = 66.733 + 33.30 = 100.033$.',
          },
          {
            prompt: 'Total bid volume across 3 levels?',
            correctAnswer: 1500,
            tolerance: 1,
            unit: 'shares',
            stepExplanation: 'Total bid $= 200 + 500 + 800 = 1500$ shares.',
          },
          {
            prompt: 'Total ask volume across 3 levels?',
            correctAnswer: 1000,
            tolerance: 1,
            unit: 'shares',
            stepExplanation: 'Total ask $= 100 + 300 + 600 = 1000$ shares.',
          },
        ],
        explanation: 'Multi-level analysis reveals that the bid has 50% more volume than the ask across 3 levels, suggesting buying pressure even if the top level alone tells a weaker story.',
        solutionSteps: [
          'Top-level: $P_{\\text{micro}} = 100.10 \\times (200/300) + 99.90 \\times (100/300) = 66.733 + 33.30 = 100.033$',
          'Total bid volume: $200 + 500 + 800 = 1500$',
          'Total ask volume: $100 + 300 + 600 = 1000$',
          'Multi-level OFI: $1500/(1500+1000) = 0.60$ (buying pressure confirmed).',
        ],
      },
      // --- INTERVIEW (3) ---
      {
        id: 'd5b-lob-15',
        exerciseType: 'free-response',
        difficulty: 'interview',
        topic: 'features',
        tags: ['lob', 'features', 'interview', 'prediction'],
        timeEstimateSeconds: 180,
        question: 'Interview: "Design features from LOB data to predict the next 100ms mid-price change. What pitfalls exist?"',
        modelAnswer: 'Features I would build: (1) Multi-level OFI: volume imbalance across top 5 levels, weighted by inverse distance. (2) Micro-price deviation from mid: $P_{\\text{micro}} - P_{\\text{mid}}$ signals short-term direction. (3) Trade imbalance: signed volume of recent trades (1s window). Buy-initiated vs sell-initiated trades using the Lee-Ready algorithm. (4) Cancellation asymmetry: if bid cancels > ask cancels, suggests informed selling. (5) Queue dynamics: rate of change of top-level size (is the bid growing or shrinking?). (6) Spread changes: widening spread often precedes volatility. Pitfalls: (a) Lookahead bias: using information that would not be available at prediction time. (b) Spoofing: large resting orders may be fake, poisoning OFI signals. (c) Overfitting: LOB data is very high-frequency and noisy. (d) Latency: in production, your features must be computable within microseconds. (e) Regime changes: features that work in quiet markets may fail during news events. (f) Cross-asset signals: ignoring correlated instruments loses predictive power.',
        explanation: 'LOB feature engineering requires combining depth, flow, and trade data while avoiding lookahead bias and overfitting.',
        solutionSteps: [
          'Key features: multi-level OFI, micro-price deviation, trade imbalance, cancel asymmetry, queue dynamics.',
          'Pitfall 1: Lookahead bias (must respect time ordering).',
          'Pitfall 2: Spoofing corrupts size-based signals.',
          'Pitfall 3: Overfitting on noisy tick data.',
          'Pitfall 4: Latency constraints in production.',
          'Pitfall 5: Regime dependence (features work differently in calm vs volatile markets).',
        ],
      },
      {
        id: 'd5b-lob-16',
        exerciseType: 'free-response',
        difficulty: 'interview',
        topic: 'micro-price',
        tags: ['lob', 'micro-price', 'interview'],
        timeEstimateSeconds: 120,
        question: 'Why does the micro-price outperform the mid-price as a fair value estimator? When might the micro-price fail?',
        modelAnswer: 'The micro-price outperforms the mid because it incorporates **size information**. The mid treats both sides equally, but if one side has much more resting volume, the "true" fair value is closer to the thin side (since it takes less aggressive flow to move price through thin liquidity). Empirically, the micro-price reduces mean-squared prediction error for the next trade price by 20-40%. Failures: (1) When sizes are not informative (e.g., spoofed or flickering quotes). (2) When the tick size is large relative to the "true" spread (constrained books where sizes reflect queue priority races, not information). (3) In very fast markets where the book state changes before you can act on it. (4) When hidden orders (iceberg/dark pool) mean the displayed size understates true liquidity.',
        explanation: 'The micro-price adds size information to the fair value estimate but can fail when displayed sizes are not genuine.',
        solutionSteps: [
          'Mid-price ignores sizes. Micro-price weights by opposite-side volume.',
          'Better predictor because size reveals where the "path of least resistance" is.',
          'Empirical improvement: 20-40% reduction in MSE for next-trade prediction.',
          'Failures: spoofing, large tick sizes, iceberg orders, latency.',
        ],
      },
      {
        id: 'd5b-lob-17',
        exerciseType: 'scenario',
        difficulty: 'interview',
        topic: 'market-making',
        tags: ['lob', 'market-making', 'interview'],
        timeEstimateSeconds: 200,
        question: 'You are a market maker quoting a stock with mid $100.00, spread $0.10. You observe the following signals. Analyze how you would adjust your quotes in each scenario.',
        scenarios: [
          {
            description: 'OFI jumps from 0.50 to 0.80 (large buy imbalance)',
            shocks: [{ variable: 'ofi', change: 30 }],
            expectedAnswer: 0.03,
            tolerance: 0.02,
            unit: '$ (shift quotes up by)',
          },
          {
            description: 'A correlated ETF drops 0.5% (cross-asset signal)',
            shocks: [{ variable: 'correlated_asset', change: -50 }],
            expectedAnswer: -0.50,
            tolerance: 0.1,
            unit: '$ (expected stock move)',
          },
          {
            description: 'Trade flow becomes 80% sell-initiated (toxic flow)',
            shocks: [{ variable: 'toxicity', change: 80 }],
            expectedAnswer: 0.15,
            tolerance: 0.05,
            unit: '$ (widen spread to)',
          },
        ],
        explanation: 'Market makers continuously adjust quotes based on LOB signals, cross-asset information, and flow toxicity.',
        solutionSteps: [
          'OFI jump to 0.80: strong buy pressure. Shift both quotes up by ~$0.03 (micro-price moved).',
          'Correlated ETF down 0.5%: if beta = 1, expect stock to fall ~$0.50. Move quotes down immediately.',
          'Toxic flow (80% sells): widen spread from $0.10 to ~$0.15 to protect against adverse selection.',
          'In all cases, the market maker adjusts BEFORE the price moves to avoid being picked off.',
        ],
      },
      {
        id: 'd5b-lob-18',
        exerciseType: 'speed-drill',
        difficulty: 'interview',
        topic: 'lob-mental-math',
        tags: ['lob', 'mental-math', 'interview'],
        timeEstimateSeconds: 90,
        timeLimitSeconds: 90,
        problems: [
          { prompt: 'Bid 200 shares, Ask 800 shares. OFI?', correctAnswer: 0.20, tolerance: 0.01 },
          { prompt: 'Micro-price: ask=$50.02, bid=$49.98, V_bid=750, V_ask=250. Result?', correctAnswer: 50.01, tolerance: 0.005 },
          { prompt: 'Lambda=0.04, buy 625 shares. Impact?', correctAnswer: 1.0, tolerance: 0.05 },
          { prompt: 'Spread=$0.10, mid=$75.00. Ask price?', correctAnswer: 75.05, tolerance: 0.001 },
          { prompt: 'OFI was 0.60, now 0.40. Direction of price prediction?', correctAnswer: -1, tolerance: 0.1 },
        ],
        explanation: 'Quick LOB calculations that a market maker performs continuously.',
        solutionSteps: [
          'OFI: $200/(200+800) = 0.20$',
          'Micro: $50.02 \\times 750/1000 + 49.98 \\times 250/1000 = 37.515 + 12.495 = 50.01$',
          'Impact: $0.04 \\times \\sqrt{625} = 0.04 \\times 25 = 1.0$',
          'Ask $= \\text{mid} + \\text{spread}/2 = 75.00 + 0.05 = 75.05$',
          'OFI decreased (0.60 to 0.40): less buying pressure, predict price DOWN ($-1$).',
        ],
      },
    ],
    flashcards: [
      { id: 'd5b-f01', front: 'Mid-price formula', back: '$P_{\\text{mid}} = (P_{\\text{ask}} + P_{\\text{bid}}) / 2$. Simple average, ignores size.', tags: ['lob', 'mid-price'] },
      { id: 'd5b-f02', front: 'Micro-price (Stoikov)', back: '$P_{\\text{micro}} = P_{\\text{ask}} \\cdot V_{\\text{bid}}/(V_{\\text{bid}}+V_{\\text{ask}}) + P_{\\text{bid}} \\cdot V_{\\text{ask}}/(V_{\\text{bid}}+V_{\\text{ask}})$. Size-weighted fair value.', tags: ['lob', 'micro-price'] },
      { id: 'd5b-f03', front: 'Order Flow Imbalance (OFI)', back: '$I = V_{\\text{bid}}/(V_{\\text{bid}}+V_{\\text{ask}})$. Ranges [0,1]. $>0.5$ = buying pressure.', tags: ['lob', 'ofi'] },
      { id: 'd5b-f04', front: 'Kyle\'s Lambda (square-root impact)', back: '$\\Delta P = \\lambda \\cdot \\text{sign}(Q) \\cdot \\sqrt{|Q|}$. Impact is concave in order size.', tags: ['lob', 'impact'] },
      { id: 'd5b-f05', front: 'Bid-ask spread', back: '$S = P_{\\text{ask}} - P_{\\text{bid}}$. Cost of immediacy; market maker\'s gross revenue.', tags: ['lob', 'spread'] },
      { id: 'd5b-f06', front: 'Price-time priority', back: 'Best price fills first. Among same price, earliest order fills first. Foundation of LOB matching.', tags: ['lob', 'mechanics'] },
      { id: 'd5b-f07', front: 'Aggressor vs Passive', back: 'Aggressor: market order, crosses spread, pays cost. Passive: limit order, earns spread if filled.', tags: ['lob', 'mechanics'] },
      { id: 'd5b-f08', front: 'When does micro-price = mid?', back: 'When $V_{\\text{bid}} = V_{\\text{ask}}$ (equal sizes on both sides). The size weights become 0.5 each.', tags: ['lob', 'micro-price'] },
      { id: 'd5b-f09', front: 'Almgren-Chriss decomposition', back: 'Total impact = permanent (information) + temporary (liquidity). Permanent does not revert; temporary does.', tags: ['lob', 'impact', 'execution'] },
      { id: 'd5b-f10', front: 'Why square-root impact?', back: '$\\sqrt{Q}$ means doubling order size increases impact by $\\sqrt{2} \\approx 1.41\\times$, not $2\\times$. Concavity reflects liquidity depth.', tags: ['lob', 'impact'] },
      { id: 'd5b-f11', front: 'Cancellation rate as a feature', back: 'High cancel rate = liquidity is flickering/fake. Signals spoofing or informed trading. Add to models alongside OFI.', tags: ['lob', 'features'] },
      { id: 'd5b-f12', front: 'VWAP execution', back: 'Volume-Weighted Average Price: fill by walking the book level by level. Total cost depends on available depth.', tags: ['lob', 'execution'] },
    ],
    cheatSheet: [
      { topic: 'Mid-Price', formula: 'P_mid = (P_ask + P_bid) / 2', description: 'Simple average of best bid and ask' },
      { topic: 'Micro-Price', formula: 'P_micro = P_ask·V_bid/(V_bid+V_ask) + P_bid·V_ask/(V_bid+V_ask)', description: 'Size-weighted fair value (Stoikov)' },
      { topic: 'Order Flow Imbalance', formula: 'I = V_bid / (V_bid + V_ask)', description: 'Ranges [0,1]; >0.5 = buying pressure' },
      { topic: 'Kyle\'s Impact', formula: 'ΔP = λ · sign(Q) · √|Q|', description: 'Square-root price impact model' },
      { topic: 'Bid-Ask Spread', formula: 'S = P_ask - P_bid', description: 'Cost of immediacy; MM gross revenue' },
      { topic: 'Micro = Mid condition', formula: 'V_bid = V_ask', description: 'Equal sizes make micro-price = mid-price' },
      { topic: 'Impact Ratio (split)', formula: 'n·√(Q/n) = √n · √Q > √Q for n>1', description: 'Naive splitting increases total impact' },
      { topic: 'VWAP', formula: 'Σ(P_i · Q_i) / Σ Q_i', description: 'Volume-weighted average execution price' },
    ],
    summary: [
      'The LOB records all resting buy/sell orders. Price-time priority determines fill order.',
      'Micro-price $= P_{\\text{ask}} \\cdot V_{\\text{bid}}/(V_{\\text{bid}}+V_{\\text{ask}}) + P_{\\text{bid}} \\cdot V_{\\text{ask}}/(V_{\\text{bid}}+V_{\\text{ask}})$ is a better fair value than mid.',
      'OFI $= V_{\\text{bid}}/(V_{\\text{bid}}+V_{\\text{ask}})$ predicts short-term price direction.',
      'Kyle\'s lambda: $\\Delta P = \\lambda \\cdot \\text{sign}(Q) \\cdot \\sqrt{|Q|}$ (square-root impact).',
      'Key LOB features: multi-level OFI, trade imbalance, cancellation rate, queue dynamics.',
      'Market makers adjust quotes in real-time based on OFI, cross-asset signals, and flow toxicity.',
    ],
    interactiveTools: ['lob-order-flow'],
  },
};

export default day05;
