import { DayContent } from './types';

const day03: DayContent = {
  dayNumber: 3,
  title: 'Expected Value & Discrete Payoffs',
  subtitle: 'Natenberg Chapter 3',
  week: 1,
  chapters: ['Chapter 3'],
  estimatedMinutes: 100,
  prerequisites: [1, 2],
  objectives: [
    'Compute expected values under discrete probability distributions',
    'Price simple dice and coin games using EV calculations',
    'Apply backward induction to multi-stage optimal stopping problems',
    'Calculate expected payoffs of options on discrete underlyings (e.g., dice)',
    'Connect risk-neutral pricing to EV under the risk-neutral measure',
  ],
  theory: {
    sections: [
      {
        title: 'Expected Value Fundamentals',
        blocks: [
          {
            type: 'text',
            body: 'Expected value (EV) is the probability-weighted average of all possible outcomes. It is the single most important concept in quantitative trading. Every decision a market maker makes boils down to: "What is the expected value of this trade?" If you can compute EV faster and more accurately than the competition, you have an edge.',
          },
          {
            type: 'formula',
            latex: 'E[X] = \\sum_{i=1}^{n} x_i \\cdot p_i',
            label: 'Expected Value (Discrete)',
            explanation: 'Sum each outcome $x_i$ multiplied by its probability $p_i$. The probabilities must sum to 1.',
          },
          {
            type: 'example',
            title: 'EV of a Fair Die Roll',
            problem: 'What is the expected value of a single roll of a fair 6-sided die?',
            solution: [
              '$E[X] = \\frac{1}{6}(1 + 2 + 3 + 4 + 5 + 6) = \\frac{21}{6} = 3.5$',
              'Each outcome has probability $1/6$.',
              'The EV of 3.5 is not itself a possible outcome, but represents the long-run average.',
            ],
          },
          {
            type: 'callout',
            variant: 'key-insight',
            body: 'In trading, you never see a "fair" game in the wild. Your job is to find edges: situations where the EV of your position is positive after accounting for transaction costs and risk. A market maker might earn $0.01 in EV per trade, but do it millions of times.',
          },
        ],
      },
      {
        title: 'Properties of Expected Value',
        blocks: [
          {
            type: 'text',
            body: 'Expected value has powerful linearity properties that make complex problems tractable. Linearity holds even when the random variables are dependent, which is remarkable and incredibly useful.',
          },
          {
            type: 'formula',
            latex: 'E[aX + bY] = a \\cdot E[X] + b \\cdot E[Y]',
            label: 'Linearity of Expectation',
            explanation: 'The expectation of a linear combination equals the linear combination of expectations. This holds for ANY random variables, independent or not.',
          },
          {
            type: 'formula',
            latex: 'E[\\max(X - K, 0)] = \\sum_{x_i > K} (x_i - K) \\cdot p_i',
            label: 'Expected Payoff of a Call on a Discrete Variable',
            explanation: 'This is the EV of a call option with strike $K$ on a discrete random variable. Only outcomes above the strike contribute.',
          },
          {
            type: 'example',
            title: 'Call Option on a Die Roll',
            problem: 'You roll a fair die. Your payoff is $\\max(\\text{roll} - 3.5, 0)$. What is the expected payoff?',
            solution: [
              'Outcomes above the strike of 3.5: rolls of 4, 5, 6.',
              '$E[\\text{payoff}] = \\frac{1}{6}[(4 - 3.5) + (5 - 3.5) + (6 - 3.5)]$',
              '$= \\frac{1}{6}[0.5 + 1.5 + 2.5] = \\frac{4.5}{6} = 0.75$',
            ],
          },
          {
            type: 'callout',
            variant: 'tip',
            body: 'The "put" on a die roll with the same strike has EV $= \\frac{1}{6}[(3.5-1) + (3.5-2) + (3.5-3)] = \\frac{1}{6}(2.5+1.5+0.5) = 0.75$. By put-call parity on a die: $C - P = E[X] - K = 3.5 - 3.5 = 0$, confirming $C = P$.',
          },
        ],
      },
      {
        title: 'Conditional Expectation & Multi-Stage Games',
        blocks: [
          {
            type: 'text',
            body: 'Many interview problems and real trading situations involve **sequential decisions**. The key technique is **backward induction**: start from the final stage, compute the EV at each decision point, and work backwards to the first stage. At each stage, the optimal decision is the one that maximizes expected value.',
          },
          {
            type: 'formula',
            latex: 'E[X] = \\sum_j E[X \\mid A_j] \\cdot P(A_j)',
            label: 'Law of Total Expectation',
            explanation: 'The unconditional expectation equals the probability-weighted average of conditional expectations. This is the mathematical foundation of backward induction.',
          },
          {
            type: 'example',
            title: 'Optimal Stopping: Two Rolls',
            problem: 'You roll a fair die. After seeing the result, you can either keep it or re-roll once. If you re-roll, you must keep the second result. What is the optimal strategy and expected value?',
            solution: [
              'Work backwards. If you re-roll, the expected value of the second roll is $3.5$.',
              'So you should keep the first roll if it exceeds $3.5$ (i.e., if you roll 4, 5, or 6) and re-roll otherwise.',
              '$E[\\text{game}] = \\frac{1}{6}(3.5 + 3.5 + 3.5 + 4 + 5 + 6) = \\frac{25.5}{6} = 4.25$',
              'The option to re-roll is worth $4.25 - 3.50 = 0.75$ above the single-roll EV.',
            ],
          },
          {
            type: 'example',
            title: 'Optimal Stopping: Three Rolls',
            problem: 'Same game, but now you get up to 3 rolls. What is the EV?',
            solution: [
              'We already know the 2-roll game has EV $= 4.25$.',
              'On the first roll, keep it if it exceeds 4.25 (i.e., roll 5 or 6), otherwise use your remaining 2 rolls.',
              '$E[\\text{3-roll}] = \\frac{1}{6}(4.25 + 4.25 + 4.25 + 4.25 + 5 + 6) = \\frac{28.0}{6} \\approx 4.667$',
              'Each additional roll adds less value: 3.50 $\\to$ 4.25 $\\to$ 4.667 (diminishing marginal value of the option).',
            ],
          },
          {
            type: 'callout',
            variant: 'key-insight',
            body: 'The optimal stopping problem is essentially an American option pricing problem. The "option" to re-roll is like the right to exercise later. Backward induction is the discrete-time version of the technique used in binomial option pricing trees.',
          },
        ],
      },
      {
        title: 'Risk-Neutral Pricing & Fair Games',
        blocks: [
          {
            type: 'text',
            body: 'In options pricing, we compute expected values under the **risk-neutral measure**, not the real-world measure. Under risk-neutral pricing, all assets earn the risk-free rate in expectation. The price of any derivative is the discounted expected payoff under this measure.',
          },
          {
            type: 'formula',
            latex: 'V_0 = e^{-rT} \\cdot E^{\\mathbb{Q}}[\\text{Payoff}]',
            label: 'Risk-Neutral Pricing Formula',
            explanation: 'The value today equals the discounted expected payoff under the risk-neutral probability measure $\\mathbb{Q}$. This is the foundation of all option pricing.',
          },
          {
            type: 'concept',
            title: 'Why Risk-Neutral Pricing Works',
            body: 'We do not need to know investors\' risk preferences. By the no-arbitrage principle, we can construct a replicating portfolio that matches the derivative\'s payoff in every state. The cost of that portfolio is the fair price. It turns out this is mathematically equivalent to computing the expected payoff under a special probability measure where the underlying grows at the risk-free rate.',
          },
          {
            type: 'example',
            title: 'Risk-Neutral Pricing of a Simple Bet',
            problem: 'A stock is at $100. In one period it goes to $110 (up) or $90 (down). Risk-free rate is 5% per period. Price a call with strike $100.',
            solution: [
              'Find risk-neutral probability $q$: $100 \\cdot e^{0.05} = q \\cdot 110 + (1-q) \\cdot 90$',
              '$105.127 = 110q + 90(1-q) = 20q + 90$',
              '$q = (105.127 - 90)/20 = 0.7564$',
              'Call payoffs: Up $= \\max(110-100,0) = 10$, Down $= \\max(90-100,0) = 0$.',
              '$C = e^{-0.05}[0.7564 \\times 10 + 0.2436 \\times 0] = 0.9512 \\times 7.564 = 7.19$',
            ],
          },
        ],
      },
    ],
  },
  exercises: [
    // --- EASY (5) ---
    {
      id: 'd3-ev-01',
      exerciseType: 'numeric',
      difficulty: 'easy',
      topic: 'expected-value',
      tags: ['ev', 'dice'],
      timeEstimateSeconds: 30,
      question: 'What is the expected value of the sum of two fair 6-sided dice?',
      correctAnswer: 7,
      tolerance: 0.01,
      explanation: 'By linearity: $E[D_1 + D_2] = E[D_1] + E[D_2] = 3.5 + 3.5 = 7$.',
      solutionSteps: [
        'By linearity of expectation: $E[D_1 + D_2] = E[D_1] + E[D_2]$',
        '$= 3.5 + 3.5 = 7$',
        'No need to enumerate all 36 outcomes — linearity makes this trivial.',
      ],
    },
    {
      id: 'd3-ev-02',
      exerciseType: 'numeric',
      difficulty: 'easy',
      topic: 'expected-value',
      tags: ['ev', 'dice'],
      timeEstimateSeconds: 45,
      question: 'You roll a fair die. Your payoff is $\\max(\\text{roll} - 4, 0)$. What is the expected payoff?',
      correctAnswer: 0.50,
      tolerance: 0.01,
      explanation: '$E = \\frac{1}{6}[0+0+0+0+1+2] = \\frac{3}{6} = 0.50$',
      solutionSteps: [
        'Only rolls of 5 and 6 produce positive payoffs.',
        'Roll 5: payoff $= 5 - 4 = 1$',
        'Roll 6: payoff $= 6 - 4 = 2$',
        '$E = \\frac{1}{6}(0+0+0+0+1+2) = \\frac{3}{6} = 0.50$',
      ],
    },
    {
      id: 'd3-ev-03',
      exerciseType: 'multiple-choice',
      difficulty: 'easy',
      topic: 'expected-value',
      tags: ['ev', 'linearity'],
      timeEstimateSeconds: 30,
      question: 'Which property of expected value holds even when random variables are dependent?',
      options: [
        '$E[XY] = E[X] \\cdot E[Y]$',
        '$E[X + Y] = E[X] + E[Y]$',
        '$\\text{Var}(X + Y) = \\text{Var}(X) + \\text{Var}(Y)$',
        '$E[\\max(X,Y)] = \\max(E[X], E[Y])$',
      ],
      correctIndex: 1,
      explanation: 'Linearity of expectation ($E[X+Y] = E[X] + E[Y]$) holds for ALL random variables, independent or dependent. The other three require independence or special conditions.',
      solutionSteps: [
        '$E[XY] = E[X]E[Y]$ requires independence.',
        '$E[X+Y] = E[X]+E[Y]$ is always true (linearity).',
        '$\\text{Var}(X+Y) = \\text{Var}(X)+\\text{Var}(Y)$ requires uncorrelated variables.',
        '$E[\\max(X,Y)] \\neq \\max(E[X],E[Y])$ in general (Jensen\'s inequality direction).',
      ],
    },
    {
      id: 'd3-ev-04',
      exerciseType: 'true-false',
      difficulty: 'easy',
      topic: 'expected-value',
      tags: ['ev'],
      timeEstimateSeconds: 20,
      statement: 'A game with positive expected value is always profitable to play.',
      correct: false,
      explanation: 'A positive EV game is profitable in expectation over many plays, but any single play can result in a loss. Risk of ruin matters: if you bet your entire bankroll on a +EV game with high variance, you can still go broke.',
      solutionSteps: [
        'Positive EV means profitable on average over many repetitions.',
        'A single play can still lose money.',
        'Variance and risk of ruin matter for finite bankrolls.',
        'Example: a game that pays $1M with 1% probability and loses $100 otherwise has positive EV but is risky for a single play.',
      ],
    },
    {
      id: 'd3-ev-05',
      exerciseType: 'numeric',
      difficulty: 'easy',
      topic: 'expected-value',
      tags: ['ev', 'coins'],
      timeEstimateSeconds: 30,
      question: 'A fair coin is flipped. Heads pays $10, tails pays $4. What is the expected payoff?',
      correctAnswer: 7,
      tolerance: 0.01,
      unit: '$',
      explanation: '$E = 0.5 \\times 10 + 0.5 \\times 4 = 5 + 2 = 7$',
      solutionSteps: [
        '$E = P(H) \\times \\text{Payoff}(H) + P(T) \\times \\text{Payoff}(T)$',
        '$= 0.5 \\times 10 + 0.5 \\times 4 = 7$',
      ],
    },
    // --- MEDIUM (6) ---
    {
      id: 'd3-ev-06',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'optimal-stopping',
      tags: ['ev', 'dice', 'optimal-stopping'],
      timeEstimateSeconds: 120,
      question: 'You roll a fair die up to 2 times. After each roll, you can stop and collect that amount (in dollars), or re-roll. If you re-roll, the previous result is lost. What is the expected value under optimal play?',
      correctAnswer: 4.25,
      tolerance: 0.01,
      unit: '$',
      explanation: 'Re-roll EV is $3.50$. Keep if roll $\\geq 4$, re-roll if $\\leq 3$. $E = \\frac{1}{6}(3.5+3.5+3.5+4+5+6) = 25.5/6 = 4.25$.',
      solutionSteps: [
        'Stage 2 (last roll): EV of a single roll $= 3.50$.',
        'Stage 1: Keep the first roll if it exceeds 3.50 (i.e., roll 4, 5, or 6). Otherwise re-roll.',
        'If roll is 1, 2, or 3: you get EV $= 3.50$ from re-rolling.',
        'If roll is 4, 5, or 6: you keep it.',
        '$E = \\frac{1}{6}(3.5 + 3.5 + 3.5 + 4 + 5 + 6) = \\frac{25.5}{6} = 4.25$',
      ],
    },
    {
      id: 'd3-ev-07',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'expected-value',
      tags: ['ev', 'dice', 'call-option'],
      timeEstimateSeconds: 90,
      question: 'You roll two fair dice and your payoff is $\\max(\\text{sum} - 7, 0)$. What is the expected payoff?',
      correctAnswer: 0.972,
      tolerance: 0.01,
      explanation: 'Sum the call payoff $\\max(s-7,0)$ weighted by the probability of each sum from 2 to 12. Only sums 8-12 contribute.',
      solutionSteps: [
        'List payoffs for sums 8 through 12 (sums $\\leq 7$ contribute zero):',
        'Sum 8: payoff 1, probability $5/36$',
        'Sum 9: payoff 2, probability $4/36$',
        'Sum 10: payoff 3, probability $3/36$',
        'Sum 11: payoff 4, probability $2/36$',
        'Sum 12: payoff 5, probability $1/36$',
        '$E = \\frac{1}{36}(1 \\times 5 + 2 \\times 4 + 3 \\times 3 + 4 \\times 2 + 5 \\times 1)$',
        '$= \\frac{5 + 8 + 9 + 8 + 5}{36} = \\frac{35}{36} \\approx 0.972$',
      ],
    },
    {
      id: 'd3-ev-08',
      exerciseType: 'multi-step',
      difficulty: 'medium',
      topic: 'expected-value',
      tags: ['ev', 'dice'],
      timeEstimateSeconds: 120,
      question: 'A game works as follows: roll a fair die. If the roll is 1-3, you lose that amount. If the roll is 4-6, you win that amount. (a) What is the EV? (b) What is the fair entry fee?',
      steps: [
        {
          prompt: 'What is the expected value of the game?',
          correctAnswer: 1.5,
          tolerance: 0.01,
          unit: '$',
          stepExplanation: '$E = \\frac{1}{6}[(-1) + (-2) + (-3) + 4 + 5 + 6] = \\frac{9}{6} = 1.50$',
        },
        {
          prompt: 'What is the fair entry fee (price at which EV of playing = 0)?',
          correctAnswer: 1.5,
          tolerance: 0.01,
          unit: '$',
          stepExplanation: 'The fair fee equals the EV of the game: $\\$1.50$. At this price, the player has zero expected profit.',
        },
      ],
      explanation: 'The fair price of any bet equals its expected value. This is the fundamental principle behind option pricing.',
      solutionSteps: [
        'Payoffs: $-1, -2, -3, +4, +5, +6$ each with probability $1/6$.',
        '$E = \\frac{1}{6}(-1-2-3+4+5+6) = \\frac{9}{6} = 1.50$',
        'Fair entry fee $= E = \\$1.50$.',
      ],
    },
    {
      id: 'd3-ev-09',
      exerciseType: 'free-response',
      difficulty: 'medium',
      topic: 'conditional-expectation',
      tags: ['ev', 'conditional'],
      timeEstimateSeconds: 120,
      question: 'You roll two dice sequentially. After the first roll, you can choose to either: (A) take the first roll as your payoff, or (B) roll again and take the maximum of the two rolls. What is the optimal strategy and EV?',
      modelAnswer: 'Option B always dominates because $E[\\max(d_1, D_2)] \\geq d_1$ for all $d_1$, with strict inequality when $d_1 < 6$. So you always choose B. The EV is $E[\\max(D_1, D_2)] = \\frac{1}{36}\\sum_{i=1}^{6}\\sum_{j=1}^{6}\\max(i,j)$. Using $P(\\max = k) = (2k-1)/36$: $E = \\frac{1}{36}(1 \\cdot 1 + 2 \\cdot 3 + 3 \\cdot 5 + 4 \\cdot 7 + 5 \\cdot 9 + 6 \\cdot 11) = \\frac{161}{36} \\approx 4.472$.',
      explanation: 'Since taking the max can never hurt you, option B always dominates. The EV of the max of two dice is approximately 4.47.',
      solutionSteps: [
        'Option B dominates: $E[\\max(d_1, D_2)] \\geq d_1$ always, with strict inequality when $d_1 < 6$.',
        'So always choose B (roll again and take the max).',
        '$E[\\max(D_1, D_2)] = \\sum_{k=1}^{6} k \\cdot P(\\max = k)$',
        '$P(\\max = k) = (k^2 - (k-1)^2)/36 = (2k-1)/36$',
        '$E = \\frac{1}{36}(1 \\cdot 1 + 2 \\cdot 3 + 3 \\cdot 5 + 4 \\cdot 7 + 5 \\cdot 9 + 6 \\cdot 11) = \\frac{161}{36} = 4.472$',
      ],
    },
    {
      id: 'd3-ev-10',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'risk-neutral-pricing',
      tags: ['ev', 'risk-neutral', 'binomial'],
      timeEstimateSeconds: 90,
      question: 'A stock is at $50. In one period it goes to $60 (up) or $45 (down). The risk-free rate is 2% per period. What is the risk-neutral probability of the up move?',
      correctAnswer: 0.401,
      tolerance: 0.005,
      explanation: '$q = \\frac{S_0 e^r - S_d}{S_u - S_d} = \\frac{50 \\cdot 1.0202 - 45}{60 - 45} = \\frac{51.01 - 45}{15} = \\frac{6.01}{15} = 0.401$',
      solutionSteps: [
        'The risk-neutral probability $q$ satisfies: $S_0 e^r = q S_u + (1-q) S_d$',
        '$50 \\cdot e^{0.02} = q \\cdot 60 + (1-q) \\cdot 45$',
        '$51.01 = 60q + 45 - 45q = 15q + 45$',
        '$q = (51.01 - 45)/15 = 6.01/15 = 0.401$',
      ],
    },
    {
      id: 'd3-ev-11',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'expected-value',
      tags: ['ev', 'dice', 'put-option'],
      timeEstimateSeconds: 60,
      question: 'You roll a fair die. Your payoff is $\\max(4 - \\text{roll}, 0)$ (a "put" with strike 4). What is the expected payoff?',
      correctAnswer: 1.0,
      tolerance: 0.01,
      explanation: '$E = \\frac{1}{6}[3+2+1+0+0+0] = \\frac{6}{6} = 1.00$',
      solutionSteps: [
        'Rolls 1, 2, 3 are "in the money" for this put.',
        'Payoffs: $3, 2, 1, 0, 0, 0$.',
        '$E = \\frac{1}{6}(3+2+1+0+0+0) = \\frac{6}{6} = 1.00$',
      ],
    },
    // --- HARD (5) ---
    {
      id: 'd3-ev-12',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'optimal-stopping',
      tags: ['ev', 'dice', 'optimal-stopping'],
      timeEstimateSeconds: 180,
      question: 'You roll a fair die up to 3 times. After each roll, you can stop and collect that amount in dollars, or re-roll (losing the current value). What is the expected value under optimal play?',
      correctAnswer: 4.667,
      tolerance: 0.01,
      unit: '$',
      explanation: 'Stage 3 EV $= 3.50$. Stage 2 EV $= 4.25$ (keep $\\geq 4$). Stage 1: keep $\\geq 5$, otherwise use remaining 2 rolls. $E = \\frac{1}{6}(4.25+4.25+4.25+4.25+5+6) = 28.0/6 \\approx 4.667$.',
      solutionSteps: [
        'Stage 3: Single roll, $EV_3 = 3.50$.',
        'Stage 2: Keep if roll $> 3.50$ (i.e., 4, 5, 6); re-roll otherwise.',
        '$EV_2 = \\frac{1}{6}(3.5+3.5+3.5+4+5+6) = 25.5/6 = 4.25$',
        'Stage 1: Keep if roll $> 4.25$ (i.e., 5 or 6); use 2-roll game otherwise.',
        '$EV_1 = \\frac{1}{6}(4.25+4.25+4.25+4.25+5+6) = 28.0/6 = 4.667$',
      ],
    },
    {
      id: 'd3-ev-13',
      exerciseType: 'multi-step',
      difficulty: 'hard',
      topic: 'risk-neutral-pricing',
      tags: ['ev', 'risk-neutral', 'binomial', 'call-option'],
      timeEstimateSeconds: 180,
      question: 'A stock is at $100. In one period it goes to $120 or $85. Risk-free rate is 3% per period. (a) Find the risk-neutral probability of an up move. (b) Price a call with strike $105. (c) Price a put with strike $105 and verify put-call parity.',
      steps: [
        {
          prompt: 'What is the risk-neutral probability of an up move?',
          correctAnswer: 0.516,
          tolerance: 0.005,
          stepExplanation: '$q = \\frac{100 \\cdot e^{0.03} - 85}{120 - 85} = \\frac{103.05 - 85}{35} = \\frac{18.05}{35} = 0.516$',
        },
        {
          prompt: 'What is the price of the call with strike $105?',
          correctAnswer: 7.51,
          tolerance: 0.1,
          unit: '$',
          stepExplanation: 'Call payoffs: Up $= \\max(120-105,0) = 15$, Down $= \\max(85-105,0) = 0$. $C = e^{-0.03}[0.516 \\times 15] = 0.9704 \\times 7.74 = 7.51$.',
        },
        {
          prompt: 'What is the price of the put with strike $105?',
          correctAnswer: 9.40,
          tolerance: 0.1,
          unit: '$',
          stepExplanation: 'Put payoffs: Up $= 0$, Down $= \\max(105-85,0) = 20$. $P = e^{-0.03}[0.484 \\times 20] = 0.9704 \\times 9.69 = 9.40$. Parity check: $C - P = 7.51 - 9.40 = -1.89$. $S - Ke^{-rT} = 100 - 101.89 = -1.89$. Confirmed.',
        },
      ],
      explanation: 'This combines risk-neutral pricing with put-call parity verification, bridging Day 1 and Day 3 concepts.',
      solutionSteps: [
        '$q = (S_0 e^r - S_d)/(S_u - S_d) = (103.05 - 85)/35 = 0.516$',
        '$C = e^{-0.03}(0.516 \\times 15) = 0.9704 \\times 7.74 = 7.51$',
        '$P = e^{-0.03}(0.484 \\times 20) = 0.9704 \\times 9.69 = 9.40$',
        'Parity: $C - P = -1.89 = S - Ke^{-rT} = 100 - 101.89$. Confirmed.',
      ],
    },
    {
      id: 'd3-ev-14',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'expected-value',
      tags: ['ev', 'dice', 'custom-payoff'],
      timeEstimateSeconds: 120,
      question: 'You roll two fair dice. You are paid the product of the two rolls (in dollars). What is the expected payoff?',
      correctAnswer: 12.25,
      tolerance: 0.01,
      unit: '$',
      explanation: 'Since the dice are independent: $E[D_1 \\cdot D_2] = E[D_1] \\cdot E[D_2] = 3.5 \\times 3.5 = 12.25$.',
      solutionSteps: [
        'For independent random variables: $E[XY] = E[X] \\cdot E[Y]$.',
        '$E[D_1] = E[D_2] = 3.5$.',
        '$E[D_1 \\cdot D_2] = 3.5 \\times 3.5 = 12.25$.',
        'Note: this uses independence. If the dice were correlated, we would need the full joint distribution.',
      ],
    },
    {
      id: 'd3-ev-15',
      exerciseType: 'free-response',
      difficulty: 'hard',
      topic: 'optimal-stopping',
      tags: ['ev', 'optimal-stopping', 'backward-induction'],
      timeEstimateSeconds: 180,
      question: 'A game show offers you a sequence of envelopes. Envelope $k$ (for $k = 1, 2, 3$) contains $2^k$ dollars with probability 0.5 and $0 with probability 0.5. You open one at a time and must decide to keep its contents or move on (forgoing it). Derive the optimal strategy and EV using backward induction.',
      modelAnswer: 'Stage 3 (last envelope): Must take it. EV_3 = 0.5 x 8 + 0.5 x 0 = 4. Stage 2: Envelope 2 contains $4 or $0. If $4, keep (since 4 >= EV_3 = 4). If $0, move to envelope 3. EV_2 = 0.5 x 4 + 0.5 x 4 = 4. Stage 1: Envelope 1 contains $2 or $0. Since 2 < EV_2 = 4, always move on. EV_1 = 0.5 x 4 + 0.5 x 4 = 4. The optimal EV is $4.',
      explanation: 'Backward induction shows that the option value of future envelopes exactly offsets the gains from early stopping. The EV is $4 regardless of strategy in this special case.',
      solutionSteps: [
        'Stage 3: $EV_3 = 0.5 \\times 2^3 + 0.5 \\times 0 = 4$.',
        'Stage 2: Open envelope 2. If $\\$4$: keep (since $EV_3 = 4$, indifferent). If $\\$0$: move on, get $EV_3 = 4$.',
        '$EV_2 = 0.5 \\times 4 + 0.5 \\times 4 = 4$.',
        'Stage 1: Open envelope 1. If $\\$2 < EV_2 = 4$: move on. If $\\$0$: move on.',
        '$EV_1 = 0.5 \\times 4 + 0.5 \\times 4 = 4$.',
        'Optimal EV $= \\$4$.',
      ],
    },
    {
      id: 'd3-ev-16',
      exerciseType: 'free-response',
      difficulty: 'hard',
      topic: 'expected-value',
      tags: ['ev', 'geometric', 'coins', 'paradox'],
      timeEstimateSeconds: 120,
      question: 'A game pays $2^n$ dollars where $n$ is the number of heads before the first tail in a sequence of fair coin flips. What is the expected payoff? Explain why this is paradoxical.',
      modelAnswer: 'The expected payoff is infinite. $E = \\sum_{n=0}^{\\infty} 2^n \\cdot (1/2)^{n+1} = \\sum_{n=0}^{\\infty} 1/2 = \\infty$. This is the St. Petersburg paradox: despite infinite EV, no rational person would pay an unlimited amount to play because: (1) utility of money is concave (diminishing marginal utility), (2) the payer has finite wealth, and (3) the probability of extreme payoffs is negligible. The resolution involves expected utility theory or imposing a finite bankroll constraint.',
      explanation: 'The St. Petersburg paradox illustrates that EV alone is insufficient for decision-making when outcomes have unbounded variance.',
      solutionSteps: [
        '$P(n \\text{ heads then tail}) = (1/2)^{n+1}$',
        'Payoff for $n$ heads: $2^n$',
        '$E = \\sum_{n=0}^{\\infty} 2^n \\cdot (1/2)^{n+1} = \\sum_{n=0}^{\\infty} \\frac{1}{2} = \\infty$',
        'The series diverges, so EV is infinite.',
        'This is the St. Petersburg paradox, illustrating that EV alone is insufficient for decision-making.',
      ],
    },
    // --- INTERVIEW (3) ---
    {
      id: 'd3-ev-17',
      exerciseType: 'speed-drill',
      difficulty: 'interview',
      topic: 'ev-mental-math',
      tags: ['ev', 'mental-math', 'dice'],
      timeEstimateSeconds: 90,
      timeLimitSeconds: 90,
      problems: [
        { prompt: 'EV of a fair 6-sided die roll', correctAnswer: 3.5, tolerance: 0.01 },
        { prompt: 'EV of max(roll - 3, 0) on a fair die', correctAnswer: 1.0, tolerance: 0.01 },
        { prompt: 'EV of max(5 - roll, 0) on a fair die', correctAnswer: 1.667, tolerance: 0.02 },
        { prompt: 'EV of the sum of 3 fair dice', correctAnswer: 10.5, tolerance: 0.01 },
        { prompt: 'EV of the max of 2 fair coin flips (H=1, T=0)', correctAnswer: 0.75, tolerance: 0.01 },
        { prompt: 'Optimal 2-roll die game EV', correctAnswer: 4.25, tolerance: 0.01 },
      ],
      explanation: 'These are standard mental math calculations that should be instant for a trading interview.',
      solutionSteps: [
        'Die EV: $(1+2+3+4+5+6)/6 = 3.5$',
        '$\\max(\\text{roll}-3, 0)$: $(0+0+0+1+2+3)/6 = 1.0$',
        '$\\max(5-\\text{roll}, 0)$: $(4+3+2+1+0+0)/6 = 10/6 = 1.667$',
        '3 dice: $3 \\times 3.5 = 10.5$ (linearity)',
        '$\\max$ of 2 coins: $P(\\max=1) = 3/4$, $P(\\max=0) = 1/4$. $E = 3/4 = 0.75$',
        '2-roll die: $25.5/6 = 4.25$',
      ],
    },
    {
      id: 'd3-ev-18',
      exerciseType: 'numeric',
      difficulty: 'interview',
      topic: 'expected-value',
      tags: ['ev', 'mental-math', 'dice'],
      timeEstimateSeconds: 60,
      question: 'You roll a fair die repeatedly until you roll a 6. How many rolls do you expect it to take (including the final roll of 6)?',
      correctAnswer: 6,
      tolerance: 0.01,
      explanation: 'This is a geometric distribution with success probability $p = 1/6$. The expected number of trials until the first success is $1/p = 6$.',
      solutionSteps: [
        'Each roll is independent with $P(6) = 1/6$.',
        'The number of rolls until the first 6 follows a geometric distribution.',
        '$E[\\text{rolls}] = 1/p = 1/(1/6) = 6$.',
      ],
    },
    {
      id: 'd3-ev-19',
      exerciseType: 'free-response',
      difficulty: 'interview',
      topic: 'expected-value',
      tags: ['ev', 'dice', 'game-theory', 'mental-math'],
      timeEstimateSeconds: 180,
      question: 'You and an opponent each roll a fair die. Highest roll wins $1 from the other (ties re-rolled). Your opponent offers you the option to see their roll before you roll, but you must still roll a single die. What is the maximum you should pay for this information?',
      modelAnswer: 'Without the option, EV = $0 by symmetry. With the option: seeing their roll does not help because you cannot choose which number to roll. You must still roll a single fair die, and the distribution of your roll is the same regardless of what information you have. The outcome is determined entirely by the two independent dice, so information about one die does not change the EV of the comparison. The information is worth $0.',
      explanation: 'Information only has value if it can change your decision. If you must roll a single fair die regardless, seeing their result changes nothing about your expected outcome.',
      solutionSteps: [
        'Standard game: both roll, highest wins. By symmetry, $EV = 0$.',
        'If you see their roll first but must still roll your own die, your action space is unchanged.',
        'You cannot choose which number to roll, so the information is useless.',
        'Maximum payment for the option: $\\$0$.',
        'Key lesson: information has value only when it can influence your decisions.',
      ],
    },
  ],
  cumulativeExercises: [
    {
      id: 'd3-cum-01',
      exerciseType: 'multi-step',
      difficulty: 'medium',
      topic: 'ev-and-forwards',
      tags: ['ev', 'forward', 'risk-neutral'],
      timeEstimateSeconds: 120,
      fromDay: 1,
      question: 'A stock is at $100, risk-free rate is 4%, $T = 0.5$ years. (a) What is the forward price? (b) Under risk-neutral pricing, what is $E^{\\mathbb{Q}}[S_T]$? (c) Explain the connection.',
      steps: [
        {
          prompt: 'What is the 6-month forward price?',
          correctAnswer: 102.02,
          tolerance: 0.05,
          unit: '$',
          stepExplanation: '$F = 100 \\cdot e^{0.04 \\times 0.5} = 100 \\cdot e^{0.02} = 102.02$',
        },
        {
          prompt: 'Under the risk-neutral measure, what is $E^{\\mathbb{Q}}[S_T]$?',
          correctAnswer: 102.02,
          tolerance: 0.05,
          unit: '$',
          stepExplanation: 'Under the risk-neutral measure, the stock grows at $r$: $E^{\\mathbb{Q}}[S_T] = S_0 e^{rT} = 102.02$. This is exactly the forward price.',
        },
      ],
      explanation: 'The forward price equals the risk-neutral expected future stock price. This is why the forward is the "center" of the risk-neutral distribution.',
      solutionSteps: [
        '$F = S_0 e^{rT} = 100 e^{0.02} = 102.02$',
        '$E^{\\mathbb{Q}}[S_T] = S_0 e^{rT} = 102.02$ (under risk-neutral measure, drift $= r$)',
        'The forward price IS the risk-neutral expected future price.',
      ],
    },
    {
      id: 'd3-cum-02',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'ev-and-parity',
      tags: ['ev', 'put-call-parity', 'risk-neutral'],
      timeEstimateSeconds: 120,
      fromDay: 1,
      question: 'A stock is at $50, $r = 5\\%$, $T = 0.25$. In a one-period binomial model, the stock goes to $60 or $42. Price the 50-strike call using risk-neutral pricing, then derive the put price using put-call parity.',
      correctAnswer: 4.73,
      tolerance: 0.1,
      unit: '$ (call price)',
      explanation: '$q = (50 e^{0.0125} - 42)/(60-42) = (50.628 - 42)/18 = 8.628/18 = 0.4793$. $C = e^{-0.0125}(0.4793 \\times 10) = 0.9876 \\times 4.793 = 4.73$. Parity: $P = C - S + Ke^{-rT} = 4.73 - 50 + 49.38 = 4.11$.',
      solutionSteps: [
        '$q = (50 e^{0.0125} - 42)/(60-42) = 8.628/18 = 0.4793$',
        '$C = e^{-0.0125}(0.4793 \\times 10 + 0.5207 \\times 0) = 0.9876 \\times 4.793 = 4.73$',
        'Parity: $P = C - S + Ke^{-rT} = 4.73 - 50 + 49.38 = 4.11$',
        'Direct check: $P = e^{-0.0125}(0.5207 \\times 8) = 0.9876 \\times 4.166 = 4.11$. Confirmed.',
      ],
    },
    {
      id: 'd3-cum-03',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'ev-and-vol',
      tags: ['ev', 'volatility'],
      timeEstimateSeconds: 90,
      fromDay: 2,
      question: 'A stock is at $100 with 30% annual vol. Using a simple two-state model (up state $S_u = S_0 e^{(r - \\sigma^2/2) + \\sigma}$, down state $S_d = S_0 e^{(r-\\sigma^2/2)-\\sigma}$, each with 50% prob, $r=5\\%$), compute the expected payoff of a 100-strike call in 1 year.',
      correctAnswer: 17.83,
      tolerance: 1.5,
      unit: '$',
      explanation: 'Up: $100 e^{0.005 + 0.30} = 100 e^{0.305} = 135.66$. Down: $100 e^{0.005 - 0.30} = 100 e^{-0.295} = 74.44$. Call payoffs: Up $= 35.66$, Down $= 0$. $E = 0.5 \\times 35.66 = 17.83$.',
      solutionSteps: [
        '$r - \\sigma^2/2 = 0.05 - 0.045 = 0.005$',
        '$S_u = 100 e^{0.005 + 0.30} = 100 e^{0.305} = 135.66$',
        '$S_d = 100 e^{0.005 - 0.30} = 100 e^{-0.295} = 74.44$',
        'Call payoffs: $\\max(135.66 - 100, 0) = 35.66$ and $\\max(74.44 - 100, 0) = 0$.',
        '$E[\\text{payoff}] = 0.5 \\times 35.66 = 17.83$',
        'Discounted call price: $17.83 \\times e^{-0.05} = 16.96$.',
      ],
    },
  ],
  flashcards: [
    { id: 'd3-f01', front: 'Expected value formula (discrete)', back: '$E[X] = \\sum x_i \\cdot p_i$', tags: ['ev'] },
    { id: 'd3-f02', front: 'EV of a fair 6-sided die', back: '$E[X] = 3.5$', tags: ['ev', 'dice'] },
    { id: 'd3-f03', front: 'Linearity of expectation', back: '$E[aX + bY] = aE[X] + bE[Y]$, always — even for dependent variables.', tags: ['ev'] },
    { id: 'd3-f04', front: 'Optimal 2-roll die game EV', back: 'Keep if $\\geq 4$, re-roll otherwise. $EV = 4.25$.', tags: ['ev', 'optimal-stopping'] },
    { id: 'd3-f05', front: 'Optimal 3-roll die game EV', back: 'Stage 1: keep if $\\geq 5$. Stage 2: keep if $\\geq 4$. $EV \\approx 4.67$.', tags: ['ev', 'optimal-stopping'] },
    { id: 'd3-f06', front: 'Risk-neutral pricing formula', back: '$V_0 = e^{-rT} E^{\\mathbb{Q}}[\\text{Payoff}]$. Discount expected payoff under the risk-neutral measure.', tags: ['ev', 'risk-neutral'] },
    { id: 'd3-f07', front: 'Risk-neutral probability (binomial)', back: '$q = \\frac{S_0 e^{rT} - S_d}{S_u - S_d}$', tags: ['ev', 'risk-neutral', 'binomial'] },
    { id: 'd3-f08', front: 'EV of max(roll - K, 0) on a die (K=3.5)', back: '$\\frac{1}{6}(0.5 + 1.5 + 2.5) = 0.75$. This is a "call on a die" at the ATM strike.', tags: ['ev', 'dice', 'call-option'] },
    { id: 'd3-f09', front: 'Law of total expectation', back: '$E[X] = \\sum_j E[X|A_j] P(A_j)$. Decompose expectations via conditioning.', tags: ['ev', 'conditional'] },
    { id: 'd3-f10', front: 'Geometric distribution: expected trials until first success', back: '$E[N] = 1/p$ where $p$ is the probability of success on each trial.', tags: ['ev', 'geometric'] },
    { id: 'd3-f11', front: 'EV of the max of two fair dice', back: '$E[\\max(D_1,D_2)] = 161/36 \\approx 4.47$', tags: ['ev', 'dice'] },
    { id: 'd3-f12', front: 'Connection: forward price and risk-neutral EV', back: '$F = E^{\\mathbb{Q}}[S_T] = S_0 e^{rT}$. The forward IS the risk-neutral expected price.', tags: ['ev', 'forward', 'risk-neutral'] },
  ],
  interactiveTools: ['dice-game', 'payoff-diagram'],
  cheatSheet: [
    { topic: 'Expected Value', formula: 'E[X] = Σ xᵢ pᵢ', description: 'Probability-weighted average of outcomes' },
    { topic: 'Linearity', formula: 'E[aX+bY] = aE[X]+bE[Y]', description: 'Holds for any random variables, dependent or not' },
    { topic: 'Call on Die', formula: 'E[max(roll-K,0)] = Σ (xᵢ-K)pᵢ for xᵢ>K', description: 'Only ITM outcomes contribute' },
    { topic: '2-Roll Optimal Stop', formula: 'EV = 4.25', description: 'Keep >= 4, re-roll <= 3' },
    { topic: '3-Roll Optimal Stop', formula: 'EV = 4.667', description: 'Keep >= 5 on roll 1, >= 4 on roll 2' },
    { topic: 'Risk-Neutral Prob', formula: 'q = (S₀eʳᵀ - Sd)/(Su - Sd)', description: 'Binomial risk-neutral up probability' },
    { topic: 'Risk-Neutral Price', formula: 'V₀ = e⁻ʳᵀ E^Q[Payoff]', description: 'Discount risk-neutral expected payoff' },
    { topic: 'Geometric EV', formula: 'E[N] = 1/p', description: 'Expected trials until first success' },
  ],
  summary: [
    '$E[X] = \\sum x_i p_i$ is the foundation of all pricing and trading decisions',
    'Linearity of expectation: $E[X+Y] = E[X] + E[Y]$ always holds',
    'Backward induction: solve multi-stage games from the last stage forward',
    'Optimal stopping on $n$-roll die: 2-roll EV $= 4.25$, 3-roll EV $\\approx 4.67$',
    'Risk-neutral pricing: $V_0 = e^{-rT} E^{\\mathbb{Q}}[\\text{Payoff}]$, with $E^{\\mathbb{Q}}[S_T] = S_0 e^{rT}$ (the forward)',
  ],
  trackB: {
    title: 'PCA & Dimensionality Reduction for Vol Surfaces',
    subtitle: 'Principal Components, Ledoit-Wolf Shrinkage',
    objectives: [
      'Explain the curse of dimensionality and why sample covariance degenerates when $p \\approx n$',
      'Derive PCA from the spectral decomposition of the covariance matrix',
      'Interpret the first 3 principal components of a vol surface as Level, Slope, and Curvature',
      'Apply PCA to reduce a 50-strike vol surface to 3 tradeable risk factors',
      'Implement Ledoit-Wolf shrinkage to stabilize covariance estimation for portfolio optimization',
    ],
    theory: {
      sections: [
        {
          title: 'The Curse of Dimensionality',
          blocks: [
            {
              type: 'text',
              body: 'A volatility surface for a single underlying may have 50-100 strike-expiry combinations. To estimate their covariance, we need the $p \\times p$ covariance matrix with $p(p+1)/2$ unique entries. With $p = 50$ strikes, that is 1,275 parameters. If we have $n = 100$ days of data, we are estimating 1,275 parameters from only 100 observations — the sample covariance matrix $\\hat{\\Sigma}$ is poorly estimated and often singular.',
            },
            {
              type: 'formula',
              latex: '\\hat{\\Sigma} = \\frac{1}{n-1}\\sum_{i=1}^{n}(x_i - \\bar{x})(x_i - \\bar{x})^T',
              label: 'Sample Covariance Matrix',
              explanation: 'An unbiased estimator of the true covariance, but has rank $\\min(n-1, p)$. When $p > n$, $\\hat{\\Sigma}$ is singular.',
            },
            {
              type: 'concept',
              title: 'Why Sample Covariance Fails',
              body: 'When $p/n > 0.1$, the smallest eigenvalues of $\\hat{\\Sigma}$ are biased downward (too small) and the largest are biased upward (too large). This is the Marchenko-Pastur phenomenon. At $p = n$, the smallest eigenvalue hits zero. Result: portfolio optimization using $\\hat{\\Sigma}^{-1}$ produces wildly leveraged, unstable portfolios.',
            },
            {
              type: 'example',
              title: 'Dimensionality Disaster in Vol Surface Hedging',
              problem: 'You trade options on SPX with 8 expiries and 7 strikes each ($p = 56$). You want to compute a minimum-variance hedge using the covariance matrix of daily IV changes. You have 60 trading days of data. Why will this fail?',
              solution: [
                'The sample covariance $\\hat{\\Sigma}$ is $56 \\times 56$ but you only have $n = 60$ observations.',
                'The rank of $\\hat{\\Sigma}$ is at most $\\min(59, 56) = 56$, so it is technically full rank.',
                'But $p/n = 56/60 = 0.93$ — extremely close to 1. The Marchenko-Pastur distribution predicts massive eigenvalue distortion.',
                'The smallest eigenvalues are essentially noise; $\\hat{\\Sigma}^{-1}$ amplifies noise in these directions.',
                'The minimum-variance portfolio $w \\propto \\hat{\\Sigma}^{-1}\\mathbf{1}$ will have enormous leverage on noisy eigenvectors.',
                'Solution: reduce to $k = 3$ principal components (Level, Slope, Curvature) or apply shrinkage.',
              ],
            },
            {
              type: 'callout',
              variant: 'warning',
              body: 'Rule of thumb: you need $n \\geq 5p$ observations for the sample covariance to be reasonably well-estimated. For a 50-strike vol surface, that means at least 250 days (~1 year) of data. PCA and shrinkage allow us to work with far less data.',
            },
          ],
        },
        {
          title: 'PCA: Theory',
          blocks: [
            {
              type: 'text',
              body: 'Principal Component Analysis finds the orthogonal directions that capture maximum variance in the data. It is based on the spectral decomposition (eigendecomposition) of the covariance matrix: $\\Sigma = V \\Lambda V^T$, where $V$ is the matrix of eigenvectors and $\\Lambda = \\text{diag}(\\lambda_1, \\ldots, \\lambda_p)$ with eigenvalues sorted $\\lambda_1 \\geq \\lambda_2 \\geq \\ldots \\geq \\lambda_p \\geq 0$.',
            },
            {
              type: 'formula',
              latex: '\\Sigma = V \\Lambda V^T = \\sum_{j=1}^{p} \\lambda_j v_j v_j^T',
              label: 'Spectral Decomposition',
              explanation: '$v_j$ is the $j$-th eigenvector (principal direction), $\\lambda_j$ is the variance explained by the $j$-th component. The data projected onto $v_j$ has variance $\\lambda_j$.',
            },
            {
              type: 'concept',
              title: 'Principal Components',
              body: 'The $j$-th principal component score for observation $x_i$ is $z_{ij} = v_j^T(x_i - \\bar{x})$. This is the projection of the centered data onto the $j$-th eigenvector. The principal components are uncorrelated: $\\text{Cov}(z_j, z_k) = 0$ for $j \\neq k$, and $\\text{Var}(z_j) = \\lambda_j$.',
            },
            {
              type: 'formula',
              latex: '\\text{Fraction of variance explained by top } k \\text{ PCs} = \\frac{\\sum_{j=1}^{k} \\lambda_j}{\\sum_{j=1}^{p} \\lambda_j}',
              label: 'Variance Ratio',
              explanation: 'Measures how much of the total variability is captured by the first $k$ components. For vol surfaces, $k=3$ typically captures 95%+.',
            },
            {
              type: 'callout',
              variant: 'key-insight',
              body: 'PCA is a dimensionality reduction technique: replace $p$-dimensional data with $k$-dimensional projections ($k \\ll p$) that retain most of the variance. For a 50-strike vol surface, $k = 3$ PCs typically explain 95% of daily vol changes. We trade 3 risk factors instead of 50.',
            },
          ],
        },
        {
          title: 'PCA: Algorithm',
          blocks: [
            {
              type: 'text',
              body: 'The PCA algorithm is straightforward: (1) Center the data: $\\tilde{X} = X - \\bar{x}$. (2) Compute the sample covariance: $\\hat{\\Sigma} = \\tilde{X}^T\\tilde{X}/(n-1)$. (3) Eigendecompose: $\\hat{\\Sigma} = V\\Lambda V^T$. (4) Select $k$ components based on variance explained. (5) Project: $Z = \\tilde{X} V_k$, where $V_k$ is the $p \\times k$ matrix of the top $k$ eigenvectors.',
            },
            {
              type: 'formula',
              latex: 'Z = (X - \\bar{x}) V_k \\in \\mathbb{R}^{n \\times k}',
              label: 'PCA Projection',
              explanation: 'Reduces data from $p$ dimensions to $k$ dimensions. $Z$ has uncorrelated columns with variances $\\lambda_1, \\ldots, \\lambda_k$.',
            },
            {
              type: 'example',
              title: 'PCA Computation: Simple 3D Example',
              problem: 'Three assets have daily returns with covariance matrix $\\hat{\\Sigma} = \\begin{pmatrix} 4 & 3 & 1 \\\\ 3 & 5 & 2 \\\\ 1 & 2 & 2 \\end{pmatrix}$. The eigenvalues are $\\lambda_1 = 8.26$, $\\lambda_2 = 2.08$, $\\lambda_3 = 0.66$. How many PCs are needed to explain 90% of variance?',
              solution: [
                'Total variance = $\\text{tr}(\\hat{\\Sigma}) = 4 + 5 + 2 = 11 = \\lambda_1 + \\lambda_2 + \\lambda_3 = 8.26 + 2.08 + 0.66$.',
                'PC1 explains: $8.26/11 = 75.1\\%$.',
                'PC1 + PC2 explains: $(8.26 + 2.08)/11 = 10.34/11 = 94.0\\%$.',
                'Two PCs are sufficient to explain 94% > 90% of variance.',
                'We can represent 3-asset risk with 2 factors, discarding the third (6% of variance).',
              ],
            },
            {
              type: 'table',
              headers: ['Step', 'Input', 'Output', 'Complexity'],
              rows: [
                ['Center', 'Raw data $X \\in \\mathbb{R}^{n \\times p}$', '$\\tilde{X} = X - \\bar{x}$', '$O(np)$'],
                ['Covariance', '$\\tilde{X}$', '$\\hat{\\Sigma} = \\tilde{X}^T\\tilde{X}/(n-1)$', '$O(np^2)$'],
                ['Eigendecompose', '$\\hat{\\Sigma} \\in \\mathbb{R}^{p \\times p}$', '$V, \\Lambda$', '$O(p^3)$'],
                ['Project', '$\\tilde{X}, V_k$', '$Z = \\tilde{X}V_k \\in \\mathbb{R}^{n \\times k}$', '$O(npk)$'],
              ],
            },
          ],
        },
        {
          title: 'PCA for Vol Surfaces',
          blocks: [
            {
              type: 'text',
              body: 'The canonical result in options research (Cont & da Fonseca, 2002) is that 3 principal components explain 95%+ of daily vol surface movements. These have clear financial interpretations:',
            },
            {
              type: 'table',
              headers: ['PC', 'Name', 'Variance Explained', 'Shape', 'Financial Interpretation'],
              rows: [
                ['PC1', 'Level', '85-90%', 'All loadings same sign, roughly flat', 'Parallel shift: all IVs move up or down together'],
                ['PC2', 'Slope/Skew', '5-8%', 'Loadings change sign once (e.g., negative for low strikes, positive for high strikes)', 'Tilt: skew steepens or flattens'],
                ['PC3', 'Curvature', '2-3%', 'Loadings change sign twice (U-shape or inverted U)', 'Butterfly: wings move relative to ATM'],
              ],
            },
            {
              type: 'example',
              title: 'Vol Surface PCA: SPX Options',
              problem: 'You compute PCA on 252 days of daily changes in SPX implied volatility across 20 strikes (90%-110% moneyness). The eigenvalues are: $\\lambda_1 = 45.2$, $\\lambda_2 = 4.8$, $\\lambda_3 = 1.5$, $\\lambda_4 = 0.4$, $\\ldots$ (sum of all = 53.1). Compute the variance explained by the first 3 PCs.',
              solution: [
                '$\\lambda_1/\\text{total} = 45.2/53.1 = 85.1\\%$ (Level).',
                '$(\\lambda_1 + \\lambda_2)/\\text{total} = 50.0/53.1 = 94.2\\%$ (Level + Slope).',
                '$(\\lambda_1 + \\lambda_2 + \\lambda_3)/\\text{total} = 51.5/53.1 = 97.0\\%$ (Level + Slope + Curvature).',
                'Three PCs explain 97% of daily vol surface variation.',
                'The remaining 17 eigenvalues collectively explain only 3% — essentially noise.',
                'A trader can hedge 97% of vol surface risk with 3 instruments (e.g., ATM straddle, risk reversal, butterfly).',
              ],
            },
            {
              type: 'interactive',
              tool: 'pca-vol-decomposition',
              defaultParams: { numStrikes: 20, numDays: 252, numComponents: 3 },
            },
            {
              type: 'callout',
              variant: 'key-insight',
              body: 'PCA tells you what to trade: PC1 (Level) is hedged with ATM straddles. PC2 (Slope) is hedged with risk reversals (buy OTM put, sell OTM call). PC3 (Curvature) is hedged with butterflies. These correspond to the standard "Greek letter" sensitivities: Vega ≈ PC1, Vanna ≈ PC2 component, Volga ≈ PC3 component.',
            },
          ],
        },
        {
          title: 'Ledoit-Wolf Shrinkage',
          blocks: [
            {
              type: 'text',
              body: 'When the sample covariance $\\hat{\\Sigma}$ is poorly estimated (because $p/n$ is large), we can improve it by **shrinking** toward a structured target. Ledoit & Wolf (2004) propose shrinking toward a multiple of the identity: $\\hat{\\Sigma}_{\\text{LW}} = \\alpha \\cdot \\frac{\\text{tr}(\\hat{\\Sigma})}{p} I + (1 - \\alpha) \\cdot \\hat{\\Sigma}$.',
            },
            {
              type: 'formula',
              latex: '\\hat{\\Sigma}_{\\text{LW}} = \\alpha \\cdot \\mu I + (1 - \\alpha) \\cdot \\hat{\\Sigma}, \\quad \\mu = \\frac{\\text{tr}(\\hat{\\Sigma})}{p}',
              label: 'Ledoit-Wolf Shrinkage Estimator',
              explanation: '$\\mu$ is the average eigenvalue (ensures trace is preserved). $\\alpha \\in [0,1]$ is the shrinkage intensity: $\\alpha = 0$ is the sample covariance, $\\alpha = 1$ is the identity target.',
            },
            {
              type: 'concept',
              title: 'Optimal Shrinkage Intensity',
              body: 'Ledoit & Wolf derive an analytical formula for the optimal $\\alpha^*$ that minimizes the expected Frobenius norm $\\mathbb{E}\\|\\hat{\\Sigma}_{\\text{LW}} - \\Sigma\\|_F^2$. Roughly, $\\alpha^* \\propto p/n$: more shrinkage when the dimension-to-sample ratio is high. When $p \\ll n$, $\\alpha^* \\approx 0$ (trust the sample). When $p \\approx n$, $\\alpha^*$ is large (trust the target).',
            },
            {
              type: 'text',
              body: '**Effect on eigenvalues:** Shrinkage pulls eigenvalues toward their mean $\\mu$. Large eigenvalues shrink down, small eigenvalues are pulled up. The condition number improves dramatically: the smallest eigenvalue becomes at least $\\alpha \\mu > 0$, preventing singularity.',
            },
            {
              type: 'example',
              title: 'Ledoit-Wolf: Condition Number Improvement',
              problem: 'Sample covariance of 20 assets has eigenvalues ranging from $\\lambda_{\\max} = 45$ to $\\lambda_{\\min} = 0.02$. Total trace = 60, so $\\mu = 60/20 = 3$. With optimal $\\alpha^* = 0.3$, compute the condition number of $\\hat{\\Sigma}_{\\text{LW}}$.',
              solution: [
                'Shrunk eigenvalues: $\\tilde{\\lambda}_j = \\alpha \\mu + (1-\\alpha)\\lambda_j = 0.3(3) + 0.7\\lambda_j = 0.9 + 0.7\\lambda_j$.',
                'Largest: $\\tilde{\\lambda}_{\\max} = 0.9 + 0.7(45) = 0.9 + 31.5 = 32.4$.',
                'Smallest: $\\tilde{\\lambda}_{\\min} = 0.9 + 0.7(0.02) = 0.9 + 0.014 = 0.914$.',
                'Condition number: $\\kappa_{\\text{LW}} = 32.4/0.914 = 35.4$.',
                'Original: $\\kappa = 45/0.02 = 2250$. Improvement: $2250/35.4 = 63.6\\times$.',
              ],
            },
            {
              type: 'interactive',
              tool: 'ledoit-wolf-shrinkage',
              defaultParams: { numAssets: 20, numObs: 60, shrinkageIntensity: 0.3 },
            },
            {
              type: 'callout',
              variant: 'tip',
              body: 'In practice, PCA and shrinkage are complementary: use PCA to identify the major risk factors (Level, Slope, Curvature) and use shrinkage on the residual covariance for the less important components. This "factor + shrinkage" approach is the industry standard for portfolio risk management.',
            },
          ],
        },
      ],
    },
    exercises: [
      {
        id: 'd3b-curse-01',
        exerciseType: 'numeric',
        difficulty: 'easy',
        topic: 'Curse of Dimensionality',
        tags: ['dimensionality', 'covariance'],
        timeEstimateSeconds: 60,
        question: 'A vol surface has 8 expiries and 10 strikes ($p = 80$). How many unique parameters are in the covariance matrix $\\Sigma$?',
        correctAnswer: 3240,
        tolerance: 0,
        explanation: 'A $p \\times p$ symmetric covariance matrix has $p(p+1)/2 = 80 \\times 81/2 = 3240$ unique entries.',
        solutionSteps: [
          '$p = 8 \\times 10 = 80$ strike-expiry combinations.',
          'Unique entries in symmetric $p \\times p$ matrix: $p(p+1)/2$.',
          '$80 \\times 81/2 = 3240$.',
          'To estimate these 3240 parameters reliably, you need at least $5p = 400$ days of data.',
        ],
      },
      {
        id: 'd3b-curse-02',
        exerciseType: 'true-false',
        difficulty: 'easy',
        topic: 'Sample Covariance',
        tags: ['covariance', 'rank'],
        timeEstimateSeconds: 45,
        statement: 'The sample covariance matrix of $p = 100$ features computed from $n = 50$ observations is always full rank.',
        correct: false,
        explanation: 'The rank of the sample covariance is at most $\\min(n-1, p) = \\min(49, 100) = 49$. With $p = 100$ and $n = 50$, the matrix has rank 49 — it is singular and non-invertible.',
        solutionSteps: [
          'Data matrix $X$ is $n \\times p = 50 \\times 100$.',
          'Centered data $\\tilde{X}$ has rank $\\leq \\min(n-1, p) = \\min(49, 100) = 49$.',
          '$\\hat{\\Sigma} = \\tilde{X}^T\\tilde{X}/(n-1)$ inherits this rank.',
          'Rank 49 < $p = 100$: the matrix is singular.',
        ],
      },
      {
        id: 'd3b-pca-01',
        exerciseType: 'multiple-choice',
        difficulty: 'easy',
        topic: 'PCA Basics',
        tags: ['pca', 'eigenvalues'],
        timeEstimateSeconds: 60,
        question: 'Eigenvalues of a covariance matrix are [10, 4, 3, 2, 1]. What fraction of variance is explained by the first principal component?',
        options: [
          '10%',
          '25%',
          '50%',
          '70%',
        ],
        correctIndex: 2,
        explanation: 'Total variance = $10 + 4 + 3 + 2 + 1 = 20$. PC1 explains $10/20 = 50\\%$.',
        solutionSteps: [
          'Total variance = trace = sum of eigenvalues = $10 + 4 + 3 + 2 + 1 = 20$.',
          'PC1 variance = $\\lambda_1 = 10$.',
          'Fraction = $10/20 = 0.50 = 50\\%$.',
        ],
      },
      {
        id: 'd3b-pca-02',
        exerciseType: 'numeric',
        difficulty: 'easy',
        topic: 'Variance Explained',
        tags: ['pca', 'variance-ratio'],
        timeEstimateSeconds: 60,
        question: 'Eigenvalues of a 6-asset covariance matrix: [25, 8, 3, 1.5, 0.4, 0.1]. What percentage of variance is explained by the first 3 PCs?',
        correctAnswer: 94.7,
        tolerance: 0.5,
        explanation: 'Total = $25 + 8 + 3 + 1.5 + 0.4 + 0.1 = 38$. Top 3: $25 + 8 + 3 = 36$. Ratio: $36/38 = 94.7\\%$.',
        solutionSteps: [
          'Total variance = $25 + 8 + 3 + 1.5 + 0.4 + 0.1 = 38$.',
          'Variance from PC1-3 = $25 + 8 + 3 = 36$.',
          'Fraction = $36/38 = 0.9474 = 94.7\\%$.',
        ],
      },
      {
        id: 'd3b-pca-03',
        exerciseType: 'multiple-choice',
        difficulty: 'easy',
        topic: 'PCA Interpretation',
        tags: ['pca', 'vol-surface'],
        timeEstimateSeconds: 60,
        question: 'In PCA of a vol surface, PC1 typically explains ~85-90% of variance. This component represents:',
        options: [
          'The skew of the vol surface steepening or flattening',
          'A parallel shift in all implied volatilities up or down',
          'The curvature (butterfly) of the smile changing',
          'Idiosyncratic moves in individual strike IVs',
        ],
        correctIndex: 1,
        explanation: 'PC1 is the "Level" component: all loadings have the same sign, meaning all IVs move up or down together. This parallel shift is the dominant mode of vol surface variation.',
        solutionSteps: [
          'PC1 loadings: all same sign, roughly flat across strikes → parallel shift.',
          'This is the "Level" factor, capturing overall vol going up or down.',
          'It explains 85-90% because vols are highly correlated across strikes.',
          'When VIX moves, it shifts the entire surface — this is PC1.',
        ],
      },
      {
        id: 'd3b-pca-04',
        exerciseType: 'multi-step',
        difficulty: 'medium',
        topic: 'PCA Computation',
        tags: ['pca', 'eigenvalues', 'projection'],
        timeEstimateSeconds: 180,
        question: 'Given a 2D covariance matrix $\\hat{\\Sigma} = \\begin{pmatrix} 5 & 3 \\\\ 3 & 5 \\end{pmatrix}$, perform PCA.',
        steps: [
          {
            prompt: 'Find the eigenvalues. Solve $\\det(\\Sigma - \\lambda I) = 0$: $(5-\\lambda)^2 - 9 = 0$. What is $\\lambda_1$ (the larger one)?',
            correctAnswer: 8,
            tolerance: 0,
            unit: '',
            stepExplanation: '$(5-\\lambda)^2 = 9 \\Rightarrow 5-\\lambda = \\pm 3$. So $\\lambda_1 = 8$, $\\lambda_2 = 2$.',
          },
          {
            prompt: 'What fraction of variance does PC1 explain?',
            correctAnswer: 80,
            tolerance: 0,
            unit: '%',
            stepExplanation: 'Total variance = $8 + 2 = 10$. PC1: $8/10 = 80\\%$.',
          },
          {
            prompt: 'The eigenvector for $\\lambda_1 = 8$ is $v_1 = (1/\\sqrt{2}, 1/\\sqrt{2})$. If a data point is $x = (3, 1)$ with mean $\\bar{x} = (0, 0)$, what is its PC1 score?',
            correctAnswer: 2.83,
            tolerance: 0.05,
            unit: '',
            stepExplanation: '$z_1 = v_1^T x = (1/\\sqrt{2})(3) + (1/\\sqrt{2})(1) = 4/\\sqrt{2} = 2\\sqrt{2} \\approx 2.83$.',
          },
        ],
        explanation: 'PCA of a $2 \\times 2$ covariance with equal variances and positive correlation: PC1 is the $(1,1)$ direction (average), PC2 is the $(1,-1)$ direction (difference). The eigenvalues are $\\sigma^2 + \\rho\\sigma^2 = 5 + 3 = 8$ and $\\sigma^2 - \\rho\\sigma^2 = 5 - 3 = 2$.',
        solutionSteps: [
          'Characteristic equation: $(5-\\lambda)^2 - 9 = 0$.',
          '$\\lambda_1 = 8$, $\\lambda_2 = 2$.',
          'PC1 explains $8/10 = 80\\%$.',
          '$v_1 = (1/\\sqrt{2}, 1/\\sqrt{2})$: the "average" direction.',
          '$v_2 = (1/\\sqrt{2}, -1/\\sqrt{2})$: the "difference" direction.',
          'PC1 score = $v_1^T x = 4/\\sqrt{2} = 2.83$.',
        ],
      },
      {
        id: 'd3b-pca-05',
        exerciseType: 'numeric',
        difficulty: 'medium',
        topic: 'Reconstruction Error',
        tags: ['pca', 'reconstruction'],
        timeEstimateSeconds: 90,
        question: 'A vol surface has 30 strike-expiry points. PCA eigenvalues: $\\lambda_1 = 50, \\lambda_2 = 6, \\lambda_3 = 2$, and the remaining 27 eigenvalues sum to 2. If you use $k = 3$ PCs to reconstruct the surface, what is the expected reconstruction error as a fraction of total variance?',
        correctAnswer: 3.33,
        tolerance: 0.1,
        unit: '%',
        explanation: 'Total variance = $50 + 6 + 2 + 2 = 60$. Variance not captured = $60 - 58 = 2$. Reconstruction error = $2/60 = 3.33\\%$.',
        solutionSteps: [
          'Total variance = $50 + 6 + 2 + 2 = 60$.',
          'Variance captured by 3 PCs = $50 + 6 + 2 = 58$.',
          'Variance not captured = $60 - 58 = 2$.',
          'Reconstruction error fraction = $2/60 = 0.0333 = 3.33\\%$.',
        ],
      },
      {
        id: 'd3b-pca-06',
        exerciseType: 'true-false',
        difficulty: 'medium',
        topic: 'PCA Properties',
        tags: ['pca', 'orthogonality'],
        timeEstimateSeconds: 60,
        statement: 'Principal components (the projected data) are always uncorrelated with each other, even if the original features were correlated.',
        correct: true,
        explanation: 'Yes, by construction. PC scores are $z_j = v_j^T(x - \\bar{x})$. Since $\\text{Cov}(z_j, z_k) = v_j^T \\Sigma v_k = v_j^T \\lambda_k v_k = \\lambda_k (v_j^T v_k) = 0$ for $j \\neq k$ (eigenvectors are orthogonal).',
        solutionSteps: [
          '$\\text{Cov}(z_j, z_k) = v_j^T \\Sigma v_k$.',
          '$\\Sigma v_k = \\lambda_k v_k$ (eigenvalue equation).',
          'So $v_j^T \\Sigma v_k = \\lambda_k v_j^T v_k = 0$ since eigenvectors are orthogonal.',
          'Therefore PC scores are always uncorrelated.',
        ],
      },
      {
        id: 'd3b-vol-01',
        exerciseType: 'multiple-choice',
        difficulty: 'medium',
        topic: 'Vol Surface PCA',
        tags: ['pca', 'vol-surface', 'hedging'],
        timeEstimateSeconds: 90,
        question: 'You have decomposed a vol surface into 3 PCs: Level (85%), Slope (8%), Curvature (4%). A trader only hedges PC1 (Level). Approximately what percentage of vol surface variance is left unhedged?',
        options: [
          '3%',
          '8%',
          '12%',
          '15%',
        ],
        correctIndex: 3,
        explanation: 'If PC1 explains 85%, then 100% - 85% = 15% is unhedged. This includes Slope (8%), Curvature (4%), and residual (3%).',
        solutionSteps: [
          'PC1 (Level) = 85% → hedged.',
          'Remaining = 100% - 85% = 15% unhedged.',
          'This 15% consists of PC2 (Slope, 8%) + PC3 (Curvature, 4%) + residual (3%).',
          'In a vol-of-vol spike, the unhedged 15% can generate significant P&L.',
        ],
      },
      {
        id: 'd3b-lw-01',
        exerciseType: 'numeric',
        difficulty: 'medium',
        topic: 'Ledoit-Wolf Shrinkage',
        tags: ['shrinkage', 'covariance'],
        timeEstimateSeconds: 120,
        question: 'Sample covariance eigenvalues: [30, 5, 0.5, 0.01]. Trace = 35.51, $p = 4$, $\\mu = 35.51/4 = 8.878$. With shrinkage $\\alpha = 0.4$, what is the new smallest eigenvalue?',
        correctAnswer: 3.557,
        tolerance: 0.01,
        explanation: '$\\tilde{\\lambda}_{\\min} = \\alpha \\mu + (1-\\alpha)\\lambda_{\\min} = 0.4(8.878) + 0.6(0.01) = 3.551 + 0.006 = 3.557$.',
        solutionSteps: [
          'Shrinkage formula: $\\tilde{\\lambda}_j = \\alpha \\mu + (1-\\alpha)\\lambda_j$.',
          '$\\mu = 35.51/4 = 8.878$.',
          '$\\tilde{\\lambda}_{\\min} = 0.4(8.878) + 0.6(0.01) = 3.551 + 0.006 = 3.557$.',
          'Original $\\lambda_{\\min} = 0.01$ was near-zero; after shrinkage it is 3.557.',
          'This prevents the singularity that would break portfolio optimization.',
        ],
      },
      {
        id: 'd3b-lw-02',
        exerciseType: 'multi-step',
        difficulty: 'hard',
        topic: 'Ledoit-Wolf: Full Computation',
        tags: ['shrinkage', 'condition-number'],
        timeEstimateSeconds: 180,
        question: 'A 10-asset covariance matrix has eigenvalues: [40, 15, 8, 4, 2, 1, 0.5, 0.2, 0.05, 0.01]. Compute the condition number before and after Ledoit-Wolf shrinkage with $\\alpha = 0.25$.',
        steps: [
          {
            prompt: 'Compute $\\mu = \\text{tr}/p$. What is $\\mu$?',
            correctAnswer: 7.076,
            tolerance: 0.01,
            unit: '',
            stepExplanation: 'Trace = $40 + 15 + 8 + 4 + 2 + 1 + 0.5 + 0.2 + 0.05 + 0.01 = 70.76$. $\\mu = 70.76/10 = 7.076$.',
          },
          {
            prompt: 'Compute the shrunk maximum eigenvalue: $\\tilde{\\lambda}_{\\max} = 0.25(7.076) + 0.75(40)$.',
            correctAnswer: 31.769,
            tolerance: 0.01,
            unit: '',
            stepExplanation: '$\\tilde{\\lambda}_{\\max} = 1.769 + 30.0 = 31.769$.',
          },
          {
            prompt: 'Compute the shrunk minimum eigenvalue and the new condition number $\\kappa_{\\text{LW}} = \\tilde{\\lambda}_{\\max}/\\tilde{\\lambda}_{\\min}$.',
            correctAnswer: 17.21,
            tolerance: 0.5,
            unit: '',
            stepExplanation: '$\\tilde{\\lambda}_{\\min} = 0.25(7.076) + 0.75(0.01) = 1.769 + 0.0075 = 1.776$. $\\kappa_{\\text{LW}} = 31.769/1.776 = 17.89$. Original $\\kappa = 40/0.01 = 4000$.',
          },
        ],
        explanation: 'Ledoit-Wolf shrinkage reduced the condition number from 4000 to ~18 — a 220x improvement. The small eigenvalues (0.01, 0.05) that would have caused numerical instability in $\\Sigma^{-1}$ are now safely bounded away from zero.',
        solutionSteps: [
          'Trace = 70.76, $\\mu = 7.076$.',
          '$\\tilde{\\lambda}_{\\max} = 0.25(7.076) + 0.75(40) = 31.769$.',
          '$\\tilde{\\lambda}_{\\min} = 0.25(7.076) + 0.75(0.01) = 1.776$.',
          '$\\kappa_{\\text{LW}} = 31.769/1.776 \\approx 17.9$.',
          'Original $\\kappa = 4000$. Improvement: $\\sim 220\\times$.',
        ],
      },
      {
        id: 'd3b-pca-07',
        exerciseType: 'free-response',
        difficulty: 'hard',
        topic: 'PCA Trading Application',
        tags: ['pca', 'vol-surface', 'trading'],
        timeEstimateSeconds: 180,
        question: 'You compute PCA on daily changes in the SPX vol surface and find that today PC2 (slope/skew) moved by +3 standard deviations while PC1 (level) barely moved. What happened in the market and how would you trade this if you believe it will mean-revert?',
        modelAnswer: 'A +3 SD move in PC2 (slope) without a level shift means the vol surface skew steepened significantly — OTM puts became much more expensive relative to OTM calls, without overall vol increasing. This could be due to (1) a sudden demand for downside protection (hedge fund buying puts), (2) an earnings event with asymmetric risk, or (3) a flash crash that affected wing IVs more than ATM. If I believe this skew move is temporary (mean-reversion), I would sell the skew: sell OTM puts and buy OTM calls (a risk reversal). Specifically, sell the 90% put and buy the 110% call in equal vega amounts, delta-hedging the net position. The expected profit is the skew compression times the vega exposure. Risk: if the skew steepening was driven by fundamental changes (e.g., approaching recession), it may persist. Size the position so that a further 2 SD skew move is survivable.',
        explanation: 'This tests the ability to translate PCA outputs into trading strategies — the core application of PCA in an options market-making context.',
        solutionSteps: [
          'PC2 = slope/skew: positive loading on low strikes, negative on high (or vice versa).',
          '+3 SD move: extreme skew steepening.',
          'Meaning: OTM puts relatively expensive, OTM calls relatively cheap.',
          'Mean-reversion trade: sell expensive skew (sell puts, buy calls) = risk reversal.',
          'Delta-hedge to isolate the skew exposure.',
          'Risk management: size to survive further 2 SD move.',
        ],
      },
      {
        id: 'd3b-pca-08',
        exerciseType: 'multiple-choice',
        difficulty: 'hard',
        topic: 'PCA vs Shrinkage',
        tags: ['pca', 'shrinkage', 'covariance-estimation'],
        timeEstimateSeconds: 120,
        question: 'For minimum-variance portfolio optimization with 50 assets and 120 observations, which approach is MOST appropriate?',
        options: [
          'Use the raw sample covariance matrix',
          'Use PCA with 3 components and discard all other variation',
          'Use Ledoit-Wolf shrinkage on the full covariance matrix',
          'Use a factor model (PCA for major factors) plus Ledoit-Wolf shrinkage on the residual covariance',
        ],
        correctIndex: 3,
        explanation: 'Option D combines the strengths of both approaches. PCA captures the dominant risk factors (which are well-estimated), while shrinkage stabilizes the residual covariance (which is poorly estimated). This "factor + shrinkage" approach is the industry standard.',
        solutionSteps: [
          'Raw sample covariance: $p/n = 50/120 = 0.42$ — too high, eigenvalues distorted.',
          'PCA with 3 components: discards 95% of dimensions but loses idiosyncratic risk information.',
          'Ledoit-Wolf alone: better than raw, but treats all directions equally.',
          'Factor + shrinkage: PCA for dominant factors (well-estimated), shrinkage for residuals.',
          'This is what BlackRock, MSCI, and Barra risk models actually use.',
        ],
      },
      {
        id: 'd3b-interview-01',
        exerciseType: 'free-response',
        difficulty: 'interview',
        topic: 'Vol Surface Risk Management',
        tags: ['pca', 'hedging', 'interview'],
        timeEstimateSeconds: 300,
        question: 'You manage a portfolio of 50 SPX options across different strikes and expiries. Explain how you would use PCA to (1) measure your portfolio\'s risk, (2) design hedges, and (3) identify trading opportunities. Be specific about which instruments you would use.',
        modelAnswer: 'Step 1 - Risk Measurement: Compute PCA on 252 days of daily changes in the IV at each of my 50 strike-expiry points. Get eigenvalues and eigenvectors. My portfolio\'s exposure to each PC is: $\\text{PC}_k\\text{-exposure} = \\sum_{i=1}^{50} w_i \\cdot \\text{vega}_i \\cdot v_{k,i}$, where $w_i$ is the position size and $v_{k,i}$ is the loading of strike-expiry $i$ on PC $k$. PC1-exposure = my net vega (level risk). PC2-exposure = my skew risk. PC3-exposure = my curvature risk. Total variance explained: $\\text{Var}(\\text{P\\&L}) \\approx \\sum_k (\\text{PC}_k\\text{-exposure})^2 \\lambda_k$.\n\nStep 2 - Hedging: To neutralize PC1 (level), trade ATM straddles until PC1-exposure ≈ 0. To neutralize PC2 (slope), trade 25-delta risk reversals (buy/sell 25-delta put and call). To neutralize PC3 (curvature), trade 25-delta butterflies. After hedging the top 3 PCs, 95%+ of vol surface risk is neutralized.\n\nStep 3 - Trading Opportunities: Monitor the PC scores daily. If PC2 (skew) is at +2.5 SD (extreme skew steepening), and fundamentals don\'t justify it, sell skew via risk reversals. If PC3 (curvature) is at -2 SD (wings cheap), buy butterflies. These mean-reversion trades exploit the fact that extreme PC moves tend to revert faster than level moves.',
        explanation: 'This is the complete framework that options market makers at firms like Optiver use to manage vol surface risk. The key insight is that PCA transforms a 50-dimensional risk management problem into a 3-dimensional one.',
        solutionSteps: [
          'Compute PCA on 50-dimensional daily IV changes.',
          'Risk = portfolio exposure to each PC × eigenvalue (variance per PC).',
          'PC1 (level) → hedge with ATM straddles.',
          'PC2 (slope) → hedge with risk reversals.',
          'PC3 (curvature) → hedge with butterflies.',
          'Trading: mean-revert extreme PC2/PC3 moves.',
          'Total: 95%+ of risk managed with 3 hedge instruments.',
        ],
      },
      {
        id: 'd3b-interview-02',
        exerciseType: 'scenario',
        difficulty: 'interview',
        topic: 'Covariance Estimation',
        tags: ['shrinkage', 'portfolio-optimization', 'interview'],
        timeEstimateSeconds: 240,
        question: 'You are optimizing a portfolio of options and need a reliable covariance matrix. Compare approaches under different data regimes.',
        scenarios: [
          {
            description: 'Regime A: You have $p = 20$ assets and $n = 500$ observations. The raw sample covariance has $\\kappa = 150$. After Ledoit-Wolf with $\\alpha = 0.15$, what is the approximate new $\\kappa$? Assume $\\lambda_{\\max} = 30$, $\\lambda_{\\min} = 0.2$, $\\mu = 5$.',
            shocks: [{ variable: 'alpha', change: 0.15 }],
            expectedAnswer: 29.8,
            tolerance: 2,
            unit: '',
          },
          {
            description: 'Regime B: Same 20 assets but only $n = 25$ observations (crisis period, limited data). $\\alpha^* = 0.6$ is much higher. Same eigenvalue spread. What is $\\kappa_{\\text{LW}}$ now?',
            shocks: [{ variable: 'alpha', change: 0.6 }],
            expectedAnswer: 4.57,
            tolerance: 0.5,
            unit: '',
          },
        ],
        explanation: 'Regime A: $\\tilde{\\lambda}_{\\max} = 0.15(5) + 0.85(30) = 26.25$, $\\tilde{\\lambda}_{\\min} = 0.15(5) + 0.85(0.2) = 0.92$. $\\kappa = 26.25/0.92 = 28.5$. Regime B: $\\tilde{\\lambda}_{\\max} = 0.6(5) + 0.4(30) = 15$, $\\tilde{\\lambda}_{\\min} = 0.6(5) + 0.4(0.2) = 3.08$. $\\kappa = 15/3.08 = 4.87$. More shrinkage gives better conditioning but more bias.',
        solutionSteps: [
          'Regime A: $\\tilde{\\lambda}_{\\max} = 0.15(5) + 0.85(30) = 0.75 + 25.5 = 26.25$.',
          '$\\tilde{\\lambda}_{\\min} = 0.15(5) + 0.85(0.2) = 0.75 + 0.17 = 0.92$.',
          '$\\kappa_A = 26.25/0.92 \\approx 28.5$.',
          'Regime B: $\\tilde{\\lambda}_{\\max} = 0.6(5) + 0.4(30) = 3.0 + 12.0 = 15.0$.',
          '$\\tilde{\\lambda}_{\\min} = 0.6(5) + 0.4(0.2) = 3.0 + 0.08 = 3.08$.',
          '$\\kappa_B = 15.0/3.08 \\approx 4.87$.',
        ],
      },
      {
        id: 'd3b-interview-03',
        exerciseType: 'free-response',
        difficulty: 'interview',
        topic: 'PCA Limitations',
        tags: ['pca', 'limitations', 'interview'],
        timeEstimateSeconds: 180,
        question: 'An interviewer asks: "What are the limitations of PCA for modeling vol surface dynamics? When would PCA give you misleading results?"',
        modelAnswer: 'Key limitations: (1) PCA assumes linear relationships between vol changes. If vol dynamics are nonlinear (e.g., level and skew have a quadratic relationship), PCA misses this. (2) Stationarity assumption: PCA uses a fixed covariance matrix, but vol surface dynamics change over time. The eigenvectors estimated from calm markets differ from crisis markets. A PCA done on 2019 data would not capture the extreme moves of March 2020. (3) PCA maximizes variance, not trading relevance. The most variable direction may not be the most profitable to trade. (4) Outliers: a few extreme days can dominate the covariance estimate and distort the eigenvectors. (5) Cross-expiry effects: standard PCA treats all strike-expiry points equally, but the dynamics differ across term structure. A per-expiry PCA might be more appropriate. (6) Rotation ambiguity: eigenvectors are only determined up to sign, and closely-spaced eigenvalues create instability in the eigenvector directions.',
        explanation: 'Understanding limitations is as important as understanding the technique. Interviewers want to see that candidates can critically evaluate tools rather than blindly apply them.',
        solutionSteps: [
          'Linearity: PCA captures only linear relationships.',
          'Non-stationarity: eigenvectors change across market regimes.',
          'Variance ≠ relevance: most variable ≠ most profitable.',
          'Outlier sensitivity: extreme days distort covariance estimates.',
          'Cross-expiry heterogeneity: different expiries have different dynamics.',
          'Rotation ambiguity: nearby eigenvalues → unstable eigenvectors.',
        ],
      },
      {
        id: 'd3b-speed-01',
        exerciseType: 'speed-drill',
        difficulty: 'easy',
        topic: 'Quick PCA Calculations',
        tags: ['pca', 'eigenvalues', 'speed'],
        timeEstimateSeconds: 90,
        timeLimitSeconds: 90,
        problems: [
          { prompt: 'Eigenvalues [20, 5, 1]. Total variance = ?', correctAnswer: 26, tolerance: 0 },
          { prompt: 'Same eigenvalues. PC1 variance explained (%) = ?', correctAnswer: 76.9, tolerance: 1 },
          { prompt: 'p = 30 features. Unique covariance entries = p(p+1)/2 = ?', correctAnswer: 465, tolerance: 0 },
          { prompt: 'Condition number: max eigenvalue 50, min eigenvalue 0.5 = ?', correctAnswer: 100, tolerance: 0 },
          { prompt: 'Ledoit-Wolf: alpha=0.5, mu=4, lambda=0.1. Shrunk eigenvalue = ?', correctAnswer: 2.05, tolerance: 0.01 },
        ],
        explanation: 'Quick PCA and covariance calculations. Total variance = trace = sum of eigenvalues. Variance ratio = eigenvalue / total. Unique entries = p(p+1)/2. Shrunk eigenvalue = alpha*mu + (1-alpha)*lambda.',
        solutionSteps: [
          'Total = $20 + 5 + 1 = 26$.',
          'PC1 = $20/26 = 76.9\\%$.',
          '$30 \\times 31/2 = 465$.',
          '$\\kappa = 50/0.5 = 100$.',
          '$\\tilde{\\lambda} = 0.5(4) + 0.5(0.1) = 2.0 + 0.05 = 2.05$.',
        ],
      },
    ],
    flashcards: [
      { id: 'd3b-f01', front: 'Why does the sample covariance matrix fail when $p \\approx n$?', back: 'The rank of $\\hat{\\Sigma}$ is at most $\\min(n-1, p)$. When $p \\geq n$, it is singular. Even when $p < n$ but $p/n > 0.1$, eigenvalues are severely distorted (smallest biased down, largest biased up).', tags: ['covariance', 'dimensionality'] },
      { id: 'd3b-f02', front: 'What is the spectral decomposition of a covariance matrix?', back: '$\\Sigma = V\\Lambda V^T = \\sum_{j=1}^p \\lambda_j v_j v_j^T$. $\\lambda_j$ = eigenvalue (variance in direction $v_j$). Eigenvectors $v_j$ are orthonormal principal directions.', tags: ['pca', 'spectral'] },
      { id: 'd3b-f03', front: 'How is PCA projection computed?', back: 'Center data: $\\tilde{X} = X - \\bar{x}$. Project: $Z = \\tilde{X} V_k$, where $V_k$ contains top $k$ eigenvectors. Scores $z_{ij} = v_j^T(x_i - \\bar{x})$ have variance $\\lambda_j$.', tags: ['pca', 'projection'] },
      { id: 'd3b-f04', front: 'Fraction of variance explained by top $k$ PCs?', back: '$\\frac{\\sum_{j=1}^k \\lambda_j}{\\sum_{j=1}^p \\lambda_j}$. For vol surfaces: $k=3$ typically gives 95%+.', tags: ['pca', 'variance-ratio'] },
      { id: 'd3b-f05', front: 'What are the 3 PCs of a vol surface?', back: 'PC1 = Level (parallel shift, ~85-90%). PC2 = Slope/Skew (tilt, ~5-8%). PC3 = Curvature/Butterfly (~2-3%). Together explain 95%+ of variation.', tags: ['pca', 'vol-surface'] },
      { id: 'd3b-f06', front: 'What instruments hedge each vol surface PC?', back: 'PC1 (Level): ATM straddles. PC2 (Slope): Risk reversals (buy OTM put, sell OTM call). PC3 (Curvature): Butterflies. These map to Vega, Vanna, and Volga exposures.', tags: ['pca', 'hedging'] },
      { id: 'd3b-f07', front: 'What is the Ledoit-Wolf shrinkage estimator?', back: '$\\hat{\\Sigma}_{LW} = \\alpha \\mu I + (1-\\alpha)\\hat{\\Sigma}$, where $\\mu = \\text{tr}(\\hat{\\Sigma})/p$. Pulls eigenvalues toward their mean, preventing near-zero eigenvalues.', tags: ['shrinkage', 'covariance'] },
      { id: 'd3b-f08', front: 'How does Ledoit-Wolf shrinkage affect the condition number?', back: 'New eigenvalue: $\\tilde{\\lambda}_j = \\alpha\\mu + (1-\\alpha)\\lambda_j$. Min eigenvalue pulled up, max pulled down. $\\kappa$ drops dramatically. The optimal $\\alpha^*$ scales with $p/n$.', tags: ['shrinkage', 'condition-number'] },
      { id: 'd3b-f09', front: 'Rule of thumb: how much data for a good covariance estimate?', back: 'Need $n \\geq 5p$ observations. For $p = 50$ (vol surface): $n \\geq 250$ days (~1 year). With less data, use PCA or shrinkage.', tags: ['covariance', 'sample-size'] },
      { id: 'd3b-f10', front: 'Are principal components guaranteed to be uncorrelated?', back: 'Yes. $\\text{Cov}(z_j, z_k) = v_j^T \\Sigma v_k = \\lambda_k (v_j^T v_k) = 0$ for $j \\neq k$ because eigenvectors are orthogonal.', tags: ['pca', 'correlation'] },
      { id: 'd3b-f11', front: 'What is the reconstruction error when using $k$ PCs?', back: 'Reconstruction error = $\\sum_{j=k+1}^p \\lambda_j / \\sum_{j=1}^p \\lambda_j$. The fraction of variance NOT captured by the top $k$ components.', tags: ['pca', 'reconstruction'] },
      { id: 'd3b-f12', front: 'When should you use PCA vs Ledoit-Wolf vs both?', back: 'PCA alone: when you want to reduce dimensions for modeling (e.g., 3 vol surface factors). Ledoit-Wolf alone: when you need full $p \\times p$ covariance for optimization. Both: factor model (PCA) + shrinkage on residuals — industry standard.', tags: ['pca', 'shrinkage', 'model-selection'] },
    ],
    cheatSheet: [
      { topic: 'Sample Covariance', formula: 'Σ_hat = (1/(n-1)) Σ(xᵢ - x̄)(xᵢ - x̄)ᵀ', description: 'Rank ≤ min(n-1, p); fails when p ≈ n' },
      { topic: 'Spectral Decomposition', formula: 'Σ = VΛVᵀ = Σ λⱼvⱼvⱼᵀ', description: 'Eigenvalues = variances; eigenvectors = principal directions' },
      { topic: 'PCA Projection', formula: 'Z = (X - x̄)Vₖ', description: 'Project p-dim data to k-dim; Z columns are uncorrelated' },
      { topic: 'Variance Ratio', formula: 'VR(k) = Σ₁ᵏ λⱼ / Σ₁ᵖ λⱼ', description: 'Fraction of variance from top k PCs' },
      { topic: 'Vol Surface PCs', formula: 'PC1 ≈ 85%, PC2 ≈ 7%, PC3 ≈ 3%', description: 'Level, Slope, Curvature explain ~95% of IV changes' },
      { topic: 'Ledoit-Wolf', formula: 'Σ_LW = α·(tr(Σ)/p)·I + (1-α)·Σ_hat', description: 'Shrink toward identity target; α∝p/n' },
      { topic: 'Shrunk Eigenvalue', formula: 'λ̃ⱼ = α·μ + (1-α)·λⱼ', description: 'Pulls all eigenvalues toward mean μ = tr/p' },
      { topic: 'Min Data Rule', formula: 'n ≥ 5p', description: 'Minimum observations for reliable covariance estimation' },
    ],
    summary: [
      'Curse of dimensionality: a $p$-dimensional covariance has $p(p+1)/2$ parameters; sample covariance fails when $p/n > 0.2$.',
      'PCA decomposes $\\Sigma = V\\Lambda V^T$: project onto top $k$ eigenvectors to reduce $p$ dimensions to $k$.',
      'Vol surface PCA: Level (PC1, ~85%), Slope (PC2, ~7%), Curvature (PC3, ~3%) explain 95%+ of daily IV changes.',
      'Hedge PC1 with straddles, PC2 with risk reversals, PC3 with butterflies — 3 instruments cover 95% of risk.',
      'Ledoit-Wolf shrinkage: $\\hat{\\Sigma}_{\\text{LW}} = \\alpha \\mu I + (1-\\alpha)\\hat{\\Sigma}$ stabilizes covariance for portfolio optimization.',
      'Best practice: factor model (PCA for dominant factors) + shrinkage on residual covariance.',
    ],
    interactiveTools: ['pca-vol-decomposition', 'ledoit-wolf-shrinkage'],
  },
};

export default day03;
