import { DayContent } from './types';

const day04: DayContent = {
  dayNumber: 4,
  title: 'Black-Scholes Framework I',
  subtitle: 'Natenberg Chapter 18',
  week: 1,
  chapters: ['Chapter 18'],
  estimatedMinutes: 120,
  prerequisites: [1, 2, 3],
  objectives: [
    'State the assumptions underlying the Black-Scholes model',
    'Calculate Black-Scholes call and put prices by hand',
    'Interpret $d_1$ and $d_2$ and their relationship to delta and exercise probability',
    'Understand limiting behavior of BS prices (deep ITM/OTM, extreme vol, time)',
    'Verify that BS prices satisfy put-call parity',
  ],
  theory: {
    sections: [
      {
        title: 'Black-Scholes Assumptions',
        blocks: [
          {
            type: 'text',
            body: 'The Black-Scholes model is built on a set of simplifying assumptions. Understanding these assumptions is critical because every real-world deviation creates trading opportunities (or risks). The model is "wrong" but extraordinarily useful as a common language and starting point.',
          },
          {
            type: 'concept',
            title: 'The Six Key Assumptions',
            body: '1. The stock follows geometric Brownian motion (lognormal returns, constant volatility). 2. No transaction costs or taxes. 3. Continuous trading is possible. 4. The risk-free rate is constant and known. 5. No dividends (or continuous dividend yield). 6. European exercise only. Each assumption that breaks in practice creates a gap between model and reality that traders must manage.',
          },
          {
            type: 'callout',
            variant: 'key-insight',
            body: 'The most important assumption that fails in practice is **constant volatility**. Real-world implied volatility varies by strike (the "smile" or "skew") and by expiration (the term structure). This single failure drives most of the complexity in modern options trading.',
          },
        ],
      },
      {
        title: 'The Black-Scholes Formula',
        blocks: [
          {
            type: 'text',
            body: 'The Black-Scholes formula gives the fair price of a European option as a function of five inputs: spot price $S$, strike $K$, time to expiry $T$, risk-free rate $r$, and volatility $\\sigma$. The formula can be derived via the replicating portfolio argument, risk-neutral pricing, or solving the BS partial differential equation.',
          },
          {
            type: 'formula',
            latex: 'C = S \\cdot N(d_1) - K e^{-rT} \\cdot N(d_2)',
            label: 'Black-Scholes Call Price',
            explanation: 'The call price is the stock price weighted by $N(d_1)$ (the delta) minus the present value of the strike weighted by $N(d_2)$ (the risk-neutral probability of exercise).',
          },
          {
            type: 'formula',
            latex: 'P = K e^{-rT} \\cdot N(-d_2) - S \\cdot N(-d_1)',
            label: 'Black-Scholes Put Price',
            explanation: 'The put formula follows from the call formula and put-call parity: $P = C - S + Ke^{-rT}$.',
          },
          {
            type: 'formula',
            latex: 'd_1 = \\frac{\\ln(S/K) + (r + \\sigma^2/2)T}{\\sigma\\sqrt{T}}',
            label: 'd1',
            explanation: '$d_1$ measures how many standard deviations the log-forward-moneyness is from the strike, adjusted for the convexity of the lognormal distribution.',
          },
          {
            type: 'formula',
            latex: 'd_2 = d_1 - \\sigma\\sqrt{T}',
            label: 'd2',
            explanation: '$d_2 = \\frac{\\ln(S/K) + (r - \\sigma^2/2)T}{\\sigma\\sqrt{T}}$. $N(d_2)$ is the risk-neutral probability that the option finishes in the money.',
          },
          {
            type: 'callout',
            variant: 'tip',
            body: 'Memory aid: $d_1$ has $+\\sigma^2/2$ in the numerator, $d_2$ has $-\\sigma^2/2$. The difference is always $\\sigma\\sqrt{T}$. For ATM options with low rates: $d_1 \\approx +\\sigma\\sqrt{T}/2$ and $d_2 \\approx -\\sigma\\sqrt{T}/2$.',
          },
        ],
      },
      {
        title: 'Interpreting d1 and d2',
        blocks: [
          {
            type: 'text',
            body: 'The terms $N(d_1)$ and $N(d_2)$ have specific, important interpretations that go beyond being "just numbers in a formula."',
          },
          {
            type: 'concept',
            title: 'N(d2): Risk-Neutral Exercise Probability',
            body: '$N(d_2)$ is the probability, under the risk-neutral measure, that the call finishes in the money ($S_T > K$). For a put, the probability of finishing ITM is $N(-d_2)$. This is the exercise probability that matters for pricing.',
          },
          {
            type: 'concept',
            title: 'N(d1): Delta of the Call',
            body: '$N(d_1) = \\Delta_{\\text{call}}$, the number of shares needed to replicate the option. It is also the probability of finishing ITM under a different probability measure (the "stock measure" or "share measure"). $N(d_1)$ is always $\\geq N(d_2)$ because $d_1 \\geq d_2$.',
          },
          {
            type: 'example',
            title: 'Computing BS Price Step by Step',
            problem: '$S = 100$, $K = 100$, $T = 0.25$, $r = 5\\%$, $\\sigma = 20\\%$. Compute the call and put prices.',
            solution: [
              '$d_1 = \\frac{\\ln(100/100) + (0.05 + 0.02)\\times 0.25}{0.20 \\times 0.50} = \\frac{0 + 0.0175}{0.10} = 0.175$',
              '$d_2 = 0.175 - 0.10 = 0.075$',
              '$N(0.175) \\approx 0.5695$, $N(0.075) \\approx 0.5299$',
              '$C = 100 \\times 0.5695 - 100 e^{-0.0125} \\times 0.5299 = 56.95 - 98.76 \\times 0.5299 = 56.95 - 52.33 = 4.62$',
              '$P = C - S + Ke^{-rT} = 4.62 - 100 + 98.76 = 3.38$',
            ],
          },
          {
            type: 'table',
            headers: ['N(z)', 'z=0.00', 'z=0.05', 'z=0.10', 'z=0.15', 'z=0.20', 'z=0.25', 'z=0.50', 'z=1.00'],
            rows: [
              ['N(z)', '0.5000', '0.5199', '0.5398', '0.5596', '0.5793', '0.5987', '0.6915', '0.8413'],
              ['N(-z)', '0.5000', '0.4801', '0.4602', '0.4404', '0.4207', '0.4013', '0.3085', '0.1587'],
            ],
          },
        ],
      },
      {
        title: 'Limiting Behavior of Black-Scholes',
        blocks: [
          {
            type: 'text',
            body: 'Understanding how BS prices behave at extremes builds deep intuition and is a favorite interview topic. Rather than memorizing formulas, think about what happens to $d_1$, $d_2$ and hence $N(d_1)$, $N(d_2)$ in each limit.',
          },
          {
            type: 'table',
            headers: ['Limit', 'Call Price', 'Put Price', 'Intuition'],
            rows: [
              ['$S \\gg K$ (deep ITM call)', '$S - Ke^{-rT}$', '$\\approx 0$', '$d_1, d_2 \\to +\\infty$, so $N(d_1), N(d_2) \\to 1$'],
              ['$S \\ll K$ (deep OTM call)', '$\\approx 0$', '$Ke^{-rT} - S$', '$d_1, d_2 \\to -\\infty$, so $N(d_1), N(d_2) \\to 0$'],
              ['$T \\to 0$', '$\\max(S-K, 0)$', '$\\max(K-S, 0)$', 'No time for volatility; option = intrinsic value'],
              ['$T \\to \\infty$', '$S$ (no divs)', '$Ke^{-rT} \\to 0$', 'Call becomes the stock; put value diminishes via discounting'],
              ['$\\sigma \\to 0$', '$\\max(Se^{rT}-K, 0)e^{-rT}$', '$\\max(K-Se^{rT}, 0)e^{-rT}$', 'Deterministic: option = discounted intrinsic on forward'],
              ['$\\sigma \\to \\infty$', '$S$', '$Ke^{-rT}$', '$d_1 \\to +\\infty$, $d_2 \\to -\\infty$; call = stock, put = PV(strike)'],
            ],
          },
          {
            type: 'callout',
            variant: 'key-insight',
            body: 'The $\\sigma \\to \\infty$ limit is counterintuitive. As vol goes to infinity, $N(d_1) \\to 1$ but $N(d_2) \\to 0$, so the call converges to $S$ (not infinity). The put converges to $Ke^{-rT}$. The option never exceeds the value of its most favorable component.',
          },
        ],
      },
    ],
  },
  exercises: [
    // --- EASY (5) ---
    {
      id: 'd4-bs-01',
      exerciseType: 'numeric',
      difficulty: 'easy',
      topic: 'black-scholes',
      tags: ['bs', 'd1-d2'],
      timeEstimateSeconds: 90,
      question: 'Compute $d_1$ for: $S = 100$, $K = 100$, $T = 1$, $r = 0$, $\\sigma = 20\\%$.',
      correctAnswer: 0.10,
      tolerance: 0.01,
      explanation: '$d_1 = \\frac{\\ln(1) + (0 + 0.02)}{0.20} = \\frac{0.02}{0.20} = 0.10$',
      solutionSteps: [
        '$d_1 = \\frac{\\ln(S/K) + (r + \\sigma^2/2)T}{\\sigma\\sqrt{T}}$',
        '$= \\frac{\\ln(100/100) + (0 + 0.04/2) \\times 1}{0.20 \\times 1}$',
        '$= \\frac{0 + 0.02}{0.20} = 0.10$',
      ],
    },
    {
      id: 'd4-bs-02',
      exerciseType: 'numeric',
      difficulty: 'easy',
      topic: 'black-scholes',
      tags: ['bs', 'd1-d2'],
      timeEstimateSeconds: 60,
      question: 'Given $d_1 = 0.10$, $\\sigma = 20\\%$, $T = 1$, what is $d_2$?',
      correctAnswer: -0.10,
      tolerance: 0.01,
      explanation: '$d_2 = d_1 - \\sigma\\sqrt{T} = 0.10 - 0.20 \\times 1 = -0.10$',
      solutionSteps: [
        '$d_2 = d_1 - \\sigma\\sqrt{T}$',
        '$= 0.10 - 0.20 \\times 1.0 = -0.10$',
      ],
    },
    {
      id: 'd4-bs-03',
      exerciseType: 'multiple-choice',
      difficulty: 'easy',
      topic: 'black-scholes',
      tags: ['bs', 'interpretation'],
      timeEstimateSeconds: 30,
      question: 'In the Black-Scholes formula, $N(d_2)$ represents:',
      options: [
        'The delta of the call option',
        'The risk-neutral probability the call finishes in the money',
        'The real-world probability the call finishes in the money',
        'The gamma of the call option',
      ],
      correctIndex: 1,
      explanation: '$N(d_2)$ is the risk-neutral probability that $S_T > K$. It is NOT the real-world probability (that would use the actual drift $\\mu$ instead of $r$). Delta is $N(d_1)$, not $N(d_2)$.',
      solutionSteps: [
        '$N(d_1) = \\Delta_{\\text{call}}$ (the delta).',
        '$N(d_2) = P^{\\mathbb{Q}}(S_T > K)$ (risk-neutral exercise probability).',
        'The real-world probability uses $\\mu$ in place of $r$ in $d_2$.',
      ],
    },
    {
      id: 'd4-bs-04',
      exerciseType: 'true-false',
      difficulty: 'easy',
      topic: 'black-scholes',
      tags: ['bs', 'assumptions'],
      timeEstimateSeconds: 20,
      statement: 'The Black-Scholes model assumes that volatility is constant over the life of the option.',
      correct: true,
      explanation: 'Constant volatility is one of the six key BS assumptions. In reality, implied volatility varies by strike and expiration (the volatility surface), which is one of the main limitations of the model.',
      solutionSteps: [
        'BS assumes GBM: $dS = \\mu S\\,dt + \\sigma S\\,dW$ with constant $\\sigma$.',
        'In practice, $\\sigma$ varies by strike (skew/smile) and time (term structure).',
        'This assumption failure is the most important in practice.',
      ],
    },
    {
      id: 'd4-bs-05',
      exerciseType: 'true-false',
      difficulty: 'easy',
      topic: 'black-scholes',
      tags: ['bs', 'limits'],
      timeEstimateSeconds: 30,
      statement: 'As volatility goes to infinity, the Black-Scholes call price also goes to infinity.',
      correct: false,
      explanation: 'As $\\sigma \\to \\infty$, $d_1 \\to +\\infty$ and $d_2 \\to -\\infty$, so $N(d_1) \\to 1$ and $N(d_2) \\to 0$. The call converges to $S$, not infinity. The maximum value of a call is the stock price.',
      solutionSteps: [
        'As $\\sigma \\to \\infty$: $d_1 = \\frac{\\ln(S/K) + (r+\\sigma^2/2)T}{\\sigma\\sqrt{T}} \\to +\\infty$ (dominated by $\\sigma^2/2$ in numerator).',
        'But $d_2 = d_1 - \\sigma\\sqrt{T} \\to -\\infty$.',
        '$C = S \\cdot N(d_1) - Ke^{-rT} \\cdot N(d_2) \\to S \\cdot 1 - Ke^{-rT} \\cdot 0 = S$.',
      ],
    },
    // --- MEDIUM (6) ---
    {
      id: 'd4-bs-06',
      exerciseType: 'multi-step',
      difficulty: 'medium',
      topic: 'black-scholes',
      tags: ['bs', 'pricing'],
      timeEstimateSeconds: 180,
      question: 'Compute the BS call and put price for: $S = 50$, $K = 50$, $T = 0.5$, $r = 4\\%$, $\\sigma = 30\\%$. Use $N(0.198) \\approx 0.578$ and $N(-0.014) \\approx 0.494$.',
      steps: [
        {
          prompt: 'What is $d_1$?',
          correctAnswer: 0.198,
          tolerance: 0.005,
          stepExplanation: '$d_1 = \\frac{\\ln(50/50) + (0.04 + 0.045)\\times 0.5}{0.30 \\times 0.7071} = \\frac{0 + 0.0425}{0.2121} = 0.200$',
        },
        {
          prompt: 'What is $d_2$?',
          correctAnswer: -0.014,
          tolerance: 0.005,
          stepExplanation: '$d_2 = 0.200 - 0.30 \\times 0.7071 = 0.200 - 0.212 = -0.012$',
        },
        {
          prompt: 'What is the call price?',
          correctAnswer: 4.39,
          tolerance: 0.15,
          unit: '$',
          stepExplanation: '$C = 50 \\times 0.578 - 50 e^{-0.02} \\times 0.494 = 28.90 - 49.01 \\times 0.494 = 28.90 - 24.21 = 4.69$',
        },
        {
          prompt: 'What is the put price (via parity)?',
          correctAnswer: 3.40,
          tolerance: 0.15,
          unit: '$',
          stepExplanation: '$P = C - S + Ke^{-rT} = 4.69 - 50 + 49.01 = 3.70$',
        },
      ],
      explanation: 'Full BS pricing walkthrough for an ATM option.',
      solutionSteps: [
        '$d_1 = \\frac{\\ln(1) + (0.04 + 0.045) \\times 0.5}{0.30\\sqrt{0.5}} = \\frac{0.0425}{0.2121} = 0.200$',
        '$d_2 = 0.200 - 0.2121 = -0.012$',
        '$N(0.200) \\approx 0.579$, $N(-0.012) \\approx 0.495$',
        '$C = 50(0.579) - 49.01(0.495) = 28.95 - 24.26 = 4.69$',
        '$P = 4.69 - 50 + 49.01 = 3.70$',
      ],
    },
    {
      id: 'd4-bs-07',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'black-scholes',
      tags: ['bs', 'pricing', 'deep-itm'],
      timeEstimateSeconds: 120,
      question: 'Compute the BS call price for a deep ITM call: $S = 150$, $K = 100$, $T = 0.25$, $r = 5\\%$, $\\sigma = 30\\%$. Use $N(2.88) \\approx 0.998$ and $N(2.73) \\approx 0.997$.',
      correctAnswer: 51.24,
      tolerance: 0.3,
      unit: '$',
      explanation: '$d_1 = \\frac{\\ln(1.5) + (0.05+0.045)\\times 0.25}{0.30 \\times 0.50} = \\frac{0.4055 + 0.02375}{0.15} = 2.862$. $d_2 = 2.862 - 0.15 = 2.712$. $C = 150(0.998) - 98.76(0.997) = 149.70 - 98.48 = 51.22$. Close to intrinsic $150 - 98.76 = 51.24$.',
      solutionSteps: [
        '$d_1 = \\frac{\\ln(150/100) + (0.05+0.045)\\times 0.25}{0.15} = \\frac{0.4055+0.02375}{0.15} = 2.86$',
        '$d_2 = 2.86 - 0.15 = 2.71$',
        '$N(2.86) \\approx 0.998$, $N(2.71) \\approx 0.997$',
        '$C = 150(0.998) - 100 e^{-0.0125}(0.997) = 149.70 - 98.48 = 51.22$',
        'Compare to intrinsic value $S - Ke^{-rT} = 150 - 98.76 = 51.24$. Deep ITM call is almost all intrinsic.',
      ],
    },
    {
      id: 'd4-bs-08',
      exerciseType: 'free-response',
      difficulty: 'medium',
      topic: 'black-scholes',
      tags: ['bs', 'interpretation'],
      timeEstimateSeconds: 120,
      question: 'Explain intuitively why $N(d_1) > N(d_2)$ always. What does this mean for the replicating portfolio of a call?',
      modelAnswer: 'Since $d_1 = d_2 + \\sigma\\sqrt{T}$ and $\\sigma\\sqrt{T} > 0$, we have $d_1 > d_2$, so $N(d_1) > N(d_2)$. For the replicating portfolio: the call can be decomposed as holding $N(d_1)$ shares of stock and borrowing $Ke^{-rT} \\cdot N(d_2)$ dollars. Since $N(d_1) > N(d_2)$, the share-weighted probability is higher than the exercise probability. Intuitively, in states where $S_T$ is high (call is ITM), the stock is worth more, so the share-weighted probability gives more weight to high-$S_T$ states. This is why delta exceeds exercise probability.',
      explanation: 'The gap $N(d_1) - N(d_2)$ represents the difference between the share-measure and risk-neutral-measure probabilities of exercise.',
      solutionSteps: [
        '$d_1 = d_2 + \\sigma\\sqrt{T} > d_2$ since $\\sigma\\sqrt{T} > 0$.',
        'Since $N$ is increasing, $N(d_1) > N(d_2)$.',
        '$N(d_1)$: delta (shares to hold in replicating portfolio).',
        '$N(d_2)$: probability of exercise (risk-neutral).',
        'Delta > exercise probability because high-$S$ states are weighted more heavily in the share measure.',
      ],
    },
    {
      id: 'd4-bs-09',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'black-scholes',
      tags: ['bs', 'limits'],
      timeEstimateSeconds: 60,
      question: 'A 1-year ATM call ($S = K = 100$) with $r = 0$ has a BS price of $C = 100 \\cdot [2N(\\sigma/2) - 1]$. For $\\sigma = 40\\%$, compute the call price. Use $N(0.20) \\approx 0.5793$.',
      correctAnswer: 15.86,
      tolerance: 0.2,
      unit: '$',
      explanation: 'With $r = 0$, $S = K$: $d_1 = \\sigma/2 = 0.20$, $d_2 = -0.20$. $C = 100[N(0.20) - N(-0.20)] = 100[0.5793 - 0.4207] = 100 \\times 0.1586 = 15.86$.',
      solutionSteps: [
        'When $r = 0$ and $S = K$: $d_1 = \\sigma\\sqrt{T}/2 = 0.40/2 = 0.20$, $d_2 = -0.20$.',
        '$C = S[N(d_1) - N(d_2)] = 100[N(0.20) - N(-0.20)]$',
        '$= 100[0.5793 - 0.4207] = 100 \\times 0.1586 = 15.86$',
        'Note: this shows ATM option value is roughly proportional to $\\sigma$ for moderate vol levels.',
      ],
    },
    {
      id: 'd4-bs-10',
      exerciseType: 'multiple-choice',
      difficulty: 'medium',
      topic: 'black-scholes',
      tags: ['bs', 'limits'],
      timeEstimateSeconds: 45,
      question: 'As $T \\to 0$ for an in-the-money call ($S > K$), what does the BS price approach?',
      options: [
        '$S$',
        '$S - K$',
        '$S - Ke^{-rT}$',
        '0',
      ],
      correctIndex: 1,
      explanation: 'As $T \\to 0$, $e^{-rT} \\to 1$, so the PV of strike approaches $K$. With $S > K$: $d_1, d_2 \\to +\\infty$, so $N(d_1), N(d_2) \\to 1$. $C \\to S - K$, which is the intrinsic value.',
      solutionSteps: [
        'As $T \\to 0$: $\\sigma\\sqrt{T} \\to 0$ and $Ke^{-rT} \\to K$.',
        'For $S > K$: $\\ln(S/K) > 0$, so $d_1, d_2 \\to +\\infty$.',
        '$N(d_1), N(d_2) \\to 1$.',
        '$C \\to S \\cdot 1 - K \\cdot 1 = S - K$.',
      ],
    },
    {
      id: 'd4-bs-11',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'black-scholes',
      tags: ['bs', 'exercise-probability'],
      timeEstimateSeconds: 90,
      question: 'For $S = 100$, $K = 110$, $T = 1$, $r = 5\\%$, $\\sigma = 25\\%$, what is the risk-neutral probability the call finishes ITM? Use $N(-0.306) \\approx 0.380$.',
      correctAnswer: 38.0,
      tolerance: 1.5,
      unit: '%',
      explanation: '$d_2 = \\frac{\\ln(100/110) + (0.05 - 0.03125)}{0.25} = -0.306$. $N(-0.306) \\approx 0.380$, so about 38% chance of finishing ITM.',
      solutionSteps: [
        '$d_2 = \\frac{\\ln(S/K) + (r - \\sigma^2/2)T}{\\sigma\\sqrt{T}}$',
        '$= \\frac{\\ln(100/110) + (0.05 - 0.03125)}{0.25}$',
        '$= \\frac{-0.0953 + 0.01875}{0.25} = \\frac{-0.0766}{0.25} = -0.306$',
        '$N(d_2) = N(-0.306) \\approx 0.380$',
        'Risk-neutral probability of finishing ITM $\\approx 38.0\\%$.',
      ],
    },
    // --- HARD (5) ---
    {
      id: 'd4-bs-12',
      exerciseType: 'multi-step',
      difficulty: 'hard',
      topic: 'black-scholes',
      tags: ['bs', 'pricing', 'put-call-parity'],
      timeEstimateSeconds: 240,
      question: 'Full BS computation: $S = 80$, $K = 85$, $T = 0.5$, $r = 3\\%$, $\\sigma = 25\\%$. Compute call, put, and verify put-call parity. Use $N(-0.159) \\approx 0.437$ and $N(-0.336) \\approx 0.369$.',
      steps: [
        {
          prompt: 'What is $d_1$?',
          correctAnswer: -0.159,
          tolerance: 0.01,
          stepExplanation: '$d_1 = \\frac{\\ln(80/85) + (0.03 + 0.03125) \\times 0.5}{0.25 \\times 0.7071} = \\frac{-0.0607 + 0.03063}{0.1768} = \\frac{-0.0301}{0.1768} = -0.170$',
        },
        {
          prompt: 'What is $d_2$?',
          correctAnswer: -0.336,
          tolerance: 0.01,
          stepExplanation: '$d_2 = -0.170 - 0.1768 = -0.347$',
        },
        {
          prompt: 'What is the call price?',
          correctAnswer: 3.58,
          tolerance: 0.3,
          unit: '$',
          stepExplanation: '$C = 80 \\times N(-0.170) - 85 e^{-0.015} \\times N(-0.347) = 80(0.433) - 83.73(0.364) = 34.61 - 30.48 = 4.13$',
        },
        {
          prompt: 'What is the put price (verify via parity)?',
          correctAnswer: 6.35,
          tolerance: 0.3,
          unit: '$',
          stepExplanation: '$P = C - S + Ke^{-rT} = 4.13 - 80 + 83.73 = 7.86$. Also directly: $P = 83.73 \\times N(0.347) - 80 \\times N(0.170) = 83.73(0.636) - 80(0.567) = 53.25 - 45.36 = 7.89$.',
        },
      ],
      explanation: 'Full BS pricing for an OTM call / ITM put, verifying internal consistency.',
      solutionSteps: [
        '$d_1 = \\frac{\\ln(80/85) + (0.03 + 0.03125)(0.5)}{0.25\\sqrt{0.5}} = \\frac{-0.0607 + 0.0306}{0.1768} = -0.170$',
        '$d_2 = -0.170 - 0.177 = -0.347$',
        '$C = 80 N(-0.170) - 83.73 N(-0.347)$',
        '$P = C - S + Ke^{-rT}$ (put-call parity verification)',
      ],
    },
    {
      id: 'd4-bs-13',
      exerciseType: 'free-response',
      difficulty: 'hard',
      topic: 'black-scholes',
      tags: ['bs', 'limits'],
      timeEstimateSeconds: 180,
      question: 'Prove that as $\\sigma \\to \\infty$, the BS call price converges to $S$ and the put price converges to $Ke^{-rT}$. Start from the behavior of $d_1$ and $d_2$.',
      modelAnswer: 'As $\\sigma \\to \\infty$: $d_1 = \\frac{\\ln(S/K) + rT}{\\sigma\\sqrt{T}} + \\frac{\\sigma\\sqrt{T}}{2}$. The first term goes to 0 (finite numerator, infinite denominator) while the second term goes to $+\\infty$. So $d_1 \\to +\\infty$ and $N(d_1) \\to 1$. For $d_2 = d_1 - \\sigma\\sqrt{T}$: as $\\sigma \\to \\infty$, $d_2 \\to -\\infty$ and $N(d_2) \\to 0$. Therefore: $C = SN(d_1) - Ke^{-rT}N(d_2) \\to S(1) - Ke^{-rT}(0) = S$. For the put: $P = C - S + Ke^{-rT} \\to S - S + Ke^{-rT} = Ke^{-rT}$.',
      explanation: 'At infinite vol, the call becomes the stock and the put becomes the bond. This is the maximum possible value for each.',
      solutionSteps: [
        'Write $d_1 = \\frac{\\ln(S/K) + rT}{\\sigma\\sqrt{T}} + \\frac{\\sigma\\sqrt{T}}{2}$',
        'As $\\sigma \\to \\infty$: first term $\\to 0$, second term $\\to +\\infty$. So $d_1 \\to +\\infty$.',
        '$d_2 = d_1 - \\sigma\\sqrt{T} \\to -\\infty$ (the subtracted term dominates).',
        '$C = S \\cdot N(+\\infty) - Ke^{-rT} \\cdot N(-\\infty) = S \\cdot 1 - Ke^{-rT} \\cdot 0 = S$.',
        '$P = C - S + Ke^{-rT} = S - S + Ke^{-rT} = Ke^{-rT}$.',
      ],
    },
    {
      id: 'd4-bs-14',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'black-scholes',
      tags: ['bs', 'atm-approximation'],
      timeEstimateSeconds: 120,
      question: 'A useful approximation for an ATM call ($S = K$) with $r = 0$ is $C \\approx 0.4 \\cdot S \\cdot \\sigma \\cdot \\sqrt{T}$. For $S = K = 100$, $\\sigma = 30\\%$, $T = 0.25$, estimate the call price using this approximation and compare to the exact formula.',
      correctAnswer: 6.0,
      tolerance: 0.3,
      unit: '$',
      explanation: '$C \\approx 0.4 \\times 100 \\times 0.30 \\times 0.50 = 6.00$. The exact BS price (with $r=0$) is $100[N(0.075) - N(-0.075)] = 100[0.530 - 0.470] = 5.99$. The approximation is remarkably accurate for ATM options.',
      solutionSteps: [
        'Approximation: $C \\approx 0.4 S \\sigma \\sqrt{T}$',
        '$= 0.4 \\times 100 \\times 0.30 \\times \\sqrt{0.25} = 0.4 \\times 100 \\times 0.30 \\times 0.50 = 6.00$',
        'Exact: $d_1 = \\sigma\\sqrt{T}/2 = 0.075$, $d_2 = -0.075$.',
        '$C = 100[N(0.075) - N(-0.075)] = 100 \\times 2[N(0.075) - 0.5] \\approx 100 \\times 0.0599 = 5.99$.',
        'The $0.4 S \\sigma \\sqrt{T}$ rule is excellent for ATM, $r \\approx 0$.',
      ],
    },
    {
      id: 'd4-bs-15',
      exerciseType: 'scenario',
      difficulty: 'hard',
      topic: 'black-scholes',
      tags: ['bs', 'sensitivity'],
      timeEstimateSeconds: 120,
      question: 'Base case: ATM call with $S = K = 100$, $T = 0.25$, $r = 0$, $\\sigma = 20\\%$. Using the ATM approximation $C \\approx 0.4 S \\sigma \\sqrt{T}$, compute the price under each scenario.',
      scenarios: [
        {
          description: 'Vol doubles to 40%',
          shocks: [{ variable: 'sigma', change: 20 }],
          expectedAnswer: 8.0,
          tolerance: 0.2,
          unit: '$',
        },
        {
          description: 'Time to expiry doubles to 0.5 years',
          shocks: [{ variable: 'T', change: 0.25 }],
          expectedAnswer: 5.66,
          tolerance: 0.2,
          unit: '$',
        },
        {
          description: 'Stock and strike both move to 200',
          shocks: [{ variable: 'S', change: 100 }],
          expectedAnswer: 8.0,
          tolerance: 0.2,
          unit: '$',
        },
      ],
      explanation: 'The ATM approximation $C \\approx 0.4 S \\sigma \\sqrt{T}$ shows: price is proportional to $S$, $\\sigma$, and $\\sqrt{T}$.',
      solutionSteps: [
        'Base: $0.4 \\times 100 \\times 0.20 \\times 0.50 = \\$4.00$',
        'Vol to 40%: $0.4 \\times 100 \\times 0.40 \\times 0.50 = \\$8.00$ (linear in vol)',
        'T to 0.5: $0.4 \\times 100 \\times 0.20 \\times 0.707 = \\$5.66$ (square root of time)',
        'S to 200: $0.4 \\times 200 \\times 0.20 \\times 0.50 = \\$8.00$ (linear in spot for ATM)',
      ],
    },
    {
      id: 'd4-bs-16',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'black-scholes',
      tags: ['bs', 'dividends'],
      timeEstimateSeconds: 150,
      question: 'Extend BS to continuous dividends: $C = Se^{-qT}N(d_1) - Ke^{-rT}N(d_2)$ where $d_1 = \\frac{\\ln(S/K) + (r - q + \\sigma^2/2)T}{\\sigma\\sqrt{T}}$. For $S = 100$, $K = 100$, $T = 1$, $r = 5\\%$, $q = 2\\%$, $\\sigma = 25\\%$. Compute $d_1$. Use $N(0.19) \\approx 0.575$.',
      correctAnswer: 0.245,
      tolerance: 0.01,
      explanation: '$d_1 = \\frac{\\ln(1) + (0.05 - 0.02 + 0.03125)}{0.25} = \\frac{0.06125}{0.25} = 0.245$.',
      solutionSteps: [
        '$d_1 = \\frac{\\ln(S/K) + (r - q + \\sigma^2/2)T}{\\sigma\\sqrt{T}}$',
        '$= \\frac{\\ln(1) + (0.05 - 0.02 + 0.03125) \\times 1}{0.25 \\times 1}$',
        '$= \\frac{0 + 0.06125}{0.25} = 0.245$',
        '$d_2 = 0.245 - 0.25 = -0.005$',
      ],
    },
    // --- INTERVIEW (3) ---
    {
      id: 'd4-bs-17',
      exerciseType: 'speed-drill',
      difficulty: 'interview',
      topic: 'bs-mental-math',
      tags: ['bs', 'mental-math', 'atm-approximation'],
      timeEstimateSeconds: 90,
      timeLimitSeconds: 90,
      problems: [
        { prompt: 'ATM call, S=100, sigma=20%, T=1yr, r=0. Approx price? (Use 0.4*S*sig*sqrt(T))', correctAnswer: 8.0, tolerance: 0.3 },
        { prompt: 'ATM call, S=100, sigma=40%, T=0.25yr, r=0. Approx price?', correctAnswer: 8.0, tolerance: 0.3 },
        { prompt: 'ATM straddle (C+P), S=100, sigma=20%, T=1yr, r=0. Approx price?', correctAnswer: 16.0, tolerance: 0.6 },
        { prompt: 'Deep ITM call, S=120, K=100, T=0.25, r=4%. Approx price?', correctAnswer: 21.0, tolerance: 0.5 },
        { prompt: 'If ATM call = $8, r=0, S=K=100, what is ATM put?', correctAnswer: 8.0, tolerance: 0.1 },
      ],
      explanation: 'ATM approximation: $C \\approx 0.4 S \\sigma \\sqrt{T}$. Deep ITM: $C \\approx S - Ke^{-rT}$. ATM straddle $\\approx 0.8 S \\sigma \\sqrt{T}$.',
      solutionSteps: [
        '$0.4 \\times 100 \\times 0.20 \\times 1 = 8.0$',
        '$0.4 \\times 100 \\times 0.40 \\times 0.50 = 8.0$',
        'Straddle = $2C = 2 \\times 8.0 = 16.0$ (at $r=0$, $S=K$)',
        'Deep ITM: $C \\approx S - Ke^{-rT} = 120 - 100(0.99) = 21.0$',
        'Put-call parity with $r=0$, $S=K$: $P = C = 8$',
      ],
    },
    {
      id: 'd4-bs-18',
      exerciseType: 'free-response',
      difficulty: 'interview',
      topic: 'black-scholes',
      tags: ['bs', 'interpretation', 'interview'],
      timeEstimateSeconds: 120,
      question: 'An interviewer asks: "Walk me through the Black-Scholes formula for a call. What does each term represent?" Give a concise answer.',
      modelAnswer: '$C = S \\cdot N(d_1) - Ke^{-rT} \\cdot N(d_2)$. The first term, $S \\cdot N(d_1)$, is the expected stock price conditional on the option finishing in the money, weighted by the exercise probability under the stock measure. $N(d_1)$ is the delta: the number of shares in the replicating portfolio. The second term, $Ke^{-rT} \\cdot N(d_2)$, is the present value of the strike times the risk-neutral probability of exercise. So the formula says: call value = (expected receipt if exercised) - (expected payment if exercised), all under risk-neutral pricing. Equivalently, the call is replicated by buying $N(d_1)$ shares and borrowing $Ke^{-rT} \\cdot N(d_2)$ at the risk-free rate.',
      explanation: 'The call is a leveraged position in the stock: long delta shares, short bonds.',
      solutionSteps: [
        '$C = S \\cdot N(d_1) - K e^{-rT} \\cdot N(d_2)$',
        'Term 1: $S \\cdot N(d_1)$ = delta shares of stock in replicating portfolio.',
        'Term 2: $K e^{-rT} \\cdot N(d_2)$ = borrowing (short bond position).',
        '$N(d_1)$ = delta = exercise probability under the share measure.',
        '$N(d_2)$ = risk-neutral probability of exercise.',
        'The call is a leveraged bet: long stock, short bonds.',
      ],
    },
    {
      id: 'd4-bs-19',
      exerciseType: 'numeric',
      difficulty: 'interview',
      topic: 'black-scholes',
      tags: ['bs', 'mental-math'],
      timeEstimateSeconds: 45,
      question: 'Quick estimate: an ATM straddle (call + put, same strike) on a $100 stock with 25% vol and 1 year to expiry. $r = 0$. Approximate the straddle price.',
      correctAnswer: 20.0,
      tolerance: 1.0,
      unit: '$',
      explanation: 'ATM straddle $\\approx 0.8 S \\sigma \\sqrt{T} = 0.8 \\times 100 \\times 0.25 \\times 1 = 20.0$. (Since $C = P$ at $r = 0$, $S = K$, the straddle is $2C \\approx 2 \\times 0.4 S \\sigma \\sqrt{T}$.)',
      solutionSteps: [
        'ATM straddle $\\approx 2C \\approx 2 \\times 0.4 S \\sigma \\sqrt{T}$',
        '$= 0.8 \\times 100 \\times 0.25 \\times 1.0 = \\$20.0$',
        'This is the standard mental-math estimate. The exact BS straddle is close to this.',
      ],
    },
  ],
  cumulativeExercises: [
    {
      id: 'd4-cum-01',
      exerciseType: 'multi-step',
      difficulty: 'medium',
      topic: 'bs-and-parity',
      tags: ['bs', 'put-call-parity'],
      timeEstimateSeconds: 120,
      fromDay: 1,
      question: 'Verify that the BS call and put prices satisfy put-call parity. Use the ATM case: $S = K = 100$, $T = 0.5$, $r = 4\\%$, $\\sigma = 30\\%$.',
      steps: [
        {
          prompt: 'What is $Ke^{-rT}$?',
          correctAnswer: 98.02,
          tolerance: 0.05,
          unit: '$',
          stepExplanation: '$Ke^{-rT} = 100 \\cdot e^{-0.02} = 98.02$',
        },
        {
          prompt: 'If the BS call is $C = 8.81$, what must the put be by parity?',
          correctAnswer: 6.83,
          tolerance: 0.1,
          unit: '$',
          stepExplanation: '$P = C - S + Ke^{-rT} = 8.81 - 100 + 98.02 = 6.83$',
        },
      ],
      explanation: 'Put-call parity must hold for any arbitrage-free pricing model. BS satisfies it by construction.',
      solutionSteps: [
        '$Ke^{-rT} = 100 e^{-0.04 \\times 0.5} = 100 e^{-0.02} = 98.02$',
        '$P = C - S + Ke^{-rT} = 8.81 - 100 + 98.02 = 6.83$',
        'This is guaranteed to match the BS put formula since BS was derived to satisfy parity.',
      ],
    },
    {
      id: 'd4-cum-02',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'bs-and-forward',
      tags: ['bs', 'forward', 'put-call-parity'],
      timeEstimateSeconds: 120,
      fromDay: 1,
      question: 'Show that the BS call - put spread equals the present value of the forward minus strike. For $S = 100$, $K = 95$, $T = 0.5$, $r = 6\\%$. Compute $C - P$ from parity.',
      correctAnswer: 7.82,
      tolerance: 0.1,
      unit: '$',
      explanation: '$C - P = S - Ke^{-rT} = 100 - 95 e^{-0.03} = 7.82$. This equals $(F - K)e^{-rT}$, confirming the connection between forward pricing and put-call parity.',
      solutionSteps: [
        '$C - P = S - Ke^{-rT} = 100 - 95 e^{-0.03} = 100 - 92.18 = 7.82$',
        '$F = Se^{rT} = 100 e^{0.03} = 103.05$',
        '$(F-K)e^{-rT} = (103.05 - 95) e^{-0.03} = 8.05 \\times 0.9704 = 7.81$',
        'These are equal (minor rounding). This shows $C - P = PV(F - K)$.',
      ],
    },
    {
      id: 'd4-cum-03',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'bs-and-ev',
      tags: ['bs', 'ev', 'risk-neutral'],
      timeEstimateSeconds: 90,
      fromDay: 3,
      question: 'Using the BS framework, compute the risk-neutral expected payoff of a 100-strike call when $S = 100$, $T = 1$, $r = 0$, $\\sigma = 20\\%$. Then discount to get the call price. (Hint: $E^{\\mathbb{Q}}[\\max(S_T - K, 0)] = C \\cdot e^{rT}$.)',
      correctAnswer: 7.97,
      tolerance: 0.2,
      unit: '$',
      explanation: 'With $r = 0$: $C = 100[N(0.10) - N(-0.10)] = 100[0.5398 - 0.4602] = 7.97$. The undiscounted expected payoff is also 7.97 (since $r = 0$, no discounting needed).',
      solutionSteps: [
        'With $r = 0$, $S = K = 100$: $d_1 = \\sigma/2 = 0.10$, $d_2 = -0.10$.',
        '$C = 100[N(0.10) - N(-0.10)] = 100[0.5398 - 0.4602] = 7.97$',
        'Since $r = 0$: $E^{\\mathbb{Q}}[\\max(S_T - 100, 0)] = C \\cdot e^{0} = C = 7.97$',
        'The BS price IS the discounted risk-neutral expected payoff (Day 3 connection).',
      ],
    },
  ],
  flashcards: [
    { id: 'd4-f01', front: 'Black-Scholes call formula', back: '$C = S N(d_1) - K e^{-rT} N(d_2)$', tags: ['bs'] },
    { id: 'd4-f02', front: 'Black-Scholes put formula', back: '$P = K e^{-rT} N(-d_2) - S N(-d_1)$', tags: ['bs'] },
    { id: 'd4-f03', front: '$d_1$ formula', back: '$d_1 = \\frac{\\ln(S/K) + (r + \\sigma^2/2)T}{\\sigma\\sqrt{T}}$', tags: ['bs', 'd1-d2'] },
    { id: 'd4-f04', front: '$d_2$ in terms of $d_1$', back: '$d_2 = d_1 - \\sigma\\sqrt{T}$', tags: ['bs', 'd1-d2'] },
    { id: 'd4-f05', front: 'What does $N(d_1)$ represent?', back: 'Delta of the call. Also the risk-neutral exercise probability under the share measure.', tags: ['bs', 'interpretation'] },
    { id: 'd4-f06', front: 'What does $N(d_2)$ represent?', back: 'Risk-neutral probability that the call finishes in the money ($S_T > K$).', tags: ['bs', 'interpretation'] },
    { id: 'd4-f07', front: 'BS call as $\\sigma \\to \\infty$', back: '$C \\to S$ (the maximum value of a call). $N(d_1) \\to 1$, $N(d_2) \\to 0$.', tags: ['bs', 'limits'] },
    { id: 'd4-f08', front: 'BS call as $T \\to 0$ (ITM)', back: '$C \\to \\max(S - K, 0)$ = intrinsic value. No time for vol to matter.', tags: ['bs', 'limits'] },
    { id: 'd4-f09', front: 'ATM call approximation ($r \\approx 0$)', back: '$C \\approx 0.4 S \\sigma \\sqrt{T}$. ATM straddle $\\approx 0.8 S \\sigma \\sqrt{T}$.', tags: ['bs', 'mental-math'] },
    { id: 'd4-f10', front: '6 BS assumptions', back: '1. GBM (lognormal, constant vol). 2. No transaction costs. 3. Continuous trading. 4. Constant risk-free rate. 5. No dividends. 6. European exercise.', tags: ['bs', 'assumptions'] },
    { id: 'd4-f11', front: 'ATM $d_1$ and $d_2$ (when $r = 0$)', back: '$d_1 = \\sigma\\sqrt{T}/2$, $d_2 = -\\sigma\\sqrt{T}/2$. Symmetric around zero.', tags: ['bs', 'd1-d2'] },
    { id: 'd4-f12', front: 'Why is $N(d_1) > N(d_2)$?', back: '$d_1 = d_2 + \\sigma\\sqrt{T}$, so $d_1 > d_2$. Delta exceeds exercise probability because high-$S$ states get more weight.', tags: ['bs', 'interpretation'] },
    { id: 'd4-f13', front: 'BS with continuous dividends', back: 'Replace $S$ with $Se^{-qT}$ and use $r - q$ in $d_1$: $d_1 = \\frac{\\ln(S/K) + (r - q + \\sigma^2/2)T}{\\sigma\\sqrt{T}}$.', tags: ['bs', 'dividends'] },
  ],
  interactiveTools: ['bs-calculator', 'payoff-diagram'],
  cheatSheet: [
    { topic: 'BS Call', formula: 'C = S N(d₁) - Ke⁻ʳᵀ N(d₂)', description: 'European call price' },
    { topic: 'BS Put', formula: 'P = Ke⁻ʳᵀ N(-d₂) - S N(-d₁)', description: 'European put price' },
    { topic: 'd₁', formula: 'd₁ = [ln(S/K) + (r+σ²/2)T] / (σ√T)', description: 'Delta = N(d₁) for calls' },
    { topic: 'd₂', formula: 'd₂ = d₁ - σ√T', description: 'N(d₂) = risk-neutral P(exercise)' },
    { topic: 'ATM Approx', formula: 'C ≈ 0.4 S σ √T', description: 'ATM call with r≈0' },
    { topic: 'ATM Straddle', formula: 'Straddle ≈ 0.8 S σ √T', description: 'ATM straddle with r≈0' },
    { topic: 'σ → ∞', formula: 'C → S, P → Ke⁻ʳᵀ', description: 'Maximum option values' },
    { topic: 'BS + Dividends', formula: 'Replace S with Se⁻ᵠᵀ; use (r-q) in d₁', description: 'Continuous dividend yield q' },
  ],
  summary: [
    'BS formula: $C = SN(d_1) - Ke^{-rT}N(d_2)$, where $d_1, d_2$ depend on $S, K, T, r, \\sigma$',
    '$N(d_1)$ = call delta; $N(d_2)$ = risk-neutral probability of exercise',
    'ATM approximation: $C \\approx 0.4 S \\sigma \\sqrt{T}$ (straddle $\\approx 0.8 S \\sigma \\sqrt{T}$)',
    'Limiting behavior: as $\\sigma \\to \\infty$, call $\\to S$; as $T \\to 0$, option $\\to$ intrinsic',
    'Most critical assumption failure in practice: constant volatility',
  ],
  trackB: {
    title: 'Time Series Forecasting & GARCH',
    subtitle: 'ARMA, ARCH, GARCH(1,1) & EWMA',
    objectives: [
      'Distinguish strict and weak stationarity and explain why returns (not prices) are modeled',
      'Identify AR, MA, and ARMA processes from ACF and PACF signatures',
      'Derive and compute ARCH(1) and GARCH(1,1) conditional variance step by step',
      'Relate EWMA to IGARCH and explain the RiskMetrics lambda = 0.94 convention',
      'Compute multi-step GARCH forecasts, long-run variance, and volatility half-life',
    ],
    theory: {
      sections: [
        {
          title: 'Stationarity & Why It Matters',
          blocks: [
            {
              type: 'text',
              body: 'A time series $\\{X_t\\}$ is **strictly stationary** if the joint distribution of $(X_{t_1}, \\ldots, X_{t_k})$ is the same as $(X_{t_1+h}, \\ldots, X_{t_k+h})$ for all $k, h$. This is too strong for practical use. **Weak (covariance) stationarity** requires only: (1) $\\mathbb{E}[X_t] = \\mu$ (constant mean), (2) $\\text{Var}(X_t) = \\sigma^2$ (constant variance), (3) $\\text{Cov}(X_t, X_{t+h}) = \\gamma(h)$ (autocovariance depends only on lag $h$).',
            },
            {
              type: 'concept',
              title: 'Why Prices Are Not Stationary',
              body: 'Stock prices $S_t$ have a time-varying mean (they trend upward on average) and their variance grows with $t$. The variance of $S_t$ under GBM is $S_0^2 e^{2\\mu t}(e^{\\sigma^2 t} - 1)$, which is unbounded. Log-returns $r_t = \\ln(S_t/S_{t-1})$ are approximately stationary: roughly constant mean $\\mu \\cdot \\Delta t$ and constant variance $\\sigma^2 \\cdot \\Delta t$.',
            },
            {
              type: 'example',
              title: 'Stationarity Test: Intuition',
              problem: 'You have 5 years of daily SPX prices and returns. Describe qualitatively why prices fail stationarity but returns (approximately) satisfy it.',
              solution: [
                'Prices: SPX went from ~2000 to ~4000. The mean clearly changed over time → fails condition (1).',
                'The daily dollar standard deviation also increased proportionally → fails condition (2).',
                'Returns: daily log-returns have mean ≈ 0.04% regardless of year.',
                'Daily return volatility ≈ 1% (annualized ~16%), roughly constant (though it clusters).',
                'Autocovariance of returns at lag $h$ depends only on $h$, not on the time period.',
                'Caveat: return VARIANCES cluster (GARCH effects), so strict stationarity fails, but weak stationarity of returns is a reasonable approximation.',
              ],
            },
            {
              type: 'callout',
              variant: 'key-insight',
              body: 'Stationarity is the foundation of time series modeling. We model returns, not prices. But even returns exhibit "volatility clustering" — large moves follow large moves. This means the CONDITIONAL variance changes over time even though the UNCONDITIONAL variance is constant. GARCH captures this.',
            },
          ],
        },
        {
          title: 'Autocorrelation & ARMA Models',
          blocks: [
            {
              type: 'text',
              body: 'The **autocorrelation function (ACF)** at lag $h$ is $\\rho(h) = \\gamma(h)/\\gamma(0) = \\text{Cor}(X_t, X_{t+h})$. The **partial autocorrelation function (PACF)** at lag $h$ is the correlation between $X_t$ and $X_{t+h}$ after removing the linear dependence on $X_{t+1}, \\ldots, X_{t+h-1}$.',
            },
            {
              type: 'concept',
              title: 'AR(1) Process',
              body: '$X_t = \\phi X_{t-1} + \\varepsilon_t$, where $\\varepsilon_t \\sim WN(0, \\sigma^2)$. Stationary iff $|\\phi| < 1$. ACF: $\\rho(h) = \\phi^h$ (exponential decay). PACF: cuts off after lag 1. Variance: $\\text{Var}(X_t) = \\sigma^2/(1-\\phi^2)$.',
            },
            {
              type: 'formula',
              latex: 'X_t = \\phi X_{t-1} + \\varepsilon_t, \\quad |\\phi| < 1, \\quad \\varepsilon_t \\sim WN(0, \\sigma^2)',
              label: 'AR(1) Process',
              explanation: 'Mean-reverting: if $X_t > 0$ and $\\phi > 0$, the next value is pulled toward zero. Half-life of mean reversion: $h_{1/2} = -\\ln 2/\\ln|\\phi|$.',
            },
            {
              type: 'concept',
              title: 'MA(1) Process',
              body: '$X_t = \\varepsilon_t + \\theta \\varepsilon_{t-1}$. Always stationary (finite memory). ACF: $\\rho(1) = \\theta/(1+\\theta^2)$, $\\rho(h) = 0$ for $h > 1$ (cuts off). PACF: exponential decay.',
            },
            {
              type: 'table',
              headers: ['Model', 'ACF Pattern', 'PACF Pattern', 'Parameters'],
              rows: [
                ['AR($p$)', 'Exponential/oscillating decay', 'Cuts off after lag $p$', '$\\phi_1, \\ldots, \\phi_p, \\sigma^2$'],
                ['MA($q$)', 'Cuts off after lag $q$', 'Exponential/oscillating decay', '$\\theta_1, \\ldots, \\theta_q, \\sigma^2$'],
                ['ARMA($p,q$)', 'Exponential decay after lag $q$', 'Exponential decay after lag $p$', '$\\phi_1, \\ldots, \\phi_p, \\theta_1, \\ldots, \\theta_q, \\sigma^2$'],
              ],
            },
            {
              type: 'example',
              title: 'Identifying an AR(1) from ACF/PACF',
              problem: 'A daily return series has ACF: $\\rho(1) = 0.15, \\rho(2) = 0.023, \\rho(3) = 0.003$, and PACF: $\\hat{\\phi}(1) = 0.15, \\hat{\\phi}(2) = 0.001, \\hat{\\phi}(3) = -0.005$. What model is this?',
              solution: [
                'ACF decays exponentially: $0.15, 0.023 \\approx 0.15^2, 0.003 \\approx 0.15^3$. Geometric decay.',
                'PACF cuts off after lag 1: only $\\hat{\\phi}(1) = 0.15$ is significant.',
                'Pattern: exponentially decaying ACF + PACF cutoff at lag 1 = AR(1).',
                'The model is $r_t = 0.15 r_{t-1} + \\varepsilon_t$.',
                'Mean reversion half-life: $-\\ln 2/\\ln(0.15) = 0.693/1.897 = 0.365$ days (very fast).',
              ],
            },
            {
              type: 'callout',
              variant: 'tip',
              body: 'For daily equity returns, the ACF of returns is typically near zero (weak predictability), but the ACF of SQUARED returns is significantly positive at many lags. This is the signature of volatility clustering — returns are uncorrelated but not independent. This motivates ARCH/GARCH models.',
            },
          ],
        },
        {
          title: 'ARCH: Modeling Volatility Clustering',
          blocks: [
            {
              type: 'text',
              body: 'Robert Engle (1982, Nobel Prize 2003) observed that financial return variances are not constant over time: large moves tend to follow large moves (volatility clustering). The **ARCH(1)** model makes the conditional variance depend on the previous squared return: $r_t = \\sigma_t \\varepsilon_t$, where $\\sigma_t^2 = \\omega + \\alpha r_{t-1}^2$ and $\\varepsilon_t \\sim N(0,1)$ i.i.d.',
            },
            {
              type: 'formula',
              latex: '\\sigma_t^2 = \\omega + \\alpha r_{t-1}^2, \\quad \\omega > 0, \\quad 0 \\leq \\alpha < 1',
              label: 'ARCH(1) Conditional Variance',
              explanation: 'After a large return $r_{t-1}$, the variance $\\sigma_t^2$ increases. The unconditional variance is $\\text{Var}(r_t) = \\omega/(1-\\alpha)$.',
            },
            {
              type: 'example',
              title: 'ARCH(1): Step-by-Step Variance Computation',
              problem: 'An ARCH(1) model has $\\omega = 0.00001$ and $\\alpha = 0.3$. Yesterday\'s return was $r_{t-1} = -0.03$ (a 3% drop). Compute today\'s conditional variance and standard deviation.',
              solution: [
                '$\\sigma_t^2 = \\omega + \\alpha r_{t-1}^2 = 0.00001 + 0.3 \\times (-0.03)^2$.',
                '$= 0.00001 + 0.3 \\times 0.0009 = 0.00001 + 0.00027 = 0.00028$.',
                '$\\sigma_t = \\sqrt{0.00028} = 0.01673$ (1.67% daily vol).',
                'Annualized: $0.01673 \\times \\sqrt{252} = 0.2656 = 26.6\\%$.',
                'Compare unconditional vol: $\\sqrt{\\omega/(1-\\alpha)} = \\sqrt{0.00001/0.7} = 0.00378$ daily = 6.0% annual.',
                'Today\'s conditional vol (26.6%) is 4.4x the unconditional vol (6.0%) because of the large move yesterday.',
              ],
            },
            {
              type: 'callout',
              variant: 'key-insight',
              body: 'ARCH captures **fat tails** even with Gaussian innovations: the unconditional distribution of $r_t$ has heavier tails than a normal because the variance varies. The kurtosis of an ARCH(1) process is $3(1-\\alpha^2)/(1-3\\alpha^2)$, which exceeds 3 (the Gaussian value) for any $\\alpha > 0$.',
            },
          ],
        },
        {
          title: 'GARCH(1,1)',
          blocks: [
            {
              type: 'text',
              body: 'ARCH($q$) requires many lags to capture the slow decay of volatility autocorrelation. **GARCH(1,1)** (Bollerslev, 1986) adds a lagged variance term, making it much more parsimonious: just 3 parameters capture the same dynamics that would require ARCH(20+).',
            },
            {
              type: 'formula',
              latex: '\\sigma_t^2 = \\omega + \\alpha \\varepsilon_{t-1}^2 + \\beta \\sigma_{t-1}^2',
              label: 'GARCH(1,1) Conditional Variance',
              explanation: '$\\alpha$ = reaction to news (how much yesterday\'s shock affects today\'s variance). $\\beta$ = persistence (how much yesterday\'s variance carries over). $\\omega$ = baseline variance.',
            },
            {
              type: 'formula',
              latex: 'V_L = \\frac{\\omega}{1 - \\alpha - \\beta}',
              label: 'Long-Run Variance',
              explanation: 'The unconditional variance that $\\sigma_t^2$ reverts to. Requires $\\alpha + \\beta < 1$ for stationarity. $\\sqrt{V_L}$ is the long-run daily volatility.',
            },
            {
              type: 'concept',
              title: 'Persistence',
              body: 'The **persistence** $\\alpha + \\beta$ measures how slowly the conditional variance reverts to $V_L$. When $\\alpha + \\beta$ is close to 1, shocks to variance are very long-lived. Typical values for daily equity returns: $\\alpha \\approx 0.05$-$0.10$, $\\beta \\approx 0.85$-$0.92$, so $\\alpha + \\beta \\approx 0.95$-$0.99$.',
            },
            {
              type: 'example',
              title: 'GARCH(1,1): Complete Variance Path',
              problem: 'GARCH(1,1) parameters: $\\omega = 0.000004$, $\\alpha = 0.08$, $\\beta = 0.90$. Current conditional variance $\\sigma_t^2 = 0.0002$ (daily vol = 1.41%). Yesterday\'s return was $\\varepsilon_t = -0.025$ (2.5% drop). Compute $\\sigma_{t+1}^2$.',
              solution: [
                '$\\sigma_{t+1}^2 = \\omega + \\alpha \\varepsilon_t^2 + \\beta \\sigma_t^2$.',
                '$= 0.000004 + 0.08 \\times (-0.025)^2 + 0.90 \\times 0.0002$.',
                '$= 0.000004 + 0.08 \\times 0.000625 + 0.90 \\times 0.0002$.',
                '$= 0.000004 + 0.00005 + 0.00018 = 0.000234$.',
                '$\\sigma_{t+1} = \\sqrt{0.000234} = 0.01530$ (1.53% daily vol).',
                'Long-run variance: $V_L = 0.000004/(1-0.08-0.90) = 0.000004/0.02 = 0.0002$.',
                'Long-run daily vol = $\\sqrt{0.0002} = 1.41\\%$. Annualized = $1.41\\% \\times \\sqrt{252} = 22.4\\%$.',
                'After the 2.5% shock, vol jumped from 1.41% to 1.53% and will revert back to 1.41%.',
              ],
            },
            {
              type: 'callout',
              variant: 'tip',
              body: 'GARCH(1,1) can be written as $\\sigma_t^2 = V_L(1-\\alpha-\\beta) + \\alpha \\varepsilon_{t-1}^2 + \\beta \\sigma_{t-1}^2$. This makes clear that the variance is a weighted average of: the long-run level ($V_L$, weight $1-\\alpha-\\beta$), yesterday\'s squared shock (weight $\\alpha$), and yesterday\'s variance (weight $\\beta$).',
            },
          ],
        },
        {
          title: 'EWMA as a Special Case',
          blocks: [
            {
              type: 'text',
              body: 'The **Exponentially Weighted Moving Average (EWMA)** is a special case of GARCH(1,1) with $\\omega = 0$ (which forces $\\alpha + \\beta = 1$, i.e., integrated GARCH or IGARCH). This eliminates the mean-reversion property: there is no long-run variance level.',
            },
            {
              type: 'formula',
              latex: '\\sigma_t^2 = \\lambda \\sigma_{t-1}^2 + (1-\\lambda) r_{t-1}^2',
              label: 'EWMA Variance',
              explanation: '$\\lambda \\in (0,1)$ is the decay factor. $\\lambda = 0.94$ is the RiskMetrics standard for daily data. Higher $\\lambda$ = more weight on history (smoother); lower $\\lambda$ = more reactive.',
            },
            {
              type: 'concept',
              title: 'RiskMetrics Convention',
              body: 'J.P. Morgan\'s RiskMetrics system uses EWMA with $\\lambda = 0.94$ for daily variance and $\\lambda = 0.97$ for monthly variance. The effective half-life is $h_{1/2} = -\\ln 2 / \\ln \\lambda$. For $\\lambda = 0.94$: $h_{1/2} = 0.693/0.0619 = 11.2$ days — a shock to variance decays to half its initial impact in about 11 days.',
            },
            {
              type: 'example',
              title: 'EWMA: Computing Variance',
              problem: 'Using EWMA with $\\lambda = 0.94$: current variance estimate $\\sigma_{t-1}^2 = 0.0003$ (daily vol = 1.73%). Today\'s return is $r_{t-1} = 0.04$ (4% move). Compute $\\sigma_t^2$.',
              solution: [
                '$\\sigma_t^2 = \\lambda \\sigma_{t-1}^2 + (1-\\lambda) r_{t-1}^2$.',
                '$= 0.94 \\times 0.0003 + 0.06 \\times 0.04^2$.',
                '$= 0.000282 + 0.06 \\times 0.0016$.',
                '$= 0.000282 + 0.000096 = 0.000378$.',
                '$\\sigma_t = \\sqrt{0.000378} = 0.01944$ (1.94% daily vol).',
                'The 4% shock increased daily vol from 1.73% to 1.94% — a 12% increase.',
              ],
            },
            {
              type: 'table',
              headers: ['Property', 'GARCH(1,1)', 'EWMA (IGARCH)'],
              rows: [
                ['Parameters', '$\\omega, \\alpha, \\beta$ (3)', '$\\lambda$ only (1)'],
                ['Stationarity', '$\\alpha + \\beta < 1$', '$\\alpha + \\beta = 1$ (unit root in variance)'],
                ['Long-run variance', '$V_L = \\omega/(1-\\alpha-\\beta)$', 'Does not exist'],
                ['Mean reversion', 'Yes: variance reverts to $V_L$', 'No: shocks persist forever'],
                ['Forecast convergence', 'Multi-step forecasts → $V_L$', 'Multi-step forecasts stay at current level'],
                ['Use case', 'Medium/long-term vol modeling', 'Short-term risk management (RiskMetrics)'],
              ],
            },
          ],
        },
        {
          title: 'Multi-Step Forecasting',
          blocks: [
            {
              type: 'text',
              body: 'For GARCH(1,1), the $h$-step-ahead variance forecast from time $t$ is given by the formula below. The forecast converges to the long-run variance $V_L$ as $h \\to \\infty$ (since $(\\alpha + \\beta)^{h-1} \\to 0$ when $\\alpha + \\beta < 1$).',
            },
            {
              type: 'formula',
              latex: '\\sigma^2_{t+h|t} = V_L + (\\alpha + \\beta)^{h-1}(\\sigma^2_{t+1|t} - V_L)',
              label: 'GARCH Multi-Step Forecast',
              explanation: 'The forecast is a weighted average of the 1-step forecast and the long-run variance, with weight $(\\alpha+\\beta)^{h-1}$ decaying toward the long-run level.',
            },
            {
              type: 'formula',
              latex: 'h_{1/2} = \\frac{\\ln 2}{\\ln(1/(\\alpha + \\beta))} = \\frac{\\ln 2}{-\\ln(\\alpha + \\beta)}',
              label: 'Variance Half-Life',
              explanation: 'The number of periods for a variance shock to decay to half its initial magnitude. For $\\alpha + \\beta = 0.98$: $h_{1/2} = \\ln 2/0.0202 = 34.3$ days.',
            },
            {
              type: 'example',
              title: 'Multi-Step GARCH Forecast & Option Pricing',
              problem: 'GARCH(1,1): $\\alpha = 0.06, \\beta = 0.92, \\omega = 0.000003$. Current 1-step forecast: $\\sigma^2_{t+1|t} = 0.0004$ (daily vol = 2%). Compute the 30-day average variance forecast (for pricing a 1-month option).',
              solution: [
                'Long-run variance: $V_L = \\omega/(1-\\alpha-\\beta) = 0.000003/0.02 = 0.00015$.',
                'Persistence: $\\alpha + \\beta = 0.98$.',
                'Term structure: $\\sigma^2_{t+h|t} = 0.00015 + 0.98^{h-1}(0.0004 - 0.00015) = 0.00015 + 0.98^{h-1} \\times 0.00025$.',
                'Average variance over 30 days: $\\bar{\\sigma}^2 = \\frac{1}{30}\\sum_{h=1}^{30} \\sigma^2_{t+h|t}$.',
                '$= V_L + \\frac{0.00025}{30}\\sum_{h=0}^{29} 0.98^h = 0.00015 + \\frac{0.00025}{30} \\cdot \\frac{1-0.98^{30}}{1-0.98}$.',
                '$0.98^{30} = 0.5455$. Geometric sum $= (1-0.5455)/0.02 = 22.73$.',
                '$\\bar{\\sigma}^2 = 0.00015 + 0.00025 \\times 22.73/30 = 0.00015 + 0.000190 = 0.000340$.',
                'Average daily vol = $\\sqrt{0.000340} = 1.84\\%$. Annualized = $29.3\\%$.',
                'This is the GARCH term-structure of vol: current vol (2%) decays toward long-run (1.22%), giving 1-month average of 1.84%.',
              ],
            },
            {
              type: 'callout',
              variant: 'key-insight',
              body: 'The GARCH term structure of volatility directly connects to option pricing. When current vol is ABOVE long-run vol, the term structure of GARCH-implied vol is **downward-sloping** (short-term options are priced higher than long-term). When current vol is BELOW long-run, it is **upward-sloping**. This maps to the observed VIX futures term structure in contango vs. backwardation.',
            },
            {
              type: 'interactive',
              tool: 'garch-forecaster',
              defaultParams: { alpha: 0.06, beta: 0.92, omega: 0.000003, horizonDays: 30 },
            },
          ],
        },
      ],
    },
    exercises: [
      {
        id: 'd4b-stat-01',
        exerciseType: 'true-false',
        difficulty: 'easy',
        topic: 'Stationarity',
        tags: ['stationarity', 'returns'],
        timeEstimateSeconds: 45,
        statement: 'Stock prices are weakly stationary because their expected value is the current price.',
        correct: false,
        explanation: 'Stock prices are NOT stationary. Their mean $\\mathbb{E}[S_t] = S_0 e^{\\mu t}$ grows over time (violating constant mean), and their variance $\\text{Var}(S_t) \\propto e^{2\\mu t}(e^{\\sigma^2 t}-1)$ also grows (violating constant variance). Log-returns are approximately stationary.',
        solutionSteps: [
          'For weak stationarity: need constant mean and constant variance.',
          '$\\mathbb{E}[S_t] = S_0 e^{\\mu t}$: depends on $t$ → non-constant mean.',
          '$\\text{Var}(S_t) = S_0^2 e^{2\\mu t}(e^{\\sigma^2 t} - 1)$: grows with $t$ → non-constant variance.',
          'Both conditions violated → prices are NOT stationary.',
        ],
      },
      {
        id: 'd4b-stat-02',
        exerciseType: 'multiple-choice',
        difficulty: 'easy',
        topic: 'Stationarity',
        tags: ['stationarity', 'volatility-clustering'],
        timeEstimateSeconds: 60,
        question: 'Daily equity returns often exhibit: low autocorrelation in returns but high autocorrelation in squared returns. This is evidence of:',
        options: [
          'Non-stationarity',
          'Volatility clustering (ARCH effects)',
          'A unit root in prices',
          'Negative serial correlation',
        ],
        correctIndex: 1,
        explanation: 'Returns being uncorrelated ($\\rho(h) \\approx 0$) means returns are unpredictable. But squared returns being autocorrelated ($\\rho_{r^2}(h) > 0$) means the MAGNITUDE of returns is predictable — large moves follow large moves. This is volatility clustering, the hallmark of ARCH/GARCH effects.',
        solutionSteps: [
          '$\\rho_{r}(h) \\approx 0$: returns themselves are nearly unpredictable.',
          '$\\rho_{r^2}(h) > 0$: squared returns are autocorrelated.',
          'This means: variance changes over time, but in a predictable way.',
          'This is the signature of ARCH/GARCH effects = volatility clustering.',
        ],
      },
      {
        id: 'd4b-ar-01',
        exerciseType: 'multiple-choice',
        difficulty: 'easy',
        topic: 'AR Process',
        tags: ['ar', 'acf', 'pacf'],
        timeEstimateSeconds: 60,
        question: 'An AR(2) process has PACF that:',
        options: [
          'Decays exponentially to zero',
          'Cuts off after lag 2 (zero for $h > 2$)',
          'Alternates between positive and negative values',
          'Has all values equal to zero',
        ],
        correctIndex: 1,
        explanation: 'The PACF of an AR($p$) process cuts off after lag $p$. For AR(2), $\\hat{\\phi}(1)$ and $\\hat{\\phi}(2)$ are non-zero, but $\\hat{\\phi}(h) = 0$ for all $h > 2$. The ACF of an AR(2) process decays exponentially (or oscillates).',
        solutionSteps: [
          'AR($p$) identification: PACF cuts off after lag $p$.',
          'AR(2): PACF non-zero at lags 1 and 2, zero after.',
          'ACF of AR(2): decays exponentially or with damped oscillation.',
          'This is the key identification tool: PACF cutoff → AR order.',
        ],
      },
      {
        id: 'd4b-arch-01',
        exerciseType: 'numeric',
        difficulty: 'easy',
        topic: 'ARCH(1)',
        tags: ['arch', 'conditional-variance'],
        timeEstimateSeconds: 90,
        question: 'ARCH(1) with $\\omega = 0.00002$ and $\\alpha = 0.25$. Yesterday\'s return was $r_{t-1} = -0.02$ (2% drop). What is today\'s conditional daily volatility $\\sigma_t$?',
        correctAnswer: 0.01095,
        tolerance: 0.0005,
        explanation: '$\\sigma_t^2 = \\omega + \\alpha r_{t-1}^2 = 0.00002 + 0.25 \\times 0.0004 = 0.00002 + 0.0001 = 0.00012$. $\\sigma_t = \\sqrt{0.00012} = 0.01095$ (1.095% daily vol).',
        solutionSteps: [
          '$r_{t-1}^2 = (-0.02)^2 = 0.0004$.',
          '$\\sigma_t^2 = 0.00002 + 0.25 \\times 0.0004 = 0.00002 + 0.0001 = 0.00012$.',
          '$\\sigma_t = \\sqrt{0.00012} = 0.01095$.',
          'Annualized: $0.01095 \\times \\sqrt{252} = 17.4\\%$.',
        ],
      },
      {
        id: 'd4b-garch-01',
        exerciseType: 'multi-step',
        difficulty: 'medium',
        topic: 'GARCH(1,1)',
        tags: ['garch', 'conditional-variance'],
        timeEstimateSeconds: 180,
        question: 'GARCH(1,1): $\\omega = 0.000005$, $\\alpha = 0.07$, $\\beta = 0.90$. Current $\\sigma_t^2 = 0.00025$. Today\'s return is $\\varepsilon_t = 0.035$ (3.5% move). Compute $\\sigma_{t+1}^2$ and the long-run variance $V_L$.',
        steps: [
          {
            prompt: 'Compute $\\sigma_{t+1}^2 = \\omega + \\alpha \\varepsilon_t^2 + \\beta \\sigma_t^2$.',
            correctAnswer: 0.000316,
            tolerance: 0.00001,
            unit: '',
            stepExplanation: '$\\sigma_{t+1}^2 = 0.000005 + 0.07 \\times 0.035^2 + 0.90 \\times 0.00025 = 0.000005 + 0.07 \\times 0.001225 + 0.000225 = 0.000005 + 0.0000858 + 0.000225 = 0.000316$.',
          },
          {
            prompt: 'Compute the long-run variance $V_L = \\omega/(1-\\alpha-\\beta)$.',
            correctAnswer: 0.000167,
            tolerance: 0.00001,
            unit: '',
            stepExplanation: '$V_L = 0.000005/(1-0.07-0.90) = 0.000005/0.03 = 0.000167$.',
          },
          {
            prompt: 'Compute the long-run annualized volatility $\\sqrt{252 \\times V_L}$.',
            correctAnswer: 0.205,
            tolerance: 0.005,
            unit: '',
            stepExplanation: '$\\sqrt{252 \\times 0.000167} = \\sqrt{0.04199} = 0.2049 \\approx 20.5\\%$.',
          },
        ],
        explanation: 'After a 3.5% daily move (large shock), variance jumped from 0.00025 to 0.000316 (daily vol from 1.58% to 1.78%). It will gradually revert to $V_L = 0.000167$ (long-run daily vol = 1.29%, annualized 20.5%).',
        solutionSteps: [
          '$\\varepsilon_t^2 = 0.035^2 = 0.001225$.',
          '$\\sigma_{t+1}^2 = 0.000005 + 0.07(0.001225) + 0.90(0.00025) = 0.000316$.',
          '$V_L = 0.000005/0.03 = 0.000167$.',
          'Long-run daily vol = $1.29\\%$, annualized = $20.5\\%$.',
          'Current vol elevated: $\\sigma_{t+1}/\\sqrt{V_L} = 1.78/1.29 = 1.38\\times$ long-run.',
        ],
      },
      {
        id: 'd4b-garch-02',
        exerciseType: 'numeric',
        difficulty: 'medium',
        topic: 'Persistence & Half-Life',
        tags: ['garch', 'persistence', 'half-life'],
        timeEstimateSeconds: 90,
        question: 'A GARCH(1,1) model has $\\alpha = 0.05$ and $\\beta = 0.93$. What is the half-life of a variance shock in trading days?',
        correctAnswer: 34.3,
        tolerance: 1,
        explanation: 'Persistence = $\\alpha + \\beta = 0.98$. Half-life = $\\ln 2 / (-\\ln 0.98) = 0.6931/0.0202 = 34.3$ days.',
        solutionSteps: [
          'Persistence = $\\alpha + \\beta = 0.05 + 0.93 = 0.98$.',
          '$h_{1/2} = \\frac{\\ln 2}{-\\ln(\\alpha + \\beta)} = \\frac{\\ln 2}{-\\ln(0.98)}$.',
          '$\\ln(0.98) = -0.02020$.',
          '$h_{1/2} = 0.6931/0.02020 = 34.3$ days.',
          'A vol shock takes about 7 weeks to decay to half its impact.',
        ],
      },
      {
        id: 'd4b-ewma-01',
        exerciseType: 'numeric',
        difficulty: 'medium',
        topic: 'EWMA',
        tags: ['ewma', 'riskmetrics'],
        timeEstimateSeconds: 90,
        question: 'EWMA with $\\lambda = 0.94$. Previous variance $\\sigma_{t-1}^2 = 0.0002$. Today\'s return $r_{t-1} = -0.015$. What is the new variance $\\sigma_t^2$?',
        correctAnswer: 0.0002015,
        tolerance: 0.000005,
        explanation: '$\\sigma_t^2 = 0.94 \\times 0.0002 + 0.06 \\times (-0.015)^2 = 0.000188 + 0.06 \\times 0.000225 = 0.000188 + 0.0000135 = 0.0002015$.',
        solutionSteps: [
          '$r_{t-1}^2 = (-0.015)^2 = 0.000225$.',
          '$\\sigma_t^2 = 0.94(0.0002) + 0.06(0.000225)$.',
          '$= 0.000188 + 0.0000135 = 0.0002015$.',
          'Daily vol = $\\sqrt{0.0002015} = 1.42\\%$. Only a small increase from $\\sqrt{0.0002} = 1.41\\%$.',
          'The 1.5% return was close to the expected daily move, so vol barely changed.',
        ],
      },
      {
        id: 'd4b-ewma-02',
        exerciseType: 'true-false',
        difficulty: 'medium',
        topic: 'EWMA vs GARCH',
        tags: ['ewma', 'garch', 'mean-reversion'],
        timeEstimateSeconds: 60,
        statement: 'EWMA variance forecasts revert to a long-run mean, just like GARCH(1,1).',
        correct: false,
        explanation: 'EWMA has $\\omega = 0$ and $\\alpha + \\beta = 1$ (unit root in variance). There is no long-run variance $V_L$ to revert to. Multi-step EWMA forecasts stay at the current variance level indefinitely. GARCH(1,1) with $\\alpha + \\beta < 1$ does mean-revert.',
        solutionSteps: [
          'EWMA: $\\sigma_t^2 = \\lambda \\sigma_{t-1}^2 + (1-\\lambda)r_{t-1}^2$ with $\\omega = 0$.',
          'Equivalent to IGARCH: $\\alpha + \\beta = 1$.',
          'Long-run variance: $V_L = \\omega/(1-\\alpha-\\beta) = 0/0$ — undefined.',
          'Multi-step forecast: $\\sigma^2_{t+h|t} = \\sigma^2_{t+1|t}$ for all $h$ (flat term structure).',
          'GARCH: $\\sigma^2_{t+h|t} \\to V_L$ as $h \\to \\infty$ (mean reversion).',
        ],
      },
      {
        id: 'd4b-garch-03',
        exerciseType: 'multi-step',
        difficulty: 'hard',
        topic: 'Multi-Step GARCH Forecast',
        tags: ['garch', 'multi-step', 'term-structure'],
        timeEstimateSeconds: 240,
        question: 'GARCH(1,1): $\\alpha = 0.08$, $\\beta = 0.90$, $\\omega = 0.000003$. Current 1-step forecast $\\sigma^2_{t+1|t} = 0.0005$. Compute the 1-day, 10-day, and 60-day variance forecasts.',
        steps: [
          {
            prompt: 'Compute the long-run variance $V_L$.',
            correctAnswer: 0.00015,
            tolerance: 0.00001,
            unit: '',
            stepExplanation: '$V_L = \\omega/(1-\\alpha-\\beta) = 0.000003/0.02 = 0.00015$.',
          },
          {
            prompt: 'Compute the 10-day forecast: $\\sigma^2_{t+10|t} = V_L + (\\alpha+\\beta)^9 \\times (\\sigma^2_{t+1|t} - V_L)$. Use $(0.98)^9 = 0.8337$.',
            correctAnswer: 0.000442,
            tolerance: 0.00002,
            unit: '',
            stepExplanation: '$\\sigma^2_{t+10|t} = 0.00015 + 0.8337(0.0005 - 0.00015) = 0.00015 + 0.8337 \\times 0.00035 = 0.00015 + 0.000292 = 0.000442$.',
          },
          {
            prompt: 'Compute the 60-day forecast using $(0.98)^{59} = 0.3034$.',
            correctAnswer: 0.000256,
            tolerance: 0.00002,
            unit: '',
            stepExplanation: '$\\sigma^2_{t+60|t} = 0.00015 + 0.3034(0.0005 - 0.00015) = 0.00015 + 0.3034 \\times 0.00035 = 0.00015 + 0.000106 = 0.000256$.',
          },
        ],
        explanation: 'The variance forecast decays from 0.0005 (current, 35.5% annualized) toward $V_L = 0.00015$ (19.4% annualized). At 10 days: 33.3% annualized. At 60 days: 25.4% annualized. This downward-sloping term structure matches a market where current vol is elevated above long-run.',
        solutionSteps: [
          '$V_L = 0.000003/0.02 = 0.00015$.',
          '1-day: $\\sigma^2 = 0.0005$ (given). Daily vol = $2.24\\%$, annualized $35.5\\%$.',
          '10-day: $0.00015 + 0.8337 \\times 0.00035 = 0.000442$. Ann. vol = $33.3\\%$.',
          '60-day: $0.00015 + 0.3034 \\times 0.00035 = 0.000256$. Ann. vol = $25.4\\%$.',
          'Term structure slopes downward: current vol above long-run.',
        ],
      },
      {
        id: 'd4b-garch-04',
        exerciseType: 'numeric',
        difficulty: 'hard',
        topic: 'GARCH Long-Run Vol',
        tags: ['garch', 'long-run', 'annualized-vol'],
        timeEstimateSeconds: 120,
        question: 'A GARCH(1,1) is fitted to daily SPX returns: $\\omega = 2.5 \\times 10^{-6}$, $\\alpha = 0.09$, $\\beta = 0.89$. What is the long-run annualized volatility?',
        correctAnswer: 17.8,
        tolerance: 0.5,
        unit: '%',
        explanation: '$V_L = \\omega/(1-\\alpha-\\beta) = 2.5 \\times 10^{-6}/0.02 = 1.25 \\times 10^{-4}$. Daily vol = $\\sqrt{1.25 \\times 10^{-4}} = 0.01118$. Annualized = $0.01118 \\times \\sqrt{252} = 0.1774 = 17.7\\%$.',
        solutionSteps: [
          '$1 - \\alpha - \\beta = 1 - 0.09 - 0.89 = 0.02$.',
          '$V_L = 2.5 \\times 10^{-6}/0.02 = 1.25 \\times 10^{-4}$.',
          'Daily vol = $\\sqrt{1.25 \\times 10^{-4}} = 0.01118 = 1.12\\%$.',
          'Annualized = $1.12\\% \\times \\sqrt{252} = 1.12\\% \\times 15.87 = 17.8\\%$.',
        ],
      },
      {
        id: 'd4b-ewma-03',
        exerciseType: 'numeric',
        difficulty: 'hard',
        topic: 'EWMA Half-Life',
        tags: ['ewma', 'half-life'],
        timeEstimateSeconds: 60,
        question: 'What is the half-life (in days) of a variance shock under EWMA with $\\lambda = 0.94$?',
        correctAnswer: 11.2,
        tolerance: 0.5,
        explanation: '$h_{1/2} = -\\ln 2/\\ln \\lambda = -0.6931/\\ln(0.94) = -0.6931/(-0.06188) = 11.2$ days.',
        solutionSteps: [
          '$\\ln(0.94) = -0.06188$.',
          '$h_{1/2} = \\ln 2/(-\\ln(0.94)) = 0.6931/0.06188 = 11.2$ days.',
          'A variance shock decays to half in about 11 days ≈ 2.2 weeks.',
        ],
      },
      {
        id: 'd4b-interview-01',
        exerciseType: 'free-response',
        difficulty: 'interview',
        topic: 'GARCH Option Pricing',
        tags: ['garch', 'option-pricing', 'interview'],
        timeEstimateSeconds: 300,
        question: 'You are pricing a 1-month ATM call option on SPX. Your GARCH(1,1) model gives: $\\alpha = 0.07, \\beta = 0.91, \\omega = 0.0000025$. Current 1-day variance forecast is $\\sigma^2_1 = 0.0004$ (daily vol = 2%, annualized ~31.7%). Explain how to use the GARCH term structure to price the option instead of using constant Black-Scholes vol.',
        modelAnswer: 'Step 1: Compute long-run variance: $V_L = 0.0000025/(1-0.07-0.91) = 0.0000025/0.02 = 0.000125$. Long-run daily vol = 1.12%, annualized = 17.8%.\n\nStep 2: Compute the average variance over 22 trading days (1 month): $\\bar{\\sigma}^2 = V_L + \\frac{\\sigma^2_1 - V_L}{22} \\cdot \\frac{1-(\\alpha+\\beta)^{22}}{1-(\\alpha+\\beta)}$. With $\\alpha+\\beta = 0.98$, $0.98^{22} = 0.6412$. Geometric sum = $(1-0.6412)/0.02 = 17.94$. $\\bar{\\sigma}^2 = 0.000125 + (0.0004-0.000125) \\times 17.94/22 = 0.000125 + 0.000275 \\times 0.8155 = 0.000125 + 0.000224 = 0.000349$.\n\nStep 3: Convert to annualized vol for BS: $\\sigma_{\\text{BS}} = \\sqrt{252 \\times \\bar{\\sigma}^2} = \\sqrt{252 \\times 0.000349} = \\sqrt{0.0879} = 29.7\\%$.\n\nStep 4: Price the 1-month ATM call using BS with $\\sigma = 29.7\\%$ instead of the current instantaneous vol of 31.7% or the long-run vol of 17.8%.\n\nKey insight: The GARCH vol term structure is downward-sloping because current vol (31.7%) exceeds long-run (17.8%). The 1-month average (29.7%) is between the two. Using instantaneous vol (31.7%) would OVERPRICE the option; using long-run vol (17.8%) would UNDERPRICE it. GARCH gives the correct average.',
        explanation: 'This question tests the practical application of GARCH to option pricing — the term structure of variance forecasts maps directly to the implied vol term structure observed in markets.',
        solutionSteps: [
          '$V_L = 0.0000025/0.02 = 0.000125$. Long-run ann. vol = $17.8\\%$.',
          'Average variance over 22 days using geometric sum.',
          '$\\bar{\\sigma}^2 \\approx 0.000349$. Average ann. vol = $29.7\\%$.',
          'Use $\\sigma = 29.7\\%$ in Black-Scholes for fair 1-month option price.',
          'This lies between instantaneous vol (31.7%) and long-run vol (17.8%).',
          'The GARCH term structure gives "correct" average vol for each maturity.',
        ],
      },
      {
        id: 'd4b-interview-02',
        exerciseType: 'scenario',
        difficulty: 'interview',
        topic: 'Volatility Forecasting Comparison',
        tags: ['garch', 'ewma', 'interview', 'forecasting'],
        timeEstimateSeconds: 240,
        question: 'Compare EWMA and GARCH variance forecasts after a market crash.',
        scenarios: [
          {
            description: 'Day after a 5% market crash. Both models had $\\sigma^2_{t-1} = 0.0002$ (1.41% daily vol). EWMA ($\\lambda = 0.94$): compute $\\sigma_t^2$.',
            shocks: [{ variable: 'return', change: -0.05 }],
            expectedAnswer: 0.000338,
            tolerance: 0.00002,
            unit: '',
          },
          {
            description: 'GARCH ($\\alpha=0.07, \\beta=0.90, \\omega=0.000004$): compute $\\sigma_t^2$ after the same 5% crash from same starting variance.',
            shocks: [{ variable: 'return', change: -0.05 }],
            expectedAnswer: 0.000359,
            tolerance: 0.00002,
            unit: '',
          },
        ],
        explanation: 'EWMA: $0.94(0.0002) + 0.06(0.0025) = 0.000188 + 0.00015 = 0.000338$. GARCH: $0.000004 + 0.07(0.0025) + 0.90(0.0002) = 0.000004 + 0.000175 + 0.00018 = 0.000359$. Both jump, but the key difference is in multi-step forecasts: EWMA stays at 0.000338 forever; GARCH reverts to $V_L = 0.000004/0.03 = 0.000133$.',
        solutionSteps: [
          '$r_{t-1}^2 = (-0.05)^2 = 0.0025$.',
          'EWMA: $0.94(0.0002) + 0.06(0.0025) = 0.000188 + 0.00015 = 0.000338$.',
          'GARCH: $0.000004 + 0.07(0.0025) + 0.90(0.0002) = 0.000359$.',
          'GARCH produces slightly higher 1-step forecast but reverts to $V_L$.',
          'EWMA: multi-step forecasts stay at 0.000338 (no mean reversion).',
          'For option pricing: GARCH is better because it captures vol term structure.',
        ],
      },
      {
        id: 'd4b-interview-03',
        exerciseType: 'free-response',
        difficulty: 'interview',
        topic: 'Model Selection',
        tags: ['garch', 'arma', 'interview'],
        timeEstimateSeconds: 240,
        question: 'An interviewer asks: "You have 5 years of daily returns data for a liquid equity. Walk me through how you would build a complete time series model for forecasting next-day volatility. What models would you consider, how would you select between them, and what diagnostic checks would you run?"',
        modelAnswer: 'Step 1 - Data preparation: Compute log-returns. Check for stationarity visually and with ADF test. Remove any mean if significant (usually not for daily returns). Step 2 - Preliminary analysis: Plot ACF of returns (should be near zero) and ACF of squared/absolute returns (should show significant autocorrelation, confirming ARCH effects). Run Engle\'s ARCH test: regress $r_t^2$ on $r_{t-1}^2, \\ldots, r_{t-q}^2$ and test joint significance. Step 3 - Model estimation: Fit GARCH(1,1) as baseline — it captures 90%+ of cases. Also fit EGARCH(1,1) for leverage effects (negative returns increase vol more than positive), GJR-GARCH for asymmetry, and EWMA for comparison. Step 4 - Innovation distribution: Compare Gaussian vs Student-t vs skewed-t innovations. Likelihood ratio test or AIC/BIC for selection. Step 5 - Diagnostics: Check standardized residuals $z_t = r_t/\\sigma_t$. Should be: (a) no autocorrelation in $z_t$ or $z_t^2$ (Ljung-Box test), (b) unit variance, (c) look like the assumed distribution (QQ-plot). Step 6 - Out-of-sample evaluation: Rolling window forecast, compare models by MSE of variance forecast vs realized variance (computed from high-frequency data). Use Mincer-Zarnowitz regression: $RV_t = a + b \\sigma^2_{t|t-1} + e_t$. Good forecast has $a=0, b=1$.',
        explanation: 'This is a comprehensive modeling workflow question. The key is demonstrating systematic methodology: explore → model → diagnose → validate out-of-sample.',
        solutionSteps: [
          'Compute log-returns; verify stationarity (ADF test).',
          'Check ARCH effects: ACF of $r_t^2$, Engle\'s ARCH test.',
          'Fit GARCH(1,1) baseline, EGARCH for leverage, GJR-GARCH.',
          'Select innovation distribution: Gaussian vs Student-t (AIC/BIC).',
          'Diagnostics: Ljung-Box on $z_t$ and $z_t^2$, QQ-plot.',
          'Out-of-sample: rolling forecast, Mincer-Zarnowitz regression.',
          'Compare to EWMA benchmark.',
        ],
      },
      {
        id: 'd4b-speed-01',
        exerciseType: 'speed-drill',
        difficulty: 'easy',
        topic: 'Quick GARCH Calculations',
        tags: ['garch', 'ewma', 'speed'],
        timeEstimateSeconds: 120,
        timeLimitSeconds: 120,
        problems: [
          { prompt: 'GARCH: alpha=0.06, beta=0.92. Persistence = ?', correctAnswer: 0.98, tolerance: 0 },
          { prompt: 'Long-run variance: omega=0.00001, 1-alpha-beta=0.02. V_L = ?', correctAnswer: 0.0005, tolerance: 0.00001 },
          { prompt: 'EWMA: lambda=0.94, sigma^2=0.0001, r^2=0.0009. New sigma^2 = ?', correctAnswer: 0.000148, tolerance: 0.000002 },
          { prompt: 'Half-life: alpha+beta=0.95. h = ln2/ln(1/0.95) = ln2/0.0513 ≈ ?', correctAnswer: 13.5, tolerance: 0.5 },
          { prompt: 'Daily vol = 2%. Annualized vol = 2% × sqrt(252) ≈ ?', correctAnswer: 31.7, tolerance: 0.5 },
        ],
        explanation: 'Quick GARCH formulas: persistence = alpha+beta. V_L = omega/(1-alpha-beta). EWMA: lambda*sigma^2 + (1-lambda)*r^2. Half-life = ln2/(-ln(alpha+beta)). Annualize: ×sqrt(252).',
        solutionSteps: [
          'Persistence = $0.06 + 0.92 = 0.98$.',
          '$V_L = 0.00001/0.02 = 0.0005$.',
          'EWMA: $0.94(0.0001) + 0.06(0.0009) = 0.000094 + 0.000054 = 0.000148$.',
          '$h_{1/2} = 0.6931/0.0513 = 13.5$ days.',
          '$2\\% \\times 15.87 = 31.7\\%$.',
        ],
      },
    ],
    flashcards: [
      { id: 'd4b-f01', front: 'Strict vs weak stationarity?', back: 'Strict: full joint distribution invariant to time shifts. Weak (covariance): constant mean, constant variance, autocovariance depends only on lag. Weak is sufficient for ARMA/GARCH modeling.', tags: ['stationarity'] },
      { id: 'd4b-f02', front: 'Why model returns instead of prices?', back: 'Prices are non-stationary (trending mean, growing variance). Log-returns $r_t = \\ln(S_t/S_{t-1})$ are approximately stationary with constant mean and variance.', tags: ['stationarity', 'returns'] },
      { id: 'd4b-f03', front: 'ACF/PACF signature of AR($p$)?', back: 'ACF: exponential (or oscillating) decay. PACF: cuts off after lag $p$. Use PACF cutoff to identify AR order.', tags: ['ar', 'identification'] },
      { id: 'd4b-f04', front: 'ACF/PACF signature of MA($q$)?', back: 'ACF: cuts off after lag $q$. PACF: exponential (or oscillating) decay. Mirror image of AR.', tags: ['ma', 'identification'] },
      { id: 'd4b-f05', front: 'ARCH(1) conditional variance?', back: '$\\sigma_t^2 = \\omega + \\alpha r_{t-1}^2$. Variance depends on previous squared return. Captures volatility clustering. Unconditional variance: $\\omega/(1-\\alpha)$.', tags: ['arch'] },
      { id: 'd4b-f06', front: 'GARCH(1,1) formula and parameters?', back: '$\\sigma_t^2 = \\omega + \\alpha \\varepsilon_{t-1}^2 + \\beta \\sigma_{t-1}^2$. $\\alpha$ = news reaction, $\\beta$ = persistence, $\\omega$ = baseline. Stationary iff $\\alpha + \\beta < 1$.', tags: ['garch'] },
      { id: 'd4b-f07', front: 'GARCH(1,1) long-run variance?', back: '$V_L = \\omega/(1-\\alpha-\\beta)$. The unconditional variance that $\\sigma_t^2$ reverts to. $\\sqrt{252 V_L}$ = long-run annualized vol.', tags: ['garch', 'long-run'] },
      { id: 'd4b-f08', front: 'GARCH variance half-life?', back: '$h_{1/2} = \\ln 2/(-\\ln(\\alpha+\\beta))$. For $\\alpha+\\beta = 0.98$: $h_{1/2} = 34.3$ days. Higher persistence = longer half-life.', tags: ['garch', 'half-life'] },
      { id: 'd4b-f09', front: 'EWMA formula and its relation to GARCH?', back: '$\\sigma_t^2 = \\lambda \\sigma_{t-1}^2 + (1-\\lambda)r_{t-1}^2$. Special case of IGARCH: $\\omega=0$, $\\alpha=1-\\lambda$, $\\beta=\\lambda$, so $\\alpha+\\beta=1$. No mean reversion.', tags: ['ewma', 'garch'] },
      { id: 'd4b-f10', front: 'RiskMetrics $\\lambda$ value and its half-life?', back: '$\\lambda = 0.94$ for daily data. Half-life: $\\ln 2/(-\\ln 0.94) = 11.2$ days. $\\lambda = 0.97$ for monthly data.', tags: ['ewma', 'riskmetrics'] },
      { id: 'd4b-f11', front: 'GARCH multi-step forecast formula?', back: '$\\sigma^2_{t+h|t} = V_L + (\\alpha+\\beta)^{h-1}(\\sigma^2_{t+1|t} - V_L)$. Converges to $V_L$ as $h \\to \\infty$. Rate of convergence determined by persistence $\\alpha+\\beta$.', tags: ['garch', 'forecasting'] },
      { id: 'd4b-f12', front: 'What is volatility clustering?', back: 'Large returns tend to follow large returns (of either sign). ACF of $r_t \\approx 0$ but ACF of $r_t^2 > 0$. Returns are uncorrelated but NOT independent. Captured by ARCH/GARCH.', tags: ['volatility-clustering'] },
    ],
    cheatSheet: [
      { topic: 'AR(1)', formula: 'Xₜ = φXₜ₋₁ + εₜ, |φ|<1', description: 'Stationary if |φ|<1; ACF decays as φʰ; PACF cuts off at lag 1' },
      { topic: 'ARCH(1)', formula: 'σₜ² = ω + αrₜ₋₁²', description: 'Conditional variance depends on last squared return' },
      { topic: 'GARCH(1,1)', formula: 'σₜ² = ω + αεₜ₋₁² + βσₜ₋₁²', description: 'α = news reaction, β = persistence; stationary iff α+β<1' },
      { topic: 'Long-Run Variance', formula: 'V_L = ω/(1-α-β)', description: 'Unconditional variance; σ_LR = √(252·V_L) annualized' },
      { topic: 'Persistence', formula: 'α + β', description: 'Close to 1 = slow mean reversion; typical 0.95-0.99' },
      { topic: 'Half-Life', formula: 'h = ln2/(-ln(α+β))', description: 'Days for variance shock to decay by half' },
      { topic: 'EWMA', formula: 'σₜ² = λσₜ₋₁² + (1-λ)rₜ₋₁²', description: 'IGARCH with ω=0; RiskMetrics λ=0.94; no mean reversion' },
      { topic: 'Multi-Step Forecast', formula: 'σ²ₜ₊ₕ = V_L + (α+β)^(h-1)·(σ²ₜ₊₁ - V_L)', description: 'Converges to V_L; gives vol term structure for option pricing' },
    ],
    summary: [
      'Stock prices are non-stationary; model log-returns $r_t = \\ln(S_t/S_{t-1})$ which are approximately stationary.',
      'ACF of returns $\\approx 0$ but ACF of $r_t^2 > 0$: volatility clustering motivates ARCH/GARCH.',
      'GARCH(1,1): $\\sigma_t^2 = \\omega + \\alpha \\varepsilon_{t-1}^2 + \\beta \\sigma_{t-1}^2$. Long-run variance $V_L = \\omega/(1-\\alpha-\\beta)$.',
      'Persistence $\\alpha + \\beta$ controls mean-reversion speed. Half-life $= \\ln 2/(-\\ln(\\alpha+\\beta))$.',
      'EWMA is IGARCH ($\\omega = 0, \\alpha + \\beta = 1$): no mean reversion, RiskMetrics $\\lambda = 0.94$.',
      'Multi-step forecasts: $\\sigma^2_{t+h} = V_L + (\\alpha+\\beta)^{h-1}(\\sigma^2_{t+1} - V_L)$ — gives the vol term structure for option pricing.',
    ],
    interactiveTools: ['garch-forecaster'],
  },
};

export default day04;
