import { DayContent } from './types';

const day04: DayContent = {
  dayNumber: 4,
  title: 'Black-Scholes Framework I',
  subtitle: 'Natenberg Chapter 18',
  week: 1,
  chapters: ['Chapter 18'],
  estimatedMinutes: 120,
  prerequisites: [1, 2, 3],
  objectives: [
    'State the assumptions underlying the Black-Scholes model',
    'Calculate Black-Scholes call and put prices by hand',
    'Interpret $d_1$ and $d_2$ and their relationship to delta and exercise probability',
    'Understand limiting behavior of BS prices (deep ITM/OTM, extreme vol, time)',
    'Verify that BS prices satisfy put-call parity',
  ],
  theory: {
    sections: [
      {
        title: 'Black-Scholes Assumptions',
        blocks: [
          {
            type: 'text',
            body: 'The Black-Scholes model is built on a set of simplifying assumptions. Understanding these assumptions is critical because every real-world deviation creates trading opportunities (or risks). The model is "wrong" but extraordinarily useful as a common language and starting point.',
          },
          {
            type: 'concept',
            title: 'The Six Key Assumptions',
            body: '1. The stock follows geometric Brownian motion (lognormal returns, constant volatility). 2. No transaction costs or taxes. 3. Continuous trading is possible. 4. The risk-free rate is constant and known. 5. No dividends (or continuous dividend yield). 6. European exercise only. Each assumption that breaks in practice creates a gap between model and reality that traders must manage.',
          },
          {
            type: 'callout',
            variant: 'key-insight',
            body: 'The most important assumption that fails in practice is **constant volatility**. Real-world implied volatility varies by strike (the "smile" or "skew") and by expiration (the term structure). This single failure drives most of the complexity in modern options trading.',
          },
        ],
      },
      {
        title: 'The Black-Scholes Formula',
        blocks: [
          {
            type: 'text',
            body: 'The Black-Scholes formula gives the fair price of a European option as a function of five inputs: spot price $S$, strike $K$, time to expiry $T$, risk-free rate $r$, and volatility $\\sigma$. The formula can be derived via the replicating portfolio argument, risk-neutral pricing, or solving the BS partial differential equation.',
          },
          {
            type: 'formula',
            latex: 'C = S \\cdot N(d_1) - K e^{-rT} \\cdot N(d_2)',
            label: 'Black-Scholes Call Price',
            explanation: 'The call price is the stock price weighted by $N(d_1)$ (the delta) minus the present value of the strike weighted by $N(d_2)$ (the risk-neutral probability of exercise).',
          },
          {
            type: 'formula',
            latex: 'P = K e^{-rT} \\cdot N(-d_2) - S \\cdot N(-d_1)',
            label: 'Black-Scholes Put Price',
            explanation: 'The put formula follows from the call formula and put-call parity: $P = C - S + Ke^{-rT}$.',
          },
          {
            type: 'formula',
            latex: 'd_1 = \\frac{\\ln(S/K) + (r + \\sigma^2/2)T}{\\sigma\\sqrt{T}}',
            label: 'd1',
            explanation: '$d_1$ measures how many standard deviations the log-forward-moneyness is from the strike, adjusted for the convexity of the lognormal distribution.',
          },
          {
            type: 'formula',
            latex: 'd_2 = d_1 - \\sigma\\sqrt{T}',
            label: 'd2',
            explanation: '$d_2 = \\frac{\\ln(S/K) + (r - \\sigma^2/2)T}{\\sigma\\sqrt{T}}$. $N(d_2)$ is the risk-neutral probability that the option finishes in the money.',
          },
          {
            type: 'callout',
            variant: 'tip',
            body: 'Memory aid: $d_1$ has $+\\sigma^2/2$ in the numerator, $d_2$ has $-\\sigma^2/2$. The difference is always $\\sigma\\sqrt{T}$. For ATM options with low rates: $d_1 \\approx +\\sigma\\sqrt{T}/2$ and $d_2 \\approx -\\sigma\\sqrt{T}/2$.',
          },
        ],
      },
      {
        title: 'Interpreting d1 and d2',
        blocks: [
          {
            type: 'text',
            body: 'The terms $N(d_1)$ and $N(d_2)$ have specific, important interpretations that go beyond being "just numbers in a formula."',
          },
          {
            type: 'concept',
            title: 'N(d2): Risk-Neutral Exercise Probability',
            body: '$N(d_2)$ is the probability, under the risk-neutral measure, that the call finishes in the money ($S_T > K$). For a put, the probability of finishing ITM is $N(-d_2)$. This is the exercise probability that matters for pricing.',
          },
          {
            type: 'concept',
            title: 'N(d1): Delta of the Call',
            body: '$N(d_1) = \\Delta_{\\text{call}}$, the number of shares needed to replicate the option. It is also the probability of finishing ITM under a different probability measure (the "stock measure" or "share measure"). $N(d_1)$ is always $\\geq N(d_2)$ because $d_1 \\geq d_2$.',
          },
          {
            type: 'example',
            title: 'Computing BS Price Step by Step',
            problem: '$S = 100$, $K = 100$, $T = 0.25$, $r = 5\\%$, $\\sigma = 20\\%$. Compute the call and put prices.',
            solution: [
              '$d_1 = \\frac{\\ln(100/100) + (0.05 + 0.02)\\times 0.25}{0.20 \\times 0.50} = \\frac{0 + 0.0175}{0.10} = 0.175$',
              '$d_2 = 0.175 - 0.10 = 0.075$',
              '$N(0.175) \\approx 0.5695$, $N(0.075) \\approx 0.5299$',
              '$C = 100 \\times 0.5695 - 100 e^{-0.0125} \\times 0.5299 = 56.95 - 98.76 \\times 0.5299 = 56.95 - 52.33 = 4.62$',
              '$P = C - S + Ke^{-rT} = 4.62 - 100 + 98.76 = 3.38$',
            ],
          },
          {
            type: 'table',
            headers: ['N(z)', 'z=0.00', 'z=0.05', 'z=0.10', 'z=0.15', 'z=0.20', 'z=0.25', 'z=0.50', 'z=1.00'],
            rows: [
              ['N(z)', '0.5000', '0.5199', '0.5398', '0.5596', '0.5793', '0.5987', '0.6915', '0.8413'],
              ['N(-z)', '0.5000', '0.4801', '0.4602', '0.4404', '0.4207', '0.4013', '0.3085', '0.1587'],
            ],
          },
        ],
      },
      {
        title: 'Limiting Behavior of Black-Scholes',
        blocks: [
          {
            type: 'text',
            body: 'Understanding how BS prices behave at extremes builds deep intuition and is a favorite interview topic. Rather than memorizing formulas, think about what happens to $d_1$, $d_2$ and hence $N(d_1)$, $N(d_2)$ in each limit.',
          },
          {
            type: 'table',
            headers: ['Limit', 'Call Price', 'Put Price', 'Intuition'],
            rows: [
              ['$S \\gg K$ (deep ITM call)', '$S - Ke^{-rT}$', '$\\approx 0$', '$d_1, d_2 \\to +\\infty$, so $N(d_1), N(d_2) \\to 1$'],
              ['$S \\ll K$ (deep OTM call)', '$\\approx 0$', '$Ke^{-rT} - S$', '$d_1, d_2 \\to -\\infty$, so $N(d_1), N(d_2) \\to 0$'],
              ['$T \\to 0$', '$\\max(S-K, 0)$', '$\\max(K-S, 0)$', 'No time for volatility; option = intrinsic value'],
              ['$T \\to \\infty$', '$S$ (no divs)', '$Ke^{-rT} \\to 0$', 'Call becomes the stock; put value diminishes via discounting'],
              ['$\\sigma \\to 0$', '$\\max(Se^{rT}-K, 0)e^{-rT}$', '$\\max(K-Se^{rT}, 0)e^{-rT}$', 'Deterministic: option = discounted intrinsic on forward'],
              ['$\\sigma \\to \\infty$', '$S$', '$Ke^{-rT}$', '$d_1 \\to +\\infty$, $d_2 \\to -\\infty$; call = stock, put = PV(strike)'],
            ],
          },
          {
            type: 'callout',
            variant: 'key-insight',
            body: 'The $\\sigma \\to \\infty$ limit is counterintuitive. As vol goes to infinity, $N(d_1) \\to 1$ but $N(d_2) \\to 0$, so the call converges to $S$ (not infinity). The put converges to $Ke^{-rT}$. The option never exceeds the value of its most favorable component.',
          },
        ],
      },
    ],
  },
  exercises: [
    // --- EASY (5) ---
    {
      id: 'd4-bs-01',
      exerciseType: 'numeric',
      difficulty: 'easy',
      topic: 'black-scholes',
      tags: ['bs', 'd1-d2'],
      timeEstimateSeconds: 90,
      question: 'Compute $d_1$ for: $S = 100$, $K = 100$, $T = 1$, $r = 0$, $\\sigma = 20\\%$.',
      correctAnswer: 0.10,
      tolerance: 0.01,
      explanation: '$d_1 = \\frac{\\ln(1) + (0 + 0.02)}{0.20} = \\frac{0.02}{0.20} = 0.10$',
      solutionSteps: [
        '$d_1 = \\frac{\\ln(S/K) + (r + \\sigma^2/2)T}{\\sigma\\sqrt{T}}$',
        '$= \\frac{\\ln(100/100) + (0 + 0.04/2) \\times 1}{0.20 \\times 1}$',
        '$= \\frac{0 + 0.02}{0.20} = 0.10$',
      ],
    },
    {
      id: 'd4-bs-02',
      exerciseType: 'numeric',
      difficulty: 'easy',
      topic: 'black-scholes',
      tags: ['bs', 'd1-d2'],
      timeEstimateSeconds: 60,
      question: 'Given $d_1 = 0.10$, $\\sigma = 20\\%$, $T = 1$, what is $d_2$?',
      correctAnswer: -0.10,
      tolerance: 0.01,
      explanation: '$d_2 = d_1 - \\sigma\\sqrt{T} = 0.10 - 0.20 \\times 1 = -0.10$',
      solutionSteps: [
        '$d_2 = d_1 - \\sigma\\sqrt{T}$',
        '$= 0.10 - 0.20 \\times 1.0 = -0.10$',
      ],
    },
    {
      id: 'd4-bs-03',
      exerciseType: 'multiple-choice',
      difficulty: 'easy',
      topic: 'black-scholes',
      tags: ['bs', 'interpretation'],
      timeEstimateSeconds: 30,
      question: 'In the Black-Scholes formula, $N(d_2)$ represents:',
      options: [
        'The delta of the call option',
        'The risk-neutral probability the call finishes in the money',
        'The real-world probability the call finishes in the money',
        'The gamma of the call option',
      ],
      correctIndex: 1,
      explanation: '$N(d_2)$ is the risk-neutral probability that $S_T > K$. It is NOT the real-world probability (that would use the actual drift $\\mu$ instead of $r$). Delta is $N(d_1)$, not $N(d_2)$.',
      solutionSteps: [
        '$N(d_1) = \\Delta_{\\text{call}}$ (the delta).',
        '$N(d_2) = P^{\\mathbb{Q}}(S_T > K)$ (risk-neutral exercise probability).',
        'The real-world probability uses $\\mu$ in place of $r$ in $d_2$.',
      ],
    },
    {
      id: 'd4-bs-04',
      exerciseType: 'true-false',
      difficulty: 'easy',
      topic: 'black-scholes',
      tags: ['bs', 'assumptions'],
      timeEstimateSeconds: 20,
      statement: 'The Black-Scholes model assumes that volatility is constant over the life of the option.',
      correct: true,
      explanation: 'Constant volatility is one of the six key BS assumptions. In reality, implied volatility varies by strike and expiration (the volatility surface), which is one of the main limitations of the model.',
      solutionSteps: [
        'BS assumes GBM: $dS = \\mu S\\,dt + \\sigma S\\,dW$ with constant $\\sigma$.',
        'In practice, $\\sigma$ varies by strike (skew/smile) and time (term structure).',
        'This assumption failure is the most important in practice.',
      ],
    },
    {
      id: 'd4-bs-05',
      exerciseType: 'true-false',
      difficulty: 'easy',
      topic: 'black-scholes',
      tags: ['bs', 'limits'],
      timeEstimateSeconds: 30,
      statement: 'As volatility goes to infinity, the Black-Scholes call price also goes to infinity.',
      correct: false,
      explanation: 'As $\\sigma \\to \\infty$, $d_1 \\to +\\infty$ and $d_2 \\to -\\infty$, so $N(d_1) \\to 1$ and $N(d_2) \\to 0$. The call converges to $S$, not infinity. The maximum value of a call is the stock price.',
      solutionSteps: [
        'As $\\sigma \\to \\infty$: $d_1 = \\frac{\\ln(S/K) + (r+\\sigma^2/2)T}{\\sigma\\sqrt{T}} \\to +\\infty$ (dominated by $\\sigma^2/2$ in numerator).',
        'But $d_2 = d_1 - \\sigma\\sqrt{T} \\to -\\infty$.',
        '$C = S \\cdot N(d_1) - Ke^{-rT} \\cdot N(d_2) \\to S \\cdot 1 - Ke^{-rT} \\cdot 0 = S$.',
      ],
    },
    // --- MEDIUM (6) ---
    {
      id: 'd4-bs-06',
      exerciseType: 'multi-step',
      difficulty: 'medium',
      topic: 'black-scholes',
      tags: ['bs', 'pricing'],
      timeEstimateSeconds: 180,
      question: 'Compute the BS call and put price for: $S = 50$, $K = 50$, $T = 0.5$, $r = 4\\%$, $\\sigma = 30\\%$. Use $N(0.198) \\approx 0.578$ and $N(-0.014) \\approx 0.494$.',
      steps: [
        {
          prompt: 'What is $d_1$?',
          correctAnswer: 0.198,
          tolerance: 0.005,
          stepExplanation: '$d_1 = \\frac{\\ln(50/50) + (0.04 + 0.045)\\times 0.5}{0.30 \\times 0.7071} = \\frac{0 + 0.0425}{0.2121} = 0.200$',
        },
        {
          prompt: 'What is $d_2$?',
          correctAnswer: -0.014,
          tolerance: 0.005,
          stepExplanation: '$d_2 = 0.200 - 0.30 \\times 0.7071 = 0.200 - 0.212 = -0.012$',
        },
        {
          prompt: 'What is the call price?',
          correctAnswer: 4.39,
          tolerance: 0.15,
          unit: '$',
          stepExplanation: '$C = 50 \\times 0.578 - 50 e^{-0.02} \\times 0.494 = 28.90 - 49.01 \\times 0.494 = 28.90 - 24.21 = 4.69$',
        },
        {
          prompt: 'What is the put price (via parity)?',
          correctAnswer: 3.40,
          tolerance: 0.15,
          unit: '$',
          stepExplanation: '$P = C - S + Ke^{-rT} = 4.69 - 50 + 49.01 = 3.70$',
        },
      ],
      explanation: 'Full BS pricing walkthrough for an ATM option.',
      solutionSteps: [
        '$d_1 = \\frac{\\ln(1) + (0.04 + 0.045) \\times 0.5}{0.30\\sqrt{0.5}} = \\frac{0.0425}{0.2121} = 0.200$',
        '$d_2 = 0.200 - 0.2121 = -0.012$',
        '$N(0.200) \\approx 0.579$, $N(-0.012) \\approx 0.495$',
        '$C = 50(0.579) - 49.01(0.495) = 28.95 - 24.26 = 4.69$',
        '$P = 4.69 - 50 + 49.01 = 3.70$',
      ],
    },
    {
      id: 'd4-bs-07',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'black-scholes',
      tags: ['bs', 'pricing', 'deep-itm'],
      timeEstimateSeconds: 120,
      question: 'Compute the BS call price for a deep ITM call: $S = 150$, $K = 100$, $T = 0.25$, $r = 5\\%$, $\\sigma = 30\\%$. Use $N(2.88) \\approx 0.998$ and $N(2.73) \\approx 0.997$.',
      correctAnswer: 51.24,
      tolerance: 0.3,
      unit: '$',
      explanation: '$d_1 = \\frac{\\ln(1.5) + (0.05+0.045)\\times 0.25}{0.30 \\times 0.50} = \\frac{0.4055 + 0.02375}{0.15} = 2.862$. $d_2 = 2.862 - 0.15 = 2.712$. $C = 150(0.998) - 98.76(0.997) = 149.70 - 98.48 = 51.22$. Close to intrinsic $150 - 98.76 = 51.24$.',
      solutionSteps: [
        '$d_1 = \\frac{\\ln(150/100) + (0.05+0.045)\\times 0.25}{0.15} = \\frac{0.4055+0.02375}{0.15} = 2.86$',
        '$d_2 = 2.86 - 0.15 = 2.71$',
        '$N(2.86) \\approx 0.998$, $N(2.71) \\approx 0.997$',
        '$C = 150(0.998) - 100 e^{-0.0125}(0.997) = 149.70 - 98.48 = 51.22$',
        'Compare to intrinsic value $S - Ke^{-rT} = 150 - 98.76 = 51.24$. Deep ITM call is almost all intrinsic.',
      ],
    },
    {
      id: 'd4-bs-08',
      exerciseType: 'free-response',
      difficulty: 'medium',
      topic: 'black-scholes',
      tags: ['bs', 'interpretation'],
      timeEstimateSeconds: 120,
      question: 'Explain intuitively why $N(d_1) > N(d_2)$ always. What does this mean for the replicating portfolio of a call?',
      modelAnswer: 'Since $d_1 = d_2 + \\sigma\\sqrt{T}$ and $\\sigma\\sqrt{T} > 0$, we have $d_1 > d_2$, so $N(d_1) > N(d_2)$. For the replicating portfolio: the call can be decomposed as holding $N(d_1)$ shares of stock and borrowing $Ke^{-rT} \\cdot N(d_2)$ dollars. Since $N(d_1) > N(d_2)$, the share-weighted probability is higher than the exercise probability. Intuitively, in states where $S_T$ is high (call is ITM), the stock is worth more, so the share-weighted probability gives more weight to high-$S_T$ states. This is why delta exceeds exercise probability.',
      explanation: 'The gap $N(d_1) - N(d_2)$ represents the difference between the share-measure and risk-neutral-measure probabilities of exercise.',
      solutionSteps: [
        '$d_1 = d_2 + \\sigma\\sqrt{T} > d_2$ since $\\sigma\\sqrt{T} > 0$.',
        'Since $N$ is increasing, $N(d_1) > N(d_2)$.',
        '$N(d_1)$: delta (shares to hold in replicating portfolio).',
        '$N(d_2)$: probability of exercise (risk-neutral).',
        'Delta > exercise probability because high-$S$ states are weighted more heavily in the share measure.',
      ],
    },
    {
      id: 'd4-bs-09',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'black-scholes',
      tags: ['bs', 'limits'],
      timeEstimateSeconds: 60,
      question: 'A 1-year ATM call ($S = K = 100$) with $r = 0$ has a BS price of $C = 100 \\cdot [2N(\\sigma/2) - 1]$. For $\\sigma = 40\\%$, compute the call price. Use $N(0.20) \\approx 0.5793$.',
      correctAnswer: 15.86,
      tolerance: 0.2,
      unit: '$',
      explanation: 'With $r = 0$, $S = K$: $d_1 = \\sigma/2 = 0.20$, $d_2 = -0.20$. $C = 100[N(0.20) - N(-0.20)] = 100[0.5793 - 0.4207] = 100 \\times 0.1586 = 15.86$.',
      solutionSteps: [
        'When $r = 0$ and $S = K$: $d_1 = \\sigma\\sqrt{T}/2 = 0.40/2 = 0.20$, $d_2 = -0.20$.',
        '$C = S[N(d_1) - N(d_2)] = 100[N(0.20) - N(-0.20)]$',
        '$= 100[0.5793 - 0.4207] = 100 \\times 0.1586 = 15.86$',
        'Note: this shows ATM option value is roughly proportional to $\\sigma$ for moderate vol levels.',
      ],
    },
    {
      id: 'd4-bs-10',
      exerciseType: 'multiple-choice',
      difficulty: 'medium',
      topic: 'black-scholes',
      tags: ['bs', 'limits'],
      timeEstimateSeconds: 45,
      question: 'As $T \\to 0$ for an in-the-money call ($S > K$), what does the BS price approach?',
      options: [
        '$S$',
        '$S - K$',
        '$S - Ke^{-rT}$',
        '0',
      ],
      correctIndex: 1,
      explanation: 'As $T \\to 0$, $e^{-rT} \\to 1$, so the PV of strike approaches $K$. With $S > K$: $d_1, d_2 \\to +\\infty$, so $N(d_1), N(d_2) \\to 1$. $C \\to S - K$, which is the intrinsic value.',
      solutionSteps: [
        'As $T \\to 0$: $\\sigma\\sqrt{T} \\to 0$ and $Ke^{-rT} \\to K$.',
        'For $S > K$: $\\ln(S/K) > 0$, so $d_1, d_2 \\to +\\infty$.',
        '$N(d_1), N(d_2) \\to 1$.',
        '$C \\to S \\cdot 1 - K \\cdot 1 = S - K$.',
      ],
    },
    {
      id: 'd4-bs-11',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'black-scholes',
      tags: ['bs', 'exercise-probability'],
      timeEstimateSeconds: 90,
      question: 'For $S = 100$, $K = 110$, $T = 1$, $r = 5\\%$, $\\sigma = 25\\%$, what is the risk-neutral probability the call finishes ITM? Use $N(-0.306) \\approx 0.380$.',
      correctAnswer: 38.0,
      tolerance: 1.5,
      unit: '%',
      explanation: '$d_2 = \\frac{\\ln(100/110) + (0.05 - 0.03125)}{0.25} = -0.306$. $N(-0.306) \\approx 0.380$, so about 38% chance of finishing ITM.',
      solutionSteps: [
        '$d_2 = \\frac{\\ln(S/K) + (r - \\sigma^2/2)T}{\\sigma\\sqrt{T}}$',
        '$= \\frac{\\ln(100/110) + (0.05 - 0.03125)}{0.25}$',
        '$= \\frac{-0.0953 + 0.01875}{0.25} = \\frac{-0.0766}{0.25} = -0.306$',
        '$N(d_2) = N(-0.306) \\approx 0.380$',
        'Risk-neutral probability of finishing ITM $\\approx 38.0\\%$.',
      ],
    },
    // --- HARD (5) ---
    {
      id: 'd4-bs-12',
      exerciseType: 'multi-step',
      difficulty: 'hard',
      topic: 'black-scholes',
      tags: ['bs', 'pricing', 'put-call-parity'],
      timeEstimateSeconds: 240,
      question: 'Full BS computation: $S = 80$, $K = 85$, $T = 0.5$, $r = 3\\%$, $\\sigma = 25\\%$. Compute call, put, and verify put-call parity. Use $N(-0.159) \\approx 0.437$ and $N(-0.336) \\approx 0.369$.',
      steps: [
        {
          prompt: 'What is $d_1$?',
          correctAnswer: -0.159,
          tolerance: 0.01,
          stepExplanation: '$d_1 = \\frac{\\ln(80/85) + (0.03 + 0.03125) \\times 0.5}{0.25 \\times 0.7071} = \\frac{-0.0607 + 0.03063}{0.1768} = \\frac{-0.0301}{0.1768} = -0.170$',
        },
        {
          prompt: 'What is $d_2$?',
          correctAnswer: -0.336,
          tolerance: 0.01,
          stepExplanation: '$d_2 = -0.170 - 0.1768 = -0.347$',
        },
        {
          prompt: 'What is the call price?',
          correctAnswer: 3.58,
          tolerance: 0.3,
          unit: '$',
          stepExplanation: '$C = 80 \\times N(-0.170) - 85 e^{-0.015} \\times N(-0.347) = 80(0.433) - 83.73(0.364) = 34.61 - 30.48 = 4.13$',
        },
        {
          prompt: 'What is the put price (verify via parity)?',
          correctAnswer: 6.35,
          tolerance: 0.3,
          unit: '$',
          stepExplanation: '$P = C - S + Ke^{-rT} = 4.13 - 80 + 83.73 = 7.86$. Also directly: $P = 83.73 \\times N(0.347) - 80 \\times N(0.170) = 83.73(0.636) - 80(0.567) = 53.25 - 45.36 = 7.89$.',
        },
      ],
      explanation: 'Full BS pricing for an OTM call / ITM put, verifying internal consistency.',
      solutionSteps: [
        '$d_1 = \\frac{\\ln(80/85) + (0.03 + 0.03125)(0.5)}{0.25\\sqrt{0.5}} = \\frac{-0.0607 + 0.0306}{0.1768} = -0.170$',
        '$d_2 = -0.170 - 0.177 = -0.347$',
        '$C = 80 N(-0.170) - 83.73 N(-0.347)$',
        '$P = C - S + Ke^{-rT}$ (put-call parity verification)',
      ],
    },
    {
      id: 'd4-bs-13',
      exerciseType: 'free-response',
      difficulty: 'hard',
      topic: 'black-scholes',
      tags: ['bs', 'limits'],
      timeEstimateSeconds: 180,
      question: 'Prove that as $\\sigma \\to \\infty$, the BS call price converges to $S$ and the put price converges to $Ke^{-rT}$. Start from the behavior of $d_1$ and $d_2$.',
      modelAnswer: 'As $\\sigma \\to \\infty$: $d_1 = \\frac{\\ln(S/K) + rT}{\\sigma\\sqrt{T}} + \\frac{\\sigma\\sqrt{T}}{2}$. The first term goes to 0 (finite numerator, infinite denominator) while the second term goes to $+\\infty$. So $d_1 \\to +\\infty$ and $N(d_1) \\to 1$. For $d_2 = d_1 - \\sigma\\sqrt{T}$: as $\\sigma \\to \\infty$, $d_2 \\to -\\infty$ and $N(d_2) \\to 0$. Therefore: $C = SN(d_1) - Ke^{-rT}N(d_2) \\to S(1) - Ke^{-rT}(0) = S$. For the put: $P = C - S + Ke^{-rT} \\to S - S + Ke^{-rT} = Ke^{-rT}$.',
      explanation: 'At infinite vol, the call becomes the stock and the put becomes the bond. This is the maximum possible value for each.',
      solutionSteps: [
        'Write $d_1 = \\frac{\\ln(S/K) + rT}{\\sigma\\sqrt{T}} + \\frac{\\sigma\\sqrt{T}}{2}$',
        'As $\\sigma \\to \\infty$: first term $\\to 0$, second term $\\to +\\infty$. So $d_1 \\to +\\infty$.',
        '$d_2 = d_1 - \\sigma\\sqrt{T} \\to -\\infty$ (the subtracted term dominates).',
        '$C = S \\cdot N(+\\infty) - Ke^{-rT} \\cdot N(-\\infty) = S \\cdot 1 - Ke^{-rT} \\cdot 0 = S$.',
        '$P = C - S + Ke^{-rT} = S - S + Ke^{-rT} = Ke^{-rT}$.',
      ],
    },
    {
      id: 'd4-bs-14',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'black-scholes',
      tags: ['bs', 'atm-approximation'],
      timeEstimateSeconds: 120,
      question: 'A useful approximation for an ATM call ($S = K$) with $r = 0$ is $C \\approx 0.4 \\cdot S \\cdot \\sigma \\cdot \\sqrt{T}$. For $S = K = 100$, $\\sigma = 30\\%$, $T = 0.25$, estimate the call price using this approximation and compare to the exact formula.',
      correctAnswer: 6.0,
      tolerance: 0.3,
      unit: '$',
      explanation: '$C \\approx 0.4 \\times 100 \\times 0.30 \\times 0.50 = 6.00$. The exact BS price (with $r=0$) is $100[N(0.075) - N(-0.075)] = 100[0.530 - 0.470] = 5.99$. The approximation is remarkably accurate for ATM options.',
      solutionSteps: [
        'Approximation: $C \\approx 0.4 S \\sigma \\sqrt{T}$',
        '$= 0.4 \\times 100 \\times 0.30 \\times \\sqrt{0.25} = 0.4 \\times 100 \\times 0.30 \\times 0.50 = 6.00$',
        'Exact: $d_1 = \\sigma\\sqrt{T}/2 = 0.075$, $d_2 = -0.075$.',
        '$C = 100[N(0.075) - N(-0.075)] = 100 \\times 2[N(0.075) - 0.5] \\approx 100 \\times 0.0599 = 5.99$.',
        'The $0.4 S \\sigma \\sqrt{T}$ rule is excellent for ATM, $r \\approx 0$.',
      ],
    },
    {
      id: 'd4-bs-15',
      exerciseType: 'scenario',
      difficulty: 'hard',
      topic: 'black-scholes',
      tags: ['bs', 'sensitivity'],
      timeEstimateSeconds: 120,
      question: 'Base case: ATM call with $S = K = 100$, $T = 0.25$, $r = 0$, $\\sigma = 20\\%$. Using the ATM approximation $C \\approx 0.4 S \\sigma \\sqrt{T}$, compute the price under each scenario.',
      scenarios: [
        {
          description: 'Vol doubles to 40%',
          shocks: [{ variable: 'sigma', change: 20 }],
          expectedAnswer: 8.0,
          tolerance: 0.2,
          unit: '$',
        },
        {
          description: 'Time to expiry doubles to 0.5 years',
          shocks: [{ variable: 'T', change: 0.25 }],
          expectedAnswer: 5.66,
          tolerance: 0.2,
          unit: '$',
        },
        {
          description: 'Stock and strike both move to 200',
          shocks: [{ variable: 'S', change: 100 }],
          expectedAnswer: 8.0,
          tolerance: 0.2,
          unit: '$',
        },
      ],
      explanation: 'The ATM approximation $C \\approx 0.4 S \\sigma \\sqrt{T}$ shows: price is proportional to $S$, $\\sigma$, and $\\sqrt{T}$.',
      solutionSteps: [
        'Base: $0.4 \\times 100 \\times 0.20 \\times 0.50 = \\$4.00$',
        'Vol to 40%: $0.4 \\times 100 \\times 0.40 \\times 0.50 = \\$8.00$ (linear in vol)',
        'T to 0.5: $0.4 \\times 100 \\times 0.20 \\times 0.707 = \\$5.66$ (square root of time)',
        'S to 200: $0.4 \\times 200 \\times 0.20 \\times 0.50 = \\$8.00$ (linear in spot for ATM)',
      ],
    },
    {
      id: 'd4-bs-16',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'black-scholes',
      tags: ['bs', 'dividends'],
      timeEstimateSeconds: 150,
      question: 'Extend BS to continuous dividends: $C = Se^{-qT}N(d_1) - Ke^{-rT}N(d_2)$ where $d_1 = \\frac{\\ln(S/K) + (r - q + \\sigma^2/2)T}{\\sigma\\sqrt{T}}$. For $S = 100$, $K = 100$, $T = 1$, $r = 5\\%$, $q = 2\\%$, $\\sigma = 25\\%$. Compute $d_1$. Use $N(0.19) \\approx 0.575$.',
      correctAnswer: 0.245,
      tolerance: 0.01,
      explanation: '$d_1 = \\frac{\\ln(1) + (0.05 - 0.02 + 0.03125)}{0.25} = \\frac{0.06125}{0.25} = 0.245$.',
      solutionSteps: [
        '$d_1 = \\frac{\\ln(S/K) + (r - q + \\sigma^2/2)T}{\\sigma\\sqrt{T}}$',
        '$= \\frac{\\ln(1) + (0.05 - 0.02 + 0.03125) \\times 1}{0.25 \\times 1}$',
        '$= \\frac{0 + 0.06125}{0.25} = 0.245$',
        '$d_2 = 0.245 - 0.25 = -0.005$',
      ],
    },
    // --- INTERVIEW (3) ---
    {
      id: 'd4-bs-17',
      exerciseType: 'speed-drill',
      difficulty: 'interview',
      topic: 'bs-mental-math',
      tags: ['bs', 'mental-math', 'atm-approximation'],
      timeEstimateSeconds: 90,
      timeLimitSeconds: 90,
      problems: [
        { prompt: 'ATM call, S=100, sigma=20%, T=1yr, r=0. Approx price? (Use 0.4*S*sig*sqrt(T))', correctAnswer: 8.0, tolerance: 0.3 },
        { prompt: 'ATM call, S=100, sigma=40%, T=0.25yr, r=0. Approx price?', correctAnswer: 8.0, tolerance: 0.3 },
        { prompt: 'ATM straddle (C+P), S=100, sigma=20%, T=1yr, r=0. Approx price?', correctAnswer: 16.0, tolerance: 0.6 },
        { prompt: 'Deep ITM call, S=120, K=100, T=0.25, r=4%. Approx price?', correctAnswer: 21.0, tolerance: 0.5 },
        { prompt: 'If ATM call = $8, r=0, S=K=100, what is ATM put?', correctAnswer: 8.0, tolerance: 0.1 },
      ],
      explanation: 'ATM approximation: $C \\approx 0.4 S \\sigma \\sqrt{T}$. Deep ITM: $C \\approx S - Ke^{-rT}$. ATM straddle $\\approx 0.8 S \\sigma \\sqrt{T}$.',
      solutionSteps: [
        '$0.4 \\times 100 \\times 0.20 \\times 1 = 8.0$',
        '$0.4 \\times 100 \\times 0.40 \\times 0.50 = 8.0$',
        'Straddle = $2C = 2 \\times 8.0 = 16.0$ (at $r=0$, $S=K$)',
        'Deep ITM: $C \\approx S - Ke^{-rT} = 120 - 100(0.99) = 21.0$',
        'Put-call parity with $r=0$, $S=K$: $P = C = 8$',
      ],
    },
    {
      id: 'd4-bs-18',
      exerciseType: 'free-response',
      difficulty: 'interview',
      topic: 'black-scholes',
      tags: ['bs', 'interpretation', 'interview'],
      timeEstimateSeconds: 120,
      question: 'An interviewer asks: "Walk me through the Black-Scholes formula for a call. What does each term represent?" Give a concise answer.',
      modelAnswer: '$C = S \\cdot N(d_1) - Ke^{-rT} \\cdot N(d_2)$. The first term, $S \\cdot N(d_1)$, is the expected stock price conditional on the option finishing in the money, weighted by the exercise probability under the stock measure. $N(d_1)$ is the delta: the number of shares in the replicating portfolio. The second term, $Ke^{-rT} \\cdot N(d_2)$, is the present value of the strike times the risk-neutral probability of exercise. So the formula says: call value = (expected receipt if exercised) - (expected payment if exercised), all under risk-neutral pricing. Equivalently, the call is replicated by buying $N(d_1)$ shares and borrowing $Ke^{-rT} \\cdot N(d_2)$ at the risk-free rate.',
      explanation: 'The call is a leveraged position in the stock: long delta shares, short bonds.',
      solutionSteps: [
        '$C = S \\cdot N(d_1) - K e^{-rT} \\cdot N(d_2)$',
        'Term 1: $S \\cdot N(d_1)$ = delta shares of stock in replicating portfolio.',
        'Term 2: $K e^{-rT} \\cdot N(d_2)$ = borrowing (short bond position).',
        '$N(d_1)$ = delta = exercise probability under the share measure.',
        '$N(d_2)$ = risk-neutral probability of exercise.',
        'The call is a leveraged bet: long stock, short bonds.',
      ],
    },
    {
      id: 'd4-bs-19',
      exerciseType: 'numeric',
      difficulty: 'interview',
      topic: 'black-scholes',
      tags: ['bs', 'mental-math'],
      timeEstimateSeconds: 45,
      question: 'Quick estimate: an ATM straddle (call + put, same strike) on a $100 stock with 25% vol and 1 year to expiry. $r = 0$. Approximate the straddle price.',
      correctAnswer: 20.0,
      tolerance: 1.0,
      unit: '$',
      explanation: 'ATM straddle $\\approx 0.8 S \\sigma \\sqrt{T} = 0.8 \\times 100 \\times 0.25 \\times 1 = 20.0$. (Since $C = P$ at $r = 0$, $S = K$, the straddle is $2C \\approx 2 \\times 0.4 S \\sigma \\sqrt{T}$.)',
      solutionSteps: [
        'ATM straddle $\\approx 2C \\approx 2 \\times 0.4 S \\sigma \\sqrt{T}$',
        '$= 0.8 \\times 100 \\times 0.25 \\times 1.0 = \\$20.0$',
        'This is the standard mental-math estimate. The exact BS straddle is close to this.',
      ],
    },
  ],
  cumulativeExercises: [
    {
      id: 'd4-cum-01',
      exerciseType: 'multi-step',
      difficulty: 'medium',
      topic: 'bs-and-parity',
      tags: ['bs', 'put-call-parity'],
      timeEstimateSeconds: 120,
      fromDay: 1,
      question: 'Verify that the BS call and put prices satisfy put-call parity. Use the ATM case: $S = K = 100$, $T = 0.5$, $r = 4\\%$, $\\sigma = 30\\%$.',
      steps: [
        {
          prompt: 'What is $Ke^{-rT}$?',
          correctAnswer: 98.02,
          tolerance: 0.05,
          unit: '$',
          stepExplanation: '$Ke^{-rT} = 100 \\cdot e^{-0.02} = 98.02$',
        },
        {
          prompt: 'If the BS call is $C = 8.81$, what must the put be by parity?',
          correctAnswer: 6.83,
          tolerance: 0.1,
          unit: '$',
          stepExplanation: '$P = C - S + Ke^{-rT} = 8.81 - 100 + 98.02 = 6.83$',
        },
      ],
      explanation: 'Put-call parity must hold for any arbitrage-free pricing model. BS satisfies it by construction.',
      solutionSteps: [
        '$Ke^{-rT} = 100 e^{-0.04 \\times 0.5} = 100 e^{-0.02} = 98.02$',
        '$P = C - S + Ke^{-rT} = 8.81 - 100 + 98.02 = 6.83$',
        'This is guaranteed to match the BS put formula since BS was derived to satisfy parity.',
      ],
    },
    {
      id: 'd4-cum-02',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'bs-and-forward',
      tags: ['bs', 'forward', 'put-call-parity'],
      timeEstimateSeconds: 120,
      fromDay: 1,
      question: 'Show that the BS call - put spread equals the present value of the forward minus strike. For $S = 100$, $K = 95$, $T = 0.5$, $r = 6\\%$. Compute $C - P$ from parity.',
      correctAnswer: 7.82,
      tolerance: 0.1,
      unit: '$',
      explanation: '$C - P = S - Ke^{-rT} = 100 - 95 e^{-0.03} = 7.82$. This equals $(F - K)e^{-rT}$, confirming the connection between forward pricing and put-call parity.',
      solutionSteps: [
        '$C - P = S - Ke^{-rT} = 100 - 95 e^{-0.03} = 100 - 92.18 = 7.82$',
        '$F = Se^{rT} = 100 e^{0.03} = 103.05$',
        '$(F-K)e^{-rT} = (103.05 - 95) e^{-0.03} = 8.05 \\times 0.9704 = 7.81$',
        'These are equal (minor rounding). This shows $C - P = PV(F - K)$.',
      ],
    },
    {
      id: 'd4-cum-03',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'bs-and-ev',
      tags: ['bs', 'ev', 'risk-neutral'],
      timeEstimateSeconds: 90,
      fromDay: 3,
      question: 'Using the BS framework, compute the risk-neutral expected payoff of a 100-strike call when $S = 100$, $T = 1$, $r = 0$, $\\sigma = 20\\%$. Then discount to get the call price. (Hint: $E^{\\mathbb{Q}}[\\max(S_T - K, 0)] = C \\cdot e^{rT}$.)',
      correctAnswer: 7.97,
      tolerance: 0.2,
      unit: '$',
      explanation: 'With $r = 0$: $C = 100[N(0.10) - N(-0.10)] = 100[0.5398 - 0.4602] = 7.97$. The undiscounted expected payoff is also 7.97 (since $r = 0$, no discounting needed).',
      solutionSteps: [
        'With $r = 0$, $S = K = 100$: $d_1 = \\sigma/2 = 0.10$, $d_2 = -0.10$.',
        '$C = 100[N(0.10) - N(-0.10)] = 100[0.5398 - 0.4602] = 7.97$',
        'Since $r = 0$: $E^{\\mathbb{Q}}[\\max(S_T - 100, 0)] = C \\cdot e^{0} = C = 7.97$',
        'The BS price IS the discounted risk-neutral expected payoff (Day 3 connection).',
      ],
    },
  ],
  flashcards: [
    { id: 'd4-f01', front: 'Black-Scholes call formula', back: '$C = S N(d_1) - K e^{-rT} N(d_2)$', tags: ['bs'] },
    { id: 'd4-f02', front: 'Black-Scholes put formula', back: '$P = K e^{-rT} N(-d_2) - S N(-d_1)$', tags: ['bs'] },
    { id: 'd4-f03', front: '$d_1$ formula', back: '$d_1 = \\frac{\\ln(S/K) + (r + \\sigma^2/2)T}{\\sigma\\sqrt{T}}$', tags: ['bs', 'd1-d2'] },
    { id: 'd4-f04', front: '$d_2$ in terms of $d_1$', back: '$d_2 = d_1 - \\sigma\\sqrt{T}$', tags: ['bs', 'd1-d2'] },
    { id: 'd4-f05', front: 'What does $N(d_1)$ represent?', back: 'Delta of the call. Also the risk-neutral exercise probability under the share measure.', tags: ['bs', 'interpretation'] },
    { id: 'd4-f06', front: 'What does $N(d_2)$ represent?', back: 'Risk-neutral probability that the call finishes in the money ($S_T > K$).', tags: ['bs', 'interpretation'] },
    { id: 'd4-f07', front: 'BS call as $\\sigma \\to \\infty$', back: '$C \\to S$ (the maximum value of a call). $N(d_1) \\to 1$, $N(d_2) \\to 0$.', tags: ['bs', 'limits'] },
    { id: 'd4-f08', front: 'BS call as $T \\to 0$ (ITM)', back: '$C \\to \\max(S - K, 0)$ = intrinsic value. No time for vol to matter.', tags: ['bs', 'limits'] },
    { id: 'd4-f09', front: 'ATM call approximation ($r \\approx 0$)', back: '$C \\approx 0.4 S \\sigma \\sqrt{T}$. ATM straddle $\\approx 0.8 S \\sigma \\sqrt{T}$.', tags: ['bs', 'mental-math'] },
    { id: 'd4-f10', front: '6 BS assumptions', back: '1. GBM (lognormal, constant vol). 2. No transaction costs. 3. Continuous trading. 4. Constant risk-free rate. 5. No dividends. 6. European exercise.', tags: ['bs', 'assumptions'] },
    { id: 'd4-f11', front: 'ATM $d_1$ and $d_2$ (when $r = 0$)', back: '$d_1 = \\sigma\\sqrt{T}/2$, $d_2 = -\\sigma\\sqrt{T}/2$. Symmetric around zero.', tags: ['bs', 'd1-d2'] },
    { id: 'd4-f12', front: 'Why is $N(d_1) > N(d_2)$?', back: '$d_1 = d_2 + \\sigma\\sqrt{T}$, so $d_1 > d_2$. Delta exceeds exercise probability because high-$S$ states get more weight.', tags: ['bs', 'interpretation'] },
    { id: 'd4-f13', front: 'BS with continuous dividends', back: 'Replace $S$ with $Se^{-qT}$ and use $r - q$ in $d_1$: $d_1 = \\frac{\\ln(S/K) + (r - q + \\sigma^2/2)T}{\\sigma\\sqrt{T}}$.', tags: ['bs', 'dividends'] },
  ],
  interactiveTools: ['bs-calculator', 'payoff-diagram'],
  cheatSheet: [
    { topic: 'BS Call', formula: 'C = S N(d₁) - Ke⁻ʳᵀ N(d₂)', description: 'European call price' },
    { topic: 'BS Put', formula: 'P = Ke⁻ʳᵀ N(-d₂) - S N(-d₁)', description: 'European put price' },
    { topic: 'd₁', formula: 'd₁ = [ln(S/K) + (r+σ²/2)T] / (σ√T)', description: 'Delta = N(d₁) for calls' },
    { topic: 'd₂', formula: 'd₂ = d₁ - σ√T', description: 'N(d₂) = risk-neutral P(exercise)' },
    { topic: 'ATM Approx', formula: 'C ≈ 0.4 S σ √T', description: 'ATM call with r≈0' },
    { topic: 'ATM Straddle', formula: 'Straddle ≈ 0.8 S σ √T', description: 'ATM straddle with r≈0' },
    { topic: 'σ → ∞', formula: 'C → S, P → Ke⁻ʳᵀ', description: 'Maximum option values' },
    { topic: 'BS + Dividends', formula: 'Replace S with Se⁻ᵠᵀ; use (r-q) in d₁', description: 'Continuous dividend yield q' },
  ],
  summary: [
    'BS formula: $C = SN(d_1) - Ke^{-rT}N(d_2)$, where $d_1, d_2$ depend on $S, K, T, r, \\sigma$',
    '$N(d_1)$ = call delta; $N(d_2)$ = risk-neutral probability of exercise',
    'ATM approximation: $C \\approx 0.4 S \\sigma \\sqrt{T}$ (straddle $\\approx 0.8 S \\sigma \\sqrt{T}$)',
    'Limiting behavior: as $\\sigma \\to \\infty$, call $\\to S$; as $T \\to 0$, option $\\to$ intrinsic',
    'Most critical assumption failure in practice: constant volatility',
  ],
};

export default day04;
