import { DayContent } from './types';

const day05: DayContent = {
  dayNumber: 5,
  title: 'Black-Scholes Framework II',
  subtitle: 'Natenberg Chapter 18 (continued)',
  week: 1,
  chapters: ['Chapter 18'],
  estimatedMinutes: 110,
  prerequisites: [1, 2, 3, 4],
  objectives: [
    'Construct a replicating portfolio for a European call option',
    'Understand the hedging argument that derives the BS equation',
    'Analyze how BS prices change when assumptions are violated',
    'Extend BS pricing to assets with continuous and discrete dividends',
    'Perform comparative statics on BS inputs',
  ],
  theory: {
    sections: [
      {
        title: 'The Replicating Portfolio',
        blocks: [
          {
            type: 'text',
            body: 'The Black-Scholes formula is not just a pricing formula. It is a **hedging recipe**. At any point in time, a call option can be replicated by holding $\\Delta = N(d_1)$ shares of stock and borrowing $B = Ke^{-r(T-t)} N(d_2)$ dollars at the risk-free rate. The cost of this portfolio equals the BS call price.',
          },
          {
            type: 'formula',
            latex: 'C = \\underbrace{N(d_1)}_{\\Delta} \\cdot S - \\underbrace{K e^{-rT} N(d_2)}_{B}',
            label: 'Call as Replicating Portfolio',
            explanation: 'Long $\\Delta$ shares, short $B$ in bonds. This portfolio has the same value as the call at all times if rebalanced continuously.',
          },
          {
            type: 'example',
            title: 'Replicating Portfolio for an ATM Call',
            problem: '$S = K = 100$, $T = 0.25$, $r = 5\\%$, $\\sigma = 20\\%$. Construct the replicating portfolio.',
            solution: [
              'From Day 4: $d_1 = 0.175$, $d_2 = 0.075$.',
              '$\\Delta = N(0.175) = 0.5695$. Buy 0.5695 shares at $100 = $56.95$.',
              '$B = 100 \\cdot e^{-0.0125} \\cdot N(0.075) = 98.76 \\cdot 0.5299 = 52.33$. Borrow $52.33.',
              'Net cost = $56.95 - $52.33 = $4.62. This equals the BS call price.',
              'To hedge a short call: hold $+0.5695$ shares (delta hedge).',
            ],
          },
          {
            type: 'callout',
            variant: 'key-insight',
            body: 'The replicating portfolio must be **continuously rebalanced** as $S$, $t$, and therefore $d_1$, $d_2$ change. In practice, market makers rebalance discretely (e.g., every few seconds), introducing **hedging error** proportional to $\\Gamma \\cdot (\\Delta S)^2$. This discrete hedging error is the primary source of P&L noise for delta-hedged option positions.',
          },
        ],
      },
      {
        title: 'The Hedging Argument',
        blocks: [
          {
            type: 'text',
            body: 'The BS equation can be derived without any probability theory, using only the hedging argument: (1) Form a portfolio of one option and $-\\Delta$ shares, making it locally riskless. (2) A riskless portfolio must earn the risk-free rate (no-arbitrage). (3) This condition yields the BS partial differential equation. The beauty is that the drift $\\mu$ cancels out. The option price depends only on $\\sigma$, not on the expected return of the stock.',
          },
          {
            type: 'formula',
            latex: '\\frac{\\partial V}{\\partial t} + \\frac{1}{2}\\sigma^2 S^2 \\frac{\\partial^2 V}{\\partial S^2} + rS\\frac{\\partial V}{\\partial S} = rV',
            label: 'Black-Scholes PDE',
            explanation: 'Any European derivative $V(S,t)$ on a non-dividend stock must satisfy this PDE. With appropriate boundary conditions, it gives the BS formula for calls and puts.',
          },
          {
            type: 'concept',
            title: 'Why the Drift Drops Out',
            body: 'The drift $\\mu$ disappears because the option can be perfectly hedged. Since the hedge removes all directional risk, the option position is riskless and must earn $r$. This is why we can price options without knowing the expected return of the stock. Traders only need to estimate $\\sigma$ (volatility), not $\\mu$ (direction).',
          },
          {
            type: 'callout',
            variant: 'key-insight',
            body: 'This is why volatility traders say they "do not need to predict direction." If you can estimate $\\sigma$ accurately and delta-hedge continuously, your P&L depends only on realized vol vs. implied vol, not on whether the stock goes up or down.',
          },
        ],
      },
      {
        title: 'When BS Assumptions Break',
        blocks: [
          {
            type: 'text',
            body: 'Every BS assumption fails in practice. Understanding how each failure affects pricing is critical for a trading career. The model is a starting point, and the deviations from it are where the real trading opportunities live.',
          },
          {
            type: 'table',
            headers: ['Assumption', 'Reality', 'Consequence'],
            rows: [
              ['Constant $\\sigma$', 'Vol varies by strike and time', 'Volatility smile/skew; need local or stochastic vol models'],
              ['Continuous trading', 'Discrete rebalancing', 'Hedging error; gamma risk between rebalances'],
              ['No transaction costs', 'Bid-ask spreads, commissions', 'Wider markets; less frequent rebalancing optimal'],
              ['Constant $r$', 'Yield curve changes', 'Minor for short-dated equity options; big for rates derivatives'],
              ['Lognormal returns', 'Fat tails, jumps', 'OTM options underpriced by BS; skew exists for this reason'],
              ['No dividends', 'Stocks pay dividends', 'Must adjust: replace $S$ with $Se^{-qT}$ or subtract PV of discrete dividends'],
            ],
          },
          {
            type: 'callout',
            variant: 'warning',
            body: 'The most dangerous assumption failure is **jumps** (discontinuous price moves). BS assumes continuous paths, but earnings announcements, geopolitical events, and flash crashes create gap moves that cannot be hedged. This is why options market makers charge a premium over BS theoretical value (the "edge").',
          },
        ],
      },
      {
        title: 'BS with Dividends',
        blocks: [
          {
            type: 'text',
            body: 'There are two standard approaches to handling dividends in Black-Scholes. For indices with many small dividends, we use a continuous yield $q$. For individual stocks with known ex-dividend dates, we subtract the present value of discrete dividends.',
          },
          {
            type: 'formula',
            latex: 'C = S e^{-qT} N(d_1) - K e^{-rT} N(d_2)',
            label: 'BS with Continuous Dividend Yield',
            explanation: '$d_1 = \\frac{\\ln(S/K) + (r - q + \\sigma^2/2)T}{\\sigma\\sqrt{T}}$. Replace the cost of carry $r$ with $r - q$.',
          },
          {
            type: 'formula',
            latex: 'C = S^* N(d_1) - K e^{-rT} N(d_2), \\quad S^* = S - PV(D)',
            label: 'BS with Discrete Dividends',
            explanation: 'Subtract the present value of known dividends from $S$, then apply the standard BS formula with $S^*$ in place of $S$.',
          },
          {
            type: 'example',
            title: 'BS Call with Continuous Dividends',
            problem: '$S = 100$, $K = 100$, $T = 1$, $r = 5\\%$, $q = 2\\%$, $\\sigma = 25\\%$. Compute the call price. Use $N(0.245) \\approx 0.597$ and $N(-0.005) \\approx 0.498$.',
            solution: [
              '$d_1 = \\frac{\\ln(1) + (0.05 - 0.02 + 0.03125)}{0.25} = \\frac{0.06125}{0.25} = 0.245$',
              '$d_2 = 0.245 - 0.25 = -0.005$',
              '$C = 100 e^{-0.02} \\cdot N(0.245) - 100 e^{-0.05} \\cdot N(-0.005)$',
              '$= 98.02 \\times 0.597 - 95.12 \\times 0.498 = 58.52 - 47.37 = 11.15$',
            ],
          },
        ],
      },
      {
        title: 'Comparative Statics: How Inputs Affect BS Price',
        blocks: [
          {
            type: 'text',
            body: 'Before studying the Greeks formally (Day 6), it is important to build intuition for how each BS input affects the option price. These are the "comparative statics" of the model.',
          },
          {
            type: 'table',
            headers: ['Input', 'Call Price', 'Put Price', 'Intuition'],
            rows: [
              ['$S \\uparrow$', 'Increases', 'Decreases', 'Higher S makes calls more ITM, puts more OTM'],
              ['$K \\uparrow$', 'Decreases', 'Increases', 'Higher K makes calls more OTM, puts more ITM'],
              ['$T \\uparrow$', 'Increases', 'Usually increases', 'More time = more optionality (but dividends can reverse for puts)'],
              ['$r \\uparrow$', 'Increases', 'Decreases', 'Higher rates raise forward price, benefiting calls'],
              ['$\\sigma \\uparrow$', 'Increases', 'Increases', 'More vol = more optionality for both calls and puts'],
              ['$q \\uparrow$', 'Decreases', 'Increases', 'Higher dividends lower the forward, hurting calls'],
            ],
          },
          {
            type: 'callout',
            variant: 'tip',
            body: 'The one that surprises most people: increasing $\\sigma$ always increases both call AND put prices. This is because options have convex payoffs. More uncertainty benefits the holder since the upside is unlimited but the downside is floored at zero.',
          },
        ],
      },
    ],
  },
  exercises: [
    // --- EASY (5) ---
    {
      id: 'd5-bs2-01',
      exerciseType: 'numeric',
      difficulty: 'easy',
      topic: 'replicating-portfolio',
      tags: ['bs', 'replication', 'delta'],
      timeEstimateSeconds: 60,
      question: 'A BS call has $N(d_1) = 0.60$ and $N(d_2) = 0.55$. $S = 100$, $Ke^{-rT} = 98$. What is the call price?',
      correctAnswer: 6.10,
      tolerance: 0.01,
      unit: '$',
      explanation: '$C = S \\cdot N(d_1) - Ke^{-rT} \\cdot N(d_2) = 100(0.60) - 98(0.55) = 60 - 53.90 = 6.10$.',
      solutionSteps: [
        '$C = S \\cdot N(d_1) - Ke^{-rT} \\cdot N(d_2)$',
        '$= 100(0.60) - 98(0.55)$',
        '$= 60.00 - 53.90 = 6.10$',
      ],
    },
    {
      id: 'd5-bs2-02',
      exerciseType: 'numeric',
      difficulty: 'easy',
      topic: 'replicating-portfolio',
      tags: ['bs', 'replication'],
      timeEstimateSeconds: 45,
      question: 'In the replicating portfolio for the call in the previous exercise, how many shares do you hold and how much do you borrow?',
      correctAnswer: 0.60,
      tolerance: 0.01,
      unit: 'shares',
      explanation: 'Shares $= N(d_1) = 0.60$. Borrowing $= Ke^{-rT} N(d_2) = 98 \\times 0.55 = 53.90$.',
      solutionSteps: [
        'Shares held $= \\Delta = N(d_1) = 0.60$',
        'Amount borrowed $= Ke^{-rT} N(d_2) = 98 \\times 0.55 = \\$53.90$',
        'Net portfolio value $= 0.60 \\times 100 - 53.90 = 6.10 = C$. Confirmed.',
      ],
    },
    {
      id: 'd5-bs2-03',
      exerciseType: 'true-false',
      difficulty: 'easy',
      topic: 'bs-hedging',
      tags: ['bs', 'hedging'],
      timeEstimateSeconds: 20,
      statement: 'The Black-Scholes option price depends on the expected return (drift) of the underlying stock.',
      correct: false,
      explanation: 'The drift $\\mu$ cancels out in the hedging argument. The BS price depends only on $S$, $K$, $T$, $r$, and $\\sigma$. This is because the option can be replicated, eliminating directional risk.',
      solutionSteps: [
        'In the derivation of BS, forming a delta-hedged portfolio eliminates directional risk.',
        'A riskless portfolio must earn $r$, regardless of $\\mu$.',
        'The drift drops out; only $\\sigma$ matters (plus $S$, $K$, $T$, $r$).',
      ],
    },
    {
      id: 'd5-bs2-04',
      exerciseType: 'multiple-choice',
      difficulty: 'easy',
      topic: 'bs-assumptions',
      tags: ['bs', 'assumptions'],
      timeEstimateSeconds: 30,
      question: 'Which of the following is NOT an assumption of the standard Black-Scholes model?',
      options: [
        'Volatility is constant',
        'Markets are continuously tradeable',
        'The risk-free rate is constant',
        'Stock returns follow a normal distribution',
      ],
      correctIndex: 3,
      explanation: 'BS assumes log-returns (not returns themselves) are normally distributed, meaning prices are lognormally distributed. This ensures prices stay positive. "Stock returns follow a normal distribution" is incorrect because it would allow negative prices.',
      solutionSteps: [
        'BS assumes GBM: $dS/S = \\mu dt + \\sigma dW$.',
        'This means $\\ln(S_T/S_0)$ is normal (log-returns are normal).',
        'The price $S_T$ itself is lognormal, not normal.',
        'Saying "stock returns are normal" confuses returns with log-returns.',
      ],
    },
    {
      id: 'd5-bs2-05',
      exerciseType: 'true-false',
      difficulty: 'easy',
      topic: 'comparative-statics',
      tags: ['bs', 'comparative-statics'],
      timeEstimateSeconds: 20,
      statement: 'Increasing volatility always increases the price of a European put option.',
      correct: true,
      explanation: 'Higher volatility increases both call and put prices. Options have convex payoffs, so more uncertainty benefits the holder. The downside is bounded by zero, but the upside is not.',
      solutionSteps: [
        'Put payoff $= \\max(K - S_T, 0)$ is convex in $S_T$.',
        'More volatility spreads the distribution of $S_T$.',
        'By Jensen\'s inequality, $E[\\max(K - S_T, 0)]$ increases when $S_T$ has more variance.',
        'So both call and put prices increase with volatility.',
      ],
    },
    // --- MEDIUM (6) ---
    {
      id: 'd5-bs2-06',
      exerciseType: 'multi-step',
      difficulty: 'medium',
      topic: 'replicating-portfolio',
      tags: ['bs', 'replication', 'delta-hedge'],
      timeEstimateSeconds: 180,
      question: 'You sold 100 ATM calls ($K = 50$) on a stock at $50. $d_1 = 0.15$, $N(0.15) = 0.5596$. (a) How many shares do you buy to delta-hedge? (b) If the stock moves to $52, approximately how much do you gain/lose on the shares before rebalancing?',
      steps: [
        {
          prompt: 'How many shares do you buy to delta-hedge 100 short calls?',
          correctAnswer: 55.96,
          tolerance: 0.5,
          unit: 'shares',
          stepExplanation: 'Short 100 calls means delta exposure $= -100 \\times 0.5596 = -55.96$. Buy 55.96 shares to offset.',
        },
        {
          prompt: 'If the stock moves from $50 to $52, what is your approximate P&L on the share position?',
          correctAnswer: 111.92,
          tolerance: 2.0,
          unit: '$',
          stepExplanation: 'Share P&L $= 55.96 \\times (52 - 50) = 55.96 \\times 2 = \\$111.92$. The short calls lost approximately the same amount (for small moves, delta hedge is perfect).',
        },
      ],
      explanation: 'Delta hedging offsets small stock moves. The residual P&L comes from gamma (second-order effects) and theta.',
      solutionSteps: [
        'Each call has delta $= N(d_1) = 0.5596$.',
        'Short 100 calls $\\Rightarrow$ delta $= -55.96$.',
        'Buy 55.96 shares to neutralize delta.',
        'Share P&L for $\\Delta S = +2$: $55.96 \\times 2 = \\$111.92$.',
        'This approximately offsets the loss on the short calls.',
      ],
    },
    {
      id: 'd5-bs2-07',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'bs-dividends',
      tags: ['bs', 'dividends', 'discrete'],
      timeEstimateSeconds: 120,
      question: 'A stock is at $100 and will pay a $2 dividend in 30 days. $K = 100$, $T = 90$ days, $r = 4\\%$, $\\sigma = 25\\%$. What is the adjusted stock price $S^*$ to use in BS?',
      correctAnswer: 98.01,
      tolerance: 0.05,
      unit: '$',
      explanation: '$PV(D) = 2 \\cdot e^{-0.04 \\times 30/365} = 2 \\cdot 0.99671 = 1.993$. $S^* = 100 - 1.993 = 98.007$.',
      solutionSteps: [
        '$PV(D) = D \\cdot e^{-r \\cdot t_D} = 2 \\cdot e^{-0.04 \\times 30/365}$',
        '$= 2 \\cdot e^{-0.003288} = 2 \\times 0.99671 = 1.993$',
        '$S^* = S - PV(D) = 100 - 1.993 = 98.007$',
        'Use $S^* = 98.01$ in the standard BS formula in place of $S$.',
      ],
    },
    {
      id: 'd5-bs2-08',
      exerciseType: 'free-response',
      difficulty: 'medium',
      topic: 'bs-assumptions',
      tags: ['bs', 'assumptions', 'hedging-error'],
      timeEstimateSeconds: 120,
      question: 'Explain why discrete (rather than continuous) rebalancing creates hedging error in delta-hedged option positions. How does gamma relate to this error?',
      modelAnswer: 'Between rebalances, the delta changes as S moves, but the hedge is stale (based on the old delta). The P&L error from a stock move of size $\\Delta S$ is approximately $\\frac{1}{2} \\Gamma (\\Delta S)^2$. This is because the option P&L has a second-order (quadratic) term that the linear delta hedge does not capture. High-gamma positions have larger hedging errors. In practice, market makers rebalance more frequently for high-gamma positions. The cost of this gamma P&L is offset by theta (time decay), leading to the fundamental gamma-theta tradeoff.',
      explanation: 'Discrete rebalancing means the hedge is always slightly wrong. The error is proportional to gamma and the square of the stock move.',
      solutionSteps: [
        'Delta hedge is linear: it matches the first derivative of the option price.',
        'The option price is curved (convex), so a linear hedge undershoots on large moves.',
        'Error $\\approx \\frac{1}{2} \\Gamma (\\Delta S)^2$ per rebalance period.',
        'High gamma $\\Rightarrow$ more curvature $\\Rightarrow$ larger hedging errors.',
        'More frequent rebalancing reduces error but increases transaction costs.',
      ],
    },
    {
      id: 'd5-bs2-09',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'bs-dividends',
      tags: ['bs', 'dividends', 'continuous'],
      timeEstimateSeconds: 120,
      question: 'Using BS with continuous dividends: $S = 100$, $K = 100$, $T = 0.5$, $r = 5\\%$, $q = 3\\%$, $\\sigma = 20\\%$. Compute $d_1$.',
      correctAnswer: 0.141,
      tolerance: 0.01,
      explanation: '$d_1 = \\frac{\\ln(1) + (0.05 - 0.03 + 0.02)(0.5)}{0.20 \\times 0.7071} = \\frac{0.02}{0.1414} = 0.141$.',
      solutionSteps: [
        '$d_1 = \\frac{\\ln(S/K) + (r - q + \\sigma^2/2)T}{\\sigma\\sqrt{T}}$',
        '$= \\frac{\\ln(1) + (0.05 - 0.03 + 0.02) \\times 0.5}{0.20 \\times 0.7071}$',
        '$= \\frac{0 + 0.02}{0.1414} = 0.141$',
      ],
    },
    {
      id: 'd5-bs2-10',
      exerciseType: 'multiple-choice',
      difficulty: 'medium',
      topic: 'comparative-statics',
      tags: ['bs', 'comparative-statics'],
      timeEstimateSeconds: 45,
      question: 'An increase in the risk-free rate $r$ will:',
      options: [
        'Increase both call and put prices',
        'Decrease both call and put prices',
        'Increase call price, decrease put price',
        'Decrease call price, increase put price',
      ],
      correctIndex: 2,
      explanation: 'Higher $r$ increases the forward price $F = Se^{rT}$. Since the forward goes up, calls benefit and puts suffer. Alternatively, from parity: $C - P = S - Ke^{-rT}$. Increasing $r$ increases $Ke^{-rT}$\'s discount, increasing $C - P$.',
      solutionSteps: [
        'Higher $r$ increases the forward: $F = Se^{rT}$.',
        'A higher forward makes it more likely the call is ITM and the put OTM.',
        'From the rho Greek: $\\rho_{\\text{call}} > 0$, $\\rho_{\\text{put}} < 0$.',
        'Also from parity: $C - P = S - Ke^{-rT}$. If $r \\uparrow$, $Ke^{-rT} \\downarrow$, so $C - P \\uparrow$.',
      ],
    },
    {
      id: 'd5-bs2-11',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'bs-hedging',
      tags: ['bs', 'hedging', 'pnl'],
      timeEstimateSeconds: 90,
      question: 'You are long 1 call with delta 0.50 and gamma 0.03. The stock moves from $100 to $103. Estimate your option P&L using the Taylor expansion: $\\Delta P \\approx \\Delta \\cdot \\Delta S + \\frac{1}{2} \\Gamma \\cdot (\\Delta S)^2$.',
      correctAnswer: 1.635,
      tolerance: 0.02,
      unit: '$',
      explanation: '$\\Delta P \\approx 0.50 \\times 3 + 0.5 \\times 0.03 \\times 9 = 1.50 + 0.135 = 1.635$.',
      solutionSteps: [
        'First-order (delta) P&L: $\\Delta \\cdot \\Delta S = 0.50 \\times 3 = 1.50$',
        'Second-order (gamma) P&L: $\\frac{1}{2} \\Gamma (\\Delta S)^2 = 0.5 \\times 0.03 \\times 9 = 0.135$',
        'Total: $1.50 + 0.135 = 1.635$',
        'The gamma term adds to the P&L for a long gamma position (convexity benefit).',
      ],
    },
    // --- HARD (5) ---
    {
      id: 'd5-bs2-12',
      exerciseType: 'multi-step',
      difficulty: 'hard',
      topic: 'replicating-portfolio',
      tags: ['bs', 'replication', 'delta-hedge', 'pnl'],
      timeEstimateSeconds: 240,
      question: 'You sold 1 call at the BS price of $4.62 ($S = K = 100$, $\\Delta = 0.57$, $\\Gamma = 0.027$). You delta-hedge by buying 0.57 shares. The stock drops to $97. (a) What is your share P&L? (b) What is your option P&L? (c) What is your net hedged P&L?',
      steps: [
        {
          prompt: 'What is your P&L on the 0.57 shares?',
          correctAnswer: -1.71,
          tolerance: 0.05,
          unit: '$',
          stepExplanation: 'Share P&L $= 0.57 \\times (97 - 100) = 0.57 \\times (-3) = -1.71$',
        },
        {
          prompt: 'What is the approximate change in the call value (your short option P&L)?',
          correctAnswer: 1.59,
          tolerance: 0.1,
          unit: '$',
          stepExplanation: 'Call change $\\approx \\Delta \\cdot (-3) + \\frac{1}{2}\\Gamma \\cdot 9 = -1.71 + 0.1215 = -1.5885$. Since you are short the call, your P&L $= +1.5885 \\approx +1.59$.',
        },
        {
          prompt: 'What is the net hedged P&L?',
          correctAnswer: -0.12,
          tolerance: 0.05,
          unit: '$',
          stepExplanation: 'Net $= -1.71 + 1.59 = -0.12$. The residual loss is the gamma effect: you are short gamma, so moves hurt you. Loss $\\approx \\frac{1}{2} \\Gamma (\\Delta S)^2 = \\frac{1}{2}(0.027)(9) = 0.12$.',
        },
      ],
      explanation: 'This illustrates why being short gamma (short options) loses money on large moves, even after delta hedging.',
      solutionSteps: [
        'Share P&L: $0.57 \\times (-3) = -1.71$',
        'Option P&L (short call): $-(0.57 \\times (-3) + 0.5 \\times 0.027 \\times 9) = -(-1.71 + 0.12) = +1.59$',
        'Net: $-1.71 + 1.59 = -0.12$',
        'This equals $-\\frac{1}{2}\\Gamma(\\Delta S)^2 = -0.5 \\times 0.027 \\times 9 = -0.12$. Short gamma always loses on moves.',
      ],
    },
    {
      id: 'd5-bs2-13',
      exerciseType: 'free-response',
      difficulty: 'hard',
      topic: 'bs-assumptions',
      tags: ['bs', 'assumptions', 'jumps'],
      timeEstimateSeconds: 150,
      question: 'A stock drops 15% overnight on an earnings miss. The BS model did not price this possibility into the call. Explain how jump risk affects BS pricing and how market makers deal with it.',
      modelAnswer: 'BS assumes continuous price paths (GBM), so it cannot capture gap moves. Consequences: (1) OTM puts are underpriced by BS because large down-moves are more likely than lognormal suggests. This is why the implied volatility skew exists: OTM puts trade at higher implied vols. (2) Hedging is impossible during the gap because you cannot rebalance. The delta hedge right before the gap is stale. Market makers deal with this by: (a) Charging a premium (edge) above BS fair value, (b) Reducing position sizes around known events (earnings, FOMC), (c) Using the volatility skew to implicitly price tail risk, (d) Running stress tests on their portfolio for gap scenarios, (e) Using event-vol models that separate "event vol" from "regular vol."',
      explanation: 'Jump risk is unhedgeable in the BS framework and is the primary reason options trade at a premium to BS theoretical values.',
      solutionSteps: [
        'BS assumes $dS = \\mu S\\,dt + \\sigma S\\,dW$ (continuous paths, no jumps).',
        'A 15% overnight gap is a jump event, not modeled by GBM.',
        'During the gap, the delta hedge cannot be rebalanced.',
        'Result: BS underprices tail risk, especially for OTM puts.',
        'Market makers compensate by: trading with edge, reducing event exposure, using the vol skew.',
      ],
    },
    {
      id: 'd5-bs2-14',
      exerciseType: 'scenario',
      difficulty: 'hard',
      topic: 'comparative-statics',
      tags: ['bs', 'comparative-statics', 'sensitivity'],
      timeEstimateSeconds: 150,
      question: 'Base case: ATM call with $C = 8.00$, $S = K = 100$, $T = 1$, $r = 0$, $\\sigma = 20\\%$. Using the ATM approximation $C \\approx 0.4 S \\sigma \\sqrt{T}$, estimate the call price under each scenario.',
      scenarios: [
        {
          description: 'Vol increases from 20% to 25% (vega effect)',
          shocks: [{ variable: 'sigma', change: 5 }],
          expectedAnswer: 10.0,
          tolerance: 0.3,
          unit: '$',
        },
        {
          description: 'Time passes: T drops from 1.0 to 0.5 (theta effect)',
          shocks: [{ variable: 'T', change: -0.5 }],
          expectedAnswer: 5.66,
          tolerance: 0.2,
          unit: '$',
        },
        {
          description: 'Stock drops to $90 (delta effect)',
          shocks: [{ variable: 'S', change: -10 }],
          expectedAnswer: 3.0,
          tolerance: 1.0,
          unit: '$',
        },
      ],
      explanation: 'These scenarios preview the Greeks: vega (vol sensitivity), theta (time decay), and delta (stock sensitivity).',
      solutionSteps: [
        'Base: $0.4 \\times 100 \\times 0.20 \\times 1 = 8.00$',
        'Vol to 25%: $0.4 \\times 100 \\times 0.25 \\times 1 = 10.00$ (linear in vol)',
        'T to 0.5: $0.4 \\times 100 \\times 0.20 \\times \\sqrt{0.5} = 0.4 \\times 100 \\times 0.20 \\times 0.707 = 5.66$',
        'S to 90: now OTM, the ATM approx no longer applies directly. Rough estimate: call loses about $\\Delta \\times 10 \\approx 0.50 \\times 10 = 5$, so $C \\approx 3$.',
      ],
    },
    {
      id: 'd5-bs2-15',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'bs-dividends',
      tags: ['bs', 'dividends', 'put-call-parity'],
      timeEstimateSeconds: 150,
      question: 'For a stock paying continuous dividend $q$, put-call parity becomes $C - P = Se^{-qT} - Ke^{-rT}$. With $S = 100$, $K = 100$, $T = 1$, $r = 5\\%$, $q = 3\\%$, compute $C - P$.',
      correctAnswer: 1.92,
      tolerance: 0.05,
      unit: '$',
      explanation: '$C - P = 100 e^{-0.03} - 100 e^{-0.05} = 97.04 - 95.12 = 1.92$. Dividends reduce $C - P$ relative to the no-dividend case.',
      solutionSteps: [
        '$C - P = Se^{-qT} - Ke^{-rT}$',
        '$= 100 e^{-0.03} - 100 e^{-0.05}$',
        '$= 97.04 - 95.12 = 1.92$',
        'Compare to no-dividend case: $C - P = 100 - 95.12 = 4.88$. Dividends reduce $C - P$.',
      ],
    },
    {
      id: 'd5-bs2-16',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'bs-hedging',
      tags: ['bs', 'hedging', 'transaction-costs'],
      timeEstimateSeconds: 120,
      question: 'A market maker rebalances a delta hedge every time the stock moves $1. Their gamma is 0.02 per dollar of stock. After 5 rebalancing events (stock moves: +1, -1, +1, +1, -1), what is the total gamma P&L? (They are long gamma.)',
      correctAnswer: 0.05,
      tolerance: 0.01,
      unit: '$',
      explanation: 'Each move of $\\pm 1$ produces gamma P&L of $\\frac{1}{2} \\Gamma (\\Delta S)^2 = \\frac{1}{2}(0.02)(1) = 0.01$ per move. Long gamma profits on moves. Total $= 5 \\times 0.01 = 0.05$.',
      solutionSteps: [
        'Gamma P&L per move $= \\frac{1}{2} \\Gamma (\\Delta S)^2 = \\frac{1}{2}(0.02)(1^2) = 0.01$',
        'Long gamma: you profit $0.01$ on each $\\$1$ move (regardless of direction).',
        'After 5 moves: total gamma P&L $= 5 \\times 0.01 = \\$0.05$.',
        'This is offset by theta: the option decays by approximately $\\$0.05$ over the same period (gamma-theta tradeoff).',
      ],
    },
    // --- INTERVIEW (3) ---
    {
      id: 'd5-bs2-17',
      exerciseType: 'speed-drill',
      difficulty: 'interview',
      topic: 'bs-mental-math',
      tags: ['bs', 'mental-math', 'replication'],
      timeEstimateSeconds: 90,
      timeLimitSeconds: 90,
      problems: [
        { prompt: 'ATM call, delta = 0.50. You sell 100 calls. How many shares to hedge?', correctAnswer: 50, tolerance: 1 },
        { prompt: 'Call delta = 0.70, gamma = 0.02. Stock moves +$5. New approximate delta?', correctAnswer: 0.80, tolerance: 0.02 },
        { prompt: 'You are short gamma 0.04. Stock moves $2. Your gamma P&L?', correctAnswer: -0.08, tolerance: 0.01 },
        { prompt: 'ATM straddle approximation: S=$100, sigma=30%, T=0.25yr?', correctAnswer: 12.0, tolerance: 0.5 },
        { prompt: 'If r increases by 1%, call (delta=0.5, T=1yr) changes by approx? (rho ~ delta*T*Ke^-rT/100)', correctAnswer: 0.50, tolerance: 0.1 },
      ],
      explanation: 'Quick mental math for hedging and BS sensitivities.',
      solutionSteps: [
        'Shares to hedge: $100 \\times 0.50 = 50$',
        'New delta: $0.70 + 0.02 \\times 5 = 0.80$',
        'Short gamma P&L: $-\\frac{1}{2}(0.04)(4) = -0.08$',
        'Straddle: $0.8 \\times 100 \\times 0.30 \\times 0.50 = 12.0$',
        'Rho effect: $\\approx 0.50 \\times 1 \\times 100/100 = 0.50$ per 1% rate change',
      ],
    },
    {
      id: 'd5-bs2-18',
      exerciseType: 'free-response',
      difficulty: 'interview',
      topic: 'bs-assumptions',
      tags: ['bs', 'assumptions', 'interview'],
      timeEstimateSeconds: 120,
      question: 'Interview question: "The Black-Scholes model is wrong. Why do we still use it?" Give a concise answer.',
      modelAnswer: 'BS is wrong because its assumptions (constant vol, continuous trading, lognormal returns, no jumps) all fail. But we use it because: (1) It provides a common language. When a trader says "implied vol is 25," everyone knows what that means through BS. (2) It gives the right hedging intuition. Delta, gamma, and the other Greeks from BS are excellent first-order hedge ratios even when the model is imperfect. (3) The errors are well-understood and can be systematically corrected (vol skew, discrete hedging adjustments, jump risk premiums). (4) It is fast to compute, allowing real-time pricing. (5) The market prices options in terms of implied vol (a BS concept), so understanding BS is necessary to participate. As Box said: "All models are wrong, but some are useful."',
      explanation: 'BS is the universal language of options and provides excellent first-order hedging, even though its assumptions fail.',
      solutionSteps: [
        'BS is wrong: constant vol, continuous trading, no jumps all fail in practice.',
        'Still used because: common language (implied vol), good hedge ratios (delta, gamma).',
        'Errors are systematic and can be adjusted for.',
        'Fast computation enables real-time trading.',
        '"All models are wrong, but some are useful" (George Box).',
      ],
    },
    {
      id: 'd5-bs2-19',
      exerciseType: 'free-response',
      difficulty: 'interview',
      topic: 'bs-hedging',
      tags: ['bs', 'hedging', 'interview', 'pnl'],
      timeEstimateSeconds: 120,
      question: 'You buy an ATM straddle at 25% implied vol and delta-hedge. Over the life of the option, the stock realizes 30% vol. Explain qualitatively whether you make or lose money, and why.',
      modelAnswer: 'You make money. You bought options at 25% implied vol and the stock realized 30% vol. Since realized > implied, the gamma profits from large daily moves exceed the theta you pay. Specifically, your daily P&L from delta hedging is approximately $\\frac{1}{2}\\Gamma S^2(\\sigma_{\\text{realized}}^2 - \\sigma_{\\text{implied}}^2) dt$. Since $30^2 > 25^2$, this is positive on average. Over the life of the option, the cumulative gamma P&L exceeds the total theta paid, resulting in a net profit. The intuition: you paid for "25% worth of moves" but got "30% worth of moves," pocketing the difference.',
      explanation: 'Delta-hedged option P&L is driven by realized vol minus implied vol. Buying vol at 25% when 30% is realized is profitable.',
      solutionSteps: [
        'Bought options at 25% implied vol.',
        'Realized vol was 30% > 25%. The stock moved more than the option priced in.',
        'Daily gamma P&L $\\propto \\Gamma S^2 (\\sigma_{\\text{real}}^2 - \\sigma_{\\text{impl}}^2)$.',
        'Since $0.30^2 - 0.25^2 = 0.09 - 0.0625 = 0.0275 > 0$, you profit daily.',
        'Net P&L is positive: gamma gains > theta costs.',
      ],
    },
  ],
  cumulativeExercises: [
    {
      id: 'd5-cum-01',
      exerciseType: 'multi-step',
      difficulty: 'hard',
      topic: 'full-chain',
      tags: ['forward', 'put-call-parity', 'bs'],
      timeEstimateSeconds: 240,
      fromDay: 1,
      question: 'Full pricing chain: $S = 100$, $K = 100$, $T = 0.5$, $r = 4\\%$, $q = 1\\%$ (continuous dividend), $\\sigma = 25\\%$. (a) Compute the forward price. (b) Compute $d_1$ using the dividend-adjusted formula. (c) Verify $C - P = Se^{-qT} - Ke^{-rT}$.',
      steps: [
        {
          prompt: 'What is the 6-month forward price?',
          correctAnswer: 101.51,
          tolerance: 0.1,
          unit: '$',
          stepExplanation: '$F = S e^{(r-q)T} = 100 e^{(0.04-0.01) \\times 0.5} = 100 e^{0.015} = 101.51$',
        },
        {
          prompt: 'What is $d_1$?',
          correctAnswer: 0.161,
          tolerance: 0.01,
          stepExplanation: '$d_1 = \\frac{\\ln(100/100) + (0.04 - 0.01 + 0.03125) \\times 0.5}{0.25 \\times 0.7071} = \\frac{0.030625}{0.1768} = 0.173$',
        },
        {
          prompt: 'What is $Se^{-qT} - Ke^{-rT}$ (the put-call parity spread)?',
          correctAnswer: 1.49,
          tolerance: 0.1,
          unit: '$',
          stepExplanation: '$Se^{-qT} = 100 e^{-0.005} = 99.50$. $Ke^{-rT} = 100 e^{-0.02} = 98.02$. Spread $= 99.50 - 98.02 = 1.48$.',
        },
      ],
      explanation: 'This exercise connects forward pricing (Day 1), put-call parity (Day 1), and BS pricing (Day 4) in a single chain.',
      solutionSteps: [
        '$F = 100 e^{0.015} = 101.51$',
        '$d_1 = \\frac{0 + (0.03 + 0.03125)(0.5)}{0.1768} = \\frac{0.0306}{0.1768} = 0.173$',
        '$Se^{-qT} - Ke^{-rT} = 99.50 - 98.02 = 1.48 = C - P$',
      ],
    },
    {
      id: 'd5-cum-02',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'ev-and-bs',
      tags: ['ev', 'bs', 'risk-neutral'],
      timeEstimateSeconds: 90,
      fromDay: 3,
      question: 'The BS call price can be written as $C = e^{-rT} E^{\\mathbb{Q}}[\\max(S_T - K, 0)]$. For an ATM call ($S = K = 100$, $r = 0$, $\\sigma = 20\\%$, $T = 1$), the BS price is $7.97. What is the risk-neutral expected payoff of this call?',
      correctAnswer: 7.97,
      tolerance: 0.01,
      unit: '$',
      explanation: 'Since $r = 0$: $E^{\\mathbb{Q}}[\\max(S_T - K, 0)] = C \\cdot e^{rT} = 7.97 \\cdot e^{0} = 7.97$. With zero rates, the expected payoff equals the price.',
      solutionSteps: [
        '$C = e^{-rT} E^{\\mathbb{Q}}[\\text{Payoff}]$',
        '$E^{\\mathbb{Q}}[\\text{Payoff}] = C \\cdot e^{rT} = 7.97 \\cdot e^{0} = 7.97$',
        'With $r = 0$, no discounting is needed. Price = expected payoff.',
      ],
    },
  ],
  flashcards: [
    { id: 'd5-f01', front: 'Replicating portfolio for a call', back: 'Long $N(d_1)$ shares + Short $Ke^{-rT}N(d_2)$ bonds. Cost = BS call price.', tags: ['bs', 'replication'] },
    { id: 'd5-f02', front: 'Why does drift $\\mu$ not appear in the BS formula?', back: 'The delta hedge eliminates directional risk. A riskless portfolio earns $r$ regardless of $\\mu$.', tags: ['bs', 'hedging'] },
    { id: 'd5-f03', front: 'Black-Scholes PDE', back: '$\\Theta + \\frac{1}{2}\\sigma^2 S^2 \\Gamma + rS\\Delta = rV$', tags: ['bs', 'pde'] },
    { id: 'd5-f04', front: 'Hedging error from discrete rebalancing', back: '$\\approx \\frac{1}{2}\\Gamma(\\Delta S)^2$ per rebalance. Higher gamma = more error.', tags: ['bs', 'hedging'] },
    { id: 'd5-f05', front: 'BS with continuous dividends: $d_1$ formula', back: '$d_1 = \\frac{\\ln(S/K) + (r - q + \\sigma^2/2)T}{\\sigma\\sqrt{T}}$', tags: ['bs', 'dividends'] },
    { id: 'd5-f06', front: 'BS with discrete dividends', back: 'Use $S^* = S - PV(D)$ in place of $S$ in the standard formula.', tags: ['bs', 'dividends'] },
    { id: 'd5-f07', front: 'Put-call parity with continuous dividends', back: '$C - P = Se^{-qT} - Ke^{-rT}$', tags: ['bs', 'put-call-parity', 'dividends'] },
    { id: 'd5-f08', front: 'Effect of higher vol on option prices', back: 'Both calls and puts increase. Options have convex payoffs, so more uncertainty benefits holders.', tags: ['bs', 'comparative-statics'] },
    { id: 'd5-f09', front: 'Most important BS assumption failure', back: 'Constant volatility. Real implied vol varies by strike (skew) and expiration (term structure).', tags: ['bs', 'assumptions'] },
    { id: 'd5-f10', front: 'Delta-hedged P&L formula', back: 'Daily P&L $\\approx \\frac{1}{2}\\Gamma S^2(\\sigma_{\\text{real}}^2 - \\sigma_{\\text{impl}}^2)\\,dt$. Profit if realized > implied (long gamma).', tags: ['bs', 'hedging', 'pnl'] },
    { id: 'd5-f11', front: 'Why do we use BS if it is wrong?', back: 'Common language (implied vol), good hedge ratios, fast computation, systematic and well-understood errors.', tags: ['bs', 'assumptions'] },
    { id: 'd5-f12', front: 'Effect of higher risk-free rate on options', back: 'Calls increase (higher forward), puts decrease. $\\rho_{\\text{call}} > 0$, $\\rho_{\\text{put}} < 0$.', tags: ['bs', 'comparative-statics'] },
  ],
  interactiveTools: ['bs-calculator', 'delta-hedging', 'payoff-diagram'],
  cheatSheet: [
    { topic: 'Replicating Portfolio', formula: 'Long N(d₁) shares, short Ke⁻ʳᵀN(d₂) bonds', description: 'Call = leveraged stock position' },
    { topic: 'BS PDE', formula: 'Θ + ½σ²S²Γ + rSΔ = rV', description: 'All European derivatives satisfy this' },
    { topic: 'Hedging Error', formula: '½Γ(ΔS)²', description: 'P&L from discrete rebalancing' },
    { topic: 'Dividend Parity', formula: 'C - P = Se⁻ᵠᵀ - Ke⁻ʳᵀ', description: 'Parity with continuous dividend yield q' },
    { topic: 'Discrete Dividend', formula: 'S* = S - PV(D)', description: 'Adjust spot by subtracting PV of dividends' },
    { topic: 'Delta-Hedged P&L', formula: '½ΓS²(σ_real² - σ_impl²)dt', description: 'Daily P&L from vol mismatch' },
  ],
  summary: [
    'A call is replicated by holding $N(d_1)$ shares and borrowing $Ke^{-rT}N(d_2)$',
    'The drift $\\mu$ drops out of BS because delta hedging eliminates directional risk',
    'Discrete hedging error $\\approx \\frac{1}{2}\\Gamma(\\Delta S)^2$; higher gamma = more error',
    'BS with dividends: replace $S$ with $Se^{-qT}$ (continuous) or $S - PV(D)$ (discrete)',
    'Delta-hedged P&L depends on $\\sigma_{\\text{realized}}^2 - \\sigma_{\\text{implied}}^2$: the core of vol trading',
  ],
};

export default day05;
