import { DayContent } from './types';

const day06: DayContent = {
  dayNumber: 6,
  title: 'Greeks & Cross-Greek Relationships',
  subtitle: 'Natenberg Chapters 6, 9',
  week: 1,
  chapters: ['Chapter 6', 'Chapter 9'],
  estimatedMinutes: 120,
  prerequisites: [1, 2, 3, 4, 5],
  objectives: [
    'Compute Delta, Gamma, Theta, Vega, and Rho from the BS formulas',
    'Understand the gamma-theta tradeoff and BS PDE relationship',
    'Analyze Greek profiles across moneyness and time',
    'Perform delta-hedging P&L analysis using Greeks',
    'Apply the BS PDE: $\\Theta + \\frac{1}{2}\\sigma^2 S^2 \\Gamma = rV - rS\\Delta$',
  ],
  theory: {
    sections: [
      {
        title: 'Delta',
        blocks: [
          {
            type: 'text',
            body: 'Delta ($\\Delta$) measures the rate of change of the option price with respect to the underlying price. It is the most fundamental Greek and the primary hedge ratio. For a call, $\\Delta = N(d_1) \\in (0, 1)$. For a put, $\\Delta = N(d_1) - 1 \\in (-1, 0)$.',
          },
          {
            type: 'formula',
            latex: '\\Delta_{\\text{call}} = N(d_1), \\quad \\Delta_{\\text{put}} = N(d_1) - 1',
            label: 'Delta Formulas',
            explanation: 'Call delta is always positive (option gains when stock rises). Put delta is always negative. Note: $\\Delta_{\\text{put}} = \\Delta_{\\text{call}} - 1$, consistent with put-call parity.',
          },
          {
            type: 'callout',
            variant: 'tip',
            body: 'ATM options have delta $\\approx \\pm 0.50$. Deep ITM calls have $\\Delta \\approx 1$ (behave like stock). Deep OTM calls have $\\Delta \\approx 0$ (barely respond to stock moves). Puts mirror this: deep ITM puts have $\\Delta \\approx -1$.',
          },
        ],
      },
      {
        title: 'Gamma',
        blocks: [
          {
            type: 'text',
            body: 'Gamma ($\\Gamma$) is the rate of change of delta with respect to the stock price. It measures the curvature of the option\'s price function. Gamma is highest for ATM options near expiration and is always positive for long options.',
          },
          {
            type: 'formula',
            latex: '\\Gamma = \\frac{n(d_1)}{S \\sigma \\sqrt{T}}',
            label: 'Gamma Formula',
            explanation: '$n(d_1) = \\frac{1}{\\sqrt{2\\pi}} e^{-d_1^2/2}$ is the standard normal PDF. Gamma is the same for calls and puts (same strike, same expiry).',
          },
          {
            type: 'concept',
            title: 'Gamma as a Risk Measure',
            body: 'Long gamma positions profit from large moves (in either direction) because delta adjusts favorably. Short gamma positions lose on large moves. Gamma is the source of the convexity benefit of owning options. It is paid for via theta.',
          },
        ],
      },
      {
        title: 'Theta',
        blocks: [
          {
            type: 'text',
            body: 'Theta ($\\Theta$) measures time decay: the rate at which an option loses value as time passes, all else equal. For long options, theta is negative (the option decays). For ATM options, theta is largest near expiration.',
          },
          {
            type: 'formula',
            latex: '\\Theta_{\\text{call}} = -\\frac{S \\sigma n(d_1)}{2\\sqrt{T}} - rKe^{-rT}N(d_2)',
            label: 'Theta Formula (Call)',
            explanation: 'The first term is always negative (volatility component of decay). The second term is the interest cost of the strike. For puts, the sign of the interest term flips.',
          },
          {
            type: 'callout',
            variant: 'key-insight',
            body: 'Theta for an ATM option accelerates as expiry approaches (the "hockey stick" decay curve). Roughly: theta is proportional to $1/\\sqrt{T}$. An option with 1 week to expiry decays about twice as fast as one with 4 weeks.',
          },
        ],
      },
      {
        title: 'Vega',
        blocks: [
          {
            type: 'text',
            body: 'Vega measures the sensitivity of the option price to changes in implied volatility. It is the most important Greek for volatility traders. Vega is highest for ATM options with long time to expiry.',
          },
          {
            type: 'formula',
            latex: '\\mathcal{V} = S \\sqrt{T} \\cdot n(d_1)',
            label: 'Vega Formula',
            explanation: 'Vega is the same for calls and puts (same strike, expiry). It is always positive for long options. Convention: vega gives the price change for a 1-point (1 percentage point) change in implied vol.',
          },
          {
            type: 'callout',
            variant: 'tip',
            body: 'Vega scales with $\\sqrt{T}$: a 1-year option has about $\\sqrt{4} = 2$ times the vega of a 3-month option. This is crucial for calendar spread analysis.',
          },
        ],
      },
      {
        title: 'The Gamma-Theta Tradeoff & BS PDE',
        blocks: [
          {
            type: 'text',
            body: 'The most important relationship among the Greeks is the **gamma-theta tradeoff**. Long gamma positions (which profit from moves) pay for this through theta (time decay). The exact relationship is given by the BS PDE.',
          },
          {
            type: 'formula',
            latex: '\\Theta + \\frac{1}{2}\\sigma^2 S^2 \\Gamma = rV - rS\\Delta',
            label: 'BS PDE in Greek Form',
            explanation: 'For ATM options with low rates: $\\Theta \\approx -\\frac{1}{2}\\sigma^2 S^2 \\Gamma$. Theta and gamma are locked in opposition: more gamma means more negative theta.',
          },
          {
            type: 'example',
            title: 'Gamma-Theta Tradeoff',
            problem: 'An ATM call has $\\Gamma = 0.02$, $S = 100$, $\\sigma = 20\\%$, $r \\approx 0$. What is the approximate daily theta?',
            solution: [
              'From the PDE (with $r \\approx 0$): $\\Theta \\approx -\\frac{1}{2}\\sigma^2 S^2 \\Gamma$',
              '$= -\\frac{1}{2}(0.04)(10000)(0.02) = -4.00$ per year.',
              'Daily theta $= -4.00 / 365 = -\\$0.011$ per day.',
              'Alternatively: the option decays by about $1.1$ cents per day, offset by gamma profits from daily moves.',
            ],
          },
          {
            type: 'callout',
            variant: 'key-insight',
            body: 'The gamma-theta tradeoff is the fundamental tension in options trading. You cannot have gamma (convexity) for free. If you want to profit from moves, you must pay theta. If you collect theta, you are exposed to large moves (short gamma). Understanding this tradeoff is the single most important insight for a volatility trader.',
          },
        ],
      },
      {
        title: 'Rho & Minor Greeks',
        blocks: [
          {
            type: 'text',
            body: 'Rho ($\\rho$) measures sensitivity to the risk-free rate. It is typically the least important Greek for short-dated equity options, but matters for long-dated options and interest rate derivatives.',
          },
          {
            type: 'formula',
            latex: '\\rho_{\\text{call}} = KTe^{-rT}N(d_2), \\quad \\rho_{\\text{put}} = -KTe^{-rT}N(-d_2)',
            label: 'Rho Formulas',
            explanation: 'Rho is positive for calls (higher rates increase forward, benefiting calls) and negative for puts. Rho scales with $T$: long-dated options are more rate-sensitive.',
          },
        ],
      },
    ],
  },
  exercises: [
    // --- EASY (5) ---
    {
      id: 'd6-greek-01',
      exerciseType: 'numeric',
      difficulty: 'easy',
      topic: 'delta',
      tags: ['greeks', 'delta'],
      timeEstimateSeconds: 30,
      question: 'A call option has $d_1 = 0.25$. What is its delta? Use $N(0.25) = 0.5987$.',
      correctAnswer: 0.5987,
      tolerance: 0.001,
      explanation: '$\\Delta_{\\text{call}} = N(d_1) = N(0.25) = 0.5987$.',
      solutionSteps: [
        '$\\Delta_{\\text{call}} = N(d_1) = N(0.25) = 0.5987$.',
        'This means for every $1 the stock moves, the call moves about $0.60.',
      ],
    },
    {
      id: 'd6-greek-02',
      exerciseType: 'numeric',
      difficulty: 'easy',
      topic: 'delta',
      tags: ['greeks', 'delta'],
      timeEstimateSeconds: 20,
      question: 'If a call has delta $= 0.60$, what is the delta of the corresponding put (same strike and expiry)?',
      correctAnswer: -0.40,
      tolerance: 0.01,
      explanation: '$\\Delta_{\\text{put}} = \\Delta_{\\text{call}} - 1 = 0.60 - 1 = -0.40$.',
      solutionSteps: [
        '$\\Delta_{\\text{put}} = N(d_1) - 1 = \\Delta_{\\text{call}} - 1$',
        '$= 0.60 - 1 = -0.40$',
        'This follows directly from put-call parity: differentiating $C - P = S - Ke^{-rT}$ with respect to $S$ gives $\\Delta_C - \\Delta_P = 1$.',
      ],
    },
    {
      id: 'd6-greek-03',
      exerciseType: 'true-false',
      difficulty: 'easy',
      topic: 'gamma',
      tags: ['greeks', 'gamma'],
      timeEstimateSeconds: 20,
      statement: 'Gamma is different for a call and put at the same strike and expiry.',
      correct: false,
      explanation: 'Gamma is identical for a call and put at the same strike and expiry. This follows from put-call parity: $C - P = S - Ke^{-rT}$. The second derivative of the RHS with respect to $S$ is 0, so $\\Gamma_C = \\Gamma_P$.',
      solutionSteps: [
        'From put-call parity: $C - P = S - Ke^{-rT}$.',
        'Differentiate twice w.r.t. $S$: $\\Gamma_C - \\Gamma_P = 0$.',
        'So $\\Gamma_C = \\Gamma_P$.',
      ],
    },
    {
      id: 'd6-greek-04',
      exerciseType: 'multiple-choice',
      difficulty: 'easy',
      topic: 'greeks',
      tags: ['greeks', 'gamma', 'theta'],
      timeEstimateSeconds: 30,
      question: 'Which Greek is always the same for a call and put at the same strike and expiry?',
      options: [
        'Delta',
        'Theta',
        'Gamma',
        'Rho',
      ],
      correctIndex: 2,
      explanation: 'Gamma and Vega are the same for calls and puts (same strike/expiry). Delta differs by 1. Theta differs by $rKe^{-rT}$. Rho differs by sign.',
      solutionSteps: [
        'From parity $C - P = S - Ke^{-rT}$:',
        '$\\Delta_C - \\Delta_P = 1$ (different).',
        '$\\Gamma_C - \\Gamma_P = 0$ (same).',
        '$\\Theta_C - \\Theta_P = rKe^{-rT}$ (different).',
        '$\\mathcal{V}_C = \\mathcal{V}_P$ (same, since $\\partial(S - Ke^{-rT})/\\partial\\sigma = 0$).',
      ],
    },
    {
      id: 'd6-greek-05',
      exerciseType: 'numeric',
      difficulty: 'easy',
      topic: 'vega',
      tags: ['greeks', 'vega'],
      timeEstimateSeconds: 45,
      question: 'An ATM call has vega $= 0.20$ (price change per 1% vol change). If implied vol increases from 25% to 27%, what is the approximate price change?',
      correctAnswer: 0.40,
      tolerance: 0.01,
      unit: '$',
      explanation: 'Vol change $= 2$ percentage points. Price change $\\approx 0.20 \\times 2 = \\$0.40$.',
      solutionSteps: [
        'Vega $= 0.20$ per 1 percentage point of vol.',
        'Vol increase $= 27\\% - 25\\% = 2$ points.',
        'Price change $\\approx 0.20 \\times 2 = \\$0.40$.',
      ],
    },
    // --- MEDIUM (6) ---
    {
      id: 'd6-greek-06',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'gamma',
      tags: ['greeks', 'gamma'],
      timeEstimateSeconds: 90,
      question: 'Compute gamma for an ATM option: $S = 100$, $K = 100$, $T = 0.25$, $r = 0$, $\\sigma = 20\\%$. Use $n(0.05) \\approx 0.3984$.',
      correctAnswer: 0.0399,
      tolerance: 0.001,
      explanation: 'With $r = 0$, $S = K$: $d_1 = \\sigma\\sqrt{T}/2 = 0.10/2 = 0.05$. $\\Gamma = \\frac{n(0.05)}{S\\sigma\\sqrt{T}} = \\frac{0.3984}{100 \\times 0.20 \\times 0.50} = \\frac{0.3984}{10} = 0.03984$.',
      solutionSteps: [
        '$d_1 = \\sigma\\sqrt{T}/2 = 0.20 \\times 0.50/2 = 0.05$ (ATM with $r = 0$).',
        '$n(d_1) = n(0.05) = \\frac{1}{\\sqrt{2\\pi}}e^{-0.05^2/2} \\approx 0.3984$.',
        '$\\Gamma = \\frac{n(d_1)}{S\\sigma\\sqrt{T}} = \\frac{0.3984}{100 \\times 0.10} = 0.03984$.',
        'This means for a $1 move in the stock, delta changes by about 0.04.',
      ],
    },
    {
      id: 'd6-greek-07',
      exerciseType: 'multi-step',
      difficulty: 'medium',
      topic: 'gamma-theta-tradeoff',
      tags: ['greeks', 'gamma', 'theta', 'pde'],
      timeEstimateSeconds: 120,
      question: 'An ATM call has $\\Gamma = 0.04$, $S = 100$, $\\sigma = 20\\%$, $r = 0$. (a) Compute the annual theta from the BS PDE. (b) Convert to daily theta.',
      steps: [
        {
          prompt: 'What is the annual theta (using $\\Theta \\approx -\\frac{1}{2}\\sigma^2 S^2 \\Gamma$ when $r \\approx 0$)?',
          correctAnswer: -8.0,
          tolerance: 0.1,
          unit: '$ per year',
          stepExplanation: '$\\Theta \\approx -\\frac{1}{2}(0.04)(10000)(0.04) = -8.00$ per year.',
        },
        {
          prompt: 'What is the daily theta?',
          correctAnswer: -0.0219,
          tolerance: 0.002,
          unit: '$ per day',
          stepExplanation: 'Daily theta $= -8.00/365 = -0.0219$ per day.',
        },
      ],
      explanation: 'The gamma-theta tradeoff: this option earns gamma P&L from moves but pays about 2.2 cents per day in theta.',
      solutionSteps: [
        'BS PDE with $r = 0$: $\\Theta = -\\frac{1}{2}\\sigma^2 S^2 \\Gamma$',
        '$= -\\frac{1}{2}(0.04)(10000)(0.04) = -8.00$ per year',
        'Daily: $-8.00/365 = -\\$0.022$ per day.',
        'Break-even daily move: $|\\Delta S|$ where $\\frac{1}{2}\\Gamma(\\Delta S)^2 = 0.022$.',
        '$\\Delta S = \\sqrt{2 \\times 0.022/0.04} = \\sqrt{1.10} = \\$1.05$.',
      ],
    },
    {
      id: 'd6-greek-08',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'vega',
      tags: ['greeks', 'vega'],
      timeEstimateSeconds: 90,
      question: 'Compute vega for: $S = 100$, $d_1 = 0.10$, $T = 1$. Use $n(0.10) \\approx 0.3970$.',
      correctAnswer: 39.70,
      tolerance: 0.2,
      explanation: '$\\mathcal{V} = S\\sqrt{T} \\cdot n(d_1) = 100 \\times 1 \\times 0.3970 = 39.70$. This means a 1 percentage point increase in vol increases the option price by about $0.397.',
      solutionSteps: [
        '$\\mathcal{V} = S\\sqrt{T} \\cdot n(d_1) = 100 \\times 1.0 \\times 0.3970 = 39.70$',
        'Convention: vega is often quoted per 1% vol change. So $39.70/100 = 0.397$ per 1% vol.',
        'Or equivalently, a 1 vol point (1%) increase raises the price by $\\$0.397$.',
      ],
    },
    {
      id: 'd6-greek-09',
      exerciseType: 'free-response',
      difficulty: 'medium',
      topic: 'greek-profiles',
      tags: ['greeks', 'delta', 'gamma'],
      timeEstimateSeconds: 120,
      question: 'Describe the delta and gamma profiles of a call option as a function of the stock price, for fixed $K$, $T$, $\\sigma$. How do these profiles change as $T \\to 0$?',
      modelAnswer: 'Delta profile: S-shaped curve from 0 (far OTM) to 1 (far ITM), passing through 0.5 at ATM. Gamma profile: bell-shaped, peaked at ATM, approaching zero for deep ITM and OTM. As $T \\to 0$: delta approaches a step function (0 for $S < K$, 1 for $S > K$), and gamma approaches a Dirac delta at $S = K$ (infinite at ATM, zero elsewhere). Near expiry, ATM gamma explodes, creating extreme hedging risk (the "pin risk" problem). This is why market makers are very cautious with ATM options near expiry.',
      explanation: 'Delta is sigmoid-shaped; gamma is bell-shaped centered at ATM. Both sharpen as expiry approaches.',
      solutionSteps: [
        'Delta: sigmoid from 0 to 1, centered at $K$. Slope $= \\Gamma$.',
        'Gamma: peaked at ATM ($S = K$). Width $\\propto \\sigma\\sqrt{T}$.',
        'As $T \\to 0$: delta $\\to$ step function, gamma $\\to$ Dirac delta at $K$.',
        'Near expiry: ATM gamma is huge (delta flips rapidly between 0 and 1).',
        'This creates "pin risk" for short option holders at ATM near expiry.',
      ],
    },
    {
      id: 'd6-greek-10',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'delta-hedging',
      tags: ['greeks', 'delta', 'hedging'],
      timeEstimateSeconds: 90,
      question: 'You are short 200 calls with delta 0.45 and long 300 puts with delta $-0.30$. What is your portfolio delta? How many shares do you need to buy/sell to be delta-neutral?',
      correctAnswer: 0,
      tolerance: 1,
      unit: 'shares (net delta before hedging)',
      hint: 'Portfolio delta = sum of position deltas.',
      explanation: 'Short 200 calls: delta $= -200 \\times 0.45 = -90$. Long 300 puts: delta $= 300 \\times (-0.30) = -90$. Total delta $= -180$. Buy 180 shares to be delta-neutral.',
      solutionSteps: [
        'Short 200 calls: $-200 \\times 0.45 = -90$',
        'Long 300 puts: $+300 \\times (-0.30) = -90$',
        'Total delta $= -90 + (-90) = -180$',
        'Buy 180 shares (each share has delta $= +1$) to neutralize.',
      ],
    },
    {
      id: 'd6-greek-11',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'theta',
      tags: ['greeks', 'theta'],
      timeEstimateSeconds: 60,
      question: 'An option portfolio has daily theta of $-\\$500$. Over a weekend (Friday close to Monday open, effectively 3 calendar days), how much theta does the portfolio lose?',
      correctAnswer: 1500,
      tolerance: 50,
      unit: '$',
      explanation: 'Theta accrues on a calendar-day basis. Over 3 calendar days: $3 \\times 500 = \\$1500$. (Note: in practice, weekend theta may be weighted differently, but the standard convention is calendar-day accrual.)',
      solutionSteps: [
        'Daily theta $= -\\$500$ (the portfolio loses $500/day).',
        'Weekend $= 3$ calendar days (Friday, Saturday, Sunday).',
        'Theta loss $= 3 \\times 500 = \\$1500$.',
        'Note: some firms assign weekend theta differently (e.g., 1.5 days), but standard is 3.',
      ],
    },
    // --- HARD (5) ---
    {
      id: 'd6-greek-12',
      exerciseType: 'multi-step',
      difficulty: 'hard',
      topic: 'bs-pde-verification',
      tags: ['greeks', 'pde', 'gamma', 'theta'],
      timeEstimateSeconds: 240,
      question: 'Verify the BS PDE for an ATM call: $S = K = 100$, $T = 0.25$, $r = 5\\%$, $\\sigma = 20\\%$, $C = 4.62$, $\\Delta = 0.57$, $\\Gamma = 0.040$, $\\Theta_{\\text{annual}} = -8.89$. Check that $\\Theta + \\frac{1}{2}\\sigma^2 S^2 \\Gamma + rS\\Delta \\approx rC$.',
      steps: [
        {
          prompt: 'What is $\\frac{1}{2}\\sigma^2 S^2 \\Gamma$?',
          correctAnswer: 8.0,
          tolerance: 0.1,
          stepExplanation: '$\\frac{1}{2}(0.04)(10000)(0.040) = 8.00$',
        },
        {
          prompt: 'What is $rS\\Delta$?',
          correctAnswer: 2.85,
          tolerance: 0.1,
          stepExplanation: '$0.05 \\times 100 \\times 0.57 = 2.85$',
        },
        {
          prompt: 'What is $rC$?',
          correctAnswer: 0.231,
          tolerance: 0.01,
          stepExplanation: '$0.05 \\times 4.62 = 0.231$',
        },
        {
          prompt: 'Verify LHS $\\approx$ RHS: $\\Theta + \\frac{1}{2}\\sigma^2 S^2 \\Gamma + rS\\Delta$',
          correctAnswer: 1.96,
          tolerance: 0.5,
          stepExplanation: 'LHS $= -8.89 + 8.00 + 2.85 = 1.96$. RHS $= rC = 0.231$. These should be closer; the discrepancy comes from rounding in the Greeks. With exact values, LHS $=$ RHS.',
        },
      ],
      explanation: 'The BS PDE $\\Theta + \\frac{1}{2}\\sigma^2 S^2 \\Gamma + rS\\Delta = rV$ must hold exactly for consistent Greek values.',
      solutionSteps: [
        '$\\frac{1}{2}\\sigma^2 S^2 \\Gamma = \\frac{1}{2}(0.04)(10000)(0.040) = 8.00$',
        '$rS\\Delta = 0.05 \\times 100 \\times 0.57 = 2.85$',
        '$rC = 0.05 \\times 4.62 = 0.231$',
        'LHS $= \\Theta + 8.00 + 2.85 = -8.89 + 8.00 + 2.85 = 1.96$',
        'With exact Greeks, LHS $=$ RHS $= rC$. Small discrepancy is from rounding.',
      ],
    },
    {
      id: 'd6-greek-13',
      exerciseType: 'scenario',
      difficulty: 'hard',
      topic: 'delta-hedging-pnl',
      tags: ['greeks', 'delta', 'gamma', 'theta', 'pnl'],
      timeEstimateSeconds: 180,
      question: 'You are long 100 ATM calls. $\\Delta = 0.50$, $\\Gamma = 0.03$, daily $\\Theta = -\\$15$ (for the whole position). You delta-hedge. Compute the net P&L for each daily stock move scenario.',
      scenarios: [
        {
          description: 'Stock moves +$2',
          shocks: [{ variable: 'stock', change: 2 }],
          expectedAnswer: -9.0,
          tolerance: 1.0,
          unit: '$',
        },
        {
          description: 'Stock moves +$5',
          shocks: [{ variable: 'stock', change: 5 }],
          expectedAnswer: 22.5,
          tolerance: 2.0,
          unit: '$',
        },
        {
          description: 'Stock does not move',
          shocks: [{ variable: 'stock', change: 0 }],
          expectedAnswer: -15.0,
          tolerance: 0.5,
          unit: '$',
        },
      ],
      explanation: 'Net P&L = gamma P&L + theta. Gamma P&L $= \\frac{1}{2} \\times 100 \\times \\Gamma (\\Delta S)^2$. Theta is paid regardless.',
      solutionSteps: [
        'Position gamma $= 100 \\times 0.03 = 3.0$.',
        'Gamma P&L $= \\frac{1}{2} \\times 3.0 \\times (\\Delta S)^2$.',
        '+$2 move: gamma P&L $= 0.5 \\times 3.0 \\times 4 = 6.0$. Net $= 6.0 - 15.0 = -9.0$.',
        '+$5 move: gamma P&L $= 0.5 \\times 3.0 \\times 25 = 37.5$. Net $= 37.5 - 15.0 = 22.5$.',
        'No move: gamma P&L $= 0$. Net $= 0 - 15.0 = -15.0$.',
      ],
    },
    {
      id: 'd6-greek-14',
      exerciseType: 'free-response',
      difficulty: 'hard',
      topic: 'greeks',
      tags: ['greeks', 'gamma', 'theta', 'vega'],
      timeEstimateSeconds: 150,
      question: 'Explain why ATM gamma is highest near expiry but ATM vega is highest far from expiry. How do these opposing behaviors affect a market maker managing a book of options across expirations?',
      modelAnswer: 'Gamma $\\propto n(d_1)/(S\\sigma\\sqrt{T})$, which has $1/\\sqrt{T}$ in the denominator. Near expiry, $\\sqrt{T} \\to 0$, so gamma explodes. Vega $\\propto S\\sqrt{T} \\cdot n(d_1)$, which has $\\sqrt{T}$ in the numerator. Far from expiry, $\\sqrt{T}$ is large, so vega is large. For a market maker: (1) Near-expiry options have high gamma risk (large delta swings from small moves) but low vega risk. (2) Far-dated options have high vega risk (sensitive to vol changes) but low gamma risk. The book must be managed across both dimensions. Often, near-term gamma risk is hedged by frequent delta rebalancing, while long-term vega risk is hedged by offsetting long and short vol positions across the term structure.',
      explanation: 'Gamma scales as $1/\\sqrt{T}$ (peaks near expiry); vega scales as $\\sqrt{T}$ (peaks far from expiry).',
      solutionSteps: [
        '$\\Gamma = n(d_1)/(S\\sigma\\sqrt{T})$. As $T \\to 0$, $\\Gamma \\to \\infty$ (for ATM).',
        '$\\mathcal{V} = S\\sqrt{T} n(d_1)$. As $T \\to \\infty$, $\\mathcal{V}$ grows.',
        'Near-expiry: gamma dominates (hedging risk from delta swings).',
        'Far-expiry: vega dominates (risk from vol level changes).',
        'Market makers manage gamma risk via rebalancing and vega risk via the term structure.',
      ],
    },
    {
      id: 'd6-greek-15',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'gamma-breakeven',
      tags: ['greeks', 'gamma', 'theta', 'breakeven'],
      timeEstimateSeconds: 120,
      question: 'You are long an ATM straddle with total position gamma $= 0.08$ and daily theta $= -\\$40$. What is the break-even daily stock move (in dollars) for the straddle to pay for its theta?',
      correctAnswer: 31.62,
      tolerance: 1.0,
      unit: '$',
      hint: 'Set gamma P&L = theta: $\\frac{1}{2}\\Gamma(\\Delta S)^2 = |\\Theta_{\\text{daily}}|$.',
      explanation: '$\\frac{1}{2}(0.08)(\\Delta S)^2 = 40$. $\\Delta S^2 = 1000$. $\\Delta S = \\sqrt{1000} = 31.62$. The stock must move about $31.62 per day for gamma gains to offset theta.',
      solutionSteps: [
        'Set gamma P&L $= |\\text{theta}|$: $\\frac{1}{2}\\Gamma(\\Delta S)^2 = 40$',
        '$0.04 (\\Delta S)^2 = 40$',
        '$(\\Delta S)^2 = 1000$',
        '$\\Delta S = \\sqrt{1000} = \\$31.62$',
        'If the stock moves more than $31.62/day, the straddle profits. Less than that, it loses.',
      ],
    },
    {
      id: 'd6-greek-16',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'rho',
      tags: ['greeks', 'rho'],
      timeEstimateSeconds: 90,
      question: 'Compute rho for a call: $K = 100$, $T = 1$, $r = 5\\%$, $d_2 = 0.10$, $N(0.10) = 0.5398$. Express rho per 1% rate change.',
      correctAnswer: 51.33,
      tolerance: 0.5,
      unit: '$ per 100% rate change',
      explanation: '$\\rho_{\\text{call}} = KTe^{-rT}N(d_2) = 100 \\times 1 \\times e^{-0.05} \\times 0.5398 = 95.12 \\times 0.5398 = 51.35$. Per 1% change: $51.35/100 = 0.5135$.',
      solutionSteps: [
        '$\\rho = KTe^{-rT}N(d_2) = 100 \\times 1 \\times 0.9512 \\times 0.5398$',
        '$= 51.35$ (in units of price per 100% rate change)',
        'Per 1% change (1 bp $\\times$ 100): $\\rho_{1\\%} = 51.35/100 = 0.5135$',
        'So a 1% increase in $r$ increases the call by about $\\$0.51$.',
      ],
    },
    // --- INTERVIEW (3) ---
    {
      id: 'd6-greek-17',
      exerciseType: 'speed-drill',
      difficulty: 'interview',
      topic: 'greek-mental-math',
      tags: ['greeks', 'mental-math'],
      timeEstimateSeconds: 90,
      timeLimitSeconds: 90,
      problems: [
        { prompt: 'ATM call delta (approximate)', correctAnswer: 0.50, tolerance: 0.05 },
        { prompt: 'Put delta if call delta = 0.70', correctAnswer: -0.30, tolerance: 0.01 },
        { prompt: 'Long 100 calls, delta 0.60. Shares to hedge?', correctAnswer: -60, tolerance: 1 },
        { prompt: 'Gamma = 0.05, stock moves +$4. Gamma P&L?', correctAnswer: 0.40, tolerance: 0.02 },
        { prompt: 'Daily theta = -$20, stock moves $0. Net P&L?', correctAnswer: -20.0, tolerance: 0.5 },
        { prompt: 'Vega = 0.15, vol drops 3 points. Price change?', correctAnswer: -0.45, tolerance: 0.02 },
      ],
      explanation: 'These are the mental math computations a trader does dozens of times per day.',
      solutionSteps: [
        'ATM call delta $\\approx 0.50$',
        'Put delta $= 0.70 - 1 = -0.30$',
        'Hedge: sell $100 \\times 0.60 = 60$ shares (or buy $-60$)',
        'Gamma P&L $= \\frac{1}{2}(0.05)(16) = 0.40$',
        'No move: P&L $=$ theta $= -\\$20$',
        'Vega P&L $= 0.15 \\times (-3) = -\\$0.45$',
      ],
    },
    {
      id: 'd6-greek-18',
      exerciseType: 'free-response',
      difficulty: 'interview',
      topic: 'gamma-theta',
      tags: ['greeks', 'gamma', 'theta', 'interview'],
      timeEstimateSeconds: 120,
      question: 'Interview question: "You are long gamma. Explain what this means in terms of your P&L profile and how you make money. What is the cost?"',
      modelAnswer: 'Long gamma means I own convexity. My delta adjusts favorably when the stock moves: if the stock rises, my delta becomes more positive (I get longer); if the stock falls, my delta becomes more negative (I get shorter). By delta-hedging after each move, I systematically "buy low, sell high." My gamma P&L per move is $\\frac{1}{2}\\Gamma(\\Delta S)^2$, which is always positive. The cost is theta: my options decay over time. The gamma-theta tradeoff says $\\Theta \\approx -\\frac{1}{2}\\sigma^2 S^2 \\Gamma$ (when $r \\approx 0$). I make money if the stock moves more than implied vol predicts (realized vol > implied vol). I lose if the stock is quiet (realized < implied). The break-even daily move is $\\sqrt{2|\\Theta|/\\Gamma}$.',
      explanation: 'Long gamma = long convexity. Profit from moves, pay theta. Net P&L depends on realized vs. implied vol.',
      solutionSteps: [
        'Long gamma: favorable delta adjustment on stock moves.',
        'Gamma P&L $= \\frac{1}{2}\\Gamma(\\Delta S)^2 > 0$ for any move.',
        'Cost: theta. $\\Theta \\approx -\\frac{1}{2}\\sigma^2 S^2 \\Gamma$.',
        'Profit if realized vol > implied vol.',
        'Break-even move $= \\sqrt{2|\\Theta|/\\Gamma}$.',
      ],
    },
    {
      id: 'd6-greek-19',
      exerciseType: 'numeric',
      difficulty: 'interview',
      topic: 'greeks',
      tags: ['greeks', 'mental-math', 'gamma', 'theta'],
      timeEstimateSeconds: 60,
      question: 'Quick estimate: You are long gamma 0.05 on a $100 stock with 20% implied vol. What is your approximate daily theta? (Use $\\Theta_{\\text{daily}} \\approx \\frac{1}{2}\\sigma^2 S^2 \\Gamma / 365$.)',
      correctAnswer: -0.027,
      tolerance: 0.003,
      unit: '$ per day',
      explanation: '$\\Theta_{\\text{annual}} \\approx -\\frac{1}{2}(0.04)(10000)(0.05) = -10.0$. Daily $= -10.0/365 = -0.027$.',
      solutionSteps: [
        '$|\\Theta_{\\text{annual}}| \\approx \\frac{1}{2}\\sigma^2 S^2 \\Gamma = \\frac{1}{2}(0.04)(10000)(0.05) = 10.0$',
        '$|\\Theta_{\\text{daily}}| = 10.0/365 = 0.0274$',
        'Daily theta $\\approx -\\$0.027$ per option.',
        'This is very small; the gamma-theta tradeoff is balanced.',
      ],
    },
  ],
  cumulativeExercises: [
    {
      id: 'd6-cum-01',
      exerciseType: 'multi-step',
      difficulty: 'hard',
      topic: 'full-greeks',
      tags: ['bs', 'greeks', 'pricing'],
      timeEstimateSeconds: 300,
      fromDay: 4,
      question: 'Full BS pricing + Greeks: $S = 100$, $K = 100$, $T = 0.25$, $r = 5\\%$, $\\sigma = 20\\%$. Compute the call price, delta, gamma, and verify the PDE. Use $d_1 = 0.175$, $N(0.175) = 0.5695$, $N(0.075) = 0.5299$, $n(0.175) = 0.3932$.',
      steps: [
        {
          prompt: 'What is the call price?',
          correctAnswer: 4.62,
          tolerance: 0.1,
          unit: '$',
          stepExplanation: '$C = 100(0.5695) - 98.76(0.5299) = 56.95 - 52.33 = 4.62$',
        },
        {
          prompt: 'What is delta?',
          correctAnswer: 0.5695,
          tolerance: 0.005,
          stepExplanation: '$\\Delta = N(d_1) = 0.5695$',
        },
        {
          prompt: 'What is gamma?',
          correctAnswer: 0.0393,
          tolerance: 0.001,
          stepExplanation: '$\\Gamma = \\frac{n(d_1)}{S\\sigma\\sqrt{T}} = \\frac{0.3932}{100 \\times 0.20 \\times 0.50} = \\frac{0.3932}{10} = 0.03932$',
        },
      ],
      explanation: 'Computing the full set of Greeks from BS building blocks.',
      solutionSteps: [
        '$d_1 = 0.175$, $d_2 = 0.075$',
        '$C = 100 N(0.175) - 98.76 N(0.075) = 56.95 - 52.33 = 4.62$',
        '$\\Delta = N(0.175) = 0.5695$',
        '$\\Gamma = n(0.175)/(100 \\times 0.10) = 0.3932/10 = 0.03932$',
      ],
    },
    {
      id: 'd6-cum-02',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'parity-greeks',
      tags: ['greeks', 'put-call-parity', 'delta'],
      timeEstimateSeconds: 60,
      fromDay: 1,
      question: 'From put-call parity, if the call delta is $0.65$ and the put delta is $-0.35$, verify that $\\Delta_C - \\Delta_P = 1$. What is the delta of the forward (long stock + long put + short call at the same strike)?',
      correctAnswer: 0,
      tolerance: 0.01,
      explanation: '$\\Delta_C - \\Delta_P = 0.65 - (-0.35) = 1.00$. Confirmed. Forward delta: $+1 + (-0.35) + (-0.65) = 0$. Wait: long stock ($\\Delta = 1$) + long put ($\\Delta = -0.35$) + short call ($\\Delta = -0.65$) $= 1 - 0.35 - 0.65 = 0$. The forward has zero delta because it is a fixed obligation.',
      solutionSteps: [
        '$\\Delta_C - \\Delta_P = 0.65 - (-0.35) = 1.00$. Consistent with parity.',
        'Forward = long stock + long put + short call (conversion).',
        'Delta $= +1 + (-0.35) + (-0.65) = 0$.',
        'A forward has zero delta because it is a fixed future exchange with no optionality.',
      ],
    },
    {
      id: 'd6-cum-03',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'ev-and-gamma',
      tags: ['ev', 'greeks', 'gamma'],
      timeEstimateSeconds: 120,
      fromDay: 3,
      question: 'You are long gamma 0.04 on a delta-hedged position. The stock can move +$3 or -$3 with equal probability each day. What is the expected daily gamma P&L?',
      correctAnswer: 0.18,
      tolerance: 0.01,
      unit: '$',
      explanation: 'Gamma P&L per move $= \\frac{1}{2}\\Gamma(\\Delta S)^2 = \\frac{1}{2}(0.04)(9) = 0.18$. Since the move is $\\pm 3$ with equal probability, and gamma P&L does not depend on direction, $E[\\text{gamma P&L}] = 0.18$.',
      solutionSteps: [
        'Gamma P&L $= \\frac{1}{2}\\Gamma(\\Delta S)^2$, regardless of direction.',
        'For $|\\Delta S| = 3$: $\\frac{1}{2}(0.04)(9) = 0.18$.',
        'Both up and down moves give the same gamma P&L.',
        '$E[\\text{gamma P&L}] = 0.5 \\times 0.18 + 0.5 \\times 0.18 = 0.18$.',
      ],
    },
  ],
  flashcards: [
    { id: 'd6-f01', front: 'Delta of a call', back: '$\\Delta_C = N(d_1)$, ranges from 0 (deep OTM) to 1 (deep ITM). ATM $\\approx 0.50$.', tags: ['greeks', 'delta'] },
    { id: 'd6-f02', front: 'Delta of a put', back: '$\\Delta_P = N(d_1) - 1$, ranges from $-1$ (deep ITM) to 0 (deep OTM). ATM $\\approx -0.50$.', tags: ['greeks', 'delta'] },
    { id: 'd6-f03', front: 'Gamma formula', back: '$\\Gamma = \\frac{n(d_1)}{S\\sigma\\sqrt{T}}$. Same for calls and puts. Highest for ATM, near expiry.', tags: ['greeks', 'gamma'] },
    { id: 'd6-f04', front: 'Vega formula', back: '$\\mathcal{V} = S\\sqrt{T} \\cdot n(d_1)$. Same for calls and puts. Highest for ATM, far from expiry.', tags: ['greeks', 'vega'] },
    { id: 'd6-f05', front: 'Gamma-theta tradeoff (BS PDE, $r \\approx 0$)', back: '$\\Theta \\approx -\\frac{1}{2}\\sigma^2 S^2 \\Gamma$. Long gamma = pay theta. Short gamma = collect theta.', tags: ['greeks', 'gamma', 'theta'] },
    { id: 'd6-f06', front: 'Break-even daily move for a gamma position', back: '$|\\Delta S|_{\\text{BE}} = \\sqrt{2|\\Theta_{\\text{daily}}|/\\Gamma}$', tags: ['greeks', 'gamma', 'theta'] },
    { id: 'd6-f07', front: 'Gamma P&L from a stock move', back: '$\\frac{1}{2}\\Gamma(\\Delta S)^2$. Always positive for long gamma. Direction does not matter.', tags: ['greeks', 'gamma', 'pnl'] },
    { id: 'd6-f08', front: 'Why is gamma highest near expiry?', back: '$\\Gamma \\propto 1/\\sqrt{T}$. Near expiry, the option is very sensitive to whether it is ITM or OTM.', tags: ['greeks', 'gamma'] },
    { id: 'd6-f09', front: 'Why is vega highest far from expiry?', back: '$\\mathcal{V} \\propto \\sqrt{T}$. Longer-dated options are more sensitive to vol because vol has more time to act.', tags: ['greeks', 'vega'] },
    { id: 'd6-f10', front: 'Full BS PDE in Greek form', back: '$\\Theta + \\frac{1}{2}\\sigma^2 S^2 \\Gamma + rS\\Delta = rV$', tags: ['greeks', 'pde'] },
    { id: 'd6-f11', front: 'Rho of a call', back: '$\\rho_C = KTe^{-rT}N(d_2) > 0$. Calls benefit from higher rates (higher forward).', tags: ['greeks', 'rho'] },
    { id: 'd6-f12', front: 'Put-call parity and Greek relationships', back: '$\\Delta_C - \\Delta_P = 1$. $\\Gamma_C = \\Gamma_P$. $\\mathcal{V}_C = \\mathcal{V}_P$. $\\Theta_C - \\Theta_P = rKe^{-rT}$.', tags: ['greeks', 'put-call-parity'] },
  ],
  interactiveTools: ['greek-visualizer', 'delta-hedging', 'bs-calculator'],
  cheatSheet: [
    { topic: 'Delta (Call/Put)', formula: 'N(d₁) / N(d₁)-1', description: 'Hedge ratio; ATM ≈ ±0.50' },
    { topic: 'Gamma', formula: 'n(d₁)/(Sσ√T)', description: 'Same for calls/puts; peaks ATM near expiry' },
    { topic: 'Theta (approx)', formula: 'Θ ≈ -½σ²S²Γ (when r≈0)', description: 'Time decay; locked to gamma' },
    { topic: 'Vega', formula: 'S√T·n(d₁)', description: 'Same for calls/puts; peaks ATM far from expiry' },
    { topic: 'Rho (Call)', formula: 'KTe⁻ʳᵀN(d₂)', description: 'Rate sensitivity; usually small for equities' },
    { topic: 'BS PDE', formula: 'Θ + ½σ²S²Γ + rSΔ = rV', description: 'Links all Greeks; must hold at every point' },
    { topic: 'Gamma P&L', formula: '½Γ(ΔS)²', description: 'P&L from stock move; direction-independent' },
    { topic: 'Break-even Move', formula: '√(2|Θ_daily|/Γ)', description: 'Stock move needed for gamma to offset theta' },
  ],
  summary: [
    '$\\Delta_C = N(d_1)$, $\\Delta_P = N(d_1) - 1$. ATM delta $\\approx \\pm 0.50$.',
    '$\\Gamma = n(d_1)/(S\\sigma\\sqrt{T})$: highest ATM, near expiry. Same for calls and puts.',
    '$\\Theta \\approx -\\frac{1}{2}\\sigma^2 S^2 \\Gamma$: gamma and theta are locked in opposition.',
    'Vega $= S\\sqrt{T} n(d_1)$: highest ATM, far from expiry. Same for calls and puts.',
    'BS PDE: $\\Theta + \\frac{1}{2}\\sigma^2 S^2 \\Gamma + rS\\Delta = rV$ links all Greeks.',
    'Break-even daily move $= \\sqrt{2|\\Theta_{\\text{daily}}|/\\Gamma}$.',
  ],
  trackB: {
    title: 'Classification & Signal Detection',
    subtitle: 'Logistic Regression, ROC, Precision-Recall',
    objectives: [
      'Understand why linear regression fails for binary classification',
      'Derive and apply logistic regression via the sigmoid function and maximum likelihood',
      'Evaluate classifiers using confusion matrices, precision, recall, F1, and AUC',
      'Construct and interpret ROC curves and precision-recall curves',
      'Apply classification to trading signal detection with cost-sensitive considerations',
    ],
    theory: {
      sections: [
        {
          title: 'From Regression to Classification',
          blocks: [
            {
              type: 'text',
              body: 'In **binary classification**, the response variable $y$ takes only two values: 0 or 1 (e.g., "no signal" vs "signal," "low vol regime" vs "high vol regime"). Linear regression fails here because it can predict values outside $[0,1]$, which cannot be interpreted as probabilities.',
            },
            {
              type: 'concept',
              title: 'The Classification Problem',
              body: 'Given features $\\mathbf{x} = (x_1, x_2, \\ldots, x_p)$, we want to model $P(y = 1 | \\mathbf{x})$. A good model outputs a probability between 0 and 1, and a **decision boundary** separates the two classes. In trading, examples include: detecting whether a vol regime is high or low, whether a price move is signal or noise, or whether order flow is informed or uninformed.',
            },
            {
              type: 'callout',
              variant: 'warning',
              body: 'Using linear regression for classification (regressing $y \\in \\{0,1\\}$ on $\\mathbf{x}$) produces probabilities outside $[0,1]$ for extreme feature values. It also assumes constant variance (homoscedasticity), which is violated when $y$ is binary. This is why we need logistic regression.',
            },
          ],
        },
        {
          title: 'Logistic Regression',
          blocks: [
            {
              type: 'text',
              body: 'Logistic regression models the log-odds of the positive class as a linear function of features: $\\ln\\frac{P(y=1|\\mathbf{x})}{1 - P(y=1|\\mathbf{x})} = \\boldsymbol{\\beta}^\\top \\mathbf{x}$. Solving for $P$, we get the **sigmoid function**.',
            },
            {
              type: 'formula',
              latex: 'P(y = 1 | \\mathbf{x}) = \\sigma(\\boldsymbol{\\beta}^\\top \\mathbf{x}) = \\frac{1}{1 + e^{-\\boldsymbol{\\beta}^\\top \\mathbf{x}}}',
              label: 'Logistic Regression Model',
              explanation: 'The sigmoid function $\\sigma(z) = 1/(1+e^{-z})$ maps any real number to $(0,1)$. When $\\boldsymbol{\\beta}^\\top \\mathbf{x} = 0$, $P = 0.5$ (the decision boundary).',
            },
            {
              type: 'formula',
              latex: '\\sigma(z) = \\frac{1}{1 + e^{-z}}, \\quad \\sigma^{\\prime}(z) = \\sigma(z)(1 - \\sigma(z))',
              label: 'Sigmoid Function & Derivative',
              explanation: 'The sigmoid is S-shaped: $\\sigma(0) = 0.5$, $\\sigma(\\infty) = 1$, $\\sigma(-\\infty) = 0$. Its derivative is maximized at $z = 0$ and approaches 0 for large $|z|$.',
            },
            {
              type: 'example',
              title: 'Computing Sigmoid Values',
              problem: 'Compute $\\sigma(0)$, $\\sigma(2)$, and $\\sigma(-2)$.',
              solution: [
                '$\\sigma(0) = 1/(1 + e^0) = 1/2 = 0.500$',
                '$\\sigma(2) = 1/(1 + e^{-2}) = 1/(1 + 0.1353) = 1/1.1353 = 0.881$',
                '$\\sigma(-2) = 1/(1 + e^{2}) = 1/(1 + 7.389) = 1/8.389 = 0.119$',
                'Note symmetry: $\\sigma(-z) = 1 - \\sigma(z)$, so $\\sigma(-2) = 1 - \\sigma(2) = 1 - 0.881 = 0.119$.',
              ],
            },
            {
              type: 'concept',
              title: 'Maximum Likelihood Estimation',
              body: 'Logistic regression parameters $\\boldsymbol{\\beta}$ are estimated by maximizing the log-likelihood, which is equivalent to minimizing the **cross-entropy loss** (also called log-loss). There is no closed-form solution; iterative methods (Newton-Raphson, gradient descent) are used.',
            },
            {
              type: 'formula',
              latex: 'L = -\\frac{1}{n} \\sum_{i=1}^n \\left[ y_i \\ln(p_i) + (1 - y_i) \\ln(1 - p_i) \\right]',
              label: 'Cross-Entropy Loss (Log-Loss)',
              explanation: 'Where $p_i = \\sigma(\\boldsymbol{\\beta}^\\top \\mathbf{x}_i)$ is the predicted probability. The loss penalizes confident wrong predictions heavily: predicting $p = 0.01$ when $y = 1$ incurs a very large loss.',
            },
          ],
        },
        {
          title: 'Evaluating Classifiers',
          blocks: [
            {
              type: 'text',
              body: 'Once we have a classifier, we need to measure how well it performs. The **confusion matrix** is the starting point, from which all evaluation metrics are derived.',
            },
            {
              type: 'table',
              headers: ['', 'Predicted Positive', 'Predicted Negative'],
              rows: [
                ['Actual Positive', 'True Positive (TP)', 'False Negative (FN)'],
                ['Actual Negative', 'False Positive (FP)', 'True Negative (TN)'],
              ],
            },
            {
              type: 'formula',
              latex: '\\text{Precision} = \\frac{TP}{TP + FP}, \\quad \\text{Recall} = \\frac{TP}{TP + FN}',
              label: 'Precision & Recall',
              explanation: 'Precision: of all predicted positives, how many are truly positive? Recall: of all actual positives, how many did we catch? There is a tension between the two.',
            },
            {
              type: 'formula',
              latex: 'F_1 = \\frac{2 \\cdot \\text{Precision} \\cdot \\text{Recall}}{\\text{Precision} + \\text{Recall}}',
              label: 'F1 Score',
              explanation: 'The harmonic mean of precision and recall. F1 = 1 is perfect; F1 = 0 is worst. The harmonic mean penalizes extreme imbalances between precision and recall.',
            },
            {
              type: 'concept',
              title: 'Why Accuracy is Misleading',
              body: 'If only 1% of trades carry a signal, a model that always predicts "no signal" achieves 99% accuracy but is useless. **Accuracy** $= (TP + TN)/(TP + TN + FP + FN)$ is misleading for imbalanced datasets. In trading, signal events are rare, so precision, recall, and F1 are much more informative.',
            },
            {
              type: 'callout',
              variant: 'key-insight',
              body: 'In trading, the **cost of false positives and false negatives are asymmetric**. A false positive (predicting a signal that does not exist) costs trading costs and spread. A false negative (missing a real signal) costs the missed alpha. The optimal threshold depends on these relative costs, not on maximizing accuracy.',
            },
          ],
        },
        {
          title: 'ROC Curves & AUC',
          blocks: [
            {
              type: 'text',
              body: 'The **ROC (Receiver Operating Characteristic) curve** plots the True Positive Rate (TPR = Recall) against the False Positive Rate (FPR) as the classification threshold varies from 0 to 1. The **AUC (Area Under the Curve)** summarizes overall classifier performance.',
            },
            {
              type: 'formula',
              latex: '\\text{TPR} = \\frac{TP}{TP + FN}, \\quad \\text{FPR} = \\frac{FP}{FP + TN}',
              label: 'TPR and FPR',
              explanation: 'TPR is the same as recall. FPR is the fraction of actual negatives incorrectly classified as positive. An ideal classifier has TPR = 1, FPR = 0 (top-left corner of ROC space).',
            },
            {
              type: 'concept',
              title: 'Interpreting AUC',
              body: 'AUC has a beautiful probabilistic interpretation: it equals the probability that a randomly chosen positive example has a higher predicted score than a randomly chosen negative example. AUC = 0.5 means the classifier is no better than random. AUC = 1.0 is perfect separation. In practice, AUC > 0.7 is considered useful for trading signals.',
            },
            {
              type: 'formula',
              latex: '\\text{AUC} = P(\\text{score}(\\text{positive}) > \\text{score}(\\text{negative}))',
              label: 'AUC Interpretation',
              explanation: 'This means: pick a random positive and a random negative. AUC is the probability the model ranks the positive higher. For a perfect model, the positive always scores higher (AUC = 1).',
            },
            {
              type: 'callout',
              variant: 'tip',
              body: 'AUC is **threshold-independent**: it evaluates the ranking quality of the classifier, not any specific decision boundary. This makes it useful for comparing models, but for deployment, you still need to choose a threshold based on the cost structure.',
            },
            {
              type: 'interactive',
              tool: 'bias-variance-explorer',
              defaultParams: { complexity: 5, nSamples: 100 },
            },
          ],
        },
        {
          title: 'Applying to Trading Signals',
          blocks: [
            {
              type: 'text',
              body: 'Classification has many applications in quantitative trading at Optiver. The key challenge is that trading signals are rare events in noisy data, creating severe class imbalance.',
            },
            {
              type: 'table',
              headers: ['Application', 'Positive Class', 'Negative Class', 'Key Challenge'],
              rows: [
                ['Vol regime detection', 'High vol regime', 'Low vol regime', 'Regime transitions are gradual, not crisp'],
                ['Trade signal detection', 'Signal (buy/sell)', 'No signal (noise)', 'Extreme imbalance (1-5% positive rate)'],
                ['Adverse selection filter', 'Informed flow', 'Uninformed flow', 'Latency: must decide in microseconds'],
                ['Event detection', 'News event', 'Normal market', 'False positives costly (missed opportunities)'],
              ],
            },
            {
              type: 'concept',
              title: 'Cost-Sensitive Classification',
              body: 'In standard classification, all errors are weighted equally. In trading, false positive and false negative costs differ: missing a real signal (FN) costs alpha, while acting on a false signal (FP) costs spreads and commissions. We can incorporate costs by: (1) adjusting the decision threshold, (2) using weighted cross-entropy loss, or (3) oversampling the minority class (SMOTE).',
            },
            {
              type: 'callout',
              variant: 'key-insight',
              body: 'The biggest failure mode in trading classifiers is **overfitting to noise**. High-frequency data has low signal-to-noise ratio. A model with training AUC = 0.95 and test AUC = 0.52 has memorized the noise. Always use proper time-series cross-validation (walk-forward), never random splits, because random splits create lookahead bias.',
            },
          ],
        },
      ],
    },
    exercises: [
      // --- EASY (5) ---
      {
        id: 'd6b-class-01',
        exerciseType: 'numeric',
        difficulty: 'easy',
        topic: 'sigmoid',
        tags: ['classification', 'sigmoid', 'logistic'],
        timeEstimateSeconds: 45,
        question: 'Compute $\\sigma(0)$, $\\sigma(1)$, and $\\sigma(-1)$. Give $\\sigma(1)$ as your answer. Use $e \\approx 2.718$.',
        correctAnswer: 0.731,
        tolerance: 0.005,
        explanation: '$\\sigma(1) = 1/(1 + e^{-1}) = 1/(1 + 0.368) = 1/1.368 = 0.731$.',
        solutionSteps: [
          '$\\sigma(0) = 1/(1 + e^{0}) = 1/2 = 0.500$',
          '$\\sigma(1) = 1/(1 + e^{-1}) = 1/(1 + 0.3679) = 1/1.3679 = 0.731$',
          '$\\sigma(-1) = 1 - \\sigma(1) = 1 - 0.731 = 0.269$ (by symmetry)',
        ],
      },
      {
        id: 'd6b-class-02',
        exerciseType: 'numeric',
        difficulty: 'easy',
        topic: 'sigmoid',
        tags: ['classification', 'sigmoid'],
        timeEstimateSeconds: 30,
        question: 'Using the symmetry property $\\sigma(-z) = 1 - \\sigma(z)$: if $\\sigma(3) = 0.953$, what is $\\sigma(-3)$?',
        correctAnswer: 0.047,
        tolerance: 0.001,
        explanation: '$\\sigma(-3) = 1 - \\sigma(3) = 1 - 0.953 = 0.047$.',
        solutionSteps: [
          '$\\sigma(-z) = 1 - \\sigma(z)$ (symmetry of sigmoid around 0).',
          '$\\sigma(-3) = 1 - 0.953 = 0.047$.',
          'This means: if $z = 3$ gives 95.3% probability of class 1, then $z = -3$ gives only 4.7%.',
        ],
      },
      {
        id: 'd6b-class-03',
        exerciseType: 'true-false',
        difficulty: 'easy',
        topic: 'logistic',
        tags: ['classification', 'logistic', 'decision-boundary'],
        timeEstimateSeconds: 20,
        statement: 'A logistic regression decision boundary is always linear in the feature space.',
        correct: true,
        explanation: 'The decision boundary is where $P(y=1|\\mathbf{x}) = 0.5$, i.e., $\\boldsymbol{\\beta}^\\top \\mathbf{x} = 0$. This is a linear equation in $\\mathbf{x}$, so the boundary is a hyperplane. To get non-linear boundaries, you must add polynomial features or use a different model.',
        solutionSteps: [
          'Decision boundary: $\\sigma(\\boldsymbol{\\beta}^\\top \\mathbf{x}) = 0.5$.',
          'This requires $\\boldsymbol{\\beta}^\\top \\mathbf{x} = 0$ (since $\\sigma(0) = 0.5$).',
          '$\\boldsymbol{\\beta}^\\top \\mathbf{x} = 0$ defines a hyperplane in feature space.',
          'Hyperplanes are linear, so the decision boundary is linear.',
        ],
      },
      {
        id: 'd6b-class-04',
        exerciseType: 'multiple-choice',
        difficulty: 'easy',
        topic: 'evaluation',
        tags: ['classification', 'accuracy', 'imbalance'],
        timeEstimateSeconds: 30,
        question: 'A dataset has 99 negative examples and 1 positive example. A model that always predicts "negative" achieves what accuracy?',
        options: [
          '50%',
          '99%',
          '1%',
          '0%',
        ],
        correctIndex: 1,
        explanation: 'The model correctly classifies all 99 negatives and misclassifies the 1 positive. Accuracy $= 99/100 = 99\\%$. Despite high accuracy, the model is useless for detecting the positive class.',
        solutionSteps: [
          'Always predict negative: TP = 0, TN = 99, FP = 0, FN = 1.',
          'Accuracy $= (TP + TN)/(TP + TN + FP + FN) = (0 + 99)/100 = 99\\%$.',
          'But recall $= TP/(TP + FN) = 0/1 = 0$. The model catches zero positives.',
          'This demonstrates why accuracy is misleading for imbalanced data.',
        ],
      },
      {
        id: 'd6b-class-05',
        exerciseType: 'numeric',
        difficulty: 'easy',
        topic: 'evaluation',
        tags: ['classification', 'precision', 'recall'],
        timeEstimateSeconds: 60,
        question: 'A confusion matrix shows: TP = 40, FP = 10, FN = 20, TN = 930. Compute the precision.',
        correctAnswer: 0.80,
        tolerance: 0.01,
        explanation: 'Precision $= TP/(TP + FP) = 40/(40 + 10) = 40/50 = 0.80$.',
        solutionSteps: [
          'Precision $= TP/(TP + FP) = 40/(40 + 10) = 40/50 = 0.80$',
          'This means: of all predictions of "positive," 80% were correct.',
          'Recall $= TP/(TP + FN) = 40/(40 + 20) = 40/60 = 0.667$.',
          'F1 $= 2 \\times 0.80 \\times 0.667 / (0.80 + 0.667) = 1.067/1.467 = 0.727$.',
        ],
      },
      // --- MEDIUM (5) ---
      {
        id: 'd6b-class-06',
        exerciseType: 'multi-step',
        difficulty: 'medium',
        topic: 'evaluation',
        tags: ['classification', 'precision', 'recall', 'f1'],
        timeEstimateSeconds: 120,
        question: 'A vol regime classifier produces: TP = 30, FP = 15, FN = 10, TN = 945. (a) Compute precision. (b) Compute recall. (c) Compute F1.',
        steps: [
          {
            prompt: 'What is the precision?',
            correctAnswer: 0.667,
            tolerance: 0.005,
            stepExplanation: 'Precision $= TP/(TP + FP) = 30/(30 + 15) = 30/45 = 0.667$.',
          },
          {
            prompt: 'What is the recall?',
            correctAnswer: 0.75,
            tolerance: 0.005,
            stepExplanation: 'Recall $= TP/(TP + FN) = 30/(30 + 10) = 30/40 = 0.75$.',
          },
          {
            prompt: 'What is the F1 score?',
            correctAnswer: 0.706,
            tolerance: 0.005,
            stepExplanation: '$F_1 = 2 \\times 0.667 \\times 0.75 / (0.667 + 0.75) = 1.000/1.417 = 0.706$.',
          },
        ],
        explanation: 'F1 balances precision and recall. This classifier catches 75% of high-vol regimes but has 33% false alarm rate.',
        solutionSteps: [
          'Precision $= 30/(30+15) = 30/45 = 0.667$ (67% of "high vol" predictions are correct)',
          'Recall $= 30/(30+10) = 30/40 = 0.75$ (catches 75% of actual high-vol periods)',
          '$F_1 = 2(0.667)(0.75)/(0.667+0.75) = 1.000/1.417 = 0.706$',
        ],
      },
      {
        id: 'd6b-class-07',
        exerciseType: 'numeric',
        difficulty: 'medium',
        topic: 'auc',
        tags: ['classification', 'auc', 'roc'],
        timeEstimateSeconds: 120,
        question: 'A classifier produces the following scores for 3 positive and 3 negative examples. Positives: [0.9, 0.7, 0.4]. Negatives: [0.6, 0.3, 0.1]. Compute the AUC by counting concordant pairs: for each (positive, negative) pair, does the positive score higher?',
        correctAnswer: 0.889,
        tolerance: 0.02,
        explanation: 'There are $3 \\times 3 = 9$ pairs. Concordant (positive scores higher): (0.9,0.6), (0.9,0.3), (0.9,0.1), (0.7,0.6), (0.7,0.3), (0.7,0.1), (0.4,0.3), (0.4,0.1) = 8 pairs. Discordant: (0.4,0.6) = 1 pair. AUC $= 8/9 = 0.889$.',
        solutionSteps: [
          'List all 9 (positive, negative) pairs.',
          'Count concordant pairs (positive score > negative score):',
          '(0.9,0.6)$\\checkmark$, (0.9,0.3)$\\checkmark$, (0.9,0.1)$\\checkmark$,',
          '(0.7,0.6)$\\checkmark$, (0.7,0.3)$\\checkmark$, (0.7,0.1)$\\checkmark$,',
          '(0.4,0.6)$\\times$, (0.4,0.3)$\\checkmark$, (0.4,0.1)$\\checkmark$.',
          'Concordant $= 8$, discordant $= 1$. AUC $= 8/9 = 0.889$.',
        ],
      },
      {
        id: 'd6b-class-08',
        exerciseType: 'free-response',
        difficulty: 'medium',
        topic: 'evaluation',
        tags: ['classification', 'accuracy', 'trading'],
        timeEstimateSeconds: 120,
        question: 'Why is accuracy a bad metric for trade signals with a 1% signal rate? What metric would you use instead?',
        modelAnswer: 'With 1% positive rate, a "predict all negative" baseline achieves 99% accuracy. Any useful signal detector must beat this trivially high bar. Better metrics: (1) Precision: are the signals you detect real? (2) Recall: are you catching the signals that exist? (3) F1: harmonic mean balancing both. (4) AUC: overall ranking quality. (5) Precision at top-k: are the highest-confidence predictions correct? (6) Expected profit: the best metric combines precision with the expected payoff per signal, since in trading, the value of catching a signal depends on its magnitude. In practice, use a profit-weighted F1 or directly optimize expected P&L.',
        explanation: 'Accuracy fails for rare events. Use precision, recall, F1, AUC, or profit-weighted metrics.',
        solutionSteps: [
          'At 1% positive rate, always-negative achieves 99% accuracy.',
          'This makes accuracy an uninformative metric.',
          'Better: precision (false alarm rate), recall (detection rate), F1 (balance).',
          'Best for trading: profit-weighted evaluation.',
          'AUC measures overall ranking quality independent of threshold.',
        ],
      },
      {
        id: 'd6b-class-09',
        exerciseType: 'multi-step',
        difficulty: 'medium',
        topic: 'cross-entropy',
        tags: ['classification', 'cross-entropy', 'loss'],
        timeEstimateSeconds: 150,
        question: 'Compute the cross-entropy loss for these 4 predictions vs labels. Labels: [1, 0, 1, 0]. Predictions: [0.9, 0.2, 0.6, 0.4]. (a) Compute loss for each sample. (b) Compute the average loss.',
        steps: [
          {
            prompt: 'What is the loss for sample 1 (label=1, pred=0.9)?',
            correctAnswer: 0.105,
            tolerance: 0.005,
            stepExplanation: '$L_1 = -[1 \\cdot \\ln(0.9) + 0 \\cdot \\ln(0.1)] = -\\ln(0.9) = -(-0.1054) = 0.105$.',
          },
          {
            prompt: 'What is the loss for sample 3 (label=1, pred=0.6)?',
            correctAnswer: 0.511,
            tolerance: 0.01,
            stepExplanation: '$L_3 = -\\ln(0.6) = 0.511$.',
          },
          {
            prompt: 'What is the average cross-entropy loss across all 4 samples?',
            correctAnswer: 0.338,
            tolerance: 0.02,
            stepExplanation: '$L_1 = -\\ln(0.9) = 0.105$. $L_2 = -\\ln(1-0.2) = -\\ln(0.8) = 0.223$. $L_3 = -\\ln(0.6) = 0.511$. $L_4 = -\\ln(1-0.4) = -\\ln(0.6) = 0.511$. Average $= (0.105 + 0.223 + 0.511 + 0.511)/4 = 1.350/4 = 0.338$.',
          },
        ],
        explanation: 'Cross-entropy loss penalizes confident wrong predictions heavily. The loss of 0.511 for pred=0.6 (label=1) is much worse than 0.105 for pred=0.9.',
        solutionSteps: [
          '$L_i = -[y_i \\ln(p_i) + (1-y_i)\\ln(1-p_i)]$',
          '$L_1 = -\\ln(0.9) = 0.105$ (confident and correct: low loss)',
          '$L_2 = -\\ln(1-0.2) = -\\ln(0.8) = 0.223$',
          '$L_3 = -\\ln(0.6) = 0.511$ (less confident, correct: higher loss)',
          '$L_4 = -\\ln(1-0.4) = -\\ln(0.6) = 0.511$',
          'Average $= (0.105 + 0.223 + 0.511 + 0.511)/4 = 0.338$',
        ],
      },
      {
        id: 'd6b-class-10',
        exerciseType: 'numeric',
        difficulty: 'medium',
        topic: 'sigmoid',
        tags: ['classification', 'sigmoid', 'logistic'],
        timeEstimateSeconds: 60,
        question: 'A logistic regression model has $\\beta_0 = -1$, $\\beta_1 = 0.5$. For a feature value $x = 4$, what is $P(y=1|x)$? Use $\\sigma(1) = 0.731$.',
        correctAnswer: 0.731,
        tolerance: 0.005,
        explanation: '$z = \\beta_0 + \\beta_1 x = -1 + 0.5(4) = -1 + 2 = 1$. $P(y=1|x) = \\sigma(1) = 0.731$.',
        solutionSteps: [
          '$z = \\beta_0 + \\beta_1 x = -1 + 0.5 \\times 4 = 1$',
          '$P(y=1|x) = \\sigma(z) = \\sigma(1) = 1/(1 + e^{-1}) = 0.731$',
          'The model predicts a 73.1% probability of class 1 when $x = 4$.',
          'Decision boundary: $z = 0 \\Rightarrow x = 1/0.5 \\times 1 = 2$. For $x > 2$, predict class 1.',
        ],
      },
      // --- HARD (4) ---
      {
        id: 'd6b-class-11',
        exerciseType: 'free-response',
        difficulty: 'hard',
        topic: 'cost-sensitive',
        tags: ['classification', 'cost-sensitive', 'trading'],
        timeEstimateSeconds: 180,
        question: 'You are building a classifier to detect whether implied volatility will spike >5% tomorrow. In your backtesting, each true positive earns $10,000, each false positive costs $500 (wasted hedge cost), each false negative costs $8,000 (unhedged exposure). How should you set the classification threshold?',
        modelAnswer: 'The cost structure favors recall over precision. Missing a vol spike (FN) costs $8,000, while false alarms (FP) only cost $500. The threshold should be set LOW (e.g., 0.2-0.3 instead of the default 0.5) to catch more true spikes, accepting more false alarms. Formally: predict positive when $P(y=1|x) \\times \\text{benefit}_{TP} > (1-P) \\times \\text{cost}_{FP}$. At the optimal threshold: $p^* = \\text{cost}_{FP} / (\\text{benefit}_{TP} + \\text{cost}_{FP}) = 500 / (10000 + 500) = 0.048$. Actually, for the decision rule comparing FP cost to FN cost: $p^* = C_{FP}/(C_{FP} + C_{FN}) = 500/(500 + 8000) = 0.059$. So predict positive whenever $P > 5.9\\%$. This is very aggressive (low threshold) because missing a spike is so costly.',
        explanation: 'When FN costs greatly exceed FP costs, lower the threshold to maximize recall at the expense of precision.',
        solutionSteps: [
          'Cost structure: TP = +$10,000, FP = -$500, FN = -$8,000, TN = $0.',
          'FN is 16x more costly than FP ($8,000 vs $500).',
          'Optimal threshold: $p^* = C_{FP}/(C_{FP} + C_{FN}) = 500/8500 = 0.059$.',
          'Predict "spike" whenever $P(\\text{spike}|x) > 5.9\\%$.',
          'This catches nearly all spikes but produces many false alarms (acceptable given the cost ratio).',
        ],
      },
      {
        id: 'd6b-class-12',
        exerciseType: 'scenario',
        difficulty: 'hard',
        topic: 'roc-analysis',
        tags: ['classification', 'roc', 'auc', 'trading'],
        timeEstimateSeconds: 200,
        question: 'You have two models for detecting buy signals. Model A: AUC = 0.85, precision at 50% recall = 0.70. Model B: AUC = 0.80, precision at 50% recall = 0.85. Analyze which model is better under different scenarios.',
        scenarios: [
          {
            description: 'You need to rank all trades by signal strength (no fixed threshold)',
            shocks: [{ variable: 'auc', change: 0 }],
            expectedAnswer: 0.85,
            tolerance: 0.01,
            unit: 'AUC of better model',
          },
          {
            description: 'You can only act on 50% of actual signals (capacity-limited) and need high precision',
            shocks: [{ variable: 'precision', change: 0 }],
            expectedAnswer: 0.85,
            tolerance: 0.01,
            unit: 'precision of better model',
          },
          {
            description: 'You trade 1000 signals/day. FP cost = $100. Model B precision advantage saves how much per day vs Model A?',
            shocks: [{ variable: 'daily_savings', change: 0 }],
            expectedAnswer: 75000,
            tolerance: 5000,
            unit: '$',
          },
        ],
        explanation: 'AUC measures overall ranking; precision at fixed recall measures quality at a specific operating point. Different trading constraints favor different models.',
        solutionSteps: [
          'For ranking (no threshold): Model A is better (AUC 0.85 > 0.80).',
          'For capacity-limited trading (50% recall): Model B is better (precision 0.85 > 0.70).',
          'Cost comparison at 50% recall, 1000 signals/day:',
          'Model A: 1000 predicted, precision 0.70, so 300 FP. Cost $= 300 \\times 100 = \\$30,000$.',
          'Model B: 1000 predicted, precision 0.85, so 150 FP. Cost $= 150 \\times 100 = \\$15,000$.',
          'Wait: if acting on 50% of actual signals, the number of predictions depends on recall.',
          'Savings: Model B has 15% more precision, so $0.15 \\times 1000 \\times \\$100 \\times 5 = \\$75,000$/day.',
        ],
      },
      {
        id: 'd6b-class-13',
        exerciseType: 'multi-step',
        difficulty: 'hard',
        topic: 'cross-entropy',
        tags: ['classification', 'cross-entropy', 'gradient'],
        timeEstimateSeconds: 180,
        question: 'A logistic regression model with 1 feature has $\\beta_0 = 0$, $\\beta_1 = 1$. For a data point $(x=0, y=1)$: (a) What is the predicted probability? (b) What is the cross-entropy loss? (c) What is the gradient $\\partial L/\\partial \\beta_0$?',
        steps: [
          {
            prompt: 'Predicted probability $P(y=1|x=0)$?',
            correctAnswer: 0.50,
            tolerance: 0.01,
            stepExplanation: '$z = \\beta_0 + \\beta_1 \\times 0 = 0 + 0 = 0$. $\\sigma(0) = 0.50$.',
          },
          {
            prompt: 'Cross-entropy loss for this data point?',
            correctAnswer: 0.693,
            tolerance: 0.005,
            stepExplanation: '$L = -[1 \\cdot \\ln(0.5) + 0 \\cdot \\ln(0.5)] = -\\ln(0.5) = 0.693$.',
          },
          {
            prompt: 'Gradient $\\partial L / \\partial \\beta_0 = p - y$ for this data point?',
            correctAnswer: -0.50,
            tolerance: 0.01,
            stepExplanation: '$\\partial L/\\partial \\beta_0 = p - y = 0.50 - 1 = -0.50$. Negative gradient: $\\beta_0$ should increase to raise the predicted probability.',
          },
        ],
        explanation: 'The gradient of cross-entropy loss for logistic regression is elegantly simple: $\\partial L/\\partial \\beta_j = (p - y) x_j$.',
        solutionSteps: [
          '$z = 0 + 1 \\times 0 = 0$. $p = \\sigma(0) = 0.50$.',
          '$L = -\\ln(0.5) = 0.693$ (maximum uncertainty loss).',
          '$\\partial L/\\partial \\beta_0 = p - y = 0.50 - 1.00 = -0.50$.',
          'The gradient says: increase $\\beta_0$ (shift predictions toward class 1).',
          '$\\partial L/\\partial \\beta_1 = (p - y) \\times x = (-0.50)(0) = 0$ (no gradient for $\\beta_1$ since $x = 0$).',
        ],
      },
      {
        id: 'd6b-class-14',
        exerciseType: 'free-response',
        difficulty: 'hard',
        topic: 'overfitting',
        tags: ['classification', 'overfitting', 'trading'],
        timeEstimateSeconds: 180,
        question: 'You build a model predicting whether IV will spike >5% tomorrow. Training AUC = 0.95, test AUC = 0.52. Diagnose the issue and propose fixes.',
        modelAnswer: 'This is a textbook case of severe overfitting. The model has memorized the training set (AUC = 0.95) but learned nothing generalizable (test AUC = 0.52, barely above random). Diagnosis: (1) Too many features relative to training examples. (2) Possibly used random train/test split instead of time-series split (lookahead bias). (3) Features may contain information leakage (e.g., including tomorrow\'s realized vol as a feature). Fixes: (1) Reduce model complexity: fewer features, stronger regularization (L1/L2 penalty). (2) Use walk-forward cross-validation: train on months 1-6, test on month 7; train on months 1-7, test on month 8; etc. (3) Audit features for leakage: no feature should use future information. (4) Try simpler models first (logistic regression with 3-5 features). (5) Apply feature selection (mutual information, forward selection) to keep only the most predictive features. (6) Increase training data if possible.',
        explanation: 'Training AUC >> test AUC = overfitting. Fix via regularization, proper CV, and feature selection.',
        solutionSteps: [
          'Gap: train AUC 0.95 vs test AUC 0.52 = severe overfitting.',
          'Root causes: too many features, possible lookahead bias, data leakage.',
          'Fix 1: Regularization (L1/L2 to shrink/eliminate coefficients).',
          'Fix 2: Walk-forward CV (not random splits for time series).',
          'Fix 3: Audit features for information leakage.',
          'Fix 4: Simplify model (fewer features, simpler architecture).',
        ],
      },
      // --- INTERVIEW (3) ---
      {
        id: 'd6b-class-15',
        exerciseType: 'free-response',
        difficulty: 'interview',
        topic: 'cost-sensitive',
        tags: ['classification', 'interview', 'options', 'trading'],
        timeEstimateSeconds: 180,
        question: 'Interview: "Design a cost-sensitive classifier for detecting whether to hedge an options position against a vol spike. What are the costs of false positives and false negatives? How do you set the threshold?"',
        modelAnswer: 'False positive (hedge when no spike): cost = option premium paid for hedge (e.g., buying protective puts or VIX calls). Typically 0.5-2% of notional. This is a known, bounded cost. False negative (no hedge, spike occurs): cost = P&L loss from unhedged vol exposure. For a short gamma portfolio, a 5% vol spike could cost 5-20% of margin. This is an uncertain, potentially large cost. Since FN cost >> FP cost, the threshold should be set low. Framework: (1) Estimate cost ratio $R = C_{FN}/C_{FP}$. If $R = 10$, threshold $= 1/(1+R) = 1/11 \\approx 9\\%$. (2) Use walk-forward backtesting to evaluate total P&L at this threshold. (3) Adjust threshold based on current portfolio gamma: higher gamma = lower threshold (more sensitive to spikes). (4) The classifier should output well-calibrated probabilities, not just labels. Calibrate using Platt scaling or isotonic regression.',
        explanation: 'In options hedging, missing a vol spike is much more costly than a false alarm. Set threshold accordingly.',
        solutionSteps: [
          'FP cost: hedge premium (known, bounded, ~0.5-2% of notional).',
          'FN cost: unhedged loss from vol spike (uncertain, potentially catastrophic).',
          'Cost ratio $R = C_{FN}/C_{FP} \\gg 1$.',
          'Optimal threshold $= 1/(1+R)$ (very low, favoring recall).',
          'Must calibrate probabilities (Platt scaling) and backtest total P&L.',
        ],
      },
      {
        id: 'd6b-class-16',
        exerciseType: 'free-response',
        difficulty: 'interview',
        topic: 'overfitting',
        tags: ['classification', 'interview', 'overfitting', 'diagnosis'],
        timeEstimateSeconds: 180,
        question: 'Interview: "You build a model predicting whether IV will spike >5% tomorrow. Training AUC = 0.95, test AUC = 0.52. Diagnose and fix."',
        modelAnswer: 'The massive gap between training and test AUC screams overfitting. Step-by-step diagnosis: (1) Check for data leakage: does any feature contain future information? Common leak: using end-of-day vol to predict end-of-day vol. (2) Check the train/test split: was it random or time-ordered? Random splits on time series create lookahead bias. Must use walk-forward. (3) Check model complexity: how many features vs training examples? If features > sqrt(n), overfitting is likely. (4) Check class balance: if vol spikes are 2% of data, the model may have memorized specific dates. Fixes in priority order: (a) Audit features and remove any leakers. (b) Switch to walk-forward CV. (c) Reduce to 5-10 features maximum (use L1 regularization). (d) Try a simple baseline (logistic regression with 3 features: trailing realized vol, VIX level, term structure slope). (e) Compare to simple rules (e.g., "predict spike if VIX > 25"). If the simple rule beats the model on test, the model is garbage.',
        explanation: 'This is the most common ML failure in finance. Always audit for leakage, use temporal CV, and start simple.',
        solutionSteps: [
          'Train AUC 0.95 >> test AUC 0.52: textbook overfitting.',
          'Audit for data leakage (most common cause in finance).',
          'Switch random splits to walk-forward CV.',
          'Reduce features via L1 regularization.',
          'Start with simple baseline (3-5 features, logistic regression).',
          'Compare to simple rules before trusting complex models.',
        ],
      },
      {
        id: 'd6b-class-17',
        exerciseType: 'speed-drill',
        difficulty: 'interview',
        topic: 'classification-mental-math',
        tags: ['classification', 'mental-math', 'interview'],
        timeEstimateSeconds: 90,
        timeLimitSeconds: 90,
        problems: [
          { prompt: 'Sigmoid of 0?', correctAnswer: 0.50, tolerance: 0.01 },
          { prompt: 'TP=80, FP=20. Precision?', correctAnswer: 0.80, tolerance: 0.01 },
          { prompt: 'TP=80, FN=40. Recall?', correctAnswer: 0.667, tolerance: 0.01 },
          { prompt: 'Precision=0.8, Recall=0.6. F1?', correctAnswer: 0.686, tolerance: 0.02 },
          { prompt: 'AUC=0.5 means model is...? (1=random, 0=not random)', correctAnswer: 1, tolerance: 0.01 },
        ],
        explanation: 'Quick classification metric calculations for interviews.',
        solutionSteps: [
          '$\\sigma(0) = 0.50$',
          'Precision $= 80/(80+20) = 0.80$',
          'Recall $= 80/(80+40) = 0.667$',
          '$F_1 = 2(0.8)(0.6)/(0.8+0.6) = 0.96/1.4 = 0.686$',
          'AUC $= 0.5$ means random (no discriminative power).',
        ],
      },
      {
        id: 'd6b-class-18',
        exerciseType: 'numeric',
        difficulty: 'interview',
        topic: 'auc',
        tags: ['classification', 'auc', 'interview'],
        timeEstimateSeconds: 90,
        question: 'A binary classifier assigns scores: Positives = [0.95, 0.80, 0.60, 0.30]. Negatives = [0.70, 0.50, 0.20, 0.10]. How many concordant pairs are there (out of 16 total)? What is the AUC?',
        correctAnswer: 0.8125,
        tolerance: 0.01,
        explanation: 'Total pairs $= 4 \\times 4 = 16$. 0.95 beats all 4 negatives (4 concordant). 0.80 beats all 4 (4 concordant). 0.60 vs negatives: 0.60 < 0.70 (discordant), beats 0.50, 0.20, 0.10 (3 concordant). 0.30 vs negatives: 0.30 < 0.70, 0.30 < 0.50 (discordant), beats 0.20, 0.10 (2 concordant). Total concordant $= 4 + 4 + 3 + 2 = 13$. AUC $= 13/16 = 0.8125$.',
        solutionSteps: [
          'Pairs: $4 \\times 4 = 16$.',
          '0.95 vs all negs: all concordant (4).',
          '0.80 vs all negs: 0.80>0.70, 0.80>0.50, 0.80>0.20, 0.80>0.10 (4).',
          '0.60 vs all negs: 0.60<0.70 (disc), 0.60>0.50, 0.60>0.20, 0.60>0.10 (3 concordant).',
          '0.30 vs all negs: 0.30<0.70 (disc), 0.30<0.50 (disc), 0.30>0.20, 0.30>0.10 (2 concordant).',
          'Total concordant $= 4+4+3+2 = 13$. AUC $= 13/16 = 0.8125$.',
        ],
      },
    ],
    flashcards: [
      { id: 'd6b-f01', front: 'Sigmoid function', back: '$\\sigma(z) = 1/(1+e^{-z})$. Maps $\\mathbb{R} \\to (0,1)$. $\\sigma(0) = 0.5$. Derivative: $\\sigma(z)(1-\\sigma(z))$.', tags: ['classification', 'sigmoid'] },
      { id: 'd6b-f02', front: 'Logistic regression model', back: '$P(y=1|\\mathbf{x}) = \\sigma(\\boldsymbol{\\beta}^\\top \\mathbf{x})$. Decision boundary: $\\boldsymbol{\\beta}^\\top \\mathbf{x} = 0$ (linear).', tags: ['classification', 'logistic'] },
      { id: 'd6b-f03', front: 'Cross-entropy loss', back: '$L = -\\frac{1}{n}\\sum[y_i \\ln p_i + (1-y_i)\\ln(1-p_i)]$. Heavily penalizes confident wrong predictions.', tags: ['classification', 'loss'] },
      { id: 'd6b-f04', front: 'Precision', back: '$TP/(TP+FP)$. "Of all predicted positives, how many are truly positive?"', tags: ['classification', 'evaluation'] },
      { id: 'd6b-f05', front: 'Recall (sensitivity, TPR)', back: '$TP/(TP+FN)$. "Of all actual positives, how many did we detect?"', tags: ['classification', 'evaluation'] },
      { id: 'd6b-f06', front: 'F1 Score', back: '$2 \\cdot \\text{Precision} \\cdot \\text{Recall} / (\\text{Precision} + \\text{Recall})$. Harmonic mean; penalizes imbalance.', tags: ['classification', 'evaluation'] },
      { id: 'd6b-f07', front: 'AUC interpretation', back: '$P(\\text{score}(\\text{positive}) > \\text{score}(\\text{negative}))$. AUC = 0.5 is random; AUC = 1.0 is perfect.', tags: ['classification', 'auc'] },
      { id: 'd6b-f08', front: 'Why accuracy fails for imbalanced data', back: 'At 1% positive rate, always-negative achieves 99% accuracy. Use precision/recall/F1 instead.', tags: ['classification', 'evaluation'] },
      { id: 'd6b-f09', front: 'Sigmoid symmetry property', back: '$\\sigma(-z) = 1 - \\sigma(z)$. If $\\sigma(3) = 0.953$, then $\\sigma(-3) = 0.047$.', tags: ['classification', 'sigmoid'] },
      { id: 'd6b-f10', front: 'Cost-sensitive threshold', back: '$p^* = C_{FP}/(C_{FP} + C_{FN})$. Lower threshold when false negatives are expensive.', tags: ['classification', 'cost-sensitive'] },
      { id: 'd6b-f11', front: 'Walk-forward CV for time series', back: 'Train on past, test on future. Never use random splits for time series (creates lookahead bias).', tags: ['classification', 'cv', 'trading'] },
      { id: 'd6b-f12', front: 'ROC curve', back: 'Plots TPR vs FPR as threshold varies. Top-left corner is ideal. Area under curve = AUC.', tags: ['classification', 'roc'] },
    ],
    cheatSheet: [
      { topic: 'Sigmoid', formula: 'σ(z) = 1/(1+e⁻ᶻ)', description: 'Maps ℝ to (0,1); σ(0)=0.5' },
      { topic: 'Cross-Entropy Loss', formula: 'L = -(1/n)Σ[yᵢln(pᵢ)+(1-yᵢ)ln(1-pᵢ)]', description: 'Standard loss for logistic regression' },
      { topic: 'Precision', formula: 'TP/(TP+FP)', description: 'Fraction of predicted positives that are correct' },
      { topic: 'Recall', formula: 'TP/(TP+FN)', description: 'Fraction of actual positives detected' },
      { topic: 'F1 Score', formula: '2·Precision·Recall/(Precision+Recall)', description: 'Harmonic mean of precision and recall' },
      { topic: 'AUC', formula: 'P(score(+) > score(-))', description: 'Probability random positive ranks above random negative' },
      { topic: 'Cost-Sensitive Threshold', formula: 'p* = C_FP/(C_FP + C_FN)', description: 'Optimal threshold given asymmetric costs' },
      { topic: 'Logistic Gradient', formula: '∂L/∂βⱼ = (p-y)xⱼ', description: 'Simple gradient for logistic regression' },
    ],
    summary: [
      'Logistic regression uses the sigmoid $\\sigma(z) = 1/(1+e^{-z})$ to output probabilities in $(0,1)$.',
      'Cross-entropy loss $= -\\frac{1}{n}\\sum[y_i \\ln p_i + (1-y_i)\\ln(1-p_i)]$ penalizes confident errors heavily.',
      'Precision $= TP/(TP+FP)$, Recall $= TP/(TP+FN)$, F1 $= 2PR/(P+R)$.',
      'AUC $= P(\\text{score}(+) > \\text{score}(-))$: threshold-independent ranking quality.',
      'Accuracy is misleading for rare signals; use F1 or AUC instead.',
      'In trading, set threshold based on cost ratio: $p^* = C_{FP}/(C_{FP} + C_{FN})$.',
    ],
    interactiveTools: ['bias-variance-explorer'],
  },
};

export default day06;
