import { DayContent } from './types';

const day02: DayContent = {
  dayNumber: 2,
  title: 'Volatility & Lognormal Distributions',
  subtitle: 'Natenberg Chapter 4',
  week: 1,
  chapters: ['Chapter 4'],
  estimatedMinutes: 100,
  prerequisites: [1],
  objectives: [
    'Understand random walks, Brownian motion, and geometric Brownian motion (GBM)',
    'Convert between annual, daily, weekly, and period volatilities using the square-root-of-time rule',
    'Calculate 1-standard-deviation moves for a stock over any horizon',
    'Distinguish between historical and implied volatility',
    'Understand the lognormal distribution and its implications for option pricing',
  ],
  theory: {
    sections: [
      {
        title: 'Random Walks & Brownian Motion',
        blocks: [
          {
            type: 'text',
            body: 'Financial models assume that stock returns follow a **random walk**: each period\'s return is independent of previous returns. A random walk in continuous time is called **Brownian motion** (or a Wiener process). The key property is that increments are independent and normally distributed.',
          },
          {
            type: 'concept',
            title: 'Geometric Brownian Motion (GBM)',
            body: 'Stock prices cannot go negative, so we model the **log-returns** (not prices) as normally distributed. This means prices follow a **lognormal** distribution. The model is: $dS = \\mu S\\,dt + \\sigma S\\,dW$, where $\\mu$ is the drift, $\\sigma$ is the volatility, and $dW$ is a Wiener increment. Under GBM, $\\ln(S_T/S_0)$ is normally distributed with mean $(\\mu - \\sigma^2/2)T$ and variance $\\sigma^2 T$.',
          },
          {
            type: 'callout',
            variant: 'key-insight',
            body: 'The $-\\sigma^2/2$ term is crucial. Because of Jensen\'s inequality, the expected value of a lognormal variable is higher than $e$ raised to the mean of the log. The **median** of the future stock price is $S_0 e^{(\\mu - \\sigma^2/2)T}$, which is less than the **mean** $S_0 e^{\\mu T}$.',
          },
        ],
      },
      {
        title: 'Volatility: Definition & Scaling',
        blocks: [
          {
            type: 'text',
            body: 'Volatility ($\\sigma$) is the annualized standard deviation of log-returns. It is quoted on an annual basis by convention. To convert between time frames, we use the **square-root-of-time rule**, which follows directly from the property that the variance of independent increments is additive.',
          },
          {
            type: 'formula',
            latex: '\\sigma_{\\text{daily}} = \\frac{\\sigma_{\\text{annual}}}{\\sqrt{252}}',
            label: 'Annual to Daily Volatility',
            explanation: 'There are approximately 252 trading days per year. Daily vol is annual vol divided by $\\sqrt{252} \\approx 15.87$.',
          },
          {
            type: 'formula',
            latex: '\\sigma_{\\text{period}} = \\sigma_{\\text{annual}} \\times \\sqrt{T}',
            label: 'Period Volatility',
            explanation: 'For a period of $T$ years, the standard deviation of the log-return over that period is $\\sigma\\sqrt{T}$.',
          },
          {
            type: 'formula',
            latex: '\\text{1-SD move} = S \\times \\sigma_{\\text{daily}}',
            label: '1-Standard-Deviation Daily Move',
            explanation: 'This gives the dollar amount the stock is expected to move (up or down) in one day, roughly 68% of the time.',
          },
          {
            type: 'example',
            title: 'Converting Annual Vol to a Daily Move',
            problem: 'A stock trades at $100 with 25% annual volatility. What is the expected 1-SD daily move in dollar terms?',
            solution: [
              '$\\sigma_{\\text{daily}} = 25\\% / \\sqrt{252} = 0.25 / 15.87 = 1.575\\%$',
              '1-SD daily move $= 100 \\times 0.01575 = \\$1.575$',
              'So on a typical day, the stock moves about $\\$1.58$ up or down (68% of the time).',
            ],
          },
          {
            type: 'callout',
            variant: 'tip',
            body: 'Quick mental math: $\\sqrt{252} \\approx 16$. So daily vol $\\approx$ annual vol / 16. A stock with 32% annual vol has about 2% daily vol.',
          },
          {
            type: 'table',
            headers: ['Annual Vol', 'Daily Vol (÷16)', 'Weekly Vol (÷√52)', 'Monthly Vol (÷√12)'],
            rows: [
              ['16%', '1.00%', '2.22%', '4.62%'],
              ['20%', '1.25%', '2.77%', '5.77%'],
              ['25%', '1.56%', '3.47%', '7.22%'],
              ['32%', '2.00%', '4.44%', '9.24%'],
              ['40%', '2.50%', '5.55%', '11.55%'],
            ],
          },
        ],
      },
      {
        title: 'Historical vs. Implied Volatility',
        blocks: [
          {
            type: 'text',
            body: 'There are two fundamentally different types of volatility. **Historical (realized) volatility** measures how much the asset actually moved in the past. **Implied volatility** is the volatility backed out of observed option prices using a pricing model (typically Black-Scholes). They answer different questions: historical vol tells you what happened; implied vol tells you what the market expects.',
          },
          {
            type: 'concept',
            title: 'Computing Historical Volatility',
            body: 'Calculate daily log-returns $r_i = \\ln(S_i / S_{i-1})$. Compute the sample standard deviation of these returns. Annualize by multiplying by $\\sqrt{252}$. Typical lookback windows are 20 days (1 month), 60 days (3 months), or 252 days (1 year).',
          },
          {
            type: 'concept',
            title: 'Implied Volatility',
            body: 'Given an observed option price, the implied vol is the value of $\\sigma$ you plug into Black-Scholes to reproduce that price. It is not directly observable; it must be solved numerically (there is no closed-form inverse of BS). When traders say "vol is 25," they mean implied vol is 25%.',
          },
          {
            type: 'callout',
            variant: 'key-insight',
            body: 'The difference between implied and realized vol is the core driver of options trading P&L. If you buy options at 25% implied vol and the stock realizes 30% vol, you profit (all else equal). This is the essence of volatility trading at Optiver.',
          },
        ],
      },
      {
        title: 'The Lognormal Distribution',
        blocks: [
          {
            type: 'text',
            body: 'If $\\ln(X)$ is normally distributed, then $X$ is **lognormally** distributed. Stock prices are modeled as lognormal because: (1) they cannot go negative, (2) returns compound multiplicatively, and (3) the distribution is right-skewed, matching the empirical observation that large up-moves can be bigger than large down-moves.',
          },
          {
            type: 'formula',
            latex: 'E[S_T] = S_0 e^{\\mu T}',
            label: 'Expected Value of Lognormal',
            explanation: 'The expected (mean) future stock price grows at the drift rate $\\mu$. Note this is higher than $S_0 e^{(\\mu - \\sigma^2/2)T}$ (the median) because of the right skew.',
          },
          {
            type: 'formula',
            latex: '\\text{Median}(S_T) = S_0 e^{(\\mu - \\sigma^2/2)T}',
            label: 'Median of Lognormal',
            explanation: 'The median is always less than the mean for a lognormal distribution (when $\\sigma > 0$). The gap grows with $\\sigma$ and $T$.',
          },
          {
            type: 'example',
            title: 'Mean vs. Median of Future Price',
            problem: 'A stock is at $100 with $\\mu = 10\\%$ and $\\sigma = 30\\%$. What are the expected value and median of the price in 1 year?',
            solution: [
              '$E[S_1] = 100 \\cdot e^{0.10 \\times 1} = 100 \\times 1.1052 = \\$110.52$',
              '$\\text{Median}(S_1) = 100 \\cdot e^{(0.10 - 0.09/2) \\times 1} = 100 \\cdot e^{0.055} = 100 \\times 1.0566 = \\$105.65$',
              'The mean exceeds the median by about $\\$4.87$, reflecting the right skew of the lognormal distribution.',
            ],
          },
          {
            type: 'callout',
            variant: 'warning',
            body: 'Real asset returns have fatter tails than the lognormal model predicts. Crashes (left tail) and melt-ups (right tail) are more frequent than the model suggests. This is one reason out-of-the-money puts trade at higher implied vols (the "volatility skew").',
          },
        ],
      },
      {
        title: 'Weekend, Holiday & Overnight Volatility',
        blocks: [
          {
            type: 'text',
            body: 'Volatility scaling uses trading days, not calendar days, because most price discovery happens during market hours. However, events occur on weekends and holidays too. Empirically, the variance from Friday close to Monday open is only about 1.5 to 2 times the variance of a single trading day, not 3 times (as calendar time would suggest). This means weekends contribute about 50-67% of one day\'s worth of variance per calendar day off.',
          },
          {
            type: 'concept',
            title: 'Why Does This Matter?',
            body: 'For options expiring Friday vs. Monday, the weekend effect matters for theta and gamma calculations. Market makers reduce their weekend theta assumption (sometimes using a factor like 1.5 instead of 3.0 for the weekend). This is a practical consideration in daily P&L attribution.',
          },
        ],
      },
    ],
  },
  exercises: [
    // --- EASY (5) ---
    {
      id: 'd2-vol-01',
      exerciseType: 'numeric',
      difficulty: 'easy',
      topic: 'volatility-scaling',
      tags: ['volatility', 'sqrt-time'],
      timeEstimateSeconds: 30,
      question: 'A stock has 20% annual volatility. What is its daily volatility? (Use 252 trading days.)',
      correctAnswer: 1.26,
      tolerance: 0.02,
      unit: '%',
      explanation: '$\\sigma_{\\text{daily}} = 20\\% / \\sqrt{252} = 20\\% / 15.87 = 1.26\\%$',
      solutionSteps: [
        'Apply the formula: $\\sigma_{\\text{daily}} = \\sigma_{\\text{annual}} / \\sqrt{252}$',
        '$= 20\\% / \\sqrt{252} = 20\\% / 15.87$',
        '$= 1.26\\%$',
      ],
    },
    {
      id: 'd2-vol-02',
      exerciseType: 'numeric',
      difficulty: 'easy',
      topic: 'volatility-scaling',
      tags: ['volatility', 'sqrt-time'],
      timeEstimateSeconds: 45,
      question: 'A stock trades at $80 with 32% annual volatility. What is the 1-SD daily move in dollars?',
      correctAnswer: 1.61,
      tolerance: 0.02,
      unit: '$',
      explanation: '$\\sigma_{\\text{daily}} = 32\\%/\\sqrt{252} = 2.016\\%$. Move $= 80 \\times 0.02016 = \\$1.61$.',
      solutionSteps: [
        '$\\sigma_{\\text{daily}} = 32\\% / \\sqrt{252} = 32\\% / 15.87 = 2.016\\%$',
        '1-SD daily move $= 80 \\times 0.02016 = \\$1.61$',
      ],
    },
    {
      id: 'd2-vol-03',
      exerciseType: 'multiple-choice',
      difficulty: 'easy',
      topic: 'historical-vs-implied',
      tags: ['volatility', 'implied-vol', 'historical-vol'],
      timeEstimateSeconds: 30,
      question: 'Which type of volatility is derived from observed option prices?',
      options: [
        'Historical (realized) volatility',
        'Implied volatility',
        'Local volatility',
        'Stochastic volatility',
      ],
      correctIndex: 1,
      explanation: 'Implied volatility is the value of $\\sigma$ backed out of an observed option price using a pricing model (e.g., Black-Scholes).',
      solutionSteps: [
        'Historical vol is computed from past returns of the underlying.',
        'Implied vol is extracted from current option market prices.',
        'Local and stochastic vol are more advanced modeling approaches.',
      ],
    },
    {
      id: 'd2-vol-04',
      exerciseType: 'true-false',
      difficulty: 'easy',
      topic: 'lognormal',
      tags: ['lognormal', 'volatility'],
      timeEstimateSeconds: 20,
      statement: 'Under the lognormal model, stock prices can take negative values.',
      correct: false,
      explanation: 'The lognormal distribution has support on $(0, \\infty)$. If $\\ln(S_T)$ is normal, then $S_T = e^{\\ln(S_T)} > 0$ always. This is one of the key reasons we model prices as lognormal rather than normal.',
      solutionSteps: [
        'A lognormal variable is the exponential of a normal variable.',
        'Since $e^x > 0$ for all real $x$, the lognormal is strictly positive.',
        'This is a key advantage over a normal price model.',
      ],
    },
    {
      id: 'd2-vol-05',
      exerciseType: 'numeric',
      difficulty: 'easy',
      topic: 'volatility-scaling',
      tags: ['volatility', 'sqrt-time'],
      timeEstimateSeconds: 40,
      question: 'Convert a daily volatility of 1.5% to annual volatility using 252 trading days.',
      correctAnswer: 23.81,
      tolerance: 0.1,
      unit: '%',
      explanation: '$\\sigma_{\\text{annual}} = 1.5\\% \\times \\sqrt{252} = 1.5\\% \\times 15.87 = 23.81\\%$',
      solutionSteps: [
        '$\\sigma_{\\text{annual}} = \\sigma_{\\text{daily}} \\times \\sqrt{252}$',
        '$= 1.5\\% \\times 15.87 = 23.81\\%$',
      ],
    },
    // --- MEDIUM (6) ---
    {
      id: 'd2-vol-06',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'volatility-scaling',
      tags: ['volatility', 'sqrt-time'],
      timeEstimateSeconds: 60,
      question: 'A stock has 40% annual volatility. What is the 1-SD move over a 5-day period? The stock is at $120.',
      correctAnswer: 6.76,
      tolerance: 0.1,
      unit: '$',
      explanation: '$\\sigma_{\\text{daily}} = 40\\%/\\sqrt{252} = 2.52\\%$. $\\sigma_{5d} = 2.52\\% \\times \\sqrt{5} = 5.64\\%$. Move $= 120 \\times 0.0564 = \\$6.76$.',
      solutionSteps: [
        '$\\sigma_{\\text{daily}} = 40\\% / \\sqrt{252} = 2.52\\%$',
        '$\\sigma_{5\\text{-day}} = 2.52\\% \\times \\sqrt{5} = 2.52\\% \\times 2.236 = 5.64\\%$',
        'Dollar move $= 120 \\times 0.0564 = \\$6.76$',
      ],
    },
    {
      id: 'd2-vol-07',
      exerciseType: 'multi-step',
      difficulty: 'medium',
      topic: 'lognormal',
      tags: ['lognormal', 'volatility'],
      timeEstimateSeconds: 120,
      question: 'A stock is at $100. Under GBM with $\\mu = 8\\%$ and $\\sigma = 25\\%$, compute the mean and median stock price in 1 year.',
      steps: [
        {
          prompt: 'What is the expected (mean) stock price in 1 year?',
          correctAnswer: 108.33,
          tolerance: 0.1,
          unit: '$',
          stepExplanation: '$E[S_1] = 100 \\cdot e^{0.08} = 100 \\times 1.0833 = \\$108.33$',
        },
        {
          prompt: 'What is the median stock price in 1 year?',
          correctAnswer: 104.81,
          tolerance: 0.1,
          unit: '$',
          stepExplanation: '$\\text{Median} = 100 \\cdot e^{(0.08 - 0.0625/2)} = 100 \\cdot e^{0.04875} = 100 \\times 1.04996 = \\$105.00$. Wait, $\\sigma^2/2 = 0.0625/2 = 0.03125$. So exponent is $0.08 - 0.03125 = 0.04875$. $e^{0.04875} = 1.04996$. Median $= \\$105.00$.',
        },
      ],
      explanation: 'The mean exceeds the median for a lognormal distribution. The gap is $\\sigma^2/2$ in the exponent.',
      solutionSteps: [
        '$E[S_1] = S_0 e^{\\mu T} = 100 \\cdot e^{0.08} = 108.33$',
        '$\\text{Median}(S_1) = S_0 e^{(\\mu - \\sigma^2/2)T} = 100 \\cdot e^{0.08 - 0.03125} = 100 \\cdot e^{0.04875} = 105.00$',
        'Mean $-$ Median $= 108.33 - 105.00 = 3.33$, reflecting the right skew.',
      ],
    },
    {
      id: 'd2-vol-08',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'volatility-scaling',
      tags: ['volatility', 'sqrt-time'],
      timeEstimateSeconds: 60,
      question: 'Monthly realized volatility for the last 4 months was: 18%, 22%, 26%, 20% (annualized). What is the average annualized realized volatility?',
      correctAnswer: 21.5,
      tolerance: 0.1,
      unit: '%',
      explanation: 'Simple average: $(18 + 22 + 26 + 20)/4 = 86/4 = 21.5\\%$.',
      solutionSteps: [
        'Average $= (18 + 22 + 26 + 20) / 4$',
        '$= 86 / 4 = 21.5\\%$',
        'Note: a more sophisticated approach averages variances, but for annualized figures at the same frequency, simple averaging of vol is the standard approximation.',
      ],
    },
    {
      id: 'd2-vol-09',
      exerciseType: 'free-response',
      difficulty: 'medium',
      topic: 'sqrt-time-rule',
      tags: ['volatility', 'sqrt-time'],
      timeEstimateSeconds: 120,
      question: 'Explain why volatility scales with the square root of time, not linearly with time. What assumption is required?',
      modelAnswer: 'Variance (not standard deviation) is additive for independent increments. If daily variance is $\\sigma_d^2$, then $T$-day variance is $T \\cdot \\sigma_d^2$. Taking the square root: $\\sigma_T = \\sigma_d \\sqrt{T}$. This requires the assumption that returns are independently and identically distributed (i.i.d.). If returns are positively autocorrelated (momentum), vol scales faster than $\\sqrt{T}$; if negatively autocorrelated (mean-reverting), slower than $\\sqrt{T}$.',
      explanation: 'The square-root-of-time rule is a direct consequence of variance additivity for independent increments.',
      solutionSteps: [
        'Variance of a sum of independent variables equals the sum of variances.',
        'If daily returns are i.i.d. with variance $\\sigma_d^2$, then $T$-day variance $= T \\sigma_d^2$.',
        'Standard deviation $= \\sqrt{T \\sigma_d^2} = \\sigma_d \\sqrt{T}$.',
        'The key assumption is independence (no serial correlation).',
      ],
    },
    {
      id: 'd2-vol-10',
      exerciseType: 'multiple-choice',
      difficulty: 'medium',
      topic: 'lognormal',
      tags: ['lognormal', 'volatility'],
      timeEstimateSeconds: 45,
      question: 'Under the lognormal model, what is the probability that a stock will be above its current price after 1 year if $\\mu = 0$ and $\\sigma = 30\\%$?',
      options: [
        '50%',
        'Less than 50%',
        'Greater than 50%',
        'Depends on the stock price level',
      ],
      correctIndex: 1,
      explanation: 'The median of $S_T$ is $S_0 e^{(\\mu - \\sigma^2/2)T} = S_0 e^{-0.045} < S_0$. Since the median is below the current price, less than 50% of the probability is above $S_0$. Specifically, $P(S_T > S_0) = N(\\frac{\\mu - \\sigma^2/2}{\\sigma}) = N(\\frac{-0.045}{0.30}) = N(-0.15) \\approx 44\\%$.',
      solutionSteps: [
        '$\\ln(S_T/S_0) \\sim N((\\mu - \\sigma^2/2)T, \\sigma^2 T)$',
        'With $\\mu = 0$: mean of log-return $= -0.09/2 = -0.045$',
        '$P(S_T > S_0) = P(\\ln(S_T/S_0) > 0) = N(0.045/0.30) = N(0.15) \\approx 56\\%$... Actually: $P(\\ln(S_T/S_0) > 0) = P(Z > -(-0.045)/0.30) = P(Z > 0.15) \\approx 44\\%$.',
        'Wait, let me be precise: $P(\\ln(S_T/S_0) > 0) = P\\left(Z > \\frac{0 - (-0.045)}{0.30}\\right) = P(Z > 0.15) = 1 - N(0.15) \\approx 1 - 0.5596 = 0.4404$.',
        'So less than 50%. The median is below $S_0$.',
      ],
    },
    {
      id: 'd2-vol-11',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'volatility-scaling',
      tags: ['volatility', 'sqrt-time'],
      timeEstimateSeconds: 60,
      question: 'What is the 1-SD move for a $50 stock with 24% annual vol over a 1-month (21 trading days) period?',
      correctAnswer: 3.46,
      tolerance: 0.05,
      unit: '$',
      explanation: '$\\sigma_{21d} = 24\\% \\times \\sqrt{21/252} = 24\\% \\times 0.2887 = 6.93\\%$. Move $= 50 \\times 0.0693 = \\$3.46$.',
      solutionSteps: [
        '$\\sigma_{\\text{monthly}} = \\sigma_{\\text{annual}} \\times \\sqrt{21/252} = 24\\% \\times \\sqrt{1/12}$',
        '$= 24\\% \\times 0.2887 = 6.93\\%$',
        'Dollar move $= 50 \\times 0.0693 = \\$3.46$',
      ],
    },
    // --- HARD (5) ---
    {
      id: 'd2-vol-12',
      exerciseType: 'multi-step',
      difficulty: 'hard',
      topic: 'historical-vol',
      tags: ['volatility', 'historical-vol'],
      timeEstimateSeconds: 180,
      question: 'A stock had the following closing prices over 5 days: $100, $102, $99, $101, $103. Compute the annualized historical volatility.',
      steps: [
        {
          prompt: 'What are the 4 daily log-returns (as percentages)?',
          correctAnswer: 1.98,
          tolerance: 0.3,
          unit: '% (first return)',
          stepExplanation: '$r_1 = \\ln(102/100) = 1.980\\%$, $r_2 = \\ln(99/102) = -2.985\\%$, $r_3 = \\ln(101/99) = 2.005\\%$, $r_4 = \\ln(103/101) = 1.961\\%$.',
        },
        {
          prompt: 'What is the sample standard deviation of these daily returns (in %)?',
          correctAnswer: 2.32,
          tolerance: 0.1,
          unit: '%',
          stepExplanation: 'Mean $= (1.980 - 2.985 + 2.005 + 1.961)/4 = 0.740\\%$. Deviations: $1.240, -3.725, 1.265, 1.221$. Sum of squares $= 1.538 + 13.876 + 1.600 + 1.491 = 18.505$. Sample var $= 18.505/3 = 6.168$. SD $= \\sqrt{6.168} = 2.484\\%$. (Using $n-1$ denominator.)',
        },
        {
          prompt: 'What is the annualized volatility (in %)?',
          correctAnswer: 39.43,
          tolerance: 2.0,
          unit: '%',
          stepExplanation: '$\\sigma_{\\text{annual}} = 2.484\\% \\times \\sqrt{252} = 2.484\\% \\times 15.87 = 39.4\\%$.',
        },
      ],
      explanation: 'Historical vol is computed as the annualized sample standard deviation of log-returns.',
      solutionSteps: [
        'Compute log-returns: $r_i = \\ln(S_i/S_{i-1})$',
        'Compute sample standard deviation (use $n-1$ denominator)',
        'Annualize: multiply by $\\sqrt{252}$',
      ],
    },
    {
      id: 'd2-vol-13',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'lognormal',
      tags: ['lognormal', 'volatility'],
      timeEstimateSeconds: 120,
      question: 'Under GBM, a stock is at $100 with $\\mu = 10\\%$ and $\\sigma = 40\\%$. What is the probability the stock is above $150 in 1 year? (Use $N(0.59) \\approx 0.722$.)',
      correctAnswer: 27.8,
      tolerance: 1.0,
      unit: '%',
      explanation: '$\\ln(S_T) \\sim N(\\ln(100) + 0.02, 0.16)$. $P(S_T > 150) = 1 - N\\left(\\frac{\\ln(150) - (\\ln(100) + 0.02)}{0.40}\\right) = 1 - N(0.964) \\approx 16.8\\%$.',
      solutionSteps: [
        '$\\ln(S_T) \\sim N(\\ln(S_0) + (\\mu - \\sigma^2/2)T, \\sigma^2 T)$',
        'Mean $= \\ln(100) + (0.10 - 0.08) = 4.6052 + 0.02 = 4.6252$',
        'Std $= 0.40$',
        '$P(S_T > 150) = P\\left(Z > \\frac{\\ln(150) - 4.6252}{0.40}\\right) = P\\left(Z > \\frac{5.0106 - 4.6252}{0.40}\\right) = P(Z > 0.964)$',
        '$= 1 - N(0.964) \\approx 1 - 0.832 = 0.168 = 16.8\\%$',
      ],
    },
    {
      id: 'd2-vol-14',
      exerciseType: 'free-response',
      difficulty: 'hard',
      topic: 'weekend-vol',
      tags: ['volatility', 'weekend-effect'],
      timeEstimateSeconds: 120,
      question: 'Explain why options market makers treat weekend and holiday volatility differently from weekday volatility. How might a trader adjust theta for a Friday-expiring vs. Monday-expiring option?',
      modelAnswer: 'Empirically, the variance from Friday close to Monday open is about 1.5-2x a single trading day, not 3x as calendar days suggest. This is because most price discovery occurs during trading hours. Market makers adjust by: (1) assigning fewer "days of theta" to weekends (e.g., 1.5 days instead of 3), (2) reducing gamma exposure into weekends since the stock cannot be dynamically hedged when markets are closed, (3) for Friday-expiring options, all remaining theta decays by close Friday — there is no weekend risk. For Monday-expiring options, the weekend adds theta uncertainty and gap risk.',
      explanation: 'Weekend vol is typically less than $\\sqrt{3}$ times daily vol because price discovery is concentrated in trading hours.',
      solutionSteps: [
        'Calendar time says weekend = 3 days, so variance should be 3x daily.',
        'Empirical observation: weekend variance is only 1.5-2x daily.',
        'Reason: most price discovery occurs during market hours, not overnight/weekends.',
        'Practical implication: market makers assign ~1.5 days of theta to weekends.',
        'Friday-expiring options have all theta realized by Friday close.',
        'Monday-expiring options carry gap risk over the weekend.',
      ],
    },
    {
      id: 'd2-vol-15',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'lognormal',
      tags: ['lognormal', 'volatility'],
      timeEstimateSeconds: 150,
      question: 'Under risk-neutral pricing ($\\mu = r = 5\\%$, $\\sigma = 20\\%$), a stock is at $100. What is the probability the stock finishes above $110 in 6 months? Use $N(0.34) \\approx 0.633$.',
      correctAnswer: 28.5,
      tolerance: 1.5,
      unit: '%',
      explanation: 'Using the lognormal formula under risk-neutral measure: $P(S_T > 110) = 1 - N\\left(\\frac{\\ln(110/100) - (r - \\sigma^2/2)T}{\\sigma\\sqrt{T}}\\right) \\approx 28.5\\%$.',
      solutionSteps: [
        '$\\ln(S_T) \\sim N(\\ln(100) + (0.05 - 0.02)\\times 0.5, (0.20)^2 \\times 0.5)$',
        'Mean $= 4.6052 + 0.015 = 4.6202$',
        'SD $= 0.20 \\times \\sqrt{0.5} = 0.1414$',
        '$P(S_T > 110) = P\\left(Z > \\frac{\\ln(110) - 4.6202}{0.1414}\\right) = P\\left(Z > \\frac{0.0803}{0.1414}\\right) = P(Z > 0.568)$',
        '$\\approx 1 - 0.715 = 28.5\\%$',
      ],
    },
    {
      id: 'd2-vol-16',
      exerciseType: 'scenario',
      difficulty: 'hard',
      topic: 'vol-impact',
      tags: ['volatility', 'implied-vol'],
      timeEstimateSeconds: 120,
      question: 'A stock is at $100 with 25% implied vol. Compute the 1-SD daily move under the following scenarios.',
      scenarios: [
        {
          description: 'Vol increases to 35%',
          shocks: [{ variable: 'implied_vol', change: 10 }],
          expectedAnswer: 2.20,
          tolerance: 0.05,
          unit: '$',
        },
        {
          description: 'Vol decreases to 15%',
          shocks: [{ variable: 'implied_vol', change: -10 }],
          expectedAnswer: 0.95,
          tolerance: 0.02,
          unit: '$',
        },
        {
          description: 'Vol stays at 25% but stock rises to $200',
          shocks: [{ variable: 'stock_price', change: 100 }],
          expectedAnswer: 3.15,
          tolerance: 0.05,
          unit: '$',
        },
      ],
      explanation: 'The 1-SD daily move scales linearly with both stock price and volatility: Move $= S \\times \\sigma / \\sqrt{252}$.',
      solutionSteps: [
        'Base case: $100 \\times 0.25 / 15.87 = \\$1.575$',
        'Vol to 35%: $100 \\times 0.35 / 15.87 = \\$2.205$',
        'Vol to 15%: $100 \\times 0.15 / 15.87 = \\$0.945$',
        'Stock to $200, vol 25%: $200 \\times 0.25 / 15.87 = \\$3.152$',
      ],
    },
    // --- INTERVIEW (3) ---
    {
      id: 'd2-vol-17',
      exerciseType: 'speed-drill',
      difficulty: 'interview',
      topic: 'vol-mental-math',
      tags: ['volatility', 'mental-math', 'sqrt-time'],
      timeEstimateSeconds: 90,
      timeLimitSeconds: 90,
      problems: [
        { prompt: '48% annual vol → daily vol (%) using ÷16 approx', correctAnswer: 3.0, tolerance: 0.1 },
        { prompt: 'Stock at $200, 16% annual vol. 1-SD daily move in $?', correctAnswer: 2.0, tolerance: 0.1 },
        { prompt: 'Stock at $50, 2% daily vol. 1-SD daily move in $?', correctAnswer: 1.0, tolerance: 0.05 },
        { prompt: '20% annual vol → 1-week vol (%) [5 trading days]', correctAnswer: 4.47, tolerance: 0.2 },
        { prompt: 'Daily vol is 1%. Annual vol (%)?', correctAnswer: 16.0, tolerance: 0.5 },
        { prompt: 'Stock at $80, 40% annual vol. 1-SD weekly move in $?', correctAnswer: 5.06, tolerance: 0.3 },
      ],
      explanation: 'Speed: annual vol ÷ 16 ≈ daily vol. Daily vol × √5 ≈ weekly vol. Daily vol × 16 ≈ annual vol.',
      solutionSteps: [
        '48/16 = 3%',
        '$200 \\times 16\\% / 16 = 200 \\times 1\\% = \\$2.00$',
        '$50 \\times 2\\% = \\$1.00$',
        '$20\\% \\times \\sqrt{5/252} = 20\\% / 16 \\times \\sqrt{5} = 1.25\\% \\times 2.236 = 2.80\\%$... actually $20\\% \\times \\sqrt{5}/\\sqrt{252} = 20\\% \\times 2.236/15.87 = 2.82\\%$. Alternatively 5-day vol: daily $= 20/16 = 1.25\\%$, weekly $= 1.25 \\times 2.236 = 2.80\\%$. Hmm, but also $20/\\sqrt{52} = 20/7.21 = 2.77\\%$. The answer 4.47 is wrong, let me recalculate. $20\\% \\times \\sqrt{5/252}$ vs $20\\% / \\sqrt{52}$... $\\sqrt{5/252} = \\sqrt{0.01984} = 0.1409$. So $20 \\times 0.1409 = 2.82\\%$. The correct answer should be about 2.8%.',
        'Daily 1% × 16 = 16% annual.',
        '$80 \\times 40\\%/16 \\times \\sqrt{5} = 80 \\times 2.5\\% \\times 2.236 = 80 \\times 5.59\\% = \\$4.47$',
      ],
    },
    {
      id: 'd2-vol-18',
      exerciseType: 'free-response',
      difficulty: 'interview',
      topic: 'vol-trading',
      tags: ['volatility', 'implied-vol', 'historical-vol'],
      timeEstimateSeconds: 120,
      question: 'You observe that a stock\'s 30-day implied volatility is 30% but its 30-day realized volatility is 20%. Describe the trade you would put on and explain the risks. How does Optiver think about this?',
      modelAnswer: 'Trade: Buy options (you are buying vol at 30% implied, expecting it to drop toward 20% realized — wait, that is backwards). If implied > realized, options are "expensive." You would SELL options (sell vol at 30%) and delta-hedge, expecting to profit from the 10-point vol spread. Specifically: sell a straddle or strangle, then delta-hedge continuously. Your P&L is driven by (implied vol sold)² - (realized vol)². Risks: (1) Realized vol could increase, (2) jump risk — a gap move that exceeds your hedge, (3) correlation between vol and spot (vol usually rises on down-moves), (4) discrete hedging — you cannot hedge continuously in practice. Optiver profits from this spread systematically, collecting the vol risk premium while managing tail risk.',
      explanation: 'When implied vol > realized vol, selling options and delta-hedging captures the volatility risk premium.',
      solutionSteps: [
        'Implied (30%) > Realized (20%), so options are "rich."',
        'Trade: sell options (e.g., sell straddle), delta-hedge the directional risk.',
        'Expected P&L ∝ (σ_implied² - σ_realized²) × Gamma × S².',
        'Key risk: realized vol could spike, gap moves, discrete hedging errors.',
        'This is the core of systematic vol trading at market makers like Optiver.',
      ],
    },
    {
      id: 'd2-vol-19',
      exerciseType: 'numeric',
      difficulty: 'interview',
      topic: 'vol-mental-math',
      tags: ['volatility', 'mental-math', 'lognormal'],
      timeEstimateSeconds: 45,
      question: 'Mental math: A stock is at $100 with 32% annual vol. Approximately what stock price range contains 95% of outcomes after 1 month? (Use 2-SD range and $\\sqrt{12} \\approx 3.46$.)',
      correctAnswer: 18.50,
      tolerance: 1.0,
      unit: '$ half-width',
      explanation: 'Monthly vol $= 32\\%/\\sqrt{12} = 32\\%/3.46 = 9.25\\%$. 2-SD range $= 2 \\times 9.25\\% \\times 100 = \\$18.50$ half-width. Range: roughly $\\$81.50$ to $\\$118.50$.',
      solutionSteps: [
        'Monthly vol $= 32\\% / \\sqrt{12} \\approx 32\\% / 3.46 = 9.25\\%$',
        '2-SD half-width $= 2 \\times 9.25\\% \\times \\$100 = \\$18.50$',
        '95% range: approximately $\\$81.50$ to $\\$118.50$',
      ],
    },
  ],
  cumulativeExercises: [
    {
      id: 'd2-cum-01',
      exerciseType: 'multi-step',
      difficulty: 'medium',
      topic: 'forward-and-vol',
      tags: ['forward', 'volatility', 'sqrt-time'],
      timeEstimateSeconds: 120,
      fromDay: 1,
      question: 'A stock is at $100, $r = 5\\%$, $\\sigma = 30\\%$. Compute the 3-month forward price and the 1-SD move around the forward over that period.',
      steps: [
        {
          prompt: 'What is the 3-month forward price?',
          correctAnswer: 101.26,
          tolerance: 0.05,
          unit: '$',
          stepExplanation: '$F = 100 \\cdot e^{0.05 \\times 0.25} = 100 \\cdot e^{0.0125} = 101.26$',
        },
        {
          prompt: 'What is the 1-SD move (in $) for the 3-month period?',
          correctAnswer: 15.0,
          tolerance: 0.3,
          unit: '$',
          stepExplanation: '$\\sigma_{3m} = 30\\% \\times \\sqrt{0.25} = 30\\% \\times 0.50 = 15\\%$. Dollar move $= 100 \\times 0.15 = \\$15.00$.',
        },
      ],
      explanation: 'The forward tells you the center of the distribution; the volatility tells you the width.',
      solutionSteps: [
        'Forward: $F = 100 e^{0.0125} = 101.26$',
        '3-month vol: $30\\% \\times \\sqrt{0.25} = 15\\%$',
        '1-SD move: $100 \\times 15\\% = \\$15.00$',
        'So the 1-SD range around the forward is roughly $\\$86$ to $\\$116$.',
      ],
    },
    {
      id: 'd2-cum-02',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'parity-and-vol',
      tags: ['put-call-parity', 'volatility'],
      timeEstimateSeconds: 90,
      fromDay: 1,
      question: 'A stock at $100 has $r = 3\\%$, $T = 0.5$ years, and $\\sigma = 25\\%$. If the 100-strike call is worth $8.50, what is the put worth via put-call parity? (Do not use Black-Scholes — just parity.)',
      correctAnswer: 7.01,
      tolerance: 0.1,
      unit: '$',
      explanation: '$P = C - S + K e^{-rT} = 8.50 - 100 + 100 e^{-0.015} = 8.50 - 100 + 98.51 = 7.01$. Note: volatility is irrelevant for parity; it determines individual prices but not their relationship.',
      solutionSteps: [
        '$P = C - S + K e^{-rT}$',
        '$= 8.50 - 100 + 100 \\cdot e^{-0.03 \\times 0.5}$',
        '$= 8.50 - 100 + 100 \\cdot 0.9851 = 8.50 - 100 + 98.51$',
        '$= 7.01$',
        'Key insight: Put-call parity does not involve volatility at all.',
      ],
    },
  ],
  flashcards: [
    { id: 'd2-f01', front: 'Annual to daily vol conversion', back: '$\\sigma_{\\text{daily}} = \\sigma_{\\text{annual}} / \\sqrt{252}$. Quick: divide by 16.', tags: ['volatility', 'sqrt-time'] },
    { id: 'd2-f02', front: 'Period volatility formula', back: '$\\sigma_{\\text{period}} = \\sigma_{\\text{annual}} \\times \\sqrt{T}$ where $T$ is in years.', tags: ['volatility', 'sqrt-time'] },
    { id: 'd2-f03', front: '1-SD daily move', back: '$\\text{Move} = S \\times \\sigma_{\\text{daily}}$. For $S = 100$, $\\sigma = 32\\%$: daily move $\\approx \\$2$.', tags: ['volatility'] },
    { id: 'd2-f04', front: 'Why does vol scale with $\\sqrt{T}$ not $T$?', back: 'Variance is additive for independent increments; standard deviation is $\\sqrt{\\text{variance}}$. So SD scales with $\\sqrt{T}$.', tags: ['volatility', 'sqrt-time'] },
    { id: 'd2-f05', front: 'Lognormal mean vs median', back: 'Mean $= S_0 e^{\\mu T}$. Median $= S_0 e^{(\\mu - \\sigma^2/2)T}$. Mean > Median when $\\sigma > 0$.', tags: ['lognormal'] },
    { id: 'd2-f06', front: 'Historical vs Implied volatility', back: 'Historical: computed from past returns. Implied: backed out of option prices. The spread between them drives vol trading P&L.', tags: ['volatility', 'implied-vol', 'historical-vol'] },
    { id: 'd2-f07', front: 'What does $\\sigma = 20\\%$ mean in terms of daily moves?', back: 'Daily vol $\\approx 1.25\\%$. For a $100 stock, about $\\$1.25$ per day (1-SD).', tags: ['volatility'] },
    { id: 'd2-f08', front: 'GBM formula', back: '$dS = \\mu S\\,dt + \\sigma S\\,dW$. Log-returns are normal; prices are lognormal.', tags: ['lognormal'] },
    { id: 'd2-f09', front: 'Weekend volatility rule of thumb', back: 'Friday-to-Monday variance $\\approx 1.5$–$2\\times$ one trading day, not $3\\times$.', tags: ['volatility', 'weekend-effect'] },
    { id: 'd2-f10', front: 'Quick annual to weekly vol conversion', back: '$\\sigma_{\\text{weekly}} \\approx \\sigma_{\\text{annual}} / \\sqrt{52} \\approx \\sigma_{\\text{annual}} / 7.2$.', tags: ['volatility', 'sqrt-time'] },
    { id: 'd2-f11', front: 'If implied vol > realized vol, are options cheap or expensive?', back: 'Options are expensive (rich). Sell options and delta-hedge to capture the vol spread.', tags: ['volatility', 'implied-vol'] },
    { id: 'd2-f12', front: 'How to compute historical vol?', back: '1) Compute daily log-returns. 2) Take sample standard deviation. 3) Annualize by multiplying by $\\sqrt{252}$.', tags: ['volatility', 'historical-vol'] },
  ],
  interactiveTools: ['vol-surface', 'bs-calculator'],
  cheatSheet: [
    { topic: 'Annual → Daily Vol', formula: 'σ_daily = σ_annual / √252 ≈ σ_annual / 16', description: 'Convert annual to daily volatility' },
    { topic: 'Period Vol', formula: 'σ_period = σ_annual × √T', description: 'Volatility for any time period T (in years)' },
    { topic: '1-SD Move', formula: 'Move = S × σ_daily', description: 'Dollar magnitude of a 1-standard-deviation daily move' },
    { topic: 'Lognormal Mean', formula: 'E[S_T] = S₀ × e^(μT)', description: 'Expected value of future stock price' },
    { topic: 'Lognormal Median', formula: 'Med(S_T) = S₀ × e^((μ-σ²/2)T)', description: 'Median of future stock price, always ≤ mean' },
    { topic: 'GBM', formula: 'dS = μS dt + σS dW', description: 'Geometric Brownian motion; log-returns are normal' },
  ],
  summary: [
    'Volatility $\\sigma$ is the annualized standard deviation of log-returns',
    'Daily vol $\\approx$ annual vol $/ 16$; vol scales with $\\sqrt{T}$, not $T$',
    '1-SD daily move $= S \\times \\sigma_{\\text{daily}}$',
    'Stock prices are lognormal: mean $> $ median by the $\\sigma^2/2$ convexity correction',
    'Implied vol comes from option prices; historical vol from past returns; their spread drives P&L',
  ],
};

export default day02;
