import { DayContent } from './types';

const day09: DayContent = {
  dayNumber: 9,
  title: 'Early Exercise for American Options',
  subtitle: 'Natenberg Chapter 12',
  week: 2,
  chapters: ['Chapter 12'],
  estimatedMinutes: 110,
  prerequisites: [1, 2, 3, 4, 5, 6, 7, 8],
  objectives: [
    'Prove why an American call on a non-dividend-paying stock should never be exercised early',
    'Identify the conditions under which early exercise of an American call is optimal (dividends)',
    'Determine the early exercise boundary for American puts',
    'Calculate the early exercise premium for American vs. European options',
    'Apply the dividend threshold rule: exercise when dividend exceeds remaining time value',
  ],
  theory: {
    sections: [
      {
        title: 'Why Never Early Exercise a Call on a Non-Dividend Stock?',
        blocks: [
          {
            type: 'text',
            body: 'This is one of the most important results in options theory and a classic interview question. An American call on a **non-dividend-paying** stock is **never** optimally exercised early. The intuition: exercising early forfeits the time value of the option and requires paying the strike price today rather than later (losing the interest on $K$).',
          },
          {
            type: 'concept',
            title: 'Three Reasons Not to Early Exercise a Call',
            body: '(1) **Insurance value**: A call provides downside protection that is lost upon exercise. Holding the call limits your loss to the premium; exercising exposes you to unlimited downside. (2) **Time value of money**: By exercising, you pay $K$ now instead of later, losing interest on $K$. (3) **Optionality**: The option to wait and decide later is always worth something. These three reasons combine to make early exercise strictly suboptimal.',
          },
          {
            type: 'formula',
            latex: 'C_{\\text{Am}} \\geq \\max(S - K, 0) \\geq S - K',
            label: 'American Call Lower Bound',
            explanation: 'The American call is always worth at least its intrinsic value. But more importantly, $C \\geq S - Ke^{-rT} > S - K$ (the European lower bound exceeds intrinsic). So selling the call always dominates exercising.',
          },
          {
            type: 'callout',
            variant: 'key-insight',
            body: 'The proof is simple: $C \\geq S - Ke^{-rT} > S - K$ (since $e^{-rT} < 1$). Exercising gives you $S - K$. Selling the call gives you at least $S - Ke^{-rT}$. Selling always dominates. QED.',
          },
          {
            type: 'example',
            title: 'Why Not Exercise Early?',
            problem: 'A deep ITM American call with $S = 150$, $K = 100$, $T = 0.5$, $r = 5\\%$. The call trades at $52$. Should you exercise?',
            solution: [
              'Intrinsic value (from exercise) = $150 - 100 = 50$.',
              'Call market value = $52 > 50$.',
              'European lower bound = $S - Ke^{-rT} = 150 - 100 \\cdot e^{-0.025} = 150 - 97.53 = 52.47$.',
              'Even the absolute minimum value ($52.47$) exceeds the exercise value ($50$).',
              'You would lose $52 - 50 = \\$2$ by exercising instead of selling.',
              'Never exercise early. Sell the call if you want to exit the position.',
            ],
          },
        ],
      },
      {
        title: 'Early Exercise for Calls on Dividend-Paying Stocks',
        blocks: [
          {
            type: 'text',
            body: 'The only time it may be optimal to early exercise an American call is **just before an ex-dividend date**. When a stock goes ex-dividend, the stock price drops by approximately the dividend amount. The call holder does not receive the dividend. If the dividend is large enough relative to the remaining time value, exercising to capture the dividend is optimal.',
          },
          {
            type: 'formula',
            latex: '\\text{Exercise if: } D > K(1 - e^{-r(T - t_D)}) + \\text{Time Value of Put}',
            label: 'Early Exercise Condition for Calls',
            explanation: 'Exercise the call just before the ex-date if the dividend $D$ exceeds the interest savings from delaying payment of $K$ plus the time value of the corresponding put. The put time value represents the insurance you give up by exercising.',
          },
          {
            type: 'concept',
            title: 'Simplified Rule of Thumb',
            body: 'For deep ITM calls where the put is far OTM (and its time value is negligible): exercise when $D > K \\cdot r \\cdot (T - t_D)$. In words: exercise when the dividend exceeds the interest earned by delaying payment of the strike. For near-ATM calls, the put time value matters and the decision is more nuanced.',
          },
          {
            type: 'example',
            title: 'Dividend-Triggered Early Exercise',
            problem: 'Stock at $110, $K = 100$ call, 3 months to expiry, ex-dividend in 1 week with $D = \\$3$. $r = 4\\%$. Remaining time after ex-date: 11 weeks. Should you exercise?',
            solution: [
              'Interest savings from not exercising = $K \\cdot (1 - e^{-r(T-t_D)}) = 100 \\cdot (1 - e^{-0.04 \\times 11/52})$',
              '$= 100 \\cdot (1 - e^{-0.00846}) = 100 \\times 0.00842 = 0.84$',
              'Put time value: With $S = 110$, the 100-strike put is deep OTM. Time value $\\approx 0.10$ (very small).',
              'Threshold: $0.84 + 0.10 = 0.94$',
              '$D = 3.00 > 0.94$. Yes, exercise just before the ex-date.',
              'By exercising, you capture the $3 dividend, losing only $0.94 in time value + interest.',
            ],
          },
          {
            type: 'callout',
            variant: 'tip',
            body: 'At Optiver, early exercise decisions are automated. The system checks every position nightly against the ex-date calendar. Understanding the logic behind the decision is essential for debugging and overriding the system when needed.',
          },
        ],
      },
      {
        title: 'Early Exercise for American Puts',
        blocks: [
          {
            type: 'text',
            body: 'Unlike calls, American puts **can** be optimally exercised early even without dividends. The intuition: when a put is deep ITM, the stock is near zero. The put is worth nearly $K$. By exercising, you receive $K$ immediately and can invest it at $r$. Waiting means foregoing interest on $K$. When this interest exceeds the remaining time value (optionality), early exercise is optimal.',
          },
          {
            type: 'formula',
            latex: 'P_{\\text{Am}} \\geq K - S \\quad \\text{(always)}',
            label: 'American Put Lower Bound',
            explanation: 'An American put is always worth at least its intrinsic value. Unlike the European put, which can trade below intrinsic when deep ITM (since $P_{\\text{Eu}} \\geq Ke^{-rT} - S$, which can be less than $K - S$).',
          },
          {
            type: 'concept',
            title: 'The Critical Stock Price $S^*$',
            body: 'There exists a critical stock price $S^*$ below which it is optimal to exercise the American put immediately. At $S^*$, the value of holding the put (time value) exactly equals the interest earned by exercising and investing $K - S^*$ at rate $r$. Above $S^*$, the put is "alive" (hold it). Below $S^*$, the put is "dead" (exercise it).',
          },
          {
            type: 'formula',
            latex: 'P_{\\text{Am}} - P_{\\text{Eu}} = \\text{Early Exercise Premium} \\geq 0',
            label: 'Early Exercise Premium',
            explanation: 'The American put is always worth at least as much as the European put. The difference is the early exercise premium, which increases as the put goes deeper ITM and as interest rates rise.',
          },
          {
            type: 'callout',
            variant: 'warning',
            body: 'Dividends make early exercise of puts LESS likely (not more). The stock is expected to drop on the ex-date, which increases the put value. Waiting to capture the drop is usually better than exercising before the dividend.',
          },
        ],
      },
      {
        title: 'European vs. American Option Pricing',
        blocks: [
          {
            type: 'text',
            body: 'For calls on non-dividend stocks: $C_{\\text{Am}} = C_{\\text{Eu}}$. The early exercise right has zero value. For puts: $P_{\\text{Am}} \\geq P_{\\text{Eu}}$, with the difference being the early exercise premium. For calls on dividend-paying stocks: $C_{\\text{Am}} \\geq C_{\\text{Eu}}$, with the premium depending on dividend size and timing.',
          },
          {
            type: 'table',
            headers: ['Option Type', 'Non-Dividend Stock', 'Dividend Stock'],
            rows: [
              ['American Call', 'Never exercise early; $C_{Am} = C_{Eu}$', 'May exercise before ex-date if $D$ large enough'],
              ['American Put', 'May exercise early when deep ITM', 'Less likely to exercise early (wait for div drop)'],
              ['Early Exercise Premium (Call)', 'Zero', 'Positive; increases with dividend size'],
              ['Early Exercise Premium (Put)', 'Positive; increases with rates', 'Smaller than no-div case'],
            ],
          },
        ],
      },
    ],
  },
  exercises: [
    {
      id: 'd9-early-01',
      exerciseType: 'true-false',
      difficulty: 'easy',
      topic: 'early-exercise',
      tags: ['early-exercise', 'american-call'],
      timeEstimateSeconds: 15,
      statement: 'It is never optimal to exercise an American call option early on a non-dividend-paying stock.',
      correct: true,
      explanation: 'This is a foundational result. The call is always worth more alive (with time value) than dead (exercised for intrinsic). Selling the call always dominates exercising because $C \\geq S - Ke^{-rT} > S - K$.',
      solutionSteps: [
        'European lower bound: $C \\geq S - Ke^{-rT}$',
        'Since $e^{-rT} < 1$: $S - Ke^{-rT} > S - K$ = intrinsic value.',
        'The option is worth more than its exercise value, so never exercise.',
      ],
    },
    {
      id: 'd9-early-02',
      exerciseType: 'true-false',
      difficulty: 'easy',
      topic: 'early-exercise',
      tags: ['early-exercise', 'american-put'],
      timeEstimateSeconds: 15,
      statement: 'It is never optimal to exercise an American put option early on a non-dividend-paying stock.',
      correct: false,
      explanation: 'Unlike calls, American puts CAN be optimally exercised early. When the put is deep ITM, the interest earned on $K - S$ from immediate exercise can exceed the remaining time value.',
      solutionSteps: [
        'For European puts: $P_{Eu} \\geq Ke^{-rT} - S$, which can be LESS than $K - S$.',
        'This means the European put can trade below intrinsic value when deep ITM.',
        'The American put is worth at least $K - S$, so it may be optimal to exercise and invest the proceeds.',
      ],
    },
    {
      id: 'd9-early-03',
      exerciseType: 'multiple-choice',
      difficulty: 'easy',
      topic: 'early-exercise',
      tags: ['early-exercise', 'american-call'],
      timeEstimateSeconds: 30,
      question: 'Which of the following gives a reason NOT to exercise an American call early?',
      options: [
        'You lose the insurance (downside protection) the call provides',
        'You pay the strike price now instead of later, losing interest',
        'You forfeit the remaining time value (optionality)',
        'All of the above',
      ],
      correctIndex: 3,
      explanation: 'All three are valid reasons. (1) The call provides a floor on losses. (2) Exercising requires paying $K$ now vs. later. (3) The option to wait is always valuable.',
      solutionSteps: [
        'Insurance: exercising exposes you to downside; holding the call does not.',
        'Interest: paying $K$ now costs $K - Ke^{-rT}$ in interest.',
        'Optionality: the right to wait and see is valuable.',
        'All three reasons apply. Answer: D.',
      ],
    },
    {
      id: 'd9-early-04',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'early-exercise',
      tags: ['early-exercise', 'american-call', 'dividend'],
      timeEstimateSeconds: 90,
      question: 'Stock at $105, 100-strike American call, 6 months to expiry. A $2 dividend in 1 month. $r = 5\\%$. Remaining time after ex-date: 5 months. Assume the put time value is negligible. Should you exercise? What is the exercise threshold?',
      correctAnswer: 2.08,
      tolerance: 0.05,
      unit: '$',
      hint: 'Calculate the interest savings from not exercising, which is the threshold the dividend must exceed.',
      explanation: 'Threshold = $K(1 - e^{-r(T - t_D)}) = 100(1 - e^{-0.05 \\times 5/12}) = 100(1 - e^{-0.02083}) = 100 \\times 0.02062 = 2.06$. Since $D = 2.00 < 2.06$, do NOT exercise. The threshold is $\\$2.06$.',
      solutionSteps: [
        'Interest savings from delaying exercise: $K(1 - e^{-r(T-t_D)})$',
        '$= 100(1 - e^{-0.05 \\times 5/12}) = 100(1 - e^{-0.02083})$',
        '$= 100 \\times 0.02062 = \\$2.06$',
        'Adding negligible put time value, threshold $\\approx \\$2.08$.',
        'Since $D = 2.00 < 2.08$, do NOT exercise.',
      ],
    },
    {
      id: 'd9-early-05',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'early-exercise',
      tags: ['early-exercise', 'american-call', 'dividend'],
      timeEstimateSeconds: 90,
      question: 'Stock at $120, 100-strike American call, 3 months to expiry. Ex-dividend in 2 weeks with $D = \\$4$. $r = 6\\%$. Remaining time after ex-date: 10 weeks. What is the minimum dividend that would trigger early exercise? (Ignore put time value.)',
      correctAnswer: 1.15,
      tolerance: 0.05,
      unit: '$',
      explanation: 'Threshold = $K(1 - e^{-r(T - t_D)}) = 100(1 - e^{-0.06 \\times 10/52}) = 100(1 - e^{-0.01154}) = 100 \\times 0.01147 = 1.15$. Since $D = 4.00 > 1.15$, exercise. But the question asks for the minimum trigger, which is $\\$1.15$.',
      solutionSteps: [
        'Threshold = $K(1 - e^{-r(T - t_D)})$',
        'Remaining time after ex-date: $10/52$ years $= 0.1923$ years',
        '$= 100(1 - e^{-0.06 \\times 0.1923}) = 100(1 - e^{-0.01154})$',
        '$= 100 \\times 0.01147 = \\$1.15$',
        'Any dividend above $\\$1.15$ triggers exercise (ignoring put time value).',
      ],
    },
    {
      id: 'd9-early-06',
      exerciseType: 'free-response',
      difficulty: 'medium',
      topic: 'early-exercise',
      tags: ['early-exercise', 'american-put'],
      timeEstimateSeconds: 120,
      question: 'Explain intuitively why it can be optimal to exercise an American put early, but not an American call (on a non-dividend stock). What is fundamentally different about the two cases?',
      modelAnswer: 'The key asymmetry is in the **time value of money** effect on the strike. For a call, exercising means paying $K$ now. Delaying saves interest on $K$. For a put, exercising means receiving $K$ now. Delaying loses interest on $K$. So for calls, time works in your favor (delay is free money). For puts, time works against you (delay costs interest). Additionally, a stock can only fall to zero (bounded downside for puts), but can rise infinitely (unbounded upside for calls). When a put is deep ITM (stock near zero), the maximum remaining upside from waiting is small relative to the interest lost. The option is essentially "maxed out" and should be exercised.',
      explanation: 'The fundamental difference is whether delaying exercise earns interest (calls) or loses interest (puts) on the strike price.',
      solutionSteps: [
        'Call exercise: pay $K$ now. Delay = save interest on $K$. Always better to delay.',
        'Put exercise: receive $K$ now. Delay = lose interest on $K$. Sometimes better to exercise.',
        'Bounded vs. unbounded payoff: put payoff maxes at $K$ (stock at 0); call payoff is unlimited.',
        'When put is deep ITM, remaining optionality is small vs. interest lost. Exercise.',
      ],
    },
    {
      id: 'd9-early-07',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'early-exercise-premium',
      tags: ['early-exercise', 'american-put', 'premium'],
      timeEstimateSeconds: 120,
      question: 'A European put is worth $8.50 and an American put (same terms) is worth $9.20. Both have $K = 100$, $S = 90$, $T = 1$, $r = 5\\%$. What is the early exercise premium? Also verify: is the European put below intrinsic?',
      correctAnswer: 0.70,
      tolerance: 0.01,
      unit: '$',
      explanation: 'Early exercise premium = $P_{Am} - P_{Eu} = 9.20 - 8.50 = 0.70$. Intrinsic = $K - S = 10$. European put = $8.50 < 10$. Yes, the European put is below intrinsic. This is possible because $P_{Eu} \\geq Ke^{-rT} - S = 95.12 - 90 = 5.12$, which is above zero but below $K - S = 10$.',
      solutionSteps: [
        'Early exercise premium = $P_{Am} - P_{Eu} = 9.20 - 8.50 = \\$0.70$',
        'Intrinsic value = $K - S = 100 - 90 = 10$',
        'European put = $8.50 < 10$: yes, it is below intrinsic.',
        'European lower bound: $Ke^{-rT} - S = 100 \\cdot e^{-0.05} - 90 = 95.12 - 90 = 5.12$.',
        'The European put ($8.50$) is above this bound but below intrinsic ($10$). This is normal for deep ITM European puts.',
      ],
    },
    {
      id: 'd9-early-08',
      exerciseType: 'multiple-choice',
      difficulty: 'medium',
      topic: 'early-exercise',
      tags: ['early-exercise', 'american-put', 'dividends'],
      timeEstimateSeconds: 45,
      question: 'How do dividends affect the early exercise decision for American puts?',
      options: [
        'Dividends make early exercise MORE likely for puts',
        'Dividends make early exercise LESS likely for puts',
        'Dividends have no effect on put early exercise',
        'The effect depends on the moneyness of the put',
      ],
      correctIndex: 1,
      explanation: 'Dividends make early exercise of puts LESS likely. An upcoming dividend will cause the stock price to drop, which increases the put value. It is better to wait for the dividend-driven drop than to exercise before it. This is the opposite of the call case.',
      solutionSteps: [
        'A dividend causes the stock to drop by approximately $D$ on the ex-date.',
        'For a put holder, this drop increases the put value.',
        'Exercising before the drop means missing out on this gain.',
        'Therefore, dividends make early exercise of puts less likely.',
      ],
    },
    {
      id: 'd9-early-09',
      exerciseType: 'multi-step',
      difficulty: 'hard',
      topic: 'early-exercise',
      tags: ['early-exercise', 'american-call', 'dividend'],
      timeEstimateSeconds: 180,
      question: 'Stock at $95, 90-strike American call, 6 months to expiry. Two dividends: $D_1 = \\$1.50$ in 2 months, $D_2 = \\$1.50$ in 5 months. $r = 5\\%$. (a) Should you exercise before $D_1$? (b) Should you exercise before $D_2$? (Ignore put time value.)',
      steps: [
        {
          prompt: 'What is the exercise threshold before $D_1$ (interest saving from delaying to expiry minus the period after D1)?',
          correctAnswer: 1.48,
          tolerance: 0.1,
          unit: '$',
          stepExplanation: 'If you exercise before $D_1$, you give up interest on $K$ from month 2 to month 6 (4 months). Threshold = $K(1 - e^{-r \\times 4/12}) = 90(1 - e^{-0.05 \\times 1/3}) = 90(1 - e^{-0.01667}) = 90 \\times 0.01653 = 1.49$. Also need to consider that if you don\'t exercise, you can still exercise before $D_2$. So the threshold is roughly $K(1 - e^{-r(t_2 - t_1)}) = 90(1 - e^{-0.05 \\times 3/12}) = 90(1 - e^{-0.0125}) = 90 \\times 0.01242 = 1.12$. Since you have the option to exercise before $D_2$ too, the relevant interest saving is just from $t_1$ to $t_2$: $1.12$. Then $D_1 = 1.50 > 1.12$, so you would exercise before $D_1$. But actually, the standard approach checks against the last dividend first. Let me use the threshold for the full remaining time: $K(1 - e^{-r(T - t_1)}) = 90(1 - e^{-0.05 \\times 4/12}) = 1.49$. $D_1 = 1.50 > 1.49$. Exercise.',
        },
        {
          prompt: 'What is the exercise threshold before $D_2$?',
          correctAnswer: 0.37,
          tolerance: 0.05,
          unit: '$',
          stepExplanation: 'Threshold = $K(1 - e^{-r(T - t_2)}) = 90(1 - e^{-0.05 \\times 1/12}) = 90(1 - e^{-0.00417}) = 90 \\times 0.00416 = 0.37$. $D_2 = 1.50 > 0.37$. Exercise before $D_2$ as well.',
        },
      ],
      explanation: 'With multiple dividends, check each ex-date. Usually only the last ex-date before expiry matters most, but large early dividends can trigger earlier exercise.',
      solutionSteps: [
        'Before $D_1$: Threshold = $K(1 - e^{-r(T - t_1)}) = 90(1 - e^{-0.01667}) = 1.49$. $D_1 = 1.50 > 1.49$: exercise.',
        'Before $D_2$: Threshold = $K(1 - e^{-r(T - t_2)}) = 90(1 - e^{-0.00417}) = 0.37$. $D_2 = 1.50 > 0.37$: exercise.',
        'Both dividends trigger exercise. In practice, you would exercise before $D_1$ (the first opportunity).',
      ],
    },
    {
      id: 'd9-early-10',
      exerciseType: 'true-false',
      difficulty: 'medium',
      topic: 'early-exercise',
      tags: ['early-exercise', 'pricing'],
      timeEstimateSeconds: 20,
      statement: 'For a non-dividend stock, American and European calls have the same value.',
      correct: true,
      explanation: 'Since early exercise of an American call on a non-dividend stock is never optimal, the early exercise premium is zero. Therefore $C_{Am} = C_{Eu}$.',
      solutionSteps: [
        'Early exercise is never optimal for calls on non-dividend stocks.',
        'The early exercise right has zero value.',
        'Therefore $C_{Am} = C_{Eu}$.',
      ],
    },
    {
      id: 'd9-early-11',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'early-exercise',
      tags: ['early-exercise', 'american-put', 'boundary'],
      timeEstimateSeconds: 120,
      question: 'For an American put with $K = 50$, $r = 8\\%$, $\\sigma = 30\\%$, $T = 1$, the critical stock price (early exercise boundary) is approximately $S^* = 36$. If the stock drops to $34$, what is the minimum value of the American put?',
      correctAnswer: 16.00,
      tolerance: 0.01,
      unit: '$',
      explanation: 'Below the critical stock price, the American put should be exercised immediately. Its value equals the intrinsic value: $P_{Am} = K - S = 50 - 34 = 16$. The put is "dead" (should be exercised).',
      solutionSteps: [
        'The critical stock price $S^* = 36$ is the boundary below which exercise is optimal.',
        'At $S = 34 < S^* = 36$, the put should be exercised immediately.',
        'Exercise value = $K - S = 50 - 34 = \\$16.00$.',
        'The American put is worth exactly its intrinsic value in this region.',
      ],
    },
    {
      id: 'd9-early-12',
      exerciseType: 'multiple-choice',
      difficulty: 'hard',
      topic: 'early-exercise',
      tags: ['early-exercise', 'interest-rates'],
      timeEstimateSeconds: 45,
      question: 'If interest rates increase, what happens to the early exercise premium of an American put?',
      options: [
        'It decreases because higher rates reduce put values',
        'It increases because the cost of delaying exercise (lost interest on $K$) is higher',
        'It stays the same because rates do not affect early exercise',
        'It increases for ITM puts but decreases for OTM puts',
      ],
      correctIndex: 1,
      explanation: 'Higher rates mean the opportunity cost of NOT exercising the put (and NOT investing $K$ at the higher rate) is larger. This makes early exercise more attractive and increases the early exercise premium.',
      solutionSteps: [
        'Exercising a put gives you $K$ cash to invest at rate $r$.',
        'Higher $r$ means more interest earned from early exercise.',
        'The cost of waiting (lost interest) increases with $r$.',
        'Therefore the early exercise premium increases with rates.',
      ],
    },
    {
      id: 'd9-early-13',
      exerciseType: 'free-response',
      difficulty: 'interview',
      topic: 'early-exercise',
      tags: ['early-exercise', 'interview'],
      timeEstimateSeconds: 120,
      question: 'An interviewer asks: "Why should you never early exercise an American call on a non-dividend stock?" Give a concise, rigorous answer.',
      modelAnswer: 'Because selling the call always dominates exercising. Proof: By the European call lower bound, $C \\geq S - Ke^{-rT}$. Exercising gives $S - K$. Since $Ke^{-rT} < K$ (for $r > 0$, $T > 0$), we have $S - Ke^{-rT} > S - K$, so $C > S - K$. The call is always worth more than its exercise value. Alternatively: by exercising, you (1) forfeit insurance against the stock dropping below $K$, (2) pay $K$ now instead of later (losing interest), and (3) give up all remaining optionality. All three effects are value-destroying.',
      explanation: 'This is the most commonly asked early exercise question in trading interviews.',
      solutionSteps: [
        'State the European lower bound: $C \\geq S - Ke^{-rT}$.',
        'Since $r > 0$: $Ke^{-rT} < K$, so $S - Ke^{-rT} > S - K$.',
        'Therefore $C > S - K$ = exercise value.',
        'Selling always beats exercising. Three reasons: insurance, interest, optionality.',
      ],
    },
    {
      id: 'd9-early-14',
      exerciseType: 'numeric',
      difficulty: 'interview',
      topic: 'early-exercise',
      tags: ['early-exercise', 'mental-math', 'interview'],
      timeEstimateSeconds: 30,
      question: 'Mental math: Stock at $100, 100-strike American put, $r = 10\\%$, $T = 1$. The European put is worth $7$. What is the minimum value of the American put?',
      correctAnswer: 7.00,
      tolerance: 0.01,
      unit: '$',
      explanation: '$P_{Am} \\geq P_{Eu} = 7$ and $P_{Am} \\geq K - S = 0$. So minimum is $\\max(7, 0) = 7$. Note: even though the European put might be below intrinsic for ITM puts, here the put is ATM with intrinsic = 0.',
      solutionSteps: [
        '$P_{Am} \\geq P_{Eu} = 7$',
        '$P_{Am} \\geq K - S = 100 - 100 = 0$',
        'Minimum American put value = $\\max(7, 0) = \\$7.00$.',
      ],
    },
    {
      id: 'd9-speed-01',
      exerciseType: 'speed-drill',
      difficulty: 'medium',
      topic: 'early-exercise',
      tags: ['early-exercise', 'speed-drill'],
      timeEstimateSeconds: 120,
      timeLimitSeconds: 120,
      problems: [
        { prompt: 'American call, no dividends. Early exercise optimal? (1=yes, 0=no)', correctAnswer: 0, tolerance: 0 },
        { prompt: 'American put, deep ITM, high rates. Early exercise possible? (1=yes, 0=no)', correctAnswer: 1, tolerance: 0 },
        { prompt: 'Stock at $50, K=$100 American put, r=5%, T=1. Put intrinsic?', correctAnswer: 50, tolerance: 0.01 },
        { prompt: 'European put lower bound: K*e^(-0.05)-S, K=100, S=90, T=1. Value?', correctAnswer: 5.12, tolerance: 0.1 },
        { prompt: 'Is the European put below intrinsic? (K-S=10, Eu put bound=5.12). 1=yes possible, 0=no', correctAnswer: 1, tolerance: 0 },
        { prompt: 'Am call = Eu call for non-div stock? (1=yes, 0=no)', correctAnswer: 1, tolerance: 0 },
      ],
      explanation: 'Speed drill covering the key early exercise facts.',
      solutionSteps: [
        'No early exercise for calls on non-div stocks.',
        'Yes, puts can be exercised early, especially deep ITM with high rates.',
        'Intrinsic = $K - S = 100 - 50 = 50$.',
        'European put lower bound = $100e^{-0.05} - 90 = 95.12 - 90 = 5.12$.',
        'Yes, European put can be below intrinsic ($5.12 < 10$).',
        'Yes, American call = European call for non-div stocks.',
      ],
    },
  ],
  cumulativeExercises: [
    {
      id: 'd9-cum-01',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'parity-early-exercise',
      tags: ['put-call-parity', 'early-exercise', 'american'],
      timeEstimateSeconds: 90,
      fromDay: 1,
      question: 'For a non-dividend stock at $100, $r = 5\\%$, $T = 0.5$: the European call at $K = 100$ is $5.00$. What is the European put? What is the American put worth at minimum?',
      correctAnswer: 2.53,
      tolerance: 0.05,
      unit: '$',
      explanation: '$P_{Eu} = C - S + Ke^{-rT} = 5.00 - 100 + 100e^{-0.025} = 5.00 - 100 + 97.53 = 2.53$. American put $\\geq \\max(P_{Eu}, K - S) = \\max(2.53, 0) = 2.53$.',
      solutionSteps: [
        'From parity: $P_{Eu} = C - S + Ke^{-rT} = 5.00 - 100 + 97.53 = 2.53$.',
        '$P_{Am} \\geq P_{Eu} = 2.53$ and $P_{Am} \\geq K - S = 0$.',
        'Minimum American put = $\\$2.53$.',
      ],
    },
    {
      id: 'd9-cum-02',
      exerciseType: 'multiple-choice',
      difficulty: 'medium',
      topic: 'synthetics-early-exercise',
      tags: ['synthetics', 'early-exercise', 'conversion'],
      timeEstimateSeconds: 60,
      fromDay: 8,
      question: 'A trader holds a conversion (long stock, long put, short call) on an American option. What additional risk does the conversion have compared to a European conversion?',
      options: [
        'The long put might be exercised early by the trader, reducing profits',
        'The short call might be assigned early if a dividend is coming',
        'The stock might gap through the strike',
        'There is no additional risk since conversions are always risk-free',
      ],
      correctIndex: 1,
      explanation: 'In an American conversion, the short call can be assigned early (especially before a dividend). This forces the trader to deliver the stock and changes the cash flow timing, potentially reducing the arbitrage profit.',
      solutionSteps: [
        'European conversion: no early exercise risk. Cash flows are locked.',
        'American conversion: the counterparty holding the call may exercise early.',
        'Early assignment on the short call means: deliver stock, receive $K$.',
        'If this happens before planned, the trader loses the remaining time value.',
        'This is particularly risky around dividend ex-dates.',
      ],
    },
    {
      id: 'd9-cum-03',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'delta-early-exercise',
      tags: ['delta', 'early-exercise', 'american-put'],
      timeEstimateSeconds: 120,
      fromDay: 5,
      question: 'An American put at the early exercise boundary ($S = S^* = 40$, $K = 50$) has a delta of exactly $-1$. Why? What is the gamma at this point?',
      correctAnswer: 0,
      tolerance: 0.01,
      unit: 'gamma',
      explanation: 'At the early exercise boundary, the American put value equals its intrinsic value $K - S$, whose slope is $-1$. The delta is exactly $-1$. Below $S^*$, the put is exercised (value = $K - S$, delta = $-1$, gamma = $0$). At $S^*$, the put transitions from "alive" to "dead." Gamma is $0$ at and below the boundary.',
      solutionSteps: [
        'At $S \\leq S^*$: put value = $K - S$ (intrinsic). Slope = $-1$. Delta = $-1$.',
        'The second derivative of $K - S$ is $0$.',
        'Therefore gamma = $0$ at and below the boundary.',
        'At $S > S^*$ (just above), gamma is positive (the put is alive with curvature).',
      ],
    },
    {
      id: 'd9-cum-04',
      exerciseType: 'free-response',
      difficulty: 'hard',
      topic: 'volatility-early-exercise',
      tags: ['volatility', 'early-exercise'],
      timeEstimateSeconds: 120,
      fromDay: 7,
      question: 'How does implied volatility affect the early exercise decision for American puts? Does higher vol make early exercise more or less likely?',
      modelAnswer: 'Higher implied volatility makes early exercise LESS likely. Here is why: higher vol increases the time value (optionality) of the put. At high vol, there is a greater chance the stock could move significantly in the remaining time, making the option to wait more valuable. The critical stock price $S^*$ moves lower when vol is higher, meaning the stock has to fall further before early exercise becomes optimal. Conversely, low vol (near zero) makes early exercise more likely because there is little chance of the stock moving significantly.',
      explanation: 'Higher vol increases optionality, which competes against the interest earned from early exercise.',
      solutionSteps: [
        'Higher vol increases put time value (more chance of profitable moves).',
        'Early exercise forfeits this time value.',
        'With high vol, the forgone time value exceeds the interest benefit.',
        'Therefore the critical price $S^*$ decreases: stock must fall further to trigger exercise.',
        'In the limit: $\\sigma \\to 0$ means exercise whenever $S < K$ (interest always wins); $\\sigma \\to \\infty$ means never exercise (time value always wins).',
      ],
    },
    {
      id: 'd9-cum-05',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'forward-early-exercise',
      tags: ['forward', 'early-exercise'],
      timeEstimateSeconds: 90,
      fromDay: 1,
      question: 'Stock at $100, $r = 6\\%$, $T = 0.25$. A deep ITM European put ($K = 130$) has a lower bound of $Ke^{-rT} - S$. Calculate this and compare to intrinsic.',
      correctAnswer: 27.07,
      tolerance: 0.1,
      unit: '$',
      explanation: 'European put lower bound = $Ke^{-rT} - S = 130 \\cdot e^{-0.015} - 100 = 128.07 - 100 = 28.07$. Intrinsic = $130 - 100 = 30$. The European lower bound ($28.07$) is below intrinsic ($30$), confirming that a European put can trade below intrinsic.',
      solutionSteps: [
        '$Ke^{-rT} = 130 \\cdot e^{-0.06 \\times 0.25} = 130 \\cdot e^{-0.015} = 130 \\times 0.98511 = 128.06$',
        'European lower bound = $128.06 - 100 = 28.06$.',
        'Intrinsic = $130 - 100 = 30$.',
        'Gap = $30 - 28.06 = 1.94$. The European put can be up to $\\$1.94$ below intrinsic.',
        'This is why the American put (which cannot trade below intrinsic) has a positive early exercise premium.',
      ],
    },
    {
      id: 'd9-cum-06',
      exerciseType: 'scenario',
      difficulty: 'hard',
      topic: 'early-exercise-greeks',
      tags: ['early-exercise', 'theta', 'rho'],
      timeEstimateSeconds: 150,
      fromDay: 5,
      question: 'Consider an American put near the early exercise boundary. How do theta and rho behave?',
      scenarios: [
        {
          description: 'Stock just above S* (put is alive): What is the sign of theta?',
          shocks: [{ variable: 'stock_price', change: 1 }],
          expectedAnswer: -1,
          tolerance: 0,
          unit: 'sign (-1 or +1)',
        },
        {
          description: 'Stock just below S* (put is dead/exercised): What is theta?',
          shocks: [{ variable: 'stock_price', change: -1 }],
          expectedAnswer: 0,
          tolerance: 0,
          unit: 'sign (0 if zero)',
        },
      ],
      explanation: 'Just above $S^*$: the American put is alive and has negative theta (time decay). Just below $S^*$: the put should be exercised immediately. Once exercised, there is no more theta (it becomes a stock/cash position). This is a discontinuity in the Greeks at the boundary.',
      solutionSteps: [
        'Above $S^*$: Put is alive. Time decay exists. Theta < 0 (sign = -1).',
        'Below $S^*$: Put should be exercised. Value = $K - S$ (no time component). Theta = 0.',
        'At the boundary: theta jumps from negative to zero (discontinuity).',
      ],
    },
  ],
  flashcards: [
    { id: 'd9-f01', front: 'Should you ever early exercise an American call on a non-dividend stock?', back: 'Never. The call is always worth more alive than dead: $C \\geq S - Ke^{-rT} > S - K$.', tags: ['early-exercise'] },
    { id: 'd9-f02', front: 'When should you early exercise an American call on a dividend stock?', back: 'Just before the ex-dividend date, if $D > K(1 - e^{-r(T-t_D)}) + \\text{put time value}$. I.e., when the dividend exceeds the interest savings plus insurance value.', tags: ['early-exercise', 'dividend'] },
    { id: 'd9-f03', front: 'Can American puts be optimally exercised early?', back: 'Yes, even without dividends. When deep ITM, the interest on $K$ from exercise exceeds remaining time value.', tags: ['early-exercise'] },
    { id: 'd9-f04', front: 'What is the critical stock price $S^*$ for an American put?', back: 'The price below which immediate exercise is optimal. At $S^*$: time value = interest on $K - S^*$.', tags: ['early-exercise', 'boundary'] },
    { id: 'd9-f05', front: 'How do dividends affect American put early exercise?', back: 'Dividends make early exercise LESS likely. The stock drops on ex-date, increasing put value. Better to wait.', tags: ['early-exercise', 'dividend'] },
    { id: 'd9-f06', front: 'American call vs European call value (no dividends)', back: '$C_{Am} = C_{Eu}$. The early exercise right has zero value.', tags: ['early-exercise', 'pricing'] },
    { id: 'd9-f07', front: 'American put vs European put value', back: '$P_{Am} \\geq P_{Eu}$. The difference is the early exercise premium, which increases with rates and ITM-ness.', tags: ['early-exercise', 'pricing'] },
    { id: 'd9-f08', front: 'Can a European put trade below intrinsic?', back: 'Yes. $P_{Eu} \\geq Ke^{-rT} - S$, which is less than $K - S$ when $r > 0$. Deep ITM European puts can be below intrinsic.', tags: ['early-exercise', 'european'] },
    { id: 'd9-f09', front: 'Three reasons not to early exercise a call', back: '(1) Lose insurance (downside protection). (2) Pay $K$ now vs. later (lose interest). (3) Forfeit optionality (right to wait).', tags: ['early-exercise'] },
    { id: 'd9-f10', front: 'How does volatility affect put early exercise?', back: 'Higher vol makes early exercise LESS likely (more optionality value). $S^*$ decreases.', tags: ['early-exercise', 'volatility'] },
    { id: 'd9-f11', front: 'How do interest rates affect put early exercise?', back: 'Higher rates make early exercise MORE likely (higher opportunity cost of not investing $K$). $S^*$ increases.', tags: ['early-exercise', 'interest-rates'] },
    { id: 'd9-f12', front: 'Delta of an American put at the early exercise boundary', back: '$\\Delta = -1$ at $S = S^*$ and below. The put tracks intrinsic value dollar-for-dollar.', tags: ['early-exercise', 'greeks'] },
  ],
  interactiveTools: ['bs-calculator', 'payoff-diagram', 'put-call-parity'],
  cheatSheet: [
    { topic: 'Call Early Exercise (no div)', formula: 'Never exercise', description: 'C ≥ S - Ke^{-rT} > S - K' },
    { topic: 'Call Early Exercise (div)', formula: 'Exercise if D > K(1-e^{-r(T-tD)})', description: 'When dividend exceeds interest savings' },
    { topic: 'Put Early Exercise', formula: 'Exercise when S < S*', description: 'Below critical price, interest on K exceeds time value' },
    { topic: 'Am Call = Eu Call', formula: 'C_Am = C_Eu (no div)', description: 'Early exercise right worthless for calls' },
    { topic: 'Am Put ≥ Eu Put', formula: 'P_Am - P_Eu = early exercise premium', description: 'Premium increases with rates and ITM-ness' },
    { topic: 'Eu Put Lower Bound', formula: 'P_Eu ≥ Ke^{-rT} - S', description: 'Can be below intrinsic K-S' },
  ],
  summary: [
    'Never early exercise an American call on a non-dividend stock: $C \\geq S - Ke^{-rT} > S - K$',
    'Exercise calls before ex-dividend when $D > K(1 - e^{-r(T-t_D)}) + \\text{put time value}$',
    'American puts may be exercised early when deep ITM: interest on $K$ exceeds time value',
    'Higher rates increase put early exercise premium; higher vol decreases it',
    'European puts can trade below intrinsic; American puts cannot',
  ],
};

export default day09;
