import { DayContent } from './types';

const day03: DayContent = {
  dayNumber: 3,
  title: 'Expected Value & Discrete Payoffs',
  subtitle: 'Natenberg Chapter 3',
  week: 1,
  chapters: ['Chapter 3'],
  estimatedMinutes: 100,
  prerequisites: [1, 2],
  objectives: [
    'Compute expected values under discrete probability distributions',
    'Price simple dice and coin games using EV calculations',
    'Apply backward induction to multi-stage optimal stopping problems',
    'Calculate expected payoffs of options on discrete underlyings (e.g., dice)',
    'Connect risk-neutral pricing to EV under the risk-neutral measure',
  ],
  theory: {
    sections: [
      {
        title: 'Expected Value Fundamentals',
        blocks: [
          {
            type: 'text',
            body: 'Expected value (EV) is the probability-weighted average of all possible outcomes. It is the single most important concept in quantitative trading. Every decision a market maker makes boils down to: "What is the expected value of this trade?" If you can compute EV faster and more accurately than the competition, you have an edge.',
          },
          {
            type: 'formula',
            latex: 'E[X] = \\sum_{i=1}^{n} x_i \\cdot p_i',
            label: 'Expected Value (Discrete)',
            explanation: 'Sum each outcome $x_i$ multiplied by its probability $p_i$. The probabilities must sum to 1.',
          },
          {
            type: 'example',
            title: 'EV of a Fair Die Roll',
            problem: 'What is the expected value of a single roll of a fair 6-sided die?',
            solution: [
              '$E[X] = \\frac{1}{6}(1 + 2 + 3 + 4 + 5 + 6) = \\frac{21}{6} = 3.5$',
              'Each outcome has probability $1/6$.',
              'The EV of 3.5 is not itself a possible outcome, but represents the long-run average.',
            ],
          },
          {
            type: 'callout',
            variant: 'key-insight',
            body: 'In trading, you never see a "fair" game in the wild. Your job is to find edges: situations where the EV of your position is positive after accounting for transaction costs and risk. A market maker might earn $0.01 in EV per trade, but do it millions of times.',
          },
        ],
      },
      {
        title: 'Properties of Expected Value',
        blocks: [
          {
            type: 'text',
            body: 'Expected value has powerful linearity properties that make complex problems tractable. Linearity holds even when the random variables are dependent, which is remarkable and incredibly useful.',
          },
          {
            type: 'formula',
            latex: 'E[aX + bY] = a \\cdot E[X] + b \\cdot E[Y]',
            label: 'Linearity of Expectation',
            explanation: 'The expectation of a linear combination equals the linear combination of expectations. This holds for ANY random variables, independent or not.',
          },
          {
            type: 'formula',
            latex: 'E[\\max(X - K, 0)] = \\sum_{x_i > K} (x_i - K) \\cdot p_i',
            label: 'Expected Payoff of a Call on a Discrete Variable',
            explanation: 'This is the EV of a call option with strike $K$ on a discrete random variable. Only outcomes above the strike contribute.',
          },
          {
            type: 'example',
            title: 'Call Option on a Die Roll',
            problem: 'You roll a fair die. Your payoff is $\\max(\\text{roll} - 3.5, 0)$. What is the expected payoff?',
            solution: [
              'Outcomes above the strike of 3.5: rolls of 4, 5, 6.',
              '$E[\\text{payoff}] = \\frac{1}{6}[(4 - 3.5) + (5 - 3.5) + (6 - 3.5)]$',
              '$= \\frac{1}{6}[0.5 + 1.5 + 2.5] = \\frac{4.5}{6} = 0.75$',
            ],
          },
          {
            type: 'callout',
            variant: 'tip',
            body: 'The "put" on a die roll with the same strike has EV $= \\frac{1}{6}[(3.5-1) + (3.5-2) + (3.5-3)] = \\frac{1}{6}(2.5+1.5+0.5) = 0.75$. By put-call parity on a die: $C - P = E[X] - K = 3.5 - 3.5 = 0$, confirming $C = P$.',
          },
        ],
      },
      {
        title: 'Conditional Expectation & Multi-Stage Games',
        blocks: [
          {
            type: 'text',
            body: 'Many interview problems and real trading situations involve **sequential decisions**. The key technique is **backward induction**: start from the final stage, compute the EV at each decision point, and work backwards to the first stage. At each stage, the optimal decision is the one that maximizes expected value.',
          },
          {
            type: 'formula',
            latex: 'E[X] = \\sum_j E[X \\mid A_j] \\cdot P(A_j)',
            label: 'Law of Total Expectation',
            explanation: 'The unconditional expectation equals the probability-weighted average of conditional expectations. This is the mathematical foundation of backward induction.',
          },
          {
            type: 'example',
            title: 'Optimal Stopping: Two Rolls',
            problem: 'You roll a fair die. After seeing the result, you can either keep it or re-roll once. If you re-roll, you must keep the second result. What is the optimal strategy and expected value?',
            solution: [
              'Work backwards. If you re-roll, the expected value of the second roll is $3.5$.',
              'So you should keep the first roll if it exceeds $3.5$ (i.e., if you roll 4, 5, or 6) and re-roll otherwise.',
              '$E[\\text{game}] = \\frac{1}{6}(3.5 + 3.5 + 3.5 + 4 + 5 + 6) = \\frac{25.5}{6} = 4.25$',
              'The option to re-roll is worth $4.25 - 3.50 = 0.75$ above the single-roll EV.',
            ],
          },
          {
            type: 'example',
            title: 'Optimal Stopping: Three Rolls',
            problem: 'Same game, but now you get up to 3 rolls. What is the EV?',
            solution: [
              'We already know the 2-roll game has EV $= 4.25$.',
              'On the first roll, keep it if it exceeds 4.25 (i.e., roll 5 or 6), otherwise use your remaining 2 rolls.',
              '$E[\\text{3-roll}] = \\frac{1}{6}(4.25 + 4.25 + 4.25 + 4.25 + 5 + 6) = \\frac{28.0}{6} \\approx 4.667$',
              'Each additional roll adds less value: 3.50 $\\to$ 4.25 $\\to$ 4.667 (diminishing marginal value of the option).',
            ],
          },
          {
            type: 'callout',
            variant: 'key-insight',
            body: 'The optimal stopping problem is essentially an American option pricing problem. The "option" to re-roll is like the right to exercise later. Backward induction is the discrete-time version of the technique used in binomial option pricing trees.',
          },
        ],
      },
      {
        title: 'Risk-Neutral Pricing & Fair Games',
        blocks: [
          {
            type: 'text',
            body: 'In options pricing, we compute expected values under the **risk-neutral measure**, not the real-world measure. Under risk-neutral pricing, all assets earn the risk-free rate in expectation. The price of any derivative is the discounted expected payoff under this measure.',
          },
          {
            type: 'formula',
            latex: 'V_0 = e^{-rT} \\cdot E^{\\mathbb{Q}}[\\text{Payoff}]',
            label: 'Risk-Neutral Pricing Formula',
            explanation: 'The value today equals the discounted expected payoff under the risk-neutral probability measure $\\mathbb{Q}$. This is the foundation of all option pricing.',
          },
          {
            type: 'concept',
            title: 'Why Risk-Neutral Pricing Works',
            body: 'We do not need to know investors\' risk preferences. By the no-arbitrage principle, we can construct a replicating portfolio that matches the derivative\'s payoff in every state. The cost of that portfolio is the fair price. It turns out this is mathematically equivalent to computing the expected payoff under a special probability measure where the underlying grows at the risk-free rate.',
          },
          {
            type: 'example',
            title: 'Risk-Neutral Pricing of a Simple Bet',
            problem: 'A stock is at $100. In one period it goes to $110 (up) or $90 (down). Risk-free rate is 5% per period. Price a call with strike $100.',
            solution: [
              'Find risk-neutral probability $q$: $100 \\cdot e^{0.05} = q \\cdot 110 + (1-q) \\cdot 90$',
              '$105.127 = 110q + 90(1-q) = 20q + 90$',
              '$q = (105.127 - 90)/20 = 0.7564$',
              'Call payoffs: Up $= \\max(110-100,0) = 10$, Down $= \\max(90-100,0) = 0$.',
              '$C = e^{-0.05}[0.7564 \\times 10 + 0.2436 \\times 0] = 0.9512 \\times 7.564 = 7.19$',
            ],
          },
        ],
      },
    ],
  },
  exercises: [
    // --- EASY (5) ---
    {
      id: 'd3-ev-01',
      exerciseType: 'numeric',
      difficulty: 'easy',
      topic: 'expected-value',
      tags: ['ev', 'dice'],
      timeEstimateSeconds: 30,
      question: 'What is the expected value of the sum of two fair 6-sided dice?',
      correctAnswer: 7,
      tolerance: 0.01,
      explanation: 'By linearity: $E[D_1 + D_2] = E[D_1] + E[D_2] = 3.5 + 3.5 = 7$.',
      solutionSteps: [
        'By linearity of expectation: $E[D_1 + D_2] = E[D_1] + E[D_2]$',
        '$= 3.5 + 3.5 = 7$',
        'No need to enumerate all 36 outcomes — linearity makes this trivial.',
      ],
    },
    {
      id: 'd3-ev-02',
      exerciseType: 'numeric',
      difficulty: 'easy',
      topic: 'expected-value',
      tags: ['ev', 'dice'],
      timeEstimateSeconds: 45,
      question: 'You roll a fair die. Your payoff is $\\max(\\text{roll} - 4, 0)$. What is the expected payoff?',
      correctAnswer: 0.50,
      tolerance: 0.01,
      explanation: '$E = \\frac{1}{6}[0+0+0+0+1+2] = \\frac{3}{6} = 0.50$',
      solutionSteps: [
        'Only rolls of 5 and 6 produce positive payoffs.',
        'Roll 5: payoff $= 5 - 4 = 1$',
        'Roll 6: payoff $= 6 - 4 = 2$',
        '$E = \\frac{1}{6}(0+0+0+0+1+2) = \\frac{3}{6} = 0.50$',
      ],
    },
    {
      id: 'd3-ev-03',
      exerciseType: 'multiple-choice',
      difficulty: 'easy',
      topic: 'expected-value',
      tags: ['ev', 'linearity'],
      timeEstimateSeconds: 30,
      question: 'Which property of expected value holds even when random variables are dependent?',
      options: [
        '$E[XY] = E[X] \\cdot E[Y]$',
        '$E[X + Y] = E[X] + E[Y]$',
        '$\\text{Var}(X + Y) = \\text{Var}(X) + \\text{Var}(Y)$',
        '$E[\\max(X,Y)] = \\max(E[X], E[Y])$',
      ],
      correctIndex: 1,
      explanation: 'Linearity of expectation ($E[X+Y] = E[X] + E[Y]$) holds for ALL random variables, independent or dependent. The other three require independence or special conditions.',
      solutionSteps: [
        '$E[XY] = E[X]E[Y]$ requires independence.',
        '$E[X+Y] = E[X]+E[Y]$ is always true (linearity).',
        '$\\text{Var}(X+Y) = \\text{Var}(X)+\\text{Var}(Y)$ requires uncorrelated variables.',
        '$E[\\max(X,Y)] \\neq \\max(E[X],E[Y])$ in general (Jensen\'s inequality direction).',
      ],
    },
    {
      id: 'd3-ev-04',
      exerciseType: 'true-false',
      difficulty: 'easy',
      topic: 'expected-value',
      tags: ['ev'],
      timeEstimateSeconds: 20,
      statement: 'A game with positive expected value is always profitable to play.',
      correct: false,
      explanation: 'A positive EV game is profitable in expectation over many plays, but any single play can result in a loss. Risk of ruin matters: if you bet your entire bankroll on a +EV game with high variance, you can still go broke.',
      solutionSteps: [
        'Positive EV means profitable on average over many repetitions.',
        'A single play can still lose money.',
        'Variance and risk of ruin matter for finite bankrolls.',
        'Example: a game that pays $1M with 1% probability and loses $100 otherwise has positive EV but is risky for a single play.',
      ],
    },
    {
      id: 'd3-ev-05',
      exerciseType: 'numeric',
      difficulty: 'easy',
      topic: 'expected-value',
      tags: ['ev', 'coins'],
      timeEstimateSeconds: 30,
      question: 'A fair coin is flipped. Heads pays $10, tails pays $4. What is the expected payoff?',
      correctAnswer: 7,
      tolerance: 0.01,
      unit: '$',
      explanation: '$E = 0.5 \\times 10 + 0.5 \\times 4 = 5 + 2 = 7$',
      solutionSteps: [
        '$E = P(H) \\times \\text{Payoff}(H) + P(T) \\times \\text{Payoff}(T)$',
        '$= 0.5 \\times 10 + 0.5 \\times 4 = 7$',
      ],
    },
    // --- MEDIUM (6) ---
    {
      id: 'd3-ev-06',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'optimal-stopping',
      tags: ['ev', 'dice', 'optimal-stopping'],
      timeEstimateSeconds: 120,
      question: 'You roll a fair die up to 2 times. After each roll, you can stop and collect that amount (in dollars), or re-roll. If you re-roll, the previous result is lost. What is the expected value under optimal play?',
      correctAnswer: 4.25,
      tolerance: 0.01,
      unit: '$',
      explanation: 'Re-roll EV is $3.50$. Keep if roll $\\geq 4$, re-roll if $\\leq 3$. $E = \\frac{1}{6}(3.5+3.5+3.5+4+5+6) = 25.5/6 = 4.25$.',
      solutionSteps: [
        'Stage 2 (last roll): EV of a single roll $= 3.50$.',
        'Stage 1: Keep the first roll if it exceeds 3.50 (i.e., roll 4, 5, or 6). Otherwise re-roll.',
        'If roll is 1, 2, or 3: you get EV $= 3.50$ from re-rolling.',
        'If roll is 4, 5, or 6: you keep it.',
        '$E = \\frac{1}{6}(3.5 + 3.5 + 3.5 + 4 + 5 + 6) = \\frac{25.5}{6} = 4.25$',
      ],
    },
    {
      id: 'd3-ev-07',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'expected-value',
      tags: ['ev', 'dice', 'call-option'],
      timeEstimateSeconds: 90,
      question: 'You roll two fair dice and your payoff is $\\max(\\text{sum} - 7, 0)$. What is the expected payoff?',
      correctAnswer: 0.972,
      tolerance: 0.01,
      explanation: 'Sum the call payoff $\\max(s-7,0)$ weighted by the probability of each sum from 2 to 12. Only sums 8-12 contribute.',
      solutionSteps: [
        'List payoffs for sums 8 through 12 (sums $\\leq 7$ contribute zero):',
        'Sum 8: payoff 1, probability $5/36$',
        'Sum 9: payoff 2, probability $4/36$',
        'Sum 10: payoff 3, probability $3/36$',
        'Sum 11: payoff 4, probability $2/36$',
        'Sum 12: payoff 5, probability $1/36$',
        '$E = \\frac{1}{36}(1 \\times 5 + 2 \\times 4 + 3 \\times 3 + 4 \\times 2 + 5 \\times 1)$',
        '$= \\frac{5 + 8 + 9 + 8 + 5}{36} = \\frac{35}{36} \\approx 0.972$',
      ],
    },
    {
      id: 'd3-ev-08',
      exerciseType: 'multi-step',
      difficulty: 'medium',
      topic: 'expected-value',
      tags: ['ev', 'dice'],
      timeEstimateSeconds: 120,
      question: 'A game works as follows: roll a fair die. If the roll is 1-3, you lose that amount. If the roll is 4-6, you win that amount. (a) What is the EV? (b) What is the fair entry fee?',
      steps: [
        {
          prompt: 'What is the expected value of the game?',
          correctAnswer: 1.5,
          tolerance: 0.01,
          unit: '$',
          stepExplanation: '$E = \\frac{1}{6}[(-1) + (-2) + (-3) + 4 + 5 + 6] = \\frac{9}{6} = 1.50$',
        },
        {
          prompt: 'What is the fair entry fee (price at which EV of playing = 0)?',
          correctAnswer: 1.5,
          tolerance: 0.01,
          unit: '$',
          stepExplanation: 'The fair fee equals the EV of the game: $\\$1.50$. At this price, the player has zero expected profit.',
        },
      ],
      explanation: 'The fair price of any bet equals its expected value. This is the fundamental principle behind option pricing.',
      solutionSteps: [
        'Payoffs: $-1, -2, -3, +4, +5, +6$ each with probability $1/6$.',
        '$E = \\frac{1}{6}(-1-2-3+4+5+6) = \\frac{9}{6} = 1.50$',
        'Fair entry fee $= E = \\$1.50$.',
      ],
    },
    {
      id: 'd3-ev-09',
      exerciseType: 'free-response',
      difficulty: 'medium',
      topic: 'conditional-expectation',
      tags: ['ev', 'conditional'],
      timeEstimateSeconds: 120,
      question: 'You roll two dice sequentially. After the first roll, you can choose to either: (A) take the first roll as your payoff, or (B) roll again and take the maximum of the two rolls. What is the optimal strategy and EV?',
      modelAnswer: 'Option B always dominates because $E[\\max(d_1, D_2)] \\geq d_1$ for all $d_1$, with strict inequality when $d_1 < 6$. So you always choose B. The EV is $E[\\max(D_1, D_2)] = \\frac{1}{36}\\sum_{i=1}^{6}\\sum_{j=1}^{6}\\max(i,j)$. Using $P(\\max = k) = (2k-1)/36$: $E = \\frac{1}{36}(1 \\cdot 1 + 2 \\cdot 3 + 3 \\cdot 5 + 4 \\cdot 7 + 5 \\cdot 9 + 6 \\cdot 11) = \\frac{161}{36} \\approx 4.472$.',
      explanation: 'Since taking the max can never hurt you, option B always dominates. The EV of the max of two dice is approximately 4.47.',
      solutionSteps: [
        'Option B dominates: $E[\\max(d_1, D_2)] \\geq d_1$ always, with strict inequality when $d_1 < 6$.',
        'So always choose B (roll again and take the max).',
        '$E[\\max(D_1, D_2)] = \\sum_{k=1}^{6} k \\cdot P(\\max = k)$',
        '$P(\\max = k) = (k^2 - (k-1)^2)/36 = (2k-1)/36$',
        '$E = \\frac{1}{36}(1 \\cdot 1 + 2 \\cdot 3 + 3 \\cdot 5 + 4 \\cdot 7 + 5 \\cdot 9 + 6 \\cdot 11) = \\frac{161}{36} = 4.472$',
      ],
    },
    {
      id: 'd3-ev-10',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'risk-neutral-pricing',
      tags: ['ev', 'risk-neutral', 'binomial'],
      timeEstimateSeconds: 90,
      question: 'A stock is at $50. In one period it goes to $60 (up) or $45 (down). The risk-free rate is 2% per period. What is the risk-neutral probability of the up move?',
      correctAnswer: 0.401,
      tolerance: 0.005,
      explanation: '$q = \\frac{S_0 e^r - S_d}{S_u - S_d} = \\frac{50 \\cdot 1.0202 - 45}{60 - 45} = \\frac{51.01 - 45}{15} = \\frac{6.01}{15} = 0.401$',
      solutionSteps: [
        'The risk-neutral probability $q$ satisfies: $S_0 e^r = q S_u + (1-q) S_d$',
        '$50 \\cdot e^{0.02} = q \\cdot 60 + (1-q) \\cdot 45$',
        '$51.01 = 60q + 45 - 45q = 15q + 45$',
        '$q = (51.01 - 45)/15 = 6.01/15 = 0.401$',
      ],
    },
    {
      id: 'd3-ev-11',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'expected-value',
      tags: ['ev', 'dice', 'put-option'],
      timeEstimateSeconds: 60,
      question: 'You roll a fair die. Your payoff is $\\max(4 - \\text{roll}, 0)$ (a "put" with strike 4). What is the expected payoff?',
      correctAnswer: 1.0,
      tolerance: 0.01,
      explanation: '$E = \\frac{1}{6}[3+2+1+0+0+0] = \\frac{6}{6} = 1.00$',
      solutionSteps: [
        'Rolls 1, 2, 3 are "in the money" for this put.',
        'Payoffs: $3, 2, 1, 0, 0, 0$.',
        '$E = \\frac{1}{6}(3+2+1+0+0+0) = \\frac{6}{6} = 1.00$',
      ],
    },
    // --- HARD (5) ---
    {
      id: 'd3-ev-12',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'optimal-stopping',
      tags: ['ev', 'dice', 'optimal-stopping'],
      timeEstimateSeconds: 180,
      question: 'You roll a fair die up to 3 times. After each roll, you can stop and collect that amount in dollars, or re-roll (losing the current value). What is the expected value under optimal play?',
      correctAnswer: 4.667,
      tolerance: 0.01,
      unit: '$',
      explanation: 'Stage 3 EV $= 3.50$. Stage 2 EV $= 4.25$ (keep $\\geq 4$). Stage 1: keep $\\geq 5$, otherwise use remaining 2 rolls. $E = \\frac{1}{6}(4.25+4.25+4.25+4.25+5+6) = 28.0/6 \\approx 4.667$.',
      solutionSteps: [
        'Stage 3: Single roll, $EV_3 = 3.50$.',
        'Stage 2: Keep if roll $> 3.50$ (i.e., 4, 5, 6); re-roll otherwise.',
        '$EV_2 = \\frac{1}{6}(3.5+3.5+3.5+4+5+6) = 25.5/6 = 4.25$',
        'Stage 1: Keep if roll $> 4.25$ (i.e., 5 or 6); use 2-roll game otherwise.',
        '$EV_1 = \\frac{1}{6}(4.25+4.25+4.25+4.25+5+6) = 28.0/6 = 4.667$',
      ],
    },
    {
      id: 'd3-ev-13',
      exerciseType: 'multi-step',
      difficulty: 'hard',
      topic: 'risk-neutral-pricing',
      tags: ['ev', 'risk-neutral', 'binomial', 'call-option'],
      timeEstimateSeconds: 180,
      question: 'A stock is at $100. In one period it goes to $120 or $85. Risk-free rate is 3% per period. (a) Find the risk-neutral probability of an up move. (b) Price a call with strike $105. (c) Price a put with strike $105 and verify put-call parity.',
      steps: [
        {
          prompt: 'What is the risk-neutral probability of an up move?',
          correctAnswer: 0.516,
          tolerance: 0.005,
          stepExplanation: '$q = \\frac{100 \\cdot e^{0.03} - 85}{120 - 85} = \\frac{103.05 - 85}{35} = \\frac{18.05}{35} = 0.516$',
        },
        {
          prompt: 'What is the price of the call with strike $105?',
          correctAnswer: 7.51,
          tolerance: 0.1,
          unit: '$',
          stepExplanation: 'Call payoffs: Up $= \\max(120-105,0) = 15$, Down $= \\max(85-105,0) = 0$. $C = e^{-0.03}[0.516 \\times 15] = 0.9704 \\times 7.74 = 7.51$.',
        },
        {
          prompt: 'What is the price of the put with strike $105?',
          correctAnswer: 9.40,
          tolerance: 0.1,
          unit: '$',
          stepExplanation: 'Put payoffs: Up $= 0$, Down $= \\max(105-85,0) = 20$. $P = e^{-0.03}[0.484 \\times 20] = 0.9704 \\times 9.69 = 9.40$. Parity check: $C - P = 7.51 - 9.40 = -1.89$. $S - Ke^{-rT} = 100 - 101.89 = -1.89$. Confirmed.',
        },
      ],
      explanation: 'This combines risk-neutral pricing with put-call parity verification, bridging Day 1 and Day 3 concepts.',
      solutionSteps: [
        '$q = (S_0 e^r - S_d)/(S_u - S_d) = (103.05 - 85)/35 = 0.516$',
        '$C = e^{-0.03}(0.516 \\times 15) = 0.9704 \\times 7.74 = 7.51$',
        '$P = e^{-0.03}(0.484 \\times 20) = 0.9704 \\times 9.69 = 9.40$',
        'Parity: $C - P = -1.89 = S - Ke^{-rT} = 100 - 101.89$. Confirmed.',
      ],
    },
    {
      id: 'd3-ev-14',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'expected-value',
      tags: ['ev', 'dice', 'custom-payoff'],
      timeEstimateSeconds: 120,
      question: 'You roll two fair dice. You are paid the product of the two rolls (in dollars). What is the expected payoff?',
      correctAnswer: 12.25,
      tolerance: 0.01,
      unit: '$',
      explanation: 'Since the dice are independent: $E[D_1 \\cdot D_2] = E[D_1] \\cdot E[D_2] = 3.5 \\times 3.5 = 12.25$.',
      solutionSteps: [
        'For independent random variables: $E[XY] = E[X] \\cdot E[Y]$.',
        '$E[D_1] = E[D_2] = 3.5$.',
        '$E[D_1 \\cdot D_2] = 3.5 \\times 3.5 = 12.25$.',
        'Note: this uses independence. If the dice were correlated, we would need the full joint distribution.',
      ],
    },
    {
      id: 'd3-ev-15',
      exerciseType: 'free-response',
      difficulty: 'hard',
      topic: 'optimal-stopping',
      tags: ['ev', 'optimal-stopping', 'backward-induction'],
      timeEstimateSeconds: 180,
      question: 'A game show offers you a sequence of envelopes. Envelope $k$ (for $k = 1, 2, 3$) contains $2^k$ dollars with probability 0.5 and $0 with probability 0.5. You open one at a time and must decide to keep its contents or move on (forgoing it). Derive the optimal strategy and EV using backward induction.',
      modelAnswer: 'Stage 3 (last envelope): Must take it. EV_3 = 0.5 x 8 + 0.5 x 0 = 4. Stage 2: Envelope 2 contains $4 or $0. If $4, keep (since 4 >= EV_3 = 4). If $0, move to envelope 3. EV_2 = 0.5 x 4 + 0.5 x 4 = 4. Stage 1: Envelope 1 contains $2 or $0. Since 2 < EV_2 = 4, always move on. EV_1 = 0.5 x 4 + 0.5 x 4 = 4. The optimal EV is $4.',
      explanation: 'Backward induction shows that the option value of future envelopes exactly offsets the gains from early stopping. The EV is $4 regardless of strategy in this special case.',
      solutionSteps: [
        'Stage 3: $EV_3 = 0.5 \\times 2^3 + 0.5 \\times 0 = 4$.',
        'Stage 2: Open envelope 2. If $\\$4$: keep (since $EV_3 = 4$, indifferent). If $\\$0$: move on, get $EV_3 = 4$.',
        '$EV_2 = 0.5 \\times 4 + 0.5 \\times 4 = 4$.',
        'Stage 1: Open envelope 1. If $\\$2 < EV_2 = 4$: move on. If $\\$0$: move on.',
        '$EV_1 = 0.5 \\times 4 + 0.5 \\times 4 = 4$.',
        'Optimal EV $= \\$4$.',
      ],
    },
    {
      id: 'd3-ev-16',
      exerciseType: 'free-response',
      difficulty: 'hard',
      topic: 'expected-value',
      tags: ['ev', 'geometric', 'coins', 'paradox'],
      timeEstimateSeconds: 120,
      question: 'A game pays $2^n$ dollars where $n$ is the number of heads before the first tail in a sequence of fair coin flips. What is the expected payoff? Explain why this is paradoxical.',
      modelAnswer: 'The expected payoff is infinite. $E = \\sum_{n=0}^{\\infty} 2^n \\cdot (1/2)^{n+1} = \\sum_{n=0}^{\\infty} 1/2 = \\infty$. This is the St. Petersburg paradox: despite infinite EV, no rational person would pay an unlimited amount to play because: (1) utility of money is concave (diminishing marginal utility), (2) the payer has finite wealth, and (3) the probability of extreme payoffs is negligible. The resolution involves expected utility theory or imposing a finite bankroll constraint.',
      explanation: 'The St. Petersburg paradox illustrates that EV alone is insufficient for decision-making when outcomes have unbounded variance.',
      solutionSteps: [
        '$P(n \\text{ heads then tail}) = (1/2)^{n+1}$',
        'Payoff for $n$ heads: $2^n$',
        '$E = \\sum_{n=0}^{\\infty} 2^n \\cdot (1/2)^{n+1} = \\sum_{n=0}^{\\infty} \\frac{1}{2} = \\infty$',
        'The series diverges, so EV is infinite.',
        'This is the St. Petersburg paradox, illustrating that EV alone is insufficient for decision-making.',
      ],
    },
    // --- INTERVIEW (3) ---
    {
      id: 'd3-ev-17',
      exerciseType: 'speed-drill',
      difficulty: 'interview',
      topic: 'ev-mental-math',
      tags: ['ev', 'mental-math', 'dice'],
      timeEstimateSeconds: 90,
      timeLimitSeconds: 90,
      problems: [
        { prompt: 'EV of a fair 6-sided die roll', correctAnswer: 3.5, tolerance: 0.01 },
        { prompt: 'EV of max(roll - 3, 0) on a fair die', correctAnswer: 1.0, tolerance: 0.01 },
        { prompt: 'EV of max(5 - roll, 0) on a fair die', correctAnswer: 1.667, tolerance: 0.02 },
        { prompt: 'EV of the sum of 3 fair dice', correctAnswer: 10.5, tolerance: 0.01 },
        { prompt: 'EV of the max of 2 fair coin flips (H=1, T=0)', correctAnswer: 0.75, tolerance: 0.01 },
        { prompt: 'Optimal 2-roll die game EV', correctAnswer: 4.25, tolerance: 0.01 },
      ],
      explanation: 'These are standard mental math calculations that should be instant for a trading interview.',
      solutionSteps: [
        'Die EV: $(1+2+3+4+5+6)/6 = 3.5$',
        '$\\max(\\text{roll}-3, 0)$: $(0+0+0+1+2+3)/6 = 1.0$',
        '$\\max(5-\\text{roll}, 0)$: $(4+3+2+1+0+0)/6 = 10/6 = 1.667$',
        '3 dice: $3 \\times 3.5 = 10.5$ (linearity)',
        '$\\max$ of 2 coins: $P(\\max=1) = 3/4$, $P(\\max=0) = 1/4$. $E = 3/4 = 0.75$',
        '2-roll die: $25.5/6 = 4.25$',
      ],
    },
    {
      id: 'd3-ev-18',
      exerciseType: 'numeric',
      difficulty: 'interview',
      topic: 'expected-value',
      tags: ['ev', 'mental-math', 'dice'],
      timeEstimateSeconds: 60,
      question: 'You roll a fair die repeatedly until you roll a 6. How many rolls do you expect it to take (including the final roll of 6)?',
      correctAnswer: 6,
      tolerance: 0.01,
      explanation: 'This is a geometric distribution with success probability $p = 1/6$. The expected number of trials until the first success is $1/p = 6$.',
      solutionSteps: [
        'Each roll is independent with $P(6) = 1/6$.',
        'The number of rolls until the first 6 follows a geometric distribution.',
        '$E[\\text{rolls}] = 1/p = 1/(1/6) = 6$.',
      ],
    },
    {
      id: 'd3-ev-19',
      exerciseType: 'free-response',
      difficulty: 'interview',
      topic: 'expected-value',
      tags: ['ev', 'dice', 'game-theory', 'mental-math'],
      timeEstimateSeconds: 180,
      question: 'You and an opponent each roll a fair die. Highest roll wins $1 from the other (ties re-rolled). Your opponent offers you the option to see their roll before you roll, but you must still roll a single die. What is the maximum you should pay for this information?',
      modelAnswer: 'Without the option, EV = $0 by symmetry. With the option: seeing their roll does not help because you cannot choose which number to roll. You must still roll a single fair die, and the distribution of your roll is the same regardless of what information you have. The outcome is determined entirely by the two independent dice, so information about one die does not change the EV of the comparison. The information is worth $0.',
      explanation: 'Information only has value if it can change your decision. If you must roll a single fair die regardless, seeing their result changes nothing about your expected outcome.',
      solutionSteps: [
        'Standard game: both roll, highest wins. By symmetry, $EV = 0$.',
        'If you see their roll first but must still roll your own die, your action space is unchanged.',
        'You cannot choose which number to roll, so the information is useless.',
        'Maximum payment for the option: $\\$0$.',
        'Key lesson: information has value only when it can influence your decisions.',
      ],
    },
  ],
  cumulativeExercises: [
    {
      id: 'd3-cum-01',
      exerciseType: 'multi-step',
      difficulty: 'medium',
      topic: 'ev-and-forwards',
      tags: ['ev', 'forward', 'risk-neutral'],
      timeEstimateSeconds: 120,
      fromDay: 1,
      question: 'A stock is at $100, risk-free rate is 4%, $T = 0.5$ years. (a) What is the forward price? (b) Under risk-neutral pricing, what is $E^{\\mathbb{Q}}[S_T]$? (c) Explain the connection.',
      steps: [
        {
          prompt: 'What is the 6-month forward price?',
          correctAnswer: 102.02,
          tolerance: 0.05,
          unit: '$',
          stepExplanation: '$F = 100 \\cdot e^{0.04 \\times 0.5} = 100 \\cdot e^{0.02} = 102.02$',
        },
        {
          prompt: 'Under the risk-neutral measure, what is $E^{\\mathbb{Q}}[S_T]$?',
          correctAnswer: 102.02,
          tolerance: 0.05,
          unit: '$',
          stepExplanation: 'Under the risk-neutral measure, the stock grows at $r$: $E^{\\mathbb{Q}}[S_T] = S_0 e^{rT} = 102.02$. This is exactly the forward price.',
        },
      ],
      explanation: 'The forward price equals the risk-neutral expected future stock price. This is why the forward is the "center" of the risk-neutral distribution.',
      solutionSteps: [
        '$F = S_0 e^{rT} = 100 e^{0.02} = 102.02$',
        '$E^{\\mathbb{Q}}[S_T] = S_0 e^{rT} = 102.02$ (under risk-neutral measure, drift $= r$)',
        'The forward price IS the risk-neutral expected future price.',
      ],
    },
    {
      id: 'd3-cum-02',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'ev-and-parity',
      tags: ['ev', 'put-call-parity', 'risk-neutral'],
      timeEstimateSeconds: 120,
      fromDay: 1,
      question: 'A stock is at $50, $r = 5\\%$, $T = 0.25$. In a one-period binomial model, the stock goes to $60 or $42. Price the 50-strike call using risk-neutral pricing, then derive the put price using put-call parity.',
      correctAnswer: 4.73,
      tolerance: 0.1,
      unit: '$ (call price)',
      explanation: '$q = (50 e^{0.0125} - 42)/(60-42) = (50.628 - 42)/18 = 8.628/18 = 0.4793$. $C = e^{-0.0125}(0.4793 \\times 10) = 0.9876 \\times 4.793 = 4.73$. Parity: $P = C - S + Ke^{-rT} = 4.73 - 50 + 49.38 = 4.11$.',
      solutionSteps: [
        '$q = (50 e^{0.0125} - 42)/(60-42) = 8.628/18 = 0.4793$',
        '$C = e^{-0.0125}(0.4793 \\times 10 + 0.5207 \\times 0) = 0.9876 \\times 4.793 = 4.73$',
        'Parity: $P = C - S + Ke^{-rT} = 4.73 - 50 + 49.38 = 4.11$',
        'Direct check: $P = e^{-0.0125}(0.5207 \\times 8) = 0.9876 \\times 4.166 = 4.11$. Confirmed.',
      ],
    },
    {
      id: 'd3-cum-03',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'ev-and-vol',
      tags: ['ev', 'volatility'],
      timeEstimateSeconds: 90,
      fromDay: 2,
      question: 'A stock is at $100 with 30% annual vol. Using a simple two-state model (up state $S_u = S_0 e^{(r - \\sigma^2/2) + \\sigma}$, down state $S_d = S_0 e^{(r-\\sigma^2/2)-\\sigma}$, each with 50% prob, $r=5\\%$), compute the expected payoff of a 100-strike call in 1 year.',
      correctAnswer: 17.83,
      tolerance: 1.5,
      unit: '$',
      explanation: 'Up: $100 e^{0.005 + 0.30} = 100 e^{0.305} = 135.66$. Down: $100 e^{0.005 - 0.30} = 100 e^{-0.295} = 74.44$. Call payoffs: Up $= 35.66$, Down $= 0$. $E = 0.5 \\times 35.66 = 17.83$.',
      solutionSteps: [
        '$r - \\sigma^2/2 = 0.05 - 0.045 = 0.005$',
        '$S_u = 100 e^{0.005 + 0.30} = 100 e^{0.305} = 135.66$',
        '$S_d = 100 e^{0.005 - 0.30} = 100 e^{-0.295} = 74.44$',
        'Call payoffs: $\\max(135.66 - 100, 0) = 35.66$ and $\\max(74.44 - 100, 0) = 0$.',
        '$E[\\text{payoff}] = 0.5 \\times 35.66 = 17.83$',
        'Discounted call price: $17.83 \\times e^{-0.05} = 16.96$.',
      ],
    },
  ],
  flashcards: [
    { id: 'd3-f01', front: 'Expected value formula (discrete)', back: '$E[X] = \\sum x_i \\cdot p_i$', tags: ['ev'] },
    { id: 'd3-f02', front: 'EV of a fair 6-sided die', back: '$E[X] = 3.5$', tags: ['ev', 'dice'] },
    { id: 'd3-f03', front: 'Linearity of expectation', back: '$E[aX + bY] = aE[X] + bE[Y]$, always — even for dependent variables.', tags: ['ev'] },
    { id: 'd3-f04', front: 'Optimal 2-roll die game EV', back: 'Keep if $\\geq 4$, re-roll otherwise. $EV = 4.25$.', tags: ['ev', 'optimal-stopping'] },
    { id: 'd3-f05', front: 'Optimal 3-roll die game EV', back: 'Stage 1: keep if $\\geq 5$. Stage 2: keep if $\\geq 4$. $EV \\approx 4.67$.', tags: ['ev', 'optimal-stopping'] },
    { id: 'd3-f06', front: 'Risk-neutral pricing formula', back: '$V_0 = e^{-rT} E^{\\mathbb{Q}}[\\text{Payoff}]$. Discount expected payoff under the risk-neutral measure.', tags: ['ev', 'risk-neutral'] },
    { id: 'd3-f07', front: 'Risk-neutral probability (binomial)', back: '$q = \\frac{S_0 e^{rT} - S_d}{S_u - S_d}$', tags: ['ev', 'risk-neutral', 'binomial'] },
    { id: 'd3-f08', front: 'EV of max(roll - K, 0) on a die (K=3.5)', back: '$\\frac{1}{6}(0.5 + 1.5 + 2.5) = 0.75$. This is a "call on a die" at the ATM strike.', tags: ['ev', 'dice', 'call-option'] },
    { id: 'd3-f09', front: 'Law of total expectation', back: '$E[X] = \\sum_j E[X|A_j] P(A_j)$. Decompose expectations via conditioning.', tags: ['ev', 'conditional'] },
    { id: 'd3-f10', front: 'Geometric distribution: expected trials until first success', back: '$E[N] = 1/p$ where $p$ is the probability of success on each trial.', tags: ['ev', 'geometric'] },
    { id: 'd3-f11', front: 'EV of the max of two fair dice', back: '$E[\\max(D_1,D_2)] = 161/36 \\approx 4.47$', tags: ['ev', 'dice'] },
    { id: 'd3-f12', front: 'Connection: forward price and risk-neutral EV', back: '$F = E^{\\mathbb{Q}}[S_T] = S_0 e^{rT}$. The forward IS the risk-neutral expected price.', tags: ['ev', 'forward', 'risk-neutral'] },
  ],
  interactiveTools: ['dice-game', 'payoff-diagram'],
  cheatSheet: [
    { topic: 'Expected Value', formula: 'E[X] = Σ xᵢ pᵢ', description: 'Probability-weighted average of outcomes' },
    { topic: 'Linearity', formula: 'E[aX+bY] = aE[X]+bE[Y]', description: 'Holds for any random variables, dependent or not' },
    { topic: 'Call on Die', formula: 'E[max(roll-K,0)] = Σ (xᵢ-K)pᵢ for xᵢ>K', description: 'Only ITM outcomes contribute' },
    { topic: '2-Roll Optimal Stop', formula: 'EV = 4.25', description: 'Keep >= 4, re-roll <= 3' },
    { topic: '3-Roll Optimal Stop', formula: 'EV = 4.667', description: 'Keep >= 5 on roll 1, >= 4 on roll 2' },
    { topic: 'Risk-Neutral Prob', formula: 'q = (S₀eʳᵀ - Sd)/(Su - Sd)', description: 'Binomial risk-neutral up probability' },
    { topic: 'Risk-Neutral Price', formula: 'V₀ = e⁻ʳᵀ E^Q[Payoff]', description: 'Discount risk-neutral expected payoff' },
    { topic: 'Geometric EV', formula: 'E[N] = 1/p', description: 'Expected trials until first success' },
  ],
  summary: [
    '$E[X] = \\sum x_i p_i$ is the foundation of all pricing and trading decisions',
    'Linearity of expectation: $E[X+Y] = E[X] + E[Y]$ always holds',
    'Backward induction: solve multi-stage games from the last stage forward',
    'Optimal stopping on $n$-roll die: 2-roll EV $= 4.25$, 3-roll EV $\\approx 4.67$',
    'Risk-neutral pricing: $V_0 = e^{-rT} E^{\\mathbb{Q}}[\\text{Payoff}]$, with $E^{\\mathbb{Q}}[S_T] = S_0 e^{rT}$ (the forward)',
  ],
};

export default day03;
