import { DayContent } from './types';

const day10: DayContent = {
  dayNumber: 10,
  title: 'Implied Vol Surfaces, Smile & Skew',
  subtitle: 'Natenberg Chapter 23',
  week: 2,
  chapters: ['Chapter 23'],
  estimatedMinutes: 130,
  prerequisites: [1, 2, 3, 4, 5, 6, 7, 8, 9],
  objectives: [
    'Understand why the volatility smile and skew exist and what they imply about the market',
    'Interpret volatility surfaces across strike and maturity dimensions',
    'Distinguish between sticky strike and sticky delta regimes',
    'Extract risk-neutral density from option prices via the Breeden-Litzenberger result',
    'Relate skew to crash risk, leverage effects, and supply/demand dynamics',
  ],
  theory: {
    sections: [
      {
        title: 'The Volatility Smile and Skew',
        blocks: [
          {
            type: 'text',
            body: 'Black-Scholes assumes constant volatility across all strikes and maturities. In reality, if you invert the BS formula for every traded option price, you get different implied volatilities for different strikes. Plotting IV against strike for a given expiry produces the **volatility smile** (or skew). This is one of the most important empirical facts in options markets.',
          },
          {
            type: 'concept',
            title: 'Smile vs. Skew',
            body: 'A **smile** is a U-shaped pattern where OTM puts and OTM calls both have higher IV than ATM options. Common in FX markets. A **skew** (or smirk) is when OTM puts have significantly higher IV than OTM calls. Common in equity index options since the 1987 crash. The skew reflects the market pricing a higher probability of large downward moves than the lognormal distribution implies.',
          },
          {
            type: 'formula',
            latex: '\\sigma_{\\text{imp}}(K) = \\sigma_{\\text{ATM}} + \\text{skew} \\times \\frac{K - F}{F} + \\text{smile} \\times \\left(\\frac{K - F}{F}\\right)^2',
            label: 'Quadratic Parameterization of Smile',
            explanation: 'A simple parameterization of the implied vol surface. The linear term captures skew (negative for equity indices). The quadratic term captures smile (positive curvature).',
          },
          {
            type: 'callout',
            variant: 'key-insight',
            body: 'The volatility skew is NOT an inefficiency. It reflects rational market pricing of fat tails, jump risk, and the asymmetric risk profile of equity markets. Trying to arbitrage the skew by selling OTM puts is a classic way to blow up.',
          },
        ],
      },
      {
        title: 'The Volatility Term Structure',
        blocks: [
          {
            type: 'text',
            body: 'The **term structure** of volatility shows how ATM implied vol varies across expiration dates. Typically, short-term vol is more volatile and mean-reverts faster than long-term vol. In calm markets, the term structure slopes upward (short-term vol < long-term vol). In crisis, it inverts (short-term vol spikes above long-term).',
          },
          {
            type: 'concept',
            title: 'The Full Volatility Surface',
            body: 'The vol surface is a 3D object: $\\sigma_{\\text{imp}}(K, T)$, mapping every strike-maturity pair to an implied vol. It encodes ALL the market\'s information about option pricing. Market makers must maintain a consistent, arbitrage-free vol surface at all times.',
          },
          {
            type: 'table',
            headers: ['Market Regime', 'Short-term IV', 'Long-term IV', 'Term Structure Shape'],
            rows: [
              ['Calm / Low vol', 'Low', 'Higher', 'Upward sloping (contango)'],
              ['Crisis / High vol', 'Very high', 'Lower', 'Inverted (backwardation)'],
              ['Mean-reverting', 'At long-term mean', 'At long-term mean', 'Flat'],
            ],
          },
          {
            type: 'callout',
            variant: 'tip',
            body: 'Think of the vol term structure like a yield curve. Normal: upward sloping. Inverted: crisis signal. The shape tells you about the market\'s expectation of future volatility.',
          },
        ],
      },
      {
        title: 'Sticky Strike vs. Sticky Delta',
        blocks: [
          {
            type: 'text',
            body: 'When the underlying moves, how does the vol surface shift? Two common models:',
          },
          {
            type: 'concept',
            title: 'Sticky Strike',
            body: 'Under **sticky strike**, the implied vol for each strike stays constant as the underlying moves. If the 100-strike option has 25% vol, it keeps 25% vol regardless of where the stock goes. This means as the stock rises, the ATM vol (now at a higher strike) changes. Sticky strike implies the vol surface is anchored to absolute strike levels.',
          },
          {
            type: 'concept',
            title: 'Sticky Delta',
            body: 'Under **sticky delta** (or sticky moneyness), the implied vol for a given moneyness level (e.g., 25-delta put) stays constant. As the stock rises from 100 to 105, the ATM vol stays the same (it moves to the 105 strike). This means strike-level vols change. Sticky delta implies the vol surface moves with the underlying.',
          },
          {
            type: 'callout',
            variant: 'key-insight',
            body: 'Neither regime is always correct. Empirically, equity markets often behave between the two. Understanding which regime is dominant matters for hedging: sticky strike implies a different delta adjustment than sticky delta. Market makers who get this wrong will be systematically over- or under-hedged.',
          },
          {
            type: 'formula',
            latex: '\\Delta_{\\text{sticky-strike}} = \\Delta_{\\text{BS}} \\quad ; \\quad \\Delta_{\\text{sticky-delta}} = \\Delta_{\\text{BS}} + \\nu \\cdot \\frac{\\partial \\sigma}{\\partial S}',
            label: 'Delta Adjustment for Sticky Regimes',
            explanation: 'Under sticky strike, the BS delta is correct. Under sticky delta, you need to add a vol-sensitivity adjustment: the product of vega and the slope of IV with respect to the underlying.',
          },
        ],
      },
      {
        title: 'Risk-Neutral Density and the Breeden-Litzenberger Result',
        blocks: [
          {
            type: 'text',
            body: 'The prices of options across all strikes encode the market\'s **risk-neutral probability distribution** for the underlying at expiry. The Breeden-Litzenberger (1978) result shows how to extract this distribution from option prices.',
          },
          {
            type: 'formula',
            latex: 'f(K) = e^{rT} \\frac{\\partial^2 C}{\\partial K^2}',
            label: 'Breeden-Litzenberger Formula',
            explanation: 'The risk-neutral probability density at $K$ equals $e^{rT}$ times the second derivative of the call price with respect to strike. In practice, this is estimated using butterfly spreads.',
          },
          {
            type: 'concept',
            title: 'Butterfly Spread as a Density Probe',
            body: 'A butterfly spread centered at $K$ (long $C(K-\\delta)$, short $2C(K)$, long $C(K+\\delta)$) approximates the second derivative of $C$ with respect to $K$. Its price, divided by $\\delta^2$ and multiplied by $e^{rT}$, gives the risk-neutral density at $K$. A more expensive butterfly means higher probability density at that strike.',
          },
          {
            type: 'callout',
            variant: 'key-insight',
            body: 'The vol smile/skew is just another way of encoding the risk-neutral density. A negatively skewed vol surface corresponds to a left-skewed (fat left tail) risk-neutral density. This is why equity index vol surfaces are negatively skewed: the market prices a higher probability of crashes.',
          },
        ],
      },
    ],
  },
  exercises: [
    {
      id: 'd10-smile-01',
      exerciseType: 'multiple-choice',
      difficulty: 'easy',
      topic: 'vol-smile',
      tags: ['vol-smile', 'skew'],
      timeEstimateSeconds: 30,
      question: 'After the 1987 crash, equity index option markets typically exhibit:',
      options: [
        'A symmetric volatility smile',
        'A negative volatility skew (OTM puts have higher IV)',
        'A positive volatility skew (OTM calls have higher IV)',
        'Flat implied volatility across all strikes',
      ],
      correctIndex: 1,
      explanation: 'Post-1987, equity index options display a pronounced negative skew (also called the "smirk"). OTM puts have higher IV than ATM options, reflecting crash risk and demand for downside protection.',
      solutionSteps: [
        'Before 1987: vol surface was roughly flat (BS assumptions seemed OK).',
        'After the crash: market permanently repriced tail risk.',
        'OTM puts became expensive (higher IV) due to crash protection demand.',
        'This creates a negative skew: IV decreases as strike increases.',
      ],
    },
    {
      id: 'd10-smile-02',
      exerciseType: 'true-false',
      difficulty: 'easy',
      topic: 'vol-smile',
      tags: ['vol-smile', 'black-scholes'],
      timeEstimateSeconds: 15,
      statement: 'The existence of the volatility smile is consistent with the Black-Scholes assumption of constant volatility.',
      correct: false,
      explanation: 'Black-Scholes assumes a single, constant volatility for all strikes and maturities. The smile directly contradicts this: different strikes imply different volatilities. The smile is evidence that the BS model is an incomplete description of reality.',
      solutionSteps: [
        'BS assumes $\\sigma$ is constant across strikes and time.',
        'The smile means $\\sigma_{imp}$ varies with $K$.',
        'This directly contradicts the BS assumption.',
      ],
    },
    {
      id: 'd10-smile-03',
      exerciseType: 'multiple-choice',
      difficulty: 'medium',
      topic: 'vol-smile',
      tags: ['vol-smile', 'fx'],
      timeEstimateSeconds: 30,
      question: 'In FX options markets, the volatility pattern across strikes is typically:',
      options: [
        'A negative skew (like equity indices)',
        'A symmetric smile (U-shaped)',
        'Flat',
        'A positive skew (OTM calls more expensive)',
      ],
      correctIndex: 1,
      explanation: 'FX markets typically show a symmetric smile because currency pairs have symmetric risk in either direction (one currency strengthening is the other weakening). Neither tail is inherently more feared.',
      solutionSteps: [
        'In FX, there is no inherent directional bias (unlike equities which tend to crash down).',
        'Both tails carry risk: either currency could move sharply.',
        'This produces a U-shaped (symmetric) smile.',
      ],
    },
    {
      id: 'd10-term-01',
      exerciseType: 'multiple-choice',
      difficulty: 'medium',
      topic: 'term-structure',
      tags: ['term-structure', 'vol-surface'],
      timeEstimateSeconds: 45,
      question: 'The VIX is at 35 while 1-year ATM implied vol is at 22. What does this term structure shape indicate?',
      options: [
        'The market is calm and expects vol to stay low',
        'The market is in crisis; short-term vol is elevated and expected to mean-revert',
        'The market expects a major event in one year',
        'Implied vol is mispriced and there is an arbitrage',
      ],
      correctIndex: 1,
      explanation: 'An inverted term structure (short-term vol >> long-term vol) indicates a current crisis or stress. The market expects volatility to mean-revert from the elevated short-term level back to the long-term average.',
      solutionSteps: [
        'VIX (30-day IV) = 35, much higher than 1-year IV = 22.',
        'This is an inverted term structure.',
        'Inversion signals current stress with expected mean-reversion.',
        'The market believes the crisis is temporary.',
      ],
    },
    {
      id: 'd10-sticky-01',
      exerciseType: 'free-response',
      difficulty: 'medium',
      topic: 'sticky-strike-delta',
      tags: ['sticky-strike', 'sticky-delta'],
      timeEstimateSeconds: 120,
      question: 'A stock is at $100 and the 100-strike call has 25% IV. The 105-strike call has 23% IV. The stock rises to $105. Under sticky strike, what is the new ATM vol? Under sticky delta?',
      modelAnswer: 'Under **sticky strike**: Each strike keeps its IV. The 100-strike still has 25% IV and the 105-strike still has 23% IV. The new ATM (now at 105) has IV = 23%. So ATM vol dropped from 25% to 23%. Under **sticky delta**: The ATM vol stays at 25% regardless of where the stock moves. The 25% vol "moves" to the 105 strike. The 100-strike (now 5 points OTM put side) gets a different vol, likely higher due to the skew. So under sticky delta, ATM vol is unchanged at 25%.',
      explanation: 'Sticky strike: vol is tied to the strike level. Sticky delta: vol is tied to the moneyness.',
      solutionSteps: [
        'Sticky strike: 100-strike keeps 25%, 105-strike keeps 23%.',
        'New ATM (at $105) has IV = 23%.',
        'Sticky delta: ATM vol stays at 25% (moneyness-based).',
        'The 105-strike (now ATM) gets 25% vol.',
        'Key difference: sticky strike sees ATM vol drop; sticky delta sees it unchanged.',
      ],
    },
    {
      id: 'd10-bl-01',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'risk-neutral-density',
      tags: ['breeden-litzenberger', 'butterfly'],
      timeEstimateSeconds: 120,
      question: 'Three call prices: $C(95) = 8.50$, $C(100) = 5.20$, $C(105) = 2.80$. $r = 3\\%$, $T = 0.25$. Estimate the risk-neutral probability density at $K = 100$ using the Breeden-Litzenberger formula with $\\delta = 5$.',
      correctAnswer: 0.037,
      tolerance: 0.003,
      unit: 'per $',
      explanation: '$\\frac{\\partial^2 C}{\\partial K^2} \\approx \\frac{C(K-\\delta) - 2C(K) + C(K+\\delta)}{\\delta^2} = \\frac{8.50 - 10.40 + 2.80}{25} = \\frac{0.90}{25} = 0.036$. Density = $e^{rT} \\times 0.036 = e^{0.0075} \\times 0.036 = 1.00753 \\times 0.036 = 0.0363$.',
      solutionSteps: [
        'Estimate second derivative: $\\frac{C(95) - 2C(100) + C(105)}{5^2}$',
        '$= \\frac{8.50 - 10.40 + 2.80}{25} = \\frac{0.90}{25} = 0.036$',
        'Apply Breeden-Litzenberger: $f(100) = e^{rT} \\times 0.036$',
        '$= e^{0.0075} \\times 0.036 = 1.00753 \\times 0.036 = 0.0363$',
        'Interpretation: ~3.6% probability density per dollar at $K = 100$.',
      ],
    },
    {
      id: 'd10-bl-02',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'risk-neutral-density',
      tags: ['breeden-litzenberger', 'butterfly'],
      timeEstimateSeconds: 120,
      question: 'Using the same prices: $C(95) = 8.50$, $C(100) = 5.20$, $C(105) = 2.80$. What is the price of the 95/100/105 butterfly spread? What does it represent?',
      correctAnswer: 0.90,
      tolerance: 0.01,
      unit: '$',
      explanation: 'Butterfly = $C(95) - 2C(100) + C(105) = 8.50 - 10.40 + 2.80 = 0.90$. This is proportional to the risk-neutral probability that the stock finishes near $100 (specifically between $95 and $105).',
      solutionSteps: [
        'Butterfly price = $C(K - \\delta) - 2C(K) + C(K + \\delta)$',
        '$= 8.50 - 2(5.20) + 2.80 = 8.50 - 10.40 + 2.80 = 0.90$',
        'This is the cost of betting on the stock finishing near $100.',
        'It approximates $e^{-rT} \\times f(100) \\times \\delta^2 = e^{-rT} \\times \\text{density} \\times 25$.',
      ],
    },
    {
      id: 'd10-skew-01',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'vol-skew',
      tags: ['skew', 'vol-surface'],
      timeEstimateSeconds: 60,
      question: 'The 25-delta put has IV = 28%, ATM IV = 22%, 25-delta call IV = 19%. What is the risk reversal (25d)?',
      correctAnswer: -9,
      tolerance: 0.5,
      unit: 'vol points',
      explanation: 'Risk reversal = IV(25d call) - IV(25d put) = 19% - 28% = -9 vol points. A negative risk reversal indicates a negatively skewed surface (typical for equities).',
      solutionSteps: [
        'Risk reversal = $\\sigma_{25\\Delta C} - \\sigma_{25\\Delta P}$',
        '$= 19\\% - 28\\% = -9\\%$ (or $-9$ vol points)',
        'Negative = puts are more expensive than calls = negative skew.',
      ],
    },
    {
      id: 'd10-skew-02',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'vol-skew',
      tags: ['skew', 'vol-surface'],
      timeEstimateSeconds: 60,
      question: 'Using the same data (25d put IV = 28%, ATM IV = 22%, 25d call IV = 19%), what is the butterfly (25d)?',
      correctAnswer: 1.5,
      tolerance: 0.5,
      unit: 'vol points',
      explanation: 'Butterfly = $\\frac{\\sigma_{25\\Delta P} + \\sigma_{25\\Delta C}}{2} - \\sigma_{ATM} = \\frac{28 + 19}{2} - 22 = 23.5 - 22 = 1.5$ vol points. Positive = smile curvature (wings are expensive relative to ATM).',
      solutionSteps: [
        'Butterfly = $\\frac{\\sigma_{25\\Delta P} + \\sigma_{25\\Delta C}}{2} - \\sigma_{ATM}$',
        '$= \\frac{28 + 19}{2} - 22 = 23.5 - 22 = 1.5$ vol points',
        'This measures the curvature (convexity) of the smile.',
      ],
    },
    {
      id: 'd10-sticky-02',
      exerciseType: 'multiple-choice',
      difficulty: 'hard',
      topic: 'sticky-strike-delta',
      tags: ['sticky-strike', 'sticky-delta', 'hedging'],
      timeEstimateSeconds: 60,
      question: 'Under sticky delta, when the stock drops, what happens to the IV of a fixed-strike OTM call?',
      options: [
        'It stays the same because the strike is fixed',
        'It increases because the call becomes more OTM (further from ATM on the smile)',
        'It decreases because the overall vol surface drops',
        'It decreases because the call becomes closer to ATM',
      ],
      correctIndex: 1,
      explanation: 'Under sticky delta, the vol surface moves with the underlying. When the stock drops, a fixed-strike call becomes more OTM (higher delta-distance from ATM). Under the smile, more OTM options have higher IV. So the IV of this call increases.',
      solutionSteps: [
        'Sticky delta: the smile is anchored to moneyness (delta), not absolute strikes.',
        'Stock drops: the fixed-strike call moves further OTM.',
        'On the smile, further OTM options have higher IV.',
        'Therefore, the IV of this fixed-strike call increases.',
      ],
    },
    {
      id: 'd10-surface-01',
      exerciseType: 'free-response',
      difficulty: 'hard',
      topic: 'vol-surface',
      tags: ['vol-surface', 'arbitrage'],
      timeEstimateSeconds: 150,
      question: 'What are the no-arbitrage constraints on a volatility surface? Name at least three.',
      modelAnswer: '(1) **Calendar spread constraint**: Forward variance must be non-negative. $\\sigma^2(T_2) \\cdot T_2 \\geq \\sigma^2(T_1) \\cdot T_1$ for $T_2 > T_1$. Otherwise you could sell the short-dated and buy the long-dated for a guaranteed profit. (2) **Butterfly constraint**: The risk-neutral density must be non-negative everywhere. This means $\\frac{\\partial^2 C}{\\partial K^2} \\geq 0$ (call prices are convex in strike). A negative butterfly price would be an arbitrage. (3) **Monotonicity in strike**: Call prices must be decreasing in strike ($\\frac{\\partial C}{\\partial K} \\leq 0$) and put prices must be increasing in strike. (4) **Bounds**: $0 \\leq C(K,T) \\leq S$ and $0 \\leq P(K,T) \\leq Ke^{-rT}$.',
      explanation: 'A vol surface must satisfy these constraints to be arbitrage-free. Market makers check these constantly.',
      solutionSteps: [
        'Calendar: forward variance $\\geq 0$ (total variance increases with maturity).',
        'Butterfly: $C(K-\\delta) - 2C(K) + C(K+\\delta) \\geq 0$ (convexity in strike).',
        'Monotonicity: $C(K_1) \\geq C(K_2)$ for $K_1 < K_2$ (calls decrease in strike).',
        'Bounds: call $\\leq S$, put $\\leq Ke^{-rT}$.',
      ],
    },
    {
      id: 'd10-interview-01',
      exerciseType: 'free-response',
      difficulty: 'interview',
      topic: 'vol-smile',
      tags: ['vol-smile', 'interview'],
      timeEstimateSeconds: 120,
      question: 'Why does the volatility skew exist in equity markets? Give at least three explanations.',
      modelAnswer: '(1) **Crash risk / fat tails**: Real-world stock returns have fatter left tails than lognormal. Large drops are more common than BS predicts. OTM puts must be priced higher to reflect this. (2) **Leverage effect**: As a stock falls, its leverage (debt/equity) increases, making it riskier and increasing its volatility. This creates a negative correlation between returns and vol. (3) **Supply/demand**: Institutional investors systematically buy OTM puts for portfolio insurance and sell OTM calls (covered calls). This demand pressure pushes up OTM put prices and pushes down OTM call prices, creating skew. (4) **Jump risk**: Markets can gap down suddenly (crashes), but rarely gap up by the same magnitude. Jump models naturally produce negative skew.',
      explanation: 'The skew reflects a combination of statistical reality (fat tails), economic mechanisms (leverage), and market structure (supply/demand).',
      solutionSteps: [
        'Fat tails: real returns have more extreme left-tail events than lognormal.',
        'Leverage effect: falling stock price increases leverage and vol.',
        'Supply/demand: institutional hedging inflates OTM put prices.',
        'Jump risk: downward jumps more severe than upward ones.',
      ],
    },
    {
      id: 'd10-interview-02',
      exerciseType: 'numeric',
      difficulty: 'interview',
      topic: 'vol-surface',
      tags: ['vol-surface', 'mental-math', 'interview'],
      timeEstimateSeconds: 45,
      question: 'ATM 1-month IV = 20%, ATM 3-month IV = 24%. What is the forward vol from month 1 to month 3? (Use $\\sigma_f^2 \\cdot \\Delta T = \\sigma_2^2 T_2 - \\sigma_1^2 T_1$.)',
      correctAnswer: 26.2,
      tolerance: 0.5,
      unit: '%',
      explanation: '$\\sigma_f^2 = \\frac{\\sigma_2^2 T_2 - \\sigma_1^2 T_1}{T_2 - T_1} = \\frac{0.24^2 \\times 3/12 - 0.20^2 \\times 1/12}{2/12} = \\frac{0.0144 - 0.00333}{0.1667} = \\frac{0.01107}{0.1667} = 0.0664$. $\\sigma_f = \\sqrt{0.0664} = 0.2577 = 25.8\\%$.',
      solutionSteps: [
        'Total variance at 1 month: $0.20^2 \\times 1/12 = 0.04/12 = 0.003333$',
        'Total variance at 3 months: $0.24^2 \\times 3/12 = 0.0576/4 = 0.01440$',
        'Forward variance: $\\frac{0.01440 - 0.003333}{2/12} = \\frac{0.01107}{0.1667} = 0.0664$',
        'Forward vol = $\\sqrt{0.0664} = 25.8\\%$',
      ],
    },
    {
      id: 'd10-smile-04',
      exerciseType: 'true-false',
      difficulty: 'medium',
      topic: 'vol-smile',
      tags: ['vol-smile', 'risk-neutral'],
      timeEstimateSeconds: 30,
      statement: 'A negative volatility skew implies the risk-neutral distribution has a fatter left tail than the lognormal distribution.',
      correct: true,
      explanation: 'A negative skew means OTM puts (low strikes) have higher IV. Higher IV at low strikes means the BS model needs more vol to match market prices there, implying the market assigns more probability to large downward moves than lognormal would. This is a fatter left tail.',
      solutionSteps: [
        'Negative skew: IV increases as strike decreases.',
        'Higher IV at low strikes = higher option prices at low strikes.',
        'Higher option prices = more probability mass in the left tail.',
        'Therefore: fatter left tail than lognormal.',
      ],
    },
  ],
  cumulativeExercises: [
    {
      id: 'd10-cum-01',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'parity-with-skew',
      tags: ['put-call-parity', 'skew', 'implied-vol'],
      timeEstimateSeconds: 90,
      fromDay: 1,
      question: 'A 100-strike call has IV = 22% and the 100-strike put has IV = 22%. A 90-strike put has IV = 28%. Does the 90-strike call also have IV = 28%?',
      correctAnswer: 28,
      tolerance: 0.1,
      unit: '%',
      explanation: 'Yes. Put-call parity guarantees that the call and put AT THE SAME STRIKE have the same implied vol. This is because parity is model-independent: $C - P = S - Ke^{-rT}$. Since the right side does not depend on vol, C and P must be consistent with the same vol. So the 90-strike call also has IV = 28%.',
      solutionSteps: [
        'Put-call parity: $C(K) - P(K) = S - Ke^{-rT}$. Model-independent.',
        'The right side is fixed (no vol dependence).',
        'If $P(90)$ implies 28% vol, then $C(90)$ must also imply 28% vol.',
        'Otherwise parity is violated = arbitrage.',
      ],
    },
    {
      id: 'd10-cum-02',
      exerciseType: 'free-response',
      difficulty: 'hard',
      topic: 'greeks-with-skew',
      tags: ['delta', 'vega', 'skew'],
      timeEstimateSeconds: 150,
      fromDay: 5,
      question: 'How does the volatility skew affect the delta of an OTM put compared to the BS delta computed with ATM vol? Is the skew-adjusted delta higher or lower in magnitude?',
      modelAnswer: 'The skew-adjusted delta of an OTM put is HIGHER in magnitude (more negative) than the BS delta computed with ATM vol. Reason: under the skew, OTM puts have higher IV than ATM. Using the correct (higher) IV to compute delta gives a larger $|\\Delta|$ because: (1) higher vol makes the put less far out of the money in standardized terms ($d_1$ is closer to zero), and (2) under sticky delta, when the stock drops, IV rises (skew effect), amplifying the put\'s sensitivity. In practice, skew-aware deltas are 10-30% larger in magnitude than flat-vol deltas for OTM puts.',
      explanation: 'The skew increases the effective delta of OTM puts, which is critical for portfolio hedging.',
      solutionSteps: [
        'OTM put IV > ATM IV (negative skew).',
        'Higher IV for the put means $d_1$ is closer to zero (less OTM in vol-normalized terms).',
        'This increases $|\\Delta_{put}|$.',
        'Additionally, $\\Delta_{adj} = \\Delta_{BS} + \\nu \\cdot \\frac{\\partial \\sigma}{\\partial S}$.',
        'Since $\\frac{\\partial \\sigma}{\\partial S} < 0$ (negative skew) and $\\nu > 0$, the adjustment is negative.',
        'For a put (already negative delta), this makes it more negative.',
      ],
    },
    {
      id: 'd10-cum-03',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'bs-with-smile',
      tags: ['black-scholes', 'implied-vol', 'pricing'],
      timeEstimateSeconds: 120,
      fromDay: 3,
      question: 'Using BS with $S = 100$, $K = 90$, $r = 3\\%$, $T = 0.25$, and a skew-implied vol of 28% (vs ATM vol of 22%): compute the 90-strike put price. Then compute what it would be using ATM vol. What is the difference?',
      correctAnswer: 1.42,
      tolerance: 0.3,
      unit: '$',
      hint: 'Use BS formula with each vol to get two put prices. The difference is the "skew premium."',
      explanation: 'With $\\sigma = 28\\%$: $d_1 = \\frac{\\ln(100/90) + (0.03 + 0.0392)\\times 0.25}{0.28 \\times 0.5} = \\frac{0.10536 + 0.01730}{0.14} = 0.877$. $d_2 = 0.877 - 0.14 = 0.737$. $P = 90e^{-0.0075}N(-0.737) - 100 N(-0.877) = 89.33 \\times 0.2306 - 100 \\times 0.1903 = 20.60 - 19.03 = 1.57$. With $\\sigma = 22\\%$: similar calc gives $P \\approx 0.15$. Difference $\\approx 1.42$.',
      solutionSteps: [
        'BS with $\\sigma = 28\\%$: compute $d_1, d_2$ and put price.',
        'BS with $\\sigma = 22\\%$: compute $d_1, d_2$ and put price.',
        'The OTM put is significantly more expensive with skew vol.',
        'Difference $\\approx \\$1.42$ -- this is the skew premium.',
      ],
    },
    {
      id: 'd10-cum-04',
      exerciseType: 'multiple-choice',
      difficulty: 'medium',
      topic: 'vega-surface',
      tags: ['vega', 'vol-surface'],
      timeEstimateSeconds: 45,
      fromDay: 5,
      question: 'A trader is long a 90-strike put (IV = 28%) and short a 100-strike put (IV = 22%). If the entire vol surface shifts up by 1%, what is the approximate P&L? Assume vega(90P) = 0.12 and vega(100P) = 0.18 per 1% vol.',
      options: [
        '+$0.06 (net vega positive)',
        '-$0.06 (net vega negative)',
        '+$0.30 (both options gain)',
        '-$0.30 (both options lose)',
      ],
      correctIndex: 1,
      explanation: 'Net vega = long put vega - short put vega = $0.12 - 0.18 = -0.06$. A 1% vol increase costs $0.06. The position is net short vega because the short ATM put has more vega than the long OTM put.',
      solutionSteps: [
        'Long 90P vega = +0.12. Short 100P vega = -0.18.',
        'Net vega = $0.12 - 0.18 = -0.06$.',
        'Vol up 1%: P&L = $-0.06 \\times 1 = -\\$0.06$.',
      ],
    },
    {
      id: 'd10-cum-05',
      exerciseType: 'scenario',
      difficulty: 'hard',
      topic: 'sticky-strike-pnl',
      tags: ['sticky-strike', 'sticky-delta', 'pnl'],
      timeEstimateSeconds: 180,
      fromDay: 5,
      question: 'You are long a 95-strike put with IV = 26%. ATM vol (at $S = 100$) is 22%. The stock drops from 100 to 95. Analyze P&L under different sticky regimes.',
      scenarios: [
        {
          description: 'Sticky strike: IV of 95-strike stays at 26%. What is the change in moneyness?',
          shocks: [{ variable: 'stock_price', change: -5 }],
          expectedAnswer: 0,
          tolerance: 0,
          unit: 'vol change (%)',
        },
        {
          description: 'Sticky delta: ATM vol stays at 22%. 95-strike is now ATM. What is its new IV?',
          shocks: [{ variable: 'stock_price', change: -5 }],
          expectedAnswer: 22,
          tolerance: 0.5,
          unit: '%',
        },
      ],
      explanation: 'Under sticky strike, the 95-strike keeps 26% IV even though it is now ATM. Under sticky delta, the 95-strike (now ATM) gets ATM vol of 22%. The sticky delta regime hurts the long put position (vol drops from 26% to 22% as the stock moves towards the strike).',
      solutionSteps: [
        'Sticky strike: IV at each strike is fixed. 95-strike stays at 26%. No vol change.',
        'Sticky delta: ATM vol is always 22%. Stock moves to 95, so 95 is now ATM. IV drops to 22%.',
        'For the long put: sticky strike is better (vol stays high); sticky delta is worse (vol drops).',
        'The 4 vol point drop under sticky delta costs approximately $\\text{vega} \\times 4\\% \\approx \\$0.50$ per contract.',
      ],
    },
    {
      id: 'd10-cum-06',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'forward-vol',
      tags: ['term-structure', 'forward-variance'],
      timeEstimateSeconds: 90,
      fromDay: 7,
      question: '1-month ATM IV = 18%, 2-month ATM IV = 20%. What is the 1-month forward implied vol from month 1 to month 2?',
      correctAnswer: 21.8,
      tolerance: 0.3,
      unit: '%',
      explanation: '$\\sigma_f^2 = \\frac{\\sigma_2^2 T_2 - \\sigma_1^2 T_1}{T_2 - T_1} = \\frac{0.04 \\times 2/12 - 0.0324 \\times 1/12}{1/12} = \\frac{0.006667 - 0.002700}{0.08333} = \\frac{0.003967}{0.08333} = 0.04760$. $\\sigma_f = 21.8\\%$.',
      solutionSteps: [
        'Total variance at 1 month: $0.18^2 \\times 1/12 = 0.002700$',
        'Total variance at 2 months: $0.20^2 \\times 2/12 = 0.006667$',
        'Forward variance: $(0.006667 - 0.002700) / (1/12) = 0.04760$',
        'Forward vol = $\\sqrt{0.04760} = 21.8\\%$.',
      ],
    },
  ],
  flashcards: [
    { id: 'd10-f01', front: 'What is the volatility smile?', back: 'A U-shaped pattern of IV vs. strike: OTM puts and calls have higher IV than ATM. Common in FX.', tags: ['vol-smile'] },
    { id: 'd10-f02', front: 'What is the volatility skew?', back: 'A pattern where IV increases as strike decreases (OTM puts have higher IV). Common in equity indices post-1987.', tags: ['skew'] },
    { id: 'd10-f03', front: 'Sticky strike regime', back: 'IV at each absolute strike is fixed when the underlying moves. If stock rises, ATM vol changes.', tags: ['sticky-strike'] },
    { id: 'd10-f04', front: 'Sticky delta regime', back: 'IV at each moneyness level (e.g., 25d put) is fixed. ATM vol stays the same as the stock moves.', tags: ['sticky-delta'] },
    { id: 'd10-f05', front: 'Breeden-Litzenberger formula', back: '$f(K) = e^{rT} \\frac{\\partial^2 C}{\\partial K^2}$. Risk-neutral density equals $e^{rT}$ times the second derivative of call price w.r.t. strike.', tags: ['risk-neutral', 'density'] },
    { id: 'd10-f06', front: 'Risk reversal (25d)', back: '$\\sigma_{25\\Delta C} - \\sigma_{25\\Delta P}$. Measures the skew. Negative for equities (puts more expensive).', tags: ['skew', 'risk-reversal'] },
    { id: 'd10-f07', front: 'Vol butterfly (25d)', back: '$\\frac{\\sigma_{25\\Delta P} + \\sigma_{25\\Delta C}}{2} - \\sigma_{ATM}$. Measures smile curvature.', tags: ['smile', 'butterfly'] },
    { id: 'd10-f08', front: 'What does an inverted vol term structure signal?', back: 'Current crisis: short-term vol is elevated and expected to mean-revert. Like an inverted yield curve.', tags: ['term-structure'] },
    { id: 'd10-f09', front: 'Forward implied vol formula', back: '$\\sigma_f^2 = \\frac{\\sigma_2^2 T_2 - \\sigma_1^2 T_1}{T_2 - T_1}$. Extracted from the term structure.', tags: ['forward-vol'] },
    { id: 'd10-f10', front: 'Do call and put at the same strike have the same IV?', back: 'Yes, always. Put-call parity guarantees this: $C - P = S - Ke^{-rT}$ is vol-independent.', tags: ['implied-vol', 'parity'] },
    { id: 'd10-f11', front: 'Why does equity skew exist?', back: '(1) Fat left tails / crash risk. (2) Leverage effect. (3) Supply/demand (hedging demand for puts). (4) Jump risk.', tags: ['skew'] },
    { id: 'd10-f12', front: 'No-arbitrage constraint: calendar spread', back: 'Total variance must increase with maturity: $\\sigma^2(T_2)T_2 \\geq \\sigma^2(T_1)T_1$. Forward variance must be non-negative.', tags: ['vol-surface', 'arbitrage'] },
  ],
  interactiveTools: ['vol-surface', 'bs-calculator', 'greek-visualizer'],
  cheatSheet: [
    { topic: 'Risk Reversal', formula: 'σ(25Δ call) - σ(25Δ put)', description: 'Measures skew; negative for equities' },
    { topic: 'Vol Butterfly', formula: '(σ(25ΔP) + σ(25ΔC))/2 - σ(ATM)', description: 'Measures smile curvature' },
    { topic: 'Forward Vol', formula: 'σ_f² = (σ₂²T₂ - σ₁²T₁)/(T₂-T₁)', description: 'Implied vol between two dates' },
    { topic: 'Breeden-Litzenberger', formula: 'f(K) = e^{rT} ∂²C/∂K²', description: 'Risk-neutral density from option prices' },
    { topic: 'Sticky Strike Delta', formula: 'Δ = Δ_BS', description: 'No vol adjustment needed' },
    { topic: 'Sticky Delta Adjustment', formula: 'Δ = Δ_BS + ν·∂σ/∂S', description: 'Add skew-driven vol sensitivity' },
  ],
  summary: [
    'The vol smile/skew contradicts BS constant vol: OTM puts have higher IV in equities',
    'Skew reflects fat tails, leverage effects, crash risk, and hedging demand',
    'Sticky strike: vol anchored to strikes. Sticky delta: vol anchored to moneyness',
    'Breeden-Litzenberger: risk-neutral density = $e^{rT} \\partial^2 C / \\partial K^2$',
    'Forward vol extracted from term structure; inverted term structure signals crisis',
  ],
};

export default day10;
