import { DayContent } from './types';

const day10: DayContent = {
  dayNumber: 10,
  title: 'Implied Vol Surfaces, Smile & Skew',
  subtitle: 'Natenberg Chapter 23',
  week: 2,
  chapters: ['Chapter 23'],
  estimatedMinutes: 130,
  prerequisites: [1, 2, 3, 4, 5, 6, 7, 8, 9],
  objectives: [
    'Understand why the volatility smile and skew exist and what they imply about the market',
    'Interpret volatility surfaces across strike and maturity dimensions',
    'Distinguish between sticky strike and sticky delta regimes',
    'Extract risk-neutral density from option prices via the Breeden-Litzenberger result',
    'Relate skew to crash risk, leverage effects, and supply/demand dynamics',
  ],
  theory: {
    sections: [
      {
        title: 'The Volatility Smile and Skew',
        blocks: [
          {
            type: 'text',
            body: 'Black-Scholes assumes constant volatility across all strikes and maturities. In reality, if you invert the BS formula for every traded option price, you get different implied volatilities for different strikes. Plotting IV against strike for a given expiry produces the **volatility smile** (or skew). This is one of the most important empirical facts in options markets.',
          },
          {
            type: 'concept',
            title: 'Smile vs. Skew',
            body: 'A **smile** is a U-shaped pattern where OTM puts and OTM calls both have higher IV than ATM options. Common in FX markets. A **skew** (or smirk) is when OTM puts have significantly higher IV than OTM calls. Common in equity index options since the 1987 crash. The skew reflects the market pricing a higher probability of large downward moves than the lognormal distribution implies.',
          },
          {
            type: 'formula',
            latex: '\\sigma_{\\text{imp}}(K) = \\sigma_{\\text{ATM}} + \\text{skew} \\times \\frac{K - F}{F} + \\text{smile} \\times \\left(\\frac{K - F}{F}\\right)^2',
            label: 'Quadratic Parameterization of Smile',
            explanation: 'A simple parameterization of the implied vol surface. The linear term captures skew (negative for equity indices). The quadratic term captures smile (positive curvature).',
          },
          {
            type: 'callout',
            variant: 'key-insight',
            body: 'The volatility skew is NOT an inefficiency. It reflects rational market pricing of fat tails, jump risk, and the asymmetric risk profile of equity markets. Trying to arbitrage the skew by selling OTM puts is a classic way to blow up.',
          },
        ],
      },
      {
        title: 'The Volatility Term Structure',
        blocks: [
          {
            type: 'text',
            body: 'The **term structure** of volatility shows how ATM implied vol varies across expiration dates. Typically, short-term vol is more volatile and mean-reverts faster than long-term vol. In calm markets, the term structure slopes upward (short-term vol < long-term vol). In crisis, it inverts (short-term vol spikes above long-term).',
          },
          {
            type: 'concept',
            title: 'The Full Volatility Surface',
            body: 'The vol surface is a 3D object: $\\sigma_{\\text{imp}}(K, T)$, mapping every strike-maturity pair to an implied vol. It encodes ALL the market\'s information about option pricing. Market makers must maintain a consistent, arbitrage-free vol surface at all times.',
          },
          {
            type: 'table',
            headers: ['Market Regime', 'Short-term IV', 'Long-term IV', 'Term Structure Shape'],
            rows: [
              ['Calm / Low vol', 'Low', 'Higher', 'Upward sloping (contango)'],
              ['Crisis / High vol', 'Very high', 'Lower', 'Inverted (backwardation)'],
              ['Mean-reverting', 'At long-term mean', 'At long-term mean', 'Flat'],
            ],
          },
          {
            type: 'callout',
            variant: 'tip',
            body: 'Think of the vol term structure like a yield curve. Normal: upward sloping. Inverted: crisis signal. The shape tells you about the market\'s expectation of future volatility.',
          },
        ],
      },
      {
        title: 'Sticky Strike vs. Sticky Delta',
        blocks: [
          {
            type: 'text',
            body: 'When the underlying moves, how does the vol surface shift? Two common models:',
          },
          {
            type: 'concept',
            title: 'Sticky Strike',
            body: 'Under **sticky strike**, the implied vol for each strike stays constant as the underlying moves. If the 100-strike option has 25% vol, it keeps 25% vol regardless of where the stock goes. This means as the stock rises, the ATM vol (now at a higher strike) changes. Sticky strike implies the vol surface is anchored to absolute strike levels.',
          },
          {
            type: 'concept',
            title: 'Sticky Delta',
            body: 'Under **sticky delta** (or sticky moneyness), the implied vol for a given moneyness level (e.g., 25-delta put) stays constant. As the stock rises from 100 to 105, the ATM vol stays the same (it moves to the 105 strike). This means strike-level vols change. Sticky delta implies the vol surface moves with the underlying.',
          },
          {
            type: 'callout',
            variant: 'key-insight',
            body: 'Neither regime is always correct. Empirically, equity markets often behave between the two. Understanding which regime is dominant matters for hedging: sticky strike implies a different delta adjustment than sticky delta. Market makers who get this wrong will be systematically over- or under-hedged.',
          },
          {
            type: 'formula',
            latex: '\\Delta_{\\text{sticky-strike}} = \\Delta_{\\text{BS}} \\quad ; \\quad \\Delta_{\\text{sticky-delta}} = \\Delta_{\\text{BS}} + \\nu \\cdot \\frac{\\partial \\sigma}{\\partial S}',
            label: 'Delta Adjustment for Sticky Regimes',
            explanation: 'Under sticky strike, the BS delta is correct. Under sticky delta, you need to add a vol-sensitivity adjustment: the product of vega and the slope of IV with respect to the underlying.',
          },
        ],
      },
      {
        title: 'Risk-Neutral Density and the Breeden-Litzenberger Result',
        blocks: [
          {
            type: 'text',
            body: 'The prices of options across all strikes encode the market\'s **risk-neutral probability distribution** for the underlying at expiry. The Breeden-Litzenberger (1978) result shows how to extract this distribution from option prices.',
          },
          {
            type: 'formula',
            latex: 'f(K) = e^{rT} \\frac{\\partial^2 C}{\\partial K^2}',
            label: 'Breeden-Litzenberger Formula',
            explanation: 'The risk-neutral probability density at $K$ equals $e^{rT}$ times the second derivative of the call price with respect to strike. In practice, this is estimated using butterfly spreads.',
          },
          {
            type: 'concept',
            title: 'Butterfly Spread as a Density Probe',
            body: 'A butterfly spread centered at $K$ (long $C(K-\\delta)$, short $2C(K)$, long $C(K+\\delta)$) approximates the second derivative of $C$ with respect to $K$. Its price, divided by $\\delta^2$ and multiplied by $e^{rT}$, gives the risk-neutral density at $K$. A more expensive butterfly means higher probability density at that strike.',
          },
          {
            type: 'callout',
            variant: 'key-insight',
            body: 'The vol smile/skew is just another way of encoding the risk-neutral density. A negatively skewed vol surface corresponds to a left-skewed (fat left tail) risk-neutral density. This is why equity index vol surfaces are negatively skewed: the market prices a higher probability of crashes.',
          },
        ],
      },
    ],
  },
  exercises: [
    {
      id: 'd10-smile-01',
      exerciseType: 'multiple-choice',
      difficulty: 'easy',
      topic: 'vol-smile',
      tags: ['vol-smile', 'skew'],
      timeEstimateSeconds: 30,
      question: 'After the 1987 crash, equity index option markets typically exhibit:',
      options: [
        'A symmetric volatility smile',
        'A negative volatility skew (OTM puts have higher IV)',
        'A positive volatility skew (OTM calls have higher IV)',
        'Flat implied volatility across all strikes',
      ],
      correctIndex: 1,
      explanation: 'Post-1987, equity index options display a pronounced negative skew (also called the "smirk"). OTM puts have higher IV than ATM options, reflecting crash risk and demand for downside protection.',
      solutionSteps: [
        'Before 1987: vol surface was roughly flat (BS assumptions seemed OK).',
        'After the crash: market permanently repriced tail risk.',
        'OTM puts became expensive (higher IV) due to crash protection demand.',
        'This creates a negative skew: IV decreases as strike increases.',
      ],
    },
    {
      id: 'd10-smile-02',
      exerciseType: 'true-false',
      difficulty: 'easy',
      topic: 'vol-smile',
      tags: ['vol-smile', 'black-scholes'],
      timeEstimateSeconds: 15,
      statement: 'The existence of the volatility smile is consistent with the Black-Scholes assumption of constant volatility.',
      correct: false,
      explanation: 'Black-Scholes assumes a single, constant volatility for all strikes and maturities. The smile directly contradicts this: different strikes imply different volatilities. The smile is evidence that the BS model is an incomplete description of reality.',
      solutionSteps: [
        'BS assumes $\\sigma$ is constant across strikes and time.',
        'The smile means $\\sigma_{imp}$ varies with $K$.',
        'This directly contradicts the BS assumption.',
      ],
    },
    {
      id: 'd10-smile-03',
      exerciseType: 'multiple-choice',
      difficulty: 'medium',
      topic: 'vol-smile',
      tags: ['vol-smile', 'fx'],
      timeEstimateSeconds: 30,
      question: 'In FX options markets, the volatility pattern across strikes is typically:',
      options: [
        'A negative skew (like equity indices)',
        'A symmetric smile (U-shaped)',
        'Flat',
        'A positive skew (OTM calls more expensive)',
      ],
      correctIndex: 1,
      explanation: 'FX markets typically show a symmetric smile because currency pairs have symmetric risk in either direction (one currency strengthening is the other weakening). Neither tail is inherently more feared.',
      solutionSteps: [
        'In FX, there is no inherent directional bias (unlike equities which tend to crash down).',
        'Both tails carry risk: either currency could move sharply.',
        'This produces a U-shaped (symmetric) smile.',
      ],
    },
    {
      id: 'd10-term-01',
      exerciseType: 'multiple-choice',
      difficulty: 'medium',
      topic: 'term-structure',
      tags: ['term-structure', 'vol-surface'],
      timeEstimateSeconds: 45,
      question: 'The VIX is at 35 while 1-year ATM implied vol is at 22. What does this term structure shape indicate?',
      options: [
        'The market is calm and expects vol to stay low',
        'The market is in crisis; short-term vol is elevated and expected to mean-revert',
        'The market expects a major event in one year',
        'Implied vol is mispriced and there is an arbitrage',
      ],
      correctIndex: 1,
      explanation: 'An inverted term structure (short-term vol >> long-term vol) indicates a current crisis or stress. The market expects volatility to mean-revert from the elevated short-term level back to the long-term average.',
      solutionSteps: [
        'VIX (30-day IV) = 35, much higher than 1-year IV = 22.',
        'This is an inverted term structure.',
        'Inversion signals current stress with expected mean-reversion.',
        'The market believes the crisis is temporary.',
      ],
    },
    {
      id: 'd10-sticky-01',
      exerciseType: 'free-response',
      difficulty: 'medium',
      topic: 'sticky-strike-delta',
      tags: ['sticky-strike', 'sticky-delta'],
      timeEstimateSeconds: 120,
      question: 'A stock is at $100 and the 100-strike call has 25% IV. The 105-strike call has 23% IV. The stock rises to $105. Under sticky strike, what is the new ATM vol? Under sticky delta?',
      modelAnswer: 'Under **sticky strike**: Each strike keeps its IV. The 100-strike still has 25% IV and the 105-strike still has 23% IV. The new ATM (now at 105) has IV = 23%. So ATM vol dropped from 25% to 23%. Under **sticky delta**: The ATM vol stays at 25% regardless of where the stock moves. The 25% vol "moves" to the 105 strike. The 100-strike (now 5 points OTM put side) gets a different vol, likely higher due to the skew. So under sticky delta, ATM vol is unchanged at 25%.',
      explanation: 'Sticky strike: vol is tied to the strike level. Sticky delta: vol is tied to the moneyness.',
      solutionSteps: [
        'Sticky strike: 100-strike keeps 25%, 105-strike keeps 23%.',
        'New ATM (at $105) has IV = 23%.',
        'Sticky delta: ATM vol stays at 25% (moneyness-based).',
        'The 105-strike (now ATM) gets 25% vol.',
        'Key difference: sticky strike sees ATM vol drop; sticky delta sees it unchanged.',
      ],
    },
    {
      id: 'd10-bl-01',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'risk-neutral-density',
      tags: ['breeden-litzenberger', 'butterfly'],
      timeEstimateSeconds: 120,
      question: 'Three call prices: $C(95) = 8.50$, $C(100) = 5.20$, $C(105) = 2.80$. $r = 3\\%$, $T = 0.25$. Estimate the risk-neutral probability density at $K = 100$ using the Breeden-Litzenberger formula with $\\delta = 5$.',
      correctAnswer: 0.037,
      tolerance: 0.003,
      unit: 'per $',
      explanation: '$\\frac{\\partial^2 C}{\\partial K^2} \\approx \\frac{C(K-\\delta) - 2C(K) + C(K+\\delta)}{\\delta^2} = \\frac{8.50 - 10.40 + 2.80}{25} = \\frac{0.90}{25} = 0.036$. Density = $e^{rT} \\times 0.036 = e^{0.0075} \\times 0.036 = 1.00753 \\times 0.036 = 0.0363$.',
      solutionSteps: [
        'Estimate second derivative: $\\frac{C(95) - 2C(100) + C(105)}{5^2}$',
        '$= \\frac{8.50 - 10.40 + 2.80}{25} = \\frac{0.90}{25} = 0.036$',
        'Apply Breeden-Litzenberger: $f(100) = e^{rT} \\times 0.036$',
        '$= e^{0.0075} \\times 0.036 = 1.00753 \\times 0.036 = 0.0363$',
        'Interpretation: ~3.6% probability density per dollar at $K = 100$.',
      ],
    },
    {
      id: 'd10-bl-02',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'risk-neutral-density',
      tags: ['breeden-litzenberger', 'butterfly'],
      timeEstimateSeconds: 120,
      question: 'Using the same prices: $C(95) = 8.50$, $C(100) = 5.20$, $C(105) = 2.80$. What is the price of the 95/100/105 butterfly spread? What does it represent?',
      correctAnswer: 0.90,
      tolerance: 0.01,
      unit: '$',
      explanation: 'Butterfly = $C(95) - 2C(100) + C(105) = 8.50 - 10.40 + 2.80 = 0.90$. This is proportional to the risk-neutral probability that the stock finishes near $100 (specifically between $95 and $105).',
      solutionSteps: [
        'Butterfly price = $C(K - \\delta) - 2C(K) + C(K + \\delta)$',
        '$= 8.50 - 2(5.20) + 2.80 = 8.50 - 10.40 + 2.80 = 0.90$',
        'This is the cost of betting on the stock finishing near $100.',
        'It approximates $e^{-rT} \\times f(100) \\times \\delta^2 = e^{-rT} \\times \\text{density} \\times 25$.',
      ],
    },
    {
      id: 'd10-skew-01',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'vol-skew',
      tags: ['skew', 'vol-surface'],
      timeEstimateSeconds: 60,
      question: 'The 25-delta put has IV = 28%, ATM IV = 22%, 25-delta call IV = 19%. What is the risk reversal (25d)?',
      correctAnswer: -9,
      tolerance: 0.5,
      unit: 'vol points',
      explanation: 'Risk reversal = IV(25d call) - IV(25d put) = 19% - 28% = -9 vol points. A negative risk reversal indicates a negatively skewed surface (typical for equities).',
      solutionSteps: [
        'Risk reversal = $\\sigma_{25\\Delta C} - \\sigma_{25\\Delta P}$',
        '$= 19\\% - 28\\% = -9\\%$ (or $-9$ vol points)',
        'Negative = puts are more expensive than calls = negative skew.',
      ],
    },
    {
      id: 'd10-skew-02',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'vol-skew',
      tags: ['skew', 'vol-surface'],
      timeEstimateSeconds: 60,
      question: 'Using the same data (25d put IV = 28%, ATM IV = 22%, 25d call IV = 19%), what is the butterfly (25d)?',
      correctAnswer: 1.5,
      tolerance: 0.5,
      unit: 'vol points',
      explanation: 'Butterfly = $\\frac{\\sigma_{25\\Delta P} + \\sigma_{25\\Delta C}}{2} - \\sigma_{ATM} = \\frac{28 + 19}{2} - 22 = 23.5 - 22 = 1.5$ vol points. Positive = smile curvature (wings are expensive relative to ATM).',
      solutionSteps: [
        'Butterfly = $\\frac{\\sigma_{25\\Delta P} + \\sigma_{25\\Delta C}}{2} - \\sigma_{ATM}$',
        '$= \\frac{28 + 19}{2} - 22 = 23.5 - 22 = 1.5$ vol points',
        'This measures the curvature (convexity) of the smile.',
      ],
    },
    {
      id: 'd10-sticky-02',
      exerciseType: 'multiple-choice',
      difficulty: 'hard',
      topic: 'sticky-strike-delta',
      tags: ['sticky-strike', 'sticky-delta', 'hedging'],
      timeEstimateSeconds: 60,
      question: 'Under sticky delta, when the stock drops, what happens to the IV of a fixed-strike OTM call?',
      options: [
        'It stays the same because the strike is fixed',
        'It increases because the call becomes more OTM (further from ATM on the smile)',
        'It decreases because the overall vol surface drops',
        'It decreases because the call becomes closer to ATM',
      ],
      correctIndex: 1,
      explanation: 'Under sticky delta, the vol surface moves with the underlying. When the stock drops, a fixed-strike call becomes more OTM (higher delta-distance from ATM). Under the smile, more OTM options have higher IV. So the IV of this call increases.',
      solutionSteps: [
        'Sticky delta: the smile is anchored to moneyness (delta), not absolute strikes.',
        'Stock drops: the fixed-strike call moves further OTM.',
        'On the smile, further OTM options have higher IV.',
        'Therefore, the IV of this fixed-strike call increases.',
      ],
    },
    {
      id: 'd10-surface-01',
      exerciseType: 'free-response',
      difficulty: 'hard',
      topic: 'vol-surface',
      tags: ['vol-surface', 'arbitrage'],
      timeEstimateSeconds: 150,
      question: 'What are the no-arbitrage constraints on a volatility surface? Name at least three.',
      modelAnswer: '(1) **Calendar spread constraint**: Forward variance must be non-negative. $\\sigma^2(T_2) \\cdot T_2 \\geq \\sigma^2(T_1) \\cdot T_1$ for $T_2 > T_1$. Otherwise you could sell the short-dated and buy the long-dated for a guaranteed profit. (2) **Butterfly constraint**: The risk-neutral density must be non-negative everywhere. This means $\\frac{\\partial^2 C}{\\partial K^2} \\geq 0$ (call prices are convex in strike). A negative butterfly price would be an arbitrage. (3) **Monotonicity in strike**: Call prices must be decreasing in strike ($\\frac{\\partial C}{\\partial K} \\leq 0$) and put prices must be increasing in strike. (4) **Bounds**: $0 \\leq C(K,T) \\leq S$ and $0 \\leq P(K,T) \\leq Ke^{-rT}$.',
      explanation: 'A vol surface must satisfy these constraints to be arbitrage-free. Market makers check these constantly.',
      solutionSteps: [
        'Calendar: forward variance $\\geq 0$ (total variance increases with maturity).',
        'Butterfly: $C(K-\\delta) - 2C(K) + C(K+\\delta) \\geq 0$ (convexity in strike).',
        'Monotonicity: $C(K_1) \\geq C(K_2)$ for $K_1 < K_2$ (calls decrease in strike).',
        'Bounds: call $\\leq S$, put $\\leq Ke^{-rT}$.',
      ],
    },
    {
      id: 'd10-interview-01',
      exerciseType: 'free-response',
      difficulty: 'interview',
      topic: 'vol-smile',
      tags: ['vol-smile', 'interview'],
      timeEstimateSeconds: 120,
      question: 'Why does the volatility skew exist in equity markets? Give at least three explanations.',
      modelAnswer: '(1) **Crash risk / fat tails**: Real-world stock returns have fatter left tails than lognormal. Large drops are more common than BS predicts. OTM puts must be priced higher to reflect this. (2) **Leverage effect**: As a stock falls, its leverage (debt/equity) increases, making it riskier and increasing its volatility. This creates a negative correlation between returns and vol. (3) **Supply/demand**: Institutional investors systematically buy OTM puts for portfolio insurance and sell OTM calls (covered calls). This demand pressure pushes up OTM put prices and pushes down OTM call prices, creating skew. (4) **Jump risk**: Markets can gap down suddenly (crashes), but rarely gap up by the same magnitude. Jump models naturally produce negative skew.',
      explanation: 'The skew reflects a combination of statistical reality (fat tails), economic mechanisms (leverage), and market structure (supply/demand).',
      solutionSteps: [
        'Fat tails: real returns have more extreme left-tail events than lognormal.',
        'Leverage effect: falling stock price increases leverage and vol.',
        'Supply/demand: institutional hedging inflates OTM put prices.',
        'Jump risk: downward jumps more severe than upward ones.',
      ],
    },
    {
      id: 'd10-interview-02',
      exerciseType: 'numeric',
      difficulty: 'interview',
      topic: 'vol-surface',
      tags: ['vol-surface', 'mental-math', 'interview'],
      timeEstimateSeconds: 45,
      question: 'ATM 1-month IV = 20%, ATM 3-month IV = 24%. What is the forward vol from month 1 to month 3? (Use $\\sigma_f^2 \\cdot \\Delta T = \\sigma_2^2 T_2 - \\sigma_1^2 T_1$.)',
      correctAnswer: 26.2,
      tolerance: 0.5,
      unit: '%',
      explanation: '$\\sigma_f^2 = \\frac{\\sigma_2^2 T_2 - \\sigma_1^2 T_1}{T_2 - T_1} = \\frac{0.24^2 \\times 3/12 - 0.20^2 \\times 1/12}{2/12} = \\frac{0.0144 - 0.00333}{0.1667} = \\frac{0.01107}{0.1667} = 0.0664$. $\\sigma_f = \\sqrt{0.0664} = 0.2577 = 25.8\\%$.',
      solutionSteps: [
        'Total variance at 1 month: $0.20^2 \\times 1/12 = 0.04/12 = 0.003333$',
        'Total variance at 3 months: $0.24^2 \\times 3/12 = 0.0576/4 = 0.01440$',
        'Forward variance: $\\frac{0.01440 - 0.003333}{2/12} = \\frac{0.01107}{0.1667} = 0.0664$',
        'Forward vol = $\\sqrt{0.0664} = 25.8\\%$',
      ],
    },
    {
      id: 'd10-smile-04',
      exerciseType: 'true-false',
      difficulty: 'medium',
      topic: 'vol-smile',
      tags: ['vol-smile', 'risk-neutral'],
      timeEstimateSeconds: 30,
      statement: 'A negative volatility skew implies the risk-neutral distribution has a fatter left tail than the lognormal distribution.',
      correct: true,
      explanation: 'A negative skew means OTM puts (low strikes) have higher IV. Higher IV at low strikes means the BS model needs more vol to match market prices there, implying the market assigns more probability to large downward moves than lognormal would. This is a fatter left tail.',
      solutionSteps: [
        'Negative skew: IV increases as strike decreases.',
        'Higher IV at low strikes = higher option prices at low strikes.',
        'Higher option prices = more probability mass in the left tail.',
        'Therefore: fatter left tail than lognormal.',
      ],
    },
  ],
  cumulativeExercises: [
    {
      id: 'd10-cum-01',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'parity-with-skew',
      tags: ['put-call-parity', 'skew', 'implied-vol'],
      timeEstimateSeconds: 90,
      fromDay: 1,
      question: 'A 100-strike call has IV = 22% and the 100-strike put has IV = 22%. A 90-strike put has IV = 28%. Does the 90-strike call also have IV = 28%?',
      correctAnswer: 28,
      tolerance: 0.1,
      unit: '%',
      explanation: 'Yes. Put-call parity guarantees that the call and put AT THE SAME STRIKE have the same implied vol. This is because parity is model-independent: $C - P = S - Ke^{-rT}$. Since the right side does not depend on vol, C and P must be consistent with the same vol. So the 90-strike call also has IV = 28%.',
      solutionSteps: [
        'Put-call parity: $C(K) - P(K) = S - Ke^{-rT}$. Model-independent.',
        'The right side is fixed (no vol dependence).',
        'If $P(90)$ implies 28% vol, then $C(90)$ must also imply 28% vol.',
        'Otherwise parity is violated = arbitrage.',
      ],
    },
    {
      id: 'd10-cum-02',
      exerciseType: 'free-response',
      difficulty: 'hard',
      topic: 'greeks-with-skew',
      tags: ['delta', 'vega', 'skew'],
      timeEstimateSeconds: 150,
      fromDay: 5,
      question: 'How does the volatility skew affect the delta of an OTM put compared to the BS delta computed with ATM vol? Is the skew-adjusted delta higher or lower in magnitude?',
      modelAnswer: 'The skew-adjusted delta of an OTM put is HIGHER in magnitude (more negative) than the BS delta computed with ATM vol. Reason: under the skew, OTM puts have higher IV than ATM. Using the correct (higher) IV to compute delta gives a larger $|\\Delta|$ because: (1) higher vol makes the put less far out of the money in standardized terms ($d_1$ is closer to zero), and (2) under sticky delta, when the stock drops, IV rises (skew effect), amplifying the put\'s sensitivity. In practice, skew-aware deltas are 10-30% larger in magnitude than flat-vol deltas for OTM puts.',
      explanation: 'The skew increases the effective delta of OTM puts, which is critical for portfolio hedging.',
      solutionSteps: [
        'OTM put IV > ATM IV (negative skew).',
        'Higher IV for the put means $d_1$ is closer to zero (less OTM in vol-normalized terms).',
        'This increases $|\\Delta_{put}|$.',
        'Additionally, $\\Delta_{adj} = \\Delta_{BS} + \\nu \\cdot \\frac{\\partial \\sigma}{\\partial S}$.',
        'Since $\\frac{\\partial \\sigma}{\\partial S} < 0$ (negative skew) and $\\nu > 0$, the adjustment is negative.',
        'For a put (already negative delta), this makes it more negative.',
      ],
    },
    {
      id: 'd10-cum-03',
      exerciseType: 'numeric',
      difficulty: 'hard',
      topic: 'bs-with-smile',
      tags: ['black-scholes', 'implied-vol', 'pricing'],
      timeEstimateSeconds: 120,
      fromDay: 3,
      question: 'Using BS with $S = 100$, $K = 90$, $r = 3\\%$, $T = 0.25$, and a skew-implied vol of 28% (vs ATM vol of 22%): compute the 90-strike put price. Then compute what it would be using ATM vol. What is the difference?',
      correctAnswer: 1.42,
      tolerance: 0.3,
      unit: '$',
      hint: 'Use BS formula with each vol to get two put prices. The difference is the "skew premium."',
      explanation: 'With $\\sigma = 28\\%$: $d_1 = \\frac{\\ln(100/90) + (0.03 + 0.0392)\\times 0.25}{0.28 \\times 0.5} = \\frac{0.10536 + 0.01730}{0.14} = 0.877$. $d_2 = 0.877 - 0.14 = 0.737$. $P = 90e^{-0.0075}N(-0.737) - 100 N(-0.877) = 89.33 \\times 0.2306 - 100 \\times 0.1903 = 20.60 - 19.03 = 1.57$. With $\\sigma = 22\\%$: similar calc gives $P \\approx 0.15$. Difference $\\approx 1.42$.',
      solutionSteps: [
        'BS with $\\sigma = 28\\%$: compute $d_1, d_2$ and put price.',
        'BS with $\\sigma = 22\\%$: compute $d_1, d_2$ and put price.',
        'The OTM put is significantly more expensive with skew vol.',
        'Difference $\\approx \\$1.42$ -- this is the skew premium.',
      ],
    },
    {
      id: 'd10-cum-04',
      exerciseType: 'multiple-choice',
      difficulty: 'medium',
      topic: 'vega-surface',
      tags: ['vega', 'vol-surface'],
      timeEstimateSeconds: 45,
      fromDay: 5,
      question: 'A trader is long a 90-strike put (IV = 28%) and short a 100-strike put (IV = 22%). If the entire vol surface shifts up by 1%, what is the approximate P&L? Assume vega(90P) = 0.12 and vega(100P) = 0.18 per 1% vol.',
      options: [
        '+$0.06 (net vega positive)',
        '-$0.06 (net vega negative)',
        '+$0.30 (both options gain)',
        '-$0.30 (both options lose)',
      ],
      correctIndex: 1,
      explanation: 'Net vega = long put vega - short put vega = $0.12 - 0.18 = -0.06$. A 1% vol increase costs $0.06. The position is net short vega because the short ATM put has more vega than the long OTM put.',
      solutionSteps: [
        'Long 90P vega = +0.12. Short 100P vega = -0.18.',
        'Net vega = $0.12 - 0.18 = -0.06$.',
        'Vol up 1%: P&L = $-0.06 \\times 1 = -\\$0.06$.',
      ],
    },
    {
      id: 'd10-cum-05',
      exerciseType: 'scenario',
      difficulty: 'hard',
      topic: 'sticky-strike-pnl',
      tags: ['sticky-strike', 'sticky-delta', 'pnl'],
      timeEstimateSeconds: 180,
      fromDay: 5,
      question: 'You are long a 95-strike put with IV = 26%. ATM vol (at $S = 100$) is 22%. The stock drops from 100 to 95. Analyze P&L under different sticky regimes.',
      scenarios: [
        {
          description: 'Sticky strike: IV of 95-strike stays at 26%. What is the change in moneyness?',
          shocks: [{ variable: 'stock_price', change: -5 }],
          expectedAnswer: 0,
          tolerance: 0,
          unit: 'vol change (%)',
        },
        {
          description: 'Sticky delta: ATM vol stays at 22%. 95-strike is now ATM. What is its new IV?',
          shocks: [{ variable: 'stock_price', change: -5 }],
          expectedAnswer: 22,
          tolerance: 0.5,
          unit: '%',
        },
      ],
      explanation: 'Under sticky strike, the 95-strike keeps 26% IV even though it is now ATM. Under sticky delta, the 95-strike (now ATM) gets ATM vol of 22%. The sticky delta regime hurts the long put position (vol drops from 26% to 22% as the stock moves towards the strike).',
      solutionSteps: [
        'Sticky strike: IV at each strike is fixed. 95-strike stays at 26%. No vol change.',
        'Sticky delta: ATM vol is always 22%. Stock moves to 95, so 95 is now ATM. IV drops to 22%.',
        'For the long put: sticky strike is better (vol stays high); sticky delta is worse (vol drops).',
        'The 4 vol point drop under sticky delta costs approximately $\\text{vega} \\times 4\\% \\approx \\$0.50$ per contract.',
      ],
    },
    {
      id: 'd10-cum-06',
      exerciseType: 'numeric',
      difficulty: 'medium',
      topic: 'forward-vol',
      tags: ['term-structure', 'forward-variance'],
      timeEstimateSeconds: 90,
      fromDay: 7,
      question: '1-month ATM IV = 18%, 2-month ATM IV = 20%. What is the 1-month forward implied vol from month 1 to month 2?',
      correctAnswer: 21.8,
      tolerance: 0.3,
      unit: '%',
      explanation: '$\\sigma_f^2 = \\frac{\\sigma_2^2 T_2 - \\sigma_1^2 T_1}{T_2 - T_1} = \\frac{0.04 \\times 2/12 - 0.0324 \\times 1/12}{1/12} = \\frac{0.006667 - 0.002700}{0.08333} = \\frac{0.003967}{0.08333} = 0.04760$. $\\sigma_f = 21.8\\%$.',
      solutionSteps: [
        'Total variance at 1 month: $0.18^2 \\times 1/12 = 0.002700$',
        'Total variance at 2 months: $0.20^2 \\times 2/12 = 0.006667$',
        'Forward variance: $(0.006667 - 0.002700) / (1/12) = 0.04760$',
        'Forward vol = $\\sqrt{0.04760} = 21.8\\%$.',
      ],
    },
  ],
  flashcards: [
    { id: 'd10-f01', front: 'What is the volatility smile?', back: 'A U-shaped pattern of IV vs. strike: OTM puts and calls have higher IV than ATM. Common in FX.', tags: ['vol-smile'] },
    { id: 'd10-f02', front: 'What is the volatility skew?', back: 'A pattern where IV increases as strike decreases (OTM puts have higher IV). Common in equity indices post-1987.', tags: ['skew'] },
    { id: 'd10-f03', front: 'Sticky strike regime', back: 'IV at each absolute strike is fixed when the underlying moves. If stock rises, ATM vol changes.', tags: ['sticky-strike'] },
    { id: 'd10-f04', front: 'Sticky delta regime', back: 'IV at each moneyness level (e.g., 25d put) is fixed. ATM vol stays the same as the stock moves.', tags: ['sticky-delta'] },
    { id: 'd10-f05', front: 'Breeden-Litzenberger formula', back: '$f(K) = e^{rT} \\frac{\\partial^2 C}{\\partial K^2}$. Risk-neutral density equals $e^{rT}$ times the second derivative of call price w.r.t. strike.', tags: ['risk-neutral', 'density'] },
    { id: 'd10-f06', front: 'Risk reversal (25d)', back: '$\\sigma_{25\\Delta C} - \\sigma_{25\\Delta P}$. Measures the skew. Negative for equities (puts more expensive).', tags: ['skew', 'risk-reversal'] },
    { id: 'd10-f07', front: 'Vol butterfly (25d)', back: '$\\frac{\\sigma_{25\\Delta P} + \\sigma_{25\\Delta C}}{2} - \\sigma_{ATM}$. Measures smile curvature.', tags: ['smile', 'butterfly'] },
    { id: 'd10-f08', front: 'What does an inverted vol term structure signal?', back: 'Current crisis: short-term vol is elevated and expected to mean-revert. Like an inverted yield curve.', tags: ['term-structure'] },
    { id: 'd10-f09', front: 'Forward implied vol formula', back: '$\\sigma_f^2 = \\frac{\\sigma_2^2 T_2 - \\sigma_1^2 T_1}{T_2 - T_1}$. Extracted from the term structure.', tags: ['forward-vol'] },
    { id: 'd10-f10', front: 'Do call and put at the same strike have the same IV?', back: 'Yes, always. Put-call parity guarantees this: $C - P = S - Ke^{-rT}$ is vol-independent.', tags: ['implied-vol', 'parity'] },
    { id: 'd10-f11', front: 'Why does equity skew exist?', back: '(1) Fat left tails / crash risk. (2) Leverage effect. (3) Supply/demand (hedging demand for puts). (4) Jump risk.', tags: ['skew'] },
    { id: 'd10-f12', front: 'No-arbitrage constraint: calendar spread', back: 'Total variance must increase with maturity: $\\sigma^2(T_2)T_2 \\geq \\sigma^2(T_1)T_1$. Forward variance must be non-negative.', tags: ['vol-surface', 'arbitrage'] },
  ],
  interactiveTools: ['vol-surface', 'bs-calculator', 'greek-visualizer'],
  cheatSheet: [
    { topic: 'Risk Reversal', formula: 'σ(25Δ call) - σ(25Δ put)', description: 'Measures skew; negative for equities' },
    { topic: 'Vol Butterfly', formula: '(σ(25ΔP) + σ(25ΔC))/2 - σ(ATM)', description: 'Measures smile curvature' },
    { topic: 'Forward Vol', formula: 'σ_f² = (σ₂²T₂ - σ₁²T₁)/(T₂-T₁)', description: 'Implied vol between two dates' },
    { topic: 'Breeden-Litzenberger', formula: 'f(K) = e^{rT} ∂²C/∂K²', description: 'Risk-neutral density from option prices' },
    { topic: 'Sticky Strike Delta', formula: 'Δ = Δ_BS', description: 'No vol adjustment needed' },
    { topic: 'Sticky Delta Adjustment', formula: 'Δ = Δ_BS + ν·∂σ/∂S', description: 'Add skew-driven vol sensitivity' },
  ],
  summary: [
    'The vol smile/skew contradicts BS constant vol: OTM puts have higher IV in equities',
    'Skew reflects fat tails, leverage effects, crash risk, and hedging demand',
    'Sticky strike: vol anchored to strikes. Sticky delta: vol anchored to moneyness',
    'Breeden-Litzenberger: risk-neutral density = $e^{rT} \\partial^2 C / \\partial K^2$',
    'Forward vol extracted from term structure; inverted term structure signals crisis',
  ],
  trackB: {
    title: 'Leduc Poker & Abstraction Techniques',
    subtitle: 'Scaling game-theoretic strategies through card abstraction and CFR',
    objectives: [
      'Understand Leduc Poker rules and why it serves as a tractable test bed for game theory',
      'Apply card abstraction and bucketing to reduce game tree complexity',
      'Implement the Counterfactual Regret Minimization (CFR) algorithm',
      'Analyze regret matching and strategy profile convergence to Nash equilibrium',
      'Measure exploitability of computed strategies',
      'Connect abstraction quality metrics to market making as an imperfect information game',
    ],
    theory: {
      sections: [
        {
          title: 'Leduc Poker: A Tractable Test Bed',
          blocks: [
            {
              type: 'text',
              body: 'Leduc Poker is a simplified poker variant introduced by Southey et al. (2005) that is small enough to solve exactly yet rich enough to exhibit the key strategic phenomena of imperfect information games. It uses a deck of only **3 ranks** (e.g., J, Q, K) with **2 suits each** (6 cards total). Each player is dealt one private card, and there are two betting rounds with a single community card revealed between them.',
            },
            {
              type: 'concept',
              title: 'Leduc Poker Rules',
              body: 'Deal: each player receives one card from a 6-card deck (3 ranks x 2 suits). Round 1: betting with a fixed bet size. Then a single community card is revealed. Round 2: betting with a larger fixed bet size. Showdown: a pair (private card matches community card) beats a high card; otherwise highest card wins. The game tree has roughly 936 information sets, making it solvable but non-trivial.',
            },
            {
              type: 'table',
              headers: ['Feature', 'Leduc Poker', 'Texas Hold\'em'],
              rows: [
                ['Deck size', '6 cards (3 ranks x 2 suits)', '52 cards (13 ranks x 4 suits)'],
                ['Private cards', '1 per player', '2 per player'],
                ['Community cards', '1', '5 (flop/turn/river)'],
                ['Betting rounds', '2', '4'],
                ['Information sets', '~936', '~10^14'],
                ['Solvable exactly?', 'Yes', 'No (requires abstraction)'],
              ],
            },
            {
              type: 'callout',
              variant: 'key-insight',
              body: 'Leduc Poker is to game theory what the Black-Scholes model is to options pricing: a simplified setting that captures the essential structure. Just as BS teaches put-call parity and delta hedging despite unrealistic assumptions, Leduc teaches bluffing, information hiding, and opponent exploitation in a tractable framework.',
            },
          ],
        },
        {
          title: 'Card Abstraction & Bucketing',
          blocks: [
            {
              type: 'text',
              body: 'Real poker (and real markets) have game trees far too large to solve exactly. **Abstraction** reduces the game to a manageable size by grouping similar states together. In poker, **card abstraction** groups hands with similar strategic properties into **buckets**. The key insight: two hands that have the same probability of winning against a random opponent hand should be played the same way.',
            },
            {
              type: 'concept',
              title: 'Bucketing Strategies',
              body: 'Common bucketing approaches: (1) **Hand strength buckets**: group by equity (probability of winning at showdown). (2) **Potential-aware buckets**: also consider how hand strength may change with future cards. (3) **Isomorphism reduction**: exploit symmetries (e.g., in Leduc, Jh and Jd are strategically identical). (4) **Earth Mover\\\'s Distance (EMD)**: cluster hands by distributional similarity of outcomes.',
            },
            {
              type: 'formula',
              latex: '\\\\text{Equity}(h) = \\\\frac{1}{|\\\\mathcal{H}_{opp}|} \\\\sum_{h\' \\\\in \\\\mathcal{H}_{opp}} \\\\mathbf{1}[h \\\\succ h\']',
              label: 'Hand Equity (Showdown Probability)',
              explanation: 'The fraction of opponent hands that hand $h$ beats at showdown. Hands with similar equity can be grouped into the same bucket without losing much strategic information.',
            },
            {
              type: 'callout',
              variant: 'tip',
              body: 'In Leduc Poker, suit isomorphism is perfect: Jh is strategically identical to Jd (the community card has the same pairing probability regardless of suit). This reduces the effective number of information sets. In real Hold\\\'em, suit isomorphism reduces the number of distinct preflop hands from 1326 to 169.',
            },
          ],
        },
        {
          title: 'CFR Algorithm',
          blocks: [
            {
              type: 'text',
              body: 'Counterfactual Regret Minimization (CFR), introduced by Zinkevich et al. (2007), is the workhorse algorithm for solving imperfect information games. It works by traversing the game tree, computing **counterfactual regret** for each action at each information set, and updating the strategy using **regret matching**. Over many iterations, the average strategy converges to a Nash equilibrium.',
            },
            {
              type: 'formula',
              latex: '\\\\sigma^{T+1}(a) = \\\\frac{R^T_+(a)}{\\\\sum_{a\'} R^T_+(a\')}',
              label: 'Regret Matching',
              explanation: 'At iteration $T+1$, the probability of playing action $a$ is proportional to its positive cumulative regret $R^T_+(a) = \\\\max(R^T(a), 0)$. If all regrets are non-positive, play uniformly. This ensures no-external-regret in the limit.',
            },
            {
              type: 'formula',
              latex: 'v_i(\\\\sigma, I) = \\\\sum_{h \\\\in I} \\\\pi_{-i}^{\\\\sigma}(h) \\\\sum_{z \\\\in Z_h} \\\\pi^{\\\\sigma}(h, z) \\\\, u_i(z)',
              label: 'Counterfactual Value',
              explanation: 'The counterfactual value for player $i$ at information set $I$ under strategy profile $\\\\sigma$. Here $\\\\pi_{-i}^{\\\\sigma}(h)$ is the probability of reaching history $h$ due to all players\\\' actions EXCEPT player $i$, and $u_i(z)$ is the utility at terminal node $z$.',
            },
            {
              type: 'concept',
              title: 'CFR Algorithm Steps',
              body: '(1) Initialize all cumulative regrets to zero. (2) For each iteration: traverse the game tree, compute counterfactual values for each action at each information set, update cumulative regrets: $R^{T+1}(a) = R^T(a) + v_i(\\\\sigma|_{I \\\\to a}) - v_i(\\\\sigma)$, then update the strategy via regret matching. (3) Track the cumulative strategy (sum of strategies weighted by reach probabilities). (4) The average strategy converges to Nash equilibrium.',
            },
            {
              type: 'callout',
              variant: 'warning',
              body: 'The CURRENT strategy at any iteration is NOT the Nash equilibrium -- it oscillates. Only the TIME-AVERAGED strategy converges. This is analogous to how SGD iterates bounce around the optimum, but the average converges.',
            },
          ],
        },
        {
          title: 'Convergence & Exploitability',
          blocks: [
            {
              type: 'text',
              body: 'CFR\\\'s convergence guarantee is one of its most powerful properties. The average strategy profile converges to a Nash equilibrium at a rate of $O(1/\\\\sqrt{T})$ in terms of exploitability. This means that no opponent can gain more than $\\\\varepsilon$ by deviating, where $\\\\varepsilon$ shrinks as we run more iterations.',
            },
            {
              type: 'formula',
              latex: '\\\\bar{\\\\sigma}^T \\\\to \\\\text{Nash equilibrium as } T \\\\to \\\\infty',
              label: 'Average Strategy Convergence',
              explanation: 'The time-averaged strategy $\\\\bar{\\\\sigma}^T = \\\\frac{1}{T} \\\\sum_{t=1}^T \\\\sigma^t$ converges to a Nash equilibrium. The convergence rate is $O(\\\\sqrt{|I| \\\\cdot |A|} / \\\\sqrt{T})$ where $|I|$ is the number of information sets and $|A|$ is the maximum number of actions.',
            },
            {
              type: 'formula',
              latex: '\\\\varepsilon(\\\\sigma) = \\\\sum_i \\\\left[ \\\\max_{\\\\sigma\'_i} u_i(\\\\sigma\'_i, \\\\sigma_{-i}) - u_i(\\\\sigma) \\\\right]',
              label: 'Exploitability',
              explanation: 'The exploitability of a strategy profile $\\\\sigma$ is the sum over all players of how much each player could gain by unilaterally deviating to their best response. At Nash equilibrium, exploitability is zero.',
            },
            {
              type: 'example',
              title: 'CFR Convergence in Leduc Poker',
              problem: 'After 10,000 iterations of CFR on Leduc Poker (~936 information sets), the exploitability is 0.05 big blinds. After 1,000,000 iterations, it drops to 0.0005 big blinds. What is the convergence rate?',
              solution: [
                'Iterations increased by 100x (from 10k to 1M).',
                'Exploitability decreased by 100x (from 0.05 to 0.0005).',
                'This is consistent with $O(1/\\\\sqrt{T})$: $\\\\sqrt{100} = 10$, but we see 100x decrease.',
                'Actually closer to $O(1/T)$ convergence, which CFR+ achieves.',
                'In practice, CFR variants like CFR+ and DCFR converge faster than vanilla CFR.',
              ],
            },
            {
              type: 'callout',
              variant: 'key-insight',
              body: 'Exploitability is the game-theoretic analogue of "out-of-sample error" in machine learning. A strategy with low exploitability is robust to adversarial opponents, just as a model with low test error generalizes well. In market making, low exploitability means your quoting strategy cannot be systematically picked off.',
            },
          ],
        },
        {
          title: 'Abstraction in Market Making',
          blocks: [
            {
              type: 'text',
              body: 'Market making IS an imperfect information game. The market maker does not know whether an incoming order is from an informed trader (who has a signal about true value) or a noise trader. The bid-ask spread is the market maker\\\'s strategy, analogous to a betting strategy in poker. Tighter spreads attract more flow but increase adverse selection risk.',
            },
            {
              type: 'concept',
              title: 'Market Making as a Game Tree',
              body: 'Nature moves first: determines whether the trader is informed or uninformed (hidden from the market maker). The trader decides whether to buy, sell, or not trade. The market maker sets bid and ask prices. The payoff depends on the true value, which is revealed later. This maps directly to an extensive-form imperfect information game.',
            },
            {
              type: 'concept',
              title: 'Abstraction in Market Making',
              body: 'Just as poker players bucket hands by equity, market makers can abstract the state space: (1) **Order flow buckets**: group order arrival patterns by informativeness. (2) **Inventory buckets**: discretize continuous inventory into levels. (3) **Volatility regime buckets**: group market conditions by vol level. (4) **Time-of-day buckets**: opening, midday, closing have different dynamics.',
            },
            {
              type: 'callout',
              variant: 'key-insight',
              body: 'The CFR framework suggests that a market maker should NOT try to exploit individual traders (that\\\'s the current strategy, which oscillates). Instead, the AVERAGE strategy over time -- a consistent, balanced spread -- is what converges to the unexploitable equilibrium. This aligns with the practical wisdom that consistent quoting outperforms aggressive pattern-matching.',
            },
          ],
        },
      ],
    },
    exercises: [
      {
        id: 'd10b-leduc-01',
        exerciseType: 'multiple-choice',
        difficulty: 'easy',
        topic: 'Leduc Poker',
        tags: ['leduc', 'game-theory'],
        timeEstimateSeconds: 45,
        question: 'In Leduc Poker, how many cards are in the deck?',
        options: [
          '3 (one per rank)',
          '6 (3 ranks x 2 suits)',
          '13 (standard ranks)',
          '52 (standard deck)',
        ],
        correctIndex: 1,
        explanation: 'Leduc Poker uses a small deck of 6 cards: 3 ranks (e.g., J, Q, K) with 2 suits each. This keeps the game tree small enough to solve exactly (~936 information sets).',
        solutionSteps: [
          'Leduc Poker deck: 3 ranks (J, Q, K) x 2 suits = 6 cards.',
          'This is deliberately small for tractability.',
          'Compare to Hold\\\'em: 52 cards, ~10^14 information sets.',
        ],
      },
      {
        id: 'd10b-leduc-02',
        exerciseType: 'true-false',
        difficulty: 'easy',
        topic: 'Leduc Poker',
        tags: ['leduc', 'information-sets'],
        timeEstimateSeconds: 30,
        statement: 'In Leduc Poker, a player holding Jh and a player holding Jd are in different information sets before the community card is revealed.',
        correct: false,
        explanation: 'Due to suit isomorphism, Jh and Jd are strategically identical before the community card is revealed. They have the same probability of pairing with the community card and the same equity against all opponent hands. They belong to the same equivalence class.',
        solutionSteps: [
          'Suit isomorphism: Jh and Jd have identical strategic properties.',
          'Both have the same pairing probability with the community card.',
          'An optimal strategy assigns the same action probabilities to both.',
          'This isomorphism reduces the effective game size.',
        ],
      },
      {
        id: 'd10b-leduc-03',
        exerciseType: 'multiple-choice',
        difficulty: 'easy',
        topic: 'Leduc Poker',
        tags: ['leduc', 'hand-ranking'],
        timeEstimateSeconds: 30,
        question: 'In Leduc Poker, which hand wins at showdown?',
        options: [
          'The highest card always wins',
          'A pair (matching community card) beats any non-pair; otherwise highest card wins',
          'The lowest card wins (like lowball)',
          'Hands are ranked by suit',
        ],
        correctIndex: 1,
        explanation: 'In Leduc Poker, pairing your private card with the community card is the strongest hand. Among non-paired hands, the highest rank wins. Suits do not affect hand ranking.',
        solutionSteps: [
          'Pair (private matches community) beats non-pair.',
          'Among non-pairs, highest rank wins (K > Q > J).',
          'Suits are irrelevant for hand ranking.',
        ],
      },
      {
        id: 'd10b-abstraction-01',
        exerciseType: 'multiple-choice',
        difficulty: 'easy',
        topic: 'Card Abstraction',
        tags: ['abstraction', 'bucketing'],
        timeEstimateSeconds: 45,
        question: 'What is the primary purpose of card abstraction in game-theoretic poker solving?',
        options: [
          'To make the game more fun to play',
          'To reduce the game tree size by grouping strategically similar hands into buckets',
          'To remove bluffing from the game',
          'To increase the number of information sets for finer-grained strategies',
        ],
        correctIndex: 1,
        explanation: 'Card abstraction groups hands with similar strategic properties (equity, potential) into buckets. This dramatically reduces the number of information sets, making the game solvable. The tradeoff is that the resulting strategy is an approximation of the true Nash equilibrium.',
        solutionSteps: [
          'Real games (Hold\\\'em) have ~10^14 information sets -- too many to solve.',
          'Abstraction groups similar states: e.g., all hands with 60-65% equity become one bucket.',
          'Reduces information sets to a manageable number.',
          'Tradeoff: solution is approximate, not exact.',
        ],
      },
      {
        id: 'd10b-abstraction-02',
        exerciseType: 'numeric',
        difficulty: 'easy',
        topic: 'Card Abstraction',
        tags: ['abstraction', 'isomorphism'],
        timeEstimateSeconds: 60,
        question: 'In Texas Hold\\\'em, there are C(52,2) = 1326 distinct two-card starting hands. Using suit isomorphism (treating all suit permutations as equivalent), how many strategically distinct starting hands are there?',
        correctAnswer: 169,
        tolerance: 0,
        explanation: 'With suit isomorphism, we distinguish only: (1) pocket pairs: 13 types (AA, KK, ..., 22), (2) suited non-pairs: C(13,2) = 78 types, (3) offsuit non-pairs: C(13,2) = 78 types. Total = 13 + 78 + 78 = 169. This reduces 1326 hands by a factor of ~7.8.',
        solutionSteps: [
          'Pocket pairs: 13 distinct types (AA through 22).',
          'Each pair has $\\\\binom{4}{2} = 6$ suit combos, all equivalent.',
          'Suited non-pairs: $\\\\binom{13}{2} = 78$ types, each with 4 suit combos.',
          'Offsuit non-pairs: $\\\\binom{13}{2} = 78$ types, each with $4 \\\\times 3 = 12$ suit combos.',
          'Total distinct: $13 + 78 + 78 = 169$. Reduction: $1326 / 169 \\\\approx 7.8\\\\times$.',
        ],
      },
      {
        id: 'd10b-cfr-01',
        exerciseType: 'multiple-choice',
        difficulty: 'medium',
        topic: 'CFR Algorithm',
        tags: ['cfr', 'regret-matching'],
        timeEstimateSeconds: 60,
        question: 'In regret matching, if the cumulative regrets for actions {Fold, Call, Raise} are {-5, 3, 7}, what are the action probabilities at the next iteration?',
        options: [
          'Fold = 0, Call = 0.3, Raise = 0.7',
          'Fold = 0.5, Call = 0.3, Raise = 0.2',
          'Fold = 0, Call = 0.5, Raise = 0.5',
          'Fold = 1/3, Call = 1/3, Raise = 1/3',
        ],
        correctIndex: 0,
        explanation: 'Regret matching: $\\\\sigma(a) = R_+(a) / \\\\sum R_+(a\\\')$. Positive regrets: Fold = max(-5, 0) = 0, Call = max(3, 0) = 3, Raise = max(7, 0) = 7. Sum = 10. Probabilities: Fold = 0/10 = 0, Call = 3/10 = 0.3, Raise = 7/10 = 0.7.',
        solutionSteps: [
          'Clip negative regrets: $R_+(\\\\text{Fold}) = 0$, $R_+(\\\\text{Call}) = 3$, $R_+(\\\\text{Raise}) = 7$.',
          'Sum of positive regrets: $0 + 3 + 7 = 10$.',
          '$\\\\sigma(\\\\text{Fold}) = 0/10 = 0$.',
          '$\\\\sigma(\\\\text{Call}) = 3/10 = 0.3$.',
          '$\\\\sigma(\\\\text{Raise}) = 7/10 = 0.7$.',
        ],
      },
      {
        id: 'd10b-cfr-02',
        exerciseType: 'numeric',
        difficulty: 'medium',
        topic: 'CFR Algorithm',
        tags: ['cfr', 'regret-matching'],
        timeEstimateSeconds: 90,
        question: 'After 5 iterations of CFR at a particular information set, the cumulative regrets for actions {Check, Bet} are {2, 8}. What probability does regret matching assign to Bet?',
        correctAnswer: 0.80,
        tolerance: 0.01,
        explanation: '$\\\\sigma(\\\\text{Bet}) = R_+(\\\\text{Bet}) / (R_+(\\\\text{Check}) + R_+(\\\\text{Bet})) = 8 / (2 + 8) = 8/10 = 0.80$.',
        solutionSteps: [
          'Both regrets are positive: $R_+(\\\\text{Check}) = 2$, $R_+(\\\\text{Bet}) = 8$.',
          'Sum = $2 + 8 = 10$.',
          '$\\\\sigma(\\\\text{Bet}) = 8 / 10 = 0.80$.',
          '$\\\\sigma(\\\\text{Check}) = 2 / 10 = 0.20$.',
        ],
      },
      {
        id: 'd10b-cfr-03',
        exerciseType: 'true-false',
        difficulty: 'medium',
        topic: 'CFR Algorithm',
        tags: ['cfr', 'convergence'],
        timeEstimateSeconds: 30,
        statement: 'In CFR, the strategy at the final iteration is the Nash equilibrium strategy.',
        correct: false,
        explanation: 'The strategy at any single iteration is NOT the Nash equilibrium. CFR\\\'s convergence guarantee applies to the TIME-AVERAGED strategy (the average of all strategies across all iterations). The per-iteration strategy oscillates and does not converge to a fixed point.',
        solutionSteps: [
          'CFR convergence: the AVERAGE strategy $\\\\bar{\\\\sigma}^T$ converges.',
          'The current strategy $\\\\sigma^T$ oscillates and does not converge.',
          'To get the Nash equilibrium approximation, you must compute the running average.',
          'This is analogous to SGD: iterates bounce, but the average converges.',
        ],
      },
      {
        id: 'd10b-exploit-01',
        exerciseType: 'numeric',
        difficulty: 'medium',
        topic: 'Exploitability',
        tags: ['exploitability', 'nash'],
        timeEstimateSeconds: 90,
        question: 'In a two-player zero-sum game, player 1\\\'s best response against player 2\\\'s strategy achieves value +0.10, and player 2\\\'s best response against player 1\\\'s strategy achieves value +0.08. The game value at Nash equilibrium is 0. What is the total exploitability of this strategy profile?',
        correctAnswer: 0.18,
        tolerance: 0.01,
        explanation: 'In a zero-sum game, exploitability is the sum of each player\\\'s best-response value: $\\\\varepsilon = BR_1 + BR_2 = 0.10 + 0.08 = 0.18$. This represents how much both players collectively could gain by deviating from the current strategy to their best responses.',
        solutionSteps: [
          'Player 1\\\'s best response value: $BR_1 = 0.10$.',
          'Player 2\\\'s best response value: $BR_2 = 0.08$.',
          'Total exploitability: $\\\\varepsilon = 0.10 + 0.08 = 0.18$.',
          'At Nash equilibrium, $\\\\varepsilon = 0$ (neither player can improve by deviating).',
        ],
      },
      {
        id: 'd10b-cfr-04',
        exerciseType: 'free-response',
        difficulty: 'medium',
        topic: 'CFR Algorithm',
        tags: ['cfr', 'counterfactual-value'],
        timeEstimateSeconds: 120,
        question: 'Explain what "counterfactual" means in Counterfactual Regret Minimization. Why use counterfactual values instead of expected values?',
        modelAnswer: 'In CFR, "counterfactual" refers to computing the value of an information set ASSUMING the player tried to reach it. Formally, the counterfactual value uses the opponents\\\' reach probability $\\\\pi_{-i}(h)$ but NOT player $i$\\\'s reach probability. This means we ask: "If I were at this information set (regardless of how unlikely my own strategy makes it), what would be the value of each action?" This is crucial because: (1) it allows regret to be computed locally at each information set, (2) it avoids the problem that a player\\\'s own strategy might make an information set unreachable (zero reach probability), causing zero regret updates, (3) it decomposes the global optimization problem into independent local problems at each information set. This decomposition is what makes CFR computationally tractable.',
        explanation: 'The counterfactual formulation is the key insight that makes CFR work. It allows independent optimization at each information set.',
        solutionSteps: [
          'Counterfactual value: weight by opponents\\\' reach probability, NOT player\\\'s own.',
          'Standard value: $v(I) = \\\\pi_i(I) \\\\cdot \\\\pi_{-i}(I) \\\\cdot$ payoff. Counterfactual: $v_{cf}(I) = \\\\pi_{-i}(I) \\\\cdot$ payoff.',
          'Why: if $\\\\pi_i(I) \\\\approx 0$ (player rarely reaches $I$), standard regret updates vanish.',
          'Counterfactual values allow learning at EVERY information set, even rarely visited ones.',
          'Enables decomposition: optimize each information set independently.',
        ],
      },
      {
        id: 'd10b-convergence-01',
        exerciseType: 'numeric',
        difficulty: 'hard',
        topic: 'Convergence',
        tags: ['cfr', 'convergence-rate'],
        timeEstimateSeconds: 120,
        question: 'CFR\\\'s exploitability bound is $O(\\\\Delta \\\\sqrt{|I| \\\\cdot |A|} / \\\\sqrt{T})$ where $\\\\Delta$ is the game\\\'s value range, $|I| = 936$ information sets, $|A| = 3$ max actions, and $\\\\Delta = 2$ (in pot units). After $T = 10000$ iterations, estimate the exploitability bound (ignoring constant factors, assume the constant is 1).',
        correctAnswer: 1.06,
        tolerance: 0.1,
        explanation: '$\\\\varepsilon \\\\leq \\\\frac{\\\\Delta \\\\sqrt{|I| \\\\cdot |A|}}{\\\\sqrt{T}} = \\\\frac{2\\\\sqrt{936 \\\\times 3}}{\\\\sqrt{10000}} = \\\\frac{2\\\\sqrt{2808}}{100} = \\\\frac{2 \\\\times 53.0}{100} = \\\\frac{106.0}{100} = 1.06$.',
        solutionSteps: [
          'Compute $\\\\sqrt{|I| \\\\cdot |A|} = \\\\sqrt{936 \\\\times 3} = \\\\sqrt{2808} \\\\approx 53.0$.',
          'Multiply by $\\\\Delta = 2$: $2 \\\\times 53.0 = 106.0$.',
          'Divide by $\\\\sqrt{T} = \\\\sqrt{10000} = 100$.',
          '$\\\\varepsilon \\\\leq 106.0 / 100 = 1.06$ pot units.',
          'Note: this is a theoretical upper bound; actual exploitability is much lower in practice.',
        ],
      },
      {
        id: 'd10b-mm-01',
        exerciseType: 'free-response',
        difficulty: 'hard',
        topic: 'Market Making as Game',
        tags: ['market-making', 'game-theory', 'abstraction'],
        timeEstimateSeconds: 180,
        question: 'Describe how a market making problem can be modeled as an imperfect information game similar to poker. Identify the players, their private information, the action spaces, and explain what the "Nash equilibrium spread" would represent.',
        modelAnswer: 'Players: (1) Market maker: sets bid/ask prices. (2) Trader: decides whether to buy at ask, sell at bid, or not trade. (3) Nature: determines the true asset value and whether the trader is informed or uninformed. Private information: The trader knows whether they are informed (and if so, the direction of the true value). The market maker only observes the order flow. Action spaces: Market maker chooses spread width and mid-price. Trader chooses to buy, sell, or abstain. Payoffs: Market maker profits from the spread but loses to informed traders (adverse selection). The Nash equilibrium spread is the tightest spread at which the market maker\\\'s expected profit from uninformed flow exactly offsets losses to informed flow. At this equilibrium: (1) the market maker cannot improve by widening (loses flow) or tightening (adverse selection dominates), (2) informed traders cannot improve their strategy (they already trade when their information exceeds the spread). This is essentially the Glosten-Milgrom zero-profit condition expressed as a game-theoretic equilibrium.',
        explanation: 'The connection between poker and market making is deep: both involve hidden information, sequential actions, and the need to balance exploitation against protection.',
        solutionSteps: [
          'Players: market maker, trader, nature.',
          'Hidden info: trader type (informed/uninformed), true value.',
          'Market maker\\\'s info set: past order flow, current market state.',
          'Nash spread: zero expected profit condition from Glosten-Milgrom.',
          'Wider spread: fewer trades, less adverse selection. Narrower: more trades, more adverse selection.',
          'Equilibrium balances these forces.',
        ],
      },
      {
        id: 'd10b-mm-02',
        exerciseType: 'multiple-choice',
        difficulty: 'hard',
        topic: 'Abstraction Quality',
        tags: ['abstraction', 'quality-metrics'],
        timeEstimateSeconds: 90,
        question: 'When evaluating the quality of a game abstraction, which metric most directly measures whether the abstracted solution is close to the true Nash equilibrium?',
        options: [
          'The number of buckets used in the abstraction',
          'The exploitability of the abstracted strategy when played in the ORIGINAL (unabstracted) game',
          'The convergence rate of CFR in the abstracted game',
          'The size reduction factor compared to the original game',
        ],
        correctIndex: 1,
        explanation: 'The true test of abstraction quality is not how well the strategy performs in the abstracted game, but how exploitable it is when "lifted" back to the original game. A strategy might be a perfect Nash equilibrium in the abstract game but highly exploitable in the real game if the abstraction grouped strategically different situations together.',
        solutionSteps: [
          'Abstraction quality = how well the abstract solution transfers to the real game.',
          'Metric: exploitability in the ORIGINAL game (not the abstract one).',
          'More buckets generally means better quality, but not always.',
          'Convergence rate measures algorithm efficiency, not solution quality.',
          'Size reduction measures compression, not approximation quality.',
        ],
      },
      {
        id: 'd10b-regret-01',
        exerciseType: 'numeric',
        difficulty: 'hard',
        topic: 'Regret Matching',
        tags: ['regret-matching', 'cfr'],
        timeEstimateSeconds: 120,
        question: 'At a particular information set, after 100 iterations the cumulative regrets are: Check = 15, Bet Small = -3, Bet Large = 8. What is the regret-matched probability of checking?',
        correctAnswer: 0.652,
        tolerance: 0.01,
        explanation: 'Regret matching: $R_+(\\\\text{Check}) = 15$, $R_+(\\\\text{Bet Small}) = 0$ (clipped), $R_+(\\\\text{Bet Large}) = 8$. Sum = 23. $\\\\sigma(\\\\text{Check}) = 15/23 = 0.652$.',
        solutionSteps: [
          'Clip negatives: $R_+(\\\\text{Check}) = 15$, $R_+(\\\\text{BS}) = 0$, $R_+(\\\\text{BL}) = 8$.',
          'Sum = $15 + 0 + 8 = 23$.',
          '$\\\\sigma(\\\\text{Check}) = 15/23 \\\\approx 0.652$.',
          '$\\\\sigma(\\\\text{Bet Small}) = 0/23 = 0$.',
          '$\\\\sigma(\\\\text{Bet Large}) = 8/23 \\\\approx 0.348$.',
        ],
      },
      {
        id: 'd10b-interview-01',
        exerciseType: 'free-response',
        difficulty: 'interview',
        topic: 'CFR in Trading',
        tags: ['cfr', 'market-making', 'interview'],
        timeEstimateSeconds: 240,
        question: 'An Optiver interviewer asks: "How would you use game-theoretic concepts to optimize a market maker\\\'s quoting strategy in a competitive market with multiple market makers and informed traders?"',
        modelAnswer: 'I would frame this as a multi-player imperfect information game. The market maker\\\'s strategy is the spread and quote sizes conditioned on observable state (inventory, recent order flow, volatility). Key steps: (1) **State abstraction**: bucket the continuous state space into discrete states: inventory levels (e.g., 5 buckets from max short to max long), volatility regimes (low/medium/high), order flow imbalance (buy-heavy/balanced/sell-heavy). (2) **Action abstraction**: discretize the spread into a few choices (tight/medium/wide) and quote sizes (small/standard/large). (3) **Opponent modeling**: model informed traders as having a noisy signal about true value, and other market makers as playing their own strategies. (4) **Solution concept**: use CFR or a variant to find the Nash equilibrium strategy for our discrete game. The equilibrium spread balances: (a) adverse selection cost from informed traders, (b) competitive pressure from other market makers, (c) inventory risk. (5) **Online adaptation**: use the offline Nash strategy as a baseline, but adapt online using regret tracking -- if we observe that a particular state leads to consistent losses, increase the spread for that bucket. The key insight from game theory: we should NOT try to maximally exploit current opponent behavior (this is the oscillating per-iteration strategy). Instead, we should play a robust, unexploitable baseline strategy (the time-averaged Nash strategy) and make small, conservative deviations when we have strong evidence of exploitable opponent patterns.',
        explanation: 'This question tests the ability to connect abstract game theory to practical market making.',
        solutionSteps: [
          'Frame as imperfect info game: hidden trader types, observable order flow.',
          'Abstract continuous states into discrete buckets (inventory, vol, flow).',
          'Discretize action space (spread width, quote size).',
          'Solve for Nash equilibrium using CFR.',
          'Deploy as baseline strategy with online adaptation.',
          'Key: robust baseline > aggressive exploitation.',
        ],
      },
      {
        id: 'd10b-interview-02',
        exerciseType: 'scenario',
        difficulty: 'interview',
        topic: 'Abstraction Tradeoffs',
        tags: ['abstraction', 'interview', 'game-theory'],
        timeEstimateSeconds: 180,
        question: 'You are designing a game-theoretic model for market making. Evaluate different abstraction granularities.',
        scenarios: [
          {
            description: 'Coarse abstraction: 3 inventory buckets (short/flat/long), 2 vol regimes, 2 flow states. Total states = 3 x 2 x 2 = 12. How many state-action pairs if there are 3 possible spreads?',
            shocks: [{ variable: 'buckets', change: 12 }],
            expectedAnswer: 36,
            tolerance: 0,
            unit: 'state-action pairs',
          },
          {
            description: 'Fine abstraction: 10 inventory buckets, 5 vol regimes, 5 flow states. Total states = 10 x 5 x 5 = 250. How many state-action pairs with 5 possible spreads?',
            shocks: [{ variable: 'buckets', change: 250 }],
            expectedAnswer: 1250,
            tolerance: 0,
            unit: 'state-action pairs',
          },
          {
            description: 'If CFR convergence requires ~1000 iterations per state-action pair, how many total iterations for the fine abstraction?',
            shocks: [{ variable: 'iterations', change: 1000 }],
            expectedAnswer: 1250000,
            tolerance: 50000,
            unit: 'iterations',
          },
        ],
        explanation: 'The tradeoff: finer abstraction gives a more accurate model but requires exponentially more computation. The coarse model (12 states) can be solved nearly instantly but may miss important distinctions. The fine model (250 states) captures more nuance but requires 35x more computation.',
        solutionSteps: [
          'Coarse: $3 \\\\times 2 \\\\times 2 = 12$ states $\\\\times 3$ actions $= 36$ pairs.',
          'Fine: $10 \\\\times 5 \\\\times 5 = 250$ states $\\\\times 5$ actions $= 1250$ pairs.',
          'Total iterations for fine: $1250 \\\\times 1000 = 1,250,000$.',
          'Tradeoff: finer = more accurate but more computation.',
          'Practical approach: start coarse, refine selectively.',
        ],
      },
      {
        id: 'd10b-interview-03',
        exerciseType: 'free-response',
        difficulty: 'interview',
        topic: 'CFR Variants',
        tags: ['cfr', 'interview', 'algorithms'],
        timeEstimateSeconds: 180,
        question: 'Describe two improvements to vanilla CFR that make it converge faster. Why does CFR+ converge faster than vanilla CFR?',
        modelAnswer: 'Two key improvements: (1) **CFR+** (Tammelin 2014): Instead of allowing regrets to become arbitrarily negative, CFR+ resets negative regrets to zero at each iteration. Formally, $R^{T+1}(a) = \\\\max(R^T(a) + r^T(a), 0)$ where $r^T(a)$ is the instantaneous regret. This achieves $O(1/T)$ convergence vs $O(1/\\\\sqrt{T})$ for vanilla CFR -- a dramatic improvement. The intuition: negative regrets represent actions that have been "tried and found wanting." Resetting them to zero means the algorithm "forgets" about bad actions faster and focuses on the competitive ones. (2) **Discounted CFR (DCFR)** (Brown & Sandholm 2019): Applies discounting to earlier iterations. Recent regrets and strategies are weighted more heavily than old ones. This adapts to non-stationary environments and converges faster in practice.',
        explanation: 'CFR+ and DCFR are the practical workhorses of modern game solving.',
        solutionSteps: [
          'CFR+: reset negative regrets to zero each iteration.',
          'Effect: $O(1/T)$ convergence vs $O(1/\\\\sqrt{T})$ for vanilla.',
          'Intuition: faster forgetting of bad actions.',
          'DCFR: discount old iterations, weight recent ones more.',
          'Effect: better adaptation to non-stationary games.',
          'Both: practical improvements used in state-of-the-art poker AI.',
        ],
      },
      {
        id: 'd10b-speed-01',
        exerciseType: 'speed-drill',
        difficulty: 'easy',
        topic: 'Quick Recall',
        tags: ['cfr', 'regret-matching', 'speed'],
        timeEstimateSeconds: 90,
        timeLimitSeconds: 90,
        problems: [
          { prompt: 'Regret matching: regrets {4, 6}. Probability of action 1?', correctAnswer: 0.4, tolerance: 0.01 },
          { prompt: 'Regret matching: regrets {-2, 5, 3}. Probability of action 2 (5)?', correctAnswer: 0.625, tolerance: 0.01 },
          { prompt: 'Regret matching: regrets {-1, -3, -5}. Probability of action 1?', correctAnswer: 0.333, tolerance: 0.01 },
          { prompt: 'Leduc Poker: how many cards in the deck?', correctAnswer: 6, tolerance: 0 },
          { prompt: 'Hold\'em starting hands after suit isomorphism: how many distinct?', correctAnswer: 169, tolerance: 0 },
        ],
        explanation: 'Quick recall of key CFR and abstraction facts. When all regrets are negative, play uniformly (1/3 each for 3 actions).',
        solutionSteps: [
          '{4, 6}: sum = 10, P(a1) = 4/10 = 0.4.',
          '{-2, 5, 3}: clip to {0, 5, 3}, sum = 8, P(a2) = 5/8 = 0.625.',
          'All negative: play uniform, P(a1) = 1/3 = 0.333.',
          'Leduc: 3 ranks x 2 suits = 6.',
          'Hold\\\'em isomorphism: 13 pairs + 78 suited + 78 offsuit = 169.',
        ],
      },
    ],
    flashcards: [
      { id: 'd10b-f01', front: 'What is Leduc Poker?', back: 'A simplified poker variant with 6 cards (3 ranks x 2 suits), 1 private card, 1 community card, 2 betting rounds. ~936 information sets. Small enough to solve exactly.', tags: ['leduc'] },
      { id: 'd10b-f02', front: 'What is card abstraction?', back: 'Grouping strategically similar hands into buckets to reduce game tree size. Methods: equity bucketing, potential-aware clustering, suit isomorphism, EMD-based clustering.', tags: ['abstraction'] },
      { id: 'd10b-f03', front: 'State the regret matching formula.', back: '$\\\\sigma^{T+1}(a) = R^T_+(a) / \\\\sum_{a^{\\\\prime}}R^T_+(a^{\\\\prime})$ where $R^T_+(a) = \\\\max(R^T(a), 0)$. If all regrets $\\\\leq 0$, play uniformly.', tags: ['cfr', 'regret-matching'] },
      { id: 'd10b-f04', front: 'What is counterfactual value in CFR?', back: '$v_i(\\\\sigma, I) = \\\\sum_{h \\\\in I} \\\\pi_{-i}^{\\\\sigma}(h) \\\\sum_{z \\\\in Z_h} \\\\pi^{\\\\sigma}(h,z) u_i(z)$. Uses opponents\\\' reach probability but not player\\\'s own.', tags: ['cfr'] },
      { id: 'd10b-f05', front: 'Does the current CFR iteration give the Nash equilibrium?', back: 'No. Only the TIME-AVERAGED strategy converges to Nash. The per-iteration strategy oscillates.', tags: ['cfr', 'convergence'] },
      { id: 'd10b-f06', front: 'What is exploitability?', back: '$\\\\varepsilon(\\\\sigma) = \\\\sum_i [\\\\max_{\\\\sigma^{\\\\prime}_i} u_i(\\\\sigma^{\\\\prime}_i, \\\\sigma_{-i}) - u_i(\\\\sigma)]$. The total gain available to all players by deviating to best responses. Zero at Nash equilibrium.', tags: ['exploitability'] },
      { id: 'd10b-f07', front: 'CFR convergence rate?', back: 'Vanilla CFR: $O(1/\\\\sqrt{T})$. CFR+: $O(1/T)$. Measured by exploitability of average strategy.', tags: ['cfr', 'convergence'] },
      { id: 'd10b-f08', front: 'How does suit isomorphism reduce Hold\\\'em hands?', back: 'From 1326 distinct starting hands to 169 strategically distinct classes (13 pairs + 78 suited + 78 offsuit).', tags: ['abstraction', 'isomorphism'] },
      { id: 'd10b-f09', front: 'How is market making like poker?', back: 'Both are imperfect information games. Market maker doesn\\\'t know if trader is informed (like not knowing opponent\\\'s cards). Spread is the "bet." Adverse selection is the cost of being wrong.', tags: ['market-making', 'game-theory'] },
      { id: 'd10b-f10', front: 'What does CFR+ change vs vanilla CFR?', back: 'Resets negative regrets to zero: $R^{T+1}(a) = \\\\max(R^T(a) + r^T(a), 0)$. Achieves $O(1/T)$ convergence vs $O(1/\\\\sqrt{T})$.', tags: ['cfr'] },
      { id: 'd10b-f11', front: 'How to measure abstraction quality?', back: 'Compute the exploitability of the abstracted strategy when played in the ORIGINAL (unabstracted) game. Low exploitability = good abstraction.', tags: ['abstraction'] },
      { id: 'd10b-f12', front: 'What is the Nash equilibrium spread in market making?', back: 'The tightest spread where expected profit from uninformed flow exactly offsets losses to informed flow (Glosten-Milgrom zero-profit condition as a game-theoretic equilibrium).', tags: ['market-making'] },
    ],
    cheatSheet: [
      { topic: 'Regret Matching', formula: 'σ^{T+1}(a) = R_+(a) / Σ R_+(a\')', description: 'Action probability proportional to positive cumulative regret' },
      { topic: 'Counterfactual Value', formula: 'v_i(σ,I) = Σ_h π_{-i}(h) Σ_z π(h,z) u_i(z)', description: 'Value weighted by opponents\' reach probability' },
      { topic: 'Average Strategy', formula: 'σ̄^T = (1/T) Σ σ^t → Nash as T→∞', description: 'Time-averaged strategy converges to Nash equilibrium' },
      { topic: 'Exploitability', formula: 'ε(σ) = Σ_i [max u_i(σ\'_i, σ_{-i}) - u_i(σ)]', description: 'Zero at Nash equilibrium; measures strategy quality' },
      { topic: 'CFR Convergence', formula: 'ε ≤ O(Δ√(|I|·|A|) / √T)', description: 'Vanilla CFR rate; CFR+ achieves O(1/T)' },
      { topic: 'Suit Isomorphism', formula: '1326 → 169 starting hands', description: 'Exploit suit symmetry to reduce game size' },
      { topic: 'Hand Equity', formula: 'Equity(h) = Σ 1[h > h\'] / |H_opp|', description: 'Fraction of opponent hands beaten at showdown' },
      { topic: 'Market Making Game', formula: 'Spread* = adverse selection cost / flow rate', description: 'Nash equilibrium spread balances informed vs uninformed flow' },
    ],
    summary: [
      'Leduc Poker (6 cards, ~936 info sets) is a tractable test bed for imperfect information game algorithms',
      'Card abstraction groups similar hands into buckets; suit isomorphism reduces Hold\\\'em hands from 1326 to 169',
      'CFR computes counterfactual regret at each info set and updates via regret matching: $\\\\sigma^{T+1}(a) = R^T_+(a) / \\\\sum R^T_+(a^{\\\\prime})$',
      'The TIME-AVERAGED strategy converges to Nash at $O(1/\\\\sqrt{T})$; CFR+ achieves $O(1/T)$ by resetting negative regrets',
      'Exploitability $\\\\varepsilon(\\\\sigma) = \\\\sum_i [\\\\max_{\\\\sigma^{\\\\prime}_i} u_i(\\\\sigma^{\\\\prime}_i, \\\\sigma_{-i}) - u_i(\\\\sigma)]$ measures distance from Nash',
      'Market making maps directly to imperfect information games: hidden trader types, bid-ask as strategy, adverse selection as the cost of being wrong',
    ],
    interactiveTools: [],
  },
};

export default day10;
